### ISSUE TITLE
`uv export` does not work if conflicting groups are defined

### ISSUE THREAD

**Issue by ghislainbourgeois** [astral-sh/uv#10000]
I have a project that requires a different version of a library based on the infrastructure we are testing against. I defined those dependencies in 2 different dependency groups and told `uv` that they conflict:

```
[project]
name = "tls-certificates-interface"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "cryptography",
    "jsonschema",
    "ops",
    "pydantic",
    "rpds-py==0.18.1"
]

[dependency-groups]
test = [
    "coverage[toml]",
    "pytest",
    "pytest-operator",
    "pytest-asyncio==0.21.2",
    "ops[testing]",
]
dev = [
    "codespell",
    "pyright",
    "ruff",
]
test-juju-2 = [
    "juju==2.9.49.0"
]
test-juju-3 = [
    "juju>3"
]

[tool.uv]
conflicts = [
    [
        { group = "test-juju-2" },
        { group = "test-juju-3" },
    ],
]
```

It works well for most of our workflows, but it fails when trying to run `uv export` to generate a `requirements.txt` file for another tool, with the error:

```
$ uv export --no-group test-juju-2 --no-group test-juju-3
Resolved 83 packages in 1ms
error: Cannot represent `uv.lock` with conflicting extras or groups as `requirements.txt`
```

I have tried many different switches to get uv to ignore those groups, as I do not need them in the requirements file, but found no way of making `uv export` work with those conflicts.

A workaround I found was to use this instead:

```
uv pip compile pyproject.toml -o requirements.txt
```

I manually validated the output against the `uv.lock` file and everything seemed to match, but I am not certain this is guaranteed when using the pip interface.

**Comment by charliermarsh** [comment]
I believe this was already fixed in more recent versions.

**Comment by ghislainbourgeois** [comment]
You are right, I just upgraded to the latest version and it works. Thank you, sorry for the noise!

**Comment by charliermarsh** [comment]
No problem, glad it was easy to resolve.
