### ISSUE TITLE
uv run as shebang hangs when script doesn't end with .py

### ISSUE THREAD

**Issue by simonpercivall** [astral-sh/uv#10003]
This may be a documentation clarification, or possible more informative output and error handling.

1. It's partially covered by the command reference, that scripts should end with `.py`, _however_ ….
2. It's a convenient and powerful way to create self-contained cli commands, to do a script with `#!/usr/bin/env uv run` with inline script metadata.
3. It works 
First, to explain what I mean.

```
> uv init --scrit my-command
> echo -e "#\!/usr/bin/env uv run\n$(cat my-command)" > my-command
> chmod +x my-command
> ./my-command
<hangs>
<Ctrl-C>
> uv run --script -q my-command
Hello from my-command!
>
```

**Comment by zanieb** [comment]
See https://github.com/astral-sh/uv/issues/6360

Let me know if you have more questions!
