### ISSUE TITLE
dependency module not found when added as local file path

### ISSUE THREAD

**Issue by straz** [astral-sh/uv#10006]
In `pyproject.toml`:

```
[project]
name = "myproject"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "my_base_project",
    "fastapi>=0.115",
    "httpx>=0.28",
    "networkx>=3.4.2",
    "pydantic>=2.10",
    "pyyaml>=6.0.2",
    "requests>=2.32",
    "uvicorn>=0.32.0",
]

[tool.uv.sources]
my_base_project = { path = "${PROJECT_ROOT}/../../../mybase/src/" }
```

When I run my app, the base dependency does not appear and cannot be loaded:
```
  % uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  ..
    from my_base_project.schemas import (
ModuleNotFoundError: No module named 'my_base_project'
```

According to `uv run --verbose`, it seems like `my_base_project` has been loaded as a requirement. But it does not appear anywhere in `sys.path`. Shouldn't I expect to be able to `import my_base_project`, and if so, from where?
```
% uv run --verbose uvicorn main:app
DEBUG Using request timeout of 30s
DEBUG Requirement already installed: my_base_project==0.1.0 (from file:///Users/straz/src/mybase/src)
DEBUG Requirement already installed: annotated-types==0.7.0
DEBUG Requirement already installed: anyio==4.7.0
DEBUG Requirement already installed: black==24.10.0
DEBUG Requirement already installed: cachetools==5.5.0
DEBUG Requirement already installed: certifi==2024.12.14
...
```

**Comment by charliermarsh** [comment]
I suspect something is wrong in how you setup `my_base_project`. It's not typical to point to a `src` directory like that.

**Comment by charliermarsh** [comment]
To help you, we would need to see a complete reproduction, such as a Git repository and a series of commands we can use to reproduce.

**Comment by nrydanov** [comment]
Same issue, but I add project directly via CLI like that: uv add --editable ../shared

Project is named inbrief-shared, but none of 
`import shared`
`import inbrief_shared` 
works

In `.venv/lib/python3.12/site-packages` I see that UV indeed does smth with that module. There's .pth file, for example. However, I can't see folder with .py files inside .venv as I do when open regular dependencies folders.

And I can't use this package in runtime...

**Comment by charliermarsh** [comment]
I suspect there's an issue with how your package is structured. I'd need a reproduction, like a Git repository, to help out.

**Comment by nrydanov** [comment]
Ok, will send soon.

**Comment by jannik4** [comment]
I am hitting the same problem, I think. I created a reproduction [here](https://github.com/jannik4/uv-local-dep).

**Comment by charliermarsh** [comment]
Yeah, if you don't have a build system, we won't build and install your project in the non-`uv pip` APIs.

Check out: https://docs.astral.sh/uv/concepts/projects/config/#build-systems.
