### ISSUE TITLE
`uv pip install --directory` not working when called with a Python subprocess

### ISSUE THREAD

**Issue by djalan** [astral-sh/uv#10013]
Hello

Sample repo? Yes! https://github.com/djalan/uv-pip-install-subprocess

Here is the problem:

As per your documentation @ https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments

> When running a command that mutates an environment such as `uv pip sync` or `uv pip install`, uv will search for a virtual environment in the following order:
> 
> - An activated virtual environment based on the VIRTUAL_ENV environment variable.
> - An activated Conda environment based on the CONDA_PREFIX environment variable.
> - A virtual environment at .venv in the current directory, or in the nearest parent directory.

This becomes a problem when you are calling `uv` using a `subprocess.Popen` from a Python project that is using a virtual env.

It won't take into consideration the `--directory` switch and changing `cwd` current working directory for `subprocess.Popen` does not resolve the issue.

```
Using Python 3.11.7 environment at: D:\workspace\project-running-subprocess\.venv
Audited 166 packages in 53ms
```

```python
print("Install dependencies with 'uv'")
with subprocess.Popen(
    [
        definitions.UV_EXE,
        "pip",
        "install",
        "--directory",
        clone_fullpath.absolute().as_posix(),
        "--no-progress",
        "--color",
        "never",
        "-r",
        requirements_path,
    ],
    stdout=subprocess.PIPE,
    bufsize=1,
    universal_newlines=True,
    cwd=clone_fullpath,
) as proc:
    for line in proc.stdout:
        print(line, end="")
```

On the other hand, `uv venv` honors the `--directory` switch and creates the .venv at the desired location.

```python
print("Create venv with 'uv'")
with subprocess.Popen(
    [
        definitions.UV_EXE,
        "venv",
        "--no-progress",
        "--color",
        "never",
        "--directory",
        clone_fullpath.absolute().as_posix(),
    ],
    stdout=subprocess.PIPE,
    bufsize=1,
    universal_newlines=True,
    cwd=clone_fullpath,
) as proc:
    for line in proc.stdout:
        print(line, end="")
```

I would fix the problem and amend the documentation and give `--directory` the biggest priority.

- The `--directory` switch on the command line
- An activated virtual environment based on the VIRTUAL_ENV environment variable.
- An activated Conda environment based on the CONDA_PREFIX environment variable.
- A virtual environment at .venv in the current directory, or in the nearest parent directory.

**Comment by zanieb** [comment]
I think you just want `uv pip install --python <path-to-venv>` instead of using `--directory`? Changing the working directory shouldn't change our Python discovery behavior, in my opinion. It should be the same as if you invoked uv from that directory.

**Comment by zanieb** [comment]
(Thank you for all the details and the reproduction!)

**Comment by djalan** [comment]
Hello

Your solution works! I pushed it to the repo.

Maybe consider adding `[PATH]` at the end of `uv pip install` just like `uv venv`.
That would replace the `--python` switch.

Right now it looks like this:

 Usage: `uv.exe venv [OPTIONS] [PATH]`

Usage: `uv.exe pip install [OPTIONS] <PACKAGE|--requirements <REQUIREMENTS>|--editable <EDITABLE>>`
