### ISSUE TITLE
Add `pip` Alias in UV-Managed Virtual Environments

### ISSUE THREAD

**Issue by mosmuell** [astral-sh/uv#10037]
Hello,

In my typical workflow, I create virtual environments using `poetry` or `venv` and activate them with `source .venv/bin/activate`. While I primarily rely on `poetry` for package management and tracking dependencies in `pyproject.toml`, I occasionally use `pip` for tasks like checking installed package versions or installing packages without tracking them in `pyproject.toml`.

Currently, this workflow isn’t possible with `uv` because virtual environments created by `uv` do not include `pip` by default. To address this, would it be possible to create an alias for `pip` that maps to `uv pip` within UV-managed virtual environments? This would ensure a seamless experience when using `pip` commands alongside `uv`.

Thank you for considering this feature request!

**Comment by FishAlchemist** [comment]
This is a rather old question (https://github.com/astral-sh/uv/issues/1657). Perhaps you could take a look at the discussion to see why uv didn't plan to do this in the past.
