### ISSUE TITLE
Package name changes: dot converts to hyphen

### ISSUE THREAD

**Issue by MrNaif2018** [astral-sh/uv#10061]
Hi! I know it might be due to package normalization rules, because I know for example underscores should be converted to hyphens
But this case is a bit new, so I wanted to ask:
```
$ uv add karrio.canadapost
Resolved 88 packages in 281ms
Installed 1 package in 2ms
 + karrio-canadapost==2023.9.2
```
Is it normal that it replaces dot with hyphen, and what if someone uploads a package with such name to pypi?
They define this package with a dot indeed, not sure how standard it is: https://github.com/karrioapi/karrio/blob/00aef3669dcbbe35ce18d199b247f9515956ecd7/modules/connectors/canadapost/setup.py#L7
Checking on pypi there is indeed no name with slash present, only with dot
But if I e.g. open https://pypi.org/project/email_validator/ it redirects to https://pypi.org/project/email-validator/

**Comment by zanieb** [comment]
Yes, this is the standard way to canonicalize package names per the specification.

**Comment by zanieb** [comment]
Related

- https://github.com/astral-sh/uv/issues/8902
- https://github.com/astral-sh/uv/issues/2006
