### ISSUE TITLE
uv pip cant locate the latest version. Only when I tell it `uv pip install <package> --upgrade` does it find the latest version.

### ISSUE THREAD

**Issue by freddyaboulton** [astral-sh/uv#10065]
Hi!

I am confused as to why `uv pip install gradio-webrtc==0.0.25` fails saying that version does not exist but `uv pip install --upgrade gradio-webrtc` finds version 0.0.25.

0.0.25 is a very recent version (~5 minutes old when I ran these two commands). I wouldn't be surprised if both commands failed to find 0.0.25 but I find it odd that only the first one fails.

<img width="442" alt="Image" src="https://github.com/user-attachments/assets/6c29af8e-a465-46cd-9283-62bd5c9ec7b4" />

**Comment by charliermarsh** [comment]
We cache PyPI metadata for 10 minutes, so running with `--upgrade` or `--refresh` is the best way to force a refresh.
