### ISSUE TITLE
Allow "uvx python" to execute Python like "uv run python"

### ISSUE THREAD

**Issue by ksamuel** [astral-sh/uv#10122]
Right now, if you run `uvx python`, it can fail. Even `uvx -p 3.11 python` will fail to start a Python shell on Windows or Ubuntu because the command doesn't map to a python executable.

However, `uv run python` [works](https://github.com/astral-sh/uv/issues/6348), no matter where you execute it.

It's counter-intuitive, one would expect you can run the installed you installed with uv from uvx. 

What's more, it would be a useful feature to be able to do `uvx -p 3.12 --with pendulum python` to test how this lib works in python 3.12 quickly.

Right now, one has to do  `uvx -p 3.12 --with pendulum ipython` which is fine if you are familiar with the Python ecosystem and `uv` limitations, but probably not for beginners, for whom `uv` is the biggest boon.

**Comment by FishAlchemist** [comment]
Are you in need of such a function
```
uvx -p 3.12 --from pendulum python
```
https://docs.astral.sh/uv/guides/tools/#commands-with-different-package-names
![Image](https://github.com/user-attachments/assets/e3fdef16-3823-4f48-9b36-5f175647da23)

**Comment by ksamuel** [comment]
Let's close it as a duplicate
