### ISSUE TITLE
Is it possible to use jfrog remote repository to install python

### ISSUE THREAD

**Issue by shireenrao** [astral-sh/uv#10134]
Is there a way to configure where python is getting installed from? It would be great if there was a way to tell uv to use a [jfrog artifactory remote repository](https://jfrog.com/help/r/jfrog-artifactory-documentation/remote-repositories) to install different versions of python similar to how one can set the index-url either in the pyproject.toml or uv.toml file for pip packages.

**Comment by zanieb** [comment]
There is [`UV_PYTHON_INSTALL_MIRROR`](https://docs.astral.sh/uv/reference/settings/#python-install-mirror)

**Comment by shireenrao** [comment]
That is exactly what I was looking for. Thank you. I will close the issue.
