### ISSUE TITLE
uv run script won't install required python version?

### ISSUE THREAD

**Issue by myarcana** [astral-sh/uv#10139]
I've made a script with metadata

```py
# /// script
# requires-python = "==3.9"
# ///
```

and when I run `uv run myscript.py`, I get an error

    error: No interpreter found for Python ==3.9 in virtual environments, managed installations, or search path

That's surprising; I would expect `uv` to install the required Python version automatically.

**Comment by FishAlchemist** [comment]
![Image](https://github.com/user-attachments/assets/1cc6aef9-0bbd-4adb-8cda-7711564a8056)
I cannot reproduce the issue you described on my Windows system. Could you provide the output with the ``--verbose`` flag?
```
uv run --verbose myscript.py 
```

If possible, please use the following command to provide UV setting information.
```
 uv run --show-settings
```

**Comment by charliermarsh** [comment]
(As an aside, you likely do _not_ want `requires-python = "==3.9"`. That requests exactly `3.9.0`, and no later patch versions. You're probably looking for `requires-python = ">=3.9"` or `requires-python = "==3.9.*"`.)

**Comment by charliermarsh** [comment]
I think @zanieb would know the details on intended behavior here.

**Comment by zanieb** [comment]
We don't have a managed download of `3.9.0` so we can't automatically download the requested version.

**Comment by zanieb** [comment]
Perhaps the canonical display of requests should add a trailing zero to these versions.

**Comment by charliermarsh** [comment]
Ahh ok yeah. It exists for Windows and Intel macOS, but not ARM.
