### ISSUE TITLE
uv sync does not respect UV_PROJECT_ENVIRONMENT

### ISSUE THREAD

**Issue by hongquan** [astral-sh/uv#10152]
I set `UV_PROJECT_ENVIRONMENT` environment variable to an absolute path (I want to have venv folder outside my project). Then I run `uv sync`, but it insists on creating `.venv` folder and install packages to this folder, instead of installing to the folder I provided via `UV_PROJECT_ENVIRONMENT`.

![Image](https://github.com/user-attachments/assets/42c2c2c7-e505-4f50-b9dd-22f040e7789b)

My environment:
- `uv` v0.5.1
- Shell: Fish v4.0b1
- OS: Ubuntu 24.04

**Comment by FishAlchemist** [comment]
![Image](https://github.com/user-attachments/assets/29ae1ba0-0f53-4ebe-b3ae-488e8f78aa79)
``echo $UV_PROJECT_ENVIRONMENT`` does not prove that you have set the environment variable.
Are you sure you've used ``export UV_PROJECT_ENVIRONMENT`` to make this environment variable accessible to child processes?

**Comment by hongquan** [comment]
@FishAlchemist Thanks, I forgot to export the variable.
