### ISSUE TITLE
`uv publish` raise error `Caused by: error decoding response body`

### ISSUE THREAD

**Issue by andrew000** [astral-sh/uv#10186]
Using `astral-sh/setup-uv@v5` and UV_VERSION `latest` or `0.5.12` causes error when publishing package: https://github.com/andrew000/FTL-Extract/actions/runs/12509313775/job/34898612613#step:8:12

Using UV_VERSION `0.5.11` works good:
https://github.com/andrew000/FTL-Extract/actions/runs/12509365391/job/34898720613

**Comment by Frazzer951** [comment]
I'm also getting the same error when trying to install a package through an AWS code-artifact. `0.5.12` fails while `0.5.11` works fine.

**Comment by charliermarsh** [comment]
Thank you. @andrew000 -- do you know if you intend to be using trusted publishing?

(@Frazzer951 -- I assume you mean _publishing_? Or are you seeing a different issue?)

**Comment by charliermarsh** [comment]
It looks like this might be due to a change in `reqwest`. I will likely revert and publish a new version: https://github.com/seanmonstar/reqwest/commit/d36c0f5fd93f8190c9f39990ce4ec859c2b6d567

**Comment by Frazzer951** [comment]
@charliermarsh Mine occurs when doing a `uv pip install`
```sh
> uv pip install -e ".[dev]" --index-url https://<<AWS CodeArtifact Url>>
Using Python 3.11.9 environment at: /Users/luke/.pyenv/versions/3.11.9/envs/analytics
  × Failed to build `pipeline @ file:///Users/luke/Sonarverse/analytics`
  ├─▶ Failed to resolve requirements from `build-system.requires`
  ├─▶ No solution found when resolving: `setuptools`
  ├─▶ Failed to fetch: `https://<<AWS CodeArtifact Url>>/setuptools/`
  ├─▶ error decoding response body
  ╰─▶ there are extra bytes after body has been decompressed
```

**Comment by charliermarsh** [comment]
Got it, thanks. I'll go ahead and revert!
