### ISSUE TITLE
python-install-mirror in uv.toml

### ISSUE THREAD

**Issue by andreas-vester** [astral-sh/uv#10192]
I am getting an error when configuring ``python-install-mirror`` in ``uv.toml`` rather than an environment variable.

```toml
[[python-install-mirror]]
url = "file://c:/tmp"
```

Opening a Windows Powershell, this will give me the following error:
``FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.Powershell.Commands.InvokeExpressionCommand``

Using bash is basically the same error:
``invalid type: sequence, expected a string``

```bash
uv --version
uv 0.5.12 (351d602d8 2024-12-26)
```

**Comment by FishAlchemist** [comment]
I think you might have set it up incorrectly.
https://docs.astral.sh/uv/reference/settings/#python-install-mirror

**Comment by andreas-vester** [comment]
You're right. Thanks for pointing me in the right direction!
