### ISSUE TITLE
`error decoding response body` when resolving dependencies from aws codeartifact repo since 0.5.12

### ISSUE THREAD

**Issue by okan-agca-entrix** [astral-sh/uv#10190]
Hello,
I'm encountering a new error since upgrading to `0.5.12` while running `uv sync`. The setup is described below. The error is not present with version `0.5.11` of uv. If there are migration steps I missed, would be happy if you can direct me there. Had a brief look at the release notes but didn't see anything relevant.

Error Message from Github Actions:
```
Using CPython 3.12.8 interpreter at: /opt/hostedtoolcache/Python/3.12.8/x64/bin/python3
Creating virtual environment at: .venv
error: Failed to generate package metadata for `*****`
  Caused by: Failed to resolve requirements from `build-system.requires`
  Caused by: No solution found when resolving: `hatchling`, `hatch-vcs`
  Caused by: Failed to fetch: `https://***-***.d.codeartifact.eu-west-1.amazonaws.com/pypi/***/simple/hatchling/`
  Caused by: error decoding response body
  Caused by: there are extra bytes after body has been decompressed
Error: Process completed with exit code 2.
```

Setup:
The code artifact url is setup in the pyproject toml
```[[tool.uv.index]]
name = "aws-code"
url = "https://***-***.d.codeartifact.eu-west-1.amazonaws.com/pypi/***/simple/"
```
The credentials are setup as environment variables as documented here: https://docs.astral.sh/uv/guides/integration/alternative-indexes/#aws-codeartifact

**Comment by kyriakost** [comment]
Can verify the error

**Comment by thiago-pythonic** [comment]
Error happens with Gitlab package registry:

```
Using Python 3.8.10 environment at: virtualenvs/***
error: Failed to fetch: `https://gitlab.com/api/v4/groups/***/-/packages/pypi/simple/***/`
  Caused by: error decoding response body
  Caused by: there are extra bytes after body has been decompressed
```

**Comment by charliermarsh** [comment]
Sorry -- this is a bug in `reqwests` that I fixed last night (#10187), but didn't realize that the subsequent release failed. I'll get it out now.

**Comment by olafdeleeuw** [comment]
No problem. Thanks!

**Comment by charliermarsh** [comment]
This should be fixed in v0.5.13.

If you're on v0.5.12, you may need to reinstall with cURL rather than via `uv self update`:

```shell
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Sorry for the inconvenience! It's my mistake for going to bed without double-checking the release pipeline.

**Comment by thiago-pythonic** [comment]
Thanks for the quick turnaround! 0.5.13 works just fine!

**Comment by olafdeleeuw** [comment]
Thanks! Also with Azure Artifacts. Everything works fine again with 0.5.13.

**Comment by flipdazed** [comment]
out of interest is there any way you can maintain previous versions in `homebrew` just in case there is a problem like this again? This caused us a bit of havoc because `brew` doesn't maintain any old versions

**Comment by charliermarsh** [comment]
Hmm, I think that's ultimately up to Homebrew, since I didn't do anything specific to have it _not_ publish to Homebrew. It's possible that the releases were just too close together, and so Homebrew never built and uploaded 0.5.12?
