### ISSUE TITLE
[error] `uv self update` does not work from `v0.5.12` to `v0.5.13`

### ISSUE THREAD

**Issue by lamteteeow** [astral-sh/uv#10196]
```
$ uv self update
error: error decoding response body
  Caused by: there are extra bytes after body has been decompressed
```

I am on version: `uv 0.5.12 (351d602d8 2024-12-26)`
Windows 11 23H2
Update from `v0.5.11` to `v0.5.12` went fine.

**Comment by jdmartin** [comment]
Having this same issue on macOS.  I am currently using `uv 0.5.12 (351d602d8 2024-12-26)`.

```
uv self update
info: Checking for updates...
error: error decoding response body
  Caused by: there are extra bytes after body has been decompressed
```

**Comment by anotherbugmaster** [comment]
Same, but with `uv pip install`:

```
Using Python 3.11.0rc1 environment at: /databricks/python3
error: Failed to fetch: `https://<private_domain>/pypi/<repo_name>/simple/<package_name>/`
  Caused by: error decoding response body
  Caused by: there are extra bytes after body has been decompressed
```

Downgrading to `0.5.11` has resolved the issue

**Comment by charliermarsh** [comment]
👍 This was a known issue in v0.5.12 due to a `reqwests` update. Sorry about that. I suggest re-installing with cURL (e.g., `curl -LsSf https://astral.sh/uv/install.sh | sh`). Subsequent self-updates should work without issue.

**Comment by FishAlchemist** [comment]
@charliermarsh Given that version 0.5.12 is unable to network, would you like to proceed with yanking it from PyPI?

**Comment by lamteteeow** [comment]
> 👍 This was a known issue in v0.5.12 due to a `reqwests` update. Sorry about that. I suggest re-installing with cURL (e.g., `curl -LsSf https://astral.sh/uv/install.sh | sh`). Subsequent self-updates should work without issue.

That solved the issue quickly! Thank you for being swift and engaged.
