### ISSUE TITLE
Update failure on Win10 64-bit

### ISSUE THREAD

**Issue by farzbood** [astral-sh/uv#10213]
Hi everyone,
Attempting update with (uv self update) command to the latest version (0.5.13), failed with following error.

PS C:\Windows\system32> uv self update
info: Checking for updates...
error: error decoding response body
  Caused by: there are extra bytes after body has been decompressed

O.S: windows 10 x86-64

**Comment by FishAlchemist** [comment]
UV's version 0.5.12, right? The self-update for this version is broken. Please refer to the comment(https://github.com/astral-sh/uv/issues/10196#issuecomment-2563857968) for the fix.

**Comment by charliermarsh** [comment]
👍 There was an issue in v0.5.12. To upgrade, I recommend re-running the installer:

```
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

Subsequent self-updates should work as expected.
