### ISSUE TITLE
`uv export` does not include workspace packages

### ISSUE THREAD

**Issue by brownj85** [astral-sh/uv#10216]
UV version: `0.5.13`

I'm trying to switch Poetry to UV, and I've encountered a difference in behaviour between `poetry export` and `uv export`. I have a project laid out like this:

```
.
├── apps
│   ├── lib-1
│   │   ├── README.md
│   │   ├── hello.py
│   │   ├── pyproject.toml
│   │   └── uv.lock
│   └── lib-2
│       ├── README.md
│       ├── hello.py
│       └── pyproject.toml
├── pyproject.toml
└── uv.lock
```

With `lib-1` and `lib-2` listed as dependencies in the root `pyproject.toml`:
```
[project]
name = "uv-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lib-1",
    "lib-2",
]

[tool.uv.workspace]
members = ["apps/lib-1", "apps/lib-2"]

[tool.uv.sources]
lib-1 = { workspace = true }
lib-2 = { workspace = true }
```

With a similar layout, `poetry export` will include the sub-packages as path dependencies in the generated requirements file.  I have a Docker workflow that uses this to install packages into a directory using `pip install --target`. However, `uv export` does not do this, it only includes the dependencies of the workspace members.

I'm not sure if this is intended behaviour - the documentation for [--no-emit-workspace](https://docs.astral.sh/uv/reference/cli/#uv-export) seems to imply that the workspace packages themselves should be included, not just the dependencies.

**Comment by charliermarsh** [comment]
Do your packages have build systems defined? Otherwise, they're considered virtual: https://docs.astral.sh/uv/concepts/projects/config/#build-systems
