### ISSUE TITLE
Add support for manylinux2014_x86_64 and manylinux2014_aarch64

### ISSUE THREAD

**Issue by Pixel-Minions** [astral-sh/uv#10210]
Hi,

I am currently working with lambdas in AWS and deploying some layers using UV, but sadly, it doesnt support `manylinux2014_x86_64` and `manylinux2014_aarch64`, it is possible to add them?

Thank you for the amazing project.

Best,

**Comment by charliermarsh** [comment]
I believe we do support these targets. What issue are you seeing exactly?

**Comment by Pixel-Minions** [comment]
Hi @charliermarsh, it is not supported, please take a look:

![Image](https://github.com/user-attachments/assets/19be44aa-898d-4042-af31-a99a99f3f9a9)

**Comment by shauneccles** [comment]
What happens if you drop the --python-platform and allow uv to try and determine the platform to install?

**Comment by charliermarsh** [comment]
You want `x86_64-manylinux_2_17`. That's equivalent to `manylinux2014`.

**Comment by charliermarsh** [comment]
I guess we can add aliases for those.

**Comment by Pixel-Minions** [comment]
> What happens if you drop the --python-platform and allow uv to try and determine the platform to install?

I am building from windows, zipping and sending to aws for thr lambda layer.

**Comment by Pixel-Minions** [comment]
> You want `x86_64-manylinux_2_17`. That's equivalent to `manylinux2014`.

That is great, thank you for letting me know, and yes maybe a alias would help to make it clear without having to dig deeper.

**Comment by Pixel-Minions** [comment]
Fantastic, thank you @charliermarsh
