### ISSUE TITLE
@ registry+https://pypi.org/simple` can't be installed because it doesn't have a source distribution or wheel for the current platform

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#10236]
##  however  , When I use  python 3.12  , this error  is    disappeared and lost

**Comment by SauravMaheshkar** [comment]
I encountered the same error. The full actions log can be found [here](https://github.com/SauravMaheshkar/idefics-nnx/actions/runs/12546153305/job/34981501048)

**Comment by charliermarsh** [comment]
This is correct. There are no Python 3.13 wheels for Torch on macOS or Windows.

**Comment by charliermarsh** [comment]
See: https://pypi.org/project/torch/2.5.1/#files.
