### ISSUE TITLE
The program cannot write to the clipboard in a PySide6 project.

### ISSUE THREAD

**Issue by vichbb** [astral-sh/uv#10235]
```python
    def copy(self, text):
        clipboard = QApplication.clipboard()
        clipboard.setText(text)
```
I'm working on a Pyside6 project, and I found that on MacBook M4, this python can't write to the clipboard without any errors, but the python installed by brew can write to the clipboard without any errors，tried pbcopy also doesn't work。

**Comment by charliermarsh** [comment]
My guess is that this is a python-build-standalone quirk and can be merged into https://github.com/astral-sh/python-build-standalone/issues/274.
