### ISSUE TITLE
Missing `latest` tag for uv distroful images

### ISSUE THREAD

**Issue by garysassano** [astral-sh/uv#10230]
The `latest` tag is only available for the `ghcr.io/astral-sh/uv:latest` distroless image.

The following image is valid: `ghcr.io/astral-sh/uv:0.5.13-python3.13-bookworm-slim`
The following image is invalid: `ghcr.io/astral-sh/uv:latest-python3.13-bookworm-slim`

You have no way to pull a specific distroful image with the latest uv binary.

**Comment by zanieb** [comment]
Thanks for the report, looking into this.

**Comment by zanieb** [comment]
Ah I thought you meant this was a regression, but this is as intended.

You don't need the `latest-` tag, you can just use `ghcr.io/astral-sh/uv:python3.13-bookworm-slim` to get the latest version. `latest` just exists for an image that would otherwise have no tag.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Docker image tagging strategy to include 'latest' tags for distrofull images. This change allows users to pull specific distrofull images with the latest uv binary using the 'latest' tag.

You can review changes in this commit: https://github.com/mark-addams001881/astral-sh-uv-10230/commit/f0044607c8cb0595701d3c5408a3f758990b1e9f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by garysassano** [comment]
How could I set the `latest` version as the default, but allow people to override it with a specific `UV_VERSION`?

```Dockerfile
ARG PYTHON_VERSION=3.13
ARG UV_VERSION=""
FROM ghcr.io/astral-sh/uv:${UV_VERSION}-python${PYTHON_VERSION}-bookworm-slim
```

**Comment by garysassano** [comment]
Ok, I was able to figure out how to set `latest` when no `UV_VERSION` is passed as a build argument.

```Dockerfile
ARG PYTHON_VERSION=3.13
ARG UV_VERSION=""
FROM ghcr.io/astral-sh/uv:${UV_VERSION:+${UV_VERSION}-}python${PYTHON_VERSION}-bookworm-slim
```
