### ISSUE TITLE
How to include non-python files

### ISSUE THREAD

**Issue by huyndao** [astral-sh/uv#10254]
Apologies if this has been posted somewhere but I could not find in the documentation or from search the issues.

I am using uv to try to package an ML model along dependencies, I'd like to include some model weights in the form of safetensors into the package however could not find the relevant option or syntax, either from command line or to add to pyproject.toml.

I was wondering if someone could help point me to the right direction.  Ideally I'd prefer to use one suite / everything uv to create instead of jumping to another set of tools.

Thank you.

**Comment by FishAlchemist** [comment]
``uv build`` relies on the ``build system`` you specify, so you should refer to the documentation of the ``build system`` you are using.
uv's ``build system``, ``build backend``, is still in preview mode, if I'm not mistaken.

**Comment by huyndao** [comment]
Thank you, @FishAlchemist .  That is helpful.
