### ISSUE TITLE
Restore Git progress bars

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#1120]
Cargo has these. I disabled them because it requires threading down our printer abstraction.

**Comment by zanieb** [comment]
@ibraheemdev I presume these are not included now that we're using the git CLI? Is it even possible anymore?

**Comment by ibraheemdev** [comment]
We could possibly stream the git CLI output and convert it to our own progress bars, but that doesn't seem very stable. We could also monitor the size of the `.git` directory, though I'm not sure we be able to get a size estimate.

**Comment by zanieb** [comment]
Let's just close this for now, though it seems fair to want to see some sort of git output eventually.
