### ISSUE TITLE
Windows trampoline that works on stable rust

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1126]
Our current windows launcher require nightly rust and a lot of unsafe just to avoid panics. Puffin on the other hand works on stable rust and doesn't use any unsafe. It would be great to have a stable rust mostly-safe trampoline, even if the resulting binaries are slightly larger.

**Comment by konstin** [comment]
See #1126

**Comment by charliermarsh** [comment]
@konstin - I think you linked to the wrong issue.
