### ISSUE TITLE
Write a "pip tools for newbies" guide

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1165]
We should add some explanations what a virtualenv is, why you need it (and why not to install in any of the global envs) and how to activate it (or why you sometimes don't need to), what those `.in` and `.txt` files are and how to use them, why there's no pip in our virtualenvs, etc.

See e.g. https://github.com/PyO3/maturin#python-packaging-basics

**Comment by konstin** [comment]
We have our own uv interface (in preview) now

**Comment by zanieb** [comment]
And actually I'm writing these things in #4426
