### ISSUE TITLE
Adjust concurrent task limits

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1205]
We set limits to the number of concurrent tasks in a number of places. We should revisit them and decide whether these number are good. Increasing them may speed up puffin, but setting them too high may also lead to losses due to synchronization or problems for registries such as pypi 

```
$ rg buffer_unordered
crates/puffin-dev/src/resolve_many.rs
132:        .buffer_unordered(args.num_tasks);

crates/puffin-dev/src/install_many.rs
171:        .buffer_unordered(50)

crates/puffin-resolver/src/finder.rs
102:            .buffer_unordered(32)

crates/puffin-installer/src/downloader.rs
82:            .buffer_unordered(50)
136:            .buffer_unordered(50);

crates/puffin-resolver/src/resolver/mod.rs
730:            .buffer_unordered(50);
```

**Comment by ibraheemdev** [comment]
Resolved by https://github.com/astral-sh/uv/pull/3493 and https://github.com/astral-sh/uv/pull/3646.
