### ISSUE TITLE
Show progress bar for slow downloads

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1209]
With fast internet and mainly small or cached packages, you barely even see the download spinner, but when e.g. trying to download torch on bad internet there is no indication how long this task is going to take or whether it got stuck.

**Comment by telamonian** [comment]
Yah, progress bars is one area in which the base `pip` has massively improved in recent years. It would be nice to have similar output by default in `uv` as well.

**Comment by detrin** [comment]
Ah I am so glad this was added.
