### ISSUE TITLE
Allow `uv venv ${dir}` for empty (not existing) directories

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#1274]

**Comment by zanieb** [comment]
We delete existing directories right now, right? Should we not?

**Comment by charliermarsh** [comment]
Ah this got fixed. The issue was that we were erroring if you tried to create a venv and the directory already existed (but was empty).

(We delete existing directories _if_ they're virtualenvs. We error if the env exists but isn't a virtualenv.)
