### ISSUE TITLE
Installing Python versions in Windows is slow

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1286]
Bootstrapping Python versions takes 1m longer in Windows than Linux (https://github.com/astral-sh/puffin/actions/runs/7876443402/job/21490474470) ~4x slower.

**Comment by zanieb** [comment]
This is really annoying me. If anyone is interested I'd appreciate help!

**Comment by konstin** [comment]
It's 50s on my windows desktop, which 100Mbit/s internet.
