### ISSUE TITLE
Consider changing wording around "novel" features

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1288]
The README includes a note about novel features; we should verify these features are not available for other Python package managers and reconsider the wording.

_Originally posted by @zanieb in https://github.com/astral-sh/puffin/pull/1265#discussion_r1486706975_

**Comment by pawamoy** [comment]
> Novel features such as [dependency version overrides](https://github.com/astral-sh/uv#dependency-overrides) and [alternative resolution strategies](https://github.com/astral-sh/uv#resolution-strategy)

Indeed, both features are supported by PDM:

- https://pdm-project.org/latest/usage/config/#override-the-resolved-package-versions
- https://pdm-project.org/latest/usage/dependency/#lock-strategies

**Comment by charliermarsh** [comment]
Awesome, thank you! We'll revise. We did look around but not sure how we missed that.

**Comment by charliermarsh** [comment]
This was removed!
