### ISSUE TITLE
Allow `pip compile` to work with stdin

### ISSUE THREAD

**Issue by mitsuhiko** [astral-sh/uv#1313]
Currently you cannot compile a requirements.txt file from stdin. Only `/dev/stdin` works, but that's not portable. It would be nice if `-` could be used to imply stdin to match behavior with `pip-tools`.

**Comment by danielhollas** [comment]
It looks like this feature is currently not documented.

**Comment by danielhollas** [comment]
Apologies, I did not realize there is a difference between `-h` and `--help`! :exploding_head: It is indeed documented in the full help output.
