### ISSUE TITLE
`uv venv` does not suggest how to activate

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1326]
```
❯ uv venv
Using Python 3.11.7 interpreter at /opt/homebrew/opt/python@3.11/bin/python3.11
Creating virtualenv at: .venv

❯ source .venv/bin/activate
```

We should prompt activation

**Comment by 0v00** [comment]
For prompting activation, would it be sufficient to add the following block to `crates/uv/src/commands/venv.rs` inside of `venv_impl`?

```rust
    writeln!(
        printer,
        "Activate virtualenv: source {}/bin/activate",
        path.normalized_display().cyan()
    )
    .into_diagnostic()?;
```

Happy to make a small PR/update tests if so.

**Comment by zanieb** [comment]
I think so! Maybe styled like "Activate with `source ....`"?

**Comment by zanieb** [comment]
Note we also need a separate hint to Windows users
