### ISSUE TITLE
Add hint that seed packages are being installed during `uv venv --seed`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1329]
```
❯ uv venv --seed
Using Python 3.11.7 interpreter at /opt/homebrew/opt/python@3.11/bin/python3.11
Creating virtualenv at: .venv
 + setuptools==69.1.0
 + pip==24.0
 + wheel==0.42.0
```

Should we suggest that we're seeding the environment?

**Comment by Peiffap** [comment]
Somewhat unrelated: is this flag still being maintained?

```zsh
% uv venv --seed
Using Python 3.12.3 interpreter at: /usr/local/opt/python@3.12/bin/python3.12
Creating virtualenv at: .venv
 + pip==24.1.1
Activate with: source .venv/bin/activate
```

Fyi, `uv venv --help` still mentions
```
[...]
      --seed
          Install seed packages (`pip`, `setuptools`, and `wheel`) into the virtual environment
[...]
```

**Comment by zanieb** [comment]
Yes the flag is being maintained — those other packages are not seeded in Python 3.12+ (this is a change upstream e.g. https://virtualenv.pypa.io/en/latest/user_guide.html#seeders)

**Comment by Peiffap** [comment]
Ah yes, I see now.

https://github.com/astral-sh/uv/blob/cb580d1a5d04525ef066ee0f8e90b74b2ce852c5/crates/uv/src/commands/venv.rs#L248-L260

Would a PR clarifying this change in the docs be welcome? I could add the hint about seeding too while I'm there.

**Comment by zanieb** [comment]
@Peiffap yeah that'd be great!
