### ISSUE TITLE
Support for shorter --python-version=3.7 argument: --3.7 or --python=3.7

### ISSUE THREAD

**Issue by 2-5** [astral-sh/uv#1336]
I often create venvs for multiple Python versions, `--python-version=3.7` is just too long, consider (additional) shorter options:

```shell
--3.7
--py=3.7
--python=3.7
```

**Comment by zanieb** [comment]
I don't think we'll support `--3.7` as that's ambiguous, but we could add a shorter flag for the version.

**Comment by dhruvmanila** [comment]
`--python` seems reasonable, it's also being used by [`pipenv`](https://github.com/pypa/pipenv#usage).

**Comment by zanieb** [comment]
We'll need to be careful that the flag makes sense with #1396

**Comment by charliermarsh** [comment]
Most commands support `-p` which I think is fine.
