### ISSUE TITLE
`uv venv` cannot find python in PATH, but it's in PATH

### ISSUE THREAD

**Issue by jojeyh** [astral-sh/uv#1337]
Downloaded `uv` using `curl` to play around

Ran
```
mkdir testing && cd testing
uv venv
```

`uv` outputs 
```
  × Neither `python` nor `python3` are in `PATH`. Is Python installed?
```

But python3 is definitely within my PATH variable?  Is this a bug?

I'm running Ubuntu 22.04.3 LTS 64-bit.

**Comment by jojeyh** [comment]
Oops just realized this is a copy of #1335

**Comment by zanieb** [comment]
Thanks for the report! Closing in favor of #1335 but I'll be looking into this immediately.

**Comment by angelhdzmultimedia** [comment]
Windows 11. PowerShell Core 7. uv installed with `irm https://astral.sh/uv/install.ps1 | iex`. Any info will be appreciated.

![Code_O7SLwxeA7z](https://github.com/astral-sh/uv/assets/10191085/e4429027-5b3f-4e18-b85a-138e6be02df3)
