### ISSUE TITLE
Issue installing HTML-escaped local version

### ISSUE THREAD

**Issue by stefanvanburen** [astral-sh/uv#1338]
Hey! `uv` looks great; nice work. Not sure if this issue is on my end or yours:

```
$ uv pip install connectrpc-eliza-grpc-python --extra-index-url https://buf.build/gen/python
error: Received some unexpected HTML from https://buf.build/gen/python/connectrpc-eliza-grpc-python
  Caused by: Unexpected fragment (expected `#sha256=...`) on URL: 43;edc8ae343b96-py3-none-any.whl
```

I'm _assuming_ this is because we're serving local versions with a `+` delimiter, which is then URL-escaped. The HTML looks something like:

```
    <a
      href="https://buf.build/gen/python/connectrpc-eliza-grpc-python/connectrpc_eliza_grpc_python-1.61.0.1.20230913231627&#43;233fca715f49-py3-none-any.whl"
      data-requires-python="&gt;=3.7"
      >connectrpc_eliza_grpc_python-1.61.0.1.20230913231627&#43;233fca715f49-py3-none-any.whl</a>
```

I haven't seen this as an issue with `pip`; it seems like something our repository should fix, but thought I'd mention in case the parsing should handle these escaped values.

**Comment by charliermarsh** [comment]
Thanks, I'll take a look!

**Comment by davidszotten** [comment]
i'm running devpi and don't have fragments at all which results in

```
 uv pip install --extra-index-url <devpi> <package>
error: Received some unexpected HTML from <devpi>/<package>
  Caused by: Unexpected fragment (expected `#sha256=...`) on URL:
```

(not truncated, there is nothing after `URL:`)

**Comment by charliermarsh** [comment]
Thanks! That should be an easy fix.

**Comment by davidszotten** [comment]
happy to give it a go if you have some pointers?

**Comment by charliermarsh** [comment]
@davidszotten - I haven't tried it yet, but I'd start in `crates/uv-client/src/html.rs` which has a `parse_hash`. I think the SHA256 _used_ to be required but we relaxed it and didn't update that code.

**Comment by charliermarsh** [comment]
@davidszotten - I moved that out to a separate issue: https://github.com/astral-sh/uv/issues/1441
