### ISSUE TITLE
`uv pip install "apache-airflow[all]"` fails to install the required extras

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#1342]
Hi all, just found out about this project, I've done a lot of work to test and improve real world resolution performance for Pip and done a lot of testing against [Rip](https://github.com/prefix-dev/rip).

I'm very excited to also test `uv`, especially with it's very interesting resolution options!

My first most common test to check any new resolution library is to try `apache-airflow[all]`, when I run (on Linux CPython 3.10):

```
pip install "apache-airflow[all]"
```

I get 428 packages installed, but when I run:

```
uv pip install "apache-airflow[all]"
```

I get 139 packages installed, is uv currently ignoring extras?

**Comment by charliermarsh** [comment]
It shouldn't be, no! Extras are definitely supported and we have a bunch of test coverage for it. Lemme look into this.

**Comment by zanieb** [comment]
Thanks for the report! It looks like you found a hole in our test scenarios.

I've reproduced this in https://github.com/astral-sh/uv/pull/1352

We don't support recursive extras at this time, but will asap!
