### ISSUE TITLE
Feature request: `--dry-run` or something similiar for uv pip install 

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#1348]
I would like to test uv's ability to correctly resolve requirements, and in general it it sometimes useful to know how a package installer will install some requirements without actually installing them. An alternative to this would be `uv pip download` which is something I used to use a lot before `--dry-run` existed in Pip.

At the moment I am rebuilding my virtual environment each time. Maybe I am missing something and there is a supported workflow already?

**Comment by charliermarsh** [comment]
Have you tried `uv pip compile`?

**Comment by charliermarsh** [comment]
It can also read from stdin, e.g. `echo "black" | uv pip compile -`.

**Comment by notatallshaw** [comment]
Yes, this is sufficent for my purpose, thanks!

**Comment by zanieb** [comment]
See also #1244
