### ISSUE TITLE
Including another file with `-r other.txt` should resolve relative to the containing file

### ISSUE THREAD

**Issue by carta-luc-ritchie** [astral-sh/uv#1367]
We have a dev requirements file `lib/requirements/dev.txt` that starts with this:

```dev.txt
-r requirements.txt
-r ../client/requirements/requirements.txt
-r ../interfaces/requirements/requirements.txt
```

Relative to the repo root, the mentioned files are at `lib/requirements/requirements.txt`, `lib/client/requirements/requirements.txt`, and `lib/interfaces/requirements/requirements.txt`. We invoke pip with `pip install -r /full/path/to/repo/lib/requirements/dev.txt`, and it's able to find and recursively include these files. If we invoke `uv pip install` the same way, it fails with

```
error: Error parsing included file in `/full/path/to/repo/lib/requirements/dev.txt` at position 0
  Caused by: failed to open file `/full/path/to/repo/requirements.txt`
  Caused by: No such file or directory (os error 2)
```

If I change directory, it becomes clear that the file is being resolved relative to the current working directory, whereas pip resolves it relative to the file containing the `-r` instruction.

**Comment by zanieb** [comment]
Thanks for the report! I agree.

**Comment by charliermarsh** [comment]
I need to do a bit of research on this -- I can't quite remember why we did it this way, but I thought it was intentional. Will take a look!

**Comment by edwardpeek-crown** [comment]
Note that pip-compile also matches pip behaviour, resolving relative to the file defining the path.

**Comment by charliermarsh** [comment]
Okay, I think the reason I was confused is that relative directories (like `-e ../..`) are interpreted relative to the current working directory. But it looks like requirements and constraints files are interpreted relative to the containing file.

https://github.com/pypa/pip/issues/8765

**Comment by charliermarsh** [comment]
Will fix tonight.
