### ISSUE TITLE
HTTP 401 Unauthorized for private package index

### ISSUE THREAD

**Issue by exs-avianello** [astral-sh/uv#1371]
Hello! Very excited for this project ❤️ 

Installing a package from a private azure package index (Azure Artifacts) seems to be failing with a `HTTP status client error (405 Method Not Allowed)`:

```
uv pip install --extra-index-url "https://<FEED_NAME>:<PERSONAL_ACCESS_TOKEN>@pkgs.dev.azure.com/<ORGANIZATION_NAME>/_packaging/<FEED_NAME>/pypi/simple/" package-name                                          
error: Failed to download: package-name==X.Y.Z
  Caused by: HTTP status client error (405 Method Not Allowed) for url (pkgs.dev.azure.com/<ORGANIZATION_NAME>/_packaging/.../pypi/download/package-name/X.Y.Z/package_name-X.Y.Z-py3-none-any.whl#[sha256=])
````

The equivalent pip-native command works as expected
```
python -m pip install --extra-index-url "https://<FEED_NAME>:<PERSONAL_ACCESS_TOKEN>@pkgs.dev.azure.com/<ORGANIZATION_NAME>/_packaging/<FEED_NAME>/pypi/simple/" package-name
```

**Comment by charliermarsh** [comment]
Thank you! Will take a look.

**Comment by yogevyuval** [comment]
Same here - Really want to test (and replace pip with) uv but waiting for Azure artifacts support :( !

**Comment by zanieb** [comment]
Yep this is a priority for me next week!

**Comment by MarcSkovMadsen** [comment]
+1. Same issue for me.

**Comment by charliermarsh** [comment]
I believe this is the same as https://github.com/astral-sh/uv/issues/1458 (lack of support for HEAD requests).

**Comment by charliermarsh** [comment]
Okay, @olivierlefloch fixed HEAD requests, but there's now an auth problem. @zanieb, do you want to take from here?

**Comment by exs-avianello** [comment]
Thank you all! 

I can confirm that on `uv 0.1.6` this is no longer giving `405 Method Not Allowed` but a `401 Unauthorized`

```
uv pip install --extra-index-url "https://<FEED_NAME>:<PERSONAL_ACCESS_TOKEN>@pkgs.dev.azure.com/<ORGANIZATION_NAME>/_packaging/<FEED_NAME>/pypi/simple/" package-name                                          
error: Failed to download: package-name==X.Y.Z
  Caused by: HTTP status client error (401 Unauthorized) for url (pkgs.dev.azure.com/<ORGANIZATION_NAME>/_packaging/.../pypi/download/package-name/X.Y.Z/package_name-X.Y.Z-py3-none-any.whl#[sha256=])
```

**Comment by gwdekker** [comment]
Same for gitlab hosted private package index: getting a 401 Unauthorized.

**Comment by zanieb** [comment]
Hi! We just merged a fix with #1874 that's out in v0.1.8 — let me know if that helps. I'll continue testing against various private repositories.

**Comment by yogevyuval** [comment]
Same here, `401 Unauthorized` for Azure Artifacts with uv `0.1.8`

**Comment by zanieb** [comment]
For my own sanity, this is also being tracked in https://github.com/astral-sh/uv/issues/1709

**Comment by zanieb** [comment]
A fix is up at https://github.com/astral-sh/uv/pull/1886 if anyone wants to give it a try against a private index.

**Comment by inigohidalgo** [comment]
Verified working on azure artifacts feed using token authentication!!

Incredible work @zanieb, @olivierlefloch and @charliermarsh 🚀

**Comment by exs-avianello** [comment]
I can confirm as well ❤️ Thank you so much!
