### ISSUE TITLE
`uv pip install filename.whl` is not supported

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#1372]
If you have a wheel file floating around, pip gives you a way to install it. Is there a way to do this in uv?

Context: we have some custom packaging code at work, currently in some cases we end up doing `pip install --no-deps firstparty1.whl firstparty2.whl firstparty3.whl` and it would be nice for this to be much faster than it is with pip

**Comment by zanieb** [comment]
Yes this is possible, you need to provide a name for the packages though

```
❯ python3.12 -m packse build-pkg example 0.1.0 --rm
Generated project for 'example-0.1.0'in 5.43ms
Built package 'example-0.1.0' in 0.20s
Linked distribution to dist/example/example-0.1.0-py3-none-any.whl
Linked distribution to dist/example/example-0.1.0.tar.gz
Done in 203.84ms

❯ uv pip install example@./dist/example/example-0.1.0-py3-none-any.whl
Resolved 1 package in 8ms
Downloaded 1 package in 3ms
Installed 1 package in 1ms
 + example==0.1.0 (from file:///Users/mz/eng/src/astral-sh/uv/dist/example/example-0.1.0-py3-none-any.whl)

```

**Comment by hauntsaninja** [comment]
Thank you! Yeah I tried to guess that but then got the error in https://github.com/astral-sh/uv/issues/1374

**Comment by carlosperate** [comment]
Could this be a feature request? to be able to install the wheel without having to specify the name?
Mostly to keep feature parity with pip and be able to be a drop-in replacement.

**Comment by zanieb** [comment]
This mismatch in behavior is actually intentional, but we are willing to reconsider. See https://github.com/astral-sh/uv/issues/313 for the tracking issue.

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip ./filename.whl ` directly, without including a package name.

**Comment by jovezhong** [comment]
`uv pip install ./filename.whl` actually
