### ISSUE TITLE
`pip install --no-cache-dir` support

### ISSUE THREAD

**Issue by Mikcl** [astral-sh/uv#1373]
Not necessarily asking for this feature but it may make sense to make `uv` more drop in replacement. 

There is `uv pip install --no-cache`. but the pip equivilent is `--no-cache-dir` https://pip.pypa.io/en/stable/topics/caching/#disabling-caching

Is this something we'd like to support for compatabilty reasons? 
(imo the --no-cache flag is much cleaner and meanigful) 

```
uv pip install --no-cache-dir six
error: unexpected argument '--no-cache-dir' found

  tip: a similar argument exists: '--no-cache'
```

**Comment by zanieb** [comment]
Yes we can add a hidden alias for this, thanks for reporting!
