### ISSUE TITLE
Add uv pip install git+ssh:// new feature

### ISSUE THREAD

**Issue by gcamargo1** [astral-sh/uv#1378]
Hi,
Is it possible to add the :
`pip install git+ssh://`

capability?
Thank you.

**Comment by charliermarsh** [comment]
👍 I believe this is the same as https://github.com/astral-sh/uv/issues/313. (We do support `flask @ git+https://github.com/pallets/flask.git@refs/pull/5313/head`, but we currently require the `flask @`.)

**Comment by charliermarsh** [comment]
(I'm gonna merge into that issue.)

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip install git+ssh://...` directly, without including a package name.
