### ISSUE TITLE
Support for `UV_CACHE_DIR=/dev/null` or equivalent

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#1382]
It would be useful to do the equivalent of `uv pip install --no-cache` via env var

**Comment by zanieb** [comment]
Like specifically to another location or to disable it entirely?

**Comment by hauntsaninja** [comment]
To disable it entirely, I think to another location currently works

**Comment by zanieb** [comment]
It'd be nice to be cross-platform so I think `UV_NO_CACHE` makes more sense than changing the value of the directory and trying to guess what value we want?

**Comment by hauntsaninja** [comment]
Yeah, that's the better UI

In a world where hard links were commonly used for Python packaging I would not have a use case. But my current use case is that I have some code that builds a container where for reasons I currently feel most comfortable using `--link-mode=copy` and I'd prefer to not end up with two copies. More generally, this is a env var pip has, so if I can get similar behaviour when using `uv` it reduces FUD when porting

**Comment by charliermarsh** [comment]
>  But my current use case is that I have some code that builds a container where for reasons I currently feel most comfortable using --link-mode=copy and I'd prefer to not end up with two copies

This part is also interesting, maybe worth considering better support for this workflow in `uv`.

**Comment by hauntsaninja** [comment]
> maybe worth considering

I'm really glad uv defaults to hard links. I just have a little FUD about some things specific to my codebase, so not sure how strongly you should consider that specific bit. Definitely consider containers though!

I do generally like that pip exposes a lot of its configuration via env vars. I think that was a good choice for a low-ish level tool

**Comment by hauntsaninja** [comment]
Thank you! :-)
