### ISSUE TITLE
Need improved handling of virtual environments

### ISSUE THREAD

**Issue by eabase** [astral-sh/uv#1390]
Hi, 

I think this package could benefit greatly by improving the handling of virtual environments. 

There are already a great simple solution available, called [venvlink](https://github.com/fohrloop/venvlink). It also has automatic venv *dis/activation* with powershell integration. 

However, that project is no longer maintained and need either a new maintainer or be integrated with something that is maintained.

The main issues with all other available package managers is that they don't separate the venv packages in a sensible manner, and insists on bloating the project directory with these entire package installation structures, while not making it easy to share, reuse or copy environments without duplicating data on disk. Because of this, they also don't keep track of what virtual environments have already been created, or what environments are available on the system.

`venvlink` solves all that!

**Comment by zanieb** [comment]
Hi!

Thanks for engaging with the project.

We're already de-duplicating installed packages (on supported platforms). We're planning to tackle a full "workflow" around environment management in the future as well. This will have a much more opinionated workflow than manually creating and activating environments.

**Comment by vtnate** [comment]
I love what Astral is doing for python tooling! For me the killer feature of pyenv is the automatic activation/de-activation of venvs as I move around in the terminal. That is the only item keeping me on pyenv at this point, tbh. https://rye-up.com/ appears to be a parallel attempt at fixing the pip/venv experience and making a universal solution.

I'm here to applaud your work and request something like pyenv's seamless venv experience, once venvs have been created.

**Comment by zanieb** [comment]
We're continuing to explore this and will probably have automated activation of a sort in the near future.
