### ISSUE TITLE
Support alternative platform detection mechanisms other than reading /bin/ls

### ISSUE THREAD

**Issue by robin-nitrokey** [astral-sh/uv#1395]
The `find_libc` function that is used to determine whether `uv` is running on `musllinux` or `manylinux` tries to read `/bin/ls`:

https://github.com/astral-sh/uv/blob/c6a43e92f91df8cd133f8e13800c3dbc4b113bb4/crates/platform-host/src/linux.rs#L128-L141

If `/bin/ls` does not exist, `uv` cannot be run.  This is the case namely on NixOS which does not follow the Filesystem Hierarchy Standard.  I understand that this is a special case, but it would be great if you would provide a way to skip this check, e. g. by setting an environment variable (or maybe using `/bin/sh` instead which is available on NixOS).

**Comment by zanieb** [comment]
Thanks for the clear report!

**Comment by zanieb** [comment]
If you patch this to `/bin/sh` does it "just work"?

**Comment by robin-nitrokey** [comment]
Yes, with `/bin/sh` it works for me.
