### ISSUE TITLE
Add pre-commit support

### ISSUE THREAD

**Issue by neumann-nico** [astral-sh/uv#1400]
Thanks for the great tool, `uv pip compile` is blazing fast 🚀 
I would like to suggest to add pre-commit support for `uv` to make it more useable.

You probably want to add a new repository similar to ruff-pre-commit?
https://github.com/astral-sh/ruff-pre-commit

Currently I use this pip-tools pre-commit hook
https://github.com/jazzband/pip-tools/blob/main/.pre-commit-hooks.yaml

**Comment by sbrugman** [comment]
In addition to locking the dependencies for replicating the exact environment, we like to use `pip compile` in our CI pipelines to ensure on all target platforms and Python versions compatible packages exist (e.g. to prevent Windows users to run into this after updates have shipped). It would be great if this hook or a second hook can be used to that (failure if not compatible, success if compatible).

**Comment by neumann-nico** [comment]
There is a PR for it: https://github.com/astral-sh/ruff-pre-commit/pull/68

**Comment by edgarrmondragon** [comment]
I guess this can be closed now?

https://github.com/astral-sh/uv-pre-commit
