### ISSUE TITLE
Better error messages when trying to `uv pip install` a wheel file without a package name

### ISSUE THREAD

**Issue by carlosperate** [astral-sh/uv#1407]
In the spirit of PR https://github.com/astral-sh/uv/pull/669, it'd be nice if some of the error messages when trying to install a wheel without specifiying the package name were a bit more helpful.

The error message for a relative path is good:
```
$ uv pip install mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl
error: Failed to parse `mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl`
  Caused by: URL requirement must be preceded by a package name. Add the name of the package before the URL (e.g., `package_name @ https://...`).
mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
But the error for a full path that starts with `/`, is not as helpful:
```
$ uv pip install /Users/microbit-carlos/workspace/tmp/mu-tests/mu/mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl
error: Failed to parse `/Users/microbit-carlos/workspace/tmp/mu-tests/mu/mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl`
  Caused by: Expected package name starting with an alphanumeric character, found '/'
/Users/microbit-carlos/workspace/tmp/mu-tests/mu/mu/wheels/1.2.2/appnope-0.1.4-py2.py3-none-any.whl
^
```

And the error when the path is a filename in a local directory is not as helpful either:
```
$ cd mu/wheels/1.2.2/
$ uv pip install appnope-0.1.4-py2.py3-none-any.whl
  × No solution found when resolving dependencies:
  ╰─▶ Because appnope-0-1-4-py2-py3-none-any-whl was not found in the package registry and you require appnope-0-1-4-py2-py3-none-any-whl, we can
      conclude that the requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
Nice, those are great cases to handle, thanks.

**Comment by zanieb** [comment]
Related #313 https://github.com/astral-sh/uv/issues/1403

**Comment by akx** [comment]
👍 from me. I have a Dockerfile that does a multistage build where wheels are built in a chunkier container and installed (only) from those wheels in a second stage.

```
FROM something AS requirements
COPY requirements.txt /wheels/requirements.txt
RUN cd /wheels && pip wheel --no-cache-dir -r requirements.txt
# ...
FROM somethingelse AS runtime
# ...
RUN --mount=type=cache,ro,from=requirements,source=/wheels,target=/wheels pip install --no-cache-dir --no-index --find-links /wheels /wheels/*.whl
```
Trying to replace `pip install` with `uv pip install` goes
```
0.171 error: Failed to parse `/wheels/Babel-2.14.0-py3-none-any.whl`
0.171   Caused by: Expected package name starting with an alphanumeric character, found '/'
0.171 /wheels/Babel-2.14.0-py3-none-any.whl
```
(Replacing `pip wheel` with `uv pip wheel` fails too, because `wheel` isn't a subcommand yet, but that's another issue.)

**Comment by charliermarsh** [comment]
(You should be able to use `Babel @ /wheels/Babel-2.14.0-py3-none-any.whl` -- does that work?)

**Comment by akx** [comment]
@charliermarsh Can't try that easily unfortunately since the list of requirements comes from shell wildcard expansion 😅

**Comment by charliermarsh** [comment]
Oh hah. Okay, got it :) It sounds like you need https://github.com/astral-sh/uv/issues/313.

**Comment by matthewfeickert** [comment]
> Can't try that easily unfortunately since the list of requirements comes from shell wildcard expansion

Yeah, this is something that I run into as well, when I have validation shell scripts that find all the wheels from an archive that's been downloaded and then execute something similar to

```
uv pip install "./archive/*.whl"
```

(I know that this is already in the works over on Issue #313, so thank you!, I just wanted to give another example of a common workflow.)

**Comment by charliermarsh** [comment]
This is now supported, so no need to improve the error messages!
