### ISSUE TITLE
Track invalid distributions as incompatibilities

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1412]
e.g. in https://github.com/astral-sh/uv/issues/1402 we say no versions exist if the distributions have invalid `requires-python` specifiers.

**Comment by zanieb** [comment]
@charliermarsh you just fixed this right?

**Comment by charliermarsh** [comment]
I think this happens at a slightly different layer… I need to check.

**Comment by konstin** [comment]
We currently still skip those files: https://github.com/astral-sh/uv/blob/cedd18e4c62cf720d6235fa623d50bdc64b12d36/crates/uv-client/src/registry_client.rs#L776-L783
