### ISSUE TITLE
Compatibility with Nix(OS)?

### ISSUE THREAD

**Issue by gkze** [astral-sh/uv#1418]
Hi, very excited to try this tool. Unfortunately Nix doesn't expose common executables on standard paths (`/bin/ls`, `/bin/ld`, etc.) so I'm not sure how to proceed. Any advice? I'm going to try to change the logic to perform a `$PATH`-based lookup, but not sure if absolute paths are desired. Would appreciate advice.

**Comment by timleslie** [comment]
I believe this is a dupe of #1395.

**Comment by charliermarsh** [comment]
Yeah I definitely want to fix this.

**Comment by charliermarsh** [comment]
I'm gonna merge into #1395.
