### ISSUE TITLE
Install `pip` by default in new environments

### ISSUE THREAD

**Issue by ikrommyd** [astral-sh/uv#1420]
I think it's more logical to automatically install pip in the newly created environments by `uv venv` so that the user can immediately have access to pip within the new environent. Now if you create a new environment and activate it, pip points to the system pip.

Please close if this is a duplicate issue that I wasn't able to find

**Comment by charliermarsh** [comment]
(Whether that should be the default is a reasonable question, so I'll leave this open! But wanted to make sure you knew about that option.)

**Comment by iasonkrom** [comment]
Nah, I didn't know it. Thanks! I was just comparing `uv venv` with `virtualenv .venv` and what those install to the new environment

**Comment by charliermarsh** [comment]
Yeah, we exclude these "seed" packages by default, since in theory you don't need them if you use `uv` to handle package installation. But if you're using `uv` to create virtualenvs that you want to manipulate with `pip`, you do need `--seed`.

**Comment by zanieb** [comment]
See #1330

**Comment by charliermarsh** [comment]
I'm happy with our current choice here, though I know it can take some adjustment for users.

**Comment by ikrommyd** [comment]
Yup, I should have actually closed it myself, I had just forgotten about it.
