### ISSUE TITLE
Failed to detect operating system version on Alpine Linux

### ISSUE THREAD

**Issue by CoolCat467** [astral-sh/uv#1427]
Semi-duplicate of #1392 but that one seems to be specifically for apple silicon.

Currently working on attempting to replace pip with `uv` in https://github.com/python-trio/trio/pull/2957 but apparently alpine linux is not supported currently.

```console
  + uv --version
  uv 0.1.1
  + uv venv .venv --seed
    × Failed to detect the operating system version: Couldn't detect either
    │ glibc version nor musl libc version, at least one of which is required
```
Source: https://github.com/python-trio/trio/actions/runs/7926057000/job/21640239761?pr=2957#step:6:115

**Comment by zanieb** [comment]
Thanks for the report! I'm not sure what's going on here yet, we'll need to get a development environment setup on Alpine so we can debug.

**Comment by BurntSushi** [comment]
I'm able to reproduce this via the `alpine:latest` docker image:

```
$ cross b --manifest-path ~/astral/uv/Cargo.toml --profile profiling -p uv --target x86_64-unknown-linux-musl
    Finished profiling [optimized + debuginfo] target(s) in 0.13s
$ cp ~/astral/uv/target/x86_64-unknown-linux-musl/profiling/uv ./
$ docker run --rm -it --mount type=bind,src=$PWD,dst=/host alpine:latest /bin/sh
/ # /host/uv venv
  x Failed to detect the operating system version: Couldn't detect either glibc version nor musl libc version, at least one of which is required
```

**Comment by mgasner** [comment]
you guys are amazing, tysm
