### ISSUE TITLE
Docs: `contributing.md` Python section anchor does not exist

### ISSUE THREAD

**Issue by JacobCoffee** [astral-sh/uv#1431]
> See the [Python](#python) section for instructions on installing the Python versions.

`#python` does not currently exist in this file.
https://github.com/JacobCoffee/uv/blob/2586f655bbf650a9797c8f88b6d9066eefe7a3dc/CONTRIBUTING.md#L30

**Comment by zanieb** [comment]
Thanks I think that should refer to https://github.com/astral-sh/uv/blob/main/CONTRIBUTING.md#testing now
