### ISSUE TITLE
ARMv7 Linux Musl

### ISSUE THREAD

**Issue by dynasticorpheus** [astral-sh/uv#1438]
As ruff enthusiast I would love to see uv-armv7-unknown-linux-musl target made available for this great initiative. Very useful for environments like Alphine linux and OpenWRT.

**Comment by charliermarsh** [comment]
Just want to confirm that the [uv-armv7-unknown-linux-musleabihf.tar.gz](https://github.com/astral-sh/uv/releases/download/0.1.2/uv-armv7-unknown-linux-musleabihf.tar.gz) variant doesn't work here, right?

**Comment by dynasticorpheus** [comment]
@charliermarsh Ok I need more coffee it seems, only checked the table where it is not mentioned but not actual assets list. I can confirm it is working so will close this issue. Keep up the good work!

**Comment by dynasticorpheus** [comment]
Closing this for now as duplicate of #1427
