### ISSUE TITLE
Request: Support uv venv --prompt 

### ISSUE THREAD

**Issue by frague59** [astral-sh/uv#1445]
Hi,
`venv` has an mainly undocumented feature :

```sh
$ python3.9 -m venv --prompt=<my prompt> ./venv
```
This command creates the virtuelenv, and append a prompt parameter ti the `pyvenv.cfg` file : 

```sh
$ cat ./venv/pyvenv.cfg
home = /usr/local/bin
include-system-site-packages = false
version = 3.9.16
prompt = '<my prompt>'
```

This option is useful when you use several virtualenvs, as the active venv prompt can be displayed by the (linux) prompt, like [liquidprompt](https://liquidprompt.readthedocs.io/en/stable/) or [starship](https://starship.rs/)

Thanks !

**Comment by reinout** [comment]
I second this. I use `--prompt` a lot because I have lots of projects. It is easy to forget to deactivate when moving from one to the other. Just seeing `(.venv) reinout@mycomputer:~/some/project/ $` doesn't help to spot the difference.

(Note that I suspect there are nicer ways to handle it and perhaps `uv` could make the prompt default to the directory name etc.... but the idea at the moment is probably to keep everything the same and just mimick pip/venv as good as possible :-) So supporting `--prompt` is good enough for now.)

**Comment by methane** [comment]
Please support `--prompt .` and make it as a default behavior.
I use this alias for daily job.

```
alias mkvenv='python3 -m venv --prompt . .venv
```

**Comment by zanieb** [comment]
I believe we discussed this multiple times internally, not sure why it didn't happen.

**Comment by greywidget** [comment]
This does seem to be the default behaviour on Windows. `uv venv` and then activating with `activate.ps1` shows a prompt of the current directory the same as `python -m venv --prompt .` would.

On my mac it defaults to a prompt of the `name` argument (which defaults to `.venv`)

**Comment by reinout** [comment]
I'm also on a mac, which matches your observation. I'd guess we can expect the same behaviour on linux. 
So: windows by default does the "right" thing?

**Comment by greywidget** [comment]
@reinout Yes, I created a couple of virtual environments on Windows 10 using `uv venv -p 3.12` and each time the prompt defaulted to the cwd like it does with `venv` with the `--prompt .` argument.

I don't know if it has any bearing but I was running Powershell inside Windows Terminal and activating with `activate.ps1`. I haven't looked to see if any of the other activate scripts do anything different.

**Comment by greywidget** [comment]
> I'm also on a mac, which matches your observation. I'd guess we can expect the same behaviour on linux. So: windows by default does the "right" thing?

@reinout I was just double checking Windows to add some more info for the PR which is waiting to be merged, when I realised that my comment was incorrect. 
In my case the venv prompt I was seeing was coming from ohmyposh. 

If I run (for example) the old version of Powershell (where I don't have ohmyposh set up) the prompt defaults to the name you gave to the venv (which we know defaults to .venv)

Apologies for the confusion.

**Comment by reinout** [comment]
If I read #1570 correctly, the upcoming behaviour is that `uv venv` even automatically sets the prompt to the name of the current directory (instead of `.venv`)? That's extra luxurious 👍 Then I won't even need `--prompt`.

**Comment by dhruvmanila** [comment]
@reinout Yes, that's correct. All thanks to @methane for the idea and the PR :)
