### ISSUE TITLE
`uv pip install -C`/`--config-settings`

### ISSUE THREAD

**Issue by nschloe** [astral-sh/uv#1460]
`pip install -C` (or `--config-settings`) allows one to pass config settings to the build backend. From the pip `--help`:

```
  -C, --config-settings <settings>
                              Configuration settings to be passed to the PEP 517
                              build backend. Settings take the form KEY=VALUE. Use
                              multiple --config-settings options to pass multiple
                              keys to the backend.
```

Would be great to have that in uv.

**Comment by henryiii** [comment]
Note this is called `-C / --config-setting` (no s) in build. And while it's pretty close to useless in setuptools, it's a key feature of alternative builders like scikit-build-core and meson-python.

**Comment by smackesey** [comment]
We need this feature to cleanly port the [Dagster](https://github.com/dagster-io/dagster) dev/CI setup over to `uv` since we rely on `pip install -e <pkg> --config-settings editable-mode=compat`.

**Comment by henryiii** [comment]
Any thoughts on the best way to do this? Currently it's just rendering a string `"{}"` and putting that into the commands. Would it be a hash table on `SourceBuild`, or an option added to all the methods?

**Comment by ion-elgreco** [comment]
I would also like to add that would be useful for us, we have a couple editable installs at the moment in our project

**Comment by charliermarsh** [comment]
I can take this one, hopefully today.

**Comment by charliermarsh** [comment]
PR is up.
