### ISSUE TITLE
query values not preserved in urls

### ISSUE THREAD

**Issue by janbernloehr** [astral-sh/uv#1463]
When specifying a requirement using a url containing a query string
```
torch @ https://foo.org/torch.whl?some=auth
```
the query string is lost by uv. This is required e.g. when downloading wheels from an azure blob storage container with SAS authentication.

pip and pip-compile preserve the query string.

**Comment by zanieb** [comment]
Thanks for the report.

We'll need to figure out a good test case for this, ideally we could include this in a `compile` or `install` test.

**Comment by charliermarsh** [comment]
So I see the query string preserved, if I run (e.g.):

```
flask @ https://files.pythonhosted.org/packages/36/42/015c23096649b908c809c69388a805a571a3bea44362fe87e33fc3afa01f/flask-3.0.0-py3-none-any.whl?foo=bar
```

Anything else to know about the URL you used? Was it an HTTPS or Git dependency? Were there environment variables in it?

**Comment by janbernloehr** [comment]
Indeed it works with 0.1.2!
