### ISSUE TITLE
Question: Will it also replace `pipenv`?

### ISSUE THREAD

**Issue by TheRealBecks** [astral-sh/uv#1465]
Have you already heard about [pipenv](https://github.com/pypa/pipenv)? I saw that you talking about replacing several package managers and virtualization managers, but I didn't see you mentioning `pipenv`.

Key benefits of using `pipenv`:

- replaces `pip` and `venv`
- No shitty `requirements.txt`, but a structured `Pipfile`
- The production or development installation from `Pipfile` will result in a `Pipfile.lock` that uses hashes to strengthen the security, but also allows to install binary-equal versions on several platform, so you development install can be equally to the production setup on a server
- Integrated into VS Code, so the virtual environment can be used directly

Especially using a `.lock` with hashes file instead of the `requirements.txt` is a killer feature. I would love to see something equal at `uv`.

**Comment by moaddib666** [comment]
Upvote this question, as pip has security concerns when we need to work with several registries private and public ones, and it's great to have lock files so that on CI we don't need to make any additional resolution at all.

**Comment by hauntsaninja** [comment]
`uv pip compile` supports pip-compile's `--generate-hashes` flag if you want a lock file with hashes. I believe `uv` aims on introducing a higher level UI in the future, but the low level commands are there.

**Comment by thomasleveil** [comment]
It would be nice to be able to : 

`uv pip compile Pipfile --generate-hashes -o requirements.txt   # Read a Pipenv file.`

**Comment by astrojuanlu** [comment]
It is my understanding that the community has been trying to standardise a lockfile for years:

- Take 1 https://peps.python.org/pep-0650/ withdrawn
- Take 2 https://peps.python.org/pep-0665/ rejected

And to the best of my knowledge, [efforts continue to provide such a standard](https://github.com/brettcannon/mousebender).

It was comforting to see [the `uv` devs being so open and receptive to community feedback](https://discuss.python.org/t/uv-another-rust-tool-written-to-replace-pip/46039) already and I hope they take a sensible approach and carefully avoid blessing locking formats that are far from being "standard".

**Comment by helderco** [comment]
@thomasleveil, you can also pass stdin:
```
pipenv requirements | uv pip compile --generate-hashes -o requirements.txt -
```

@astrojuanlu, there's a [Take 3](https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593) (discussion phase, before PEP), continuing from the mousebender project 🙂

**Comment by zanieb** [comment]
We're building a lock file; see https://github.com/astral-sh/uv/issues/3347

**Comment by datalifenyc** [comment]
@TheRealBecks Have you made the switch to `uv`? As a `pipenv` user, is there anything I should know about making the transition to `uv`?

**Comment by datalifenyc** [comment]
@TheRealBecks Thank you for the detailed project setup and ansible repo! This will definitely simplify my transition, especially with the references to fastapi and docker.

**Comment by cclauss** [comment]
# https://pypi.org/project/pipenv-uv-migrate
