### ISSUE TITLE
Direct URL constraints are ignored

### ISSUE THREAD

**Issue by sbidoul** [astral-sh/uv#1467]
It seems that uv does not honor constraints that are Direct URLs.

Assuming you have a direct URL for `pkga` in `constraints.txt`, `uv pip install pkga -c constraints.txt` fails saying pkga is not found in the package registry.

Here is a reproducer:

```bash
#/bin/bash

cd $(mktemp -d)

mkdir pkga
cat <<EOF > pkga/pyproject.toml
[project]
name="pkga"
version="1.0"
EOF

cat <<EOF > constraints.txt
pkga @ file://$PWD/pkga
EOF

uv venv
source .venv/bin/activate

uv pip install pkga -c constraints.txt
```

**Comment by charliermarsh** [comment]
Thanks! Will fix.

**Comment by charliermarsh** [comment]
Sorry about this, silly oversight in the code. Will go out in the next release, thanks!

**Comment by sbidoul** [comment]
That was quick, thanks!
