### ISSUE TITLE
Support for pip-compile-multi workflows?

### ISSUE THREAD

**Issue by PeterJCLaw** [astral-sh/uv#1468]
I see from https://github.com/astral-sh/uv/issues/815 that you're aware of `pip-compile-multi`, just wondering if you have plans to add support for that too?

**Comment by zanieb** [comment]
I don't think we plan to support it. The usage is small and there are simple workarounds e.g. a requirements file that includes the others. Sorry I know that's not a great answer to hear but I'd rather focus on building new workflows that solve this problem rather than adding another compatibility interface.

**Comment by Mogost** [comment]
@zanieb Could you provide more details on the specific plans and features you’re considering? Additionally, how do you see uv evolving in terms of unique workflows and integration with Dependabot? Enhancing these areas and good dependabot integration could significantly popularize uv and streamline dependency management.

For reference, Dependabot is open to contributing new ecosystems, which you can find more about [here](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems).

I was too embarrassed to open a new issue, so I asked here. Moreover this ticket can probably be closed.

**Comment by zanieb** [comment]
Hi!

Dependabot support is being tracked in https://github.com/astral-sh/uv/issues/2512 — of course we'd love an integration once what we're stable.

You can see all the work in progress with the [preview label](https://github.com/astral-sh/uv/issues?q=label%3Apreview+). We don't have a full roadmap written out at this time, the [readme](https://github.com/astral-sh/uv?tab=readme-ov-file#roadmap) has a blurb though.

**Comment by Mogost** [comment]
Thanks for the clarification! 
> We don't have a full roadmap

It would be great to have one. Anyway thank you for you work on py-cargo 😃

**Comment by mermerico** [comment]
If I tried to work on a PR to implement this, would you be interested or do you feel it's not worth supporting? We're finding the sequential import workflow to be a pain.
