### ISSUE TITLE
problem with relative includes in requirements file

### ISSUE THREAD

**Issue by detlefla** [astral-sh/uv#1470]
Incompatibility: If pip-compile is invoked for a file requirements/dev.in and this file includes `-r common.in`, the included file will be searched in the same directory (requirements/) where the including file is located. `uv pip compile requirements/dev.in` obviously tries (and fails) to resolve the include from the caller's working directory.

**Comment by hauntsaninja** [comment]
Duplicate of #1367 (and already fixed on main)
