### ISSUE TITLE
How to run uv behind a corporate proxy?

### ISSUE THREAD

**Issue by NiklasRosenstein** [astral-sh/uv#1474]
Our corporate proxy inspects traffic and thus inserts its own certificate that has to be configured to trust across applications on the system. I do this by setting `REQUESTS_CA_BUNDLE` and `SSL_CERT_FILE`, etc. It seems that `uv` doesn't respect either of those. Is there another environment variable that it takes into account?

```
error: error sending request for url (https://pypi.org/simple/protobuf/): error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: invalid peer certificate: UnknownIssuer
```

**Comment by kvelicka** [comment]
#1339 seems like a near-duplicate but I think it's important to distinguish "treat this host as trusted" and "verify the trustworthiness of this host, but using a user-specified certificate". For a corporate environment the latter option is much prefereable as we'd rather not compromise on security. Having said that, resolving #1339 would allow corporate users to at least _try_ `uv` in earnest so it would be some progress!

**Comment by j-baker** [comment]
This might have a much simpler solution - basically, if you changed your `reqwest` feature flag from `rustls-tls` (which means `rustls-tls-webpki-roots` to `rustls-tls-native-roots`, it'd use the operating system's truststore (which corporate certs are typically added to), as well as using `SSL_CERT_FILE` and other standard config mechanisms.

**Comment by zanieb** [comment]
I actually made this exact change in https://github.com/astral-sh/uv/pull/609 but it didn't get merged, we'll reconsider.

**Comment by carlosjourdan** [comment]
I'm still facing the same issue on version 0.1.11

Corporate network with ssl inspection firewall, custom ca on every site. Root certificate is trusted by windows, and environment variables REQUESTS_CA_BUNDLE and SSL_CERT_FILE are setup. Python requests work fine. Pip install as well. u v fails with below.

```
error: error sending request for url (https://pypi.org/simple/zeep/): error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: invalid peer certificate: UnknownIssuer
```

**Comment by dorschw** [comment]
in WSL, running [windows-certs-2-wsl](https://github.com/bayaro/windows-certs-2-wsl), `update-ca-certificates`, then `export SSL_CERT_DIR=/etc/ssl/certs` did the trick.

**Comment by a087861** [comment]
Following as I am in a similar boat :-/

On mac with apple silicon behind proxy.  Tried running `uv venv -p 3.8` which resulted in an 'invalid peer certificate' error.  I think this is due to the same thing that affects others in this discussion but certs aren't my forte so I may be wrong.

**Comment by zanieb** [comment]
@a087861 try using the `--native-tls` flag

**Comment by a087861** [comment]
@zanieb that worked like a charm - thanks!

**Comment by Gr3at** [comment]
> [@a087861](https://github.com/a087861) try using the `--native-tls` flag

this might work for linux based systems (including wsl) but in Windows it greatly depends on several preconditions (event the selected shell).

IMO a great flag addition similar to the `--native-tls` would be to introduce a `--custom-ca-file`.
This would allow to specifically define what certs needs to be utilized to make any `uv` requests.

Not sure how difficult this is to add.

In my case i was able to install packages using the following on Windows 10 using git-bash as my shell of choice.

```bash
export HTTPS_PROXY=<company-proxy-here>
uv add --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org <package_name>
```

instead i would like to be able to do something like the following:

```bash
export HTTPS_PROXY=<company-proxy-here>
uv add --custom-ca-file <path to company internal root ca cert or bundle of certs> <package_name>
```

**Comment by zanieb** [comment]
You can use the standard [`SSL_CERT_FILE` variable](https://docs.astral.sh/uv/configuration/environment/#ssl_cert_file)

**Comment by duygu-sahin** [comment]
For those on Windows, here’s the equivalent workaround that worked for me: 

set HTTPS_PROXY=<company-proxy-here>
uv pip install --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org <package_name>

**Comment by oguz-hanoglu** [comment]
For github related downloads like new python installs
`export UV_INSECURE_HOST="github.com raw.githubusercontent.com objects.githubusercontent.com"`

**Comment by oguz-hanoglu** [comment]
export UV_NATIVE_TLS=true

**Comment by cloudquestor** [comment]
> For github related downloads like new python installs `export UV_INSECURE_HOST="github.com raw.githubusercontent.com objects.githubusercontent.com"`

This worked beautifully.

**Comment by brillarm** [comment]
I work behind a company proxy too, and I use Docker with `uv` to build and execute my projects; never had an issue like this before but since 05/02/2026, it stopped working with error on `uv self update` (github api rate limit exceeded) or with docker image `docker.io/astral/uv:latest` (invalid peer certificate: UnknownIssuer on `uv sync --locked`).

After some search, I found myself here and tried almost everything, the only thing that worked is to use docker image and add `UV_INSECURE_HOST="github.com raw.githubusercontent.com objects.githubusercontent.com pypi.org files.pythonhosted.org"`. (big up @oguz-hanoglu )

I asked around in my company, but nothing (proxy or certificate)-related seems to have changed, so I don't really understand why I need this now...

**Comment by rdbisme** [comment]
I think suggesting deactivating TLS signing is bad practice. You're basically disabling SSL security. If your custom CA is correctly configured, you should not need to disable TLS verification. 

Setting `SSL_CERT_FILE` (and adding /building the right ca bundle) should cover both installing packages and python interpreters.

Ideally, on Windows, `uv` should leverage the system trust store if it still does not.

**Comment by JasonF-CGI** [comment]
> I think suggesting deactivating TLS signing is bad practice. You're basically disabling SSL security. If your custom CA is correctly configured, you should not need to disable TLS verification.
> 
> Setting `SSL_CERT_FILE` (and adding /building the right ca bundle) should cover both installing packages and python interpreters.
> 
> Ideally, on Windows, `uv` should leverage the system trust store if it still does not.

I think we need something to leverage windows certs in WSL or a way to easily export them. I have looked and can find no clear process or script.

**Comment by fenchu** [comment]
on windows11 powershell I have to use  `uv self update --system-certs` not needed on linux, macos
