### ISSUE TITLE
`uv pip install` cannot fetch requirement file from remote URL

### ISSUE THREAD

**Issue by kdeldycke** [astral-sh/uv#1481]
Trying to install packages from a `requirements.txt` file that is available on a remote URL is not supported:
```shell-session
$ uv pip install --requirement https://raw.githubusercontent.com/kdeldycke/workflows/main/requirements.txt
error: failed to open file `https://raw.githubusercontent.com/kdeldycke/workflows/main/requirements.txt`
  Caused by: No such file or directory (os error 2)
```

The same is working without any issue with `pip`:
```shell-session
$ python -m pip install --requirement https://raw.githubusercontent.com/kdeldycke/workflows/main/requirements.txt
Collecting (...)
(...)
Successfully installed (...)
```

That being said, thanks for the fantastic initiative that is `uv` and good luck with the deluge of issues and reports following the launch! 🤗

**Comment by charliermarsh** [comment]
👍 Yeah this is something we don't support yet. I honestly didn't even know pip supported it :joy: Shouldn't be too hard to add.

**Comment by omh1280** [comment]
Is this something I can pick up as a first issue?

**Comment by zanieb** [comment]
@omh1280 feel free to give it a try!

**Comment by omh1280** [comment]
Thanks @zanieb !

I opened a draft PR into my fork since it's still WIP. I will keep trying to get it to work, but I would appreciate any help to get me unstuck. I've left some comments with questions on that PR.

**Comment by charliermarsh** [comment]
This just merged and will be supported in the next release: https://github.com/astral-sh/uv/pull/2081
