### ISSUE TITLE
Python package in format git+https://gitlab.com/<path_to_package>@<version> not recognized

### ISSUE THREAD

**Issue by erwinmintiens** [astral-sh/uv#1500]
When installing with `uv pip install -r requirements.txt` an error occurs when adding packages from private repositories.
Some packages in the requirements file can look like this:
`git+https://gitlab.com/<url_to_package>@<version>`.
But when trying to install these package(s), the following error occurs:

```
error: Unsupported requirement in pip-requirements.txt at position 419
  Caused by: URL requirement must be preceded by a package name. Add the name of the package before the URL (e.g., `package_name @ https://...`).
```

**Comment by charliermarsh** [comment]
Thanks! This is the same as https://github.com/astral-sh/uv/issues/313. We currently require that you add a name for the package, like `<your_package_name> @ git+https://gitlab.com/<url_to_package>@<version>`. We'll fix this limitation in a future release though.

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip install git+https://gitlab.com/<url_to_package>@<version>` directly, without including a package name.
