### ISSUE TITLE
pip install error: failed to rename file from ../.tmp to real package

### ISSUE THREAD

**Issue by kafonek** [astral-sh/uv#1508]
Maybe related to https://github.com/astral-sh/uv/issues/1454? I see the following issue when running inside a relatively beefy Ubuntu 22.04 docker container. The same lines run fine on my local Ubuntu 22.04 WSL box.

```
❯ uv venv
Using Python 3.10.12 interpreter at /usr/bin/python3.10
Creating virtualenv at: .venv

❯ uv pip install torch
Resolved 22 packages in 9ms
error: Failed to install: nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (nvidia-cublas-cu12==12.1.3.1)
  Caused by: failed to rename file from /root/si/.venv/lib/python3.10/site-packages/.tmp06hBnQ/__init__.py to /root/si/.venv/lib/python3.10/site-packages/nvidia/__init__.py
  Caused by: No such file or directory (os error 2)
```

I've also seen the same error happen with `pysoundfile` when installing a long list of deps from `requirements.txt` but then installing `pysoundfile` on its own in a fresh venv works. Hope this helps give you an idea of where a potential race condition or other issue might be.

```
Downloaded 399 packages in 2m 05s
error: Failed to install: pysoundfile-0.9.0.post1-py2.py3-none-any.whl (pysoundfile==0.9.0.post1)
  Caused by: failed to rename file from /root/si/.venv/lib/python3.10/site-packages/.tmp3vcGXK/soundfile.py to /root/si/.venv/lib/python3.10/site-packages/soundfile.py
  Caused by: No such file or directory (os error 2)
```

```
❯ uv venv
Using Python 3.10.12 interpreter at /usr/bin/python3.10
Creating virtualenv at: .venv

❯ uv pip install pysoundfile
Resolved 3 packages in 6ms
Installed 3 packages in 28ms
 + cffi==1.16.0
 + pycparser==2.21
 + pysoundfile==0.9.0.post1
 ```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Do you mind trying again with v0.1.3?

**Comment by kafonek** [comment]
hard to prove a negative, but all of the situations that were consistently leading to this error before are working with 0.1.3 🚀

**Comment by kafonek** [comment]
Probably fixed, anyone else still seeing this should feel free to reopen this though.

Thanks @charliermarsh ❤️

**Comment by charliermarsh** [comment]
Sweet, let me know if it pops up again!

**Comment by kafonek** [comment]
For posterity, was this fixed in https://github.com/astral-sh/uv/pull/1546?

**Comment by charliermarsh** [comment]
Yes (that was the intent, at least).
