### ISSUE TITLE
File-based configuration

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1511]
We should support configuration via a file, but what this looks like exactly is not yet determined.

**Comment by DanCardin** [comment]
Please dont use `dirs`, as they've explicitly rejected the idea of supporting XDG on macos, which is really annoying to the people that care, and irrelevant to the people that dont care. You'll eventually (or immediately) get requests to do so, and will have to work around their weird stance. Nushell has had a many years long [open issue](https://github.com/nushell/nushell/issues/893#issuecomment-1872575029) as a result of their early choice to use `app_dirs`.

I've had good success with `etcetera`, although I'm certain there are other options for arriving at mutually liked behavior.
