### ISSUE TITLE
PEP 514 support

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1521]
https://peps.python.org/pep-0514/

We use `py` to find Python installations on Windows today but we want to switch to registry look-ups per PEP 514

**Comment by gaborbernat** [comment]
Note virtualenv already does this via https://github.com/pypa/virtualenv/blob/main/src/virtualenv/discovery/windows/pep514.py 👍

**Comment by gaborbernat** [comment]
`tox-uv` seems to be failing on Github Actions without this https://github.com/tox-dev/tox-uv/actions/runs/7935511069?pr=2

**Comment by MichaReiser** [comment]
According to pep514, `py` already makes use of the registry information. Therefore, implementing PEP514 is unlikely to help when trying to discover all python versions.

> When installed on Windows, the official Python installer creates a registry key for discovery and detection by other applications. This allows tools such as installers or IDEs to automatically detect and display a user’s Python installations. For example, the [PEP 397](https://peps.python.org/pep-0397/) py.exe launcher and editors such as PyCharm and Visual Studio already make use of this information.
