### ISSUE TITLE
failed to copy file from C:\Users\xxxxx\.conda\envs\uv\Lib\venv\scripts\nt\python.exe

### ISSUE THREAD

**Issue by OliverKleinBST** [astral-sh/uv#1524]
Running
uv pip compile -o requirements.txt -p 3.9 requirements.in
on windows with conda installation provides error
"failed to copy file from C:\Users\xxxxx\.conda\envs\uv\Lib\venv\scripts\nt\python.exe"

When I am located in my conda environment the python.exe is located here:
C:\Users\xxxxx\.conda\envs\uv\python.exe

while there is no python.exe in the path it actually looks for it.
(uv) dir C:\Users\xxxxx\.conda\envs\uv\Lib\venv\scripts\nt
 Volume in drive C is Windows
 Directory of C:\Users\xxxxx\.conda\envs\uv\Lib\venv\scripts\nt

16/02/2024  19:30    <DIR>          .
16/02/2024  19:30    <DIR>          ..
24/08/2023  18:59               967 activate.bat
24/08/2023  18:59               368 deactivate.bat
               2 File(s)          1.335 bytes

CONDA_PREFIX is set to 
C:\Users\xxxxx\.conda\envs\uv

**Comment by charliermarsh** [comment]
I think this is _probably_ fixed. If not, let me know and I'll re-open.
