### ISSUE TITLE
Uninstalling then reinstalling a package produces METADATA error

### ISSUE THREAD

**Issue by RafailFridman** [astral-sh/uv#1525]
Steps to reproduce:
* Installing some package, let's say `pandas`
```
uv venv env1 -p 3.10
source env1/bin/activate
uv pip install pandas
```
* Uninstalling it and installing it again:
```
uv pip uninstall pandas
uv pip install pandas
```

* Produces the following error:
```
error: Failed to read metadata for: pandas==2.2.0
  Caused by: failed to open file `~/env1/lib/python3.10/site-packages/pandas-2.2.0.dist-info/METADATA`
  Caused by: No such file or directory (os error 2)
```

Am I doing something wrong?

**Comment by zanieb** [comment]
Hm interesting, I can't reproduce this:

```
❯ source .venv/bin/activate
❯ uv pip install pandas
Resolved 6 packages in 96ms
Downloaded 2 packages in 499ms
Installed 2 packages in 26ms
 + numpy==1.26.4
 + pandas==2.2.0
❯ uv pip uninstall pandas
Uninstalled 1 package in 87ms
 - pandas==2.2.0
❯ uv pip install pandas
Resolved 6 packages in 3ms
Installed 1 package in 16ms
 + pandas==2.2.0
```

**Comment by charliermarsh** [comment]
It might be useful to see the contents of `~/env1/lib/python3.10/site-packages/pandas-2.2.0.dist-info` or similar after the uninstall, and then after the second install.

**Comment by RafailFridman** [comment]
After the uninstall the folder `~/env1/lib/python3.10/site-packages/pandas-2.2.0.dist-info` is empty, but it still exists
After the second install attempt it remains empty.

I tried to manually remove the `pandas-2.2.0.dist-info` before the second installation attempt, and then the installation succeeded!
So it seems that this folder was not removed during the uninstall, which causes this issue.

**Comment by charliermarsh** [comment]
Great, that's really helpful! Just confirming: it's _totally_ empty, no dotfiles or anything, right? Will review.

**Comment by RafailFridman** [comment]
Yes, it is totally empty - nothing shows up with `ls -a`

Thanks!

**Comment by charliermarsh** [comment]
Thanks! I have at least one idea here.

**Comment by RafailFridman** [comment]
I checked it in version 0.1.13, and I don't get this issue anymore. Closing, I guess :)

**Comment by akozlu** [comment]
having similar problems on 0.4.27 on linux I think, whenever i do a `uv pip uninstall` and then `uv pip install` I end up in the following situation. Wondering if there's an argument/command I can utilize to get out of this state instead of manually deleting the dist-info file or re-creating the `.venv`
```
warning: Failed to uninstall package at .venv/lib/python3.8/site-packages/aiobotocore-2.13.3.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
```

**Comment by Cogito** [comment]
Just adding, I ran into a similar issue on Windows trying to `uv sync --reinstall` as there were some ghost python processes with some libraries open. This caused a permissions error, leaving an empty `.dist-info` folder, which then caused errors like above.

**Comment by akozlu** [comment]
Its definitely the failure to delete `.dist-info` folder, even though the contents of them are deleted. Was curious what you meant by  _ghost python processes with some libraries_, were those UV related operations? thank you.

**Comment by Cogito** [comment]
Unfortunately I'm unsure as to what exactly was going on.

I was using intellij and thought maybe it was indexing the venv, but that seems unlikely.
I had run a few tools with uv (dagster, dbt, jupyter, etc) and of the ones I had I most suspected dagster (as it has long running daemon and webserver). In any case, I could see python processes running (spawned by uv as far as I could tell) that didn't match up to anything I was actively using. killing them and fixing the empty folders seemed to resolve the issue.
