### ISSUE TITLE
Failed to detect operating system version on amazonlinux:2023 and rocky 8/9

### ISSUE THREAD

**Issue by altendky** [astral-sh/uv#1532]
https://github.com/Chia-Network/chia-blockchain/actions/runs/7933582391/job/21662665237?pr=17572#step:11:45
```
error: Failed to detect the operating system version: Couldn't parse /bin/ls for detecting the ld version: Invalid magic number: 0x622f7273752f2123
```

We test our installer script across several linux flavors via docker and as I switched to uv I started getting the above error on amazonlinux:2023, rocky8, and rocky9.  The Debian, Arch, Fedora, and Ubuntu images we test do not fail.

This may be related to https://github.com/astral-sh/uv/issues/1427 but I made a new issue so you can decide to merge them or not.

**Comment by BurntSushi** [comment]
I'm pretty sure this is fixed by https://github.com/astral-sh/uv/pull/1493.

**Comment by BurntSushi** [comment]
Yeah I've confirmed this is fixed locally in the `amazonlinux:2023` docker image.
