### ISSUE TITLE
`uv` does not understand URL-encoded link data

### ISSUE THREAD

**Issue by SnoopJ** [astral-sh/uv#1542]
`uv` commands offer `--find-links`, but do not behave as `pip` and `pip-compile` do when dealing with indices that URL-encode their package names/URLs. For reference, see the [implementation of the correct behavior in `pip`](https://github.com/pypa/pip/blob/51de88ca6459fdd5213f86a54b021a80884572f9/src/pip/_internal/models/link.py#L382-L394).

Without this support, packages provided by PyTorch that explicitly identify their CUDA support cannot be installed with `uv pip install` or resolved by `uv pip compile`.

## Example reproduction

```
$ uv pip install --find-links https://download.pytorch.org/whl/torch_stable.html "torch==2.0.0+cu118"
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of torch==2.0.0+cu118 and you require torch==2.0.0+cu118, we can conclude that the requirements are
      unsatisfiable.
```

**Comment by charliermarsh** [comment]
Thanks! I reproduced, I'll fix this now.
