### ISSUE TITLE
Operation Timeout on Pip Install

### ISSUE THREAD

**Issue by PeterParker** [astral-sh/uv#1549]
On an internet connection with slow downloads a `uv pip install` often seems to lead to a timeout.

Here is an example error message:

```
20.82 Resolved 163 packages in 20.61s                                                                                                                        
320.0 error: Failed to download distributions                                                                                                                
320.0   Caused by: Failed to fetch wheel: scikit-image==0.21.0                                                                                               
320.0   Caused by: Failed to extract source distribution: request or response body error: operation timed out                                                
320.0   Caused by: request or response body error: operation timed out
320.0   Caused by: operation timed out
```

I am running `uv==0.1.2`.

Is there a way to increase the timeout to allow for slower downloads?

**Comment by zanieb** [comment]
We currently have this hard-coded to 5 min https://github.com/astral-sh/uv/blob/0bfce353fba9f4a44d748c1d492a2efebaabd528/crates/uv-client/src/registry_client.rs#L85

I agree a setting seems important.

**Comment by ilkersigirci** [comment]
This is really frustrating since I couldn't able to install pytorch. I hope it will be fixed soon
