### ISSUE TITLE
Allow uv to install global packages with supporting flag

### ISSUE THREAD

**Issue by savioxavier** [astral-sh/uv#1550]
Right now, I use a ton of different CLI tools written in Python to manage my workflow. I also make sure that I regularly upgrade them with the help of `pip review`. Unfortunately, pip is really slow and takes forever to run, which is why I'm super excited about uv.

Currently, it doesn't seem as if uv allows the installation of global packages, which in this case are CLI tools (it always requires a venv). Doing so could keep my CLI tools easier to manage and upgrade and also, separate from my individual projects.

What I propose is a new flag called `-g|--global` to be added to the `uv pip install` command. 

For example:
```sh
$ uv pip install --global frogmouth # a terminal markdown viewer app
```

In addition (although these could be planned for later): 
- `uv pip upgrade --global --all`
- `uv pip list --global`

**Comment by zanieb** [comment]
Thanks for your feedback! Great to hear you're excited about the tool :)

Your requests are being tracked in:

- #1401
- #1419 
- #1526
