### ISSUE TITLE
allow duplicates of the same version of the same package

### ISSUE THREAD

**Issue by raylu** [astral-sh/uv#1552]
we have multiple requirements.txt files with the same package at the same version (thanks to `pip-sync -c requirements1.txt requirements2.in`)

```
$ uv pip sync <(echo packaging==23.1) <(echo packaging==23.1)
error: Failed to determine installation plan
  Caused by: Detected duplicate package in requirements: packaging
```

I think the check here is too strict https://github.com/astral-sh/uv/blob/4e0b6f8f849bdbc9e21ab302eb8c8dcb1e81fe6d/crates/uv-installer/src/plan.rs#L125-L130

**Comment by ericbn** [comment]
pip-tools works as expected:
```
$ pip-sync <(echo packaging==23.1) <(echo packaging==23.1)
...
Installing collected packages: packaging
Successfully installed packaging-23.1
```

pip-tools will only fail if there are incompatible requirements found:
```
$ pip-sync <(echo packaging==23.1) <(echo packaging==23.2)
Incompatible requirements found: packaging==23.2 (from -r /dev/fd/12 (line 1)) and packaging==23.1 (from -r /dev/fd/11 (line 1))
```

I'd like to see both behaviors in uv too.

**Comment by charliermarsh** [comment]
I think this makes sense, though I'm not sure what should happen if the requirements overlap? E.g., `packaging==23.2` and `packaging<=24` or something.

**Comment by ericbn** [comment]
pip-tools seems to work only when the duplicated requirements are exactly the same, otherwise it will fail with `Incompatible requirements found`. I guess it makes sense because it expects pinned versions generated by pip-compile (like `==23.2`), not ranges like `<=24` or anything else.

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/uv/pull/1558.
