### ISSUE TITLE
`uv pip install` gets stuck combining `--resolution=lowest-direct` and `--upgrade` flags

### ISSUE THREAD

**Issue by adamtheturtle** [astral-sh/uv#1563]
Tested with `uv 0.1.3`.

Choose a package, in this example, `mypy`.

Run:

```
uv pip install --resolution=lowest-direct --upgrade "mypy"
```

This stalls for at least 30 minutes.

Seen on macOS (locally) and on Ubuntu (GitHub Actions).

**Comment by charliermarsh** [comment]
I think you can reproduce with just: `cargo run pip install --resolution=lowest-direct "wheel==0.1"`
