### ISSUE TITLE
A way to get sub-command output when running `uv pip install`

### ISSUE THREAD

**Issue by alex** [astral-sh/uv#1567]
Currently if you run `uv pip install -v` you get, more or less, a trace of all the operations `uv` does internally.

When doing a `uv pip install 'package @ .'`, and building that package requires compilation (notably, rust compilation!) I'd like to have a way to stream the output from that while running `uv pip install` (the output serves as a form of progress bar for long compilation).

Ideally I'd be able to get this output _without_ getting the full trace output from uv

**Comment by charliermarsh** [comment]
Yeah I agree, I also want this.
