### ISSUE TITLE
Flaky expect failures in resolver

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#1585]
Getting the following segfault:
```
thread 'main' panicked at crates/uv-resolver/src/resolution.rs:135:30:
Every package should have metadata
```

Repro:
```
In [5]: Counter(subprocess.run("rm -rf .venv; uv venv --seed; uv pip install --no-cache --link-mode=copy --no-deps gpustat==1.1.1", shell=True).returncode for _ in range(100))
Out[5]: Counter({101: 73, 0: 27})
```

https://github.com/astral-sh/uv/pull/1583 should improve the error message (I had to do some bisection to narrow it down to a single package)

With #1583 it appears there's some connection to setuptools-scm

Similar message reported in this comment: https://github.com/astral-sh/uv/issues/1484#issuecomment-1948863469

**Comment by charliermarsh** [comment]
Awesome, thanks! Will fix.

**Comment by charliermarsh** [comment]
I can reproduce this on some old commits (I randomly tried c1eb6130e1cb46a7ce5c34bccdfcb9245e29e8a8), but not on `main`, so I think it's resolved, at least on `main`? Will re-open if not.

**Comment by hauntsaninja** [comment]
I bisected to #1607 , hopefully there's something in there that explains non-deterministic behaviour
