### ISSUE TITLE
 uv-x86_64-pc-windows-msvc.zip is getting flagged by Windows Defender

### ISSUE THREAD

**Issue by pfmoore** [astral-sh/uv#1587]
I tried to download the latest release, 0.1.3, specifically the file uv-x86_64-pc-windows-msvc.zip, but Windows Defender flagged it as malicious with the error

![image](https://github.com/astral-sh/uv/assets/1110419/12618a47-cf9a-4c29-bbc5-dfd9a84fdd6f)

(sorry for the screenshot, the dialog box won't let me copy the text out 🙁)

I assume this is a false positive, but I'm reluctant to tell the virus checker to simply ignore the issue. The 0.1.0 release didn't have this problem.

**Comment by zanieb** [comment]
Sorry but there's usually nothing we can do about these false positives — we get these in Ruff too.

**Comment by pfmoore** [comment]
No worries, I didn't think so - I just wanted to let you know. I can wait for the next release (or build it myself - it's impressively straightforward to build 🙂)

**Comment by charliermarsh** [comment]
These are my worst enemy.

**Comment by senden9** [comment]
I got by the same windows defender update. I was using `uv` and from one moment to the next i got the message that the command `uv` is unknown. A few moments later windows defender proudly notified my that it detected and quarantined `uv.exe` for containing `Trojan:Script/Wacatac.B!ml`. I did come here and write that comment to have the name of the falsely detected threat somewhere in the issue tracker.

**Comment by senden9** [comment]
I reported that false positive under https://www.microsoft.com/en-us/wdsi/filesubmission as Customer.

**Comment by senden9** [comment]
Update from the Analyst at Microsoft:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.
> 
So as far as I understand `uv` should no longer trigger a Microsoft Defender quarantine with the latest update 🎉
