### ISSUE TITLE
Support `.` for paths

### ISSUE THREAD

**Issue by Zethson** [astral-sh/uv#1589]
```bash
⋊>  uv pip install .                                                                                                                (lamindb) 14:24:53
error: Failed to parse `.`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.
^
```

```bash
pip install .
``` 
works

**Comment by stillmatic** [comment]
`uv pip install -e .` ?

**Comment by Zethson** [comment]
That installs in editable mode, but sometimes I want a "snapshot" of the current version.

**Comment by charliermarsh** [comment]
👍 I believe this is the same as https://github.com/astral-sh/uv/issues/313. We actually do support `uv pip install "foo @ ."` where `foo` is the package name -- internally, we just have various codepaths that rely on having a package name upfront. But we'll remove that restriction in the future.

(Closing to merge into #313.)

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip install .` directly, without including a package name.
