### ISSUE TITLE
Implement "uv pip show"

### ISSUE THREAD

**Issue by jab** [astral-sh/uv#1594]
```
❯ uv --version
uv 0.1.2

❯ uv pip show uv
error: unrecognized subcommand 'show'

Usage: uv pip [OPTIONS] <COMMAND>

For more information, try '--help'.

❯ pip show uv
Name: uv
Version: 0.1.2
Summary: An extremely fast Python package installer and resolver, written in Rust.
Home-page: https://pypi.org/project/uv/
Author: uv
Author-email: "Astral Software Inc." <hey@astral.sh>
License: MIT OR Apache-2.0
Location: /Users/jab/src/bidict/.venv/dev/lib/python3.12/site-packages
Requires:
Required-by:

❯ pip show -qq uv && echo uv installed || echo uv not installed
uv installed
```
As in the last example, the `-qq` form is particularly useful for querying just whether _any_ version of a particular package is installed, which is all I actually need.

It's possible to run `uv pip freeze | grep ...` instead, but it seems like it might be easy enough and worth it to add `uv pip show <pkg>` (or at least `uv pip show -qq <pkg>`), which should also be faster.

**Comment by jab** [comment]
Relatedly, `uv pip list` is also missing, which has some overlap here. I'll hold off on creating a separate ticket for that for now though.

**Comment by ismail** [comment]
@jab https://github.com/astral-sh/uv/issues/1401 for `pip list`.

**Comment by charliermarsh** [comment]
This was added in https://github.com/astral-sh/uv/pull/2115.

**Comment by charliermarsh** [comment]
Thanks @ChannyClaus!
