### ISSUE TITLE
Use async zip streaming for non-range-request supporting registries

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#1596]
For registries that support range requests, we grab the wheel metadata using range requests, which is much faster than downloading the wheel.

For registries that don’t, we fall back to downloading the wheel, and reading the metadata from disk.

Instead, we should be able to stream the wheel in-memory until we get to the METADATA entry, then return it without writing to disk (and without downloading the entire wheel). I don’t know where the METDATA is typically located (e.g., if it’s at the front of the archive, this will be significantly faster; if it’s at the end, it won’t be that different).

**Comment by zanieb** [comment]
Is this a wish or something we think we should do soon?

**Comment by notatallshaw** [comment]
btw, I think this is somewhat related work on Pip side: https://github.com/pypa/pip/pull/12208, or at least I think it's related.

I think the author has seen examples of metadata at both the front and back of the zip file.

Sorry if it's not actually that closely related, my mind was triggered from reading this and remembering that PR, but I only have time to skim over things.
