### ISSUE TITLE
Seeding venv adds setuptools and wheel on Python 3.12

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#1602]
If you use `--seed` on a Python 3.12 venv, you still get setuptools and wheel, while both virutalenv and venv have dropped them if using Python 3.12 or newer. This causes `uv venv -p 3.12 --seed` (524ms) to be slower than `virtualenv .venv` (360ms), which is only adding `pip`.

**Comment by zanieb** [comment]
Thanks! We can drop them too.

**Comment by charliermarsh** [comment]
Oh wow!
