### ISSUE TITLE
Extras aren't included for local editable install

### ISSUE THREAD

**Issue by pjbull** [astral-sh/uv#1616]
Our [dev requirements file](https://github.com/drivendataorg/cloudpathlib/blob/a242f68d762cdf6a7cfc56e5962a8d83bced5f1b/requirements-dev.txt#L1) has the line `-e .[all]` in it.

While all the other packages seemed to install correctly with `uv pip install -r requirements-dev.txt`, the extras did not.

uv 0.1.1

If you want to repro, you can run:
```bash
git clone https://github.com/drivendataorg/cloudpathlib.git
cd cloudpathlib
uv pip install -r requirements-dev.txt
```

[You should end up with the `azure-storage-blob`, `boto3`, and `google-cloud-storage` packages installed.
](https://github.com/drivendataorg/cloudpathlib/blob/a242f68d762cdf6a7cfc56e5962a8d83bced5f1b/pyproject.toml#L37-L41)

**Comment by charliermarsh** [comment]
I believe this was fixed in v0.1.3 -- do you mind trying? (#1435)

**Comment by pjbull** [comment]
Yep, looks good in 0.1.3. Sorry for the noise!

**Comment by charliermarsh** [comment]
No prob, thanks for the clear repro!
