### ISSUE TITLE
Keep editable "." install when locking and syncing

### ISSUE THREAD

**Issue by PetterS** [astral-sh/uv#1626]
I saw a few other issues tagged with **question**, so I thought it could be OK so a ask one like this.

I have a codebase with some dependencies and some code. I would like to create a venv where all of that is available.

So far `uv` works if I do this:
```
uv pip compile pyproject.toml -o requirements.txt
...
uv pip sync requirements.txt
uv pip install -e .
```
I would like to not have to run the last command after every sync. How can I somehow specify the editable install of the current project in pyproject?

- In poetry, I used a `packages` key under `[tool.poetry]` but that is obviously not going to work here.
- Adding `"myproject @ ."` as a dependency results in a `relative path without a working directory: .` message from `uv`

PS the speed of `uv` looks absolutely fantastic!

**Comment by zanieb** [comment]
👋 It looks like you're looking for the behavior described in

https://github.com/astral-sh/uv/pull/1000

Let me know if that works for you!

**Comment by PetterS** [comment]
You mean a dependency like `"my-project @ file://."`? That also gives the "relative path without a working directory" error

**Comment by zanieb** [comment]
Can you share the full output with the `-v` flag?

**Comment by charliermarsh** [comment]
It’s possible that we parse pyproject.toml without passing the relative dir down. I can take a look this week to understand what the correct behavior is and whether we’re matching it.

**Comment by charliermarsh** [comment]
One option is that you should be able to do `my-project @ file://${PROJECT_ROOT}`. Do you mind trying that?

**Comment by PetterS** [comment]
> my-project @ file://${PROJECT_ROOT}

I then get `error: my-project 1 depends on itself`

**Comment by PetterS** [comment]
> > my-project @ file://${PROJECT_ROOT}
> 
> I then get `error: my-project 1 depends on itself`

Update: that worked when I installed the latest version of `uv`. Great!

**Comment by serjflint** [comment]
> One option is that you should be able to do `my-project @ file://${PROJECT_ROOT}`. Do you mind trying that?

Hello! ''my-sub-project @ file://${PROJECT_ROOT}/../relative/path#egg=sub_package'' worked, but only halfway:
`error: Distribution not found at: file:///resolved/path%23egg=sub_package`

**Comment by debugger24** [comment]
Hi, I am trying out something similar, using ${PROJECT_ROOT} does work but when we have chain of libraries, it doesn't compile, it take relative path of my current project directly even of dependent libraries.

**Comment by charliermarsh** [comment]
I think we intentionally don't allow relative paths in `pyproject.toml` because it's not part of the PEP standard, and that file needs to follow standards, whereas `requirements.txt` is _not_ standardized and already does a few things that don't adhere to them.

**Comment by PetterS** [comment]
`my-project @ file://${PROJECT_ROOT}` does not install `my-project` as editable in 0.1.24. It makes a copy. In fact, it seems difficult to ever upgrade it without deleting the `.venv`. `pip compile` and `pip sync` does not change anything

**Comment by charliermarsh** [comment]
You need to install with -e in order to install as editable. For example, “uv pip install -e .”

**Comment by PetterS** [comment]
Yes, that works. Would be nice to somehow specify that the project itself should be installed editable. But maybe the pyproject syntax does not allow this

**Comment by atomiechen** [comment]
I found a way to solve this: by specifying `setuptools` as the build system, `uv sync` will make the project editable installed:


```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

I verified that `uv.lock` is updated with `source = { editable = "." }` under your project package.

**Comment by joaoprocopio** [comment]
thanks @atomiechen!!!!!!!!!

**Comment by robert-elles** [comment]
Leads to errors for me, first i get:
```ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must not contain {'package-mode'} properties```

After removing the line `package-mode = false`, I then get the following error:

```
[stderr]
error: Multiple top-level packages discovered in a flat-layout: ['data', 'logs', 'typings', ...].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

**Comment by MrMegaMango** [comment]
local module installed by `uv add --editable ./pkg` doesn't work when running `uv run service/server.py`. ModuleNotFoundError: No module named 'pkg'

**Comment by CorentinJ** [comment]
> I found a way to solve this: by specifying `setuptools` as the build system, `uv sync` will make the project editable installed:
> 
> [build-system]
> requires = ["setuptools"]
> build-backend = "setuptools.build_meta"
> I verified that `uv.lock` is updated with `source = { editable = "." }` under your project package.

Oh wow I've been trying for so long to make my repository importable as a package outside of its cwd. I tried many variations of `uv add --editable . --dev` but it never worked. This was the solution... that was really far from obvious

**Comment by charliermarsh** [comment]
The impact of the build system is covered in the docs: https://docs.astral.sh/uv/concepts/projects/init/.
