### ISSUE TITLE
Question: How to use uv with poetry on CI?

### ISSUE THREAD

**Issue by Warchant** [astral-sh/uv#1634]
Is it possible to use uv to speed-up `poetry install` on CI?

**Comment by woutervh** [comment]
for now:
```
poetry export > requirements.txt
uv venv
uv pip install -r requirements
poetry install
```

**Comment by zanieb** [comment]
We'd need to add support for reading Poetry's dependency format, I'm not sure if we will. 

Related:
- #1650

**Comment by Warchant** [comment]
> for now:
> 
> ```
> poetry export > requirements.txt
> uv venv
> uv pip install -r requirements
> poetry install
> ```

This works, but `poetry export > requirements.txt` creates UTF16-LE file, while `uv pip install -r requirements.txt` expects UTF-8, so I manually need to re-save it in UTF8. It is not a problem, but would be cool if `uv` would detect input file encoding...

**Comment by Secrus** [comment]
> for now:
> 
> ```
> poetry export > requirements.txt
> uv venv
> uv pip install -r requirements
> poetry install
> ```

Do not redirect stream from `poetry export`, use `-o` flag to specify output file (it properly handles user messages and the actual dependency output).

**Comment by zanieb** [comment]
As of https://github.com/astral-sh/uv/pull/2633 we support reading this directly.
