### ISSUE TITLE
`uv pip install --resolution=lowest --upgrade "ruff"` gets stuck

### ISSUE THREAD

**Issue by adamtheturtle** [astral-sh/uv#1645]
Run: `uv pip install --resolution=lowest --upgrade "ruff"`

This gets stuck.

The same happens with `uv pip install --resolution=lowest --reinstall "ruff"`

```
> uv --version
uv 0.1.4
> python -m platform
macOS-14.3-arm64-arm-64bit
```

**Comment by charliermarsh** [comment]
I suspect that it's trying to build the lowest-available version of Ruff, which means it's building from source? Which means it will take a long time...

**Comment by adamtheturtle** [comment]
🤦 I feel stupid! Sorry I didn't wait long enough.

**Comment by charliermarsh** [comment]
Not at all... This is similar to another issue that requests more proactive output when building deps.
