### ISSUE TITLE
I expected `--resolution=lowest` to imply `--reinstall` for an existing package

### ISSUE THREAD

**Issue by adamtheturtle** [astral-sh/uv#1647]
I ran:

```
uv pip install ruff # installs the latest version
> uv pip install --resolution=lowest ruff
Audited 1 package in 0ms
```

I expected that this would install the lowest version of ruff.
I think that either changing the behaviour, or documenting this is suitable.

**Comment by charliermarsh** [comment]
I think our behavior here is actually okay, because it's consistent in general with how `pip install` works: if you have a satisfactory version in your environment, it defers to that. But we should document it somewhere / somehow.

**Comment by zanieb** [comment]
We could also consider displaying a warning? That seems hard to do well though.

**Comment by charliermarsh** [comment]
I think our behavior here is ok, though I can understand why it might be confusing on first run.
