### ISSUE TITLE
Tag created venvs as a cache dir to avoid most of in-project venv downsides

### ISSUE THREAD

**Issue by hynek** [astral-sh/uv#1648]
Some people prefer their virtualenvs in a central place which has its valid reasons.

Some of those reasons can be avoided by tagging the .venv directory as a cache directory which will be treated as such by software that supports it (e.g. backups).

Here's the standard: https://bford.info/cachedir/ but it's just adding a file called `CACHEDIR.TAG` with the contents `Signature: 8a477f597d28d172789f06886806bc55`.

The standard is surprisingly old (2004!), but I've noticed that Direnv has started adding it to its directories only recent and Brett Cannon asked about it re venv the other day too. So it looks like it might have some legs, finally.

**Comment by charliermarsh** [comment]
Oh nice. We already add `CACHEDIR.TAG` to the uv cache. It seems correct to me to add this to virtualenvs too...

Any objections?
