### ISSUE TITLE
support 'uv --completions' to generate a completions file for bash/zsh/fish/powershell

### ISSUE THREAD

**Issue by woutervh** [astral-sh/uv#1654]
Currently uv version0.1.4 does not support tab-completions out of the box:

```
uv <TAB>   # does nothing
````

It would be nice to generate a shell-specific completions-file:
```
uv --completions  bash | zsh | fish | pwsh
````

**Comment by zanieb** [comment]
Thanks this seems reasonable to add. We'd probably want to mirror whatever we do in Ruff.
