### ISSUE TITLE
Add support for `--upgrade`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#166]
By default, we're supposed to avoid upgrading packages by looking at the locked resolution. `pip-compile` supports selective upgrades although I'm not sure that's necessary.

**Comment by matthewfeickert** [comment]
@charliermarsh As `uv` is 

https://github.com/astral-sh/uv/blob/8ef396e849c35f378831cfe873517c0cde472a74/README.md?plain=1#L10-L11

I'm a bit confused why `--ugprade` is only supported in for the `pip-compile` mode and not the `pip` mode.

For example I would expect for the following to work:

```console
$ docker run --rm -ti python:3.12 /bin/bash
root@87f3a80b206d:/# python -m venv venv && . venv/bin/activate
(venv) root@87f3a80b206d:/# python -m pip --quiet install uv
(venv) root@87f3a80b206d:/# uv --version
uv 0.1.1
(venv) root@87f3a80b206d:/# uv pip install 'awkward<2.6.0'
Resolved 4 packages in 900ms
Downloaded 4 packages in 1.21s
Installed 4 packages in 22ms
 + awkward==2.5.2
 + awkward-cpp==28
 + numpy==1.26.4
 + packaging==23.2
(venv) root@87f3a80b206d:/# uv pip install --upgrade awkward
error: unexpected argument '--upgrade' found

  tip: to pass '--upgrade' as a value, use '-- --upgrade'

Usage: uv pip install [OPTIONS] <PACKAGE|--requirement <REQUIREMENT>|--editable <EDITABLE>>

For more information, try '--help'.
(venv) root@87f3a80b206d:/#
```

Was there a particular design decision to avoid allowing this? Or would this be in scope in the future in your mind?

**Comment by charliermarsh** [comment]
@matthewfeickert - This was just an oversight -- @zanieb added it a few hours ago: https://github.com/astral-sh/uv/pull/1379. I'll probably cut another release tonight.

**Comment by matthewfeickert** [comment]
Ah thanks! Sorry I was only looking in the Issues, not the PRs as the last release was 5 hours ago. You're all just moving fast! :rocket:

**Comment by charliermarsh** [comment]
I'm just glad it's now open source, having fun wading through the issues :)
