### ISSUE TITLE
`uv pip install` fails for dependencies on already-installed local packages

### ISSUE THREAD

**Issue by charlesnicholson** [astral-sh/uv#1661]
When a package depends on an editable-installed namespaced package, `uv pip install` fails saying that the already-installed package can't be found. Possibly related to string hygiene and converting `ns1.package1` to `ns1-package1`?

Full cloneable repro case here: https://github.com/charlesnicholson/uv-pep420-bug/tree/main 
(Runs at least on macOS and maybe Linux, let me know if it's insufficient and I'll fix it up)

<img width="724" alt="Screenshot 2024-02-18 at 12 58 16 PM" src="https://github.com/astral-sh/uv/assets/3010295/50b162c4-03cd-4b17-9091-058daca3ef4e">

**Comment by charlesnicholson** [comment]
Ah, sorry:
```
❯ ./uv --version
uv 0.1.3
```

**Comment by charlesnicholson** [comment]
Confirmed still happens on `0.1.4` (albeit with a much more soothing color scheme!):

<img width="905" alt="Screenshot 2024-02-18 at 1 43 43 PM" src="https://github.com/astral-sh/uv/assets/3010295/76308b51-b871-45c3-9cfd-ee70e28369d0">

**Comment by charliermarsh** [comment]
So, I think `cargo run pip install -e ns2.package2 -e ns1.package1` works, but installing the packages one-by-one does not. I need to think about what the right solution is here. When we go to install the second package (`-e ns2.package2`), we start by performing a resolution, to figure out the required dependencies. We don't consider the "current virtual environment" to be a valid package source, so we have no way of finding `ns1-package1`.

**Comment by charlesnicholson** [comment]
Ah, interesting, thanks for taking a look and sharing your thoughts!

For context, if it's useful, the reason we incrementally `pip install -e` our various packages in order is because they're part of a larger build system that understands the dependencies between our packages and other tools. Each package has an "editable install" target, and for our build system to satisfy our version of `ns2.package2`'s dependencies, it needs to bring the "editable-install `ns1.package1`" target up-to-date first, which it does via a separate invocation of `pip install -e`.

**Comment by charliermarsh** [comment]
I think it's probably correct for us to fix this. It just changes a lot of assumptions -- right now, we perform a resolution that's independent of the virtual environment.

**Comment by kkpattern** [comment]
Installing all the editable packages at once works for us.

**Comment by charliermarsh** [comment]
Yeah, the problem is that the second install doesn't "know" where to find the existing editable. We need to make the resolver aware of packages that already exist in the virtual environment.

**Comment by vivekkalyan** [comment]
Would like to add that I am facing a similar scenario but getting a different error:

```error: Package `one` attempted to resolve via URL: file:///home/vivek/personal/python-uv-test/modules/one. URL dependencies must be expressed as direct requirements or constraints. Consider adding `one @ file:///home/vivek/personal/python-uv-test/modules/one` to your dependencies or constraints file.```

In this case, im trying to install package "one" into the directory of package "two". `uv pip sync` works, but running `uv pip install -e .` results in the above error. Running `pip install -e .` works. 

Just thought to add my error in case this is a different issue. Happy to create a reproducible repo/issue if required.

**Comment by tylerw** [comment]
Possibly related (if not, I can file a separate issue—or none at all if this is a misunderstanding on my part), when I `pip compile` a `requirements.in` or `pip install` a `requirements.txt` that has local, editable-installed modules (e.g, specified with `-e path/to/module`) they are all rebuilt and I assume cached, even if they haven't changed and don't need it. Is this avoidable?

For the record, this is a large monorepo with dozens of modules. The commands complete really fast and therefore it's not a huge problem, just wondering if there is a way (or possibly a different work flow) to prevent this.

**Comment by charliermarsh** [comment]
@tylerw -- I _think_ we try to avoid rebuilding with `uv pip compile`, but we always rebuild right now in `uv pip install`. Building editables is typically pretty cheap, but I'm looking into removing that step.

**Comment by zanieb** [comment]
Hi! Charlie tricked me into taking on this hard task instead :)

It should be addressed in the latest release ([0.1.27](https://github.com/astral-sh/uv/releases/tag/0.1.27)) via #2596.

Let us know if you have any problems.

**Comment by charlesnicholson** [comment]
So far it's great, thanks! (I'm integrating it as I type this :) )
