### ISSUE TITLE
uv pip compile does not indicate whether dependencies originate from the main package or from additional extras

### ISSUE THREAD

**Issue by neumann-nico** [astral-sh/uv#1665]
Extras are actually generated correctly but not indicated where they come from in the output file. You don't know if a dependency is part of the main package or if it is generated from an extra. This is an incompatibility with pip-compile.

(The `via -r ...` part, which is also different in the output, was already mentioned in #1343)

`psycopg[binary,pool]==3.1.18` -> `psycopg==3.1.18`
`[binary,pool]` is missing in the output.

But the extras are generated correctly:
```
psycopg-binary==3.1.18
    # via psycopg
psycopg-pool==3.2.1
    # via psycopg
```

Steps to reproduce it:

requirements.in
```
psycopg[binary,pool]==3.1.18
```

`uv pip compile requirements.in`
```
# This file was autogenerated by uv v0.1.4 via the following command:
#    uv pip compile requirements.in
psycopg==3.1.18
psycopg-binary==3.1.18
    # via psycopg
psycopg-pool==3.2.1
    # via psycopg
typing-extensions==4.9.0
    # via
    #   psycopg
    #   psycopg-pool
```

`pip-compile requirements.in`
```
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile requirements.in
#
psycopg[binary,pool]==3.1.18
    # via -r requirements.in
psycopg-binary==3.1.18
    # via psycopg
psycopg-pool==3.2.1
    # via psycopg
typing-extensions==4.9.0
    # via
    #   psycopg
    #   psycopg-pool
```

**Comment by zanieb** [comment]
Is this a duplicate of https://github.com/astral-sh/uv/issues/1595?

**Comment by neumann-nico** [comment]
Sorry I used the search but actually did not see the mentioned issue. Closing this one 👍🏻

**Comment by charliermarsh** [comment]
Supported in the next version via https://github.com/astral-sh/uv/pull/3269.
