### ISSUE TITLE
Support alternative requirements file encodings

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1666]
e.g. `UTF16-LE`

> This works, but `poetry export > requirements.txt` creates UTF16-LE file, while `uv pip install -r requirements.txt` expects UTF-8, so I manually need to re-save it in UTF8. It is not a problem, but would be cool if `uv` would detect input file encoding...
> 
> ```
> uv pip install -r .\requirements.txt
> error: failed to read from file `.\requirements.txt`
>   Caused by: stream did not contain valid UTF-8
> ```

_Originally posted by @Warchant in https://github.com/astral-sh/uv/issues/1634#issuecomment-1951402367_

**Comment by mitsuhiko** [comment]
For sake of not making an even bigger mess in the ecosystem it would be ideal if this stays as UTF-8. I'm perplexed that poetry would generate a UTF-16 file and I can only assume this is because it picks up some weird default encoding by accident.

**Comment by zanieb** [comment]
That's a fair point, it'd be nice to use a consistent encoding.

cc @Secrus

**Comment by dimbleby** [comment]
Poetry does not generate a utf-16 file.

If told a filename to write to, it writes utf-8.  However OP is redirecting stdout, presumably the encoding is whatever the python interpreter says it is in that environment

**Comment by Secrus** [comment]
The UTF-16 encoding was most likely picked up from the environment. As I stated in [here](https://github.com/astral-sh/uv/issues/1634#issuecomment-1951496960), stream redirection is not the way to export to requirements file. We use UTF-8 when writing to files.

**Comment by zanieb** [comment]
Great thanks for the background! It seems safe to close this. Happy to hear more use-cases if they exist though.
