### ISSUE TITLE
No type annotations for find_uv_bin

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#1677]
I'm using `find_uv_bin` inside https://github.com/tox-dev/tox-uv/blob/main/src/tox_uv/_venv.py#L14, but mypy complain that this method is not exposed (no `__all__` containing it) and also no type annotations for it (because https://peps.python.org/pep-0561/#packaging-type-information is missing from the Python package, plus actual type annotations for it)

**Comment by zanieb** [comment]
Hi! This is not a public function, `__main__` is intended for internal use only.

We could consider exposing `find_uv_bin` in `__init__` but I would say in general we are very hesitant to commit to a Python API at this stage.

**Comment by gaborbernat** [comment]
In the world of Python `__main__` is a public module... You might want to move it to something like _uv... But I'd ask for this one method to be public 😅

**Comment by zanieb** [comment]
I mean, it's Python everything is "public". I meant I don't think `__main__` is a module you're meant to be importing things from. It's meant to be a script entrypoint for the module.

**Comment by gaborbernat** [comment]
That's not true by convention anything starting with an underscore is considered private.

**Comment by zanieb** [comment]
I would strongly discourage you from importing from our `__main__` module. Whether by convention or not (I cannot find any documentation saying either way), this is not a part of our public API.

It looks like it does have type annotations already? I'm happy to add a `py.typed` marker and consider moving it to `__init__.py` though if it's useful. I'm surprised we haven't gotten similar requests in Ruff (which has an identical setup).

**Comment by gaborbernat** [comment]
> I would strongly discourage you from importing from our `__main__` module. Whether by convention or not (I cannot find any documentation saying either way), this is not a part of our public API.
> 
> It looks like it does have type annotations already? I'm happy to add a `py.typed` marker and consider moving it to `__init__.py` though if it's useful. I'm surprised we haven't gotten similar requests in Ruff (which has an identical setup).

Would this be made, I'd move over 👍
