### ISSUE TITLE
Trailing slash needed in URL link address in requirements.in when `uv pip compile requirements.in`

### ISSUE THREAD

**Issue by JohanSchott** [astral-sh/uv#1683]
I have a `requirements.in` that contain one line that looks something like:

`-f https://extranet.helloworld.com/public/wheels`

Running `uv pip compile requirements.in` gives error `HTTP status client error (404 Not Found) for url`.
However, if I add a trailing slash to the URL address, i.e.:

`-f https://extranet.helloworld.com/public/wheels/` 

it works fine.

I expected the trailing slash would not be needed.

**Comment by charliermarsh** [comment]
Thanks! Easy fix, will do.

**Comment by charliermarsh** [comment]
Will fix real quick.

**Comment by charliermarsh** [comment]
Do you have a public index that I can reproduce this with?

**Comment by charliermarsh** [comment]
Nevermind, found one.
