### ISSUE TITLE
`pyvenv.cfg` version-info doesn't match `virtualenv`'s

### ISSUE THREAD

**Issue by akx** [astral-sh/uv#1689]
I was playing around trying to make `pre-commit` use `uv venv` and `uv pip` (because why not!), and it ends up reporting

```
virtualenv python version did not match created version:
- actual version: 3.12.1.final.0
- expected version: 3.12
```
(which I can work around while patching things over there).

I tracked this down to https://github.com/astral-sh/uv/blob/b76efc62a72ed8031aa91ae80bb1b4a159bd3d21/crates/uv-interpreter/src/get_interpreter_info.py#L8-L13 trimming things, but changing that breaks other things ("Querying Python at `/opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12` did not return the expected data: after parsing 3.12.1, found ".final.0" after it, which is not part of a valid version)" so I'm not sure that's the right way to go here. 

Just thought I'd report this in case it is (or should be) actionable – in case it's not, never mind 😁 

## Environment

* uv: 0.1.5
* Platform: macOS 14.2.1, Homebrew-installed Python 3.12.1.

### diff between pyvenv.cfg created by `virtualenv` 20.24.6 and `uv` 0.1.5

```patch
1c1
< home = /opt/homebrew/opt/python@3.12/bin
---
> home = /opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/bin
3,4c3,4
< version_info = 3.12.1.final.0
< virtualenv = 20.24.6
---
> version_info = 3.12
> gourgeist = 0.0.4
8c8
< base-executable = /opt/homebrew/opt/python@3.12/bin/python3.12
---
> base-executable = /opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

### diff between pyvenv.cfg created by `venv` shipped with said Python and `uv` 0.1.5

```patch
1a2,4
> implementation = CPython
> version_info = 3.12
> gourgeist = 0.0.4
3,5c6,8
< version = 3.12.1
< executable = /opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12
< command = /Users/akx/envs/uv/bin/python3.12 -m venv /Users/akx/build/uv/foofoo-venv
---
> base-prefix = /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
> base-exec-prefix = /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
> base-executable = /opt/homebrew/Cellar/python@3.12/3.12.1_1/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

**Comment by charliermarsh** [comment]
We now match `venv` when reporting the Python version.
