### ISSUE TITLE
`uv pip compile` doesn't seem to support emitting its results to stdout

### ISSUE THREAD

**Issue by kvelicka** [astral-sh/uv#1690]
When running `uv pip compile requirements.in --output-file=-` I expected to have the ouptut printed in stdout like it does with `pip-compile`. Instead, it gets written to a file called `-` on the filesystem.

**Comment by omh1280** [comment]
pip-compile defaults to writing to stdout if no `--output-file` is specified. Does that not work for your use case?

When I run locally, with `pip-compile requirements.in --output-file=-`, I get a double output in stdout:
```python
#
#
# This file is autogenerated by pip-compile with Python 3.12
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
# by the following command:
#
#
#    pip-compile --output-file=- requirements.in
#    pip-compile --output-file=- requirements.in
#
#
blinker==1.7.0
    # via flask
blinker==1.7.0
    # via flask
click==8.1.7
    # via flask
click==8.1.7
    # via flask
```

**Comment by kvelicka** [comment]
Silly me, with no `--output-file` it prints to stdout just fine!

**Comment by charliermarsh** [comment]
I wonder if it should print to `stdout` in either case.

**Comment by charliermarsh** [comment]
I feel like it should.
