### ISSUE TITLE
Question: How is "uv" intended to be pronounced? 

### ISSUE THREAD

**Issue by bwanshoom** [astral-sh/uv#1691]
Is it "you-vee"? Or like "of"? Or something else entirely?

**Comment by trag1c** [comment]
I'd guess "you-vee" considering what the name means :)

<img width="617" alt="70391" src="https://github.com/astral-sh/uv/assets/77130613/18a57f77-0003-46a2-a554-31e0396b6dc4">

**Comment by bwanshoom** [comment]
Nice, thanks!
