### ISSUE TITLE
`--index-url` from `requirements.txt` is ignored

### ISSUE THREAD

**Issue by framillien** [astral-sh/uv#1692]
`--index-url` is ignored in `requirements.txt`, no issue with `--extra-index-url` parameter.

Look like it's related to the way IndexUrl argument is used. This argument is always initialized with a value [(here)](https://github.com/astral-sh/uv/blob/main/crates/uv/src/main.rs#L530) and `combine` always keep the previous value if present [(here)](https://github.com/astral-sh/uv/blob/main/crates/distribution-types/src/index_url.rs#L193).

If I invert the expression in `combine`, my `--index-url` in `requirements.txt` is correctly used; but this is maybe not the expected way to fix it because command line parameter (if really defined) should take precedence ?

This affect both `pip install` and `pip  compile` commands.

Fail with this `requirements.txt`:
```
--index-url https://my-pip-index.org/artifactory/api/pypi/pypi-custom-release/simple/

my-custom-package
```

Work with:
```
--extra-index-url https://my-pip-index.org/artifactory/api/pypi/pypi-custom-release/simple/

my-custom-package
```

With both commands:
```
uv -v --no-cache pip install requirements.txt
uv -v --no-cache pip compile requirements.in
```

To set the `--index-url`, the current workaround is to always set in on command line like:
```
uv -v --no-cache pip install --index-url https://my-pip-index.org/artifactory/api/pypi/pypi-custom-release/simple/ requirements.txt
```

**Comment by framillien** [comment]
(description edited because  it's more related to arguments default values rather than `IndexLocations` default values)

**Comment by PetterS** [comment]
It is possible to add private PyPI in the `pyproject.toml` in a standardized way that uv understands? That is quite imporant in many corporate settings.  `poetry` supports this via the non-standard `[[tool.poetry.source]]` so that works well for corporations.

**Comment by zanieb** [comment]
Not yet, but we will support persistent configuration of registries in the future.

**Comment by framillien** [comment]
Thanks for the quick fix

**Comment by PetterS** [comment]
> Not yet, but we will support persistent configuration of registries in the future.

@zanieb is there a tracking issue for that feature I can subscribe to?
