### ISSUE TITLE
Fetch version metadata in batches

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#170]
When resolving:

```
urllib3<1.25.4
boto3
```

We end up testing hundreds of boto versions. After a point, we should start fetching the version metadata in parallel for these cases.

**Comment by konstin** [comment]
As an update, pubgrub is much faster now, and it will be even faster for this case with https://github.com/pubgrub-rs/pubgrub/pull/177 (the benchmark i used hits the boto case), so we can retry doing this.
