### ISSUE TITLE
Add --no-header-version CLI flag?

### ISSUE THREAD

**Issue by mikeckennedy** [astral-sh/uv#1704]
Hi folks. Congrats on the big success of uv. I'm an instant fan.

One thing I noticed using it is that by default the uv pip compile output is causing unnecessary git conflicts:

```
- # This file was autogenerated by uv v0.1.4 via the following command:
+ # This file was autogenerated by uv v0.1.5 via the following command:
#    uv pip compile requirements.piptools --upgrade --output-file requirements.txt
```

I know there is the flag `--no-header` for no header at all. I'd love to keep it there for people less familiar with the workflow. But the version of uv in there is not super important and is likely to conflict across machines unless the version of uv is carefully managed (and that seems not necessary once uv stabilizes how it works).

Thanks for the consideration and the amazing tool.

**Comment by mikeckennedy** [comment]
Hi @zanieb No there is not, because they never put the version of piptools in there:

```
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile requirements.piptools
# 
```

**Comment by charliermarsh** [comment]
Ahhh that's interesting, I hadn't even thought of that.

**Comment by charliermarsh** [comment]
(Thanks so much @mikeckennedy!)

**Comment by mikeckennedy** [comment]
Welcome! Thanks for the thoughts @charliermarsh

**Comment by mikeckennedy** [comment]
You all are legends. Look at how fast you decided and turned that around. Thank you. We'll be discussing this tomorrow on Python Bytes too (the project not necessarily this issue).
