### ISSUE TITLE
uv cache clean doesn't work

### ISSUE THREAD

**Issue by sandipb** [astral-sh/uv#1738]
## Environment

`uv` installed via `pipx`.

```
$ uv --version
uv 0.1.5

$ uname -a
Darwin machine.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112 arm64
```

## Problem

According to the README, to clear the cache, I should be running `uv cache clean`.

> To clear the global cache entirely, run uv cache clean.

But:

```shell-session
$ uv cache clean
error: unrecognized subcommand 'cache'

Usage: uv [OPTIONS] <COMMAND>

For more information, try '--help'.
```

**Comment by hauntsaninja** [comment]
Wait for uv 0.1.6 to be released, in the meantime you can run `uv clean`

**Comment by charliermarsh** [comment]
Ah sorry, that's a disconnect between the README (docs) and the latest published version.

**Comment by rjn32s** [comment]
Thanks @hauntsaninja

**Comment by hauntsaninja** [comment]
Wow, why are you using uv 0.1, it's 2025!

**Comment by rjn32s** [comment]
🥹 living in past
