### ISSUE TITLE
pip list looks at global and not .venv created with UV

### ISSUE THREAD

**Issue by ion-elgreco** [astral-sh/uv#1741]
Running  python3 -m venv .venv, and then install with uv pip install works fine. You can then also inspect the installed packages with pip list

However doing `uv venv` then install with `uv pip install` also works, but now I cannot do pip list even though .venv is activated. Pip list is now looking at global install.

**Comment by m-aciek** [comment]
What does `python -m pip list` return for you?

**Comment by ion-elgreco** [comment]
@m-aciek it returns this: 

```python
(.venv) ion@<redacted>:~/<redacted>$ python -m pip list
/home/ion/<redacted>/.venv/bin/python: No module named pip
```

**Comment by m-aciek** [comment]
You don't have pip installed in your venv. You need to install it there or wait for https://github.com/astral-sh/uv/issues/1401.
