### ISSUE TITLE
Fail to read metadata from `.dist-info`: data did not match any variant of untagged enum DirectUrl

### ISSUE THREAD

**Issue by messense** [astral-sh/uv#1744]
```bash
$ uv pip freeze
error: Failed to read metadata: from /home/ubuntu/workspace/example/.venv/lib/python3.10/site-packages/qPython-2.0.0.dist-info
  Caused by: data did not match any variant of untagged enum DirectUrl
```

```bash
$ cat /home/ubuntu/workspace/example/.venv/lib/python3.10/site-packages/qPython-2.0.0.dist-info/direct_url.json
{"url": "git@github.example.com:example/qPython.git", "vcs_info": {"vcs": "git", "requested_revision": "7190a34911a789bd8e44f6b1986c8e84815b62e2", "commit_id": "7190a34911a789bd8e44f6b1986c8e84815b62e2"}}
```

https://github.com/astral-sh/uv/blob/d05cb8464a933a4b8e1ebe39988e0209da73ed19/crates/pypi-types/src/direct_url.rs#L32-L37

Probably because the `url` crate can't parse `git@github.example.com:example/qPython.git`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3a089088700e500364057509872b61f9

> thread 'main' panicked at src/main.rs:4:72:
> called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase

uv version: 0.1.5

**Comment by konstin** [comment]
I've checked https://packaging.python.org/en/latest/specifications/direct-url-data-structure/ and PEP 610 neither defines what grammar the url field allows :/

What command did you use to install qPython?

**Comment by messense** [comment]
It was installed by Poetry, I'm playing around with `uv` in a existing venv.

**Comment by charliermarsh** [comment]
I can look at this (though mildly dreading it).

**Comment by konstin** [comment]
I'd expect the poetry maintainers would be willing to fix this, i wonder if any other tools are doing something similar. It would be helpful if we could agree in https://packaging.python.org/en/latest/specifications/direct-url-data-structure/ that `url` contains a url as defined by https://url.spec.whatwg.org/.

**Comment by sbidoul** [comment]
> It would be helpful if we could agree in https://packaging.python.org/en/latest/specifications/direct-url-data-structure/ that url contains a url as defined by https://url.spec.whatwg.org/.

Looks like an oversight in the spec, but that was the intent, yes.

**Comment by messense** [comment]
Happy to report that `pip install` correctly uses `ssh://git@...` in `direct_url.json`.

**Comment by messense** [comment]
> I'd expect the poetry maintainers would be willing to fix this

Seems like poetry is just writing out the source url specified in `pyproject.toml` to `direct_url.json`:
https://github.com/python-poetry/poetry/blob/cff4d7d51c9ac0f9a8b9ac91652b6dc20e63e203/src/poetry/installation/executor.py#L910-L922

I had something like 

```toml
 [tool.poetry.dependencies]
qpython = { git = "git@github.example.com:example/qPython.git", rev = "7190a34911a789bd8e44f6b1986c8e84815b62e2" }
```

in `pyproject.toml`.
