### ISSUE TITLE
Install instructions for Windows command prompt

### ISSUE THREAD

**Issue by 12932** [astral-sh/uv#1750]
In the README.md [document](https://github.com/astral-sh/uv/blob/main/README.md)

It says "On Windows." , and then provides a Powershell-only compatible command. Running it in my command prompt gave me an error:
```
'irm' is not recognized as an internal or external command,
operable program or batch file.
```

It works fine in Powerhsell. I think the readme should say powershell only for that specific command

**Comment by AlexWaygood** [comment]
Agreed. Ideally we'd have a command that worked on both PowerShell and CMD (or at least instructions for how to do things with the CMD shell). But for now, just documenting that this is a PowerShell-specific command would be an improvement. PR welcome!
