### ISSUE TITLE
uv venv creates path starting with \\?\ in activate.bat which doesn't work

### ISSUE THREAD

**Issue by orlp** [astral-sh/uv#1763]
To reproduce on Windows 10 with uv 0.1.5:

```
uv venv uv-venv
cd uv-venv
.\Scripts\activate.bat
where python.exe
python.exe -c "import sys; print(sys.executable)"
```

On my machine this prints:

```
(venv) D:\tmp\uv\uv-venv>where python.exe
\\?\D:\tmp\uv\uv-venv\Scripts\python.exe
C:\dev\Python312\python.exe

(venv) D:\tmp\uv\uv-venv>python.exe -c "import sys; print(sys.executable)"
C:\dev\Python312\python.exe
```

It appears that `cmd.exe` interprets a path starting with `\\?\` in the PATH variable incorrectly, despite `where` resolving it.

---

Normal `venv` does not start paths with `\\?\` in the PATH variable, and this works fine on my machine. So perhaps this could be changed?

**Comment by charliermarsh** [comment]
@MichaReiser - (We have a `normalize()` trait method for this.)
