### ISSUE TITLE
Preserve executable when unpacking tars

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1767]
We preserve the executable bit an unpacking zips (#1743), we should do the same when unpacking source distributions, both async and sync.

**Comment by MichaReiser** [comment]
Do you have any code pointers to the unpacking logic? I would find that helpful as a first time contributor.

**Comment by konstin** [comment]
The streaming/async .tar.gz extraction: https://github.com/astral-sh/uv/blob/d6aaf7be3098ec381105c0e0db0391fd97db483d/crates/uv-extract/src/stream.rs#L103-L112
The sync version: https://github.com/astral-sh/uv/blob/9a720a87c842a070ecc58f5309c7ecc6a334da67/crates/uv-extract/src/sync.rs#L88-L107

**Comment by charliermarsh** [comment]
I'll fix this tonight, I've worked with these async unzip crates several times.
