### ISSUE TITLE
No changelog after 0.1.3

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#1774]
Seems there's no longer a changelog anywhere past 0.1.3. https://github.com/astral-sh/uv/releases/tag/0.1.3. It would be nice to have a place to easily see what changes are in new versions.

**Comment by charliermarsh** [comment]
We're gonna add the same changelog setup as in Ruff, hopefully this week!

**Comment by zanieb** [comment]
We'll be adding a real changelog soon.

**Comment by zanieb** [comment]
@charliermarsh should we leave the cargo-dist ones on until then?

**Comment by orhun** [comment]
Hey! I also realized there was no changelog and found this issue.

You can consider [`git-cliff`](https://git-cliff.org/) for automated generation of the changelog. As the author of the tool, I'm happy provide any guidance about it! 🐻

**Comment by orhun** [comment]
With the [last version](https://git-cliff.org/blog/2.0.0#-github-integration) of `git-cliff` that's also possible! Are you using the GitHub's changelog format? I would like to give it a shot to generate the changelog in the style you prefer - I'm also curious how that would turn out.
