### ISSUE TITLE
Any way to install a package from private repository with deploy key?

### ISSUE THREAD

**Issue by kolkre** [astral-sh/uv#1775]
I'm attempting to install a package from our Git instance using the command uv pip install `git+https://<DEPLOY_KEY>@<HOST>/<REPO>`, but it appears that it's not implemented in uv. It works when I use the regular pip. 

Are there any plans to implement this?

**Comment by charliermarsh** [comment]
Yup! We're working on it right now. Hopefully this week.

**Comment by kolkre** [comment]
> Hey @kolkre, just want to clarify: how are you specifying your deploy key?

It's not an SSH key. It's a text-format token that should be specified in the `Authorization` header for HTTP requests to Git.

**Comment by kolkre** [comment]
I just noticed a similar issue has already been opened, and the related PR has been merged. Perhaps it would be good to mention this in the documentation/examples.
