### ISSUE TITLE
Warn when registry doesn't support range requests for wheels

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1799]
[Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) are very important for uv's performance, especially with large wheels. They are the difference between downloading entire wheels and just some slices in the bytes to KB range. They have been part of the HTTP/1.1 and are supported by all major webserver and blob storages. We should warn users if their registry is misconfigured and doesn't support range requests. Without a warning, it is otherwise inexplicable to users why uv is slower than advertised.

**Comment by charliermarsh** [comment]
I don’t think these should be user-facing, since users typically have no control over this.

**Comment by charliermarsh** [comment]
But like, Artifactory doesn’t support this at all. Making these user-visible means Artifactory users will see these on every invocation with no recourse.

**Comment by MichaReiser** [comment]
It's a difficult one. Making it visible to users could motivate artifactory to add support for it but showing it on every invocation sounds annoying. I wonder if there are other ways we could achieve the same. Maybe with a --profile flag that tells you where uv spends time.

**Comment by Eh2406** [comment]
Perhaps only display the message if the just run command spent more than 1 second downloading wheels from a registry that does not support range queries. Something like:

```
This took longer than expected because registry (url) does not support Http 1.1 range queries.
```

**Comment by hmc-cs-mdrissi** [comment]
`more than 1 second downloading wheels `

So every time for large pytorch (or other ml/data ecosystem libraries) wheels on registries that don't support range requests? I'd still lean to call it noise that's not usually not actionable for most users.

**Comment by charliermarsh** [comment]
I think I'm gonna close this. We do show this in verbose logging, but I just don't love showing non-actionable user-facing warnings like this.
