### ISSUE TITLE
Skip over versions with invalid metadata

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#1800]
There are a number of (mostly older) releases on pypi with files with invalid metadata (e.g. #1363, #1686, #1798) we can't parse even with our fixups. We already skip over simple metadata entries we can't parse with fixups. We should do the same with versions that contain a wheel with invalid METADATA file. The failed packages should have a custom incompatibility in pubgrub so they get explained in resolution failures.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/2834.
