### ISSUE TITLE
error trying to connect: invalid peer certificate: UnknownIssuer - Even with SSL_CERT_FILE mapped

### ISSUE THREAD

**Issue by mholt77** [astral-sh/uv#1819]
Hey, I saw https://github.com/astral-sh/uv/issues/1474 should have resulted in uv being able to work via SSL_CERT_FILE, but when running.
```
uv pip install --extra-index-url https://packages.dns.ad.xyz.com/artifactory/api/pypi/pypi-libs-local/simple upv-model
```
 I am still encountering 
```
error: error sending request for url (https://packages.dns.ad.xyz.com/artifactory/api/pypi/pypi-libs-local/simple/upv-model/): error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: error trying to connect: invalid peer certificate: UnknownIssuer
  Caused by: invalid peer certificate: UnknownIssuer
```
I have validated that my trust store and environment variables are correctly mapped, should the merge for 1474 not have fixed this?

Using uv has a lot of scope to speed up so many internal package deployments so would be very keen to get to test this further.

Thanks for all the great work so far on it!

**Comment by zanieb** [comment]
Thanks for the report! I'm not sure what's going on here, it's all upstream of us now that we're using `rustls-native-certs`.

Related:
- https://github.com/rustls/rustls-native-certs/issues/16
- https://github.com/astral-sh/uv/issues/1700
- https://github.com/astral-sh/uv/issues/1701

**Comment by mholt77** [comment]
No worries, will keep my eyes open for the `--trusted-host` progress as may be able to trial it that way

**Comment by zanieb** [comment]
If there's any way you can help us reproduce the issue or investigate with verbose logs e.g. `RUST_LOG=trace uv pip install -v ...` that's the best bet to move this forward.

**Comment by mholt77** [comment]
I have attached a snippet of the log below, it appears to be failing to connect here, it cycles through this several time before returning the error.

```
            0.075847s  49ms TRACE hyper::client::pool checkout waiting for idle connection: ("https", packages.dns.ad.xyz.com)
            0.075872s  49ms DEBUG reqwest::connect starting new connection: https://packages.dns.ad.xyz.com/
            0.075890s  49ms TRACE hyper::client::connect::http Http::connect; scheme=Some("https"), host=Some("packages.dns.ad.xyz.com"), port=None
    0.075921s DEBUG hyper::client::connect::dns resolving host="packages.dns.ad.xyz.com"
            0.079257s  52ms DEBUG hyper::client::connect::http connecting to xxx
            0.082095s  55ms DEBUG hyper::client::connect::http connected to xxx
            0.082113s  55ms DEBUG rustls::client::hs No cached session for DnsName("packages.dns.ad.xyz.com")
            0.082181s  55ms DEBUG rustls::client::hs Not resuming any session
            0.082201s  55ms TRACE rustls::client::hs Sending ClientHello Message {
             version: TLSv1_0,
             payload: Handshake { .....
             0.085173s  58ms TRACE rustls::client::hs We got ServerHello ServerHelloPayload {
             legacy_version: TLSv1_2,
             random: 02b36fd708ebb74373bc26e6f796bc289ce14b60d144bd486cc4bb4b8ac24329,
             session_id: e96c4cbb3dfe7b1448d51201a3752a9c6f1ca048846ef276c297c2e014815b48,
             cipher_suite: TLS13_AES_256_GCM_SHA384,
             compression_method: Null,
             extensions: [
                 SupportedVersions(
                     TLSv1_3,
                 ),
                 KeyShare(
                     KeyShareEntry {
                         group: X25519,
                         payload: aca8a9529090f752aa450105beead313fc745d2f7cd121a52693d86d27d20b2c,
                     },
                 ),
             ],
         }
            0.085207s  58ms DEBUG rustls::client::hs Using ciphersuite TLS13_AES_256_GCM_SHA384
            0.085217s  58ms DEBUG rustls::client::tls13 Not resuming
            0.085224s  58ms TRACE rustls::client::client_conn EarlyData rejected
            0.085301s  58ms TRACE rustls::conn Dropping CCS
            0.085312s  58ms DEBUG rustls::client::tls13 TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])]
            0.085321s  58ms DEBUG rustls::client::hs ALPN protocol is Some(b"http/1.1")
            0.085821s  59ms TRACE rustls::client::tls13 Server cert is [......
                     ]
            0.086041s  59ms TRACE hyper::client::pool checkout dropped for ("https", packages.dns.ad.xyz.com)
            0.086059s  59ms  WARN reqwest_retry::middleware Retry attempt #1. Sleeping 649.8106ms before the next attempt
....
    2.626812s TRACE hyper::proto::h2::client client::dispatch::Sender dropped
    2.626844s TRACE hyper::client::pool pool closed, canceling idle interval
           h2::proto::connection::poll 
                2.626900s   0ms TRACE h2::proto::connection connection.state=Open
             h2::codec::framed_write::FramedWrite::buffer frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
                  2.626932s   0ms DEBUG h2::codec::framed_write send, frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
                  2.626943s   0ms TRACE h2::frame::go_away encoding GO_AWAY; code=NO_ERROR
                  2.626951s   0ms TRACE h2::codec::framed_write encoded go_away, rem=17
                2.626963s   0ms DEBUG h2::proto::connection Connection::poll; connection error, error=GoAway(b"", NO_ERROR, Library)
                2.626972s   0ms TRACE h2::proto::connection     -> already going away
                2.626979s   0ms TRACE h2::proto::connection connection.state=Closing(NO_ERROR, Library)
                2.626986s   0ms TRACE h2::proto::connection connection closing after flush
             h2::codec::framed_write::FramedWrite::flush 
                  2.627004s   0ms TRACE h2::codec::framed_write queued_data_frame=false
                  2.627041s   0ms TRACE h2::codec::framed_write flushing buffer
                2.627053s   0ms DEBUG rustls::common_state Sending warning alert CloseNotify
                2.627077s   0ms TRACE h2::proto::connection connection.state=Closed(NO_ERROR, Library)
    2.627092s TRACE h2::proto::streams::streams Streams::recv_eof
 h2::proto::streams::prioritize::clear_pending_capacity 
```

Also to confirm that `echo $SSL_CERT_FILE` returns `/etc/ssl/certs/ca-certificates.crt` and `echo $REQUESTS_CA_BUNDLE` returns `/etc/ssl/certs/ca-certificates.crt`

**Comment by varun-995** [comment]
If you are using rye

I was getting the similar issue, i was able to fix it following below steps.

Error trace:
abc@123 airflow_learning % rye sync                                   
Reusing already existing virtualenv
Generating production lockfile: /Users/abc/Desktop/main/airflow_learning/requirements.lock
Generating dev lockfile: /Users/abc/Desktop/main/airflow_learning/requirements-dev.lock
Installing dependencies
Resolved 1 package in 1ms
  × Failed to build `airflow-learning @ file:///Users/abc/Desktop/main/airflow_learning`
  ├─▶ Failed to resolve requirements from `build-system.requires`
  ├─▶ No solution found when resolving: `hatchling`
  ├─▶ Failed to fetch: `https://pypi.org/simple/hatchling/`
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://pypi.org/simple/hatchling/)
  ├─▶ client error (Connect)
  ╰─▶ invalid peer certificate: UnknownIssuer
error: Installation of dependencies failed in venv at /Users/abc/Desktop/main/airflow_learning/.venv. uv exited with status: exit status: 1

From the trace, I can see that it is failing for https://pypi.org/simple/hatchling/. 

- Head over to https://pypi.org/simple/hatchling/
- click on the view site information icon in the url bar.
<img width="433" alt="Image" src="https://github.com/user-attachments/assets/b2b48bd7-a616-412e-a753-de177a290ff3" />

- Click on connection is secure.
- Click on connection is valid.
- The certificate viewer will appear, so click the "Details" tab. The hierarchical certificate will be displayed.
- Follow the certificate hierarchy from pypi.org, select the top-most root certificate, and while it is still selected, click Export in the bottom right of the window to download the root certificate.
- export SSL_CERT_FILE=~/Desktop/certadmin.pem, here ~/Desktop/certadmin.pem is the path to the downloaded certificate.
- rye sync // no error at this point

**Comment by Symbolk** [comment]
`uv venv openr1 --python 3.11 --native-tls --allow-insecure-host https://github.com` Resolves the issue

**Comment by SaymV** [comment]
I also found myself here from the great deity google.

```uv sync --allow-insecure-host github.com --allow-insecure-host pypi.org --allow-insecure-host files.pythonhosted.org```

**Comment by matanco1** [comment]
Under corporate VPN I got the same issue, tried everything, but the only thing that helped me was changing the VPN endpoint (different zone)

**Comment by kangqiwang** [comment]
> Quick work around is to activate the environment and configure the SSL_CERT_FILE enviroment variable and then run the command:
> 
> ```
> uv init . 
> source .venv/bin/activate
> export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
> ```

works for me

**Comment by uranusjr** [comment]
If you’re on Mac, you can get a perm file by installing OpenSSL. With Homebrew, for example, the perm file should be somewhere in `/opt/homebrew/etc/openssl@<version>/cert.pem` (replace version as appropriate)

**Comment by dooafus** [comment]
I'm here from google to share another command that works fine in 2025. I was trying update a lock file and kept getting _invalid peer certificate: UnknownIssuer_ when uv was trying to download cPython behind a corporate firewall. It worked with:

`uv --native-tls --allow-insecure-host github.com lock --upgrade`

So a generic working template would be:

`uv --native-tls --allow-insecure-host github.com <your uv command here>`

**Comment by xml** [comment]
Personal learning on this, and I think there are some gaps in my knowledge, and YMMV. But... this seems to have explanatory power and a safe/usable solution:

First, I'm not deep in pythonia, but it seems like files.pythonhosted.org is the official Content Delivery Network (CDN) for the Python Package Index (PyPI), which hosts all package artifacts (wheels .whl and source tarballs .tar.gz) for almost everything on PyPI, from uv to pyright and beyond. So, when we go run an install, the actual file download comes from files.pythonhosted.org.

When I encountered this error, I began looking at connectivity to files.pythonhosted.org. The HTTPS requests resulted in similar certificate/security errors as the above, as did a basic: `curl -vI https://files.pythonhosted.org/`, which produced the following: 

```sh 
* Host files.pythonhosted.org:443 was resolved.
* IPv6: 2a04:4e42:d000::223
* IPv4: 167.82.52.223
*   Trying [2a04:4e42:d000::223]:443...
* Connected to files.pythonhosted.org (2a04:4e42:d000::223) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Fastly, Inc.; CN=default.ssl.fastly.net
*  start date: May  1 16:26:08 2025 GMT
*  expire date: Jun  2 16:26:07 2026 GMT
*  subjectAltName does not match host name files.pythonhosted.org
* SSL: no alternative certificate subject name matches target host name 'files.pythonhosted.org'
* Closing connection
curl: (60) SSL: no alternative certificate subject name matches target host name 'files.pythonhosted.org'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

My ai agent cleverly noticed my query was attempting to connect on IPv6, and suggested I try the curl over IPv4. Whammo: suddenly, no errors, everything resolves fine, the certs are good. The IPv4 query tells me a valid, secure IP address for files.pythonhosted.org, so I record this combo to my /etc/hosts, then I try running the install again, and... life is good, but without me institutionalizing the use of unsafe-hosts or whatever. 

Now, I don't know WHY the IPv6 path was broken. I don't know if I was behind a proxy at the cafe that had bad cache, or if there's a misconfiguration on the cert or DNS for files.pythonhosted.org, or what the root-root-cause was. That would take more time and effort than I have for this, although I'll note one complication: when I began troubleshooting this, I was on one network. When I found the path forward and started trying IPv4, I was on another. So, I'm not even sure if my solution would have worked in the first context, or if it was the move to a new network that solved it. All I know is that, even after I moved from the cafe network to my more reliable home network, the bad IPv6 dns/cert data was still blocking me.

But, I'm hoping this at least points toward a path for further problem-solving by the community. Maybe an option for uv to fall-back to IPv4 if IPv6 is throwing peer-cert errors? Maybe something the folks at pythonhosted.org can work on with their infra team? Or, maybe just a note on these issues explaining the settled science of it all. ;-)

-----

No idea where it goes from here, but I just want to thank the maintainers here on uv, the amazing folks who run pythonhosted, and the rest of the community who make this kind of work possible. We can't do what we do without you.
