### ISSUE TITLE
Difference with pip on local non-editable installs

### ISSUE THREAD

**Issue by hsheth2** [astral-sh/uv#1827]
```sh
$ uv pip install '.'
error: Failed to parse `.`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.

# whereas pip allows this
$ pip install '.'  # works as expected
```

I saw #1000 - if I do `uv pip install 'package-name @ .'` then it works, but pip doesn't like that syntax. Ideally there'd be something that works uniformly across both.

```
$ uv --version
0.1.6
```

**Comment by charliermarsh** [comment]
👍 This is the same as https://github.com/astral-sh/uv/issues/313 -- we'll lift this restriction eventually, it just made life easier for reasons that relate to implementation details.

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip install .` directly, without including a package name.
