### ISSUE TITLE
Spurious failures in CI on macOS

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1829]
7 tests failed with

```
thread 'main' panicked at crates/uv-client/src/registry_client.rs:107:33:␊
Failed to build HTTP client.: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -36, message: "I/O error." } } }␊
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace␊
```

ref https://github.com/astral-sh/uv/actions/runs/7995358164/job/21835501182?pr=1826

[Full logs](https://github.com/astral-sh/uv/files/14365026/logs.txt)

**Comment by zanieb** [comment]
Another example, 7 tests again

https://github.com/astral-sh/uv/actions/runs/8011782050/job/21885714541

**Comment by konstin** [comment]
Have we seen those recently?

**Comment by zanieb** [comment]
I'm not seeing this failure, but I am seeing spurious network failures in CI on macOS :D
