### ISSUE TITLE
Consider to hide `--index-url` and `--extra-index-url` if `--emit-index-url` flag is not presented

### ISSUE THREAD

**Issue by DrJackilD** [astral-sh/uv#1834]
Hey guys! As the title said, I wonder if the `uv` could hide `--index-url` and `--extra-index-url` if the `--emit-index-url` flag is not presented. Otherwise, if you have a private package index, this data could be accidentally committed to the repository. `pip-tools` hides the index and extra index both from the command in the comment and of course does not include them in the body of the compiled files.

I've created a small PR to do this, but if this is "by design", than I'll just close it :)

**Comment by charliermarsh** [comment]
We hide these by default in the body, right? So would this mainly be to remove them from the comment header?

**Comment by DrJackilD** [comment]
> We hide these by default in the body, right? So would this mainly be to remove them from the comment header?

Yes, exactly, only in the header comment, the body of the requirements is doing good :)
