### ISSUE TITLE
uv init

### ISSUE THREAD

**Issue by dbrtly** [astral-sh/uv#1837]
Most of the time I do:

```
uv venv
source .venv/bin/activate || source .venv/Scripts/activate
uv pip install --upgrade pip
uv pip install -r requirements.txt

```

I'd like to add an alias `uv init` or `uv up` that does all that rather than copy/paste that boilerplate everywhere. Besides "use Makefile".

**Comment by zanieb** [comment]
Thanks for the feedback. This is a duplicate of https://github.com/astral-sh/uv/issues/1360
