### ISSUE TITLE
UV pip install support for --trusted-host and --extra-index-url

### ISSUE THREAD

**Issue by Cypher1** [astral-sh/uv#1842]
OS: Mac OSX
UV platform: unknown
UV version: 0.1.6

Repro suggestion:
```
$ cat req.requirements
--extra-index-url http://pypi.company.com/simple/
--trusted-host pypi.company.com
-r requirements-dev.txt
```

```
$uv pip install -r req.requirements
```

My logs
```
$ uv pip install -r "company-platform.requirements"
error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement in `req.requirements`...
```

**Comment by charliermarsh** [comment]
Thanks. `--trusted-host` is tracked in https://github.com/astral-sh/uv/issues/1339.

**Comment by Cypher1** [comment]
Sorry does this mean `--extra-index-url` is not planned or is this just a duplicate?

**Comment by charliermarsh** [comment]
We actually already support `--extra-index-url` on both the command-line and in `requirements.txt`!

**Comment by Cypher1** [comment]
Ah! Great. Thank you!

**Comment by charliermarsh** [comment]
No prob!
