### ISSUE TITLE
feature: Allow uv pip compile to take input from CLI

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#1845]
I would appreciate it if we could get the resolved packages list without needing to install them into a virtual environment. For example it would be super helpful to be able to do:

```bash
uv resolve -p 3.8 sphinx tox
```

that would equal to:

```bash
rm .venv -rf
uv venv -p 3.8
uv pip install sphinx tox
uv pip freeze
rm .venv -rf
```

**Comment by charliermarsh** [comment]
Is this different than `uv pip compile`?

**Comment by gaborbernat** [comment]
I guess that is the same would one invoke, but without requiring a `requirements.in` file 🤔 

```
uv pip compile -p 3.8 requirements.in --no-annotate --no-header
```

Can pip compile get then a flag to take the input from the CLI? 😆

**Comment by zanieb** [comment]
You can do `echo "foo" | uv pip compile -`

**Comment by zanieb** [comment]
It seems unlikely we'll add another option for direct input to `pip compile` unless we get a lot of feedback that piping is insufficient — I think it's not common enough of a use case to maintain.
