### ISSUE TITLE
Cannot install `flit-core==2.3.0` from source

### ISSUE THREAD

**Issue by adrianeboyd** [astral-sh/uv#1861]
Command, using uv 0.1.7:

```shell
uv pip install "flit-core==2.3.0" --no-cache --no-binary flit-core --reinstall
```

Output:

```none
Resolved 2 packages in 394ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: flit-core==2.3.0
  Caused by: Failed to build: flit-core==2.3.0
  Caused by: Invalid pyproject.toml
  Caused by: TOML parse error at line 4, column 16
  |
4 | backend-path = "."
  |                ^^^
invalid type: string ".", expected a sequence
```

This has been fixed in `flit-core>=3`, but pip installs `flit-core==2.3.0` without errors so pip must be more permissive here. (Actually, it looks the internal type in pip isn't correct in the one place where `backend_path` is typed and then this is unnoticed in practice due to `list(".") == list(["."])`.)

If it weren't a build backend I would not be concerned about an older now-patched version of a library that can't be installed from source, but it's thwarting me in some cases when testing with `--no-binary :all:` for packages with `flit_core<3`.

In general, it might also be useful to have an official supported way to override build requirements, especially given the explicit support of overrides for other purposes?

**Comment by charliermarsh** [comment]
We can make this more permissive.
