### ISSUE TITLE
`cache clean` -> `cache clear`

### ISSUE THREAD

**Issue by nschloe** [astral-sh/uv#1867]
I believe the syntax

```
uv cache clean
```

is a bit misleading. This command doesn't _clean_ the cache (tidy it up), but _clears_ it (remove completely). It should be

```
uv cache clear
```

**Comment by AlexWaygood** [comment]
We probably used "clean" because of [the `cargo clean` command](https://doc.rust-lang.org/cargo/commands/cargo-clean.html), but I agree `clear` feels like it maybe makes more sense from first principles! (And Python devs won't necessarily be familiar with cargo)

**Comment by charliermarsh** [comment]
Yarn and npm also use “clean”.

**Comment by AlexWaygood** [comment]
Precedents from some of the other Python packaging tools:
- `poetry` has a `poetry cache clear` command: https://python-poetry.org/docs/master/cli/#cache-clear
- `pdm` has a `pdm cache clear` command: https://pdm-project.org/latest/reference/cli/#clear
- `hatch` has a `hatch clean` command, but it cleans all build artifacts (so does something a little different to what our `cache clean` command does, IIUC): https://hatch.pypa.io/1.9/cli/reference/#hatch-clean

**Comment by MichaReiser** [comment]
It may be worth considering what we want the command to be in the long term and the brute force deleting (it does tidy it up ;)) is just the implementation behavior for now

**Comment by nschloe** [comment]
Perhaps it makes sense to add a `clear` alias for now.
