### ISSUE TITLE
Can we use uv for dependency management like poetry

### ISSUE THREAD

**Issue by YeonwooSung** [astral-sh/uv#1870]
Just curious, is it possible to use uv for managing and updating the dependencies and dependencies of dependencies just like poetry so that we could replace the poetry with uv?

**Comment by YeonwooSung** [comment]
Ah, nice.
Thanks for the reply.

I will look forward to that day that we could replace the poetry with uv

**Comment by nikhilweee** [comment]
@zanieb Is the roadmap publicly documented somewhere?

**Comment by zanieb** [comment]
Not yet, just in the issue tracker.

**Comment by benjaminbauer** [comment]
because I did not find it in the tracker: is there an issue for platform independent lock files? Will uv wait for the finalization of the mentioned PEP?

What is the currently recommended worklow for managing/freezing dependencies?

**Comment by zanieb** [comment]
We are implementing platform independent lock files and will do so before waiting for a standard to be established. I can't find an issue either, @BurntSushi do you know of one / want to make one?

**Comment by charliermarsh** [comment]
I believe it's here: https://github.com/astral-sh/uv/issues/2679

**Comment by zanieb** [comment]
The lock file work is being tracked in https://github.com/astral-sh/uv/issues/3347 and we're actively adding experimental Poetry-style commands such as `add`, `remove`, `sync`, and `run`.
