### ISSUE TITLE
Requirements.txt empty after compile error

### ISSUE THREAD

**Issue by luchiago** [astral-sh/uv#1879]
I've tried to compile my project requirements from `pyproject.toml` and even with the hint ```specify dependencies in the `project.dependencies` section; `tool.poetry.dependencies` is not currently supported```, my previous `requirements.txt` filled with dependencies was erased. I don't think that's a correct behavior

`uv pip compile pyproject.toml -o requirements.txt --verbose`

```bash
 uv::requirements::from_source source=pyproject.toml
warning: `pyproject.toml` does not contain any dependencies (hint: specify dependencies in the `project.dependencies` section; `tool.poetry.dependencies` is not currently supported)
 uv::requirements::from_source source=requirements.txt
    0.002724s DEBUG uv_interpreter::virtual_env Found a virtualenv named .venv at: /home/lucas/api/.venv
    0.002795s DEBUG uv_interpreter::interpreter Using cached markers for: /home/lucas/api/.venv/bin/python
    0.002820s DEBUG uv::commands::pip_compile Using Python 3.9.7 interpreter at /home/lucas/api/.venv/bin/python for builds
    0.003060s DEBUG uv_client::registry_client Using registry request timeout of 300s
 uv_client::flat_index::from_entries
 uv_resolver::resolver::solve
      0.004159s   0ms DEBUG uv_resolver::resolver Solving with target Python version 3.9.7
   uv_resolver::resolver::choose_version package=root
   uv_resolver::resolver::get_dependencies package=root, version=0a0.dev0
```

My `requirements.txt` after the command:
```txt
# This file was autogenerated by uv via the following command:
#    uv pip compile pyproject.toml -o requirements.txt --verbose

```

uv version: `0.1.7`

**Comment by luchiago** [comment]
If this an actual error and unexpected behavior, I would like to start working on it.

**Comment by zanieb** [comment]
I think is expected, you've asked us to compile requirements for a file with no requirements. We allow this, but we warn you to help figure out if you've made a mistake.

**Comment by luchiago** [comment]
Ok then. Thanks for the reply! I thought it was a strange behavior because even though it was a mistake on my `pyprojetc.toml` wouldn't clear my actual `requirements.txt` with the dependencies.
