### ISSUE TITLE
Rename `uv pip` command

### ISSUE THREAD

**Issue by gotmax23** [astral-sh/uv#1899]
Thanks for your work on uv and ruff! I would like to suggest changing the `uv pip` subcommand name. `uv` and `pip` are different tools. `uv` is not necessarily going to implement the same interface as `pip`. It feels a bit crummy to write a replacement to another tool and then take its name. I would suggest renaming the subcommand to `pkg` or something similar that's more descriptive and won't lead to unnecessary confusion. Leaving `pip` as an undocumented alias makes sense, but I don't think it should be the default name for the package management subcommand.

**Comment by gotmax23** [comment]
Closing as duplicate of https://github.com/astral-sh/uv/issues/1657

**Comment by zanieb** [comment]
Note the intent is only for this to be a compatible interface and we do intend to have entirely separate interfaces for all of the same functionality but with a new workflow. There are many tools with `pip` in the name, e.g. `pipx`, `pip-tools`, etc. Nonetheless, we agree though changing the name might make sense and are considering a few options.
