### ISSUE TITLE
`uv pip compile`: add `--no-upgrade` flag

### ISSUE THREAD

**Issue by gotmax23** [astral-sh/uv#1900]
(Version: uv 0.1.9)

It would be nice if `uv pip compile` had a `--no-upgrade` flag to reverse `--upgrade`. In my projects' nox configurations, we have something like

``` python
@nox.session(name="pip-compile")
def pip_compile(session):
    session.run("pip-compile", "requirements.in", "-o", "requirements.txt", "--upgrade", *session.posargs)
```

so `--upgrade` is the default operation, but sometimes we want to disable that behavior with `nox -e pip-compile -- --no-upgrade`.

**Comment by zanieb** [comment]
Could you just drop `--upgrade` from that command when you see `--no-upgrade`? I think allowing multiple conflicting arguments to be passed leads to too much ambiguity.

**Comment by gotmax23** [comment]
> Could you just drop --upgrade from that command when you see --no-upgrade?

We _could_, but that would definitely make it more complicated.

> I think allowing multiple conflicting arguments to be passed leads to too much ambiguity.


For what it's worth, allowing to invert boolean CLI flags with a `--no-FLAG` option is popular amongst CLI interfaces.
