### ISSUE TITLE
Duplicate git dependencies that resolve to the same commit are treated as conflicting

### ISSUE THREAD

**Issue by rossmacarthur** [astral-sh/uv#1903]
If you have two git dependencies that resolve to the same commit, they could be treated as the same.
```
uv 0.1.9
```

```
# requirements.in
werkzeug @ git+https://github.com/pallets/werkzeug.git@2.0.0
werkzeug @ git+https://github.com/pallets/werkzeug@af160e0b6b7ddd81c22f1652c728ff5ac72d5c74
```

When running `uv pip compile requirements.in`
```
error: Requirements contain conflicting URLs for package `werkzeug`:
- git+https://github.com/pallets/werkzeug.git@2.0.0
- git+https://github.com/pallets/werkzeug@af160e0b6b7ddd81c22f1652c728ff5ac72d5c74
```

However, if you just have 
```
# requirements.in
werkzeug @ git+https://github.com/pallets/werkzeug.git@2.0.0
```

It resolves to that url when running `uv pip compile requirements.in`

```
# requirements.txt
werkzeug @ git+https://github.com/pallets/werkzeug@af160e0b6b7ddd81c22f1652c728ff5ac72d5c74
```

**Comment by rossmacarthur** [comment]
I would have expected #1877 to resolve this, but it doesn't

**Comment by rossmacarthur** [comment]
To clarify the reason I encounter is this:
- I have a git dependency in my `pyproject.toml`
- I generate `requirements.txt` from `pyproject.toml`
- Then I generate `requirements.dev.txt` using `requirements.txt` _and_ `pyproject.toml`  + extra dev as the input.

So if don't put the commit hash as the ref in `pyproject.toml` I get this error.

**Comment by charliermarsh** [comment]
Alternatively you can use your `requirements.txt` as an `--overrides requirements.txt`.

**Comment by rossmacarthur** [comment]
> Can I ask why requirements.txt needs to be an input to the second resolution?

Maybe the following can help explain what error I want to catch:

Consider the following input

```toml
# pyproject.toml

[project]
name = "example"
version = "0.0.0"
dependencies = [
    "pydantic",
]

[project.optional-dependencies]
dev = [
    "pydantic < 2.6.0",
]
```


- **simple case**
   ```
   uv pip compile pyproject.toml -o requirements.txt
   uv pip compile --extra dev pyproject.toml -o requirements.dev.txt
   ```
   Problem: prod and dev now have different versions of pydantic
   
- **using override**
   ```
   uv pip compile pyproject.toml -o requirements.txt
   uv pip compile pyproject.toml --override requirements.txt -o requirements.dev.txt
   ```
   Problem: dev dependency might be broken
   
- **using requirements.txt** as input
   ```
   uv pip compile pyproject.toml -o requirements.txt
   uv pip compile pyproject.toml requirements.txt -o requirements.dev.txt
   ```
   Appropriately errors that the dependencies are unresolvable
