### ISSUE TITLE
[BUG] Running `py --list-paths` failed with status exit code: 0

### ISSUE THREAD

**Issue by arghhjayy** [astral-sh/uv#1904]
Hello fellow devs,

Thank you for giving us uv, I'm so excited to try it!
I just installed it using pip on my Windows 11: `pip install uv`

I have Anaconda installed, so the shell looks like:
`(base) PS C:\Users\MyUserName>`

and when I try to execute `uv venv` as mentioned in the Getting Started guide in README, I get the following error:

```
  × Running `py --list-paths` failed with status exit code: 0:
  │ --- stdout:
  │ -3.10-64       C:\Users\MyUserName\AppData\Local\Programs\Python\Python310\python.exe
  │  -3.9-64        C:\Users\MyUserName\anaconda3\python.exe
  │ --- stderr:
  │ Installed Pythons found by py Launcher for Windows *
  │ ---
```

**Comment by MichaReiser** [comment]
Ah, interesting, so it's Anaconda's py launcher that prints `Pythons found by py launcher for Windows`? 

This should be fixed by https://github.com/astral-sh/uv/pull/1885

**Comment by arghhjayy** [comment]
Thank you for the prompt reply @MichaReiser

**Comment by konstin** [comment]
Do we have instructions how to reproduce this? I'd like to file an upstream bug report

**Comment by arghhjayy** [comment]
> Do you have instructions how to reproduce this? I'd like to file an upstream bug report

In Windows with Anaconda installed, just install: `pip install uv` and do `uv venv`
