### ISSUE TITLE
pip.conf/pip.ini and Artifactory compatability

### ISSUE THREAD

**Issue by Muhtasham** [astral-sh/uv#1907]
Thanks for another great package!

Wanted to ask anybody tested if `uv` also honors `pip.conf/pip.ini` and plays nicely with Artifactory?

**Comment by zanieb** [comment]
Hi!

We don't read `pip.conf` or `pip.ini` (and probably won't since we're a separate tool). The next release will play nicely with Arficatory though (see #1709)

**Comment by astrojuanlu** [comment]
For users `pip.conf` see https://github.com/astral-sh/uv/issues/1404
