### ISSUE TITLE
For uv>0.1.6 Docker/Github Action fails to install package from Github URL 

### ISSUE THREAD

**Issue by mtmpaulwulff** [astral-sh/uv#1914]
In my requirements file i am specifying to install the following package:
`django-celery-beat @ git+https://github.com/celery/django-celery-beat.git@acd10a390c85414a59e9b37be6226e4a9ea4fb81`

The commit does exist in Github: https://github.com/celery/django-celery-beat/commit/acd10a390c85414a59e9b37be6226e4a9ea4fb81

With `uv==0.1.6` the uv pip install process ran without problems.

For `uv>=0.1.8` the process fails with the following error message:

```
------
 > [python-run-stage  6/23] RUN uv pip install --no-cache -r local.txt:
: Failed to download and build: django-celery-beat @ git+https://github.com/celery/django-celery-beat.git@acd10a390c8[541](https://github.com/martalmar/foundation/actions/runs/8020252175/job/21909709543#step:3:542)4a59e9b37be6226e4a9ea4fb81
0.650   Caused by: Git operation failed
0.650   Caused by: failed to clone into: /tmp/.tmpwqm4ZO/git-v0/db/6fd60c06f70cb37a
0.650   Caused by: failed to fetch commit `acd10a390c85414a59e9b37be6226e4a9ea4fb81`
0.650   Caused by: could not execute process `git fetch --force --update-head-ok 'https://github.com/celery/django-celery-beat.git' '+acd10a390c85414a59e9b37be6226e4a9ea4fb81:refs/commit/acd10a390c85414a59e9b37be6226e4a9ea4fb81'` (never executed)
0.650   Caused by: No such file or directory (os error 2)
------
```

- The image is based on `3.10-slim-bullseye`.
- I am installing uv itself with `RUN pip install uv==0.1.9` in my Dockerfile.
- I am setting `ENV VIRTUAL_ENV=/usr/local` in my Dockerfile. But I also tested `RUN uv venv` instead.
- I did not check `uv==0.1.7`
- I can replicate the error within my local Docker build process. 
- I cannot replicate the error in my local Windows environment.

**Comment by charliermarsh** [comment]
Thanks! We changed our git clone which fixed a bunch of issues with authentication, but there must be some non-authentication-related case we regressed on here.

**Comment by charliermarsh** [comment]
@mtmpaulwulff - One question: do you have Git installed in the container? Like does `which git` succeed?
