### ISSUE TITLE
`uv pip install .` and `uv pip install ".[dev]"` do not work, results in error

### ISSUE THREAD

**Issue by boldandbrad** [astral-sh/uv#1945]
## Description

Installing the current package via `uv pip install .` or its dev deps via `uv pip install ".[dev]"` do not work, results in error.

## Env

Platform: macOS 14.3.1 (Intel)
shell: zsh
uv version: 0.1.9

## Reproduce

Reproduce with by running either `uv pip install .` or `uv pip install -v ".[dev]"` in the root of a python project containing a uv created venv, and pyproject.toml with dev dependencies specified.

Output:

```
 uv::requirements::from_source source=.[dev]
error: Failed to parse `.[dev]`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
.[dev]
^
```

It appears uv is failing to recognize `.` as the current package. I expect this to work since it does with pip and the uv readme claims that installing dev deps by package name is valid with the following syntax `uv pip install "package[dev]"`

Interestingly, it works if you specify `-e`. But I don't always want to install the package in editable mode if I just want to get dev or test deps installed.

It's also worth mentioning that more pip-like syntax `uv pip install ."[dev]"` (dot outside the quotes) does not work either, as it does with pip itself.

**Comment by charliermarsh** [comment]
Thanks -- we support `uv pip install "package_name[dev] @ ."` and `uv pip install -e ".[dev]"`. For non-editable requirements, we require a package name right now. We'll lift this restriction in the future. You can track it in https://github.com/astral-sh/uv/issues/313.

**Comment by charliermarsh** [comment]
This is supported as of `v0.1.24`. You can `uv pip install .[dev]` directly, without including a package name.
