### ISSUE TITLE
Failed to install cchardet

### ISSUE THREAD

**Issue by chrisgoddard** [astral-sh/uv#1946]
Error install cchardet==2.1.7

```--- stderr:
src/cchardet/_cchardet.cpp:196:12: fatal error: 'longintrepr.h' file not found
  #include "longintrepr.h"
           ^~~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit code 1```

Mac (intel) OSX 14.2.1 - though I had the same issue on my M1.

**Comment by chrisgoddard** [comment]
Oh weird - 3.12 actually. Normal pip works but I'll check out the fork

**Comment by hauntsaninja** [comment]
Yeah, cchardet is dead. Fwiw, seems like a lot of people are switching to charset_normalizer anyway

**Comment by chrisgoddard** [comment]
I'll check that out - quite a few scraping libs have it as an optional dependency for performance.

**Comment by notatallshaw-gts** [comment]
> I'll check that out - quite a few scraping libs have it as an optional dependency for performance.

FYI there is a mypyc mode for charset-normalizer for some performance improvement: https://charset-normalizer.readthedocs.io/en/latest/community/speedup.html

**Comment by zanieb** [comment]
It looks like there's nothing for us to address here.
