### ISSUE TITLE
Audit does not include check for new extras

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1948]
Adding an extra does not update the package without `--upgrade`, e.g.

```
❯ uv pip install packse
...
❯ packse index up
Using index commands requires installation with extra 'index'.
❯ uv pip install "packse[index]"
Audited 1 package in 10ms
❯ uv pip install "packse[index]" --upgrade
Resolved 33 packages in 368ms
Downloaded 1 package in 102ms
Installed 1 package in 13ms
 + pypiserver==2.0.1
```

If feasible, we should include this in audits.

**Comment by skshetry** [comment]
Maybe https://github.com/astral-sh/uv/issues/1651 is also related? 

It does not pick any new dependencies, on either editable or non-editable installs.

```console
uv pip install "."
Audited 1 package in 2ms
```

But the `--upgrade` works.

**Comment by charliermarsh** [comment]
I think editable are slightly different, but I’ll be looking into both this weekend or early next week.

**Comment by charliermarsh** [comment]
I'm unable to reproduce this. Is it possible you're on an older version? (We did fix this in https://github.com/astral-sh/uv/pull/1727.)

**Comment by zanieb** [comment]
Yep older version — sorry so many shims around.
