### ISSUE TITLE
[Question] Could we deprecate `pip sync` in favor of `pip install -r`?

### ISSUE THREAD

**Issue by T-256** [astral-sh/uv#1967]
We can consider `uv pip install -r <LOCKFILE>` instad of `uv pip sync <LOCKFILE>`:

```shell
uvtest> uv venv
Using Python 3.7.9 interpreter at C:\Python37\python.exe
Creating virtualenv at: .venv
Activate with: .venv\Scripts\activate

uvtest> uv pip install -r requirements.txt
Resolved 9 packages in 7ms
Installed 9 packages in 99ms
 + anyio==3.7.1
 + certifi==2024.2.2
 + exceptiongroup==1.2.0
 + h11==0.14.0
 + httpcore==0.17.3
 + httpx==0.24.1
 + idna==3.6
 + sniffio==1.3.0
 + typing-extensions==4.7.1

uvtest> uv pip install -r requirements.txt
Resolved 9 packages in 5.25s
Downloaded 1 package in 1.86s
Installed 1 package in 60ms
 - anyio==3.7.1
 + anyio==3.7.0

uvtest> uv pip sync requirements.txt
Uninstalled 1 package in 11ms
Installed 1 package in 62ms
 - anyio==3.7.0
 + anyio==3.7.1
```

**Comment by T-256** [comment]
I just checked that all command options of `pip sync` are available at `pip install` and nothing more provided from `pip sync`.

**Comment by zanieb** [comment]
Syncing is different, it will remove packages in the virtualenv not present in the requirements.

**Comment by charliermarsh** [comment]
Yeah, there are two keys differences:

1. As Zanie mentioned, syncing ensures that your environment exactly matches the requirements (and so will remove extraneous packages).
2. `uv pip sync` doesn't do any dependency resolution -- it only installs the exact packages in the lockfile (i.e., it assumes the input lockfile is the `uv pip compile` output).

**Comment by T-256** [comment]
> 1\. As Zanie mentioned, syncing ensures that your environment exactly matches the requirements (and so will remove extraneous packages).

Correct, what about use it as an option for `pip install` instead of making it separated command:
- `pip install --sync -r req.txt`

> 2\. `uv pip sync` doesn't do any dependency resolution -- it only installs the exact packages in the lockfile (i.e., it assumes the input lockfile is the `uv pip compile` output).

same as what's `--no-deps` currently doing? then we could specify `--sync` auto invokes `--no-deps`.
