### ISSUE TITLE
Does `--find-links <local-path> --offline` allow packages to be used?

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#1974]
Does `uv` pull packages from e.g. a `--find-links .../site-packages` when `--offline` is used? I don't think so, I think it only reads from the cache — but it should allow loading from local paths right?

**Comment by charliermarsh** [comment]
I think it should allow that. Does it not?

**Comment by zanieb** [comment]
I think it does

```
❯ uv pip install --no-index --find-links ~/workspace/packse/vendor/build --force-reinstall wheel --offline --no-cache
Resolved 1 package in 8ms
Downloaded 1 package in 5ms
Installed 1 package in 5ms
 - wheel==0.42.0
 + wheel==0.42.0
```

I think I got confused because I thought `--find-links` would find unpackaged distributions in `site-packages`.
