### ISSUE TITLE
`Failed to spawn the python child process: The system cannot find the file specified.`

### ISSUE THREAD

**Issue by astrojuanlu** [astral-sh/uv#1988]
Still not able to provide a minimal reproducer, but I'm putting this here in case it helps other folks.

I'm trying to replace `pip` with `uv pip` on my CI and I've been mostly successful, with the exception on Windows. There I'm getting an error like this:

```
> pytest tests
(uv internal error) Failed to spawn the python child process: The system cannot find the file specified.
```

this is despite `pytest` being present, as can be seen with a `uv pip freeze` right before.

See https://github.com/kedro-org/kedro-plugins/actions/runs/8052616036/job/21993159176 for an example of this.

The way I fixed it is by replacing `pytest` with `python -m pytest`.

I added a `type ${Python_ROOT_DIR}\\Scripts\\pytest` to understand what's there, see https://github.com/kedro-org/kedro-plugins/actions/runs/8053504403/job/21996069725?pr=569

I'm using `uv==0.1.11`, released minutes ago.

I'm unfamiliar with how scripts are created on Windows, is `uv` doing anything special here?

**Comment by MichaReiser** [comment]
I think the issue is related to https://github.com/astral-sh/uv/issues/1779

The `VIRTUAL_ENV=<global_python>` hack doesn't work on Windows because the Python executable is in a different location than what's expected by `uv`. We're working on a proper support for global installation. 

For now, you can work around it by creating a virtual env instead of pointing `VIRTUAL_ENV` to the global python path.

**Comment by kexul** [comment]
I'm still getting this error with the newest version of uv.

**Comment by konstin** [comment]
Do you mean 0.1.11 or the main branch?

**Comment by kexul** [comment]
> Do you mean 0.1.11 or the main branch?

yes

**Comment by MichaReiser** [comment]
> > Do you mean 0.1.11 or the main branch?
> 
> 0.1.11

Charlie's changes have not been released yet. Please create a new issue if you're still experience issues with the new version that we release soon and include more details: What commands did you run? What's your operating system? What package do you use, etc.
