### ISSUE TITLE
uv fails to resolve package if published in non normalized format

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#1989]
Assume a package is published as `magic.demo.hera`. If you do `uv pip install magic.com` this correctly, redirects to `https://m.com/artifactory/api/pypi/magic-pypi/simple/magic-demo-hera/"`. However, if the page then contains packages in the form of:

```
magic.demo.hera-0.9.5+frozen-py3-none-any.whl
magic.demo.hera-0.9.5+release.tar.gz
```

uv comes back with:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of magic-demo-hera==0.9.5 and you require magic-demo-hera==0.9.5, we can conclude that the requirements are unsatisfiable.
```

This works with pip today though.

**Comment by charliermarsh** [comment]
I believe this is the same as https://github.com/astral-sh/uv/issues/1855. @BurntSushi is working on it this week.
