### ISSUE TITLE
Dynamic optional dependencies not audited upon re-install

### ISSUE THREAD

**Issue by kendallbailey** [astral-sh/uv#1991]
uv version: 0.1.11
platform: Ubuntu 20.04, python 3.10

I have a `pyproject.toml` that uses dynamic optional dependencies

```
[tool.setuptools.dynamic]
optional-dependencies.tests = {file = ["reqs/test.txt"]}
```

After an editable install using `uv`, and then editing the `reqs/test.txt` file, a re-install doesn't notice the changes in the optional dependencies the way `pip` does.  I have to `touch pyproject.toml` to convince `uv` to look at the dynamic optional dependencies and ensure the changes are applied to the environment. I'm used to doing `pip install -e ".[tests]"` after updating `test.txt`, but `uv pip install -e ".[tests]"` says "Audited 1 package in 90ms" and does not install the package(s) that were added to `test.txt`.

The above is a simplified example. In reality I have multiple optional dependencies, many of which involve multiple `.txt` files.

**Comment by charliermarsh** [comment]
This is mostly by design. We don't validate changes across the full environment. But you can pass `--reinstall` to force it.

**Comment by sbidoul** [comment]
@charliermarsh would you reconsider this? Checking the timestamp of pyproject.toml makes sense except when some metadata is declared as dynamic, in which case it can be computed from other sources than pyproject.toml itself. This way you could have the fastest performance for fully static pyproject.toml, but keep a correct behaviour for those who need dynamic metadata.

**Comment by charliermarsh** [comment]
@sbidoul -- Yeah definitely open to reconsidering it, but how could we "tell" that some metadata is dynamic?

**Comment by charliermarsh** [comment]
Oh, if you have the above in your `pyproject.toml`, does it in turn require that have you `dynamic = ["dependencies"]` set?

**Comment by sbidoul** [comment]
If there is a `[project]` table, yes, every dynamic metadata MUST be declared in `project.dynamic`. If there is no `[project]` table, everything is to be considered dynamic.

**Comment by charliermarsh** [comment]
That makes sense, we can probably support this.

**Comment by charliermarsh** [comment]
Or rather, we can support this, I just have to get through a few other things first.
