### ISSUE TITLE
Requirement with `--only-binary apache-beam` fails to resolve even though solution exists

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#2003]
Python 3.11.6, Linux x64, uv 0.1.11

```
$ echo "apache-airflow[all]" | uv pip compile - --only-binary apache-beam
error: Failed to download and build: apache-beam==2.2.0
  Caused by: Building source distributions is disabled
```

But a solution exists because if I put a lower bound on `apache-beam` so that my environment can always get a wheel it can resolve:

```
$ echo -e "apache-airflow[all]\napache-beam>=2.47" | uv pip compile -
Resolved 546 packages in 6.30s
...
apache-beam==2.54.0
    # via apache-airflow-providers-apache-beam
...
```

**Comment by charliermarsh** [comment]
IIRC, `--only-binary` doesn't affect the resolution -- it just disallows building from source. Like, we don't _skip_ versions that lack binaries, we just error if you try to build one. I don't know if this was intentional, @zanieb would know when they're back from vacation.

**Comment by notatallshaw** [comment]
Interesting, pip definetly uses this to determine what is resolved: https://pip.pypa.io/en/stable/development/architecture/upgrade-options/#controlling-what-gets-considered

I wouldn't of normally tried this but this comment indicated it would work like that with uv but I can't reproduce them resolving it: https://github.com/astral-sh/uv/issues/1560#issuecomment-1949626187

**Comment by zanieb** [comment]
Yeah this sounds unintentional. I think `--no-binary` is taken into consideration during resolutions i.e. we mark distributions with only wheels as unusable but I don't think we don't do the same for `--only-binary` right now? I could take a look at this as part of (or after) #1298

**Comment by charliermarsh** [comment]
Looking into this, I think I see the path forward.

**Comment by charliermarsh** [comment]
I believe this is closed by https://github.com/astral-sh/uv/pull/1298 (merged but not yet released).
