### ISSUE TITLE
UV pip list does not give system package list.

### ISSUE THREAD

**Issue by GadgetSteve** [astral-sh/uv#2005]
The command `uv pip list` **when run outside of a virtual environment** _or conda installation_ does not list any system level packages.
```
$ uv pip list
error: Failed to locate a virtualenv or Conda environment (checked: `VIRTUAL_ENV`, `CONDA_PREFIX`, and `.venv`). Run `uv venv` to create a virtualenv.
```
Platform: Windows 11 (64 bit)
Version: uv 0.1.11 (32e5cacdd 2024-02-26)

**Comment by zanieb** [comment]
I think this requires https://github.com/astral-sh/uv/pull/2000

**Comment by charliermarsh** [comment]
Yeah, we now have the capability to list packages in a system environment, so we can support this.

**Comment by zanieb** [comment]
Maybe a good "second" issue :)

**Comment by charliermarsh** [comment]
Oops too late
