### ISSUE TITLE
Editable '-e.' w/o space works in pip, fails in uv

### ISSUE THREAD

**Issue by jensens** [astral-sh/uv#2007]
I have a `requirement.txt` like so
```
-c constraints.txt
-e.[test]
``` 
which works with  `pip install -r requirements.txt`, but `uv pip install -r requirements.txt` fails with `error: Expected '=' or whitespace, found Some('.') in `requirements-mxdev.txt` at position 282`
(side quest: why in 282, does it concat the constraints and forgets about the real line number?)

if I change the `requirements.txt` to contain a space after the dot it works
```
-c constraints.txt
-e .[test]
``` 

Versions
- Linux 6.5.0-18-generic 18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- uv 0.1.10
- Python 3.12.2

**Comment by konstin** [comment]
>  (side quest: why in 282, does it concat the constraints and forgets about the real line number?)

The parser doesn't have the mapping back to line numbers implemented: https://github.com/astral-sh/uv/issues/2012

**Comment by charliermarsh** [comment]
@konstin - Is this allowed in the grammar, or it "just works"? It seems strange to me.

**Comment by konstin** [comment]
The requirements.txt doesn't have a grammar, it is effectively pip cli arguments written to a file; The most comprehensive docs we have is https://pip.pypa.io/en/stable/reference/requirements-file-format/. At least all official examples i've seen use a space. I would prefer enforcing the space after `-e` for clarity.

**Comment by charliermarsh** [comment]
Yeah, I agree.

**Comment by jensens** [comment]
I just stumbled over it and since it works in pip I reported this. I have no idea how close you plan to have compatibility with pip. It is good to have a clear syntax, so enforcing a space makes sense. 

Anyway, I would at least add a short section to the docs with those things that are meant to possibly break.

**Comment by konstin** [comment]
Yes, we definitely want to track those differences.

Closing in favor of #2023.
