### ISSUE TITLE
Use Metadata 2.2+ for source distributions

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#2009]
When a source distribution contains a PKG-INFO file at the top level with `Metadata-Version: 2.2` or `Metadata-Version: 2.3` and neither `Dynamic: Requires-Dist` nor `Dynamic: Provides-Extra`, we can use the information in PKG-INFO as reliable metadata without calling any PEP 517 hooks or even setting up the build env. While the PEP has been accepted for some time, this is now supported by at pypi (https://github.com/pypi/warehouse/pull/13606).

After downloading and unpacking[^1], we can read `PKG-INFO` with the same utils as `METADATA` and given the preconditions perform no build in `uv pip compile`. This should provide a significant speedup as more package are published with metadata 2.2+. 

[pyo3-mixed 2.1.5](https://inspector.pypi.io/project/pyo3-mixed/2.1.5/packages/2b/b8/e04b783d3569d5b61b1dcdfda683ac2e3617340539aecd0f099fbade0b4a/pyo3_mixed-2.1.5.tar.gz/pyo3_mixed-2.1.5/PKG-INFO)

[^1]: I don't think .tar.gz has a central directory we could use for the same remote partial reading trick as for zips, but i can't find a good source.

**Comment by charliermarsh** [comment]
Yes!!!

**Comment by sbidoul** [comment]
Note `Version` can be dynamic too.

**Comment by charliermarsh** [comment]
I might do this because it looks fun.
