### ISSUE TITLE
`Intepreter::query` was made `pub(crate)`

### ISSUE THREAD

**Issue by tdejager** [astral-sh/uv#2015]
Hi!

Because we are integrating uv into pixi https://github.com/prefix-dev/pixi/pull/863, we are using the `Interpreter::query` function, to query the python interpreter that we passed in (our project allows for multiple python version at the same time), this used to be a `pub` function, but was changed to a `pub(crate)` somewhere in the last days.

Would it be possible to change this back? As there is no other way to use the correct `PythonInfo` other than querying it yourself.

Thanks!

**Comment by tdejager** [comment]
Said function: https://github.com/astral-sh/uv/blob/f487b2e8c18f1667f2afd03b560b6e6eeb586b16/crates/uv-interpreter/src/interpreter.rs#L38

**Comment by tdejager** [comment]
Made a PR for it: https://github.com/astral-sh/uv/pull/2016

**Comment by charliermarsh** [comment]
Yup, sorry!
