### ISSUE TITLE
Add support for NO_PROXY or equivalent

### ISSUE THREAD

**Issue by rth** [astral-sh/uv#2021]
A few more edge cases in enterprise environments, where some package indexes might need to go though a proxy while other don't. 
In pip this is handled [through the vendored requests package](https://github.com/pypa/pip/blob/0ad4c94be74cc24874c6feb5bb3c2152c398a18e/src/pip/_vendor/requests/sessions.py#L306) which allows,
 - defining `HTTP_PROXY` env variable to define the proxy
 - the `NO_PROXY` env variable to define domains that shouldn't be proxied

More related discussion in https://github.com/pypa/pip/issues/5378#issuecomment-388183686.

Currently as far as I can tell uv respects  `HTTP_PROXY` but ignores the `NO_PROXY`.  Having some mechanism for it would be nice.

**Comment by zanieb** [comment]
Is there support for this in [`reqwest`](https://docs.rs/reqwest/latest/reqwest/)? I think we basically rely on them for networking behavior

**Comment by barbet** [comment]
NO_PROXY in reqwest seems implemented [here](https://github.com/seanmonstar/reqwest/blob/master/src/proxy.rs#L448) originating in [this PR](https://github.com/seanmonstar/reqwest/pull/877)

**Comment by rth** [comment]
Yes, indeed. Maybe it was some other issue on my end. Thanks closing.
