### ISSUE TITLE
Formalize policy on pip compatibility

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/uv#2023]
We should define a formal policy on the pip functionality and workflows we want and don't want to support. This helps us triaging issues and users to understand the scope of `uv pip`.

**Comment by charliermarsh** [comment]
We now have a document that summarizes our compatibility policy, and highlights many of the areas of incompatibility: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md
