### ISSUE TITLE
Error while installing pytorch with uv

### ISSUE THREAD

**Issue by Tanmaypatil123** [astral-sh/uv#2037]
I am facing issues in installing Python using uv package installer.

I am executing `uv pip install --pre torch torchvision torchaudio --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cu118`.

I was not able to find related documentation so any help would be appreciated.

**Comment by konstin** [comment]
Could you post the error message you got?

**Comment by jensens** [comment]
Probably because of `--pre` - I just stumbled over the same issue. Same in uv is `--prerelease=allow`. Another thing to document as pip incompatibility (see also #2023)
Question is it would not be better to keep `--pre` working as it is use a lot with pip.

**Comment by zanieb** [comment]
I created an issue for that at #2047 

Is your issue resolved with prereleases allowed?

**Comment by charliermarsh** [comment]
Closing for now, as I suspect this is resolved by the docs in https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers.
