### ISSUE TITLE
Managing dependencies on top of system site-packages

### ISSUE THREAD

**Issue by fbergroth** [astral-sh/uv#2038]
Hi,

I'm currently working with the docker image `l4t-pytorch`, which already includes certain system libraries like `torch==2.0.0a0+ec3941ad.nv23.2`.

My goal is to add extra dependencies on top of this and manage them with uv, while pinning the preinstalled version of torch.

I'm trying to this via a venv with system-site-packages and declaring a dependency on `torch==2.0.0a0`, which fails since it can't resolve dependencies.

Is there any trick to do this or something I might have overlooked?

Thanks

**Comment by fbergroth** [comment]
Thanks for having a look. I believe I can already work around the first of the two linked issues, and I'm not sure the last one applies.

My core issue seems to be that the version of torch already installed has a pre-release identifier (I don't think the local version identifier is the issue here). I'm trying to use the system version by pinning torch to this version (`2.0.0a0`), but `uv pip compile` fails since it can't find it in any package index. I'm not sure of the best way to handle this.

**Comment by fbergroth** [comment]
I think the scenario is too odd and doesn't really make sense to support.

**Comment by YodaEmbedding** [comment]
Is this supported?

```bash
$ uv venv --system-site-packages
$ uv run --no-sync python -c 'import torch; print(f"{torch.__version__=}")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

**Comment by konstin** [comment]
It's not supported yet, see https://github.com/astral-sh/uv/issues/2500
