### ISSUE TITLE
uv pip install error: No such host is known. (os error 11001)

### ISSUE THREAD

**Issue by contang0** [astral-sh/uv#2043]
I am trying to use uv in a corporate environment and unfortunately packages fail to install. I get the following error:

```
error: error sending request for url (https://pypi.org/simple/networkx/): error trying to connect: dns error: No such host is known. (os error 11001)
  Caused by: error trying to connect: dns error: No such host is known. (os error 11001)
  Caused by: dns error: No such host is known. (os error 11001)
```

* The command you invoked (e.g., `uv pip sync requirements.txt`), ideally including the `--verbose` flag.

uv pip install networkx

* The current uv platform.

Windows 11

* The current uv version (`uv --version`).

uv 0.1.11 (32e5cacdd 2024-02-26)

**Comment by konstin** [comment]
Do you know some details about your proxy setup?

**Comment by contang0** [comment]
Hardly.. we're a big organisation. I know that we're using certificates to bypass a proxy, but not much more.

**Comment by samypr100** [comment]
> I know that we're using certificates to bypass a proxy

What's you pip.conf file like?

Do you configure a custom CA certificate like `pip config set global.cert /path/to/your/ca-bundle.crt`
or do you set some environment variables like `REQUESTS_CA_BUNDLE` or anything like described in https://pip.pypa.io/en/stable/topics/https-certificates/#using-a-specific-certificate-store

**Comment by samypr100** [comment]
@konstin we can probably add support to allow users to specify their own CA bundles for `uv-client` like pip allows? Maybe `UV_CERT` to be similar to of `PIP_CERT` or `UV_CA_BUNDLE`? Which would mean it reads it in and adds it as part of https://messense.github.io/bosonnlp-rs/reqwest/struct.ClientBuilder.html#method.add_root_certificate

**Comment by zanieb** [comment]
You can use `SSL_CERT_FILE` since we're using [`rustls-native-certs`](https://github.com/rustls/rustls-native-certs)

There's a `pip.conf` issue at #1404

**Comment by contang0** [comment]
I had a look at my pip.ini (which is, I believe, the Windows alternative of pip.conf). It actually doesn't have any configuration for certs, just URLs to our Artifactory server that I think hosts a copy of pypi. We use our own copy for security reasons.

So I believe I would need a way to point uv to our local artifactory server rather than looking up pypi.

```
[global]
# pypi-remote is a local mirror of https://files.pythonhosted.org
index-url = https://artifactory.url/api/pypi/pypi-remote/simple
# pypi-local is a repository for packages developed at our organisation
extra-index-url = https:///artifactory.url/artifactory/api/pypi/pypi-local/simple

[search]
index = https://artifactory.url/artifactory/api/pypi/pypi-remote/
```

**Comment by zanieb** [comment]
You can set the `UV_INDEX_URL` and `UV_EXTRA_INDEX_URL` environment variables or use the corresponding CLI flags.

**Comment by charliermarsh** [comment]
Gonna tentatively close this out, since the thread suggests this is solved by the env vars.
