### ISSUE TITLE
Support remote url constraints?

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#2067]
One feature pip has for constraints file is specifying a URL, it is used to effect in the Airflow installation guide: https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html

> pip install "apache-airflow[celery]==2.8.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.8.2/constraints-3.8.txt"

However this does not work for uv:

```
$ echo "apache-airflow==2.3.4" | uv pip compile - --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.4/constraints-3.10.txt"
error: failed to open file `https://raw.githubusercontent.com/apache/airflow/constraints-2.3.4/constraints-3.10.txt`
  Caused by: No such file or directory (os error 2)
```

I don't think it's a very important feature, but Airflow uses are used to it from pip.

**Comment by charliermarsh** [comment]
I think this is the same as https://github.com/astral-sh/uv/issues/1332.

**Comment by notatallshaw** [comment]
Oh yeah.
