### ISSUE TITLE
Weird interaction between pyenv and `uv pip install --python ...`

### ISSUE THREAD

**Issue by edgarrmondragon** [astral-sh/uv#2068]
The `--python` flag seems to be following some form of symlink for the python interpreter, which is causing packages to be installed outside of the desired virtual environment. Here's a reproducible example:

```console
$ uv --version
uv 0.1.12 (f68b2d1d5 2024-02-28)

$ uv venv venv --python python3.11
Using Python 3.11.8 interpreter at /Users/me/.pyenv/versions/3.11.8/bin/python3.11
Creating virtualenv at: venv
Activate with: source venv/bin/activate

$ uv pip install --no-cache --python venv/bin/python cowsay
Resolved 1 package in 771ms
Downloaded 1 package in 277ms
Installed 1 package in 9ms
 + cowsay==6.1

$ ./venv/bin/cowsay -t moo
zsh: no such file or directory: ./venv/bin/cowsay
```

So you can notice the package was not installed in the virtual environment, but in the source Python interpreter:

```console
$ /Users/me/.pyenv/versions/3.11.8/bin/python3.11 -m cowsay -t moo
  ___
| moo |
  ===
   \
    \
      ^__^
      (oo)\_______
      (__)\       )\/\
          ||----w |
          ||     ||
```

If I repeat the same steps but instead of using the `--python` flag, I activate the virtual environment and then install cowsay, it works as expected:

```console
$ (venv) uv pip install --no-cache cowsay
Resolved 1 package in 771ms
Downloaded 1 package in 277ms
Installed 1 package in 9ms
 + cowsay==6.1

$ ./venv/bin/cowsay -t moo
  ___
| moo |
  ===
   \
    \
      ^__^
      (oo)\_______
      (__)\       )\/\
          ||----w |
          ||     ||
```

Is this all expected and I'm just using the `--python` flag wrong, or is this a bug?

**Comment by charliermarsh** [comment]
Can you re-run the `uv pip install --no-cache --python venv/bin/python cowsay` command with `--verbose`?

**Comment by edgarrmondragon** [comment]
Here you go!

```console
$ uv --verbose pip install --no-cache --python venv/bin/python cowsay
 uv::requirements::from_source source=cowsay
 uv_interpreter::python_query::find_requested_python request=venv/bin/python
      0.002480s   0ms DEBUG uv_interpreter::python_query Starting interpreter discovery for Python venv/bin/python
      0.003579s   1ms DEBUG uv_interpreter::interpreter Probing interpreter info for: /Users/me/.pyenv/versions/3.11.8/bin/python3.11
      0.034149s  31ms DEBUG uv_interpreter::interpreter Found Python 3.11.8 for: /Users/me/.pyenv/versions/3.11.8/bin/python3.11
    0.034411s DEBUG uv::commands::pip_install Using Python 3.11.8 environment at /Users/me/.pyenv/versions/3.11.8/bin/python3.11
Audited 1 package in 35ms

```

**Comment by charliermarsh** [comment]
My guess is we shouldn't be canonicalizing paths (i.e., following symlinks) for pyenv shims, I'll play around with it...

**Comment by charliermarsh** [comment]
We should def fix this but can I ask what the motivation is for using `--python` with a virtualenv? (Did you see this behavor with non-venv Python?)

**Comment by edgarrmondragon** [comment]
> We should def fix this but can I ask what the motivation is for using `--python` with a virtualenv? (Did you see this behavor with non-venv Python?)

So, we create venvs and install packages in them on behalf of users. That involves calling the equivalent of `./venv/bin/python -m pip install ...` ([source code](https://github.com/meltano/meltano/blob/e61deee2d39667cc5065b1f178d8b4bdf2910b2c/src/meltano/core/venv_service.py#L447-L456)).

We are able to do that because pip is seeded into every virtual environment, but that's not the case with uv, so I figured `--python` would allow us to get similar behavior.

I guess an alternative is to pass `VIRTUAL_ENV=./venv/bin/python` to the subprocess uv call 🤷‍♂️.

**Comment by charliermarsh** [comment]
Yeah, I think either should work (though the pyenv behavior is buggy, will fix).

**Comment by charliermarsh** [comment]
(I see the issue, will fix for the next release.)
