### ISSUE TITLE
uv installs an old version of Django

### ISSUE THREAD

**Issue by wathika-eng** [astral-sh/uv#2075]
uv pip install Django gets django 4.2 instead of 5.0

**Comment by konstin** [comment]
Could you please add the commands you used, your operating system and your python version?

**Comment by woutervh** [comment]
This is not reproducible in a new venv,  (using uv 0.1.12)

```
 uv pip install Django
Resolved 3 packages in 212ms
Downloaded 3 packages in 3.22s
Installed 3 packages in 1.06s
 + asgiref==3.7.2
 + django==5.0.2
 + sqlparse==0.4.4
```

**Comment by charliermarsh** [comment]
Going to close for now in the absence of more info.
