### ISSUE TITLE
Cross-platform support

### ISSUE THREAD

**Issue by michaelboyd2** [astral-sh/uv#2079]
My goal is to support building OCI (docker) images for a platform other than the host platform.

For reasons related to our tooling (we use Bazel and want hermetic builds), we do not want to do this via running `pip install` commands on the image itself (as would be normal in a Dockerfile).

The solution we have now is to download wheels for different platforms using `pip download --platform`. We can then pass the appropriate target depending on which platform we are building for. This method has the downside that we need appropriate wheels to exist for the packages we want to use (this sometimes involves creating our own).

Is there any way to achieve my goal with uv? Support for `uv pip download --platform` would be sufficient, but it would be ideal to be able to not need the wheels. `uv pip install --platform` or similar would be even better (no idea if this is at all feasible).

**Comment by ah-quant** [comment]
@michaelboyd2 sorry for reviving this ancient issue just for a request, but ... do you have any public repo combining uv (best case using it from a recent rules_python) with rules_oci? I'd soooo love to see one.

**Comment by michaelboyd2** [comment]
@ah-quant I don't have anything public sorry. I think I understand what you want, but I am not sure we have a really good solution to this although maybe we could eventually create one if needed. Here are some resources I gathered that might be slightly helpful?

https://github.com/theoremlp/rules_uv?tab=readme-ov-file#multi-platform-setup
https://rules-python.readthedocs.io/en/latest/pypi-dependencies.html#bazel-downloader-and-multi-platform-wheel-hub-repository

Here are some slightly outdated docs that we have - no longer sure that this the best solution:


# Cross-Platform Support for Python

rules_py relies on pip under the hood to manage 3rd party dependencies. Pip doesn't deal with
cross-platform builds by default. This macro adds support by providing multiple pip repositories
(one per platform/architecture) to choose from when building the artifacts (such as oci images). The
logic is:

- For each platform you need to support, define a pip repository in _WORKSPACE_ similar to below:

```starlark
load("@python//3.11:defs.bzl", python_3_11_interpreter = "interpreter")

# Download explicit x86_64 Linux wheels for dependencies that are not cross-platform
load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip_linux_amd64",
    download_only = True,
    extra_pip_args = [
        "--platform",
        "manylinux2014_x86_64",
    ],
    python_interpreter_target = python_3_11_interpreter,
    requirements_lock = "//third-party-deps/python:requirements_lock.txt",
)

load("@pip_linux_amd64//:requirements.bzl", "install_deps")

install_deps()

```
> [CAUTION] Make sure you point to a valid `python_interpreter_target` and update
> `requirements_lock` according to your repo setup

- In _root_ BUILD file, call the macro specifying which pip_repository to use per platform. example:

```starlark
load("@bp_bazel//prelude/python/crossplatform:python_cross_platform.bzl", "generate_py_cross_platform_aliases")

generate_py_cross_platform_aliases(
    name = "cross_platform_aliases",
    platforms = {
        "@bp_bazel//prelude/platforms:is_linux_amd64": "pip_linux_amd64",
        "@bp_bazel//prelude/platforms:is_linux_arm64": "third_party_python_deps",
        "@bp_bazel//prelude/platforms:is_darwin_amd64": "third_party_python_deps",
        "@bp_bazel//prelude/platforms:is_darwin_arm64": "third_party_python_deps",
    },
)
```

So when building for linux_amd64, pip_linux_amd64 repo would be used to reference dependencies...

> [CAUTION] by default, the macro expects to be called from root BUILD file

- Add the below gazelle directives to your root BUILD file to use the new py_library and py_binary
  macros generated

```starlark
# gazelle:map_kind py_binary py_binary @bp_bazel//prelude/python/crossplatform:python_cross_platform.bzl
# gazelle:map_kind py_library py_library @bp_bazel//prelude/python/crossplatform:python_cross_platform.bzl
```

- Add below flags to .bazelrc, otherwise OCI image will fail to build

```starlark
# this is flipped by default in bazel 7 but causes issues with OCI tarball
common --noincompatible_enable_cc_toolchain_resolution
```

## Wheels

Wheels are the standard binary packaging format for Python. Almost every package provides wheels,
and you can check by browsing to PyPI and checking the "Built Distribution" section under Download
files. [Example](https://pypi.org/project/requests/#files).

Sadly, there is a tiny minority of packages that do not provide wheels, and only publish a source
distribution (a `.tar.gz` file) that needs to be compiled on the host. This will make our
cross-platform pip repository fail, because we explicitly request a binary compatible with Linux
x64. A list of known dependencies without wheels is below:

- pdpyras (PagerDuty SDK)
- pendulum
- pypika

**Please DO NOT add new dependencies (or transitive dependencies) without wheels available.** This
is an indication of a poorly maintained package and is simply a pain to deal with. If you really
have no alternative, please use the guidance below to build and mirror the package to Artifactory.

### Mirroring a Wheel to Artifactory

This will need to be done every time the package version or Python version is upgraded. If you're
upgrading the package version, check and see if the author has already published some wheels. If
they have, no action is required.

#### Building the Wheel

To create the wheel for a package, run `pip wheel` with the package name and version like so:

```bash
(.venv) ➜  accelerate-monorepo git:(bazel-macos) ✗ pip wheel --wheel-dir=/tmp pdpyras==5.1.3
Collecting pdpyras==5.1.3
  Downloading pdpyras-5.1.3.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
```

This will create a `.whl` file in the directory specified by `--wheel-dir` which should look
something like this:

```bash
Created wheel for pdpyras: filename=pdpyras-5.1.3-py3-none-any.whl size=24227 sha256=ba74a956864426dc2e789a6da0c56a6f7bbd004e6e71f598474aa174f599202c
```

If your `.whl` ends in `none-any.whl`, proceed to the next step to upload it. If your wheel contains
a bunch of OS-specific metadata instead of `none-any.whl`, you'll need to build a wheel for each
platform.

Here's an example:

```bash
Created wheel for pendulum: filename=pendulum-2.1.2-cp311-cp311-macosx_14_0_arm64.whl size=127373 sha256=575e5cf1ef5c1ec3c09e0789e577e6cfcf3ea0fb4a953954984a1042be861d37
```

In this case, we've built a macOS wheel for Python 3.11 on Apple Silicon. But we're running
containers for Linux x64, so we need to build a wheel for that platform as well. Someone on a Linux
machine (or you can use a Docker container) will need to run the command again to build a wheel for
Linux x64.

```bash
Created wheel for pendulum: filename=pendulum-2.1.2-cp311-cp311-manylinux_2_35_x86_64.whl ...
```

For Linux wheels, they must be renamed manually to indicate that they support `manylinux2014` (the
`--platform` we pass to pip). To do this, rename the wheel to include `manylinux2014_x86_64` before
the `.whl` extension:

```bash
mv pendulum-2.1.2-cp311-cp311-manylinux_2_35_x86_64.whl pendulum-2.1.2-cp311-cp311-manylinux_2_35_x86_64.manylinux2014_x86_64.whl
```

Finally, proceed to the next step.

#### Mirror the Wheel to DML

Specific to DML.

**Comment by ah-quant** [comment]
Thanks @michaelboyd2 - I already have something, it's just too convoluted for my taste :-/
I'll try to modernize and distill it and link it here...
