### ISSUE TITLE
Is the installation of `uv` from `conda-forge` officially supported?

### ISSUE THREAD

**Issue by Yura52** [astral-sh/uv#2084]
Hi! I noticed that I could install `uv` via `conda` from `conda-forge`, here is the feedstock: https://github.com/conda-forge/uv-feedstock

However, this installation method is not mentioned in README. Is it officially supported or is it a community effort?

**Comment by Yura52** [comment]
Thank you for the quick reply!

**Comment by notatallshaw-gts** [comment]
> I wouldn't recommend managing `uv` with `conda` (as I wouldn't recommend managing it with `pip`) but it's fine.

btw, is there some reason beyond uv has less control over how it's installed?

We have the use case of having multiple Python development environments, and we bootstrap the binaries (CPython, git, a few others) via conda and the install the Python packages via pip (testing and prod use the same pip process but don't need to bootstrap the binaries with conda).

I was looking at how feasible it is to replace pip with uv, and in this scenario it would be simplest to add uv to the binary requirements that conda bootstraps. But if there's some significant reason not to do this it would be good to know.

**Comment by Yura52** [comment]
My situation is technically different, but it is somewhat similar in its spirit, and I was considering using micromamba just to fetch uv. Perhaps I should not have closed the issue, so reopening it just in case, though feel free to close it.

**Comment by charliermarsh** [comment]
> But if there's some significant reason not to do this it would be good to know.

I don't think there's any _significant_ reason not to do it. The one reason I _can_ think of not to do it is that we're likely to make `uv` self-updateable in the future (e.g., `uv update` or similar), and `uv` installations that come from a package manager (instead of through the standalone binary) won't support that.

**Comment by charliermarsh** [comment]
I'm fine to maintain it though as long as we're added as feedstock maintainers (\cc @bollwyvl) similar to our relationship to https://github.com/conda-forge/ruff-feedstock.

**Comment by charliermarsh** [comment]
(So yes, I consider it fine and I'm happy to support it, but we would need to be added as feedstock maintainers before I would consider us "supporting it".)
