### ISSUE TITLE
Option for the Windows installer to setup to a specific dir

### ISSUE THREAD

**Issue by gozdal** [astral-sh/uv#2087]
When working with `uv 0.1.12` installer in our CI env I had to use `CARGO_HOME` env var to direct the installer to a directory of my choosing with something like:
```powershell
$env:CARGO_HOME = "c:\Python\uv.0.1.12";
irm https://astral.sh/uv/install.ps1 | iex
```

I think it'd be a good addition for the installer to have a destination directory option (say `c:\tools` which might already be in `$PATH`).

**Comment by woutervh** [comment]
Why only the windows-installer?

A lot of installer-scripts have a "--destination" or "--target" flag. 
I would certainly make use of it.

**Comment by charliermarsh** [comment]
I think the env var is ok but needs to be documented (see: https://github.com/astral-sh/uv/issues/5449).
