### ISSUE TITLE
Option to not expand environment variables in uv pip compile

### ISSUE THREAD

**Issue by gwdekker** [astral-sh/uv#2116]
first of all thanks for the great work!

I have a use case where I define my package dependencies in pyproject.toml and compile them to requirements.txt. One of my dependencies is on a private gitlab repo which I have access to using auth through a private gitlab token. I use an environment variable to access this, so in pyproject.toml I have something like `https://__token__${GITLAB_TOKEN}@gitlab.com/….`

when running uv pip compile this gets expanded and solved. Works like a charm. However, the url with token exposed ends up in requirements.txt! I would claim the better behaviour would be to not do that but rather put the non-expanded variable in the requirements.txt file. 

There is an open issue on this on the pip tools repo where it is explained that this is not easy to solve for them as pip does not support it. Maybe uv could however?

**Comment by charliermarsh** [comment]
Can you give an example of the `pyproject.toml` and the command you're running? We don't expand environment variables when they're defined (e.g.) in a `requirements.txt`.

**Comment by gwdekker** [comment]
Will provide more details in a few hours when at my keyboard!

**Comment by charliermarsh** [comment]
Ah I see. This doesn't happen _in general_ but I think it _does_ happen for Git dependencies _specifically_ because of the mechanism we use to add the SHA to the end of the URL.

**Comment by charliermarsh** [comment]
We should be able to fix this in the common case. The only case we can't really fix is if there's an environment variable in the SHA or branch tag.
