### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by ofek** [astral-sh/uv#2133]
Hello there! I would like to use the internal crates here in [PyApp](https://github.com/ofek/pyapp). As far as I understand, the only functionality that I require would be:

1. creating virtual environments using a specific path to a Python binary
2. installing packages like `uv pip install ...` (users are allowed to pass extra flags so must be CLI)

I'm assuming the first one wouldn't be too challenging but the latter might require shipping the actual CLI/everything. How would I go about this, or even should I at this time?

**Comment by charliermarsh** [comment]
Are you open to interacting with `uv` over the CLI, rather than using it as a Rust library?

**Comment by ofek** [comment]
Certainly but not for this specific use case if possible. I would much prefer to import the necessary crates.

**Comment by zanieb** [comment]
I don't think our Rust APIs are stable enough for this — we would rather focus on the user experience at this time.
