### ISSUE TITLE
Per-platform overrides

### ISSUE THREAD

**Issue by mjclarke94** [astral-sh/uv#2142]
Generally speaking, version resolution is platform independent for the majority of dependencies, with only a subset (torch...and others...mostly torch) needing a nudge in the right direction.  Cross-platform support is probably the main thing preventing us from adopting uv/rye at the moment, as we build on MacOS but deploy on Linux. There's already an open issue for cross platform support (#2079), but I imagine implementing that is a fairly involved process.

As a short term solution to unblock the adoption of uv until cross-platform version resolution is implemented, `overrides.txt` could allow the pinning of versions on a per-platform basis.

**Comment by charliermarsh** [comment]
So in some sense, I think that overrides already _do_ allow this, because you can provide multiple overrides for a single package, like:

```txt
pywin32 > 1.0 : sys.platform == 'win32'
pywin32 < 1.0 : sys.platform != 'win32'
```

With this, whenever we see `pywin32`, we'll replace it with both of these, so only the one that applies to the given platform will end up being activated.

Would this work for what you're describing?

**Comment by pamelafox** [comment]
I'm not sure if my question is the same question or a different one, but it seems related. Does uv already support the functionality of https://pypi.org/project/pip-compile-cross-platform/ ? Can we compile once, and have it keep the markers for different OSes in the resulting requirements.txt file?

**Comment by charliermarsh** [comment]
@pamelafox -- We don't quite support that yet. That tool looks like a wrapper around Poetry which does a platform-agnostic resolution. We're going to support that in the future, but right now we only lock for a single platform (like `pip-compile`).

**Comment by danieleades** [comment]
> @pamelafox -- We don't quite support that yet. That tool looks like a wrapper around Poetry which does a platform-agnostic resolution. We're going to support that in the future, but right now we only lock for a single platform (like `pip-compile`).

is there somewhere we can track progress towards platform-agnostic resolution?

**Comment by charliermarsh** [comment]
@inoa-jboliveira -- I think that's best tracked as part of https://github.com/astral-sh/uv/issues/2679. (We're building some prototypes for it now.)

**Comment by zanieb** [comment]
See also https://github.com/astral-sh/uv/issues/3347 for cross-platform lock files.

I don't know if there's a clear todo here regarding per-platform overrides so I'm going to close this. Let me know if we're missing something.
