### ISSUE TITLE
Verbosity level to see output from build backend

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#2146]
Related to https://github.com/astral-sh/uv/issues/1569 , but I'd love to be able to see the output from the build backend during a successful install. `pip install -v` will show this to you

Would make debugging things like https://github.com/astral-sh/uv/issues/2145 much easier

**Comment by alex** [comment]
I think this is the same as https://github.com/astral-sh/uv/issues/1567

**Comment by charliermarsh** [comment]
Gonna merge into https://github.com/astral-sh/uv/issues/1567.
