### ISSUE TITLE
`uv pip compile` does not respect unsafe packages defined in `pyproject.toml`

### ISSUE THREAD

**Issue by silv-io** [astral-sh/uv#2161]
# Expected behavior

`pip-compile` has the feature to define "unsafe packages" which should not be pinned. This is useful when you want to make sure to always use the latest version of a specific package, regardless of the pin.

`uv` supports this feature, but only in the command line with the `--unsafe-package` option. However, `pip-tools` also scan the `pyproject.toml` section `tools.pip-tools` for the key `unsafe-package`.

It looks something like this:
```
[tool.pip-tools]
unsafe-package = ["some-package", "pip", "setuptools", "distribute"] # packages that should not be pinned
```
# Bug

`uv` does not read this section of the TOML and therefore produces different output on the same project. It should ideally read this section to offer drop-in replace-ability. Since this is in general a useful feature (not only for feature parity reasons), reading the equivalent key in "tools.uv", might be an option for the future as well. 

# Platform

* Linux AMD64
* `uv` version: `0.1.13`

**Comment by zanieb** [comment]
Hi!

I don't think we're willing to read another tool's configuration. We're still formalizing a policy around this though.

We can also consider adding our own configuration section.

**Comment by silv-io** [comment]
Hi!

That's understandable. But as mentioned, it would be nice in general to have a way to set some parameters directly in the `pyproject.toml`. 

Here's the documentation section from `pip-tools` about that: https://github.com/jazzband/pip-tools?tab=readme-ov-file#configuration

**Comment by zanieb** [comment]
Yeah we'll have our own persistent configuration eventually, we're still determining what that will look like though.

And yeah a pre-commit hook is of interest to us.

**Comment by silv-io** [comment]
@zanieb Do you have any update on when such a configuration will be available, or is there an official roadmap for that?
This is basically the only thing seriously blocking us from adopting `uv` now and we'd love to use it as it is so much faster :)

**Comment by silv-io** [comment]
@zanieb, @charliermarsh Any updates regarding persistent configuration? I see in https://github.com/astral-sh/uv/blob/main/docs/specifying_dependencies.md that you have some kind of configuration already in the `pyproject.toml`. I don't see however, whether there is support for setting something like this:

```
[tool.uv.pip.compile]
unsafe-package = ["some-package", "pip", "setuptools", "distribute"] # packages that should not be pinned
```

**Comment by zanieb** [comment]
We are building persistent configuration right now, e.g. https://github.com/astral-sh/uv/pull/3007

**Comment by silv-io** [comment]
@zanieb Looking through the toml schema, I found the possibility to define `no-emit-package` in the `pyproject.toml`.
This essentially does the same thing.

```
[tool.uv.pip]
no-emit-package = ["some-package", "pip", "setuptools", "distribute"] # packages that should not be pinned
```

I think this can be closed now! :)
