### ISSUE TITLE
uv does not install newly added dependencies to `pyproject.toml`

### ISSUE THREAD

**Issue by duarteocarmo** [astral-sh/uv#2164]
Thank you for taking the time to report an issue! We're glad to have you involved with uv.

If you're filing a bug report, please consider including the following information:

* A minimal code snippet that reproduces the bug.
* The current uv platform: Darwin
* The current uv version (`uv --version`): 0.1.2

![image](https://github.com/astral-sh/uv/assets/26342344/3a6ed549-234e-4011-920d-b671ebd787f1)

**Comment by charliermarsh** [comment]
Do you mind upgrading your `uv` version? We're now on `0.1.14`, and this is fixed (IIUC).

**Comment by duarteocarmo** [comment]
@charliermarsh what is this dark magic? I had heard you're fast. But this is next level..
