### ISSUE TITLE
Print shell-specific activation command in `venv`

### ISSUE THREAD

**Issue by saada** [astral-sh/uv#2174]
When using the [`fish` shell](https://fishshell.com/), the activate script fails with this error

```sh
❯ uv --version
uv 0.1.13

❯ uv venv -p 3.11
Using Python 3.11.7 interpreter at: /opt/homebrew/opt/python@3.11/bin/python3.11
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

❯ source .venv/bin/activate
.venv/bin/activate (line 69): Unsupported use of '='. In fish, please use 'set VIRTUAL_ENV '/Users/myapp/.venv''.
VIRTUAL_ENV='/Users/myapp/.venv'
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file .venv/bin/activate
.: Error while reading file '.venv/bin/activate'
```

Are there any plans to support fish shell?
Thank you for this great project 🙏🏽

**Comment by mkniewallner** [comment]
A dedicated `activate.fish` exists, so you should be able to use `source .venv/bin/activate.fish`.

It looks like the `venv` command does not try to guess the current shell used, so it always displays `bin/activate` on non-Windows systems: https://github.com/astral-sh/uv/blob/14d968ac224c88988c60b6c067f0cafbc3ea4a07/crates/uv/src/commands/venv.rs#L227-L231

**Comment by daniel-bartley** [comment]
Also with git bash on windows uv says: `Activate with: .venv\Scripts\activate` 
but command is wrong. Should be `source .venv/Scripts/activate`

**Comment by charliermarsh** [comment]
Hopefully the above would fix that too though not 100% sure.

**Comment by saada** [comment]
I can confirm that activate.fish worked 🙌🏽 
So yea, it's just a nit to make the experience more intuitive.
Thanks forlks
