### ISSUE TITLE
Where should dev-dependancies go in pyproject.toml file?

### ISSUE THREAD

**Issue by teaxio** [astral-sh/uv#2182]
In my pyproject.toml file I added:
```
[tool.uv.dev-dependencies]
ruff = "^0.0.79"
sphinx = "^4.0.0"
```
However, I am not sure if that is correct or not. Basically, how can I ensure that someone is able to install them with a command that gets run against the toml file? For instance I run `uv pip compile pyproject.toml -o requirements.txt` to generate the requirements.txt. Is there an equivalent that looks at `tool.uv.dev-dependencies` ? And where do I find general information on the processing of the toml file?

**Comment by zanieb** [comment]
Hi!

The `pyproject.toml` specification is at [packaging.python.org](https://packaging.python.org/en/latest/specifications/pyproject-toml/) and it sounds like you're looking for the [`optional-dependencies` field](https://packaging.python.org/en/latest/specifications/pyproject-toml/#dependencies-optional-dependencies)
