### ISSUE TITLE
Path to python garbled on Windows when virtual environment activated

### ISSUE THREAD

**Issue by daniel-bartley** [astral-sh/uv#2184]
Path to python gets messed up somewhere. I installed python310 with chocolatey.

```
$ python --version
Python 3.10.11

$ where python
C:\Python310\python.exe

$ pipx uninstall uv
uninstalled uv! ✨ 🌟 ✨

$ uv --version
bash: uv: command not found

$ pipx install uv
  installed package uv 0.1.14, installed using Python 3.10.11
  These apps are now globally available
    - uv.exe
done! ✨ 🌟 ✨

$ uv --version
uv 0.1.14 (c525fdf2b 2024-03-04)

$ uv venv
Using Python 3.10.11 interpreter at: C:\Users\myprofile\.local\bin\python3.exe
Creating virtualenv at: .venv
Activate with: .venv\Scripts\activate


$ source .venv/Scripts/activate

(uv-validate) 
$ python --version
No Python at '"C:\Users\myprofile\.local\bin\python.exe'
```

Tried creating a shortcut to "python3.exe" named "python.exe" but that doesn't work

**Comment by charliermarsh** [comment]
Thanks, I'll try to add some tests for this and see if we can reproduce.

**Comment by charliermarsh** [comment]
I'm unable to reproduce locally, but what is `C:\Users\myprofile\.local\bin\python3.exe`?

**Comment by dbrtly** [comment]
I'm honestly not sure. I think maybe pipx creates them for each app.

**Comment by dbrtly** [comment]
Installed cowsay via pipx. They definitely are artifacts from pipx.

**Comment by konstin** [comment]
Do you know where `.local\bin\python.exe` comes from? I tried various things but couldn't get one. I also tried using python 3.10 from `choco install python3.10`

```
PS C:\Users\Konstantin> dir .\.local\bin\

    Directory: C:\Users\Konstantin\.local\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          08.03.2024    12:21         108418 cmake.exe
-a---          08.03.2024    12:21         108418 cpack.exe
-a---          08.03.2024    12:21         108418 ctest.exe
-a---          08.03.2024    12:21         108438 poetry.exe
la---          08.03.2024    12:43              0 pycowsay.exe -> C:\Users\Konstantin\AppData\Local\pipx\pipx\venvs\pycowsay\Scripts\pycowsay.exe
-a---          08.03.2024    12:52         108406 tqdm.exe
```

**Comment by dbrtly** [comment]
I installed uv and many other python cli tools with pipx. Pipx is generating most of those files in that directory.

**Comment by daniel-bartley** [comment]
I deleted the python3.exe file and that seems to have solved the problem. How did that happen? lol

**Comment by charliermarsh** [comment]
Should this remain open @daniel-bartley?

**Comment by dbrtly** [comment]
No happy to close. I think it was unique to me


Thanks,
Daniel
________________________________
