### ISSUE TITLE
Support `xz` compressed source packages

### ISSUE THREAD

**Issue by lengau** [astral-sh/uv#2187]
Example failure:

```
$ uv pip install 'python-apt @ https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/python-apt/2.7.6/python-apt_2.7.6.tar.xz'
error: Failed to download and build: python-apt @ https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/python-apt/2.7.6/python-apt_2.7.6.tar.xz
  Caused by: Failed to extract source distribution
  Caused by: Unsupported archive type: python-apt_2.7.6.tar.xz
```

This is probably low priority, I'm sure.

**Comment by charliermarsh** [comment]
Interesting, does `pip` support it?

**Comment by lengau** [comment]
It does - I haven't looked at how `pip` extracts source distributions in tarballs, but I'm guessing it does so through the `tarfile` module, which supports `gz`, `bz2` and `xz` compressed tarballs, so I would guess full feature parity here would be to support all three.

**Comment by charliermarsh** [comment]
Sweet, thank you!
