### ISSUE TITLE
Could `uv venv` detect whether source files are inside `src` directory (like Poetry does)?

### ISSUE THREAD

**Issue by torarvid** [astral-sh/uv#2197]
Hi, and thanks for making `uv` ❤️

I experienced an issue converting an existing project at work from Poetry to uv, and tried making a minimal example to repro. Btw, I'm on macOS 14.3.1 using `uv 0.1.11 (32e5cacdd 2024-02-26)`.

## Part 1 — Poetry

I tried a hello-example looking like this — first using Poetry 1.7.1:

```bash
❯ tree
.
├── pyproject.toml
└── src
    └── hello.py

2 directories, 2 files
```
pyproject.toml contents:
```
[tool.poetry]
name = "hello"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
and hello.py contents:
```
print("Hello, world")
```
I then run:
```bash
❯ poetry install
Creating virtualenv hello-sRlYik7q-py3.12 in /Users/torarvid/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file

Installing the current project: hello (0.1.0)
❯ poetry run python -m hello
Hello, world
```

If anybody wonders, `poetry run python` is a shim-like feature that will use the python interpreter defined in the poetry venv. All well and good. Now:

## Part 2 — uv

I change pyproject.toml (in case it matters, I'm not sure whether it only does for `uv pip`?) to:
```
[project]
name = "hello"
version = "0.1.0"
requires-python = "~=3.12"
authors = [{ email = "Your Name <you@example.com>" }]
description = ""

[build-system]
requires = ["setuptools >= 69"]
build-backend = "setuptools.build_meta"
```
Same hello.py inside `src`. I run:
```bash
❯ uv venv
Using Python 3.12.1 interpreter at /Users/torarvid/.local/share/mise/installs/python/3.12.1/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
❯ source .venv/bin/activate.fish
❯ python -m hello
/Users/torarvid/dev/hello/.venv/bin/python: No module named hello
```

## Part 3 — what is wrong?

I don't know if there's possibly something I should add to pyproject.toml to inform `uv` about the `src` directory being "an entrypoint folder" or whatever it should be called 😊 But I *did* figure out the reason why it works using poetry: If I look in the venv created by poetry, there's this:

```bash
❯ ls /Users/torarvid/Library/Caches/pypoetry/virtualenvs/hello-sRlYik7q-py3.12/lib/python3.12/site-packages/
__pycache__  _virtualenv.pth  _virtualenv.py  hello-0.1.0.dist-info  hello.pth  pip  pip-23.3.1.dist-info  pip-23.3.1.virtualenv
```
The `hello.pth` file contains just `/Users/torarvid/dev/hello/src`. If I place a file like that in the `uv`-created venv, it also works just fine.

I have not investigated how poetry has implemented any logic that results in them creating this .pth file, so whether they look at all project folders containing .py files or have hard-coded support for some folders like "src", "tests" or whatever I don't know.

But in any case, it's probably not that uncommon to have a repo where the sources are inside a src sub-folder.

Would be a bit ironic if I wrote this long issue and it turns out to be a simple one-liner I need to fix in my pyproject.toml or something, but anyway — might help somebody else who runs into this in the future 😄 Have a nice day!

**Comment by woutervh** [comment]
Poetry does not do auto-detection.

You are missing a packages in pyproject.toml:
```
[tool.poetry]
packages = [{ include = "hello", from = "src" }]

```

but a package is a subdirectory with an __init__.py.
Move  hello.py  into hello/__init__.py
Otherwise you get an error like this:
```
> poety install
   .../src/hello does not contain any element
```

**Comment by torarvid** [comment]
@woutervh Thanks, but this issue isn't really about getting anything to work with Poetry (that already works just fine as I see it). It is about how to get things to work when transitioning from Poetry to uv.

**Comment by woutervh** [comment]
```
 (that already works just fine as I see it)
```
I'm actually baffled that this works,  it shouldn't.
As far as I'm concerned, this works by accident. 
I really hate tools creating their own magic and their ows hardcoded conventions.
This only complicates teaching proper python-packaging.

**Comment by zanieb** [comment]
It looks like you never installed your project into the virtual environment, have you tried `uv pip install -e .`? This is roughly equivalent to `poetry install`.

**Comment by torarvid** [comment]
@woutervh I recommend you make an issue in the poetry repo 👍🏻

**Comment by torarvid** [comment]
@zanieb Yes, thank you! This was it. So in conclusion: I'm a user somewhat familiar with Poetry and not familiar with pip (or the `uv pip ...` syntax) who's trying to convert a repo from Poetry to uv, and my lack of knowledge tripped me up 😄

Ok, so this seems to solve my problem completely, thanks a lot. Will close the issue.
