### ISSUE TITLE
Inconsistent behaviour of `help` with `uv venv`

### ISSUE THREAD

**Issue by navneethc** [astral-sh/uv#2200]
Ubuntu 22.04
uv 0.1.14

I like the fact that `uv` doesn't always require me to type `--` before `help` to see the documentation, however this doesn't always work as intended. When you run `uv venv help`, as I did, it instead creates a venv named `help`.

```
❯ uv venv help
Using Python 3.10.12 interpreter at: /usr/bin/python3
Creating virtualenv at: help
Activate with: source help/bin/activate
```
And there's no mention of this at the documentation at the top level.

```
❯ uv help
Usage: uv [OPTIONS] <COMMAND>

Commands:
  pip      Resolve and install Python packages
  venv     Create a virtual environment
  cache    Manage the cache
  version  Display uv's version
  help     Print this message or the help of the given subcommand(s)
...
```

This kind of behaviour may appear 'obvious' in retrospect, but if someone wishes to quickly look up documentation for a subcommand like `venv` but keeps running into an issue like this, it may get irritating.

**Comment by T-256** [comment]
You can use `uv help venv` instead.
`help` is for commands that have subcommands like `uv pip`. even though I suggest you always use `help` as first command, because it accepts nested subcommands: `uv help pip install`.

**Comment by navneethc** [comment]
> You can use `uv help venv` instead. `help` is for commands that have subcommands like `uv pip`. even though I suggest you always use `help` as first command, because it accepts nested subcommands: `uv help pip install`.

That is indeed helpful, thank you.

**Comment by charliermarsh** [comment]
Thanks @T-256.
