### ISSUE TITLE
Add `uv pip list --format json`

### ISSUE THREAD

**Issue by Daverball** [astral-sh/uv#2201]
This is very helpful for interpreting the output of `pip list` in e.g. shell scripts using `jq` and then further process it to generate follow-up commands.

This in combination with https://github.com/astral-sh/uv/issues/2150 is the last remaining blocker for me to be able to replace `pip` with `uv` in one of my projects (this also happens to be where I'm experiencing the most slowdowns).

**Comment by T-256** [comment]
Already working on it: https://github.com/astral-sh/uv/pull/1998

**Comment by charliermarsh** [comment]
This was added in https://github.com/astral-sh/uv/pull/1998.
