### ISSUE TITLE
uv attempts (and fails) to install ancient setuptools

### ISSUE THREAD

**Issue by mdekstrand** [astral-sh/uv#2203]
With uv 0.1.14, using the following command:

```
uv pip install --system --resolution=lowest-direct -e '.[test]'
```

causes `uv` to attempt (and fail) to install a very ancient version of setuptools (0.7.?). This was not the case in `uv` 0.1.13. `uv` is running on the `ubuntu-latest` runner in GitHub Actions.

- [Failing build with uv 0.1.14](https://github.com/lenskit/lkpy/actions/runs/8150058325/job/22275701510)
- [Working build with uv 0.1.13](https://github.com/lenskit/lkpy/actions/runs/8150224438/job/22276128055)

The project in question is https://github.com/lenskit/lkpy (while I noticed this problem in a PR branch, the main branch should also trigger it).

**Comment by charliermarsh** [comment]
I'll take a look.

**Comment by charliermarsh** [comment]
I see the issue, sorry about that. Will fix and include in today's release.

**Comment by mdekstrand** [comment]
@charliermarsh thanks!
