### ISSUE TITLE
uv installed on 3.9 version, but make venv on 3.7 version

### ISSUE THREAD

**Issue by mephistiks** [astral-sh/uv#2222]
Input:
```sh 
python3.9 -m uv venv venv
```

Output:
```sh
Using Python 3.7.17 interpreter at: /usr/bin/python3
Creating virtualenv at: venv
Activate with: source venv/bin/activate
```

**Comment by charliermarsh** [comment]
I would recommend instead: `uv venv --python python3.9`.

**Comment by zanieb** [comment]
We _could_ hint to UV to use the correct version as we do for virtual environments, I would expect this command to work as well.

https://github.com/astral-sh/uv/blob/65518c9c585648267721a6effc090cb2f18e12dc/python/uv/__main__.py#L29-L31

**Comment by charliermarsh** [comment]
Perhaps, take a look at https://github.com/astral-sh/uv/issues/2058 too.
