### ISSUE TITLE
“uv pip install -P PACKAGE“ error prompted

### ISSUE THREAD

**Issue by zzm-note** [astral-sh/uv#2233]
`uv pip install -P   Appium-Python-Client`
![image](https://github.com/astral-sh/uv/assets/25860330/98d9b407-a0c1-4b38-a812-af4a108cd526)

uv version == uv 0.1.15 (a8ac7b1eb 2024-03-05)

**Comment by zzm-note** [comment]
> What is the intended behavior of `-P`? I don't see that flag in `pip`. You can omit it if you intended to run `uv pip install Appium-Python-Client`. `-P` 的预期行为是什么？我在1#里没有看到那面旗。如果您打算运行 `uv pip install Appium-Python-Client` ，则可以省略它。

```
  -P, --upgrade-package <UPGRADE_PACKAGE>
          Allow upgrade of a specific package
```
Sometimes I only want to upgrade a single library. If I use `uv pip install Appium-Python-Client`, the associated dependencies will also be upgraded.

**Comment by charliermarsh** [comment]
This flag exists on `uv pip compile`, maybe that's what you're looking for?

**Comment by zzm-note** [comment]
> This flag exists on `uv pip compile`, maybe that's what you're looking for?

Maybe not, `uv pip compile` requires a <SRC_FILE>, but I just want to upgrade a certain library separately

**Comment by zzm-note** [comment]
For example
 Current virtual environment:
```
Package      Version
------------ -------
click        8.1.7
colorama     0.4.6
flask        2.0.0
itsdangerous 2.1.2
jinja2       3.1.3
markupsafe   2.1.5
werkzeug     3.0.1
```
I want to upgrade `flask` to the latest, use `uv pip install flask -U`
```
Installed 4 packages in 64ms
 + blinker==1.7.0
 - flask==2.0.0
 + flask==3.0.2
 + importlib-metadata==7.0.1
 + zipp==3.17.0
```
But I only want to upgrade flask, and I don’t want other libraries to be upgraded as well.

**Comment by charliermarsh** [comment]
Ahh right -- `uv pip install flask -P flask` should work!
