### ISSUE TITLE
`uv pip install --system` doesn't not respect `PIP_BREAK_SYSTEM_PACKAGES`

### ISSUE THREAD

**Issue by jfcherng** [astral-sh/uv#2234]
While `--system` has been added recently, as per [Externally Managed Environments](https://packaging.python.org/en/latest/specifications/externally-managed-environments/), if there is the `EXTERNALLY-MANAGED` marker file in the Python distribution, then packages won't be installed.

However, the env variable `PIP_BREAK_SYSTEM_PACKAGES` can make `pip` to forcely install to externally managed Python distribution. I try to migrate `pip` to `uv` but `uv` doesn't seem to respect `PIP_BREAK_SYSTEM_PACKAGES` so I guess there is just no way to skip that check. An workaround is that I just remove the `/usr/lib/python3.x/EXTERNALLY-MANAGED` file.

My use case is that I am making a read-only Singularity image (it's just like a Docker image). So I just don't care about that.

**Comment by zanieb** [comment]
We're willing to add support for the command line flag, we just haven't done so yet.
