### ISSUE TITLE
install.ps1 doesn't work on ARM64 devices

### ISSUE THREAD

**Issue by kbattocchi** [astral-sh/uv#2246]
I'm on a Surface Pro 9 (5G), and running `powershell -c "irm https://astral.sh/uv/install.ps1 | iex"` fails with:

> Downloading uv 0.1.15 (x86_64-pc-windows-msvc)
> Installing to C:\Users\kebatt\.cargo\bin
> &nbsp;&nbsp;uv.exe
> Cannot index into a null array.

The problem seems to be that the `Download` function in the PowerShell script correctly falls back to `x86_64-pc-windows-msvc` but `Invoke-Installer` doesn't have any corresponding logic to do that.  (I'd raise a PR fixing it, but I don't see the install script in the repo)

**Comment by charliermarsh** [comment]
Thank you! Do you mind filing an issue or PR on https://github.com/axodotdev/cargo-dist?

**Comment by charliermarsh** [comment]
I'm gonna close in favor of the issue in `cargo-dist` (though this is not resolved).
