### ISSUE TITLE
Markers (incorrectly?) require the variable to be to the left of the operator

### ISSUE THREAD

**Issue by kbattocchi** [astral-sh/uv#2247]
For a marker like `python_version<='3.8'`, pip also allows `'3.8'>=python_version`.  However `uv` (version 0.1.15) requires the variable to be on the left hand side.

E.g. `pip install "pytest;'1.0'>python_version"` correctly does nothing and `pip install "pytest;'4.0'>python_version"` correctly always installs the library, but the corresponding `uv pip install --system "pytest;'1.0'>python_version"` and `uv pip install --system "pytest;'4.0'>python_version"` throw an error.

(Technically, the grammar seems to also allow comparisons where both sides of the operator are variables, or both are strings, but `pip` doesn't seem to actually handle those correctly...)

**Comment by charliermarsh** [comment]
_Probably_ a bug but I defer to @konstin.
