### ISSUE TITLE
Please add the ability to  `uv pip install` for the global interpreter to speed up docker builds

### ISSUE THREAD

**Issue by dempstert** [astral-sh/uv#2257]
Feature Request:
At the moment UV requires a virtualenv in order to install requirements.

In order to speed up docker builds, can we introduce the ability to run uv install and introduce requirements to the global interpreter?

**Comment by charliermarsh** [comment]
I believe this is already possible. Have you tried running with the `--system` flag, as in `uv pip install --system`?

**Comment by dempstert** [comment]
Thanks @charliermarsh !
Missed that... Perfect.

**Comment by charliermarsh** [comment]
No prob!
