### ISSUE TITLE
pip compile constraining combined with git based dependencies

### ISSUE THREAD

**Issue by gwdekker** [astral-sh/uv#2266]
First things first: I have to say that I never felt so encouraged to file issues at an open source project - as it is obvious that the chance of getting it fixed and soon is orders of magnitude higher than anywhere else! 

Use case that fails:
- I want to have requirements and dev-requirements that are guaranteed to be compatible: I want to make sure I am not running a package version in production that I do not have in my dev environment.
- The suggested workflow for this I found is to compile the dev requirements first, and then use the resulting dev-requirements.txt as a constraint file for solving the production requirements like so:
```
	uv pip compile --extra dev -o requirements-dev.txt pyproject.toml 
	uv pip compile --constraint requirements-dev.txt -o requirements.txt pyproject.toml 
```

This fails in the case of having packages installed directly from a git repo. I have a repo in pyproject.toml like this:

`PACKAGE_NAME @ git+https://__token__:${GITLAB_ACCESS_TOKEN}@gitlab.com/PATH_TO_REPO.git@my_branch`

What happens is that the branch name gets resolved to a commit hash, and as a result the resolving fails:

```
error: Requirements contain conflicting URLs for package `PACKAGE_NAME`:
- git+https://__token__:${GITLAB_ACCESS_TOKEN}@gitlab.com/PATH_TO_REPO.git@intraday-main
- git+https://__token__:${GITLAB_ACCESS_TOKEN}@gitlab.com/PATH_TO_REPO@THE_FULL_COMMIT_SHA

```

**Comment by charliermarsh** [comment]
I think we can support this as a sort of special-case (when URLs conflict, and one is a pinned VCS SHA, accept the pinned VCS SHA).

**Comment by charliermarsh** [comment]
I'm just gonna categorize it as a bug since that's what users would expect.

**Comment by gwdekker** [comment]
Thanks for sharing my comment on X, happy to see you appreciated it! Keep up the amazing work :)
