### ISSUE TITLE
Python interpreter query fails on Windows in a conda environment starting with 0.1.14

### ISSUE THREAD

**Issue by MatthieuDartiailh** [astral-sh/uv#2269]
I upgraded my uv install inside a conda environment on Windows (from 0.1.11 to 0.1.15) to try to fix an issue with entry points. However after the upgrade, uv failed with:
```
uv pip install pyvisa-sim
 uv::requirements::from_source source=pyvisa-sim
    0.003712s DEBUG uv_interpreter::python_environment Found a virtualenv through CONDA_PREFIX at: C:\xxxxxx\miniconda3\envs\charac
    0.004238s DEBUG uv_interpreter::interpreter Probing interpreter info for: \\?\C:\xxxxxxxx\miniconda3\envs\charac
error: Failed to query python interpreter `\\?\C:\xxxxxxxx\miniconda3\envs\charac`
  Caused by: Access is denied. (os error 5)
```
I then downgraded and found that 0.1.13 is the last version that works (install, I did not check the entry_points yet).

**Comment by charliermarsh** [comment]
Thanks! I'll take a look at this now.

**Comment by ev-dev** [comment]
Also been encountering this issue in last 2 releases (>0.1.13) while using [micromamba](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html) on Windows for conda envs, had to downgrade/pin uv to version 0.1.13 to fix.
```
error: Failed to query python interpreter `\\?\C:\Users\<user>\micromamba\envs\testenv-cp312-1
  Caused by: Access is denied. (os error 5)
```
Awesome work btw! I honestly still gasp each time I use `uv` to install packages, so crazy fast 😁

**Comment by charliermarsh** [comment]
Thanks :) I'll install micromamba now. Seems like I unintentionally broke something!

**Comment by charliermarsh** [comment]
Sorry, this was honestly something dumb by me, it only affected Conda-on-Windows and I didn't test it: https://github.com/astral-sh/uv/pull/2279
