### ISSUE TITLE
uv pip wont accept my requirements file

### ISSUE THREAD

**Issue by yashranjan1** [astral-sh/uv#2276]
The command I wrote:
```
uv pip install -r .\requirements.txt
```
The result:
```
error: failed to read from file `.\requirements.txt`
  Caused by: stream did not contain valid UTF-8
```
The requirements file:
```
annotated-types==0.6.0
anyio==4.3.0
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
cryptography==42.0.5
exceptiongroup==1.2.0
fastapi==0.110.0
h11==0.14.0
idna==3.6
pycparser==2.21
pydantic==2.6.3
pydantic-core==2.16.3
python-dotenv==1.0.1
requests==2.31.0
sniffio==1.3.1
starlette==0.36.3
typing-extensions==4.10.0
urllib3==2.2.1
uvicorn==0.27.1
```

Current UV version:
```
Yash ❯❯ uv --version
uv 0.1.15 (a8ac7b1eb 2024-03-05)
```

Operating System: Windows 

This works when I use pip but not with UV. I tried to look for a similar issue but couldn't find one. If this is a duplicate, I apologise. Would you be so kind to give me a link to the issue where the solution for this is discussed? Thanks!

**Comment by BurntSushi** [comment]
Can you upload an exact copy of your `requirements.txt` as an attachment? My hunch is that it's UTF-16 or otherwise contains invalid UTF-8 based on the error message you're getting.

**Comment by yashranjan1** [comment]
My requirements file -> [requirements.txt](https://github.com/astral-sh/uv/files/14526633/requirements.txt)

I had uv write this out for me using the command:
```
uv pip freeze > requirements.txt
```

**Comment by BurntSushi** [comment]
Can you share the original `requirements.txt`? The one that produced the error in the original issue.

**Comment by yashranjan1** [comment]
That is the one, I installed the packages myself using uv and then i created a requirements file so other people can run my program on their computers as well

**Comment by notatallshaw** [comment]
> My requirements file -> [requirements.txt](https://github.com/astral-sh/uv/files/14526633/requirements.txt)
> 
> I had uv write this out for me using the command:
> 
> ```
> uv pip freeze > requirements.txt
> ```

No idea on the cause, but FYI this file is "UTF-16 LE BOM" , not "UTF-8".

**Comment by zanieb** [comment]
@BurntSushi we previously said we would not change this behavior:

- https://github.com/astral-sh/uv/issues/1666
