### ISSUE TITLE
ERROR: powershell -c "irm https://astral.sh/uv/install.ps1 | iex" Error: PowerShell requires an execution policy in [Unrestricted, RemoteSigned, ByPass] to run uv.

### ISSUE THREAD

**Issue by 2zzly** [astral-sh/uv#2286]
powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
Error: PowerShell requires an execution policy in [Unrestricted, RemoteSigned, ByPass] to run uv. For example, to set the execution policy to 'RemoteSigned' please run:

    Set-ExecutionPolicy RemoteSigned -scope CurrentUser

**Comment by samypr100** [comment]
It's possible you don't have developer mode set on your windows machine, or in the corporate case there is a Group Policy on your computer to prevent running PowerShell scripts that are not signed. Couple possible options here:
1) Install via `pipx` or friends (See [Getting Started](https://github.com/astral-sh/uv?tab=readme-ov-file#getting-started))
2) Download directly from https://github.com/astral-sh/uv/releases
3) Temporarily adjust your PowerShell policy to allow remote powershell scripts to run without signing.

**Comment by charliermarsh** [comment]
Thanks! There's an upstream issue filed with the installer here: https://github.com/axodotdev/cargo-dist/issues/833.
