### ISSUE TITLE
UV path not added to enviroment using windows pip install

### ISSUE THREAD

**Issue by 2zzly** [astral-sh/uv#2287]
c:\>pip install uv
Defaulting to user installation because normal site-packages is not writeable
Collecting uv
  Using cached uv-0.1.15-py3-none-win_amd64.whl.metadata (21 kB)
Using cached uv-0.1.15-py3-none-win_amd64.whl (8.3 MB)
Installing collected packages: uv
Successfully installed uv-0.1.15

c:\>uv
'uv' is not recognized as an internal or external command,
operable program or batch file.

**Comment by charliermarsh** [comment]
If you `pip install` other programs, are you able to access them?

**Comment by Times0** [comment]
You probably just need to have the script dir of python in your path. On windows  for python 3.11:
```setx PATH "%PATH%;C:\~AppData\Roaming\Python\Python311\Scripts```

I had the same issue after installing python on a new PC today. Somehow ticking the box "add to path" in the python installer didn't work this time.

**Comment by charliermarsh** [comment]
I think this is not an issue with uv but rather with the original Python install.
