### ISSUE TITLE
uv pip install sometimes results in `error: Cannot uninstall package; RECORD file not found at ...`

### ISSUE THREAD

**Issue by mkleinbort-ic** [astral-sh/uv#2304]
When running 
```python -m uv pip install --system --prerelease=allow -r pyproject.toml```

I am hitting the error:

```
error: Cannot uninstall package; 
RECORD file not found at: C:\Users\{USER}\AppData\Local\Programs\Python\Python310\Lib\site-packages\catboost-1.2.2.dist-info\RECORD
```

Which seems to be a common error in other installation systems (ie. not `uv` specific):

https://stackoverflow.com/questions/68886239/cannot-uninstall-numpy-1-21-2-record-file-not-found

That said, if `uv` has any mitigation for this - that'd be great. 

Using uv 0.1.16 on Windows 11

**Comment by charliermarsh** [comment]
That's interesting, can you share more on the dependencies included to trigger this? If we can repro reliably, we can probably fix it.

**Comment by mkleinbort-ic** [comment]
Not sure what caused it, It may be that I killed a process mid-way through a pip install (I'm cautiously moving from pip to uv these days).

I tried pip uninstalling catboost (which succeded) but the issue remained when re running `uv pip install`

The solution was to navegate to

C://Users/{USER}/AppData/Local/Programs/Python/Python310/Lib/site-packages/

and `rm -r catboost-1.2.2.dist-info/` which was empty

**Comment by mkleinbort-ic** [comment]
Ah, now the issue with catboost is solved, but I hit the same issue with matplotlib

error: Cannot uninstall package; RECORD file not found at: C:\Users\mkleinbort\AppData\Local\Programs\Python\Python310\Lib\site-packages\matplotlib-3.8.2.dist-info\RECORD

**Comment by mkleinbort-ic** [comment]
Ok, mostly managed to reproduce the issue

1) When running uv pip install to install a newer version of a package
2) and I hit the error described here: https://github.com/astral-sh/uv/issues/1491#issuecomment-1983615072
3) When I re-run the uv pip install I hit the error described here on the package on which the error (2) was hit
4) So I go and manually delete the {package}-dist-info/ 
5) now that package installation succeeds, but I hit the https://github.com/astral-sh/uv/issues/1491#issuecomment-1983615072 somewhere else and it continues so 

I hope this will succeed once for all the packages and then become a quicker way to install new versions than pip

**Comment by mkleinbort-ic** [comment]
Ok, just FYI - it did work after 42 runs and re-runs of uv pip install 

But it was worth it - now my "update dependencies" workflow has gone down from 4 minutes (via pip) to basically nothing

**Comment by charliermarsh** [comment]
Ah interesting, so you're on Windows and you're hitting that even with the latest version. Hmm...

**Comment by charliermarsh** [comment]
Ah okay, sorry, I misunderstood -- so you're hitting https://github.com/astral-sh/uv/issues/1491#issuecomment-1983615072 which is causing there to be "incomplete" packages in the site-packages, got it.
