### ISSUE TITLE
Remove wheel for PEP 517 fallback builds

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#2313]
Setuptools declares wheel as a wheel build dependency for PEP 517 builds already via a build hook. Both pip 24 (https://github.com/pypa/pip/pull/12449)  and build 1.1 (https://github.com/pypa/build/pull/716) have removed wheel from the default PEP 517 fallback environment. I think uv should do the same. 

There are a small collection of packages that `import wheel` inside setup.py directly, which is discouraged by `wheel` (as there's no official pubic API), and these packages should either declare wheel explicitly as a dependency in pyproject.toml, protect the import, or use setuptool's functionality to get a build class without importing it.

**Comment by charliermarsh** [comment]
Any idea if there are known packages that won't build under this?

**Comment by henryiii** [comment]
They also won't work with pip or build. :) The most recent issue was one with pyodide https://github.com/pyodide/pyodide/discussions/4593 - the user forgot to copy the pyproject.toml into the docker container when building. :) Another: https://github.com/pypa/build/issues/750. I think pip took the brunt of this, though, as pip 24 came out before build 1.1, and people using build tend to be more likely to have pyproject.tomls, etc., so looking around in pip's issue tracker might be helpful.
