### ISSUE TITLE
uv Created Virtual Environment is not Usable by PyCharm

### ISSUE THREAD

**Issue by bwanshoom** [astral-sh/uv#2317]
PyCharm will not recognize a virtual environment created by uv. I'm not sure what it's looking for in a virtual environment, but one created by python -m venv .venv is somehow different from one created by uv venv --seed.

I can select the uv created environment, but PyCharm won't use it, save it or load it.

**Comment by bwanshoom** [comment]
Answering my own issue - uv does not create an Include directory like the Python venv module does. That directory is empty with the python venv, so just creating an empty Include directory in the uv venv allows PyCharm to use the uv virtual environment.

**Comment by charliermarsh** [comment]
Just confirming, this is on Windows right?

**Comment by charliermarsh** [comment]
Oh, or not. The thing I'm surprised by is that `virtualenv` doesn't create an `include` either, but `python -m venv` does. Do you see the same problem if you use `virtualenv`?

**Comment by charliermarsh** [comment]
Can you give me steps to repro? Specifically, what do you do in the PyCharm UI that isn't working?

**Comment by bwanshoom** [comment]
Yes, it's on Windows. Interestingly, virtualenv does not fail even without the Include directory.

**Comment by bwanshoom** [comment]
Repro steps:
1. In PyCharm, open Settings => Python Interpreter
2. Click Add Interpreter => Add Local Interpreter
3. Click Existing then browse to the uv venv (e.g. xxxx\.venv\Scripts\python.exe)
4. Click OK, then click OK again
5. If PyCharm likes the interpreter, it will read the installed packages and display them. With the uv one, it won't show anything. If you close settings and go back in, there will be no interpreter selected for the project

**Comment by charliermarsh** [comment]
Thanks, I can reproduce on Windows! (But not macOS.)

**Comment by charliermarsh** [comment]
Hmm, I actually can't reproduce this though when I use `--seed`.

**Comment by charliermarsh** [comment]
Can you try removing the interpreter from PyCharm, re-running with `--seed`, re-opening PyCharm, and trying again...?

**Comment by bwanshoom** [comment]
I did that originally and it wasn't working, but now after doing it with a new project it is working. I think I was running into some kind of internal caching in PyCharm so this is probably not a uv issue after all.

**Comment by charliermarsh** [comment]
Yeah, I see similar flakiness in the caching. I had to remove the interpreter and restart. Anyway, thank you for filing.
