### ISSUE TITLE
Pytorch dependency resolution with external link

### ISSUE THREAD

**Issue by SiviP-Glossai** [astral-sh/uv#2328]
I am having a resolution issue for torch packages with an external link.
This same setup is being resolved in pip.

cmd: ` uv pip install -r requirements.txt`
platform: `windows 11`
uv version: `uv 0.1.16 (9f1452cb7 2024-03-07)`
requirements file:
```
-f https://download.pytorch.org/whl/torch_stable.html
torch==1.13.1+cu117
torchaudio==0.13.1
torchvision==0.14.1+cu117
```
terminal output:
```
  × No solution found when resolving dependencies:
  ╰─▶ Because torchaudio==0.13.1 depends on torch==1.13.1 and you require
      torch==1.13.1+cu117, we can conclude that you require==0a0.dev0 and
      torchaudio==0.13.1 are incompatible.
      And because you require torchaudio==0.13.1, we can conclude that the
      requirements are unsatisfiable.
```

So I was also trying to add `+cu117` to `torchaudio` but I get a similar result:

requirements file:
```
-f https://download.pytorch.org/whl/torch_stable.html
torch==1.13.1+cu117
torchaudio==0.13.1+cu117
torchvision==0.14.1+cu117
```

termianl output:
```
  × No solution found when resolving dependencies:
  ╰─▶ Because torchaudio==0.13.1+cu117 depends on torch==1.13.1 and you
      require torch==1.13.1+cu117, we can conclude that you require==0a0.dev0
      and torchaudio==0.13.1+cu117 are incompatible.
      And because you require torchaudio==0.13.1+cu117, we can conclude that
      the requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
Thanks, please see: https://github.com/astral-sh/uv/issues/1855 (https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers). We don't yet handle local version specifiers properly which causes problems with PyTorch. Can track the linked issue!

**Comment by charliermarsh** [comment]
This will be supported in the next release via https://github.com/astral-sh/uv/pull/2430.
