### ISSUE TITLE
Use UV without VENV (devcontainer)

### ISSUE THREAD

**Issue by osbyrne** [astral-sh/uv#2333]
> uv pip install manim_automata

error: Failed to locate a virtualenv or Conda environment (checked: `VIRTUAL_ENV`, `CONDA_PREFIX`, and `.venv`). Run `uv venv` to create a virtualenv.

my dev env is a devcontainer, specifically the image [mcr.microsoft.com/devcontainers/python:1-3.12-bullseye](mcr.microsoft.com/devcontainers/python:1-3.12-bullseye) hosted at [https://github.com/devcontainers/images/blob/main/src/python](https://github.com/devcontainers/images/blob/main/src/python)

I think .venv is useful to contain python dev envs, but in my case, the whole OS is contained. I shouldn't have to use .venv

**Comment by charliermarsh** [comment]
Thanks, this is already supported -- you can pass `--system` or a specific Python interpreter with `--python path/to/python`. See the docs here: https://github.com/astral-sh/uv?tab=readme-ov-file#installing-into-arbitrary-python-environments.

**Comment by Malix-off** [comment]
But wait, [`--system` doesn't work in GitHub codespaces](https://github.com/astral-sh/uv/issues/3417)

**Comment by Malix-off** [comment]
Yep, I am already tracking that one
