### ISSUE TITLE
Special case error message when `wheel` is missing with no build isolation

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#2342]
I have problems with [`xformers` by Meta](https://github.com/facebookresearch/xformers) (see [issue](https://github.com/facebookresearch/xformers/issues/940)). I even tried with latest `uv` _without build isolation_:

```bash
❯ uv pip install setuptools torch numpy
Resolved 11 packages in 2ms
Installed 1 package in 23ms
 + numpy==1.26.4

❯ uv pip install xformers --no-build-isolation
Resolved 11 packages in 2ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: xformers==0.0.24
  Caused by: Failed to build: xformers==0.0.24
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

_Originally posted by @baggiponte in https://github.com/astral-sh/uv/issues/2252#issuecomment-1985287074_

**Comment by baggiponte** [comment]
Also posting the solution provided by @charliermarsh : you just have to install `wheel` too. (also: will you eventually re-implement `wheel` so that `uv` can handle these cases?)
