### ISSUE TITLE
Investigate overhead in initializing HTTP client

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2346]
If I add debug logging before and after:

```rust
// Initialize the base client.
let client = self.client.unwrap_or_else(|| {
    // Disallow any connections.
    let client_core = ClientBuilder::new()
        .user_agent(user_agent_string)
        .pool_max_idle_per_host(20)
        .timeout(std::time::Duration::from_secs(timeout));

    client_core.build().expect("Failed to build HTTP client.")
});
```

...in the registry client, it says it takes >120ms to initialize the client. That's a ton! In many cases, it's more expensive than the resolution itself.

Did this regress at some point? My best guess would be that we regressed by reading the system certificates, but we should look into it.

**Comment by charliermarsh** [comment]
I would be curious if this reproduces on Linux at all, or if it's macOS-only.

**Comment by charliermarsh** [comment]
Either way, I’m going to make the client initialization lazy.

**Comment by konstin** [comment]
Is that mac specific or do i need to set an environment variable? I tried to reproduce but client building is 4ms on my ubuntu machine.

**Comment by charliermarsh** [comment]
I believe it’s specific to macOS.
