### ISSUE TITLE
uv doesn't include environment markers in compiled output

### ISSUE THREAD

**Issue by euan-reid** [astral-sh/uv#2349]
In a current project I have an optional dependency that's not available on Windows - specifically, uvloop (used for better performance by uvicorn) is currently unavailable for Windows. As such, I set environment markers to only install that extra on non-Windows platforms. However, when I run `uv pip compile` it doesn't include the markers in the output requirements.txt.

`uv version` output:
```
uv 0.1.17 (bb2d06cbb 2024-03-10)
```

Minimal pyproject.toml:
```
[project]
name = "coolapp"
version = "0.1.0"
dependencies = [
    'fastapi~=0.110',
    'uvicorn[standard]~=0.27 ; platform_system != "Windows"',
    'uvicorn~=0.27 ; platform_system == "Windows"',
]
```

Relevant section of compiled requirements.txt
```
uvicorn==0.27.1
uvloop==0.19.0
    # via uvicorn
watchfiles==0.21.0
    # via uvicorn
websockets==12.0
    # via uvicorn
```

For now I'm just manually working aroung it by adding a `; platform_system ~= "Windows"` on the line with uvloop before git committing, but that's obviously not ideal.

**Comment by ChannyClaus** [comment]
Should the ideal output also include extras? For example, the minimal example provided in the description produces the below when run through `pip-compile`:

<details closed>
<summary>pip-compile output</summary>
```

WARNING: --strip-extras is becoming the default in version 8.0.0. To silence this warning, either use --strip-extras to opt into the new default or use --no-strip-extras to retain the existing behavior.
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile pyproject.toml
#
annotated-types==0.6.0
    # via pydantic
anyio==4.3.0
    # via
    #   starlette
    #   watchfiles
click==8.1.7
    # via uvicorn
fastapi==0.110.0
    # via coolapp (pyproject.toml)
h11==0.14.0
    # via uvicorn
httptools==0.6.1
    # via uvicorn
idna==3.6
    # via anyio
pydantic==2.6.3
    # via fastapi
pydantic-core==2.16.3
    # via pydantic
python-dotenv==1.0.1
    # via uvicorn
pyyaml==6.0.1
    # via uvicorn
sniffio==1.3.1
    # via anyio
starlette==0.36.3
    # via fastapi
typing-extensions==4.10.0
    # via
    #   fastapi
    #   pydantic
    #   pydantic-core
uvicorn[standard]==0.28.0 ; platform_system != "Windows"
    # via coolapp (pyproject.toml)
uvloop==0.19.0
    # via uvicorn
watchfiles==0.21.0
    # via uvicorn
websockets==12.0
    # via uvicorn
```

</details>

**Comment by charliermarsh** [comment]
We won't include extras by default (pip-compile is also removing them by default in the next release, hence the warning) and won't prioritize implementing them, but you can track here: https://github.com/astral-sh/uv/issues/1595.

For markers, you can track https://github.com/astral-sh/uv/issues/1429 (I'll merge into that issue), which is the same request. The one thing I'll say is that it isn't really safe to be using compiled requirements files this way, because you have no indication of the dependencies you're missing. Like, FastAPI could have some Windows-only dependency, and it just wouldn't show up at all in the resolution above, regardless of whether we preserve markers at all.

**Comment by euan-reid** [comment]
Not sure why I didn't find #1429 when searching issues - thanks!

**Comment by charliermarsh** [comment]
No prob, took me a few searches and I already knew it existed :)
