### ISSUE TITLE
URL Environment Variable Substitution ordering

### ISSUE THREAD

**Issue by matty-rose** [astral-sh/uv#2375]
## Description
Environment variable substitution only happens _after_ matching the scheme of the provided url for a dependency in a requirements file, which means a URL like `${LIBRARY_URL}` gets matched as a file and errors out. If we change the variable in the requirements file to `https://${LIBRARY_URL}` and remove the `https://` from the variable value itself, `uv` works as expected.

assuming I'm looking at the right code:
[parse_url](https://github.com/astral-sh/uv/blob/c159a262f2168abc8fd9d7f18ed59e4019e21bec/crates/pep508-rs/src/lib.rs#L749) calls [preprocess_url](https://github.com/astral-sh/uv/blob/c159a262f2168abc8fd9d7f18ed59e4019e21bec/crates/pep508-rs/src/lib.rs#L764) which matches on `scheme`, but since the env var isn't expanded yet, the `https://` isn't there so we hit [this else branch](https://github.com/astral-sh/uv/blob/c159a262f2168abc8fd9d7f18ed59e4019e21bec/crates/pep508-rs/src/lib.rs#L861-L875) which attempts to parse as a path

current uv version:
```
 uv --version
uv 0.1.17 (bb2d06cbb 2024-03-10)
```
### Not functional
`requirements.in`
```
loguru @ ${LOGURU_URL}
```

command
```shell
LOGURU_URL='https://files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl#sha256=003d71e3d3ed35f0f8984898359d65b79e5b21943f78af86aa5491210429b8eb' uv pip compile requirements.in
```

output
```
error: Distribution not found at: file:///Users/mattyrose/work/matty-rose-sandbox/uv-var-substitution/https:/files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl%23sha256=003d71e3d3ed35f0f8984898359d65b79e5b21943f78af86aa5491210429b8eb
```

### Functional
`requirements.in`
```
loguru @ https://${LOGURU_URL}
```

command
```shell
LOGURU_URL='files.pythonhosted.org/packages/03/0a/4f6fed21aa246c6b49b561ca55facacc2a44b87d65b8b92362a8e99ba202/loguru-0.7.2-py3-none-any.whl#sha256=003d71e3d3ed35f0f8984898359d65b79e5b21943f78af86aa5491210429b8eb' uv pip compile requirements.in
```

output
```
Resolved 1 package in 150ms
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in
loguru @ https://${LOGURU_URL}
```

**Comment by charliermarsh** [comment]
Thanks, good catch.

**Comment by matty-rose** [comment]
thanks for the super-speedy fix!
