### ISSUE TITLE
Error compiling langchain with pytorch CPU index URL

### ISSUE THREAD

**Issue by silb-saxobank** [astral-sh/uv#2377]
Compiling langchain with the pytorch CPU index URL gives an error:
```
thread 'main' panicked at crates/uv-resolver/src/resolution.rs:230:50:
no entry found for key
```

MWE:
```bash
echo langchain > requirements.txt && RUST_BACKTRACE=full uv pip compile --verbose -o requirements.out requirements.txt --extra-index-url "https://download.pytorch.org/whl/cpu"
```

This only (?) seems to occur with this index-url, not with any other random index-url I tested.
If I use `pip-tools` it seems to work fine.

Running in WSL2 with uv 0.1.17

Am I missing something obvious here?
Of course, in this MWE I can remove the extra-index-url, but in my original requirements I also need pytorch-cpu and still get this error.

Thanks in advance for the help, and thanks for creating this really cool tool!

**Comment by konstin** [comment]
Langchain has been fixed in https://github.com/astral-sh/uv/pull/2360, could you try running from main if that fixes your problem, too?

**Comment by charliermarsh** [comment]
I suspect the `requests` issue is that `requests` exists on https://download.pytorch.org/whl/cpu, but not at that version. We stop at the first index that contains the dependency.

**Comment by charliermarsh** [comment]
Closing in favor of some other issues. The `no entry found for key` is fixed in the latest release. The "`requests` not found" is discussed in detail here: https://github.com/astral-sh/uv/issues/171.
