### ISSUE TITLE
Hash is missing for url based dependencies

### ISSUE THREAD

**Issue by 9128305** [astral-sh/uv#2378]
uv version: uv 0.1.17 (ec8315166 2024-03-10)
```shell
echo "astpretty @ https://github.com/asottile/astpretty/archive/refs/heads/main.zip" > requirements.in
pip-compile --allow-unsafe --generate-hashes --resolver=backtracking --quiet --strip-extras --no-annotate
uv pip compile --generate-hashes --no-annotate requirements.in
```

**Comment by eth3lbert** [comment]
This would be quite interesting. Currently, uv downloads and builds the source but doesn't store the source archive. In this case, I'm not sure how to recompute the hash if a cache entry exists.
