### ISSUE TITLE
Install uses wrong package location when a secondary Python installation is declared as venv

### ISSUE THREAD

**Issue by adebrecht661** [astral-sh/uv#2387]
On Ubuntu 22.04, with Python installed to `~/.local/bin/python` through a symlink (-> `/usr/bin/python` -> `/usr/bin/python3.11`) and `VIRTUAL_ENV=~/.local/`:

With `uv==0.1.11`, `uv pip install` installs to `~/.local/lib/python3.11/site-packages`. This makes sense.

With `uv==0.1.12`, `uv pip install` attempts to install to `/usr/local/lib/python3.11/dist-packages` (and fails because of insufficient permissions). I would expect this to still attempt to install to `~/.local`, since that was declared as the virtual environment. 

I believe #2353, #2059, #1584, #1526 are related (e.g. the `--user` flag would at least resolve this issue), but it seems like this may be a separate problem with the order of resolution of possible installation locations; that is, I'd expect `uv` to attempt to install to a virtual environment if one is declared, even if the virtual environment eventually resolves to a system(ish) Python installation.

**Comment by charliermarsh** [comment]
I'm not sure on this one... I think it'd be error-prone to treat `~/.local/bin/python` as a virtual environment just because it's set as `VIRTUAL_ENV`. There's just no guarantee at all that (AFAICT?) that `~/.local/lib/python3.11/site-packages` would actually be on `sys.path` at runtime. So we'd end up installing packages that aren't available to the user.

**Comment by charliermarsh** [comment]
A virtual environment has a more "formal" definition (AFAIK), which is, a Python interpreter in which `sys.prefix` and `sys.base_prefix` are not equivalent.

**Comment by charliermarsh** [comment]
I think this is reasonably solved by creating a real virtual environment, or using `--user` once it's supported, but I don't think it's tenable to make assumptions about the paths based on `VIRTUAL_ENV`.

**Comment by charliermarsh** [comment]
I think this would work now with `--prefix ~/.local`?
