### ISSUE TITLE
`uv venv` creates a venv without pip or pip3

### ISSUE THREAD

**Issue by lukecivantos** [astral-sh/uv#2390]
Hey all – our team is running into issues with running `uv venv` locally where it's created without pip/pip3. 

Is this by design as pip should only be called with `uv`? 

When working locally we use `uv venv --python=$(which python3.11)` which creates the `.venv` folder, but in `bin` there's no pip or pip3. 

If I run `python3.11 -m venv .venv` this doesn't happen. We're on version `0.1.17` of uv. 

Here's a screenshot of first the `bin` folder when running uv venv and then after the folder when running the original call.  

<img width="779" alt="image" src="https://github.com/astral-sh/uv/assets/16458635/c2ca7c02-2570-4f89-afbc-a0d2b67ee5cf">

<img width="777" alt="image" src="https://github.com/astral-sh/uv/assets/16458635/359cafa6-7666-458d-ba04-db9c5593cd50">

Thanks!

**Comment by charliermarsh** [comment]
You can run `uv venv --seed` to include `pip`. We don't install `pip` into virtual environments by default, since `uv` on its own is sufficient to install, etc. (It's _supposed_, it's just not the default.)

**Comment by lukecivantos** [comment]
Thanks! If it helps for context – Being able to include mypy just helped us debug some issues around local mypy package issues and the venv looking at the on-device homebrew installs (which we didn't want)  

I'm going to remove `--seed` now, but it was helpful to have as a resource!

**Comment by zanieb** [comment]
Thanks!
