### ISSUE TITLE
Question/ docs: What is the difference, if any, between `pip install --pre` and `uv pip install --prerelease=allow`?

### ISSUE THREAD

**Issue by ivirshup** [astral-sh/uv#2407]
As title, is `uv pip install --prerelease=allow` equivalent to `pip install --pre`? Are there differences I should be aware of?

I'm looking at switching some CI processes over to `uv`, but I'm having a little trouble understanding if I can assume `--prerelease=allow` is equivalent to `--pre`. This is more an issue of not really understanding what `pip`'s `--pre` argument does, since the documentation for it is less specific than the docs here.

Thanks for any guidance!

**Comment by charliermarsh** [comment]
Good question: there's no difference at all. `--pre` is just an alias for `--prerelease=allow`, to match pip's interface.

**Comment by charliermarsh** [comment]
They both mean the same thing: allow prereleases for any dependency.
