### ISSUE TITLE
Unable to upload `uv>=0.1.17` to Azure Artifacts due to `Metadata-Version: 2.3`

### ISSUE THREAD

**Issue by olivierlefloch** [astral-sh/uv#2414]
`uv==0.1.17`'s wheel seems to have switched to `Metadata-Version: 2.3`, which Azure Artifacts does not support:

(same issue with `ruff`) https://github.com/astral-sh/ruff/issues/10378

It's not clear whether this will get resolved promptly by Azure: https://developercommunity.visualstudio.com/t/Uploading-ruff032-to-Azure-Repos-for/10614507

```
Bad Request - Metadata version '2.3' is unsupported. Supported versions
         are: 1.0,1.1,1.2,2.0,2.1.
```

**Comment by charliermarsh** [comment]
We could pin back to Maturin 0.14.0 or whichever it was that preceded Metadata 2.2 (and Metadata 2.3), but Metadata 2.2 and 2.3 are actually good, and soon Poetry and Hatch and others will build source distributions with Metadata 2.2 by default.

**Comment by charliermarsh** [comment]
I'm gonna say for now that we won't roll this back, but if it continues to be a problem for an extended period of time let me know and we can reconsider.
