### ISSUE TITLE
Can't find .dist-info for package with local version string

### ISSUE THREAD

**Issue by jasonprado** [astral-sh/uv#2424]
My requirements.txt has this:
```
my-package==2024.3.13+0873c15
```

When I `uv pip install -r requirements.txt`:

```
error: Failed to download: my-package==2024.3.13+0873c15
  Caused by: No .dist-info directory found
```

If I expand the whl, I see this dir:

```
my_package-2024.3.13_0873c15.dist-info
```

The `+` is being converted to a `_`. I suspect that is why they dist-info can't be found. There is kind of a [mess of Python version strings](https://discuss.python.org/t/escaping-versions-for-wheel-sdist-and-dist-info-names/5605/22) where `+` is a legal part of a version string denoting a local version, but it isn't allowed in the name of the `.dist-info` dir.

Running version `0.1.18` in a docker Linux shell.

**Comment by jasonprado** [comment]
One thing I notice is that pip is not considering the package version in looking for the `.dist-info: https://github.com/pypa/pip/blob/36823099a9cdd83261fdbc8c1d2a24fa2eea72ca/src/pip/_internal/utils/wheel.py#L60

But uv is: https://github.com/astral-sh/uv/blob/91597317920f8c253c8ddb84846719db92f128a4/crates/install-wheel-rs/src/metadata.rs#L69

Perhaps a solution for uv is asserting that there is only one `.dist-info` present and that its path starts with the canonical name of the package, like pip.

**Comment by charliermarsh** [comment]
I'll take a look!

**Comment by charliermarsh** [comment]
Are you able to share how you're building your wheel? E.g. which tool?

**Comment by jasonprado** [comment]
Thanks for submitting a fix. I'll try it out ASAP.

I thought I found some documentation saying that the prefix to `.dist-info` only allowed `_-.` and not `+` but I can't find that source now. We are using bazel with the `aspect_rules_py` package.

**Comment by jasonprado** [comment]
0.1.21 works in our environment at flyzipline.com. Thanks! I'll start looking at migrating over to uv soon.
