### ISSUE TITLE
What is uv's versioning policy?

### ISSUE THREAD

**Issue by hugovk** [astral-sh/uv#2426]
When Ruff reached 0.1.0, a custom versioning scheme was adopted, which is sort of like SemVer with an extra 0. at the start:

* https://docs.astral.sh/ruff/versioning/
* https://github.com/astral-sh/ruff/discussions/6998

uv is already at 0.1.8 but it has a breaking change: https://github.com/astral-sh/uv/releases/tag/0.1.18. This is not a number I'd pay attention to for a breaking change :)

What is uv's versioning policy? SemVer? Custom like Ruff? Another custom scheme? Or even CalVer like pip?

**Comment by zanieb** [comment]
We do not have a versioning policy yet since it's such a new product. I think we're likely to bump the minor version number for major breaking changes but there _will_ be small breaking changes in patch releases as we rapidly improve uv.

**Comment by charliermarsh** [comment]
(Closing as answered _for now_.)
