### ISSUE TITLE
manual uninstallation instructions for uv

### ISSUE THREAD

**Issue by axiomofjoy** [astral-sh/uv#2428]
I installed and uninstalled `uv` via `brew` on my Mac. I am now seeing a Rust-related error message when running a project via a separate toolchain (`conda` with `hatch`). I am not sure if `uv` is the cause of the issue, but I'd like to ensure I successfully uninstalled `uv` from my system for the sake of debugging. Are there any locations I should check to ensure the uninstallation was successful?

```python
hatch run tests
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by zanieb** [comment]
I think `hatch` uses Rust these days so I would look there.

I'm not sure what steps `brew` takes to install `uv` — we generally just download a single binary into `~/.cargo/uv` and nothing else.

**Comment by axiomofjoy** [comment]
@zanieb Thanks for the quick reply! Will do.
