### ISSUE TITLE
Version 0.1.19 breaks AWS CodeArtifact authentication

### ISSUE THREAD

**Issue by tom-engineering** [astral-sh/uv#2444]
`uv` version 0.1.19 gives a 401 error when connecting to a CodeArtifact repo, where 0.1.18 works fine.

uv version: 0.1.19
platform: macOS 14.4 (23E214)

Example:
`uv pip install -r requirements.txt --index-url https://aws:<redacted-key>@<redacted-subdomain>.codeartifact.us-east-1.amazonaws.com/pypi/eng/simple/`

```
error: Failed to download: tenacity==8.1.0
  Caused by: HTTP status client error (401 Unauthorized) for url (https://<redacted-subdomain>.codeartifact.us-east-1.amazonaws.com/pypi/eng/simple/tenacity/8.1.0/tenacity-8.1.0[...])
```

Can't give a repro but it does track with the changes to authentication between 0.1.18 and 0.1.19. The module that fails changes each time, so not specific to the module.

**Comment by charliermarsh** [comment]
Did you try with `--native-tls`?

**Comment by charliermarsh** [comment]
\cc @zanieb - my guess is this is related to the authentication store in some way?

**Comment by tom-engineering** [comment]
> Did you try with `--native-tls`?

Just ran and same result ($UV_INDEX_URL is set as the `--index-url` flag was before):
```
uv pip install --native-tls -r requirements.txt
error: Failed to download and build: strict-rfc3339==0.7
  Caused by: HTTP status client error (401 Unauthorized) for url (https://<redacted-subdomain>.codeartifact.us-east-1.amazonaws.com/pypi/eng/simple/[...])
```

**Comment by charliermarsh** [comment]
Okay, thanks!

**Comment by zanieb** [comment]
Thanks for the report! We should have a fix released shortly

**Comment by ealap** [comment]
Hi @charliermarsh, I can confirm that this issue was fixed on v0.1.20 (#2446) but the issue came back after v0.1.22 (probably due to #2449?)

**Comment by charliermarsh** [comment]
Oh strange! Will take a look.

**Comment by charliermarsh** [comment]
Unfortunately I'm not able to reproduce this when running against an authenticated CodeArtifact index. Are you certain that this is the issue you're running into? And certain that you're on the right uv version, etc.?

**Comment by zanieb** [comment]
@ealap can you open a new issue please and provide verbose logs (`-v`) with your password omitted?

This issue is for AWS CodeArtifact.

**Comment by ealap** [comment]
Sorry, I thought the root issue was generally for basic HTTP authentication / in-URL credentials.

I will create a separate issue.
