### ISSUE TITLE
On M1/2/3 MacOS onnx gets built from source. 

### ISSUE THREAD

**Issue by arshan-ritual** [astral-sh/uv#2456]
## Description
I was installing `onnx` and saw this error:
`cmake not in path` which I got around by installing cmake: `brew install cmake` but was curious why it's required to be built from source? Unsure if this is a `uv` issue or just that `onnx` on pypi hasn't shipped the built version for macos. 

## Reproduce
On an M1/2/3 Mac, run
```
uv pip install onnx
```

## My system
![image](https://github.com/astral-sh/uv/assets/155479767/9b42baca-5e10-4556-81b6-69585435e977)
```
uv --version
uv 0.1.16 (9f1452cb7 2024-03-07)
python --version
Python 3.12.2
```

**Comment by zanieb** [comment]
Hi! `pip` builds this from source too — at https://pypi.org/simple/onnx/ you can see they don't publish Python 3.12 wheels.
