### ISSUE TITLE
How to install uv on google colab

### ISSUE THREAD

**Issue by raybellwaves** [astral-sh/uv#2469]
Firstly, excellent project! Thanks a lot for taking the time to build this and open source it!

Secondly, do you want to enable the discussions tab in the GitHub repo? I find the discussions a good place to ask usage questions (like this) and filters them out of issues which allows Issues to be more focused on bugs and feature requests.

Are they any google colab notebooks out there that install uv then pip install something else (ruff?). I wasn't sure it.

It writing this I just worked out how to do: https://colab.research.google.com/drive/1Lt2mw6zsqcvzmHxcqyp26EX-W5ARt1FZ?usp=sharing

PR incoming.

You are more than welcome to create you own notebook and use the colab button to link it so you can own the notebook

**Comment by renxida** [comment]
I've been using

!pip install uv
!uv pip install --system [packages]

**Comment by konstin** [comment]
I've made a notebook showing the two main options, using pip (as renxida showed) and using our standalone installer: <https://colab.research.google.com/drive/1yXx2Xbmgsx34q5lsKEchwEBo5dGbmRa8>. I've skipped the pipx installation since pipx is not preinstalled on colab.

**Comment by jas-ho** [comment]
> I've made a notebook showing the two main options, using pip (as renxida showed) and using our standalone installer: https://colab.research.google.com/drive/1yXx2Xbmgsx34q5lsKEchwEBo5dGbmRa8. I've skipped the pipx installation since pipx is not preinstalled on colab.

thanks for putting this together!

For both of these options I end up with 
```
error: No Python interpreters found in system toolchains
```
when trying to do `uv pip install ...`.
