### ISSUE TITLE
VIRTUAL_ENV not respected

### ISSUE THREAD

**Issue by PrinceJunkie** [astral-sh/uv#2472]
I'm using uv primarily in a devcontainer where I don't have root rights and I don't want a .venv folder in the project folder.
Therefore I've set VIRTUAL_ENV to /home/dev/.local and everything should be installed there but right now it throws a Permission denied with a path which is not VIRTUAL_ENV.
  
I was using this exact setup before and it was working fine. Unfortunately I don't know the version in which it worked. It seems like VIRTUAL_ENV is not respected anymore.

Here's my devcontainer docker file:
Dockerfile:
```dockerfile
ARG PYTHON_VERSION="3.12"

FROM mcr.microsoft.com/vscode/devcontainers/python:${PYTHON_VERSION}-bullseye
ENV VIRTUAL_ENV=/home/dev/.local \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

RUN pip install --upgrade pip \
    && rm /usr/bin/python3 && ln -s /usr/local/bin/python /usr/bin/python \
    && usermod -l dev -d /home/dev -m vscode \
    && sed -i 's/vscode/dev/' /etc/sudoers.d/vscode \
    && mv /etc/sudoers.d/vscode /etc/sudoers.d/dev \
    # Install uv as dev user
    && wget https://astral.sh/uv/install.sh && chmod 755 install.sh && sudo -H -u dev /install.sh && rm /install.sh
```

and here's what I'm running in the postCreateCommand (basically executing this as the dev user in a shell)
```bash
PYTHON_VERSION=$(python3 -c "import sys; print(f'python{sys.version_info.major}.{sys.version_info.minor}')")
mkdir -p $HOME/.local/bin
mkdir -p $HOME/.local/lib/$PYTHON_VERSION/site-packages
ln -s /usr/local/bin/python $HOME/.local/bin/python
uv pip install -r requirements-dev.txt
```

Here's the output while trying to e.g. install pytest:
```bash
dev ➜ /project $ echo $VIRTUAL_ENV    
/home/dev/.local
dev ➜ /project $ uv pip install pytest --verbose
DEBUG Found a virtualenv through VIRTUAL_ENV at: /home/dev/.local
DEBUG Cached interpreter info for Python 3.12.2, skipping probing: /home/dev/.local/bin/python
DEBUG Using Python 3.12.2 environment at /home/dev/.local/bin/python
DEBUG Using registry request timeout of 300s
DEBUG Solving with target Python version 3.12.2
DEBUG Adding direct dependency: pytest*
DEBUG Found fresh response for: https://pypi.org/simple/pytest/
DEBUG Searching for a compatible version of pytest (*)
DEBUG Selecting: pytest==8.1.1 (pytest-8.1.1-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/4d/7e/c79cecfdb6aa85c6c2e3cf63afc56d0f165f24f5c66c03c695c4d9b84756/pytest-8.1.1-py3-none-any.whl.metadata
DEBUG Adding transitive dependency: iniconfig*
DEBUG Adding transitive dependency: packaging*
DEBUG Adding transitive dependency: pluggy>=1.4, <2.0
DEBUG Found fresh response for: https://pypi.org/simple/iniconfig/
DEBUG Found fresh response for: https://pypi.org/simple/pluggy/
DEBUG Found fresh response for: https://pypi.org/simple/packaging/
DEBUG Searching for a compatible version of iniconfig (*)
DEBUG Selecting: iniconfig==2.0.0 (iniconfig-2.0.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/a5/5b/0cc789b59e8cc1bf288b38111d002d8c5917123194d45b29dcdac64723cc/pluggy-1.4.0-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/ef/a6/62565a6e1cf69e10f5727360368e451d4b7f58beeac6173dc9db836a5b46/iniconfig-2.0.0-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of packaging (*)
DEBUG Selecting: packaging==24.0 (packaging-24.0-py3-none-any.whl)
DEBUG Searching for a compatible version of pluggy (>=1.4, <2.0)
DEBUG Selecting: pluggy==1.4.0 (pluggy-1.4.0-py3-none-any.whl)
Resolved 4 packages in 6ms
DEBUG Requirement already cached: iniconfig==2.0.0
DEBUG Requirement already cached: packaging==24.0
DEBUG Requirement already cached: pluggy==1.4.0
DEBUG Requirement already cached: pytest==8.1.1
DEBUG Unnecessary package: gitpython==3.1.41
DEBUG Unnecessary package: gitdb==4.0.11
DEBUG Preserving seed package: setuptools==69.0.3
DEBUG Unnecessary package: smmap==5.0.1
DEBUG Preserving seed package: pip==24.0
DEBUG Preserving seed package: wheel==0.42.0
error: Failed to install: iniconfig-2.0.0-py3-none-any.whl (iniconfig==2.0.0)
  Caused by: failed to create directory `/usr/local/lib/python3.12/site-packages/iniconfig`
  Caused by: Permission denied (os error 13)
```
* The current uv platform.
Devcontainer: mcr.microsoft.com/vscode/devcontainers/python:3.12-bullseye on Apple Silicon
* The current uv version (`uv --version`).
uv 0.1.20

**Comment by helderco** [comment]
To properly setup a virtual environment you need to update PATH as well:
```Dockerfile
ENV VIRTUAL_ENV=/home/dev/.local
ENV PATH=$VIRTUAL_ENV/bin:$PATH
```

**Comment by PrinceJunkie** [comment]
Setting PATH didn't change anything.

If you don't have a python file under the VIRTUAL_ENV/bin path it fails:
````
error: failed to canonicalize path `/home/dev/.local/bin/python`
  Caused by: No such file or directory (os error 2)
```

Didn't think about using uv venv, thanks for that!

**Comment by charliermarsh** [comment]
Yeah, I'd suggest using `uv venv --seed` and running within a virtual environment.

**Comment by PrinceJunkie** [comment]
Thanks, that worked but I don't know why. Could someone of you explain it to me why using `uv venv --seed `doesn't end in a permission denied error?

**Comment by charliermarsh** [comment]
Likely because if you run `pip` outside of the virtualenv, or without `--seed`, that will be the system `pip`, and so you'll get an error when you try to `pip install`. If you use `--seed`, then we'll include a version of `pip` in the virtualenv, so once you activate it, that `pip install` will install into the virtual environment, which avoids any permission denied issues.

**Comment by charliermarsh** [comment]
(We don't include `pip` in the virtualenv by default (and hence require `--seed`) because in most cases you shouldn't need it if you're already using `uv`. It's supported, of course, via `--seed`, but not the default.)

**Comment by charliermarsh** [comment]
(Gonna close but happy to answer any more questions!)

**Comment by PrinceJunkie** [comment]
> Likely because if you run `pip` outside of the virtualenv, or without `--seed`, that will be the system `pip`, and so you'll get an error when you try to `pip install`. If you use `--seed`, then we'll include a version of `pip` in the virtualenv, so once you activate it, that `pip install` will install into the virtual environment, which avoids any permission denied issues.

Yeah but I was getting the problem while using `uv pip install pytest` or did I miss sth. obvious?

**Comment by charliermarsh** [comment]
Ah yeah. I think the issue there is that you were using `VIRTUAL_ENV` to point to `/home/dev/.local`. But that's not quite the same as installing into a virtual environment, even one rooted at `/home/dev/.local`, since when uv asks the Python interpreter for the "correct install path", it will tell it to use a system path that will then yield a permission error.

**Comment by Zer0x00** [comment]
Thanks for the explanation and keep up the great work!
