### ISSUE TITLE
Should `--reinstall` default to true  with `uv pip install --editable .`?

### ISSUE THREAD

**Issue by tlambert03** [astral-sh/uv#2481]
If you run `pip install -e .` in a directory that has already been installed, I believe the default behavior is to re-install the package.  That's my observation, but please correct me if I'm wrong, or if I've missed something.

With uv pip, it does not reinstall unless you explicitly pass the `--reinstall` flag:

```
$ uv pip install -e .
Audited 1 package in 4ms

$ uv pip install -e . --reinstall
Building file:///Users/...
░░░░░░░░░░░░░░░░░░░░ [0/1] Fetching packages...
```

I think whenever I'm doing `pip install -e .`, I usually *want* it to do anything it might normally do during installation (such as re-compiling c extensions, etc...).  So, with `uv`, I regularly find myself needing re-enter the command with `--reinstall`.

I'm curious whether that was a conscious decision to use a different behavior from `pip`?  Explicit is always clearer of course, but muscle memory is strong too :)

**Comment by charliermarsh** [comment]
We use some heuristics to decide whether to rebuild the package (e.g., if the `pyproject.toml` or `setup.py` has changed), but then expect users to use `--reinstall` if they have out-of-band changes that need to be respected.

**Comment by charliermarsh** [comment]
This is basically the same as https://github.com/astral-sh/uv/issues/2152, so I'll merge in there.

**Comment by tlambert03** [comment]
thanks.  missed that issue
