### ISSUE TITLE
Fail if req name and metadata name mismatch

### ISSUE THREAD

**Issue by wimglenn** [astral-sh/uv#2484]
pip refuses to install a .whl if the req is wrong, e.g.

```
$ pip install 'dateutil @ file:///tmp/python_dateutil-2.9.0.post0-py2.py3-none-any.whl'
Processing /tmp/python_dateutil-2.9.0.post0-py2.py3-none-any.whl
ERROR: dateutil has an invalid wheel, .dist-info directory 'python_dateutil-2.9.0.post0.dist-info' does not start with 'dateutil'
```

uv pip install should probably do the same? currently, it's happy with something like

```
uv pip install 'whatever @ file:///tmp/python_dateutil-2.9.0.post0-py2.py3-none-any.whl'
```

**Comment by zanieb** [comment]
Thanks for the report. I imagine this would be annoying before we do #313, otherwise I'm all for it.

**Comment by charliermarsh** [comment]
We enforce this in most cases — definitely when building source distributions. We probably need to add enforcement in a few codepaths. (I don’t think #313 is required.)
