### ISSUE TITLE
pip list shows more than uv pip list

### ISSUE THREAD

**Issue by lkadin** [astral-sh/uv#2499]
Not sure if this is really an issue.
I installed uv on Windows 11 globally from your PS download 

I then did a uv venv and activated it.

I tried pip list and pip freeze and they both had a lot more packages than the corresponding uv pip list and uv pip freeze.

File is attached
[diff.txt](https://github.com/astral-sh/uv/files/14628806/diff.txt)

**Comment by zanieb** [comment]
Are they listing the same environment? `pip` is not included in `uv` virtual environments by default so you could be using one outside of it? You can get `pip` with `uv pip install pip` or `uv venv --seed`.

If there are still difference please share the verbose output from both tools.

**Comment by lkadin** [comment]
That was the issue. Thanks. This issue can be closed.
