### ISSUE TITLE
Improper Caching - failed to unpack - Is a directory

### ISSUE THREAD

**Issue by AiyionPrime** [astral-sh/uv#2539]
This one might be a nasty one.
The problem is not reliably reproducible, yet.

We've got a jenkins, which runs multiple steps invoking `uv pip` in **parallel**.
building the package, running tests (and installling test requirements), building the docs (and install theirs as well).

They are running in the same workspace and share `~/home/jenkins/.cache/uv/`.
Is this form of concurrent access allowed?

And further:
If one of the parallel stages fails early the others get **aborted**.
Might this leave the cache in strange states as well?

We're hitting several seemingly random problems right now, the most clear of them being:

```bash
lint: install_package> venv/bin/uv pip install --reinstall --no-deps my-project@/home/localuser/jenkins/workspace/my-project-py_PR-655/.tox/.tmp/package/2/my-project-1.1.0rc3.dev2+ge757c45.tar.gz

[35](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-35)
error: Failed to build: my-project @ file:///home/localuser/jenkins/workspace/my-project-py_PR-655/.tox/.tmp/package/2/my-project-1.1.0rc3.dev2+ge757c45.tar.gz

[36](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-36)
  Caused by: Failed to extract archive

[37](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-37)
  Caused by: failed to unpack `/home/jenkins/.cache/uv/built-wheels-v0/.tmpJZqxvB/my-project-1.1.0rc3.dev2+ge757c45/src/my_project/common/sendable_commands/schemas`

[38](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-38)
  Caused by: failed to unpack `my-project-1.1.0rc3.dev2+ge757c45/src/my_project/common/sendable_commands/schemas/` into `/home/jenkins/.cache/uv/built-wheels-v0/.tmpJZqxvB/my-project-1.1.0rc3.dev2+ge757c45/src/my_project/common/sendable_commands/schemas`

[39](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-39)
  Caused by: Is a directory (os error 21)

[40](https://jenkins.somecompany.net/job/my-project-py/job/PR-655/25/pipeline-console/?start-byte=0&selected-node=99#log-40)
lint: exit 2 (0.09 seconds) /home/localuser/jenkins/workspace/my-project-py_PR-655> venv/bin/uv pip install --reinstall --no-deps my-project@/home/localuser/jenkins/workspace/my-project-py_PR-655/.tox/.tmp/package/2/my-project-1.1.0rc3.dev2+ge757c45.tar.gz pid=1494
```

We're using `tox-uv 1.5.1` and and uv 0.1.22`.
The problem is not new in these versions.

**Comment by charliermarsh** [comment]
Yes, this form of concurrent access should work fine.

**Comment by charliermarsh** [comment]
I will take a look.

**Comment by AiyionPrime** [comment]
Thank you, that's highly appreciated.

**Comment by charliermarsh** [comment]
No prob. The cache is designed to be robust to concurrent access so any errors of this form are a bug.

**Comment by charliermarsh** [comment]
Is it possible for you to try installing _just_ that package? I'm trying to understand if this is in any way specific to the contents of the package. (I assume you can't share it.)

**Comment by charliermarsh** [comment]
Oh sorry, I misread -- you are installing _just_ that package, got it.

**Comment by charliermarsh** [comment]
I honestly might need the package in order to debug this. It could be trimmed down and obfuscated as long as it reproduces.

**Comment by AiyionPrime** [comment]
This might very well be a fail on our end.
I'm running a pipeline to verify this, but I think I messed up:
One of the five things we do in parallel is `python -m build .` (within a tox step).

As I learned today, `setuptools` is not supposed to run in parallel with anything,
as it builds e.g. sdist parts right within your project folder.
It creates an intermediate directory e.g. `my-project-1.1.0rc3.dev2+ge757c45` and copies src and test directories in it.

It does so for about 140ms and creates a tar from this new folder, puts that into its output directory and deletes its temporary folder afterwords.
Internally this folder is called `base_dir` if someone wants to look it up.

Furthermore this might not only happen upon our explicit build step, but each of the tox steps might do this implicitely.

**Comment by AiyionPrime** [comment]
Alright, that appears to have been it.
Upon entering a `tox` run (which happens 5 times in parallel for us) `tox` starts building an sdist to then install and use, unless configured otherwise.
Building an sdist with `setuptools` does not happen in the target folder, but in the project root, which these 5 `tox` incarnations then simultaneously use to build a directory to then compress into the output dir.

Each of the 5 `tox run` creates a directory to copy source and test files into.
If this happens at the same time (which `uv` seems to abet by reliable speed) the folder creations collide with the above error.

**Comment by AiyionPrime** [comment]
This is not a bug in `uv`, not in `tox-uv` either, but something that should be fixed in setuptools, imho.

**Comment by charliermarsh** [comment]
Thanks so much for following up.

**Comment by AiyionPrime** [comment]
Thanks for your fast responses :)
This project looks really nice, we're looking forward to use it in more of our repos.
