### ISSUE TITLE
Support nightly PyTorch installs

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2541]
See: https://github.com/astral-sh/uv/issues/2008.

Commands like `pip install -U --prerelease allow torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121` currently fail, and it's inconvenient to add the `+cu121` specifiers where necessary because the user is intentionally pulling in the "latest" release, and so doesn't want to add a dedicated version specifier.

**Comment by charliermarsh** [comment]
I think it's possible we could support that specific case by extracting the name and version from the wheel filename (i.e., the URL). Can I ask why you prefer to use direct references for these?

**Comment by ewhauser** [comment]
This is an existing requirements file so it is possible there is no good reason under `uv`. However, in order for this to work without direct references, you have to specify:

```
 --extra-index-url https://download.pytorch.org/whl/cu118
torch==2.2.1+cu118
torchaudio==2.2.1+cu118
```

which I assume has a performance hit for large requirements files? It does for `pip-tools`. 

I did try that with `uv` and it started to choke on some of our dependencies that were valid:

```
 certifi==2024.2.2

 --extra-index-url https://download.pytorch.org/whl/cu118

 whisperX @ https://github.com/m-bain/whisperX/archive/befe2b242eb59dcd7a8a122d127614d5c63d36e9.zip
 pyannote-audio @ git+https://github.com/pyannote/pyannote-audio@11b56a137a578db9335efc00298f6ec1932e6317
 torch==2.2.1+cu118
 torchaudio==2.2.1+cu118
 pytorch_triton @ https://download.pytorch.org/whl/nightly/pytorch_triton-2.1.0%2B7d1a95b046-cp311-cp311-linux_x86_64.whl
```

```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of certifi==2024.2.2 and you require certifi==2024.2.2, we can conclude that the requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
Ah yeah, that's because certifi is published on https://download.pytorch.org/whl/cu118, but only at a different version. We don't allow dependencies to pull "mixed" versions from across indexes as a security measure.

**Comment by charliermarsh** [comment]
Anyway, I think we can support this specific thing with the URLs.

**Comment by charliermarsh** [comment]
I created a new issue to track that here: https://github.com/astral-sh/uv/issues/2623

**Comment by fernandogrd** [comment]
> Ah yeah, that's because certifi is published on https://download.pytorch.org/whl/cu118, but only at a different version. We don't allow dependencies to pull "mixed" versions from across indexes as a security measure.

Hi, just experienced this today, specially the different versions of packages being available in the pytorch.

The `@` workaround worked, but wondering if there would be other workarounds by now as it is a bit tedious to copy the link of each package specially when there a number of them.

**Comment by charliermarsh** [comment]
This works now!

```
uv pip install -U --prerelease allow torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```
