### ISSUE TITLE
"Stray quotes" fixup can lead to invalid markers

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2551]
The "stray quotes" fixup will remove quotes from markers, e.g., `numpy (>=1.19) ; python_version >= "3.7"` gets rewritten as `numpy (>=1.19) ; python_version >= 3.7`.

**Comment by fatelei** [comment]
i want to have a try

**Comment by zanieb** [comment]
Just let us know here or in a draft pull request if you need any help!
