### ISSUE TITLE
Incorrect version of torchvision is installed

### ISSUE THREAD

**Issue by hovnatan** [astral-sh/uv#2562]
When trying `uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu` older than necessary version of `torchvision` is installed and the installed version is without `+cpu` flag. Running `pip install ...` without `uv` works fine. I think this can be related to https://github.com/python-poetry/poetry/issues/2543.

**Comment by charliermarsh** [comment]
For PyTorch with uv, you generally need to be specifying the `+` suffixes directly. There's more on the limitations and differences from pip here: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers.
