### ISSUE TITLE
Warn when using `uv` with an incompatible Python version.

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/uv#2587]
`uv` only supports Python 3.8 or newer. However, that's not very obvious from our documentation (you need to scroll all the way down to platform support) and some or even most functionality works fine, even when using `uv` with a Python version older than 3.8, e.g. the Python discovery works fine and uv only fails to run scripts (https://github.com/astral-sh/uv/issues/2445).

`uv` should print a warning message when creating a virtual env or installing into a global Python environment when Python is older than 3.8 to make users aware that their platform isn't officially supported.

**Comment by charliermarsh** [comment]
In our defense, it's also at the very top of the repo:

![Screenshot 2024-03-21 at 9 43 17 AM](https://github.com/astral-sh/uv/assets/1309177/27bcb1ec-a54f-467d-87aa-fb5f85069014)
