### ISSUE TITLE
Remove self-update feature for other distributors

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2588]
We should make it an opt-in feature that we enable in our release pipeline. It would still be enabled for `pip install uv`, unfortunately, but it's a lot more work to prevent that.

**Comment by zanieb** [comment]
We shouldn't just suggest that downstream package maintainers turn it off?

**Comment by charliermarsh** [comment]
It's already on for `pip install uv`.

**Comment by charliermarsh** [comment]
I think the feature should be opt-in not opt-out, if we're the only ones that want it on. (Right now, it can't be opted at all.)

**Comment by charliermarsh** [comment]
We can turn it off for `pip install uv`, but it requires writing the release pipeline to build separate binaries for PyPI vs. the installers, and then running every release build twice.
