### ISSUE TITLE
uv pip compile fails with conflicting urls (sha vs tag) across dependencies

### ISSUE THREAD

**Issue by fraenkel** [astral-sh/uv#2614]
I am issuing the following `pipenv requirements | uv pip compile --generate-hashes -o requirements.txt -` which fails with:
```
error: There are conflicting URLs for package `common`:
- git+ssh://git@github.com/cerebrotech/platform-python-common.git@565787e8abc8a81b18ea49770f98df09453987e6
- git+ssh://git@github.com/cerebrotech/platform-python-common.git@v3.0.1
```

git shows the following for the v3.0.1 tag: 
`commit 565787e8abc8a81b18ea49770f98df09453987e6 (HEAD -> develop, tag: v3.0.1, origin/develop, origin/HEAD)`

The current package has the following in its requirements.txt
`common@ git+ssh://git@github.com/cerebrotech/platform-python-common.git@565787e8abc8a81b18ea49770f98df09453987e6`

However there is a dependency on another package `platform-python-catalog` which has in its pyproject.toml, 
`"common @ git+ssh://git@github.com/cerebrotech/platform-python-common.git@v3.0.1"`

According to the debug, the failure occurs when resolving
`DEBUG Searching for a compatible version of catalog @ git+ssh://git@github.com/cerebrotech/platform-python-catalog.git@11866ba07919d174c77b8a161c0f10b0073003c8 (*)`

**Comment by zanieb** [comment]
Related https://github.com/astral-sh/uv/issues/1903 / #2285

**Comment by charliermarsh** [comment]
The common way to support this is to add `git+ssh://git@github.com/cerebrotech/platform-python-common.git@v3.0.1` as a constraint. (I'm not certain whether we'll support it in general without the constraint.)
