### ISSUE TITLE
Document `--only-binary` behavior when using unnamed requirements

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#2620]
We should highlight all exemptions from `--only-binary` and note differences from `pip` in our compatibility document. Note that `pip` does not necessarily have intuitive behavior here as discussed in https://github.com/astral-sh/uv/pull/2600#discussion_r1534779844. This is also an opportunity to highlight any behaviors we should change.

**Comment by zanieb** [comment]
@charliermarsh could you do this?

**Comment by charliermarsh** [comment]
Yeah

**Comment by charliermarsh** [comment]
Doing now.
