### ISSUE TITLE
uv pip compile `--no-header` flag should delete existing headers for feature parity with pip-compile

### ISSUE THREAD

**Issue by danielstrizhevsky** [astral-sh/uv#2631]
If I have headers already in my `requirements.txt` and run `pip-compile` with `--no-header`, the headers will be deleted in the output `requirements.txt`

With `uv pip compile --no-header`, the existing header still persists.

My use case is that I expect there to be no header when I pass `--no-header`, so that I can write my own custom header.

Currently on `uv 0.1.22`

**Comment by charliermarsh** [comment]
Are you writing to the `requirements.txt` with `-o`? In my testing we do clear the header, so I can't reproduce this.

**Comment by danielstrizhevsky** [comment]
No, not using `-o`. I'll see if I can reproduce it in a simpler setup!

**Comment by charliermarsh** [comment]
Unlike `pip-compile`, we don't output to a `requirements.txt` implicitly. You have to specify `-o`. Could that be it?

**Comment by danielstrizhevsky** [comment]
Yeah that sounds like it's probably it. Thank you!
