### ISSUE TITLE
`uv pip install` should create a virtualenv if no `venv` is found

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2661]
This seems like a better (and more beginner-friendly) default behavior than erroring.

**Comment by adzenith** [comment]
Alternatively, it could print out a helpful message. I think of when you try to `git commit` for the first time. Here I unset user.name to trigger it:
<img width="428" alt="image" src="https://github.com/astral-sh/uv/assets/614934/663ca1d6-f52a-4e14-9748-3b7a934028fa">
Then beginners can create a venv without having to hit Google and pros can realize they have their venv set up wrong and act accordingly.

**Comment by gwdekker** [comment]
I think this might run into issues for cases where the user is not in the directory where they should be, for example they are by accident one directory above where they think they are. Erroring with a helpful error message is much preferable I feel in that case than assuming the intention. I think the original design decision of either trying to find a virtual env, or explicitly asking for one to get created, is preferable to silently creating one.

**Comment by liquidcarbon** [comment]
It could be helpful to have a flag for WHERE to install.  Like:
```
--venv=.venv
or
--where=elsewhere/.venv
```

In the situation the very first uv pip install, in the absence existing `.venv` or this flag, go interactive.

**Comment by astrojuanlu** [comment]
Strong +1 to this. We've become numb to how difficult venvs are to explain to beginners. If the default is to create one, they become a bit more invisible and that lowers the barrier of entry, in a way fulfilling the dream of PEP 582
