### ISSUE TITLE
Download Progress Bar for Large Files

### ISSUE THREAD

**Issue by Aydinhamedi** [astral-sh/uv#2667]
I would like to request a feature for the `uv` package: a download progress bar for large files during installation. This would enhance the user experience by providing visual feedback on the download status, especially when installing sizable packages like `torch` using the command `uv pip install torch`.

**Comment by charliermarsh** [comment]
I'm open to something like this but we need it to work with highly concurrent downloads.

**Comment by zanieb** [comment]
This is a duplicate of https://github.com/astral-sh/uv/issues/1209
