### ISSUE TITLE
Freeze generated requirements aren't properly formatted for git and local dependencies

### ISSUE THREAD

**Issue by tonydavis629** [astral-sh/uv#2677]
I have a project with dependencies installed from github and from local disk.

```
uv pip freeze > requirements.txt
```
generates a requirements.txt with lines such as 
```
cutie==1.0.0 (from file:///home/jovyan/clips-labeler/Cutie)
segment-anything==1.0 (from git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588)
```
I try to install from this requirements.txt
```
uv pip install -r requirements.txt
```
and it seems the requirements.txt is not in the right format for these types of dependencies.
```
error: Couldn't parse requirement in `requirements.txt` at position 250
  Caused by: Trailing `(from file:///home/jovyan/clips-labeler/Cutie)` is not allowed
cutie==1.0.0 (from file:///home/jovyan/clips-labeler/Cutie)
```
and 
```
error: Couldn't parse requirement in `requirements.txt` at position 1848
  Caused by: Trailing `(from git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588)` is not allowed
segment-anything==1.0 (from git+https://github.com/facebookresearch/segment-anything.git@6fdee8f2727f4506cfbbe553e23b895e27956588)
```

I can manually modify these lines to use the '@' for uv, but I feel like this should be the default.

**Comment by zanieb** [comment]
Thanks for the report!

**Comment by charliermarsh** [comment]
Do you know what uv version you're on? This was fixed long ago.

**Comment by charliermarsh** [comment]
See:

- https://github.com/astral-sh/uv/issues/1931
- https://github.com/astral-sh/uv/pull/1936

**Comment by tonydavis629** [comment]
Indeed I was on an older version. You guys are moving so fast you think 3 weeks is a long time!

**Comment by charliermarsh** [comment]
Thanks so much for following up :)
