### ISSUE TITLE
Activation prompt shows wrong path on windows and nushell

### ISSUE THREAD

**Issue by BenediktMaag** [astral-sh/uv#2687]
When creating an environment in nushell (uv venv) it tells me how to activate:

- Activate with: overlay use .venv\bin\activate.nu

Since I am on windows, the subfolder containing the activation files is called Scripts.
When creating the environment within powershell the prompt points to the right folder:

- Activate with: .venv\Scripts\activate

**Comment by charliermarsh** [comment]
What's the "correct" invocation on nushell on Windows?
