### ISSUE TITLE
Problem with `scikit-build-core` backend

### ISSUE THREAD

**Issue by chainyo** [astral-sh/uv#2689]
Hi, thanks for this initiative, I'm impatient to have a cargo grade dev tools environment for python.

This issue is related to this one I opened in `rye` initially, but in fact is totally related to the `uv` process under the hood. https://github.com/astral-sh/rye/issues/872

I can install the `cugraph` library (poorly packaged but that's another subject) just fine with `uv` by doing this command in a python 3.9.18 .venv:

`uv pip install "cugraph-cu12==24.02.*" --extra-index-url "https://pypi.nvidia.com"`

Outputs:

![CleanShot 2024-03-27 at 12 11 49](https://github.com/astral-sh/uv/assets/50595514/8870ff26-3b5e-4b09-8550-b2833c59f363)

The problem arises when I'm trying to run the `rye sync --features gpu` command I get a lock file generation error.
It might be because the `cugraph` library is using the `scikit-build-core` backend and this backend isn't handled by `uv` yet?

Here is the error I have:

```bash
rye sync --features gpu
Reusing already existing virtualenv
Generating production lockfile: /home/user/foo/requirements.lock
error: Failed to download and build: cugraph-cu12==24.2.0
  Caused by: Failed to build: cugraph-cu12==24.2.0
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/home/user/.cache/uv/.tmpD0iI7V/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/home/user/.cache/uv/.tmpD0iI7V/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/home/user/.cache/uv/.tmpD0iI7V/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/user/.cache/uv/.tmpD0iI7V/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 90, in <module>
RuntimeError: Bad params
---
error: could not write production lockfile for project

Caused by:
    failed to generate lockfile
``` 

Here is the minimal reproduction steps:

1. `rye init --lib foo`
2. `rye pin 3.10`
3. Add the following to your `pyproject.toml`

```toml
[[tool.rye.sources]]
name = "cugraph-cu12"
url = "https://pypi.nvidia.com"
type = "index"

[project.optional-dependencies]
gpu = ["cugraph-cu12==24.2.0"]
```

4. `rye sync --features gpu`

**Comment by charliermarsh** [comment]
Ah yeah -- this does look like a problem with the failed build, but I'm not sure on the source. My guess is that `pip` would also fail if you tried to install `cugraph-cu12==24.2.0` with that specific Python executable and version.

I've run into this in the past when trying to build packages from source with an incompatible CUDA or cuDNN version installed, but I can't say definitively that that's the problem...

**Comment by chainyo** [comment]
> uv pip install "cugraph-cu12==24.02.*" --extra-index-url "https://pypi.nvidia.com"



> Ah yeah -- this does look like a problem with the failed build, but I'm not sure on the source. My guess is that `pip` would also fail if you tried to install `cugraph-cu12==24.2.0` with that specific Python executable and version.

I tried both `uv pip` and `pip` and the package is found correctly with this command:

`[uv] pip install "cugraph-cu12==24.02.*" --extra-index-url "https://pypi.nvidia.com"`

Weird thing it seems that the retrieved versions were cp310 comaptible while I'm in a python 3.9.18 .venv atm.
