### ISSUE TITLE
Use separate resource pools for downloads and source distribution builds

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#2719]
I believe we have a fixed concurrency limit, and the atomic unit is "get the wheel for this distribution". For built distributions, that's typically a download + unzip. For source distributions, it's a download + unzip + build.

We should use separate pools for downloading vs. building, since we otherwise risk not saturating the network while we build.

**Comment by charliermarsh** [comment]
@konstin - You may also find this interesting / relevant.

**Comment by charliermarsh** [comment]
I think doing this fully-correctly is non-trivial since we need to change the source distribution database to return an unbuilt source.

**Comment by charliermarsh** [comment]
I'm trying a simpler thing to start: just use separate pools for wheels and source distributions.

**Comment by konstin** [comment]
Our pool size is currently 50, how many of those would be taken by source dist builds, do you have an example?

**Comment by charliermarsh** [comment]
Well I think the things we want are...

- We should start building source distributions ASAP, and always be building as many as we have cores.
- We should continue to download wheels at a high rate even while building source distributions.

I'm just testing against the requirements that messense posted in the other issue.

**Comment by konstin** [comment]
Solved by #3493
