### ISSUE TITLE
Installing from subdirectories is broken in 0.1.26 (and 0.1.25 probably)

### ISSUE THREAD

**Issue by abdulhaq-e** [astral-sh/uv#2727]
A  dependency defined using a subdirectory fails to generate the lockfile in `0.1.26`. 

An example dependency is: `"mersal @ git+ssh://git@github.com/mersal-org/mersal.git@trunk#subdirectory=core"`

The error message is:

```
error: Failed to download and build: mersal @ git+ssh://git@github.com/mersal-org/mersal.git@trunk#subdirectory=core
  Caused by: Package metadata name `mersal-virtual-workspace` does not match given name `mersal`
error: could not write production lockfile for project
```

The error was originally obtained using `rye sync` but then I switched to using `uv` directly via `uv pip compile pyproject.toml -o requirements.txt`

What is happening: The process is finding a `pyproject.toml` at the root directory which has a package metadata name `mersal-virtual-workspace`. This didn't happen in version `0.1.24` or before (I tested from `01.20`).

With `0.1.25`, I get a different error which I believe is now resolved in `0.1.26` (https://github.com/astral-sh/uv/pull/2712):

```
 Caused by: Failed to deserialize cache entry
  Caused by: expected version to start with a number, but no leading ASCII digits were found
```

However, looking at the changelog, the original error was probably caused by a change in `0.1.25`.

**Comment by abdulhaq-e** [comment]
If I had to guess, it's probably not the subdirectory handling itself being broken but the existence of a `pyproject.toml` in the root directory is throwing the resolver.

**Comment by zanieb** [comment]
Thanks for the thorough report! If you have time, could you share a reproduction with a public repository?

Note for us, we should add test coverage for this in https://github.com/astral-test/uv-public-pypackage or another repository (`uv-pypackage-workspace` or something).

cc @charliermarsh

**Comment by charliermarsh** [comment]
Not immediately obvious to me how this would be happening.

**Comment by charliermarsh** [comment]
Sorry, yes it is. Easy fix, my mistake.

**Comment by charliermarsh** [comment]
Fixed in the next release, apologies.
