### ISSUE TITLE
Document that it's safe to run multiple `uv` instances in a single venv

### ISSUE THREAD

**Issue by charlesnicholson** [astral-sh/uv#2730]
Historically, pip has had a [hard time](https://github.com/pypa/pip/issues/2361) with multiple instances running concurrently. Pip's cache could get corrupted, the venv could get corrupted, etc.

Is it safe to run multiple instances of `uv pip install ...` against the same venv at the same time? I don't see this documented on the markdown landing page. It would be great if `uv` could be run concurrently, even if the strategy is just "lock the entire venv" and have the other `uv` instance(s) block.

**Comment by charliermarsh** [comment]
Yeah we designed uv with this in mind. There are two components to it: (1) we do lock the venv when installing, and (2) the cache is designed to be append-only (so installing into separate venvs concurrently should also be fine).

**Comment by charlesnicholson** [comment]
That's great to hear! Could I ask that this be part of the documentation? It would help people with pip scars  :)

**Comment by charliermarsh** [comment]
Will do!
