### ISSUE TITLE
Update macOS cache test to use `actions/setup-python`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#2734]
No real reason for this test to use Brew's Python. It's probably faster to just install from the GitHub official setup-python action.

_Originally posted by @zanieb in https://github.com/astral-sh/uv/pull/2729#discussion_r1545394084_

**Comment by zanieb** [comment]
This should be a simple change to the `ci.yaml` file and is a great way to make a first contribution to the project.

**Comment by charliermarsh** [comment]
I thought it was intended to literally test Brew Python installs.

**Comment by zanieb** [comment]
`system-test-macos-aarch64` is intended to cover a Brew Python install `cache-test-macos-aarch64` should be Python interpreter agnostic.

**Comment by zanieb** [comment]
Sorry I did this in #2735 because CI was broken.
