### ISSUE TITLE
uv venv references already existing environment instead of creating new

### ISSUE THREAD

**Issue by Ssslakter** [astral-sh/uv#2737]
I've just started using uv, but I couldn't find any information about this behavior, so don't know if it's expected, but it wasn't to me originally.
First, I've installed uv with my conda installation on WSL. Then I ran
```sh
cd my-repo
uv venv
source .venv/bin/activate
uv pip install -r requirements.txt
``` 
But then I've realized that I have some packages installed in my environment that are not in requirements and not supposed to be installed, then I've deactivated venv to get back to base conda and saw with `conda list` that **everything** I've installed into venv was installed into my base environment!😭
I inspected the .venv folder and found that python binary and activation scripts were linking to the base python from conda.

Well, I guess it makes sense that uv didn't create a separate environment, if it doesn't depend on python, but if you have to create actual python venv by yourself, what's the purpose of `uv venv` command?

**Comment by charliermarsh** [comment]
What version on uv are you on?

I'm having a little trouble following the issue. Are you saying that `uv pip install -r requirements.txt` didn't install into `.venv`, it installed into your Conda environment?

**Comment by Ssslakter** [comment]
I have uv 0.1.26
Yes, I guess so, if I get it correctly `uv venv` somehow referenced my global environment and when I installed requirements inside `.venv` they ended up there as well, but I think I might have also messed up something. I'll try to reproduce it with other env and write here later

**Comment by charliermarsh** [comment]
Ok, we recently changed the logic to ensure that if you have a virtualenv _and_ a Conda environment enabled, we favor the virtual environment, so this _should_ be working as you originally expected.

**Comment by charliermarsh** [comment]
Ah yes, you can run `uv venv --seed` if you want to include the "seed packages" (i.e., `pip`). Otherwise, `uv` excludes `pip` by default, since you already have `uv` installed and `uv` can handle installation for you.

**Comment by Ssslakter** [comment]
Thank you! It is much more clear now

**Comment by charliermarsh** [comment]
Thanks for following up :)

**Comment by Ssslakter** [comment]
Hi @charliermarsh! 

I was able to reproduce multiple times a similar problem where uv can't find itself in a new environment. Is this expected?
```sh
python -m venv venv
source venv/bin/activate
pip install uv
uv venv
source activate .venv/bin/activate
uv --help
# outputs uv: command not found
```
