### ISSUE TITLE
Can this install the right version of python?

### ISSUE THREAD

**Issue by dillfrescott** [astral-sh/uv#2739]
Or do i have to go out and download the right version of python for the project I'm trying to run?

**Comment by dillfrescott** [comment]
```shell
× Could not find `python.exe` through `py --list-paths` or in 'PATH'. Is Python installed?
```

Thats a bummer, especially considering you can only install one version of python at a time on windows without using third party tools such as conda...

**Comment by dillfrescott** [comment]
It should be included in the venv!

**Comment by charliermarsh** [comment]
We don't currently bootstrap uninstalled Python versions but we plan to in the future. (This will be the first piece: https://github.com/astral-sh/uv/issues/2617)

**Comment by charliermarsh** [comment]
> Thats a bummer, especially considering you can only install one version of python at a time on windows without using third party tools such as conda...

I'm not sure if you consider these third-party, but you can install as many Python versions as you like from both python.org directly and the Windows Store via the Pythons that are distributed by the PSF.

**Comment by dillfrescott** [comment]
Oh, thank you!
