### ISSUE TITLE
Support for pip install --target argument

### ISSUE THREAD

**Issue by mpderbec** [astral-sh/uv#2751]
We have some specific tooling that uses the `-t` flag in `pip install` to direct where we want pip to put the packages. (We aren't using virtual environments.)

Here's the help from pip for that argument:

```
-t, --target <dir>          Install packages into <dir>. By default this will not replace existing files/folders in <dir>. Use --upgrade to replace existing packages in <dir> with new versions.
```

Not sure how popular the argument is in pip land, but at least for us I've not found a way to soldier on without it.

**Comment by charliermarsh** [comment]
Do you mind chiming in here? https://github.com/astral-sh/uv/issues/1517

Merging into that issue.
