### ISSUE TITLE
Support no-op --no-compile

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#2771]
It would be nice to simply ignore `--no-compile`, rather than throw an error, to make it easier to swap pip and uv.

**Comment by sam-goodwin** [comment]
I think I ran into this with `uv pip compile`. Just wanted a way to resolve a `requirements.txt` but it built `pyspark` which took 1-2 minutes. Expected the operation to be instant.

**Comment by zanieb** [comment]
@sam-goodwin this is totally separate — `--no-compile` means do not compile `.pyc` files. You're looking for `--only-binary`

**Comment by henryiii** [comment]
That's not what `--no-compile` means. It means skip making .pyc files from .py files, which uv already does, and is opt-in for pip.

**Comment by sam-goodwin** [comment]
Thanks @zanieb and @henryiii , sorry for the confusion.

**Comment by staaam** [comment]
@charliermarsh  I'd like to reopen this issue, since --no-compile flag is still not support. Getting this error:
```
$ uv pip install --no-compile test
error: unexpected argument '--no-compile' found

  tip: a similar argument exists: '--no_compile'
```
which kind of misses the point

**Comment by charliermarsh** [comment]
It's `--no-compile-bytecode`, but we can add an alias.

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/uv/pull/4453.
