### ISSUE TITLE
`uv pip list -e -q` outputs nothing.

### ISSUE THREAD

**Issue by charlesnicholson** [astral-sh/uv#2776]
This one is more entertaining than serious- we deploy Python artifacts as a set of wheels, a constraints file, and a bunch of shell/batch scripts that possibly create the venv and install the wheels etc before launching the corresponding entry point script in the venv.

These shell / batch scripts run from a non-deployed development repository as well, so they have to decide whether to `uv pip install` anything or just lean on the existing editable-installs of our first-party packages.

To do this, we run `uv pip list -e` and search the process's stdout: if there are no editable installations matching the requested package name, we install from the wheel file.

Amusingly, our scripts are also quiet by default, so we pass `-q` to everything.

So, we run `uv -q pip list -e`, which always prints nothing and quietly messes up our strategy because the output with the "quiet" flag is indistinguishable from the lack of output when `uv pip list` finds nothing.

Removing the `-q` flag of course fixes it trivially. I'm totally happy with this being "user error", but I thought it was an interesting / funny way to hold `uv` wrong.

![3caedb8a-1692-4c89-945e-791386768c3d_text](https://github.com/astral-sh/uv/assets/3010295/8fcb882f-50d4-4d0e-9541-b3c3b5eae552)

**Comment by zanieb** [comment]
We agree it probably shouldn't be _that_ quiet :)

**Comment by charlesnicholson** [comment]
If it's interesting, my opinion is that if a tool only exists to dump info to stdout/stderr, a quiet flag doesn't make sense and I'd probably not offer it as an option. I'd prefer to be forced to simply not call it, instead of having an option that can confound the meaning of "there was no output".

But it's easy to see the other side too: users are grown-ups, and the tool is giving them what they've explicitly asked for :)

**Comment by zanieb** [comment]
`--quiet` is just a global CLI flag that adjusts the verbosity of our logging, I'm not sure if it makes sense to turn off for a single command although I agree it doesn't really make sense in a "show me things" command.

**Comment by zanieb** [comment]
We should emit this to stdout instead of stderr

**Comment by charliermarsh** [comment]
It looks like `pip list --quiet` _also_ doesn't print :D

**Comment by charlesnicholson** [comment]
Any appetite for something like a `--json` flag that emits the repository installed package manifest to stdout in json format? That way it's easily machine-parseable (unlike the current output), and there's a difference between "no output whatsoever" (`-q`) and "no output because of requested filters or the venv is just empty"- the latter would emit `{\n}\n`.

That might be a nice way to disambiguate the cases and make `uv pip list` easier to tool against, all at the same time.

**Comment by zanieb** [comment]
If we emit to stdout instead of stderr it will not be silenced by `-q`.

There's appetite for machine readable / JSON output throughout the CLI though, yeah.

**Comment by BurntSushi** [comment]
I think probably the `-q/--quiet` flag should be respect here and `uv` shouldn't emit any output. I think this matches the behavior of other CLI tools like `grep`. Typically, the utility in a `-q/--quiet` flag though is that you want to run the command just to determine whether it was successful or not by querying its exit status. I'm not sure that's a meaningful thing to ask of `uv pip list`, though it conceivably could be I suppose.

**Comment by charliermarsh** [comment]
Yeah, that makes sense to me.

**Comment by zanieb** [comment]
Thanks!
