### ISSUE TITLE
[feature request] python bindings for uv api

### ISSUE THREAD

**Issue by gmankab** [astral-sh/uv#2794]
in python you can do this:

```python
import venv
venv.create()
```

can you please provide python bindings for uv api, so then you can do this:

```python
import uv.venv
uv.venv.create()
```

**Comment by zanieb** [comment]
Hi! Thanks for your request, but we won't be supporting this anytime soon. The more APIs we need to maintain the less we can focus on innovation. Right now, we're focusing on our CLI as the canonical way to interact with `uv`. For some use-cases, we are willing to make changes to our Rust API but that is very unstable.

If you're reading this issue feel free to 👍 the original post if you're interested in this.

We're likely to have a programmatic API someday, but not now.
