### ISSUE TITLE
Throw an error if a requirement exists with conflicting URLs

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#284]
E.g., if you depend on Flask at one URL, and one of your dependencies depends on Flask at a different URL, we need to throw an error.

**Comment by ayush-rathore-quartic** [comment]
Does anyone know a way to explicitly prefer one of the conflicting URLs or work around this error without updating the dependent packages? cc @charliermarsh

**Comment by charliermarsh** [comment]
@ayush-rathore-quartic -- You can use `--override overrides.txt`, and put something like:
```
flask @ git+https://github.com/pallets/flask@commit-sha
```
