### ISSUE TITLE
`uv pip install` not recognizing existing Pytorch installed by `conda` in Pytorch docker image

### ISSUE THREAD

**Issue by StellarStorm** [astral-sh/uv#2841]
Good afternoon!
I've just discovered `uv` and am finding it quite helpful - thanks for all the work on it!

I'm building a Docker image based on the [pytorch 2.2.2 Docker image](https://hub.docker.com/layers/pytorch/pytorch/2.2.2-cuda12.1-cudnn8-runtime/images/sha256-923f687790bec78081c357e71dcd5dcef80b0cc00f6c34484902a5e83362c854?context=explore) and I've found something I don't expect. When trying to install certain packages that depend upon pytorch, `uv` wants to re-install torch. This is despite the Docker image being built upstream with torch already present and installed from conda.

For example, this will add torch==2.2.2, despite it already being present on the system:

`CONDA_PREFIX=/opt/conda uv pip install monai[all]  `

I've also tried with the `--system` flag instead of setting `CONDA_PREFIX`, but get the same result.

Looking at the output from `uv pip list`, there's a difference in what is sees vs. the system-wide `pip`:

```bash
root@colima-amd64:/workspace# CONDA_PREFIX=/opt/conda uv pip list | grep torch
torchelastic              0.2.2
root@colima-amd64:/workspace# pip list | grep torch
torch                     2.2.2
torchaudio                2.2.2
torchelastic              0.2.2
torchvision               0.17.2
```
This is my uv/pip version information:
```bash
root@colima-amd64:/workspace# uv --version
uv 0.1.29
root@colima-amd64:/workspace# pip --version
pip 24.0 from /opt/conda/lib/python3.10/site-packages/pip (python 3.10)
```
The Docker image is based upon Ubuntu 22.04. Python is installed by the upstream Pytorch Docker devs with conda. I installed uv with pip.

```bash
root@colima-amd64:/workspace# conda --version
conda 23.9.0

root@colima-amd64:/workspace# which pip
/opt/conda/bin/pip
root@colima-amd64:/workspace# which conda
/opt/conda/bin/conda
root@colima-amd64:/workspace# which uv
/opt/conda/bin/uv
```

Thank you!

**Comment by charliermarsh** [comment]
That's interesting... Are you able to include a minimal Dockerfile that reproduces the issue? Happy to look into it.

**Comment by StellarStorm** [comment]
Sure - here's the minimal dockerfile (can't attach for some reason):
```text
FROM pytorch/pytorch:2.2.2-cuda12.1-cudnn8-runtime

RUN pip install uv \
    && CONDA_PREFIX=/opt/conda uv pip install monai --verbose
```

Saved to "Dockerfile" and built with `docker buildx build --platform linux/amd64 --rm --network=host --progress=plain -t uv_test .`

Thanks!

**Comment by samypr100** [comment]
See https://github.com/astral-sh/uv/issues/2928#issuecomment-2053727555 that explains this issue.

**Comment by StellarStorm** [comment]
Seems to work great now with IV 0.1.40, thanks! 🎉
