### ISSUE TITLE
uv pip install -r is not completely compatible with the original pip install -r - does not accept extra options

### ISSUE THREAD

**Issue by flyaroundme** [astral-sh/uv#2851]
I have a requirements.txt file which starts with extra options for `pip install`, like extra pypi index url and actually contains something like this:
```
--extra-index-url=https://<extra_pypi_index_url>
--trusted-host=github.com
-e .[development]
```

And the invocation of 
```
$ uv pip install -r requirements.txt
```

Leads to 

```
error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement at requirements.txt:2:1
```

While the old `pip install -r` works perfectly fine

**Comment by charliermarsh** [comment]
We don’t support trusted host. The rest of your requirements file will work fine.

**Comment by charliermarsh** [comment]
You can track trusted host here: https://github.com/astral-sh/uv/issues/1339. But removing the second line of your file should lead to a successful run.

**Comment by flyaroundme** [comment]
Thanks!
