### ISSUE TITLE
Annotate the index from which a package is pulled in `uv pip compile`

### ISSUE THREAD

**Issue by miccoli** [astral-sh/uv#2852]
Awaiting that #171 gets resolved, it would be very useful if `uv pip compile` could generate annotations with the “source” index.

Currently `uv pip compile --extra-index-url <MYINDEX> --no-header <(echo MYPACKAGE)` outputs something like
```
DEPENDENCY==1.18.5
    # via MYPACKAGE
MYPACKAGE==0.0.5
```
and I found no easy way (apart from analyzing the `--verbose` trace or cross-referencing the hashes from `--generate-hashes`) to understand which package comes from which index.

I would like explicit annotations, e.g.
```
DEPENDENCY==1.18.5
    # via MYPACKAGE
    # from https://pypi.org/simple
MYPACKAGE==0.0.5
    # from <MYINDEX>
```

**Comment by zanieb** [comment]
Technically, we could do this without #171. We know which index each package comes from at compile-time.

**Comment by charliermarsh** [comment]
Makes sense :)

**Comment by zanieb** [comment]
Ah cool makes sense. As long as there's not an expectation that we will guarantee the given index is used on install.
