### ISSUE TITLE
Detect conda environment managed by micromamba

### ISSUE THREAD

**Issue by meridionaljet** [astral-sh/uv#2862]
uv version: 0.1.29

Micromamba sets `MAMBA_ROOT_PREFIX` instead of `CONDA_PREFIX`: https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html#quickstarts

But `uv` only looks for `CONDA_PREFIX`, so errors like this get thrown when using it in environments such as the `mambaorg/micromamba` image:

```
error: Failed to locate a virtualenv or Conda environment (checked: `VIRTUAL_ENV`, `CONDA_PREFIX`, and `.venv`). Run `uv venv` to create a virtualenv.
```

Obviously this can be worked around by setting `CONDA_PREFIX` manually in such environments, so this is a minor issue, but figured it would be good to document.

**Comment by zanieb** [comment]
This makes sense although I'm not sure where we should draw the line on environment variables we check.

**Comment by meridionaljet** [comment]
> This makes sense although I'm not sure where we should draw the line on environment variables we check.

Definitely agree there should be a reasonable limit on this. Micromamba / mamba is a pretty popular implementation of conda, though, and if uv users are performance-oriented, they will often be using micromamba as well.

**Comment by charliermarsh** [comment]
Makes sense. What should we do if `MAMBA_ROOT_PREFIX` and `CONDA_PREFIX` are both set?

**Comment by meridionaljet** [comment]
> Makes sense. What should we do if `MAMBA_ROOT_PREFIX` and `CONDA_PREFIX` are both set?

Maybe just error if they are not equal? You could pick one to default to but I could see that leading to frustrating bugs for users. I'm struggling to think of a correct use-case where both vars are set and intentionally different.

**Comment by charliermarsh** [comment]
I just ran `micromamba activate` and it does seem to set `CONDA_PREFIX`?

```
❯ echo $CONDA_PREFIX
/Users/crmarsh/micromamba
```

**Comment by meridionaljet** [comment]
> I just ran `micromamba activate` and it does seem to set `CONDA_PREFIX`?
> 
> ```
> ❯ echo $CONDA_PREFIX
> /Users/crmarsh/micromamba
> ```

Funny enough I get the same behavior, which is inconsistent with the [docs](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html#quickstarts). However, in the `mambaorg/micromamba` docker image, it is indeed `MAMBA_ROOT_PREFIX` that is set, which is when I first ran into this issue. I can't immediately explain the inconsistency.

**Comment by charliermarsh** [comment]
Okay thanks, that's good to know.

**Comment by zanieb** [comment]
Should we open an upstream issue before adding support?

**Comment by meridionaljet** [comment]
Mamba itself may not actually have an issue. Mamba seems to define `MAMBA_ROOT_PREFIX` as the root prefix of the mamba/conda distribution (e.g., `/opt/conda`). `CONDA_PREFIX`, however, points to the directory of the currently active env, e.g. `/opt/conda/envs/test`. When the base env is activated, such as in the micromamba docker image, `MAMBA_ROOT_PREFIX` and `CONDA_PREFIX` would have the same value of `/opt/conda`. 

The potential issue, then, is that the current version of the [Micromamba Docker image](https://github.com/mamba-org/micromamba-docker) doesn't seem to set `CONDA_PREFIX` even though the base env is activated by default when the image is built.

If this is indeed unintended behavior and we should always expect `CONDA_PREFIX` to be defined when an env is active, then perhaps this is entirely an upstream issue.

I've opened an upstream issue to hopefully gain some clarity: https://github.com/mamba-org/micromamba-docker/issues/458

**Comment by charliermarsh** [comment]
Sounds good, thank you!

**Comment by meridionaljet** [comment]
Micromamba apparently has particular instructions that are necessary to activate a conda environment during the docker build process. When followed correctly, $CONDA_PREFIX is set as one would expect. There is thus nothing to be done here. I apologize for the wasted time.
