### ISSUE TITLE
Tracking: uv top-level commands and user experience

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#2917]
This is a tracking issue for the uv user experience outside of the `pip`-compatible interface.

This post will be updated with links to relevant work.

General discussion about designs is allowed here unless there is a relevant issue for the topic.

**Comment by naosense** [comment]
Upvote this. The current  command format `uv pip...` is very misleading， which makes people feel that to use uv you must install pip first.

**Comment by zanieb** [comment]
We haven't really been making use of this because I forgot I made it 🙃 

Here's a rough set of links:

- #3347 
- #3560 
- #2607 
- https://github.com/astral-sh/uv/issues/3959 
- https://github.com/astral-sh/uv/issues/3960
- https://github.com/astral-sh/uv/pull/3263
- https://github.com/astral-sh/uv/pull/3436

We're tracking most of this work with the `projects` and `preview` labels.
