### ISSUE TITLE
Specify global configurations similar to pip

### ISSUE THREAD

**Issue by jmspereira** [astral-sh/uv#2929]
Hey everyone,

Pip has a mechanism to specify configurations that override the configurations passed as parameters or environment variables (i.e., global configurations specified on pip-conf file). 

In my case, I have some build scripts that are parametrized with extra-index-urls (as a parameter), and I override them with the pip.conf file in a CI process, with uv I am not able to do this because the parameter has a higher priority than the environment variable.

Does someone know how to have the same functionally with uv? 
Best!

**Comment by konstin** [comment]
We're tracking support for pip.conf in https://github.com/astral-sh/uv/issues/1404, but we will also add a global configuration for uv itself.
