### ISSUE TITLE
uv pip compile removes --find-links, --extra-index-url etc from requirements.txt, by design?

### ISSUE THREAD

**Issue by artemisart** [astral-sh/uv#2937]
`pip compile` from pip-tools keeps the --find-links and (extra) index-urls from its inputs (both command-line and source files) and saves them to the output file, but `uv pip compile` removes them, is this by design ? Is there an option to enable it ? Thanks!

To reproduce:
```sh
uv --version  # uv 0.1.29
echo -e '-f https://download.pytorch.org/whl/torch_stable.html\ntorch==1.9.1+cu111' > requirements.in
uv pip compile requirements.in --output-file requirements-uv.txt
pip-compile requirements.in  # pip-tools 7.4.1 but this is not new
```
Gives requirements-uv.txt:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile requirements.in --output-file requirements-uv.txt
torch==1.9.1+cu111
typing-extensions==4.11.0
    # via torch
```
And requirements.txt from pip-tools:
```
#
# This file is autogenerated by pip-compile with Python 3.9
# by the following command:
#
#    pip-compile requirements.in
#
--find-links https://download.pytorch.org/whl/torch_stable.html

torch==1.9.1+cu111
    # via -r requirements.in
typing-extensions==4.11.0
    # via torch
```

Keeping the --find-links and --extra-index-url is really useful to keep the lockfile contained, otherwise we can't install with uv pip install -r requirements.txt as it's missing all these urls.

**Comment by zanieb** [comment]
Hi there are [several duplicate issues](https://github.com/astral-sh/uv/issues?q=is%3Aissue+emit-index-url+is%3Aclosed) about this.

You're looking for `--emit-index-url` and `--emit-find-links`.

**Comment by artemisart** [comment]
Oh yes sorry I think I only searched for --find-links and missed those, is it possible to configure the --emit* in a config file maybe? thanks @zanieb

**Comment by zanieb** [comment]
No problem it happens a lot :) I blame GitHub's search.

Not a this time. We're designing a persistent configuration file now though.
