### ISSUE TITLE
Behaviour when metadata is incorrect differs from pip

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#2953]
It looks like docutils made a new release today and something is a little weird with the release.

When installing with pip, I get the following warning:
```
Discarding https://files.pythonhosted.org/packages/67/9a/ff2ff8e922f3b97c4b4864ca6c78d76ca5969bd730560001167b7054ac48/docutils-0.21.post1.tar.gz (from https://pypi.org/simple/docutils/) (requires-python:>=3.9): Requested docutils>=0.13.1 from https://files.pythonhosted.org/packages/67/9a/ff2ff8e922f3b97c4b4864ca6c78d76ca5969bd730560001167b7054ac48/docutils-0.21.post1.tar.gz has inconsistent version: expected '0.21.post1', but metadata has '0.21'
```
and it falls back to installing from the wheel (that is missing the post release version).

uv seems pretty happy to build from the sdist that has the post release, even though the resulting metadata does not match the version.

It all seems harmless enough in this case, but feels like a sort of weird situation and maybe uv should match pip's behaviour here.

**Comment by charliermarsh** [comment]
Thanks! To confirm, it's just: `uv pip install docutils`?

**Comment by hauntsaninja** [comment]
Yup! And it's unclear to me what installers should do here / this is more of a curiosity than anything, so feel free to close :-)

**Comment by charliermarsh** [comment]
We already validate the package _name_, I think it makes sense to validate the version too!

**Comment by hauntsaninja** [comment]
Yeah, I guess the following feels a little undesirable:
```
λ uv pip install 'docutils==0.21.post1'
Resolved 1 package in 1ms
Downloaded 1 package in 2ms
Installed 1 package in 10ms
 - docutils==0.21
 + docutils==0.21
λ uv pip freeze | grep docutils
docutils==0.21
```
