### ISSUE TITLE
--generate-hashes should generate missing hashes for pinned packages

### ISSUE THREAD

**Issue by CharString** [astral-sh/uv#2962]
Since #2532 uv "preserves" hashes for pinned packages. This is correct, but if no hash is present for a pinned package, a hash should still be generated.

When "turning on --generate-hashes" for a project, I don't want to run with --update, but I do want to generate hashes for pinned versions. Because pip will expect all hashes to be present:

> ERROR: Hashes are required in --require-hashes mode, but they are missing from some requirements. Here is a list of those requirements along with the hashes their downloaded archives actually had. Add lines like these to your requirements files to prevent tampering. (If you did not enable --require-hashes manually, note that it turns on automatically when any package has a hash.)

Workaround: rollback to uv 0.1.22 when preservation of hashes wasn't implemented yet.

**Comment by charliermarsh** [comment]
I think that makes sense. Can change it...
