### ISSUE TITLE
uv not recognizing existing installed package

### ISSUE THREAD

**Issue by shiyangcao** [astral-sh/uv#2982]
Hi,

I apologize if this has been reported elsewhere but I didn't see it. UV with --find-links and no-index currently doesn't look at existing installed packages correctly.

For example:

1. Create an empty virtualenv, install urllib3

```
$ uv pip freeze


pip==23.3.1
setuptools==69.0.2
urllib3==2.2.1
wheel==0.42.0
```

Then download the latest requests wheel file and put it somewhere

Then try to install it:
```
$uv pip install requests --find-links . --no-index --offline

  × No solution found when resolving dependencies:
  ╰─▶ Because urllib3>=1.21.1, <3 was not found in the provided package locations and requests==2.31.0 depends on urllib3>=1.21.1,<3, we can conclude that requests==2.31.0 cannot be used.
      And because only requests==2.31.0 is available and you require requests, we can conclude that the requirements are unsatisfiable.
```

It complains that it cannot find urllib3 from the find-links, which is correct, but shouldn't it detect that urllib3 is already installed and does not need reinstalling?

Thanks

**Comment by charliermarsh** [comment]
Can you share your uv version? This works as expected for me.

**Comment by charliermarsh** [comment]
For example (with `urllib3` and `idna` installed, and `certifi`, `charset-normalizer`, and `requests` in `~/Downloads`):

```
❯ uv pip install requests --find-links ~/Downloads --no-index --offline
Resolved 5 packages in 3ms
Downloaded 3 packages in 8ms
Installed 3 packages in 2ms
 + certifi==2022.12.7
 + charset-normalizer==2.1.1
 + requests==2.31.0
```

**Comment by shiyangcao** [comment]
```
(uv_test) $ uv --version
uv 0.1.31
(uv_test) $ uv pip freeze
certifi==2024.2.2
charset-normalizer==3.3.2
idna==3.6
pip==23.3.1
setuptools==69.0.2
urllib3==2.2.1
uv==0.1.31
wheel==0.42.0
(uv_test) $ python3.11 -m uv pip install requests --find-links . --no-index --upgrade
  × No solution found when resolving dependencies:
  ╰─▶ Because urllib3>=1.21.1, <3 was not found in the provided package locations and requests==2.31.0 depends on urllib3>=1.21.1,<3, we can conclude that requests==2.31.0 cannot be used.
      And because only requests==2.31.0 is available and you require requests, we can conclude that the requirements are unsatisfiable.
```

my bad, my version was originally not the latest, but on the latest, the `--upgrade` flag triggers the same behavior.

thanks for responding so quickly!

**Comment by charliermarsh** [comment]
@zanieb - what's the intended behavior here?

**Comment by zanieb** [comment]
Ah perhaps you're looking for `--upgrade-package requests` instead of `--upgrade`? Otherwise I think we will not consider your local `urllib3` version since you've requested an upgrade of the full dependency tree.

**Comment by shiyangcao** [comment]
ok this works for me! thanks

**Comment by zanieb** [comment]
I wonder if we should limit exclusions to the directly requested dependencies during upgrades.
