### ISSUE TITLE
uv does not recognise PIP_BREAK_SYSTEM_PACKAGES env variable

### ISSUE THREAD

**Issue by m-reichle** [astral-sh/uv#2988]
Hi, 

I am trying to use uv as a drop-in replacement for pip in a test container setting to speed up my test runs. 
Since my containers are built new for every test run, I don't use a venv and allow pip to break system packages. I do that by setting PIP_BREAK_SYSTEM_PACKAGES=1 in my environment, rather than using the break system packages argument on every pip call.

It seems uv doesn't recognise that environment variable though. Would it be possible to add it?

**Comment by charliermarsh** [comment]
As a "rule", we don't read pip-specific configuration, but we do read `UV_<ENV_VAR>` for some values: https://github.com/astral-sh/uv?tab=readme-ov-file#environment-variables.

I don't mind adding `UV_BREAK_SYSTEM_PACKAGES` there.

**Comment by m-reichle** [comment]
Aw, awesome! Thank you very much for the quick response!
