### ISSUE TITLE
Mismatch between documentation and code comment on PyPI Index priority

### ISSUE THREAD

**Issue by tdejager** [astral-sh/uv#2990]
The code in `crates/distribution-types/src/index_url.rs:167` says: 

```
/// The index locations to use for fetching packages.
///
/// By default, uses the PyPI index.
///
/// "pip treats all package sources equally" (<https://github.com/pypa/pip/issues/8606#issuecomment-788754817>),
/// and so do we, i.e., you can't rely that on any particular order of querying indices.
///
/// If the fields are none and empty, ignore the package index, instead rely on local archives and
/// caches.
///
/// From a pip perspective, this type merges `--index-url`, `--extra-index-url`, and `--find-links`.
```

Hower the `PIP_COMPATIBILITY.md` mentions:

> In both uv and pip, users can specify multiple package indexes from which to search for the available versions of a given package. However, uv and pip differ in how they handle packages that exist on multiple indexes.
>For example, imagine that a company publishes an internal version of requests on a private index (--extra-index-url), but also allows installing packages from PyPI by default. In this case, the private requests would conflict with the public [requests](https://pypi.org/project/requests/) on PyPI.
>When uv searches for a package across multiple indexes, it will iterate over the indexes in order (preferring the --extra-index-url over the default index), and stop searching as soon as it finds a match. This means that if a package exists on multiple indexes, uv will limit its candidate versions to those present in the first index that contains the package.
> etc.

I feel like this contradicts each other. I think the code comment is out of date or am I missing something else 😄 ?

**Comment by charliermarsh** [comment]
The comment is out-of-date, I'll update it.

**Comment by charliermarsh** [comment]
(The compatibility guide is correct.)

**Comment by tdejager** [comment]
Great thank you! :)
