### ISSUE TITLE
UV_SYSTEM_PYTHON cannot be switched off

### ISSUE THREAD

**Issue by hynek** [astral-sh/uv#3000]
I'm using uv as part of a GitHub Action and have noticed that when the caller sets `UV_SYSTEM_PYTHON=true`, it cannot be undone by locally setting `UV_SYSTEM_PYTHON=false` although the error indicates that false is a valid value. I always get the "system is incompatible with python":

```console
$ env UV_SYSTEM_PYTHON=false uv pip install --python .venv/bin/python ruff
error: the argument '--python <PYTHON>' cannot be used with '--system'
$ uv --version
uv 0.1.31 (7bcca28b1 2024-04-09
```

I have now solved it by unsetting the variable, but I think this should work?

**Comment by charliermarsh** [comment]
Will need to look into it... This is something that Clap does automatically (https://github.com/clap-rs/clap), we just specify the mapping between argument and environment variable.

**Comment by hynek** [comment]
Yeah I've noticed when looking at #2354. Since this problem will likely manifest itself elsewhere too, I hope this doesn't mean you have a clap rewrite on your plate, too. 😬

**Comment by charliermarsh** [comment]
Hahah don't worry I have enough on my plate to be comfortable passing on that one :)

**Comment by charliermarsh** [comment]
I suspect the problem here is actually that Clap thinks both `--system` and `--python` are being passed (even though `--system` is falsey).

**Comment by charliermarsh** [comment]
If you omit `--python`, do you see the right behavior? `uv` would default to `.venv` anyway, as long as `--system` is false. (We should fix the interaction here, I'm just confirming the diagnosis...)

**Comment by hynek** [comment]
It does, but it has bad interactions with venv too (which is what sent me down this path):

```
nox > Running session tests-3.8(opt_deps=[])
nox > Creating virtual environment (uv) using python3.8 in .nox/tests-3-8-opt_deps
nox > Command uv venv -p python3.8 /home/runner/work/stamina/stamina/.nox/tests-3-8-opt_deps failed with exit code 2:
error: the argument '--python <PYTHON>' cannot be used with '--system'
```

**Comment by charliermarsh** [comment]
Okay, I believe I know how to fix this.
