### ISSUE TITLE
`uv-git` should be async

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#302]
It's hard because the `git2` structs aren't `Send`....

**Comment by zanieb** [comment]
@ibraheemdev should we still do this?

**Comment by zanieb** [comment]
(Presuming this is not relevant anymore)

**Comment by ibraheemdev** [comment]
Our git code is now all process based. Use tokio processes internally isn't clearly better than a single outer `spawn_blocking` call, so I think it's fine how it is.
