### ISSUE TITLE
Can the `--help` output be wrapped differently?

### ISSUE THREAD

**Issue by bluetech** [astral-sh/uv#3057]
The `uv pip install --help` output looks like this for me:

![image](https://github.com/astral-sh/uv/assets/1223550/60d7511e-9f64-41c3-a8d7-3fd19c4fd8b1)

This is pretty minor, but the long lines which wrap (the "When enabled ..." lines in this image) are not indented, which makes it hard (for me at least) to quickly scan the options. I think for this reason usually the wrapping is indented.

For contract, here is part of `ruff check --help`:

![image](https://github.com/astral-sh/uv/assets/1223550/679eec76-cc39-4937-a492-4a175ad86f42)

and `pip install --help`:

![image](https://github.com/astral-sh/uv/assets/1223550/3a889b4a-2278-4f88-91f0-80b5ef44ca54)

---

Version: uv 0.1.32
Platform: Linux

**Comment by AlexWaygood** [comment]
We probably just need to do the same thing we did over at Ruff in https://github.com/astral-sh/ruff/pull/9633
