### ISSUE TITLE
Show included files in the annotation

### ISSUE THREAD

**Issue by FredStober** [astral-sh/uv#3066]
# Input Files:

`constraints.txt`
> boto3==1.34.80

`requirements.a.in`
> boto3

`requirements.b.in`
> pytz

`requirements.in`
> -r requirements.a.in
> -r requirements.b.in
> -c requirements.c.in

# Ticket Information
* The command you invoked (e.g., `uv pip sync requirements.txt`), ideally including the `--verbose` flag.

`uv pip compile requirements.in` yields
```
boto3==1.34.80
botocore==1.34.84
    # via
    #   boto3
    #   s3transfer
....
```

Meanwhile, `pip-compile requirements.in` yields
```
boto3==1.34.80
    # via
    #   -c constraints.txt
    #   -r requirements.a.in
botocore==1.34.84
    # via
    #   boto3
    #   s3transfer
....
```

* The current uv platform. linux
* The current uv version (`uv --version`) uv 0.1.32

Having the additional source information in the annotation would be useful to understand where a requirement comes from exactly.

**Comment by charliermarsh** [comment]
I believe this is the same as #1343. Thanks!

**Comment by charliermarsh** [comment]
Supported in the next version via https://github.com/astral-sh/uv/pull/3269.
