### ISSUE TITLE
`KeyringProvider::fetch_subprocess` should be async

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#3073]
As far as I can tell, we're egregiously blocking the event loop for 80ms on keyring fetches. The function should be async and use an async subprocess API.

**Comment by zanieb** [comment]
See https://docs.rs/tokio/latest/tokio/process/struct.Command.html

https://github.com/astral-sh/uv/blob/c0efeeddf6d738991d8f3149168ce57c52073f4e/crates/uv-auth/src/keyring.rs#L100

**Comment by naosense** [comment]
> See https://docs.rs/tokio/latest/tokio/process/struct.Command.html
> 
> https://github.com/astral-sh/uv/blob/c0efeeddf6d738991d8f3149168ce57c52073f4e/crates/uv-auth/src/keyring.rs#L100

hey@zanieb i want to try this, could you assign it to me?

**Comment by charliermarsh** [comment]
Done @naosense thanks!

**Comment by zanieb** [comment]
Sweet let me know if you have any questions. The `KeyringProvider::fetch` API will need to become async too.
