### ISSUE TITLE
Add `--prefix` flag for `uv pip install`

### ISSUE THREAD

**Issue by jorng** [astral-sh/uv#3076]
When performing multi-stage Docker builds, the `--prefix` flag is very useful to create an isolated install of dependencies that can then be copied to the final stage of a build.

Example with `pip`:
```Dockerfile
FROM python AS builder
# Possibly install prerequisites, gcc, etc, that aren't needed in runtime
COPY requirements.txt ./
RUN pip install -r requirements.txt --prefix /install
# Do other installs / builds...

FROM python:slim
COPY --from=builder /install /usr/local
# Other stuff as needed
```

Related:
- #1517 
- #2077 

Notably, this may need to be used in association with `--system` or `--python` to specify which python executables are pointed to.

**Comment by ericmarkmartin** [comment]
We have a use for this at Jane Street. I have a first draft patch that seems to work.

Still need to write tests and think about windows though

**Comment by zanieb** [comment]
Is `--target` insufficient?

**Comment by charliermarsh** [comment]
What’s the use-case?

**Comment by ericmarkmartin** [comment]
> Is `--target` insufficient?

Target is insufficient: target dumps everything into the specified dir. Prefix implies a [certain `Scheme`](https://docs.python.org/3/library/sysconfig.html). This is useful for assembling python environments.

**Comment by charliermarsh** [comment]
What is the workflow though that demands `--prefix` as opposed to installing into an arbitrary Python environment via `--python`? `--prefix` has its own problems -- IIUC, scripts etc. will reference the parent Python interpreter, not the `--prefix` Python interpreter.

**Comment by charliermarsh** [comment]
(By the way, I don't think `--prefix` is too hard to support, and I'm not really against it -- I just want to make sure that it's justified.)

**Comment by charliermarsh** [comment]
Do you want advice on your draft? My hope is that you can just change `Interpreter::layout` to return paths joined against `self.virtualenv` rather than `self.scheme`.

**Comment by charliermarsh** [comment]
I put up a PR here with basic support: https://github.com/astral-sh/uv/pull/4085.

**Comment by charliermarsh** [comment]
Was hoping to save you some trouble, sorry if I stepped on your toes.

**Comment by ericmarkmartin** [comment]
Haha no worries--thanks for the help!

**Comment by fdfz** [comment]
> (By the way, I don't think `--prefix` is too hard to support, and I'm not really against it -- I just want to make sure that it's justified.)

`pip install --root` is a better fit for container builds than `--prefix`. @charliermarsh I've opened a PR for it here: https://github.com/astral-sh/uv/pull/18774

It’s generally **easier and more common** for multi-stage container builds since you can mirror the final layout in a temp dir and just `COPY --from=builder /tmp/root /`. Unlike `--prefix`, you don't need to worry about the specific site-packages path—you just merge the root.
