### ISSUE TITLE
Fails to install torchvision (ROCm)

### ISSUE THREAD

**Issue by kaanyalova** [astral-sh/uv#3098]
uv 0.1.33
Fedora 40 

To reproduce run:
```
uv pip install --pre torchvision  --index-url https://download.pytorch.org/whl/nightly/rocm6.0 
```
Works on pip

Output:
[uv_out.txt](https://github.com/astral-sh/uv/files/15014764/uv_out.txt)

**Comment by zanieb** [comment]
Have you tried with `--extra-index-url` instead?

**Comment by kaanyalova** [comment]
Still getting the same error

**Comment by charliermarsh** [comment]
You probably need to add some local version specifiers in your input requirements. I'd suggest reading through https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers.
