### ISSUE TITLE
[Crash] transitive URL installs from localhost are erroneously interpreted as local paths

### ISSUE THREAD

**Issue by patrick-kidger** [astral-sh/uv#3128]
Using `uv` version `0.1.33`.

First of all let me jump to the root cause. This line:
https://github.com/astral-sh/uv/blob/25deddd3bf04c28a07180e8d73a5da1320425747/crates/uv-installer/src/site_packages.rs#L401
treats URL dependencies on `localhost` as a local path. (See the [special case for it described here](https://docs.rs/url/latest/url/struct.Url.html#method.to_file_path).) Under some circumstances this causes a crash, as the local path provided does not actually exist.

---

On to the more specific details.

I have a library `foo` with a dependency of the form `bar @ http://localhost:8000/bar-0.0.1-py3-none-any.whl`. The first time I run `uv pip install "foo @ http://localhost:8000/foo-0.0.1-py3-none-any.whl"`, then things work as normal. The second time I run this command (which should be idempotent), then when it tries to validate the library:

https://github.com/astral-sh/uv/blob/25deddd3bf04c28a07180e8d73a5da1320425747/crates/uv/src/commands/pip_install.rs#L164

it will crash with
```
error: failed to query metadata of file `/bar-0.0.1-py3-none-any.whl`
  Caused by: No such file or directory (os error 2)
```

I've not tracked through the details too closely, but it looks like specifically the transitive dependency is needed to trigger this.

For context, I am trying to use the URL dependency on `localhost` as an escape hatch to work around #3121. (Spinning up a quick local server that packages up a git repository appropriately, and then spits back a wheel file.)

Let me know if you need any more details!

**Comment by charliermarsh** [comment]
Thanks, that does seem unintended.

**Comment by charliermarsh** [comment]
Assigning to myself.

**Comment by patrick-kidger** [comment]
Wonderful stuff! I've checked and version `0.1.34` works on my full use-case as well.
Thank you for such a quick fix.

**Comment by charliermarsh** [comment]
Awesome, thank you for following up.
