### ISSUE TITLE
Support URL and path dependencies without a package name

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#313]
Apparently this works with pip?

```
git+https://github.com/pallets/flask.git@refs/pull/5313/head
```

As opposed to:
```
flask @ git+https://github.com/pallets/flask.git@refs/pull/5313/head
```

We could decide not to support these. I don't know if they're spec-compliant.

**Comment by sfc-gh-jcarroll** [comment]
It seems like this is also an issue for installing a local whl file?

```sh
% uv pip install ./streamlit-1.31.1-py2.py3-none-any.whl 
error: Failed to parse `./streamlit-1.31.1-py2.py3-none-any.whl`
  Caused by: Expected package name starting with an alphanumeric character, found '.'
./streamlit-1.31.1-py2.py3-none-any.whl
^

% uv pip install "streamlit @ ./streamlit-1.31.1-py2.py3-none-any.whl"
Resolved 40 packages in 680ms
Downloaded 40 packages in 1.74s
Installed 40 packages in 97ms
...
```

BTW `uv` seems awesome!! Thank you!!!

**Comment by charliermarsh** [comment]
Yup, all the same issue! Although we can probably support local wheels "trivially" since the file name is required to be encoded in the wheel.

**Comment by edgarrmondragon** [comment]
This is probably the biggest blocker to experimenting with uv [in Meltano](https://github.com/meltano/meltano/blob/c47653b75be5be03441285f64a8d23d7fddd7a41/src/meltano/core/venv_service.py) since dependencies of the type `git+https://...` are very widely used by plugins.

**Comment by charliermarsh** [comment]
👍 I want to support this, requires a bunch of internal refactors but definitely doable.

**Comment by yyolk** [comment]
Hopefully not to add to the confusion - I've been running scenarios against integrating with [`pdm`](https://github.com/pdm-project/pdm).

While investigating my own feature request, pdm-project/pdm#2641 I discovered `pdm` is handling `requirements.txt`-style exports in a way that falls back to pip's behavior...and works with `uv` if I remove the `#egg=` fragments. 

Here's some quirks I was able to discover. Being able to do `uv v --seed` for running through was very helpful, I use the `.venv/bin/pip` for wherever `pip install` is used. I believe these quirks would be universal, anywhere there's a python package with a `pyproject.toml`. 

I'm using the [pdm-example-monorepo](https://github.com/pdm-project/pdm-example-monorepo) below in the latest Python Docker image under a freshly made user in their home directory.


**When in a git directory:**

`pip` will end up resolving an editable install (`pip install -e 'file://'$PWD'relative/path'`) of a local path that's inside a git directory differently than one that is not. 

When inside a git directory, pip will include an `#egg=` fragment along with another query param for its relative directory.

e.g.;
```bash
# replace .venv
$ uv v --seed
# install the package as editable with relative path
$ .venv/bin/pip install -e 'file://'$PWD'packages/pkg-second'

# ...

# show pip installation
$ .venv/bin/pip freeze | grep pkg-core

-e git+https://github.com/pdm-project/pdm-example-monorepo@b85261555ea063e68eaf744e225804149c27e64f#egg=pkg_core&subdirectory=packages/pkg-core
```

**When it's not a git directory, and it's still an editable install:**

```bash
# replace .venv
$ uv v --seed
# get rid of .git, so it's not detected as a git repository
$ mv .git .gitold
# install the package as editable with relative installation, again
$ .venv/bin/pip install -e 'file://'$PWD'/packages/pkg-core'

# ...

# show pip installation
$ .venv/bin/pip freeze | grep pkg-core

# Editable install with no version control (pkg-core==0.1.0+editable)
-e /home/python/pdm-example-monorepo/packages/pkg-core
```

There's also this way that will lend itself to the next example - `pkg-name @ file:///...`, which cannot be installed as editable, regardless of git directory or not:

```bash
# replace .venv
$ uv v --seed
# install relative package, non-editable, pkg @ file://... way
$ .venv/bin/pip install 'pkg-core @ file://'$PWD'/packages/pkg-core'

# ...

# freezes the same way whether in a git repository or not
$ venv/bin/pip freeze | grep pkg-core

pkg-core @ file:///home/python/pdm-example-monorepo/packages/pkg-core
```

And lastly - `pip install 'file://...` will result in the same `package-name @ file://...` expansion regardless if it's in a git directory or not 😅 

```bash
# replace .venv
$ uv v --seed
# install non-editable, just 'file://...' 
$ .venv/bin/pip install 'file://'$PWD'/packages/pkg-core'

# ...

# freezes the same way whether in git repository or not
$ .venv/bin/pip freeze | grep pkg-core
pkg-core @ file:///home/python/pdm-example-monorepo/packages/pkg-core
```

**Comment by kkpattern** [comment]
We have a similar use case; we want to install a package in a local directory without `editable.`

We have several Python packages in a mono repo. Sometimes we need to create a python `venv`, install those packages into the `venv`, then pack the `venv` and distribute it to CI or production environment.

So we want to be able to install a local package like this:

```bash
uv pip install ./path/to/package/dir
```

We don't want to use `-e` here because the venv will be redistributed.

**Comment by charliermarsh** [comment]
@kkpattern - that _is_ supported, but you need to include the package name, like “ uv pip install ‘foo @ ./path/to/package/dir’”. We’ll lift this restriction in term, I’m mostly focused on correctness issues right now.

**Comment by kkpattern** [comment]
@charliermarsh  Yes. We figured that out. We have already switched to uv on our main branch. Massive speed up. Thanks for this awesome tool. (And ruff too!)

**Comment by shekharidentv** [comment]
I could able to install the package as mentioned above ways. but 
```uv pip sync requirements.txt``` is failing.  I am running `uv pip freeze > requirements.txt ` to generate the txt file.
```error: Couldn't parse requirement in `requirements.txt` at position 384
  Caused by: Trailing `(from https://<url>/<package>-0.7.1-py3-none-any.whl)` is not allowed
```

**Comment by charliermarsh** [comment]
@shekharidentv - do you mind opening a new issue for this? We may want to strip those URLs from freeze.

**Comment by jkgenser** [comment]
👍  for this feature. I'm liking UV so much that I'm using `pip install path/to/my.whl` (which is slow) and then `uv pip install` after.

**Comment by zanieb** [comment]
@jkgenser note you _can_ just provide a package name e.g. `pip install foo@path/to/my.whl` in the meantime.

**Comment by jkgenser** [comment]
> @jkgenser note you _can_ just provide a package name e.g. `uv pip install "foo@path/to/my.whl"` in the meantime.

Wow amazing thank you that worked! I was having trouble because I saw other examples in github issues that referred to `package @ path/to/my.whl` and it wasn't working me. However removing the spaces was what was needed.

**Comment by aliencaocao** [comment]
How to install optional deps?
```uv pip install xxx@./xxx[yy]``` dont work and says Distribution not found

**Comment by akx** [comment]
> How to install optional deps? 
> `uv pip install xxx@./xxx[yy]` dont work 

I'd guess `uv pip install package[extra]@location`.

**Comment by jeremander** [comment]
Loving `uv` so far!

Will supporting this also allow the very basic `uv pip install .` (non-editable) to work?

**Comment by charliermarsh** [comment]
Publicly committing to this one.

**Comment by dadokkio** [comment]
I've a similar issue with a requirements.txt file that contains a package installed as:

`-e git+https://github.com/xxx/package.git@commit_id#egg=package package`

at the moment `uv pip install` fails because -e seems to work only for local files 
```error: Unsupported URL (expected a `file://` scheme) in requirements.txt ```

Will this syntax be supported? There is an alternative way to install a specific package in requirements in current folder from a github repo?

Thanks

**Comment by charliermarsh** [comment]
You can do `package @ git+https://github.com/xxx/package.git@commit_id`, right?

**Comment by dadokkio** [comment]
Yes, but in that case it'll be installed under python path and not under current folder.. also with standard pip the behavior is different

**Comment by charliermarsh** [comment]
We don't support editable installs for Git and URL dependencies. I'd suggest just cloning the repo and installing it as a file-based editable install (`-e ./package`).

**Comment by charliermarsh** [comment]
Okay, this is now in review.

**Comment by charliermarsh** [comment]
These have all merged. Will be supported in the next release.

**Comment by franciscoafonsoo** [comment]
Thank you so much for making this, makes a world of a difference !
