### ISSUE TITLE
Windows defender/antivirus software flags version 0.1.35

### ISSUE THREAD

**Issue by ofek** [astral-sh/uv#3157]
Windows defender immediately flags it as malware and quarantines/deletes https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

![image](https://github.com/astral-sh/uv/assets/9677399/efba17ca-2fe7-4fb3-a69a-09249881b3ab)

![image](https://github.com/astral-sh/uv/assets/9677399/9ef11ee8-8ecc-4d9a-8a50-32f771e39f82)

Also Chrome download fails immediately:

![image](https://github.com/astral-sh/uv/assets/9677399/b3e90174-ff37-414e-86ea-b705b4311008)

**Comment by charliermarsh** [comment]
There tends not to be much that we can do about this. It happens sporadically.

**Comment by ofek** [comment]
Can the binary be signed or must it be inside of the package like an MSI to be signed?

**Comment by ZeyadMoustafaKamal** [comment]
I am unsure, but cloning the repo and compiling it locally might solve the problem. Windows seems to hate anything downloaded over the internet.

**Comment by ofek** [comment]
It seems enough people have reported it as a false positive and it no longer is flagged. I suppose there is a very short window after every release in which this would happen.

It would be worth it to somehow postpone the PyPI release for a few hours after the GitHub release to greatly reduce the number of affected users.
