### ISSUE TITLE
Windows scripts always uses `venvwlauncher.exe`

### ISSUE THREAD

**Issue by jbott** [astral-sh/uv#3158]
I was doing some windows spelunking and noticed that uv is unconditionally using `venvwlauncher.exe` for both the `python.exe` and `pythonw.exe` case. This seems to be a typo compared to the upstream cpython venv module, which uses the binary that matches the presence or absence of `w`.

I haven't actually run into an issue using this, so I can't actually confirm it's a bug.

https://github.com/astral-sh/uv/blob/b4ee7d73594183e677f8324f3e890ce53a3ba76d/crates/uv-virtualenv/src/bare.rs#L182-L186
https://github.com/python/cpython/blob/d457345bbc6414db0443819290b04a9a4333313d/Lib/venv/__init__.py#L274-L277

**Comment by charliermarsh** [comment]
That definitely looks wrong, but trying to understand why it hasn't caused any problems...

**Comment by charliermarsh** [comment]
Ah, it only affects Python 3.13.

**Comment by charliermarsh** [comment]
PR welcome or I can fix!

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/uv/pull/3160, thanks.
