### ISSUE TITLE
Add support for `--upgrade-strategy` or specify behavior

### ISSUE THREAD

**Issue by luiscastro193** [astral-sh/uv#3159]
By default, `pip --upgrade` only upgrades packages specified on pip’s command line. Ideally, at least dependencies would also be considered. This can be fixed with `--upgrade-strategy eager`.

What is the default behavior of `uv`? If dependencies are not considered, could `--upgrade-strategy eager` be added as an option?

**Comment by charliermarsh** [comment]
By default, we don't try to upgrade installed packages. But if you run with `--upgrade`, we attempt to upgrade all packages. You can also pass `--upgrade-package flask` to only upgrade a single package.

**Comment by charliermarsh** [comment]
(Hopefully that helps but happy to answer any follow-ups.)

**Comment by luiscastro193** [comment]
What do you mean by "we attempt to upgrade all packages"?

If you run `pip install --upgrade flask` it will only upgrade flask. However, if you run `pip install --upgrade --upgrade-strategy eager flask` it will upgrade flask and its requirements.

So what does `uv pip install --upgrade flask` do? Does it upgrade dependencies as well then?

**Comment by luiscastro193** [comment]
I did a quick test and `uv pip install --upgrade` upgrades indeed dependencies as well. That's great. Maybe it should be noted though in [PIP_COMPATIBILITY.md](../blob/main/PIP_COMPATIBILITY.md)?
