### ISSUE TITLE
Intermittent errors when installing from git reference

### ISSUE THREAD

**Issue by edgarrmondragon** [astral-sh/uv#3176]
* Platform: M2 macOS Sonoma
* uv 0.1.35

[Our project runs](https://github.com/meltano/meltano/blob/068289ea8fb7bdf558b58fd541c71c40c0648367/src/meltano/core/venv_service.py#L664-L673), for example `uv pip install git+https://github.com/jwills/target-duckdb.git@main duckdb==0.9.2
` under the hood and I've confirmed that running this command directly fails occasionally:

```
$ uv pip install git+https://github.com/jwills/target-duckdb.git@main duckdb==0.9.2
Updating https://github.com/jwills/target-duckdb.git (main)
error: Git operation failed
  Caused by: failed to fetch into: /Users/edgarramirez/Library/Caches/uv/git-v0/db/84855f4c2e0a8c94
  Caused by: failed to fetch branch or tag `main`
  Caused by: process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/jwills/target-duckdb.git' '+refs/tags/main:refs/remotes/origin/tags/main'` (exit status: 128)
--- stderr
```

**Comment by ChannyClaus** [comment]
looks like the subprocess failing while running `git` is failing rather than `uv`? (i.e. is there a reason to suspect this is a `uv` issue?)

**Comment by zanieb** [comment]
Does that `git fetch` invocation work outside of `uv`?

Was there any output in that stderr log?

**Comment by edgarrmondragon** [comment]
I think @ChannyClaus is right and this seems to be a problem in the git client. Still not sure what's going on but I'm seeing similar intermittent errors with pre-commit:

```
stderr:
    fatal: unable to access 'https://github.com/pycqa/flake8/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
Check the log at /Users/edgarramirez/.cache/pre-commit/pre-commit.log
```
