### ISSUE TITLE
Remove the pip command

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#3185]
Suggestion to remove the "pip" command from uv and just move all its subcommands to top level (install, freeze, list, sync, compile...). Instead of `uv pip install foo` we would be writing `uv install foo`.

### Pros

- Makes it easier to select executable uv/pip when writing scripts that could support both options in a transition period
- Pip is the name of another project and the interface is not identical
- Commands become shorter and direct to the point.
- In a couple years no one will even remember what pip is.
- It is still early in the uv life so that such a big change is still possible.

### Cons:

- Familiarity with the pip name, maybe
- uv plans to have several other tools (like `uv run`), so a command like `uv check` could not be obvious that it is related to installed packages.

**Comment by zanieb** [comment]
Hi! Please see #1899.

`uv install` will not be the same interface of `uv pip install` — we don't want to support all of the complexity of pip in our new workflow.

**Comment by inoa-jboliveira** [comment]
That is good news. Thank you

**Comment by zanieb** [comment]
You're welcome! Thanks for sharing your feedback.
