### ISSUE TITLE
Install.sh Missing from Repo?

### ISSUE THREAD

**Issue by blakete** [astral-sh/uv#3196]
```console
$ curl -LsSf https://astral.sh/uv/install.sh
curl: (22) The requested URL returned error: 404
```
Therefore, the [Getting Started instructions here](https://github.com/astral-sh/uv#getting-started) do not work. 
```console
# On macOS and Linux.
curl -LsSf https://astral.sh/uv/install.sh | sh
```
And this, in my Dockerfile, also now no longer works because of this issue:
```Dockerfile
# Install UV
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh
```
Please fix this!!!

**Comment by zanieb** [comment]
Investigating...

**Comment by zanieb** [comment]
We've rolled the latest release back to 0.1.35. We're troubleshooting permissions errors in the publish for 0.1.36. Thanks for the report!

**Comment by rodolfolottin** [comment]
Thank you @zanieb !

**Comment by blakete** [comment]
Thanks @zanieb and @rodolfolottin

**Comment by zanieb** [comment]
We'll track the long term fix for this in #3198.

We'll either fix 0.1.36 or publish 0.1.37 today.

**Comment by zanieb** [comment]
Note that there's nothing wrong with the 0.1.36 release it just didn't make it to PyPI and the installer script is missing.

**Comment by blakete** [comment]
@zanieb understood. Thanks for your quick response and resolution of the issue!

**Comment by zanieb** [comment]
That release is fixed now too.
