### ISSUE TITLE
uv doesn't reinstall editable package when non-editable package is requested

### ISSUE THREAD

**Issue by danielhollas** [astral-sh/uv#3200]
Consider the following sequence 

```console
$ git clone https://github.com/aiidateam/aiida-core && cd aiida-core
$ uv venv --seed
$ uv pip install --no-deps -e .
   Built file:///home/hollas/atmospec/aiida-core                                                                                                                                                                   Built 1 editable in 170ms
Resolved 1 package in 0.71ms
Installed 1 package in 1ms
 + aiida-core==2.5.1.post0 (from file:///home/hollas/atmospec/aiida-core)
```

Running editable install for the second time re-installs the package, which is nice:

```console
$ uv pip install --no-deps -e .
Built 1 editable in 183ms
Resolved 1 package in 0.93ms
Installed 1 package in 4ms
 - aiida-core==2.5.1.post0 (from file:///home/hollas/atmospec/aiida-core)
 + aiida-core==2.5.1.post0 (from file:///home/hollas/atmospec/aiida-core)
```

However, trying to install the package in non-editable mode does not re-install it

```console
$ uv pip install --no-deps .
Resolved 1 package in 1ms
Audited 1 package in 0.04ms
```

uv version 0.1.36

**Comment by charliermarsh** [comment]
Hmm interesting. Makes sense to force a reinstall here I suppose.

**Comment by danielhollas** [comment]
My understanding was that while the editable mode generally tries to emulate the actual installation, it is not guaranteed to be perfect so I think reinstalling is the only correct option here. Citing from [PEP 660](https://peps.python.org/pep-0660/#terminology-and-goals) 

> Depending on the way build backends implement this specification, some minor differences may be visible such as the presence of additional files that are in the source tree and would not be part of a regular install. Build backends are encouraged to document such potential differences.

**Comment by charliermarsh** [comment]
I'll label it as a bug.

**Comment by robinshen36** [comment]
@algora-pbc attempt

This is exactly the kind of thing I enjoy working on.

Been diving into Python lately and this seems like a perfect fit.

Thinking of kicking things off by checking the venv handling - does that sound reasonable?

Around $210-$370 seems fair to me, but open to whatever works.

Thanks for considering!
