### ISSUE TITLE
Disable lock to allow parallel installs?

### ISSUE THREAD

**Issue by fersarr** [astral-sh/uv#3215]
This is more of a question: 

We have a script that creates a copy of your venv (like a twin) and the special thing about this use case is that instead of installing `package_a, package_b, etc.` , we install `package_a==version_x, package_b==version_y, etc`. And because we have the full list, we can install them using `pip install --no-deps ...`. So, in this particular use case, we improved the speed of the creation of the twin by running pip in parallel, so that we install a group of packages in each parallel run. I tried to do this parallelization with `uv` but it looks like there's a lock, so there are no speed ups compared to unparalellized `uv`. Or is `uv` already smart enough out-of-the-box to do the parallelization itself given that we are using `--no-deps`?

**Comment by charliermarsh** [comment]
Yeah, uv already installs in parallel so there'd be no speed-up to (e.g.) splitting the packages in half and then running uv in a separate process for each subset. (This differs from pip, which does not perform a parallel install.) So, yes, uv should already be doing all the parallelization, and you shouldn't need to this package grouping.

**Comment by charliermarsh** [comment]
(Closing for now since you should just be able to do a single `uv pip install` here, but happy to answer any follow-up questions.)

**Comment by fersarr** [comment]
Sounds good, thanks for explaining and for the quick reply!
