### ISSUE TITLE
Is there a way to connect to the Internet via a proxy server? 

### ISSUE THREAD

**Issue by tealgreen0503** [astral-sh/uv#3233]
In pip, we can connect Internet via a proxy server using the `--proxy` option or by following the method described [here](https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server). How can we do the same in uv?

**Comment by zanieb** [comment]
We support the standard `HTTP_PROXY`, `HTTPS_PROXY` and `ALL_PROXY` environment variables via `reqwest`

https://github.com/seanmonstar/reqwest/blob/580606308d94f20139548d4668e5d0f06068a70b/src/proxy.rs#L897-L920

We can add these to the README
