### ISSUE TITLE
`compile_index_url_fallback_prefer_primary` test doesn't seem to test anything

### ISSUE THREAD

**Issue by mgorny** [astral-sh/uv#3238]
The following test:

https://github.com/astral-sh/uv/blob/116d47ed03695c5fb2ce8084663ff79bc87b6b54/crates/uv/tests/pip_compile.rs#L7808-L7844

indicates that it relies on the "extra" index having 3.1.2 as the newest version. However, looking at https://download.pytorch.org/whl/jinja2/, the index includes 3.1.3 as well, so the test doesn't really test anything.

I suppose it would be better to actually use a index that you control here.

**Comment by zanieb** [comment]
Thanks!

**Comment by charliermarsh** [comment]
My guess is that the index version was updated.

**Comment by zanieb** [comment]
Are we not using exclude newer here?

**Comment by zanieb** [comment]
Huh we explicitly turn that off, seems unnecessary.

**Comment by charliermarsh** [comment]
No, it's intentional -- we can't use `--exclude-newer` with the PyTorch index.

**Comment by zanieb** [comment]
Ah because they don't have timestamps? 😭

**Comment by charliermarsh** [comment]
But the solution is to not use the PyTorch index :joy:
