### ISSUE TITLE
Segmentation fault on MacOS 11.7.10 (BigSur)

### ISSUE THREAD

**Issue by fbehrens** [astral-sh/uv#3261]
Hi, thanks for `uv`.
I am using it, unfortunately today on my late 2013 MacBook Pro (which has latest updates offered by apple )

```
curl -LsSf https://astral.sh/uv/install.sh | sh
# downloading uv 0.1.38 x86_64-apple-darwin
# installing to /Users/fb/.cargo/bin
#   uv
# everything's installed!

uv -V
# [1]    5088 segmentation fault  uv -V
```

`uv` was working on the hardware in previous versions,
so I report it here.

Thank you

**Comment by charliermarsh** [comment]
Are you on macOS 11?

**Comment by charliermarsh** [comment]
My guess is that the issue here is that GitHub changed `macos-latest` to `macos-14`, rather than `macos-12`.

**Comment by charliermarsh** [comment]
We may want to roll back to `macos-12` to ensure that macOS 11 keeps working... but note that macOS 11 has been EOL for over six months.
