### ISSUE TITLE
Add a `pipdeptree` like output

### ISSUE THREAD

**Issue by mgaitan** [astral-sh/uv#3272]
[pipdeptree](https://github.com/tox-dev/pipdeptree) is a cool tool for visualizing the dependency tree of python packages. It allows users to see a structured "tree" of dependencies and, using its reverse mode, to understand why a particular dependency is required for our project.

One particularly [useful use case](https://github.com/tox-dev/pipdeptree?tab=readme-ov-file#using-pipdeptree-to-write-requirementstxt-file) of `pipdeptree` is to filter out only the "top-level" packages. This helps in cleaning up `*.in` files by leaving the resolution of transitive dependencies to the compilation process.

Would it be possible to support something similar to this as a built-in feature of `uv` ? something like `uv pip list --format=tree` ?

**Comment by charliermarsh** [comment]
I like the idea of having a tree view for this. `cargo tree` is another good example -- really useful.

**Comment by MarcinKonowalczyk** [comment]
Strong support for this(!) I was about to make a proposal similar to it, although i didn't know `pipdptree` so was going to use `pip-chill` as an example. I'd love to see alongside this functionality like `pip-autoremove` - remove given package and all the orphan packages it leaves behind.

**Comment by samypr100** [comment]
For reference/design, poetry has `--tree` as part of `poetry show`

**Comment by ibraheemdev** [comment]
Opened https://github.com/astral-sh/uv/issues/4439 to track additional features that did not land in the initial PR.

**Comment by dbux** [comment]
For anybody else arriving here from a web search, the command is [`uv pip tree`](https://docs.astral.sh/uv/reference/cli/#uv-pip-tree)

**Comment by RafalSkolasinski** [comment]
1. would be nice if https://docs.astral.sh/uv/pip/inspection/ mentioned this
2. would be nice if the output of the command was coloured
