### ISSUE TITLE
Defining index-url in pyproject.toml not working

### ISSUE THREAD

**Issue by florianfischer91** [astral-sh/uv#3288]
First of all thanks for developing uv (and ruff). They are really amazing :-)
 
I was trying to set the `index-url` in a `pyproject.toml`, but im always getting the following error:

```
error: Failed to parse `pyproject.toml`
  Caused by: TOML parse error at line 2, column 5
  |
2 | Url="https://randomstring/simple"
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
invalid type: string "https://randomstring/simple", expected struct VerbatimUrl
```

Example to reproduce the bug, call `UV_CONFIG_FILE=pyproject.toml uv pip show ruff` where `pyproject.toml` contains

```
[tool.uv.pip.index-url]
Url="https://randomstring/simple"
```

uv version: 0.1.38

Am I doing something wrong or is this still not ready for use?

**Comment by charliermarsh** [comment]
I think you would want:

```toml
[tool.uv.pip]
index-url = "https://randomstring/simple"
```

**Comment by florianfischer91** [comment]
I have already tried that but i also results in an error:
```
error: Failed to parse `pyproject.toml`
  Caused by: TOML parse error at line 2, column 13
  |
2 | index-url = "https://randomstring/simple"
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unknown variant `https://randomstring/simple`, expected one of `Pypi`, `Url`, `Path`
```

**Comment by charliermarsh** [comment]
Oh sorry, thanks, I'll fix that.

**Comment by charliermarsh** [comment]
(This isn't an officially supported feature yet, it's undocumented.)

**Comment by charliermarsh** [comment]
Please continue to file bugs on it though, much appreciated!

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/uv/pull/3289.
