### ISSUE TITLE
Implied "--require-hashes"?

### ISSUE THREAD

**Issue by helderco** [astral-sh/uv#3305]
It's great to have the new `--require-hashes` option, but can it be implied if installing from a requirements file with hashes?

It's what `pip` does:

>   --require-hashes            Require a hash to check each requirement against, for repeatable installs. This option is implied when any package in a requirements file has a --hash option.

The reason I need this is because I need to make a container image that installs dependencies from a requirements file, but I don't know if that file will have hashes or not.

**Comment by zanieb** [comment]
Seems reasonable!

**Comment by helderco** [comment]
`pip install` checks hashes by default if a requirements file contains hashes. You could disable it with `--no-require-hashes`.

Or introduce an explicit `--verify-hashes` that checks them if they exist, but otherwise doesn't "require" them.

**Comment by helderco** [comment]
Hey! 👋 Any update on this? In Dagger, hashes are only checked if uv is disabled explicitly.

**Comment by charliermarsh** [comment]
I added it in https://github.com/astral-sh/uv/pull/4007.

**Comment by hauntsaninja** [comment]
I think it's important for the defaults to be secure. Maybe uv could have the proposed `--verify-hashes` behaviour on by default? ("I have a hash but I don't want it checked" seems pretty niche)
