### ISSUE TITLE
Build backend failed to build wheel through `build_wheel()` - wrong architecture

### ISSUE THREAD

**Issue by CatamountJack** [astral-sh/uv#3308]
Using `uv` (via `rye`), it can't create x86 wheels for (some) dependencies on my x64 machine.

I created my project with Python 3.12.2 x64 and all worked well, but I wanted to build a 32-bit executable.  In rye, I set my `.python-version` to `cpython-x86@3.12.2` and then ran `rye sync`.  This worked great on a different project, but the current project depends on `pandas` and it's choking while trying to build a wheel for that.

uv version:  `uv 0.1.37 (645d0399f 2024-04-23)`

rye version:
```rye 0.33.0
commit: 0.33.0 (58523f69f 2024-04-24)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

Platform:  `Windows 11 Pro 23H2 on x64`

Traceback:
```
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pandas==2.2.1
  Caused by: Failed to build: `pandas==2.2.1`
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit code: 1
--- stdout:
+ meson setup C:\Users\abcdefg\AppData\Local\uv\cache\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz C:\Users\abcdefg\AppData\Local\uv\cach
e\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz\.mesonpy-jm3uwz41\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv
 --native-file=C:\Users\abcdefg\AppData\Local\uv\cache\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz\.mesonpy-jm3uwz41\build\meson-python-native-file.ini
The Meson build system
Version: 1.2.1
Source dir: C:\Users\abcdefg\AppData\Local\uv\cache\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz
Build dir: C:\Users\abcdefg\AppData\Local\uv\cache\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz\.mesonpy-jm3uwz41\build
Build type: native build
Project name: pandas
Project version: 2.2.1
Activating VS 17.4.4
C compiler for the host machine: cl (msvc 19.34.31937 "Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64")
C linker for the host machine: link link 14.34.31937.0
C++ compiler for the host machine: cl (msvc 19.34.31937 "Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64")
C++ linker for the host machine: link link 14.34.31937.0
Cython compiler for the host machine: cython (cython 3.0.5)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES (C:\Users\abcdefg\AppData\Local\uv\cache\.tmpDIdfXM\.venv\Scripts\python.exe)
Need python for x86_64, but found x86
Run-time dependency python found: NO (tried sysconfig)

..\..\pandas\_libs\tslibs\meson.build:32:7: ERROR: Python dependency not found

A full log can be found at C:\Users\abcdefg\AppData\Local\uv\cache\built-wheels-v3\index\b2a7eb67d4c26b82\pandas\2.2.1\mKNob4WeHbOZ108PaIHLq\pandas-2.2.1.tar.gz\.mesonpy-jm3uwz41\build\meson-logs\meson-log.txt
--- stderr:

---
error: Installation of dependencies failed in venv at C:\dev\source\tools\EvaluateWeights\.venv. uv exited with status: exit code: 2
```

Looks like maybe it's trying to use the x64 compiler instead of a 32-bit one?  (is there anything additional I would need to do, like install a separate x86 compiler on my machine?)

**Comment by suryavirkapur** [comment]
**Same Error**

uv version: `uv 0.1.18 (43dc9c87a 2024-03-13)`
platform: `Windows 11 Pro 23H2 on x64`
tracelog: ```
Resolved 41 packages in 11ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: scikit-learn==1.0.2
  Caused by: Failed to build: scikit-learn==1.0.2
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit code: 1
--- stdout:
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um /Tctest_program.c /Foobjects\test_program.obj
INFO: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /MANIFEST:EMBED,ID=1 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64 objects\test_program.obj /OUT:test_program.exe
INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
```

**Comment by konstin** [comment]
Could you run with `-v` and share the log as [gist](https://gist.github.com/)?

**Comment by CatamountJack** [comment]
Log (of `rye sync -v`) [here](https://gist.github.com/CatamountJack/0d1cdc316b426d16613354f771ffef62).  Not sure if rye is passing `-v` to uv or not, I'm not using uv directly.

**Comment by vfilter** [comment]
Having the same issue with pandas 2.1.0. 2.2.2 works just fine.

**Comment by IndrajeetPatil** [comment]
I am seeing the same issue while building a Docker image on a Windows machine:

The relevant part Dockerfile:

```
FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app
COPY . /app/

RUN uv sync --frozen
```

Error log:

```
 => ERROR [backend stage-0 5/6] RUN uv sync --frozen                                                                                                                                                                                                                            9.0s 
------
 > [backend stage-0 5/6] RUN uv sync --frozen:
0.800 Using CPython 3.13.0 interpreter at: /usr/local/bin/python
0.800 Creating virtual environment at: .venv
8.674 error: Failed to prepare distributions
8.674   Caused by: Failed to download and build `geventhttpclient==2.3.1`
8.674   Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
8.675
8.675 [stderr]
8.675 warning: no previously-included files matching '*' found under directory 'tests'
8.675 warning: no previously-included files matching '__pycache__' found anywhere in distribution
8.675 warning: no previously-included files matching '*.py[co]' found anywhere in distribution
8.675 error: command 'gcc' failed: No such file or directory
------
failed to solve: process "/bin/sh -c uv sync --frozen" did not complete successfully: exit code: 2
```

**Comment by charliermarsh** [comment]
That just looks like you're missing `gcc`. Maybe one of your dependencies doesn't ship Python 3.13 wheels yet? You can either install `gcc` to enable building from source, or try using a version like Python 3.12.

**Comment by brunolnetto** [comment]
Hi, @charliermarsh. I just got the same error for specifically for library [`factory`](https://pypi.org/project/Factory/), logs below. Do you have any idea solving this issue? My python version on command run `python3 --version` is `Python 3.10.12`.

````
  × Failed to download and build `factory==1.2`
  ╰─▶ Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/home/brunolnetto/.cache/uv/builds-v0/.tmpanGVjU/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/brunolnetto/.cache/uv/builds-v0/.tmpanGVjU/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/home/brunolnetto/.cache/uv/builds-v0/.tmpanGVjU/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/home/brunolnetto/.cache/uv/builds-v0/.tmpanGVjU/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      NameError: name 'file' is not defined. Did you mean: 'filter'?
```

**Comment by zanieb** [comment]
@brunolnetto that's a different issue than being discussed here and doesn't look related to uv (it's a build failure when invoking the setup script for that package)

**Comment by zanieb** [comment]
@mike-hearn I can't really diagnose the difference between mise and uv, but you can resolve that failure by adding the Python version's library to `LDFLAGS`, e.g.: `LDFLAGS=-L/root/.local/share/uv/python/cpython-3.9.20-linux-x86_64-gnu/lib`. I tested that with `docker run --platform linux/x86_64 -e LDFLAGS=-L/root/.local/share/uv/python/cpython-3.9.20-linux-x86_64-gnu/lib --rm -it ghcr.io/astral-sh/uv:bookworm /bin/bash -c "apt update && apt install clang -y && uv venv -p 3.9 && uv pip install uwsgi==2.0.28"`

**Comment by gmaOCR** [comment]
Got the same in a docker during a build in armv7. Dependecies installed with uv pip install

```
Using Python 3.11.10 environment at: /venv
39.23   × Failed to download and build `run==0.2`
39.23   ╰─▶ Build backend failed to determine requirements with `build_wheel()`
39.23       (exit status: 1)
39.23 
39.23       [stderr]
39.23       Traceback (most recent call last):
39.23         File "<string>", line 14, in <module>
39.23         File
39.23       "/root/.cache/uv/builds-v0/.tmpofEZnh/lib/python3.11/site-packages/setuptools/build_meta.py",
39.23       line 334, in get_requires_for_build_wheel
39.23           return self._get_build_requires(config_settings, requirements=[])
39.23                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
39.23         File
39.23       "/root/.cache/uv/builds-v0/.tmpofEZnh/lib/python3.11/site-packages/setuptools/build_meta.py",
39.23       line 304, in _get_build_requires
39.23           self.run_setup()
39.23         File
39.23       "/root/.cache/uv/builds-v0/.tmpofEZnh/lib/python3.11/site-packages/setuptools/build_meta.py",
39.23       line 522, in run_setup
39.23           super().run_setup(setup_script=setup_script)
39.23         File
39.23       "/root/.cache/uv/builds-v0/.tmpofEZnh/lib/python3.11/site-packages/setuptools/build_meta.py",
39.23       line 320, in run_setup
39.23           exec(code, locals())
39.23         File "<string>", line 12, in <module>
39.23       NameError: name 'file' is not defined. Did you mean: 'filter'?
```

**Comment by zanieb** [comment]
@gmaOCR Please open a new issue, that is not the same error as the OP encountered. See #9452. The [build failure](https://docs.astral.sh/uv/reference/build_failures/) guide might be helpful.

I'm going to close this issue because we keep getting unrelated reports.
