### ISSUE TITLE
Add environment variable for `--no-build-isolation`

### ISSUE THREAD

**Issue by morotti** [astral-sh/uv#3309]
Hello,

I am trying to use the `--no-build-isolation` option, introduced in https://github.com/astral-sh/uv/pull/2258
It's necessary to make uv/pip use the current venv when installing or building packages. 
It's largely used in build systems and environments where a venv is already prepared to build/install packages.

I am finding that the option is not working when set by an environment variable? I think it might not be implemented.
Or the environment variable name/value might be something else. I've tried a few variants I could think of but that did not help.

```
# pass
uv pip install -e . --no-build-isolation
```

```
# fail
UV_NO_BUILD_ISOLATION=true uv pip install -e .
```

uv version 0.1.39 (latest as of today)

**Comment by zanieb** [comment]
Yeah, we don't provide an environment variable for this yet.
