### ISSUE TITLE
Consider `zlib-rs` flate2 backend instead of `zlib-ng`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#3310]
See https://github.com/rust-lang/flate2-rs/releases/tag/1.0.29 and #3295

**Comment by charliermarsh** [comment]
Ohh this would be great. (But low priority.)

**Comment by hauntsaninja** [comment]
Sounds like zlib-rs is actually 5-10% slower than zlib-ng

**Comment by charliermarsh** [comment]
I briefly tried and hit some errors, gonna defer for now.
