### ISSUE TITLE
Add environment variable for `--link-mode`

### ISSUE THREAD

**Issue by davidfritzsche** [astral-sh/uv#3313]
Hello,

thanks for you work on uv!

The outout of `uv pip install --help` (uv version 0.1.139) does not offer an environment variable for `--link-mode`. As I'm commonly editing installed Python packages (to debug something), it would be of great help if I could set the default link mode to `clone` instead of `hardlink` (I'm mostly working on Linux).

In general, from the documentation it is not really clear why the OS-specific defaults were chosen (probably performance?) and how uv protects itself against stupid old-school developers like me when they accidentially modify cached files installed with link mode `hardlink`.

PS: At $WORK my Windows-using colleagues are very much looking forward to use `uv` to speed up the creation of tox venvs to not take several minutes anymore. 🥇 for the astral team and all the contributors!

**Comment by zanieb** [comment]
Thanks for the kind words!

This seems reasonable to add.
