### ISSUE TITLE
[Question] Are platform-agnostic lockfiles on the roadmap?

### ISSUE THREAD

**Issue by Turakar** [astral-sh/uv#3321]
The uv README discusses the fact that uv generates platform-specific lockfiles, while other tools like PDM and poetry generate platform-agnostic lockfiles. While uv is able to generate cross-platform lockfiles, the question remains: Does uv plan to at some point be able to create platform-agnostic lockfiles?

At the moment, one would need to manage multiple lockfiles for a cross-platform project. This might be tedious and lead to inconsistencies. However, a unified lockfile might require conditionals, so I think that there is a tradeoff here.

I am interested in your opinions on that topic. Please link instances where this issue has been discussed previously.

**Comment by BurntSushi** [comment]
Yes, we are planning to do this. The [blog post announcing `uv` sketches our high level vision](https://astral.sh/blog/uv#a-cargo-for-python-uv-and-rye). I don't think we've discussed platform-agnostic lock files publicly in any open issues yet because it's still in the very early design phase. But we're looking to tools like Cargo and Poetry for inspiration.

**Comment by adminy** [comment]
would you support poetry lock files? Its a well defined format and if its already present, why not just use it?

**Comment by adminy** [comment]
So the only feature that I care about from poetry is the ability to define different packages inside project.toml file. and install just the ones needed per use case. To some extent that is now possible with pip as a builtin now. If uv supports that I'm happy to just switch away from poetry, lock files aside.

**Comment by chrisrodrigue** [comment]
I had the same question which was answered here: https://github.com/astral-sh/uv/issues/3347
