### ISSUE TITLE
Enable uv self-update via uv pip commands on Windows

### ISSUE THREAD

**Issue by FredStober** [astral-sh/uv#3339]
On windows, uv should be able to update itself when uv is installed into a virtual environment.

* The command you invoked (e.g., `uv pip sync requirements.txt`), ideally including the `--verbose` flag.
```
uv venv --seed test
test\Scripts\activate
pip install "uv==0.1.35"
uv pip install "uv==0.1.38"
```
Results under windows in `error: failed to remove file <......>\test\Lib\site-packages\../../Scripts/uv.exe`

The minimal example is just to show how to trigger the error. The same issue appears with a much more likely `uv pip sync`, whenever uv is listed as part of the requirements.

* The current uv platform

This affects all uv versions under windows (very likely due to the system limitations related to running processes).
There are different workarounds imaginable, so it would be nice if one could be implemented. Alternatively, uv should probably avoid even trying to do this and abort with a nicer error message, indicating that this is not supported - at least under windows, since it works fine on linux.

**Comment by charliermarsh** [comment]
Thanks -- I believe this is the same as #1368 and #1327.
