### ISSUE TITLE
`tool.uv.sources` needs to preserve verbatim representation

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3366]
See: https://github.com/astral-sh/uv/pull/3263/files#r1589862490

**Comment by konstin** [comment]
My idea was the pyproject.toml doesn't allow env vars; we can support relative paths properly and authentication and indexes with dedicated configuration.

**Comment by charliermarsh** [comment]
But we don't currently output relative paths when writing to `requirements.txt`. Is that not a bug?

**Comment by konstin** [comment]
I see, that should indeed be fixed
