### ISSUE TITLE
Preserve url parsing in `Dist`

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3409]
Part of #3407. We first need to
* Decide which types to add to the `Dist` variants
* Add these types
* Get this information from the`PubGrubPackage`
* Use it in subsequent code over the `VerbatimUrl`

**Comment by charliermarsh** [comment]
Is this specifically for `Dist::from_url`?

**Comment by konstin** [comment]
This is done, we track all the fields we need now

**Comment by charliermarsh** [comment]
Oh nice.
