### ISSUE TITLE
Make it possible to avoid yanked versions of packages in compiled requirements

### ISSUE THREAD

**Issue by barseghyanartur** [astral-sh/uv#3425]
## Feature request

Make it possible to avoid yanked versions of packages in compiled requirements (compiled with `uv pip compile`).

### What's the problem this feature will solve?

For instance, [Django 4.2.12](https://pypi.org/project/Django/4.2.12/) was marked as yanked, but appears in the compiled requirements. Not ideal.

### Describe the solution you'd like

At least to have an option to opt-out from yanked versions. It would be better though to have that as a default (and have an optional argument for opting-in).

### Command

```sh
uv pip compile --output-file requirements/default.txt \
    --no-strip-extras \
    --extra tests --extra loadtests pyproject.toml \
    --no-emit-package pip \
    --upgrade
```

### UV platform

macOS

### UV version

0.1.39

**Comment by barseghyanartur** [comment]
It might be that you already do that. In that case, maybe I was unlucky, and my requirements were compiled after the release has been marked as yanked. In that case, sorry for the buzz. Worth checking anyway.

**Comment by barseghyanartur** [comment]
@zanieb:

Thanks for confirming. Then it was probably just a bad timing.

**Comment by seefood** [comment]
just got a remark about a yanked package for the first time while running uv lock. it's not an explicit dependency. should I just accept the fate or make it an explicit dependency? is there a recommended workaround or is uv smart enough to have used one if there was and I should just accept its resolution as the best scenario?

**Comment by zanieb** [comment]
We'll usually only use a yanked version if it's pinned somewhere, so presumably one of your dependencies is pinning to that yanked version?

You can use `uv lock --upgrade-package <name>` to see if we can resolve to another version.

**Comment by seefood** [comment]
in my case it just said package foo version 1.5.0 is yanked, so I explicitly added foo<1.5.0 and the lock indeed picked 1.4.5 and said nothing. I think there's no automatic attempt by uv to avoid yanks.

**Comment by zanieb** [comment]
That's just not true. See the test coverage at https://github.com/astral-sh/uv/blob/ee0ba65eb22c6bba59ea216ff07aeb170f8d3f2a/crates/uv/tests/it/pip_install_scenarios.rs#L4189-L4631

 Feel free to share a reproduction in a new issue and we can look at it. It's not appropriate to bump an old issue like this.
