### ISSUE TITLE
Allow passing constraint file to `uv pip sync`?

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#3438]
With pip-compile, this can be accomplished via `--pip-args '--constraint c.txt'`.

The use case here is a little niche, since usually you just apply `--constraint` at the time you produce the lock file. But it's possible if your constraints file changes to encounter old lock files (maybe you're going back in history, or you don't automatically keep your lock file up to date), in which case it can be nice to get errors instead of e.g. installing some insecure dependency.

**Comment by charliermarsh** [comment]
I plan to support this but it's proving to be motivation to do some refactoring / cleanup work between `pip sync` and `pip install`, so want to knock that out first.
