### ISSUE TITLE
uv pip compile complains that my pyproject.toml dependencies aren't pinned after update to 0.1.40

### ISSUE THREAD

**Issue by VerdantFox** [astral-sh/uv#3445]
In `uv==0.1.39` the command `uv pip compile --output-file=requirements-prod.txt  pyproject.toml` works without error. On `uv==0.1.40`, when I run the same command, I get the following error:

```bash
❯ uv pip compile --output-file=requirements-prod.txt  pyproject.toml
error: Failed to parse `pyproject.toml`
  Caused by: Failed to parse entry for: `aiocache`
  Caused by: Must specify a version constrain
```

If I pin every single file in `pyproject.toml`, it works, but I don't want to pin those versions in `pyproject.toml`. That's what the lockfile is for. Do you have any idea what's going on? Is this breaking change intended, or is this a bug? Is there a new flag I should be using?

Thanks for the help! :)

I'm running this on Ubuntu 22.04.

**Comment by kpeez** [comment]
I'm getting the same exact error when attempting to compile dependencies from my `pyproject.toml` file

**Comment by zanieb** [comment]
Sounds like a bug! Thanks for the report. We'll investigate. Can you share a minimal example?

**Comment by charliermarsh** [comment]
Thanks, this is already fixed in https://github.com/astral-sh/uv/pull/3443.

**Comment by charliermarsh** [comment]
I will cut a new release tonight.

**Comment by VerdantFox** [comment]
Thanks! Quick work. I appreciate the effort and this project. :)
