### ISSUE TITLE
Incorrect locking with uv `--python-platform x86_64-apple-darwin`

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#3454]
```
λ cat r.in
ray==2.10
λ uv pip compile r.in --python-platform x86_64-apple-darwin
  × No solution found when resolving dependencies:
  ╰─▶ Because ray==2.10.0 is unusable because no wheels are available with a matching Python ABI and you require ray==2.10, we can conclude that the requirements are
      unsatisfiable.
```

I don't know why uv's complaining about this. There are valid wheels: https://pypi.org/project/ray/2.10.0/#files

**Comment by konstin** [comment]
The problem is that we set the macos version to 10.12:

https://github.com/astral-sh/uv/blob/2ffb252498a9d452b3fe28e16abe2948cd21ec51/crates/uv-configuration/src/target_triple.rs#L79-L92

Should we set a higher default here @charliermarsh?

**Comment by hauntsaninja** [comment]
10.15 is like five years old, so higher default sounds good. For my use case, I'd be happy to set the right value explicitly too if there was a way to

**Comment by charliermarsh** [comment]
I believe I chose 10.12 for a reason. I need to look back...

I experimented with adding a mechanism to specify exact versions. It added a lot of complexity and it wasn't clear how to display the candidate options on the CLI but I will revisit it. I was kind of waiting for someone to have a real need for it.

**Comment by charliermarsh** [comment]
Bumping the default to 12.0 (last non-EOL version), and adding support for `MACOSX_DEPLOYMENT_TARGET` so that you can override it as needed.

**Comment by charliermarsh** [comment]
Yeah, mostly because it's a standard environment variable read by other tools, so it's a little unusual for us to expose it as uv-specific configuration.
