### ISSUE TITLE
Offline mode is not automatic fallback when offline

### ISSUE THREAD

**Issue by minusf** [astral-sh/uv#3468]
I am trying to understand the reason why `--offline` is not implied when network connections fail:

```
VIRTUAL_ENV=venv uv pip install -r requirements.txt
error: Could not connect, are you offline?
  Caused by: error sending request for url (https://pypi.org/simple/django-timezone-field/)
  Caused by: client error (Connect)
  Caused by: dns error: failed to lookup address information: nodename nor servname provided, or not known
  Caused by: failed to lookup address information: nodename nor servname provided, or not known
```

Is there one?  The great appeal of `devpi` was that no matter if I was online or offline `pip install` just worked. It makes the CI/CD pipeline somewhat more convoluted if a flag needs to be added to explicitly request offline mode.

If the reason is to fail loudly and early and make some noise so a human has a look, it would be really nice to have a "fallback to offline if can't connect anywhere" command line switch please.

**Comment by zanieb** [comment]
I'm a little confused by what you expect to happen here. Can you expand on what you think uv's behavior should be? With devpi, there's a package index for tools to query — how do you think uv should work without a package index available?

**Comment by minusf** [comment]
I am sorry, I didn't include the rest of the story: the same command with `--offline` succeeds as all these packages were already in the cache.

Obviously if the dependency graph cannot be successfully resolved and the packages installed only using the cache, the operation should fail.

**Comment by zanieb** [comment]
Are all of your requirements pinned? I don't think we should attempt a network request unless it is needed, i.e. I would expect us to use the cache without the `--offline` flag here.

cc @charliermarsh

**Comment by minusf** [comment]
This is a hobby project, so not all packages are pinned :D  Actually only django is and the rest "gets the latest" strategy.

**Comment by zanieb** [comment]
If you just pin them i.e. use separate `requirements.in` and `requirements.txt` files with `uv pip compile` you shouldn't run into this issue. I'm not sure we should infer using offline for unpinned requirements, it's interesting to consider though.

**Comment by minusf** [comment]
Thank you, I will check out `pip-compile` "flow", never used it before.

What are the risks of trying going offline mode here? I have a tunnel vision of my use case here (i.e. the `venv` was built completely successfully at least once and is cached), but it seems harmless to me to try and see if all packages can be installed from the local cache. What is there to lose? If I add the `--offline` parameter it just all works already...

**Comment by zanieb** [comment]
I think the main problem is that package resolution should not change whether you have internet or not — that'd be a surprising behavior without opt-in.

cc @charliermarsh

**Comment by samypr100** [comment]
> that'd be a surprising behavior without opt-in.

👆 100% agree

**Comment by minusf** [comment]
So if I understand correctly, if all packages and subpackages were pinned, there could be no surprising behaviour and `--offline` could be a safe fallback?

**Comment by minusf** [comment]
I tested the all pinned workflow and `--offline` indeed becomes redundant. 

This is great and maybe worth documenting. This means that for my uses cases I don't need `devpi` anymore and that's just toast. `pip` is also a marked man, all it does now is `pip list --outdated`.

I think this issue can be closed.
