### ISSUE TITLE
Error running uv pip compile with `--python-version` specified when Python 2 is on the PATH

### ISSUE THREAD

**Issue by notatallshaw-gts** [astral-sh/uv#3474]
I am looking to migrate some scripts I have at work to use uv, perhaps I am using the `--python-version` flag wrong, does a Python with that version need to be available on the PATH or can uv resolve without it?

```
$ uv -V
uv 0.1.41

$ python -V
Python 3.11.4

$ echo "requests" > test.txt

$ uv pip compile --python-version 3.10.6  test.txt 
error: Querying Python at `/usr/bin/python` failed with status exit status: 2 with exit status: 2
--- stdout:

--- stderr:
Unknown option: -I
usage: /usr/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
---

$ /usr/bin/python -V
Python 2.7.15
```

**Comment by charliermarsh** [comment]
I can fix that. We're not catching that specific failure (`-I` is unsupported).

**Comment by notatallshaw-gts** [comment]
I don't know if it makes a difference, but the reproduction is using a conda environment.

I have some a couple of scripts that do something very similar to uv pip compile and sync by using a mix of conda and pip, I am experimenting if I can significantly simplify and speed them up with uv.

**Comment by notatallshaw** [comment]
Thanks as always for the lighting quick fix! 

My aging work environment always seems to have a way to find interesting issues. I'll continue working to see if I can replace large parts of my logic with uv and if it finds anymore issues 🙂 .

**Comment by charliermarsh** [comment]
No prob, let me know if you continue to see Python 2 issues. It's tricky because we can't actually get a structured error here (we're passing `-I` to the interpreter which isn't supported prior to 3.4).
