### ISSUE TITLE
 Unsupported scheme `git+http` on URL (insecure Git protocol)

### ISSUE THREAD

**Issue by my1e5** [astral-sh/uv#3483]
I'm trying to use `rye` (with `uv`) to install a python package which I'm hosting on a local [`gitea`](https://github.com/go-gitea/gitea)  server.

```
$ rye add foo --git http://mygiteaserver/org/repo
error: Failed to run uv compile error: Unsupported scheme `git+http` on URL: git+http://mygiteaserver/org/repo (insecure Git protocol)
. uv exited with status: exit code: 2
```

Before moving to `rye` I would usually use `pip install git+http://mygiteaserver/org/repo` and this worked fine. Is there any way to get this working with `rye`/`uv`?

This issue is possibly related - https://github.com/astral-sh/uv/issues/2960

**Comment by charliermarsh** [comment]
We intentionally don't support insecure HTTP dependencies. Can you serve over HTTPS?

**Comment by my1e5** [comment]
I've found an alternative solution is to use `ssh`. Requires each user to have ssh keys set-up with `gitea`, but then it does work as it did before with `pip`. And we don't have to set up HTTPS. For example:
```
$ rye add foo --git ssh://git@mygiteaserver/org/repo.git
```
If you don't intend to support HTTP then I suppose those of us who are used to using `pip install git+http://_______` will have to use alternative methods which I'm ok with.

**Comment by zanieb** [comment]
It does sound nice to hint to use https or ssh in our error message.
