### ISSUE TITLE
Unable to query interpreter information of MUSL standalone distribution

### ISSUE THREAD

**Issue by ofek** [astral-sh/uv#3486]
The following illustrates that for some reason the standalone distribution's pip does not consider MUSL wheels and will download the source distribution:

```
docker run --rm -d --name builder python:alpine sleep infinity
docker exec builder ash -c "apk update && apk add curl"
docker exec builder curl -LO https://github.com/indygreg/python-build-standalone/releases/download/20240415/cpython-3.12.3+20240415-x86_64_v3-unknown-linux-musl-install_only.tar.gz
docker exec builder tar xzf cpython-3.12.3+20240415-x86_64_v3-unknown-linux-musl-install_only.tar.gz
docker exec builder /python/bin/python -m pip install uv
```

That is probably an issue for that repository but then I had the idea of using UV to install into the distribution as follows:

```
docker exec builder pip install uv
docker exec builder uv pip install --python /python/bin/python uv
```

but that produces an error:

```
error: Querying Python at `/python/bin/python` did not return the expected data: invalid value: integer `-1`, expected u16 with exit status: 0
--- stdout:
{"result": "success", "markers": {"implementation_name": "cpython", "implementation_version": "3.12.3", "os_name": "posix", "platform_machine": "x86_64", "platform_python_implementation": "CPython", "platform_release": "5.15.153.1-microsoft-standard-WSL2", "platform_system": "Linux", "platform_version": "#1 SMP Fri Mar 29 23:14:13 UTC 2024", "python_full_version": "3.12.3", "python_version": "3.12", "sys_platform": "linux"}, "base_prefix": "/python", "base_exec_prefix": "/python", "prefix": "/python", "base_executable": "/python/bin/python", "sys_executable": "/python/bin/python", "stdlib": "/python/lib/python3.12", "scheme": {"platlib": "/python/lib/python3.12/site-packages", "purelib": "/python/lib/python3.12/site-packages", "include": "/python/include/python3.12", "scripts": "/python/bin", "data": "/python"}, "virtualenv": {"purelib": "lib/python3.12/site-packages", "platlib": "lib/python3.12/site-packages", "include": "include/site/python3.12", "scripts": "bin", "data": ""}, "platform": {"os": {"name": "manylinux", "major": -1, "minor": -1}, "arch": "x86_64"}, "gil_disabled": false}
--- stderr:

---
```

**Comment by charliermarsh** [comment]
@konstin - can you take a look at this?

**Comment by zanieb** [comment]
Interesting that the OS versions are "major": -1, "minor": -1, maybe we just need to allow that?

**Comment by charliermarsh** [comment]
I think (-1, -1) is just a sign that we didn't detect glibc either. The error message is off: https://github.com/astral-sh/uv/pull/3487. But we should be detecting musl, not sure why we aren't? We just call methods in `packaging`.

**Comment by ofek** [comment]
I opened an issue over there for the first part of this bug: https://github.com/indygreg/python-build-standalone/issues/260

**Comment by charliermarsh** [comment]
Thx.

**Comment by ofek** [comment]
The error message should be improved so I will be closing this, thanks!

**Comment by konstin** [comment]
The musl builds are statically linked. This means it's a python without any external deps, but it also means - to my best understanding of how ELF works - that it can't load dynamic libraries. `pip debug` also only shows `linux_x86_64` and `any` as supported tags (no manylinux or musllinux). It afaik doesn't matter whether it's statically linked against glibc or musl, since that information isn't available at runtime.

We can support statically linked python interpreter, but i'd only do so if there is explicit demand since these are nearly unusable without loading libraries.
