### ISSUE TITLE
iron out how to represent path dependencies in the universal lock file

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#3506]
We want to support path dependencies in our lock file. But the data model for path dependencies in our lock file is, at the time of writing, not quite right. I believe what we _ought_ to have for a path dependency is a single file URL to a directory, source distribution or wheel. But the data model currently allows for a source distribution _and_ zero or more wheels, but specifically does not allow for a directory.

I think the current data model is mostly just a reaction to the types that we have after resolution. Namely, I think we have two related types. The first is for wheel path dependencies:

https://github.com/astral-sh/uv/blob/616ed530430f08577af5ae549c3d2b525e7e34ce/crates/distribution-types/src/lib.rs#L174-L180

And the second is for source distribution path dependencies:

https://github.com/astral-sh/uv/blob/616ed530430f08577af5ae549c3d2b525e7e34ce/crates/distribution-types/src/lib.rs#L206-L213

My understanding is that the second is _also_ used when we have a path dependency to a directory.

This all matters for the lock file because if a path dependency points to a wheel or a source dist, then we want to record a hash for it. But if it comes from a directory, then we very specifically do not want to record a hash.

So to fix this issue, I think we need to:

* [x] Adjust the `PathSourceDist` type so that it indicates whether it came from a real source distribution or a directory. Possibly one way to do this is to split the type in two, with one type representing source distributions and the other representing a directory.
* [ ] Adjust the `Lock` data model so that distributions with a `path` source kind are more limited than what they are today. I think we actually do _not_ want to encode the file path itself, and instead derive that from the `pyproject.toml`. (This would match what Cargo does.)

**Comment by charliermarsh** [comment]
I can look at the first bullet there, splitting `PathSourceDist`.

**Comment by charliermarsh** [comment]
What does the second bullet mean exactly? Can you flesh it out a bit more? Perhaps I can help with it.

**Comment by charliermarsh** [comment]
Is it that the path gets omitted entirely when it's part of the workspace?

**Comment by BurntSushi** [comment]
> Is it that the path gets omitted entirely when it's part of the workspace?

Yeah exactly. Cargo rebuilds the path from the `Cargo.toml` instead, as I understand it. So in order to get the path of a path dependency in a lock file, I think there is some interaction point between what's in `pyproject.toml` and what's in the lock file.

(There is at least one other interaction point as well: finding the relevant root package in the lock file at which to start a graph traversal.)
