### ISSUE TITLE
Explore using a dev drive for windows CI

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3508]
We observe that windows is much slower on any io operations, e.g. just downloading and unpacking the python versions takes 1.5min. We should explore using using a VHDX virtual harddisk as described in https://github.com/actions/cache/issues/752#issuecomment-1847036770 to see if this solves the performance bottleneck in github actions.

**Comment by notatallshaw** [comment]
FYI there are some more details here where this was reccomended for pip to do: https://github.com/pypa/pip/issues/12055

Ultimately pip maintainers are very conservative about adding new features, but you might find the post informative.

**Comment by zanieb** [comment]
See also, this brief GitHub Actions thread requesting this feature: https://github.com/actions/runner-images/issues/8698
