### ISSUE TITLE
Cannot install cryptacular==1.6.2 (or any recent version) with uv

### ISSUE THREAD

**Issue by bgedik** [astral-sh/uv#3509]
```
uv --version
uv 0.1.42
```

```
python --version
Python 3.11.9
```

In a clean environment with no packages:

`uv pip install cryptacular==1.6.2`

gives

```
--- stdout:

--- stderr:
Traceback (most recent call last):
  File "<string>", line 14, in <module>
TypeError: prepare_metadata_for_build_wheel() got an unexpected keyword argument 'config_settings'
---

```

Whereas the same command works for regular pip in a virtual environment created with `virtualenv`:

```
pip --version
pip 24.0 from /home/ubuntu/.test_vm/lib/python3.11/site-packages/pip (python 3.11)
```

```
pip install cryptacular==1.6.2
Collecting cryptacular==1.6.2
  Using cached cryptacular-1.6.2-cp311-cp311-linux_x86_64.whl
Collecting pbkdf2 (from cryptacular==1.6.2)
  Using cached pbkdf2-1.3-py3-none-any.whl
Requirement already satisfied: setuptools in ./.test_vm2/lib/python3.11/site-packages (from cryptacular==1.6.2) (44.0.0)
Installing collected packages: pbkdf2, cryptacular
Successfully installed cryptacular-1.6.2 pbkdf2-1.3
```

**Comment by charliermarsh** [comment]
That's a strange error. `config_settings` is part of the specification: https://peps.python.org/pep-0517/#prepare-metadata-for-build-wheel.

**Comment by charliermarsh** [comment]
I think that build backend is not spec compliant, in that it uses the variable name `settings`? 

https://github.com/dholth/enscons/blob/8a63d64d7782bc1ad492181b6578797140684570/enscons/api.py#L33

My guess is that pip passes this as a positional argument.

**Comment by bgedik** [comment]
@charliermarsh  is there a suggested workaround?

**Comment by notatallshaw** [comment]
> My guess is that pip passes this as a positional argument.

Maybe I'm reading the pip source totally wrong here, I've never spent much time looking at the mechanics of how this works, but as I read it:

* Pip outsources this call to pyproject-hooks: https://github.com/pypa/pip/blob/main/src/pip/_internal/utils/misc.py#L730
* pyproject-hooks writes the config settings to an "input.json" file, then calls the build backend via a subprocess pointed to the directory that json is in: https://github.com/pypa/pyproject-hooks/blob/main/src/pyproject_hooks/_impl.py#L378

Therefore side stepping calling `prepare_metadata_for_build_wheel` directly, and hence why this build backend doesn't error out. Again though, first time I'm reading this code, so maybe I'm misunderstanding something.

**Comment by charliermarsh** [comment]
pip calls these as positional arguments: https://github.com/pypa/pyproject-hooks/blob/261e4d82121782d05f6fddfaded8b8a7493d0370/src/pyproject_hooks/_in_process/_in_process.py#L166. So I guess we need to do the same, even though I'd argue that the build backend is at fault.

**Comment by notatallshaw** [comment]
> So I guess we need to do the same, even though I'd argue that the build backend is at fault

Personally, I agree, but I would like to bring this to the attention of a wider audience: https://discuss.python.org/t/are-build-backends-that-use-different-keyword-arguments-to-the-standard-spec-compliant/53056

**Comment by charliermarsh** [comment]
Thanks.

**Comment by charliermarsh** [comment]
@bgedik - will work in the next version of uv.
