### ISSUE TITLE
Persistent config section of README out of date

### ISSUE THREAD

**Issue by jonfitt** [astral-sh/uv#3510]
> uv supports persistent configuration at both the project- and user-level.
> 
> Specifically, uv will search for a pyproject.toml or uv.toml file in the current directory, or in the nearest parent directory.
> 
> If a pyproject.toml file is found, uv will read configuration from the [tool.uv.pip] table. For example, to set a persistent index URL, add the following to a pyproject.toml:
> 
> [tool.uv.pip]
> index-url = "https://test.pypi.org/simple"

This section of the README seems inaccurate with the current version (0.1.42)

When trying to use an index-url setting I get:

```
error: Failed to parse `pyproject.toml`
  Caused by: TOML parse error at line 196, column 10
    |
196 | [tool.uv.pip]
    |          ^^^
unknown field `pip`, expected `sources` or `workspace`

```

I tried "sources" literally but that's not what it was looking for. Could you please update the doc?

**Comment by charliermarsh** [comment]
My guess is this is happening when you run `pip install -r pyproject.toml`, but not `pip install flask` (for example) with a `pyproject.toml` in the same directory?

**Comment by jonfitt** [comment]
It was `uv pip compile`

**Comment by charliermarsh** [comment]
Sorry, yes, the distinction I'm drawing is: you were passing it directly as an argument, right?

**Comment by jonfitt** [comment]
Ah yes:
`uv pip compile .\requirements_dev.in .\pyproject.toml -o requirements.txt` to be exact.
