### ISSUE TITLE
Add support for setting all remote packages to --only-binary

### ISSUE THREAD

**Issue by yeswalrus** [astral-sh/uv#3513]
Feature request/suggestion:
If your requirements.txt file contains both local packages that are meant to be built as well as remote packages, the `--no-build` flag becomes unusable. It would be very useful to be able to specify you don't want to build any package that needs to be fetched remotely.  At minimum this could be achieved with `--only-binary :remote:`.

Perhaps more flexible would be adding wildcard pattern support for the `--only-binary` flag, perhaps in the form `:<package>@<remote>:`, so you could say `--only-binary :some-package@*:` or `--only-binary :*@remote.url:`

edit:
The simplest option would be to simply ignore the --only-binary flag for any package marked with `--editable` in the requirements.txt

**Comment by zanieb** [comment]
I'm having a hard time pulling up the code to confirm this, but I'm pretty sure that we already do not apply `--only-binary` to editable requirements.

**Comment by zanieb** [comment]
Here's a demonstrative test case https://github.com/astral-sh/uv/pull/3521

**Comment by yeswalrus** [comment]
Interesting. I've got some --editable local packages, and when I set --no-build, I wind up with failures. Ex:

```
Built 6 editables in 868ms
error: Failed to build `sim-scores @ file:///home/user/dev/prod/pins/python/sim_scores`
  Caused by: Building source distributions is disabled
```

where my requirements.txt looks like:
```
...
--editable python/sim_scores
...
```

**Comment by yeswalrus** [comment]
Perhaps relevant - our sim_scores package has a setup.py, not a project.toml? I'm trying to reproduce in a unit test like the one you linked and not having any luck, but I can absolutely reproduce the issue with any version of uv I try.

**Comment by yeswalrus** [comment]
I've managed to reproduce the error in a unit test here: https://github.com/astral-sh/uv/pull/3559

**Comment by zanieb** [comment]
Thanks! I've reproduced that in https://github.com/astral-sh/uv/pull/3561

**Comment by zanieb** [comment]
Going to track this in a more focused issue at https://github.com/astral-sh/uv/issues/3562
