### ISSUE TITLE
uv cache clean fails after build failures

### ISSUE THREAD

**Issue by yeswalrus** [astral-sh/uv#3515]
Related to https://github.com/astral-sh/uv/issues/3512

When builds fail, it appears that uv cache can get into a corrupted state where a particular directory exists, and is owned, but is missing +rx permissions and so cannot be deleted.

Repro steps
1) Run
```
#!/bin/bash
make_venv(){
    uv venv $1
    source $1/bin/activate
    uv pip install jaeger-client
}

for i in {1..8}
do
   make_venv $1/$i &
done
```
2) run `uv cache clean`

**Comment by charliermarsh** [comment]
Can you share the permission flags on the file?

**Comment by charliermarsh** [comment]
We already have handling for read-only files (we try to delete; if it fails and the file is read-only, we change permissions and try again), so wondering if there's something else...

**Comment by yeswalrus** [comment]
The file it fails on is actually a directory, so that may have been it?

**Comment by yeswalrus** [comment]
```
Clearing cache at: ~/.cache/uv
error: Failed to clear cache at: ~.cache/uv
  Caused by: IO error for operation on ~/.cache/uv/built-wheels-v3/index/6024232a22aa81c8/jaeger-client/4.3.0/b1Sqzocp-Y-aYlYPEp_R4/jaeger-client-4.3.0.tar.gz/build/bdist.linux-x86_64/wheel/jaeger_client: Permission denied (os error 13)
  Caused by: Permission denied (os error 13)
  ```
  ls -la on that file shows:
  ```
  d-w------- 2 user user 4096 May 10 18:00 jaeger_client
  ```

**Comment by charliermarsh** [comment]
Thank you!

**Comment by charliermarsh** [comment]
Thanks, reproduced and think I have a fix.

**Comment by yeswalrus** [comment]
Thanks for the prompt resolution!
