### ISSUE TITLE
Cleaning an empty cache removes 4 files

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3539]
Repeatedly calling `uv cache clean` removes 4 files every time on ubuntu 24.04. This should not happen, `uv cache clean` shouldn't create a cache directory before cleaning (and/or we should count correctly)

```
Clearing cache at: /home/konsti/.cache/uv
Removed 4 files (44B)
```

**Comment by charliermarsh** [comment]
Yeah I looked at this recently too. The problem is that we initialize the cache in `main.rs` every time IIRC. And that involves creating a few files.
