### ISSUE TITLE
Custom name of directory instead of ".venv" for multiple envs inside the same project

### ISSUE THREAD

**Issue by detrin** [astral-sh/uv#3540]
I would like to create multiple environments with a custom name instead of the default ".venv" directory name. I can't find it in the README.md. Is this option available?

**Comment by zanieb** [comment]
`uv venv [name]` should work.

**Comment by detrin** [comment]
> `uv venv [name]` should work.

It does work! Thanks! Would you add it to README.md as well? I didn't find any docs outside README.md

**Comment by zanieb** [comment]
We could, though I'm not sure where it'd fit right now.

The CLI help menu is pretty useful e.g. `uv venv --help`.

**Comment by detrin** [comment]
I think it would fit into the section "To create a virtual environment:"

**Comment by detrin** [comment]
I see we thought of the same section :)

**Comment by zanieb** [comment]
Thanks!
