### ISSUE TITLE
Extra index url when it is specified over command line and uv.toml

### ISSUE THREAD

**Issue by jmspereira** [astral-sh/uv#3541]
Hey everyone,

I have a setup where I call uv pip install with an extra-index-url specified as a parameter, for instance:

uv pip install <package> --extra-index-url <extra-index-url>

But during CI I want to overwrite the value of that flag, for that, I am using the uv. tom file where I have specified:

[pip]
extra-index-url = [<extra-index-url2>]

So the final setup is the uv.toml file and uv being called as mentioned previously (i.e., having 2 extra index URL).
However, it appears that uv is not looking the one specified in the configuration (contrary to what pip does). Is this supposed to happen? Or am I doing something wrong?

Best regards,
- Jorge

**Comment by charliermarsh** [comment]
Are you _also_ providing the `--extra-index-url` on the command-line in CI? So in CI, do you have _both_ the command-line argumnet _and_ the `uv.toml` file present?

**Comment by jmspereira** [comment]
Correct

**Comment by charliermarsh** [comment]
Ah, ok. Command-line arguments always take precedence over configuration files, so yes, this is the expected behavior. I think you'll need to find a way to avoid passing the command-line argument in CI.

**Comment by jmspereira** [comment]
is there any reason to implement that behavior? That is not the behavior of pip when there are configurations specified as global in pip.conf

**Comment by charliermarsh** [comment]
It's standard for the command line to override environment variables, and for environment variables to override configuration files. Even pip implements this (at least as-written here): https://pip.pypa.io/en/stable/topics/configuration/#precedence-override-order.

**Comment by jmspereira** [comment]
Ok, I looked into it and the difference in behavior is that in the case of pip, for the concrete case of the extra-index-url (since it can take multiple values), the value passed in the command line is merged with the value specified in the config file (i.e., if you have 1 extra index url specified in pip.conf and another in the command line, in the end, the two are used).

**Comment by charliermarsh** [comment]
Oh, you want _both_ index URLs to be respected? I assumed from the original issue that you were trying to _disable_ the index URL from the command-line given `extra-index-url = []`.

**Comment by jmspereira** [comment]
Sorry If I was not explicit enough in the original issue, but yes, I would like to have both to be respected.

**Comment by charliermarsh** [comment]
I think it's reasonable to merge here when the type is a vector? We at least merge when we discover multiple configuration files. What do you think @zanieb?

**Comment by zanieb** [comment]
I think merging seems reasonable, we have `--isolated` to stop reading the configuration file.

**Comment by charliermarsh** [comment]
Out now in [v0.1.45](https://github.com/astral-sh/uv/releases/tag/0.1.45). Let me know if you continue to see issues.

**Comment by jmspereira** [comment]
Everything works as expected from my side, thank you!
