### ISSUE TITLE
Missing documentation for available fields in `uv.toml` and `pyproject.toml`

### ISSUE THREAD

**Issue by silv-io** [astral-sh/uv#3545]
The Readme (which to my knowledge is currently the only documentation available) mentions the availability of configuration values in `uv.toml` and `pyproject.toml`. It does not, however, mention which configuration values are available. 

It would be nice to have an overview of what is available here to more easily discover the `uv` features one might want to use. 
If it is planned to support adding all CLI arguments also as a configuration value (like `pip-compile` does), it would also be nice to have documentation on how those CLI arguments translate to the configuration values.

**Comment by charliermarsh** [comment]
We already create and publish a JSON Schema for this which is the hard part. (Separately, you should get  Maybe there's something low-effort we can do to generate visual documentation from that.

Separately, if you have the TOML extension installed in VS Code, you should already get completion:

![Screenshot 2024-05-13 at 10 59 03 AM](https://github.com/astral-sh/uv/assets/1309177/8d40b419-4ff3-4c0a-ab01-49c06f381b05)

**Comment by charliermarsh** [comment]
This now exists -- I wrote it all out today, and we have a docs pipeline working. We'll make this public soon.

**Comment by silv-io** [comment]
@charliermarsh That's great. Just want to add that when I go to astral.sh and click on "Docs" I get redirected immediately to the `ruff` docs :) 
Don't see a way yet to get to https://docs.astral.sh/uv/ without typing it out (It's also not linked in the sidebar of the repo)

**Comment by silv-io** [comment]
Also, I'll close this now as the requested documentation is available here: https://docs.astral.sh/uv/settings/

**Comment by Mukhametvaleev** [comment]
> Also, I'll close this now as the requested documentation is available here: https://docs.astral.sh/uv/settings/

404 - Not found

**Comment by charliermarsh** [comment]
The URL is: https://docs.astral.sh/uv/reference/settings/
