### ISSUE TITLE
Track parsed url parts in `GitSourceUrl`

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3571]
Like in `GitSourceDist`, we should track the parsed url parts in `GitSourceUrl` to resolve https://github.com/astral-sh/uv/pull/3458/files#r1599281039. Half of it is https://github.com/astral-sh/uv/compare/konsti/track-url-parts-in-git-source-url, but it still needs lifetime fixes for `resolve_requirement`.

**Comment by charliermarsh** [comment]
I can do this.
