### ISSUE TITLE
Still get error running uv pip compile with --python-version specified when Python 2 is on the PATH

### ISSUE THREAD

**Issue by notatallshaw-gts** [astral-sh/uv#3579]
This is a follow up to https://github.com/astral-sh/uv/issues/3474 that was closed by https://github.com/astral-sh/uv/pull/3476

I am still getting the same error:

```
$ python -V
Python 3.11.2

$ uv self update
info: Checking for updates...
success: Upgraded `uv` to v0.1.43! https://github.com/astral-sh/uv/releases/tag/0.1.43

$ uv -V
uv 0.1.43

$ uv cache clean
Clearing cache at: /scratch/.cache/uv
Removed 31527 files (1.0GiB)

$ uv pip compile --python-version 3.10.6  -c base-constraints.txt temp-requirements.txt
error: Querying Python at `/usr/bin/python` failed with status exit status: 2 with exit status: 2
--- stdout:

--- stderr:
Unknown option: -I
usage: /usr/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
---

$ /usr/bin/python -V
Python 2.7.15
```

**Comment by charliermarsh** [comment]
It's because `usage: /usr/bin/python [option], we're matching against `usage: python [option]`. I can fix it, but that's why it worked in my case but not yours.

**Comment by notatallshaw-gts** [comment]
Thanks again for your quick fix!

I'll keep reporting issues as long as you don't mind supporting quirky edge cases old Linux distros (Fedora 29) can produce.

**Comment by charliermarsh** [comment]
Out now in [v0.1.45](https://github.com/astral-sh/uv/releases/tag/0.1.45). Please report if you're still running into problems, always welcome!

**Comment by notatallshaw-gts** [comment]
Thanks, I am now able to get uv commands to run under this scenario! 

I have found a very curious difference between the output of pip and uv, I am investigating now to see if it's a bug in one or the other.
