### ISSUE TITLE
pip compile with local disk package without hard dependency on uv?

### ISSUE THREAD

**Issue by Nomelas** [astral-sh/uv#3593]
This is my situation, 

In my project i have a `pyproject.toml` which contains my dependencies and maps my `lib` directory as a local package.
When i run `pip install .` it installs my dependencies and my lib directory as my project name (my-project for example) and version specified in my `pyproject.toml` (version is actually dynamic).

In order to have `uv pip compile` also include my local package, i needed to create a requirements.in which contains only `.` (i have a separate one for requirements-dev.in containing `-e .[dev]` for additional development dependencies).

When I run `uv pip compile requirements.in -o requirements.txt`, it generates the file as expected except for the line;
`my-project @ .`

When I run `uv pip compile requirements-dev.in -o requirements-dev.txt`, it generates the file as expected except for the line;
`-e .`

Now, when I run vanilla `pip install -r requirements-dev.txt` it works as expected, but when I run `pip install -r requirements.txt`, it complains that the line `my-project @ .` is not valid. This works fine however when running `uv pip install -r requirements.txt` but my goal is to not have a hard dependency on uv when installing already pinned versions like this. Is it possible to accomplish this?

**Comment by Nomelas** [comment]
manually replacing "my-project @ ." with "." makes it work with pip, but there must be a better way?

**Comment by charliermarsh** [comment]
Yes, pip does not support relative paths with named dependencies, and we always output with names. You can track and chime in here if you'd like: https://github.com/astral-sh/uv/issues/3180
