### ISSUE TITLE
uv run can install two versions of the same package (and forces upgrades)

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#3601]
I was trying out different versions of pytest with a pytest plugin to see when it was broken. I mentally was thinking of `uv run` as the Python launcher for UNIX, a way to avoid activating a venv (`py` instead of `.venv/bin/python`). It seems to do some installing automatically - including three strange things:

```console
$ uv venv
$ uv pip install -e .
$ uv pip install 'pytest==7.0.*'
$ uv run pytest
warning: `uv run` is experimental and may change without warning.
Resolved 5 packages in 8ms
   Built pytest-github-actions-annotate-failures @ file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures                                                                    Downloaded 1 package in 1.25s
Installed 2 packages in 33ms
 - pytest==7.0.1
 + pytest==8.2.0
 - pytest-github-actions-annotate-failures==0.2.0 (from file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures)
 + pytest-github-actions-annotate-failures==0.2.0 (from file:///Users/henryschreiner/git/software/pytest-github-actions-annotate-failures)
... pytest output ...
```

At this point, I hadn't noticed it had forcibly upgraded the pytest I was testing to the latest version, so I thought 7.0.x worked. (Some else in parallel found it was 7.4 that broke us).

Then the next line caught me by surprise, it uninstalls two pytests:

```console
$ uv pip install 'pytest==6.*'
Resolved 7 packages in 145ms
Downloaded 2 packages in 68ms
Installed 2 packages in 6ms
 - pytest==7.0.1
 - pytest==8.2.0
 + pytest==6.2.5
 + toml==0.10.2
```

And finally, the final `uv run` actually works just fine, and doesn't upgrade pytest:

```console
$ uv run pytest
... pytest output ...
```

**Comment by charliermarsh** [comment]
Thanks. To be clear, I wouldn't recommend `uv run` for "real" use yet but I do appreciate bug reports. Are you able to reproduce the double-uninstall reliably?

**Comment by henryiii** [comment]
Same sequence does do it again:

```console
$ uv venv
$ uv pip install -e .
$ uv pip install 'pytest==7.0.*'
$ uv run pytest
$ uv pip list
Package                                 Version
--------------------------------------- -------
attrs                                   23.2.0
iniconfig                               2.0.0
packaging                               24.0
pluggy                                  1.5.0
py                                      1.11.0
pytest                                  7.0.1
pytest                                  8.2.0
pytest-github-actions-annotate-failures 0.2.0
tomli                                   2.0.1
```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by zanieb** [comment]
@charliermarsh this looks like it might be because we use `EmptySitePackages` in `resolve` instead of passing the `site_packages` we grabbed earlier.

**Comment by charliermarsh** [comment]
Thanks @zanieb.

**Comment by henryiii** [comment]
> To be clear, I wouldn't recommend uv run for "real" use yet

If it were finished, where would the fun be in me using it? ;)
