### ISSUE TITLE
installation of editable package don't work when adding python markers

### ISSUE THREAD

**Issue by ImpSy** [astral-sh/uv#3604]
## UV details
version: `0.1.44`
command `uv pip sync requirements.txt`

## What
 uv currently not work while installing an editable package with python markers

## How to reproduce

for the following requirements.txt
```
-e file:///Users/sebastienmaintrot/libs/aws-client ; python_version >= "3.9" and python_version < "3.11"
```

uv fails with the following error
```
error: Failed to build editables
  Caused by: Source distribution not found at: /Users/sebastienmaintrot/Spot/CP/bigdata-python-services/libs/aws-client ; python_version >= "3.9" and python_version < "3.11"
```

**Comment by charliermarsh** [comment]
I don't think pip respects these, as far as I can tell they're just ignored?

For example, installing this file _always_ installs the editable:

```
-e ./scripts/packages/black_editable ; python_version < "3.9"
```

**Comment by charliermarsh** [comment]
Fixed in https://github.com/astral-sh/uv/pull/3622.

**Comment by charliermarsh** [comment]
Out now in [v0.1.45](https://github.com/astral-sh/uv/releases/tag/0.1.45).
