### ISSUE TITLE
Cache on CI gets broken whenever UV updates

### ISSUE THREAD

**Issue by haarisr** [astral-sh/uv#3612]
Using Github CI and Github actions cache, we save the cache dir.

When there is no update to uv, `uv pip install -r requirements.txt` uses the cached files and our CI takes about a minute.

Whenever there is an update to uv, the install time goes upto 8 minutes. On checking, uv reinstalls all our packages and seems to not use the cache anymore.

**Comment by charliermarsh** [comment]
How are you installing uv? How are you saving and restoring the cache? (uv itself does not invalidate the cache across updates.)

**Comment by zanieb** [comment]
On some versions, we need to make changes to the cache. This shouldn't happen on every release though, do you have examples of this occurring?

**Comment by haarisr** [comment]
> How are you installing uv? How are you saving and restoring the cache? (uv itself does not invalidate the cache across updates.)

curl -LsSf https://astral.sh/uv/install.sh | sh

> On some versions, we need to make changes to the cache. This shouldn't happen on every release though, do you have examples of this occurring?

It happened from 0.1.23 to 0.1.24 and from 0.1.24 to 0.1.26. We never had any PR's on 0.1.25.

**Comment by zanieb** [comment]
We _did_ bump the cache in v0.1.26 https://github.com/astral-sh/uv/commit/7b685a8158f0e444526732d25667aa6a7bc418cf

It seems likely you just encountered some cache changes.

**Comment by zanieb** [comment]
Let us know if you encounter more problems. The cache has been more stable in recently releases, but still might change need to change for us to improve the data model.
