### ISSUE TITLE
`find-links` TOML parse error: expected `Path` or `Url`

### ISSUE THREAD

**Issue by masonkirchner** [astral-sh/uv#3617]
Hey team, I have the following `uv.toml` file: 
```
[pip]
find-links = ["file:///home/mkirchner/development/"]
```

When I try to run `uv pip compile requirements.in` I get the following error: 

```
error: Failed to parse `uv.toml`
  Caused by: TOML parse error at line 2, column 15
  |
2 | find-links = ["file:///home/mkirchner/development/"]
  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unknown variant `file:///home/mkirchner/development/`, expected `Path` or `Url`
```

I'm not exactly sure if this is a bug in the parsing or user error on my end, but regardless I can't get it to work. I cannot find much documentation about the `uv.toml` file. Any ideas?

**Comment by charliermarsh** [comment]
I suspect it's just a bug. Will take a look!

**Comment by charliermarsh** [comment]
Sorry about that, fixed here: https://github.com/astral-sh/uv/pull/3619
