### ISSUE TITLE
mTLS Support?

### ISSUE THREAD

**Issue by SystemCoder99** [astral-sh/uv#3626]
Now that uv.toml is implemented and we can set the native-tls flag, will there be support for mTLS? 
Will we be able to pass a client_cert file path through the uv.toml so our developers and their package repos can authenticate each other?
We rely heavily on this feature in pip, it would be great to see UV have some kind of implementation too!

**Comment by zanieb** [comment]
Can you say more about how you're using this in pip? Perhaps link to an example or the relevant part of the pip implementation?

It sounds reasonable to configure certificates via the persistent config file. We do support `SSL_CERT_FILE` already.

**Comment by zanieb** [comment]
Thanks for the additional details. This seems reasonable but I'd have to start working on an implementation to understand if it makes sense.

The `SSL_CERT_FILE` loading comes from https://github.com/rustls/rustls-native-certs but I _think_ that's their behavior.

**Comment by alkatar21** [comment]
We also need the `cert` option. Currently this option is used for pip for our index and I have not found an alternative way with `uv` to access our index.

**Comment by zanieb** [comment]
I'm guessing this looks something like https://github.com/camelop/rust-mtls-example/blob/1379379eb08c63f22f9b4eae080c9380e29ffd44/src/main.rs#L22-L71

If anyone is interested in putting up a pull request I'm happy to review

**Comment by zanieb** [comment]
@SystemCoder99 this should be available in the latest release.
