### ISSUE TITLE
Install root package as editable in `uv run`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3628]

**Comment by janosh** [comment]
which commit/PR resolved this issue? wondering what the current behavior is and not finding it here: https://docs.astral.sh/uv/guides/scripts (doesn't mention `editable`). [i'm seeing CI errors](https://github.com/janosh/pymatviz/pulls/286) suggesting install is not editable

**Comment by konstin** [comment]
`uv run --extra extras` should also work
