### ISSUE TITLE
Where is `install.sh` in the repo?

### ISSUE THREAD

**Issue by s-banach** [astral-sh/uv#3640]
The documentation says to download `astral.sh/uv/install.sh`.
Where is `install.sh` in the repo?
I would feel safer linking to fixed versions of this script in a specific commit, rather than a dynamic version on your personal webpage.

**Comment by konstin** [comment]
The link in the readme is a redirect to https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh. You can find a fixed `uv-installer.sh` asset on each release in the releases page.

**Comment by bluenote10** [comment]
Coincidentally I was wondering exactly the same at roughly the same time :wink: 

I still don't really understand where it is coming from though, i.e., how does the release pull it out of thin air / where is it actually coming from originally?

**Comment by charliermarsh** [comment]
Yeah that's right -- we use `cargo-dist` to create our installers. They're generated as part of the release pipeline.
