### ISSUE TITLE
Support UV_CONFIG env variable to provide path to global configuration file

### ISSUE THREAD

**Issue by kpfleming** [astral-sh/uv#3648]
When building a container image with some pre-configuration for uv, I'd like to be able to run commands later without having to specify the path to the configuration file... and the container image doesn't have 'user home directories' so the usual discovery process isn't applicable.

I'd like to be able to set a UV_CONFIG (or similar name) environment variable which would bypass the discovery process and use the provided path for uv.toml directly.

**Comment by charliermarsh** [comment]
We actually already support this! Try `UV_CONFIG_FILE`. I need to add to the list in the README.
