### ISSUE TITLE
 Failed to run uv compile error: Received some unexpected HTML Caused by: Unexpected fragment (expected `#sha256=...` or similar)

### ISSUE THREAD

**Issue by njmaeff** [astral-sh/uv#3654]
The [jetbrains space package index](https://pypi.pkg.jetbrains.space/) uses a URL encoded sha256. Should this be handled by the package manager?

URL Encoded: `sha256%3D4095ada29e51070f7d199a0a5bdf5c8d8e238e03f0bf4dcc02571e78c9ae800d`
Decoded: `sha256=4095ada29e51070f7d199a0a5bdf5c8d8e238e03f0bf4dcc02571e78c9ae800d`

rye 0.33.0
commit: 0.33.0 (58523f69f 2024-04-24)
platform: linux (x86_64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: true

**Comment by charliermarsh** [comment]
I'll take a look.

**Comment by charliermarsh** [comment]
Should work in the next release.

**Comment by charliermarsh** [comment]
Out now in [v0.1.45](https://github.com/astral-sh/uv/releases/tag/0.1.45).
