### ISSUE TITLE
Tilde seen in site-packages

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [astral-sh/uv#3668]
I'm unsure how I got to this point, but the easiest way to reproduce this is to create a directory with a tilde at the front. As far as I can tell, the package and dist-info directories both have this tilde in the front. I also have the actual datadog_api_client 2.2.0 installed (i.e. both directories exist, it's just that the 1.11.0 version has a tilde replacing the `d`), so there must've been some kind of deletion error that happened that caused this tilde directory.
```
uv pip install -r dev_requirements.txt
error: Failed to list installed packages
  Caused by: Failed to read metadata: from /Users/andrew/Work/.direnv/python-3.10/lib/python3.10/site-packages/~atadog_api_client-1.11.0.dist-info
  Caused by: Not a valid package or extra name: "~atadog_api_client". Names must start and end with a letter or digit and may only contain -, _, ., and alphanumeric characters.
```

reference SO answer: https://stackoverflow.com/a/57488427:

Is it possible that you installed those particular packages with pip? If so, then the mangled directories are probably the temporary directories that pip creates when it uninstalls a package (or when it uninstalls a package in preparation for updating a package).

I dug through the pip source code and found [this snippet](https://github.com/pypa/pip/blob/19.2.2/src/pip/_internal/utils/temp_dir.py#L87-L106) which is evidently only used on uninstalling packages:

```
class AdjacentTempDirectory(TempDirectory):
    """Helper class that creates a temporary directory adjacent to a real one.
    Attributes:
        original
            The original directory to create a temp directory for.
        path
            After calling create() or entering, contains the full
            path to the temporary directory.
        delete
            Whether the directory should be deleted when exiting
            (when used as a contextmanager)
    """
    # The characters that may be used to name the temp directory
    # We always prepend a ~ and then rotate through these until
    # a usable name is found.
    # pkg_resources raises a different error for .dist-info folder
    # with leading '-' and invalid metadata
    LEADING_CHARS = "-~.=%0123456789"

    ...
```

If that's what these files are, then you can safely delete them.

**Comment by charliermarsh** [comment]
Thanks! Not sure what to do with these... We don't create them and they _are_ invalid package names, and the solution is indeed to delete them. Failing seems okay to me? The alternative is a warning.

**Comment by Andrew-Chen-Wang** [comment]
Would love to see an explicit warning and recommendation such as "Probably need to delete"
