### ISSUE TITLE
`uv pip list --format json` outputs _nothing_

### ISSUE THREAD

**Issue by thejcannon** [astral-sh/uv#3670]
It'd be nice if we could reliably parse the output as JSON, but right now if there's nothing installed matching the criteria I get _nothing_ (rather than an empty list). 😭 

```console
$ uv venv .venv
$ uv pip list --format json --python .venv/bin/python
$
$ uv --version                                           
uv 0.1.44 (d417daad7 2024-05-14)
```

(same for `--editable` in a seeded venv)

**Comment by thejcannon** [comment]
I suspect this might be around where the bug is: https://github.com/astral-sh/uv/blob/c32fb8647f53639a6bf19f93e9971ed36115b7f8/crates/uv/src/commands/pip/list.rs#L69

Dunno if `uv` should special-case JSON, or allow `results` to flow through all output formats

**Comment by charliermarsh** [comment]
My instinct would be to check what `pip` does and follow that for compatibility. PR welcome if you'd like! Otherwise I can get to it today.

**Comment by thejcannon** [comment]
`pip` does `[]`

```console
$ uv venv --seed
$ .venv/bin/pip list --format json --editable
$ []
$ .venv/bin/pip --version                    
pip 24.0 from ...
```

**Comment by thejcannon** [comment]
(If I had a dev env ready for hacking I'd totally just dive in 😭 )

**Comment by charliermarsh** [comment]
Haha no worries. I can fix today.

**Comment by thejcannon** [comment]
To close the loop with `pip` and the other formats:
```console
$ .venv/bin/pip list --editable --format columns
$ .venv/bin/pip list --editable --format freeze
$
```

so it's just JSON

**Comment by charliermarsh** [comment]
Out now in [v0.1.45](https://github.com/astral-sh/uv/releases/tag/0.1.45).
