### ISSUE TITLE
incorrect use of data-dist-info-metadata (PEP-714)

### ISSUE THREAD

**Issue by bazzargh** [astral-sh/uv#3689]
This is a driveby observation from code inspection at the current time

https://github.com/astral-sh/uv/blob/906f65306288407774bcd155ae20f5247b6fe6aa/crates/uv-client/src/registry_client.rs#L366
https://github.com/astral-sh/uv/blob/906f65306288407774bcd155ae20f5247b6fe6aa/crates/uv-client/src/html.rs#L190-L191
https://github.com/astral-sh/uv/blob/906f65306288407774bcd155ae20f5247b6fe6aa/crates/pypi-types/src/simple_json.rs#L40-L42

I was curious about the mechanism used to fetch metadata because dependabot is doing the Wrong Thing when calling artifactory, so I'm reading the codebases of other python registry clients. Reading the code here I noticed it's using the PEP 658 name of "dist-info-metadata" to find out if metadata is present, and an alias of "data-dist-info-metadata" to replicate a pip bug.

The problem is those were superceded by https://peps.python.org/pep-0714/ - because getting pip to use the correct PEP 658 name caused it to crash. uv is using what are now optional aliases for backwards compatibility in the api, and may not exist in other registries.

So I think:
```
    // Non-PEP 691-compliant alias used by PyPI.
    #[serde(alias = "data-dist-info-metadata")]
    pub dist_info_metadata: Option<DistInfoMetadata>,
```
should be (avoiding renaming the field internally but supporting the rename):
```
    // Non-PEP 691-compliant alias used by PyPI, and PEP-714 renamed field
    #[serde(alias = "data-dist-info-metadata", alias = "core-metadata")]
    pub dist_info_metadata: Option<DistInfoMetadata>,
```

Similarly this:
```
        // Extract the `data-dist-info-metadata` field, which should be set on
        // the `data-dist-info-metadata` attribute.
        let dist_info_metadata = if let Some(dist_info_metadata) =
            link.attributes().get("data-dist-info-metadata").flatten()
        {
            let dist_info_metadata = std::str::from_utf8(dist_info_metadata.as_bytes())?;
            let dist_info_metadata = html_escape::decode_html_entities(dist_info_metadata);
            match dist_info_metadata.as_ref() {
                "true" => Some(DistInfoMetadata::Bool(true)),
                "false" => Some(DistInfoMetadata::Bool(false)),
                fragment => Some(DistInfoMetadata::Hashes(Self::parse_hash(fragment)?)),
            }
        } else {
            None
        };
```
needs to be something more like (correcting first line of comment and adding fallback):
```
        // Extract the `dist_info_metadata` field, which should be set on
        // the `data-core-metadata` attribute (see PEP-714)
        let dist_info_metadata = if let Some(dist_info_metadata) =
            link.attributes().get("data-core-metadata").flatten()
        {
            let dist_info_metadata = std::str::from_utf8(dist_info_metadata.as_bytes())?;
            let dist_info_metadata = html_escape::decode_html_entities(dist_info_metadata);
            match dist_info_metadata.as_ref() {
                "true" => Some(DistInfoMetadata::Bool(true)),
                "false" => Some(DistInfoMetadata::Bool(false)),
                fragment => Some(DistInfoMetadata::Hashes(Self::parse_hash(fragment)?)),
            }
        // fallback to pre PEP-714 name from PEP-658
        } else if let Some(dist_info_metadata) =
            link.attributes().get("data-dist-info-metadata").flatten()
        {
            let dist_info_metadata = std::str::from_utf8(dist_info_metadata.as_bytes())?;
            let dist_info_metadata = html_escape::decode_html_entities(dist_info_metadata);
            match dist_info_metadata.as_ref() {
                "true" => Some(DistInfoMetadata::Bool(true)),
                "false" => Some(DistInfoMetadata::Bool(false)),
                fragment => Some(DistInfoMetadata::Hashes(Self::parse_hash(fragment)?)),
            }
        } else {
            None
        };
```
(I don't really speak rust, I'm sure there's a better way to dedupe that code)

**Comment by charliermarsh** [comment]
I can take a look, thanks.

**Comment by charliermarsh** [comment]
Do you know of any registry that actually implements `data-core-metadata`? Does Artifactory?

**Comment by charliermarsh** [comment]
Oh I see, PyPI adds it now in addition to `data-dist-info-metadata`.

**Comment by bewinsnw** [comment]
Artifactory does not implement that. Its support is unfortunately _very_ basic: over here https://jfrog.atlassian.net/browse/RTFACT-16101 you can see people asking for simple-json to be implemented and it was closed without comment.

Looking at our own instance, I can see that _none_ of the metadata attributes are exposed in the simple index pages it publishes. For libraries in our pull-through cache (like say, poetry, django) I can see that despite the attribute not being there adding `.metadata` to the wheel url does pull the correct metadata. For internal libraries published to the private simple index, no metadata is available at all.

It was headscratching at this and wondering how the heck dependabot was supposed to be working that led me to reading the spec and this code.

I don't know the status of the other non-warehouse servers, but I'd assume they're just as bad. Sonatype Nexus doesn't list its pep compatibility, but the examples in their docs are only of simple (not simple-json), and AWS Codeartifact says it only supports simple https://docs.aws.amazon.com/codeartifact/latest/ug/python-compatibility.html so really - PEP 714 more a theoretical concern with the specs, as far as I'm aware everything else lags pypi by several years and hasn't even got to PEP-658.

**Comment by charliermarsh** [comment]
The lack of support for this stuff (among other features) in non-PyPI registries is such a shame.
