### ISSUE TITLE
universal-lock: Lock with all extras, trim down on installation

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3700]
The lockfile needs to be built on a resolution with all extras of the root project and workspace requirements, but when installing we only want the extras and workspace packages the user requested. The need to trim the resolution, probably by a DAG traversal. This includes mapping unnamed requirements to their named counterpart in the resolution map.

**Comment by BurntSushi** [comment]
> The lockfile needs to be built on a resolution with all extras and workspace requirements

I think there is a hitch here right? Because some packages will have "dev" extras, and we specifically don't want to bring those into the lock file right? Basically that a package shouldn't inherit the dev dependencies of its dependencies. How do we deal with that?

**Comment by zanieb** [comment]
Development dependencies are separate from extras, technically. They can be placed in an extra, but generally they are separate and not a part of the standard metadata (i.e. it's project management tool specific).

**Comment by zanieb** [comment]
There's a bigger problem here though... extras can conflict with each other. Are we going to solve with them all turned on and ban conflicts? Are we going to lock all combinations?

**Comment by konstin** [comment]
If we want to support conflicting extras, the user needs to specify which those are and we apply the same split-resolve-merge as for conflicting disjoint markers. The ensures that extras are generally unified and conflict free and avoids combinatorial explosion.

**Comment by zanieb** [comment]
Do we know how they're going to express the conflict? Can you just do it with `<self-name>[extra]` markers?

**Comment by konstin** [comment]
We need additional `tool.uv` metadata for this, i don't think any other tool covers this yet. I've heard that some large complex frameworks had trouble adopting poetry due to this.

**Comment by charliermarsh** [comment]
I can take this if we want to start by "including all extras, then trimming at install time".

**Comment by olivier-lacroix** [comment]
You may want to take inspiration from pixi, which handles this via features (equivalent to a group of extra), that are included in environment(s).
Environments are included in the lock-file, and sometimes solved together when requested.
This avoids combinatorial explosion and is pretty flexible.
