### ISSUE TITLE
Confusing resolution error message

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#3710]
From [this CI failure](https://github.com/astral-sh/uv/actions/runs/9178311640/job/25237925377?pr=3643#step:6:361):

>   × No solution found when resolving dependencies:
  ╰─▶ Because pandas-stubs==2.0.3.230814 depends on numpy>=1.25.0 and you
      require numpy==1.24.4, we can conclude that you require==0a0.dev0 and
      pandas-stubs==2.0.3.230814 are incompatible.
      And because you require pandas-stubs==2.0.3.230814, we can conclude that
      the requirements are unsatisfiable.
 
 The requirements.txt was generated on a different platform than CI, should be able to reproduce by running `pip install` on [this file](https://github.com/astral-sh/uv/blob/e557cb4cedad811b9dc7e3a33da60154d187cd3c/scripts/requirements/compiled/airflow.txt), on Ubuntu (though there may be some other marker environments involved).

**Comment by zanieb** [comment]
Fixing the bad error message
