### ISSUE TITLE
Hash non-index files while downloading

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#372]
We need to record the hashes of non-index files, which we can do while downloading them:

https://github.com/astral-sh/puffin/blob/fbe28d3b7c51ed5bf27e4af7a7e1efde66b5114a/crates/install-wheel-rs/src/wheel.rs#L116-L144

This means that we need to download all url wheels after the resolve step to get the hashes, so we can also directly download and unpack them into the cache

**Comment by charliermarsh** [comment]
We now do this.
