### ISSUE TITLE
Deadlock during resolution

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#3724]
We're observing non-deterministic deadlocks in our test suite that we believe comes from #3627 which would mean it's present in v0.1.45+.

Please chime in if you're encountering this. We have yet to come up with a reliable reproduction.

This looks limited to Linux (Ubuntu in our test suite).

**Comment by ChannyClaus** [comment]
is there a link to the deadlocked build?

**Comment by ibraheemdev** [comment]
https://github.com/astral-sh/uv/pull/3987 should fix this, but we can reopen if it ever appears again.
