### ISSUE TITLE
Plans for eventually using published pubgrub?

### ISSUE THREAD

**Issue by musicinmybrain** [astral-sh/uv#3794]
I noticed that `pubgrub` is one of two dependencies that `uv` currently needs to fork (https://github.com/astral-sh/pubgrub), with [`async_zip`](https://github.com/prefix-dev/async_http_range_reader/issues/14) being the other. I also noticed that there seems to be ongoing work toward minimizing the changes in the fork, e.g. https://github.com/astral-sh/uv/pull/3713, https://github.com/astral-sh/pubgrub/commit/eeb63dd5fe524d4e3633d789da81e1d73dd574e5.

For the benefit of distribution packagers and others who [need to treat git dependencies specially](https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_replacing_git_dependencies), could you please comment briefly on whether you have a plan for eventually using the published [`pubgrub` crate](https://crates.io/crates/pubgrub)?

**Comment by konstin** [comment]
We unfortunately require api-breaking changes to pubgrub and access to some of the internals that will not be exposed in the published version. While we have been and will be spending significant effort into upstreaming our changes (https://github.com/pubgrub-rs/pubgrub/pulls?q=is%3Apr+author%3Akonstin), we unfortunately do not have plans to switch to a crates.io version of pubgrub.

**Comment by musicinmybrain** [comment]
Thanks! Even if the fork will be maintained indefinitely, the statement and explanation is valuable.

**Comment by zanieb** [comment]
We could vendor it within `uv` itself if it makes a big difference externally. We generally find it easier to maintain the fork in a separate repository though.

**Comment by musicinmybrain** [comment]
> We could vendor it within `uv` itself if it makes a big difference externally. We generally find it easier to maintain the fork in a separate repository though.

In Fedora, we handle `git` crate dependencies by adding an additional source archive, like https://github.com/astral-sh/pubgrub/archive/0e684a874c9fb8f74738cd8875524c80e3d4820b/pubgrub-0e684a874c9fb8f74738cd8875524c80e3d4820b.tar.gz, to the source RPM. Then we extract it and patch the `git` crate dependency into a `path` one.

This is perhaps a little more effort than dealing with an “in-tree” vendored/bundled crate, but not much more, as long as the number of such crates is small. Plus, this method has the advantage that it’s explicit, with no chance of missing vendored/bundled code that we needed to document and justify to satisfy our packaging guidelines. So I can’t speak for other distributions, but I’m perfectly happy with the way these two forked crates are managed now.
