### ISSUE TITLE
uv pip fails on BSD: Libc type could not be detected

### ISSUE THREAD

**Issue by lcheylus** [astral-sh/uv#3824]
Success to build of `uv` version 0.2.2 on OpenBSD current/amd64 with Rust version 1.78.0:
```bash
$ uv version
uv 0.2.2

$ rustc -vV
rustc 1.78.0 (15adfb9cd 2024-04-28) (built from a source tarball)
binary: rustc
commit-hash: 15adfb9cd5b029268e1470a41391d91859b0a1f8
commit-date: 2024-04-28
host: x86_64-unknown-openbsd
release: 1.78.0
LLVM version: 16.0.6
```

When I try to exec `uv pip list` command (or other `pip` commands), I have the following error:
```bash
$ uv pip list
error: Libc type could not be detected
```

After some analysis, this error seems to come from "Rewrite Python interpreter discovery" #3266. (release in version 0.2.0).

In `crates/uv-interpreter/src/platform.rs` file, function `Libc::from_env`, there is no case for BSD OD (`freebsd`, `openbsd`, `netbsd`), only for `linux` and `windows | macos` => `Error::LibcNotDetected` is returned for BSD OS.

I think this function sould return a new value `Libc::BSD` for BSD OS (specific libc version for this OS type, different from GNU libc).

**Comment by lcheylus** [comment]
OK, PR #3825 fixes this issue:

- build of `uv` v0.2.3 on OpenBSD current/amd64 with Rust 1.78.0
- `uv pip <command>` works as attended
```bash
$ uv pip list
Package                       Version
----------------------------- ---------
alabaster                     0.7.16
astroid                       3.1.0
attrs                         23.2.0
autopep8                      2.0.4
(...)
```

Thanks @konstin for your fix.

**Comment by zanieb** [comment]
Thank you for checking back in!
