### ISSUE TITLE
Read-only file system (os error 30) error on Render deploy starting with uv 0.2.0

### ISSUE THREAD

**Issue by yhoiseth** [astral-sh/uv#3838]
Deploying a web service (Django) on Render started failing with uv `0.2.0`. `0.1.45` works fine.

The command run is `uv pip sync --system requirements.txt`. The error is: ```failed to remove file `/usr/local/lib/python3.11/site-packages/crcmod-1.7.dist-info/INSTALLER`
  Caused by: Read-only file system (os error 30)```

I have attached the entire output using `--verbose`: [log.txt](https://github.com/astral-sh/uv/files/15447570/log.txt)

**Comment by charliermarsh** [comment]
It looks like you’re installing into the system Python but don’t have the permissions to modify it. Running with 0.1.45 works on the same image, etc.? Can you include the corresponding build logs from 0.1.45 to compare?

**Comment by yhoiseth** [comment]
> Can you include the corresponding build logs from 0.1.45 to compare?

Here it is: [log-0.1.45.txt](https://github.com/astral-sh/uv/files/15453621/log-0.1.45.txt)

> Running with 0.1.45 works on the same image, etc.?

Everything is the same, just different uv version. As far as I can tell, Render doesn’t expose image names or anything like that.

> It looks like you’re installing into the system Python but don’t have the permissions to modify it.

Yeah, to me it makes sense to use the system Python as this container or whatever it is is used only to serve this Django app.

**Comment by konstin** [comment]
Does it work without `--system`? It looks like there's a virtual environment in `.venv` that uv used to use, but with the interpreter discovery changes we're ignoring it since `.venv` is not a system interpreter.

**Comment by yhoiseth** [comment]
It does work on `0.2.3` without system: [log-0.2.3-without-system.txt](https://github.com/astral-sh/uv/files/15456326/log-0.2.3-without-system.txt)

Huh… 🤔 I used `--system` since I thought it was necessary to make all the “default” `python` commands to work. But now I see in the log that there is an active virtual environment: `DEBUG Found CPython 3.12.2 at `/opt/render/project/src/.venv/bin/python3` (active virtual environment)`

**Comment by charliermarsh** [comment]
Yeah I think you want to actively remove `--system` if you have a virtual environment.
