### ISSUE TITLE
onnxruntime doesn't resolve using python-platform x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by rbtcollins** [astral-sh/uv#3842]
uv version `0.2.3`
Originally discussed https://github.com/microsoft/onnxruntime/issues/20825

With requirements.in containing `onnxruntime==1.18` 

`uv pip compile   --python-platform x86_64-manylinux_2_28     --python-version="3.12"     -o ./requirements.txt requirements.in`

succeeds and 

`uv pip compile     --python-platform x86_64-unknown-linux-gnu --python-version="3.12"     -o ./requirements.txt requirements.in`

fails.

The wheels uploaded by onnxruntime looks sensible, and there should be no need for them to upload an exact match with manylinux existing.

We use bazel, and the bazel platform is of course the failing platform given to uv.

**Comment by charliermarsh** [comment]
This makes sense, though? The minimum supported manylinux on `x86_64-unknown-linux-gnu` is `manylinux_2_17`, and it's documented as such.

**Comment by charliermarsh** [comment]
In more detail: `x86_64-unknown-linux-gnu` on its own is under-specified, so we have to choose some reasonable default for it. `manylinux_2_17` is the current default, and we expose selectors like `x86_64-manylinux_2_28` for cases in which you want to use a different manylinux compatibility constraint. `onnxruntime` seems to use `manylinux_2_27` as its minimum supported version, so using the more specific platform identifier seems correct to me.

**Comment by rbtcollins** [comment]
I agree that `x86_64-unknown-linux-gnu` is underspecified :) - where is the correspondence to `manylinux_2_17` documented?

**Comment by charliermarsh** [comment]
It's in `uv pip install --help` (or similar):

```
      --python-platform <PYTHON_PLATFORM>
          The platform for which requirements should be installed.

          Represented as a "target triple", a string that describes the target platform in terms of its CPU, vendor, and operating system name, like `x86_64-unknown-linux-gnu` or `aaarch64-apple-darwin`.

          WARNING: When specified, uv will select wheels that are compatible with the _target_ platform; as a result, the installed distributions may not be compatible with the _current_ platform. Conversely, any distributions that are
          built from source may be incompatible with the _target_ platform, as they will be built for the _current_ platform. The `--python-platform` option is intended for advanced use cases.

          Possible values:
          - windows:                    An alias for `x86_64-pc-windows-msvc`, the default target for Windows
          - linux:                      An alias for `x86_64-unknown-linux-gnu`, the default target for Linux
          - macos:                      An alias for `aarch64-apple-darwin`, the default target for macOS
          - x86_64-pc-windows-msvc:     An x86 Windows target
          - x86_64-unknown-linux-gnu:   An x86 Linux target. Equivalent to `x86_64-manylinux_2_17`
          - aarch64-apple-darwin:       An ARM-based macOS target, as seen on Apple Silicon devices
          - x86_64-apple-darwin:        An x86 macOS target
          - aarch64-unknown-linux-gnu:  An ARM64 Linux target. Equivalent to `aarch64-manylinux_2_17`
          - aarch64-unknown-linux-musl: An ARM64 Linux target
          - x86_64-unknown-linux-musl:  An `x86_64` Linux target
          - x86_64-manylinux_2_17:      An `x86_64` target for the `manylinux_2_17` platform
          - x86_64-manylinux_2_28:      An `x86_64` target for the `manylinux_2_28` platform
          - aarch64-manylinux_2_17:     An ARM64 target for the `manylinux_2_17` platform
          - aarch64-manylinux_2_28:     An ARM64 target for the `manylinux_2_28` platform
```

Specifically the line: `x86_64-unknown-linux-gnu:   An x86 Linux target. Equivalent to `x86_64-manylinux_2_17`

**Comment by charliermarsh** [comment]
Going to call this "working as intended", though we could discuss bumping the manylinux minimum at some point.
