### ISSUE TITLE
Architecture not supported: arm

### ISSUE THREAD

**Issue by bulletmark** [astral-sh/uv#3854]
Using last uv version 1 works fine on my Raspberry Pi (running Arch):
```
$ uv -V
uv 0.1.7

$ uv venv
Using Python 3.12.3 interpreter at /usr/bin/python3.12
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
```
Using current uv version 2 can't create venv:
```
$ uv -V
uv 0.2.3

$ uv venv
  × Architecture not supported: arm
```
```
$ uname -a
Linux pi2 6.6.31-2-rpi #1 SMP Fri May 24 17:26:41 MDT 2024 armv7l GNU/Linux
```

**Comment by charliermarsh** [comment]
By the way, `uv 0.1.7` is very old (at least in uv terms), that's like 40 versions behind.

**Comment by bulletmark** [comment]
Yes, sorry Arch on ARM is poorly supported so uv 0.1.7 was the easiest version 1 available for me for me to easily restore from the standard packages.  I just hand installed uv 0.1.45 and that worked fine so clearly this is a version 2 issue.

**Comment by charliermarsh** [comment]
Yup all good. Should be fixed in the next release...
