### ISSUE TITLE
Specify a custom index for only one package

### ISSUE THREAD

**Issue by mariomeissner** [astral-sh/uv#3931]
I am using `uv pip compile` in a project that has pytorch dependencies. I need to use the custom pytorch index `https://download.pytorch.org/whl/cu117` to install `pytorch==2.13.1+cu117`. I am using the following syntax in my `requirements.in` file:
```
--extra-index-url https://download.pytorch.org/whl/cu117
torch==1.13.1+cu117
torchmetrics==1.3.1
```

However, this fails with the following error:
```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of torchmetrics==1.3.1 and you require
      torchmetrics==1.3.1, we can conclude that the requirements are
      unsatisfiable.
```

Indeed, `torchmetrics==1.3.1` is not available in the pytorch index, but it should be available in the default pypi index. I am aware of uv's limitation to search across multiple indexes, but I thought that I would be able to apply the custom index flag to only one package (in this case `torch`), and have it search for all other packages in the default index. This doesn't seem to be the case, as shown by the torchmetrics failure.

Is there a way to specify a custom index for just one package?

**Comment by charliermarsh** [comment]
There isn't a way to do this with `requirements.txt` but we'll support it in the future via TOML (see: #171). In the meantime, you should be able to use `--index-strategy unsafe-first-match` or `--index-strategy unsafe-any-match` to allow searching over multiple indexes.

**Comment by mariomeissner** [comment]
Thanks Charlie. 

I think one more solution is to use the '@' notation to specify the download URL, probably better and faster than enabling unsafe search.
