### ISSUE TITLE
Stop workspace discovery for git and other cache entries at cache entry root

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3936]
Currently, workspace discovery walks from the project `pyproject.toml` to the file system root to find a workspace pyproject.toml. For cache entries such as git checkout and temporary directories, we should only walk up to the cache entry boundary; we don't want to consider any `pyproject.toml` files the user may have above the cache root.

**Comment by charliermarsh** [comment]
What are Cargo's rules here?
