### ISSUE TITLE
Missing test coverage for `tool.uv` behaviours

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#3943]
In #3904, we added support for a whole class of new `tool.uv` behaviors, but no tests for them yet. 

- [x] Tests path dependencies into another workspace than the current. Consider two workspaces one disk, one workspace with packages A, B and another workspace with C, D, and path dependencies (editable or not) A -> B, B -> C, C -> D where A is the current project. We should test that B -> C correct resolves so that c -> D uses the workspace package D. https://github.com/astral-sh/uv/pull/4833
- [x] Test that we don't read `tool.uv` information from index packages, url archives or path archives, neither `tool.uv.sources` nor `tool.uv.workspace`.
- [x] Test that all combinations of editable and non-editable dependencies both in and across workspace work. Editable should take precedence over non-editable, e.g. if you require a package both as editable and non-editable, it becomes an editable.
- [x] Test that `tool.uv.sources` inheritance from the workspace to the project works.
- [x] Test that extras work with workspaces, specifically if the extra is part of another workspace package. We should check what cargo is doing here.
- [x] https://github.com/astral-sh/uv/issues/4603

**Comment by charliermarsh** [comment]
We should also test the `requires-python` behavior for workspaces -- what happens when no project has a `requires-python`? What happens when a single project has a `requires-python`? Etc.

**Comment by charliermarsh** [comment]
See also: https://github.com/astral-sh/uv/pull/4298

**Comment by charliermarsh** [comment]
Did these! They surfaced a few bugs too which is great.
