### ISSUE TITLE
Implement `uv remove`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3960]
As part of the Project API, we should have native `add` and `remove` commands.

**Comment by zanieb** [comment]
Most of our design discussions about this are internal right now, but we're publicizing some of them (e.g. #3560) and all of the work is public and [labeled as preview](https://github.com/astral-sh/uv/pulls?q=is%3Apr+label%3Apreview) (e.g. https://github.com/astral-sh/uv/pull/3705, https://github.com/astral-sh/uv/pull/3263).
