### ISSUE TITLE
Should installed distributions use canonical or specified path?

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3968]
Right now, if you create a symlink, and `uv pip install` the symlink, then `uv pip freeze`, we list the canonical path (with symlinks resolved). Is this preferred? Or should we use the user-provided path? The latter is more complex as we still need to normalize it.

**Comment by nathanjmcdougall** [comment]
Perhaps use the canonical path for now, and then in the future the behaviour could be configurable.

**Comment by charliermarsh** [comment]
Yeah, let's leave it as-is for now. Issue will continue to exist for users to find if it comes up in practice.
