### ISSUE TITLE
Locking in a workspace should lock the entire workspace

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#3983]
If you run `uv lock` in a workspace, we should lock the entire workspace, creating a single shared lockfile.

**Comment by charliermarsh** [comment]
\cc @konstin -- I think you wrote a TODO for this.

**Comment by idlsoft** [comment]
I think it would also be useful to have an MD5 checkum of the original dependencies.
Something like
```
# md5:albatross cc83132c0988b1cc87db8aad990d7649fef2a09e7c5d450bc3b44bc779bee51a
# md5:albatross:test 6b81ef26a9447316237f1c5a3debd7d131411c1f1a28d490f57de1f33400e369
```
This way commands like `venv --no-lock`  can complain about stale locks.
A dedicated `check-lock` command would also be nice.

We do this currently with `rye` so people don't forget to run `lock` after modifying `pyproject.toml`.
The implementation is bit hacky, but it's a good sanity check.
