### ISSUE TITLE
Unable to install pytorch dev release build (uv pip fails, regular pip succeeds)

### ISSUE THREAD

**Issue by fynnsu** [astral-sh/uv#3997]
uv version: 0.2.6

I ran the following and found that `uv` failed to find the `torch==2.3.1` package, but regular pip succeeded with the same command. Command to install upcoming release build of torch comes from [here](https://dev-discuss.pytorch.org/t/pytorch-release-2-3-1-final-rc-is-available/2126)

```bash
uv venv # Found a cpython 3.10 interpreter
source .venv/bin/activate
uv pip install --index-url https://download.pytorch.org/whl/test/cu121 torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1
# Fails with:
#   × No solution found when resolving dependencies:
#   ╰─▶ Because there is no version of torch==2.3.1 and you require torch==2.3.1, we can conclude that the requirements are unsatisfiable.

uv pip install pip
python -m pip install --index-url https://download.pytorch.org/whl/test/cu121 torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1
# Succeeds
```

Also going to the index link, I can manually confirm that the `torch==2.3.1` package does exist.

**Comment by fynnsu** [comment]
Ahh okay, looking into this further, it seems like the versions are listed with `+cu121` and if I update the command to
```bash
uv pip install --index-url https://download.pytorch.org/whl/test/cu121 torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121
```
it works.

I still think this might be a bug though, because I would expect `uv pip` to behave the same as regular pip and match without the `+cu121`.

**Comment by charliermarsh** [comment]
Thanks -- this is covered in the pip compatibility guide: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers
