### ISSUE TITLE
Advice on matching result from pip freeze with uv, e.g., search order ?

### ISSUE THREAD

**Issue by buildqa** [astral-sh/uv#4008]
I read some documentation that package repo search order can be changed with various args to uv.  My question is that given we have always used (conventional) pip freeze to create a snapshot of the installed package revisions - then what is the recommended way to run freeze (or some other cammnd) with uv to at least try and achieve party with what pip reports?  With no additional args, it looks like uv freeze reports tensorflow should be at the older revision 2.7.3 instead of the newer revision 2.13.1, but torch should be at the newer revision 2.3.0 instead of 2.1.2.

**Comment by charliermarsh** [comment]
Can you describe (in pip commands) the workflow you're trying to achieve? `uv pip freeze` just reports the _currently installed_ versions in your environment.

**Comment by zanieb** [comment]
As discussed in https://docs.astral.sh/uv/concepts/resolution/#basic-examples, there are multiple valid resolutions for a set of requirements. We can't guarantee that we match pip's behavior exactly in this regard (nor can pip guarantee it will match its own behavior from version to version or even invocation to invocation). You'll want to add more precise constraints to your requirements if you need to get an identical resolution.
