### ISSUE TITLE
FR: re-enforce distinction between download time and build time

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/uv#4011]
Hi, thanks for this wonderful tool !
I noticed that when building packages from source, either locally or from downloaded tarballs, reports build time is bundled in download time, which is somewhat misleading. I think it'd be more correct (and informative) to show time spent building sources separately, especially because it's usually much longer than resolution/download/install and that uv is not actually doing the heavy lifting there.
To illustrate what I mean, here's what happens if I run `uv pip install yt --no-binary yt` in a fresh env

```
Resolved 39 packages in 690ms
   Built yt==4.3.1
Downloaded 1 package in 33.49s
Installed 39 packages in 220ms
...
```
almost all the time is spent waiting for compilers and linkers (~33s), but it's still included in "downloaded".

Another aspect of this is the message you see as the package is being built (downloading itself takes a couple seconds at most)
![Screenshot 2024-06-04 at 09 49 56](https://github.com/astral-sh/uv/assets/14075922/45654536-f122-4b33-8a7b-a7251f0e4ae8)

Furthermore, if I instead clone https://github/yt-project/yt.git and install locally (`uv pip install -e .`), I *still* see build time being included in "download" time, which in this context seems plain wrong
```
Resolved 47 packages in 389ms
   Built yt @ file:///Users/clm/dev/yt-project/yt
Downloaded 10 packages in 25.44s
Installed 47 packages in 153ms
...
```

**Comment by zanieb** [comment]
Thanks for the clear report! This sounds incorrect, though I'm uncertain how easy it will be to fix.

**Comment by charliermarsh** [comment]
It isn’t really “possible” to fix this because we don’t download-then-build in discrete phases. We download and build in parallel across all packages. So while some packages are being downloaded, others are being built.

**Comment by charliermarsh** [comment]
We can use a more generic term, but conceptually we can’t report separate phases.

**Comment by zanieb** [comment]
Yeah the concurrent pipelining was my concern regarding feasibility. We could track the separate total times but I don't know we'd report it in a coherent way.

**Comment by neutrinoceros** [comment]
Thanks for clarifying that the built/download phase is conccurent, this wasn't obvious to me.
Since I'm having trouble coming up with a more generic term, how about something like this ?

```
Downloaded/built 10 packages in 25.44s
```
