### ISSUE TITLE
Allow `virtual = true` to declare a workspace root as virtual

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4025]
Right now, we seem to rely on `project` being absent, but that also means that we (e.g.) can't show a project name during errors. I think we should decouple `project` from virtual.

**Comment by konstin** [comment]
Where would we get the package name from with `virtual = true`?

**Comment by zanieb** [comment]
I presume there'd be a spec-compliant `[project]` table?

**Comment by konstin** [comment]
The `[project]` is for specifying the (core) metadata of a distribution, but a virtual workspace is not a distribution. Through the `dynamic` mechanism, just specifying `name` and `version` for a `[project]` implies specifying the other metadata such as dependencies, too.

**Comment by charliermarsh** [comment]
We did this (`package = false`).
