### ISSUE TITLE
Bug: wrong ordering with `@commitID` and `#subdirectory` after `uv pip compile`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#4037]
We have a package installed from GitHub private repo in a `requirements.in`:

```none
foo @ git+ssh://git@github.com/org/foo.git
```

This `foo` package depends on another GitHub private repo (that is not listed in `requirements.in`) called `spam`. Coincidentally, `spam` is in a subdirectory, so you have to specify `#subdirectory=spam`.

Running `uv pip compile requirements.in -o requirements.txt` with `uv==0.2.5`, it outputs this:

```none
foo @ git+ssh://git@github.com/org/foo.git@abc123
    # via -r requirements.in
spam @ git+ssh://git@github.com/org/spam.git#subdirectory=spam@def456
    # via foo
```

This _almost_ was perfect, except for the fact that `spam @ git+ssh://git@github.com/org/spam.git#subdirectory=spam@def456` is not valid, per the ordering of `#subdirectory` and `@commitID`.

Thus, the bug is that `#subdirectory=spam` needs to come after `@def445`.

Reference: https://pip.pypa.io/en/stable/topics/vcs-support/#git

**Comment by charliermarsh** [comment]
Thanks.

**Comment by charliermarsh** [comment]
This looks like a bug in `apply_redirect`.

**Comment by charliermarsh** [comment]
I will fix tomorrow, thanks.
