### ISSUE TITLE
Need an alias for `uv pip`

### ISSUE THREAD

**Issue by itsmeadarsh2008** [astral-sh/uv#4039]
I think adding an alias `uvp` for the name `uv pip` is a great idea. It would make the name easier to remember and type, especially for those who frequently use the tool. Plus, it can help to streamline commands and make the overall user experience more efficient. Overall, adding an alias like `uvp` for `uv pip` seems like a simple yet effective way to improve usability.

**Comment by zanieb** [comment]
Hi! I think we're leaning away from this kind of alias. Is there a reason a shell alias e.g. `alias uvp="uv pip"` won't work for you? 

There's a bunch more discussion over in #1899.
