### ISSUE TITLE
Locking depends on the current python version if `requires-python` isn't set

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4050]
Locking dependencies with `uv lock` or `uv run` depends on the current python version when no explicit `requires-python` is given:

```
[project]
name = "albatross"
version = "0.1.0"
dependencies = ["numpy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

This resolves different numpy versions with `uv venv -p 3.8 && uv run --preview` vs. `uv venv -p 3.12 && uv run --preview`, since the latest numpy versions don't support python 3.8.

When the lockfile is committed to git, it means that each invocation by a developer with a different default python version will create lockfile diff, and it destroy the shared environment promise of lockfiles.

Poetry and pdm both generate a `require-python` or `Python` entry by default. When this entry is removed, they enforce compatibility with all python versions. pdm complains about this when backtracking and backtracks to 1.21.1, poetry silently backtracks to 1.16.6.

**Comment by zanieb** [comment]
I'm not sure this is a "bug" but yeah we might want to change it. I'm not particularly opposed to the behavior, although a warning may make sense.

**Comment by charliermarsh** [comment]
Yeah I actually think the current behavior is reasonable though I know it could be a footgun for users.

**Comment by konstin** [comment]
You can turn this into a bug easily:

```
uv venv -p 3.12 && uv lock --preview
uv venv -p 3.8 && uv sync
```

This ignores the `requires-python: ">=3.9"` bound on `numpy-1.26.4.tar.gz` and errors with:

```
meson-python: error: Package requires Python version >=3.9, running on 3.8.18
```

**Comment by zanieb** [comment]
Do we not encode the Python version range in the lock file and error if it cannot be fulfilled? That sounds like a separate issue from whatever we default to using.

**Comment by konstin** [comment]
We currently don't, but picking a default range and adding it to the lockfile would be one solution. Others are:
* Make specifying `requires-python` mandatory
* Warn when `requires-python` is missing (any behavior after, users have been warned)
* Pick a default `requires-python` range, say all non-EOL python versions
* Assume all python versions (poetry seems to do this)
There might be more solutions, they work as long as we get a consistent range no matter from what python we invoke the locking.

**Comment by charliermarsh** [comment]
Adding the Python requirement to the lockfile seems important yeah.

**Comment by zanieb** [comment]
I created a separate issue for that problem at #4052 

I think warning that `requires-python` is missing and requiring the current minor version seems pretty decent?

I think it's totally normal for an "application"-style project to just rely on the current Python version being consistent.

**Comment by charliermarsh** [comment]
@konstin - are you planning to do this or should I take it?

**Comment by konstin** [comment]
I'm not certain yet which options of those is the right one, you can take it

**Comment by charliermarsh** [comment]
In https://github.com/astral-sh/uv/pull/4070, I made it such that if `requires-python` is missing, we warn and use the current minor as a minimum version.
