### ISSUE TITLE
Feature Request: Allow `--no-binary` for `uv pip compile`

### ISSUE THREAD

**Issue by notatallshaw-gts** [astral-sh/uv#4064]
This request is based on my use case here https://github.com/astral-sh/uv/issues/4063

Basically. I want to "allow list" sdists for a small number of packages for `uv pip compile`, the request in https://github.com/astral-sh/uv/issues/4063 suggests to be able to use `--no-binary` to do this, but `--no-binary` isn't currently supported by `uv pip compile`.

If a different solution or method is suggested for this use case, then this request is defunct.

**Comment by zanieb** [comment]
Should be a straight-forward change to copy it over.

**Comment by charliermarsh** [comment]
Yeah we can add this.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/4301.
