### ISSUE TITLE
Issue with `uv@0.2.7` in Dockerfile + venv

### ISSUE THREAD

**Issue by omarish** [astral-sh/uv#4072]
I think I've encountered an issue related to (I believe) virtualenv detection when using uv in a dockerfile. Specifically, I noticed that my company's CI started failing on all images that rely on uv.

For reference, here is the dockerfile:

```dockerfile
# syntax = docker/dockerfile:1.0-experimental

# Base image
FROM python:3.12.2 as build
RUN apt-get update && apt-get install -y build-essential curl libpq-dev
ENV VIRTUAL_ENV=/opt/venv \
  PATH="/opt/venv/bin:$PATH"

ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh
COPY ./packages/waldo-db-proxy/requirements.txt .
RUN /root/.cargo/bin/uv venv /opt/venv && \
  /root/.cargo/bin/uv pip install --no-cache -r requirements.txt

# App image
FROM python:3.12.2-slim-bookworm
RUN apt-get update && apt-get install -y build-essential curl libpq-dev
COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app
COPY  ./packages/waldo-db-proxy ./
EXPOSE  5432
CMD [ "python", "-m", "app", "start" ]
```

This started failing universally this morning.

I hopped in to a partial image (before this line that activates the venv `RUN /root/.cargo/bin/uv venv /opt/venv`), and found that it was running uv@0.2.7.

This image works without issue when I replace `https://astral.sh/uv/install.sh` with `https://github.com/astral-sh/uv/releases/download/0.2.6/uv-installer.sh`.

I haven't had time to further debug, but just wanted to raise this issue in case others are trying to debug.

Edit: it seems to fail at this step on 0.2.7:

```sh
 > [build 6/6] RUN /root/.cargo/bin/uv venv /opt/venv &&   /root/.cargo/bin/uv pip install --no-cache -r requirements.txt:
#19 0.100   × failed to canonicalize path `/opt/venv/bin/python3`
#19 0.100   ╰─▶ No such file or directory (os error 2)
```

**Comment by charliermarsh** [comment]
FWIW, you can also use `https://astral.sh/uv/0.2.6/install.sh` as the installer link.

**Comment by charliermarsh** [comment]
Can you share any more on what is failing?

**Comment by charliermarsh** [comment]
Modifying the Dockerfile a bit, I eventually get:

```
 > [build 6/6] RUN /root/.cargo/bin/uv venv /opt/venv &&   /root/.cargo/bin/uv pip install --no-cache -r requirements.txt:
#19 0.100   × failed to canonicalize path `/opt/venv/bin/python3`
#19 0.100   ╰─▶ No such file or directory (os error 2)
```

Does that look familiar?

**Comment by omarish** [comment]
Sorry for not posting that in the original issue. Yes, that's the issue I ran into using 0.2.7.

**Comment by zanieb** [comment]
Thanks! We'll have a fix out shortly.

**Comment by omarish** [comment]
That was fast! Thank you.

**Comment by zanieb** [comment]
The release should be out now. Let us know if you run into any more problems :)
