### ISSUE TITLE
Avoid redundant enumeration of all package versions during solve failure

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4075]
```
error: Because the current Python version (3.9.6) does not satisfy Python>=3.11,<4.0 and all versions of rooster-blue depend on Python>=3.11,<4.0, we can conclude that all versions of rooster-blue cannot be used.
And because only the following versions of rooster-blue are available:
    rooster-blue==0.0.1
    rooster-blue==0.0.2
    rooster-blue==0.0.3
    rooster-blue==0.0.4
and you require rooster-blue, we can conclude that the requirements are unsatisfiable.
```

There's no reason for this message to be so verbose. We already said all versions of rooster-blue cannot be used. The conclusion could be:

```
And because you require rooster-blue, we can conclude that the requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
How would you go about solving this?

**Comment by zanieb** [comment]
I'm not sure. I think the latter half comes from

https://github.com/astral-sh/uv/blob/57ea55d2185213236e68fef82135f1cfc1686043/crates/uv-resolver/src/pubgrub/report.rs#L280-L293

which doesn't have a obvious way to inspect that we previously concluded that "all versions cannot be used".

Maybe we don't need to know that we said that previously and instead we should just have better handling at

https://github.com/astral-sh/uv/blob/57ea55d2185213236e68fef82135f1cfc1686043/crates/uv-resolver/src/pubgrub/report.rs#L92-L99

and collapse that to "all versions" when we see we're enumerating all of the available versions
