### ISSUE TITLE
Support directories passed via --index-url

### ISSUE THREAD

**Issue by ericmarkmartin** [astral-sh/uv#4078]
The pip install docs say the following `--index-url` (emphasis mine)

> This should point to a repository compliant with PEP 503 ... _or a local directory laid out in the same format_

Empirically, pip install does work with either a path passed in for `--index-url` (though in this case it warns about the lack of scheme) or a file-scheme url.

Currently, when passed a directory for `--index-url`, `uv` complains about it being a `relative URL without a base`. When passed a file scheme url, it encounters a reqwest error in the request builder: `URL scheme is not allowed`.

Given that pip warns when given a naked directory, it seems okay to not support this, but I have a use case that would benefit from support for the file scheme urls.

**Comment by charliermarsh** [comment]
What is the advantage of using `--index-url` over `--find-links` for searching from a local directory?

**Comment by ericmarkmartin** [comment]
I'll also note that I'm happy to work on a patch if folks think this would be okay to add, but I might need a bit of guidance. I'm aware that uv supports installation of requirements specified with file scheme urls, but I'm new to this codebase and could probably benefit from some pointers on how to leverage that code.

**Comment by ericmarkmartin** [comment]
> What is the advantage of using `--index-url` over `--find-links` for searching from a local directory?

As I understand it, `--find-links` only works for a flat index, so the distributions would have to be immediate descendants of whatever path you pass.

> If a path, the target must be a directory that contains package as wheel files (`.whl`) or source distributions (`.tar.gz` or `.zip`) at the top level.

I want to be able to pass a parent directory of this, e.g. `foo` where `foo/numpy` holds `numpy` wheels.

**Comment by charliermarsh** [comment]
Why is it important, though, that you can pass in a parent directory with HTML files, rather than dumping the artifacts into a flat directory? I'm just trying to understand why it's necessary to support before committing to it.

FWIW it seems reasonable to support, but it kinda depends on how much complexity it adds.

**Comment by AbaoFromCUG** [comment]
> Why is it important, though, that you can pass in a parent directory with HTML files, rather than dumping the artifacts into a flat directory? I'm just trying to understand why it's necessary to support before committing to it.但是，为什么传递包含 HTML 文件的父目录而不是将工件转储到平面目录中很重要呢？我只是想理解为什么在承诺之前需要支持。
> 
> FWIW it seems reasonable to support, but it kinda depends on how much complexity it adds.FWIW 支持似乎是合理的，但这有点取决于它增加了多少复杂性。

I have the same question. I'm also curious about the reason behind this design. My directory doesn't contain an index.html.
Why  should we create an index.html inside the directory.  In my opinion,   a naked directory is enough.

Are there any tools that can help me generate index.html?

# My case
I have some wheels, I want to generate requirements.txt with
```shell
uv pip compile  -o requirements.txt --default-index=/path/to/wheels  requirements.in 
```
```
/path/to/wheels/
               - a
                 - a-1.0.0.whl
                 - a-2.0.0.whl
               - b
                 - b-1.0.0.whl
                 - b-2.0.0.whl

```
