### ISSUE TITLE
A path dependency is incompatible with the current platform

### ISSUE THREAD

**Issue by henryiii** [astral-sh/uv#4088]
I'm running into `error: Failed to determine installation plan Caused by: A path dependency is incompatible with the current platform` when trying to use uv in cibuildwheel for macOS and Windows wheels (Linux is fine).

Windows fails right away with `deflate-0.8.0-cp38-cp38-win32.whl`; I'd speculate it might be a 32-bit Windows issue.

MacOS Intel is fine for CPython 3.8-3.10 then 3.11 fails on `deflate-0.8.0-cp311-abi3-macosx_10_9_x86_64.whl`. 3.8-3.10 were not ABI3 wheels in this case, though, so it seems to be the ABI3 wheel.

MacOS ARM dies sooner, on `deflate-0.8.0-cp39-cp39-macosx_11_0_arm64.whl`, which is the first tested wheel (3.8 can't be tested on ARM since we use the Intel CPython install).

This might be a regression, as I know the Windows one worked a week or two ago.

**Comment by henryiii** [comment]
I might be using the wrong Python when setting up the venv, let me reopen if I pin it down to uv again.

**Comment by henryiii** [comment]
Adding `--python=Python` when making the venv seems to have fixed it.

**Comment by munechika-koyo** [comment]
I also saw the above error in building virtual env at test phase:
```
uv venv /private/var/folders/t8/r_s4tkhn46g6y0d15z25l36c0000gn/T/cibw-run-zf_mu_np/cp310-macosx_x86_64/venv-test-x86_64 --python=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
```

@henryiii Could you please tell me how you configured `--python` argument in the setup file (e.g. pyproject.toml)?

**Comment by henryiii** [comment]
You are hardcoding a minimum macOS target of macOS 14 but trying to build on macOS 13.
