### ISSUE TITLE
constraints not respected by `uv pip compile`

### ISSUE THREAD

**Issue by iisakkirotko** [astral-sh/uv#4091]
If I run `uv pip compile req.txt -c constraints.txt`, with the two files having the following content:

req.txt
```
solara[extra]
```
where `pillow`'s version is not restricted at all in solara-ui's dependencies

constraints.txt
```
pillow==10.0.0
```

`uv` resolves
```
...
pillow==10.3.0
    # via
    #   -c constraints.txt
    #   solara-ui
...
```

despite the fact that the version should be constrained to 10.0.0.

This happens on `uv` versions 0.2.7 and 0.2.8, but versions <= 0.2.6 work as expected.

**Comment by charliermarsh** [comment]
Thanks, not immediately obvious to me what changed but I'll fix and release it today.
