### ISSUE TITLE
No build isolation option for bluejay commands

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4103]
Locking huggingface currently fails because it depends on [natten](https://pypi.org/project/natten/) which only hast source dists and can only be built without build isolation. `uv run`, `uv lock` and `uv sync` should support a `--no-build-isolation` flag.

**Comment by zanieb** [comment]
Is there an alternative design for `--no-build-isolation` we should consider? Like specifying extra build dependencies per package? Forcing the user to install build dependencies manually and dropping isolation seems like a bad outcome.

**Comment by charliermarsh** [comment]
It's a good question to ask. Answering it requires understanding why these projects require `--no-build-isolation`. Often, it's because they require PyTorch, and my understanding is that people don't want to require that you reinstall PyTorch independently for each package, or something.

**Comment by charliermarsh** [comment]
(Also note that `--no-build-isolation` doesn't mean that we combine the virtualenv with the build dependencies. It means the build dependencies are entirely ignored, i.e., it's assumed that the virtualenv has everything it needs.)

**Comment by charliermarsh** [comment]
We may want to add this, since we haven't invested time in an alternative design yet.
