### ISSUE TITLE
pyproject defined override dependencies  ignored by uv lock and uv sync

### ISSUE THREAD

**Issue by idlsoft** [astral-sh/uv#4108]
It looks like `uv pip install` and `uv pip compile` read 
```
[tool.uv]
override-dependencies = ...
```
from `pyproject.toml` but `uv lock` and `uv sync` don't.

Is that intentional?

**Comment by zanieb** [comment]
Worth noting that we may want to explore a different syntax before supporting this in the new API cc @konstin

**Comment by zanieb** [comment]
I don't have a specific request, just voicing that we should consider if we want something else (as noted by @charliermarsh)
