### ISSUE TITLE
`uv pip sync` should maybe have a `--no-remove` flag?

### ISSUE THREAD

**Issue by thejcannon** [astral-sh/uv#4113]
👋 Howdy!

At $work we use a global lockfile to manage dependencies, so `uv pip sync` naturally is a great fit for keeping the transient environment up-to-date with regard to the lockfile as we travel forward and backwards in time (via git ops).

_However_, we also support people installing certain dependencies for one-off tooling or prototyping and I'd hate to tell them to run `uv pip sync` and those deps dissapear.

I understand that havign some kind of `--no-remove` flag is likely not _truly_ what we want (because the env will maybe become bloated over time, or maybe there's conflicting deps, or maybe we're leaving a dep with a security concern) but I think it handles the use-case well-enough that it's worth trying out.

**Comment by zanieb** [comment]
What if we have other ways to managing one-off tooling and prototyping? e.g. `uv tool` (#3560) or `uv run --with <one-off-package>`?

**Comment by thejcannon** [comment]
I expected this answer 😄 I'd love to see those. I'm not 100% certain I'd be able to convince all of the folks I support (some of which aren't engineers, and don't know what `uv` is, or that it's used under the hood for our common tooling) to always use the totally-awesome-`uv`-thing.

**Comment by charliermarsh** [comment]
I think `pip install --no-deps` will... basically do what you want? Internally it's like, exactly this.

**Comment by zanieb** [comment]
We'll probably expose something like this, it was in our original designs. I'm just curious to see how far we can get without exposing it by, e.g., building better APIs and want to learn more about the stories behind it. Centrally managing environment state seems like a fair use case, especially if the downstream users have access to `pip`. You could still definitely break their environment with a sync operation though (or the sync could fail).

**Comment by charliermarsh** [comment]
To be clear, I meant `uv pip install --no-deps`.

**Comment by thejcannon** [comment]
Oh...... yeeeeeaaaaaaahhhh I think you're right 🤦
