### ISSUE TITLE
Setuptools is installed conditionally when it should be installed unconditionally

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4137]
Resolving this [pyproject.toml](https://gist.github.com/konstin/365b137c572a718e342b6635e49840fa) (needs minification) with `uv lock` on ubuntu, i get this [uv.lock](https://gist.github.com/konstin/90a99e5911e30b0cc90a681de71ca91a). If i `uv sync` it, it installs `pyramid`, but not setuptools, even though pyramid depends on setuptools. This does not happen if `pyramid` is the sole dependency.

**Comment by charliermarsh** [comment]
I can take this one later, unless someone beats me to it. Very weird, good bug!

**Comment by charliermarsh** [comment]
I can't reproduce -- it does install setuptools for me.

**Comment by charliermarsh** [comment]
Ah ok. You need to use Python < 3.12.

**Comment by charliermarsh** [comment]
It's the same as https://github.com/astral-sh/uv/issues/4125.
