### ISSUE TITLE
Packages without source dists break universal resolver

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4139]
Consider a project with one of the following requirements, where the host linux and `tensorflow-macos` has only mac os wheels and no source dist, i.e. it is only installable on mac os. 
1. `tensorflow-macos==2.16.1`
2. `tensorflow-macos==2.16.1; platform_system == "Darwin"`
3. `tensorflow-macos==2.16.1; platform_system == "Linux"`

Option 1 currently fails:

```
  x No solution found when resolving dependencies:
  `-> Because the requested Python version (>=3.8) does not satisfy Python>=3.9 and tensorflow-macos==2.16.1 depends on Python>=3.9, we can conclude that
      tensorflow-macos==2.16.1 cannot be used.
      And because foo==1.0.0 depends on tensorflow-macos==2.16.1, we can conclude that foo==1.0.0 cannot be used.
      And because only foo==1.0.0 is available and foo depends on foo, we can conclude that the requirements are unsatisfiable.

      hint: The `Requires-Python` requirement (>=3.8) defined in your `pyproject.toml` includes Python versions that are not supported by your dependencies (e.g.,        
      tensorflow-macos==2.16.1 only supports >=3.9). Consider using a more restrictive `Requires-Python` requirement (like >=3.9).
```

So does option 2 and 3:
```
  x No solution found when resolving dependencies:
  `-> Because the requested Python version (>=3.8) does not satisfy Python>=3.9 and tensorflow-macos{platform_system == 'Darwin'}==2.16.1 depends on Python>=3.9, we can
      conclude that tensorflow-macos{platform_system == 'Darwin'}==2.16.1 cannot be used.
      And because foo==1.0.0 depends on tensorflow-macos{platform_system == 'Darwin'}==2.16.1, we can conclude that foo==1.0.0 cannot be used.
      And because only foo==1.0.0 is available and foo depends on foo, we can conclude that the requirements are unsatisfiable.

      hint: The `Requires-Python` requirement (>=3.8) defined in your `pyproject.toml` includes Python versions that are not supported by your dependencies (e.g.,        
      tensorflow-macos{platform_system == 'Darwin'}==2.16.1 only supports >=3.9). Consider using a more restrictive `Requires-Python` requirement (like >=3.9).
```

Option 1 failing on linux is fine, unless we require that a non-installing target should be able to lock. Option 2 failing is a problem: This is a mac-only dep, it should not break linux or universal wheels! We know that there a wheels that work on macos, so the macos side of things should resolve. Option 3 failing could be considered a feature, because this can never install (there is no platform that is both a linux system and supports mac tags).

One option at solving this would be dropping the solve time tag check and doing only an install time check. This would remove backpropagation from wheels with unsupported to wheels with supported tags, otoh tags are usually not a version-to-version difference in that different version support different tags but a per-package property where certain packages are platform specific, such as tensorflow-macos is mac os only and pywin32 is windows only (and doesn't build on linux).

**Comment by charliermarsh** [comment]
I think the only option really is to ignore tags are solve time.

**Comment by konstin** [comment]
I'm pretty sure that's what poetry does too

**Comment by charliermarsh** [comment]
I can give it a shot.

**Comment by charliermarsh** [comment]
I think there's a possible improvement here, like... if we know we're in a branch that only supports macOS, ensure that there's _at least one_ macOS-compliant wheel. But I don't know how to formalize that.
