### ISSUE TITLE
`uv lock` should not create a virtual environment

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4141]
`uv lock` creates a `.venv` directory in my working directory. I do not expect it to need to create a user-facing virtual environment to generate a lock file.

**Comment by charliermarsh** [comment]
We do need a Python interpreter though, because we need to be able to build dependencies.

**Comment by zanieb** [comment]
That's okay we discover the Python interpreter separately. Why do we need to create an environment with it? Don't we create temporary environments for builds?

**Comment by charliermarsh** [comment]
Yes I’m not necessarily disagreeing.
