### ISSUE TITLE
[request] uv pip install -r pyproject.toml[optional_deps]

### ISSUE THREAD

**Issue by gmankab** [astral-sh/uv#4169]
### feature request

i really like `uv pip install -r pyproject.toml` feature, which installs project dependencis but does not installs project iteslf

also there is a support for optional dependences installing with `uv pip install .[optional_deps]`

can you please provide optional dependencies installing when `-r` flag is used, so then i can install project optional dependencies, but not install project itself

idk which syntax would be better for it, maybe something like `uv pip install -r pyproject.toml[optional_deps]`

### why

when i debelop projects i use `uv pip install -r pyproject.toml` to install dependencies for my project

also there is autotests dependences, which only needed to run autotests, and should not be installed on computers of people who don't contribute to the project and don't running autotests

so i want to use uv to install testing dependences to the venv

**Comment by zanieb** [comment]
Hi it sounds like you're looking for the `--extra` flag

```
      --extra <EXTRA>
          Include optional dependencies in the given extra group name; may be provided more than once
```
