### ISSUE TITLE
Socks5 proxy setting and subcommands tab completion.

### ISSUE THREAD

**Issue by hongyi-zhao** [astral-sh/uv#4186]
I'm not sure this tool supports the following features:

1. According to [the document](https://github.com/astral-sh/uv#environment-variables), it seems that only http[s] proxies are supported:

> HTTP_PROXY, HTTPS_PROXY, ALL_PROXY: The proxy to use for all HTTP/HTTPS requests.

So, I would like to know whether it can also support socks5 proxy, say, socks5://127.0.0.1:16668
 
2. Subcommands tab completion.

Regards,
Zhao

**Comment by charliermarsh** [comment]
We do support tab completion. The instructions are basically the same as in Ruff: https://docs.astral.sh/ruff/configuration/#shell-autocompletion.

**Comment by zanieb** [comment]
I don't think we support SOCKS5 at all (we don't have the `reqwest` crate feature turned on). I don't think they support a SOCKS5_PROXY environment variable, but if you're interested in it I'd check in upstream.

**Comment by hongyi-zhao** [comment]
If you are willing to consider, both `SOCKS5` and `SOCKS5H` should be supported.

**Comment by zanieb** [comment]
Can you share more about the use case?

**Comment by hongyi-zhao** [comment]
My native proxy is of type Socks5, and in my specific region, using such a proxy to download dependency packages is more efficient.
