### ISSUE TITLE
Add setting to manage preference for managed toolchains

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4198]
Users should be able to opt in and out of managed toolchains, e.g.

```
managed-toolchains = always | preferred | fallback | never
```

**Comment by zanieb** [comment]
We could also frame this differently, like..

```
toolchain-discovery = prefer-system | prefer-managed | only-system | only-managed
```

**Comment by baggiponte** [comment]
> We could also frame this differently, like..
> 
> ```
> toolchain-discovery = prefer-system | prefer-managed | only-system | only-managed
> ```

What about?

```
toolchains = uv-first | system-first | managed-first | uv-only | system-only | managed-only
```

Or you could explicitly configure python providers like [PDM](https://pdm-project.org/en/latest/usage/config/#configure-the-python-finder). People might (and are) using tools like mise asdf pyenv.

**Comment by zanieb** [comment]
What's the difference between `uv-only` and `managed-only` there?

I don't think we'll support discovery of Python interpreters in _other_ tool's installation directories. It seems more reasonable to just expect them to be registered in the PATH (or, on WIndows, in the registry).

**Comment by baggiponte** [comment]
> What's the difference between `uv-only` and `managed-only` there?
> 
> I don't think we'll support discovery of Python interpreters in _other_ tool's installation directories. It seems more reasonable to just expect them to be registered in the PATH (or, on WIndows, in the registry).

Makes sense, but then I guess what's the difference between `system` python and other tools? In other words, brew python should just not come up, am I correct?

**Comment by zanieb** [comment]
A "system" Python here is any Python toolchain installed on the system i.e. not being managed by uv. Brew Python will come up if it's on the PATH, but we won't try to discover it a Brew-specific location (as we won't, thusfar, attempt to discover `pyenv` Python in their storage directory)

**Comment by delfick** [comment]
It would be useful to be able to tell uv to prefer using asdf/pyenv discovery/installation if that's available rather than only python-build-standalone

**Comment by zanieb** [comment]
This issue is actually completed: https://docs.astral.sh/uv/reference/settings/#python-preference

Feel free to open a new one to track support for other managed Python distribution kinds, but we're pretty unlikely to support more.

**Comment by delfick** [comment]
sure, done https://github.com/astral-sh/uv/issues/7400

Thanks!
