### ISSUE TITLE
failed to open file `/dev/null/uv/uv.toml`

### ISSUE THREAD

**Issue by misery** [astral-sh/uv#4199]
I tried uv in pre-receive hook in gitlab. Seems gitlab misses something here. But it would be nice if uv won't fail anymore.

Tried 0.2.9
```
uv -v venv $VIRTUAL_ENV
 error: failed to open file `/dev/null/uv/uv.toml`
   Caused by: Not a directory (os error 20)
```

**Comment by zanieb** [comment]
Thanks for the report!
