### ISSUE TITLE
Add .gitignore with * as contents to .uv

### ISSUE THREAD

**Issue by njzjz** [astral-sh/uv#4219]
xref: https://github.com/astral-sh/uv/issues/3879#issuecomment-2159292206

This has been done by ruff and many other tools: https://github.com/astral-sh/ruff/issues/204, https://github.com/astral-sh/ruff/pull/208

**Comment by michaelmior** [comment]
Note that this has a subtle problem. Using `*` causes git to ignore the `.gitgnore` file itself! This should more correctly have the contents

```
*
!.gitignore
```
