### ISSUE TITLE
Support for SOCKS5 and SOCKS5H

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4227]
We don't support these but it looks like `reqwest` does so we could.

Prompted in https://github.com/astral-sh/uv/issues/4186

**Comment by hongyi-zhao** [comment]
Do you mean `SOCKSSH` is an alias of `SOCKS5H`, aka, [SOCKS5-hostname](https://everything.curl.dev/usingcurl/proxies/socks.html) used by curl?

**Comment by zanieb** [comment]
The latter, thanks! 🤦‍♀️

**Comment by zanieb** [comment]
Added in #7503
