### ISSUE TITLE
Add command to check if the lock file is up to date with the project metadata

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4264]
e.g. as in `poetry check --lock` (not yet sure why they deprecated `poetry lock --check`)

**Comment by zanieb** [comment]
Some discussion about the `poetry lock --check` change at https://github.com/python-poetry/poetry/pull/8015 and https://github.com/python-poetry/poetry/issues/6756

We ought to have a top-level `uv check` command eventually too but should it do this?

**Comment by asanglard** [comment]
hi

I have the same need here which basically consist to assert that the current uv.lock respects the project metadata without forcing to update the uv.lock file is new version of the dependencies has been released. It should block if it is missing dependencies or it there are none necessary dependencies.

Let me give a concret example of where it could help to assert that the project metadata match to uv.lock file.


**main project**
`pyproject.toml (example)
dependencies = [
"shared_lib", # this is a local lib - monorepo project
"pydantic>=2.4.0,<3.0.0" # it could be any lib
]`

uv.lock is for example locked to pydantic in version 2.5.0


**shared lib** (local project)
`pyproject.toml
dependencies = []`

someone on the project add a dependencies to the shared_lib, let's **foo-lib** but forget to update the uv.lock file of the main project. In the same time, a new version of pydantic has been released (let's say 2.6.0).

The fact that uv.lock does not integrate **foo-lib** is blocking and the main project will be broken. The fact that a new pydantic version has been released is not a blocking issue. By the way, there could be a lot of other dependencies that have been updated and it could be hard to upgrade all these libraries at the same time... we are a bit force to handle all update currently withe `uv sync` command.

In my mind, it would be therefore great to have such command that only check that the project metadata are respected by the uv.lock file without forcing to update all other librairies. The purpose of the command will consist to check that it is no missing dependencies or that there is no necessary dependencies (removal of dep in the shared_lib for example)

Right now, the idea could be to use this command :
`uv sync --frozen --locked` 

It would consist to assert without trying to update the uv.lock file, but this is not supported.

**Comment by asanglard** [comment]
> It's a bit silly, but `uv lock --locked` does that.

I didn't saw initially that `uv lock` does not upgrade the dependencies by default.

So, this usage of the command is a good solution to check that there is no "breaking" changes in the dep (missing dep for example...) and it does not try to upgrade the existing dep.

**Comment by charliermarsh** [comment]
Yeah the locked flag is the intended solution here.

**Comment by hbelmiro** [comment]
I wrote a GitHub action for that. It also validades requirements.txt, if needed. 

https://github.com/hbelmiro/uv-lock-check
