### ISSUE TITLE
Request: Download "official" (vanilla) Python binaries in toolchains

### ISSUE THREAD

**Issue by hoechenberger** [astral-sh/uv#4270]
Hello, I was trying out `toolchain install` and it seems the binaries are pulled from https://github.com/indygreg/python-build-standalone

Now while I have no doubt that these are "clean", it still gives me an uneasy feeling that binaries are being downloaded from a seemingly random place. Would it be possible to provide toolchains based on the official binaries provided by python.org? And if binaries are not available, to download the sources and compile them?

**Comment by zanieb** [comment]
Hi! Sorry this will be clarified in future documentation so it's not a surprise. We use the `python-build-standalone` builds similar to Hatch and Rye. We're collaborators over on that project so they're not random.

The problem with using the official Python builds (as far as I know) is that they are not portable e.g. whether or not the build will work on your machine depends on things outside of our control. We can definitely consider an option for this though and I'd love to hear more discussion about the trade-offs. 

You may also be interested in [PEP 711](https://peps.python.org/pep-0711/).
cc @konstin who might be able to provide some more context on the builds.

**Comment by charliermarsh** [comment]
I started writing this before Zanie replied so I'll just post my perspective.

---

Appreciate the question, a few pieces to this...

First, python.org doesn't provide pre-built redistributable binaries -- they provide source releases. We don't currently plan to facilitate building Python from source -- perhaps that will change in the future. You're of course welcome to use a separate tool if you want to install Python from source, and our tooling will contain to interoperate with those external toolchains. There's no requirement that you use the `uv toolchain` stuff to use uv and that will continue to be true going forward.

Second, we're maintainers on `python-build-standalone`, which compiles Python from the source releases published on python.org. It's become a very popular source of installing Python and is fairly load-bearing in the ecosystem now -- the releases are used tens of millions of times per month, and they're the Python distribution that you get if you use Bazel, Rye, Mise, etc.

**Comment by cbrnr** [comment]
I think as long as you are using build flags identical to those used in the official builds, there shouldn't be any problems. I'm specifically referring to their macOS build, which uses (among other flags) `--enable-framework`, which is important for accessing the macOS GUI.

**Comment by hoechenberger** [comment]
Thank you so much for your swift responses, @zanieb and @charliermarsh 

This sounds all very reasonable. It's good to know you're involved with the upstream project, this helps give me a little peace of mind 😄 

Please feel free to close this issue if you wish!

Have a great day.

**Comment by zanieb** [comment]
> First, python.org doesn't provide pre-built redistributable binaries -- they provide source releases. We don't currently plan to facilitate building Python from source -- perhaps that will change in the future. 

Yeah this is critical point — I second guessed myself due to the prompt :D.

I've considered support for building distributions via [`python-build`](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) from pyenv but even that is also applying patches to the official sources.

Since there aren't official vanilla binaries available, I'll close this as in-actionable for now.

**Comment by hoechenberger** [comment]
@zanieb Sorry for bothering you about this again, but I believe @cbrnr made an important remark above: on macOS, many developers will critically depend on a "framework build". Turns out, the `python-build-standalone` builds do currently not fulfill this requirement:

https://github.com/indygreg/python-build-standalone/issues/274

Just something to be aware of.

**Comment by charliermarsh** [comment]
Make sense, thanks. For now I would consider that a case of “If you need a Framework build, you need to bring your own Python”, similar to other build variants.

**Comment by hoechenberger** [comment]
> For now I would consider that a case of “If you need a Framework build, you need to bring your own Python”, similar to other build variants.

Absolutely! Just wanted to ensure you're aware of this (potential) issue.

Let's see if it will disappear magically by getting resolved upstream in https://github.com/indygreg/python-build-standalone/issues/274 😄

**Comment by john-kurkowski** [comment]
> “If you need a Framework build, you need to bring your own Python”, similar to other build variants.

@charliermarsh is there a link to uv documentation about how to handle other build variants?

**Comment by zanieb** [comment]
You can use `--no-managed-python` to disable managed Python or `UV_PYTHON_PREFERENCE=system` to prefer external installations. I'm not sure if you're asking for more?

Please don't bump old issues in the future.

**Comment by john-kurkowski** [comment]
Sorry! I'll play around with your suggestion. I'll open a new issue or add to the documentation thread if I have further questions.
