### ISSUE TITLE
Marker normalization doesn't collapse non-pre-release ranges

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4272]
We don't recognize that `python_version < "3.7" or python_version >= "3.7"` evaluates to `true` because of our use of min versions to handle pre-releases.

**Comment by charliermarsh** [comment]
Although, it is true that `3.7.0a0` does not match either of these markers.

**Comment by charliermarsh** [comment]
What if we had a rule like... if none of the versions contain pre-release or post-release or dev release or local release, then we use different semantics and ignore those things?

**Comment by dimbleby** [comment]
> Although, it is true that 3.7.0a0 does not match either of these markers.

huh?  `python_version >= "3.7"` matches 3.7.0a0.  

https://peps.python.org/pep-0440/#inclusive-ordered-comparison has no special rules for pre-releases, the match is made just based on the consistent ordering defined at https://peps.python.org/pep-0440/#version-scheme
