### ISSUE TITLE
On Windows 11, it will cause virus error.

### ISSUE THREAD

**Issue by zengqiu** [astral-sh/uv#4300]
Platform: Windows 11
Version: 0.2.11

![ee54a858c44d64a1ce35c12ed544e4a](https://github.com/astral-sh/uv/assets/487040/829d2382-24a8-4223-a05f-38fbcebe214d)
![03a65caaf1148c0dbbc97a7fc78f3f8](https://github.com/astral-sh/uv/assets/487040/2270b7ac-2d48-4787-b35c-69c05ea8ab61)

**Comment by zanieb** [comment]
Sorry there's nothing we can do about these false positives except report it as such e.g. https://github.com/astral-sh/uv/issues/1587
