### ISSUE TITLE
No solution found when resolving dependencies (torch==2.3.1)

### ISSUE THREAD

**Issue by mariomeissner** [astral-sh/uv#4303]
UV Version: `0.2.11`

Code snippet:
```
pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu # works as expected

uv pip install torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu # fails
  × No solution found when resolving dependencies:
  ╰─▶ Because torch==2.3.1 has no wheels are available with a matching Python implementation and you require torch==2.3.1, we can conclude
      that the requirements are unsatisfiable.
```

I saw #4252, #4253 which seemed very much related, but it seems to have been merged and included in the `0.2.11`. However, I am still facing the above issue, so I am guessing there is more to it.

**Comment by FishAlchemist** [comment]
I'm not sure why, but it should work if you use ``2.3.1+cpu`` or don't specify a version.

**Comment by charliermarsh** [comment]
Yeah, you may need to include the local version segment -- there's more detail in the doc that @FishAlchemist linked.

**Comment by mariomeissner** [comment]
Ah, I guess this excerpt covers it:
> If only local versions exist for a package foo at a given version (e.g., 1.2.3+local exists, but 1.2.3 does not), uv pip install foo==1.2.3 will fail, while pip install foo==1.2.3 will resolve to an arbitrary local version.

Adding `+cpu` sounds reasonable, let me proceed with that. Thank you both!
