### ISSUE TITLE
The managed toolchain directory should be robust to concurrent access

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4311]
e.g. fetches should be safe to run concurrently and _reading_ a toolchain should not occur mid-fetch.

I believe we won't already read a toolchain mid-fetch because we download into a temporary directory then rename.

Do we need to lock the toolchain directory when fetching the same version concurrently? Or do we just let the later one overwrite the first?

**Comment by konstin** [comment]
Fixed by https://github.com/astral-sh/uv/pull/4733
