### ISSUE TITLE
How to change and manage python version? 

### ISSUE THREAD

**Issue by takan1** [astral-sh/uv#4320]
I switched from rye recently and with rye, I was able to manage python version with `rye pin`. What's the best way to manage the python versions with uv?

**Comment by zanieb** [comment]
Hi! We don't support pinning Python versions (though we will soon). Are you using our preview project interface (e.g. `uv run`, `uv lock`) or are you using our pip-compatible interface (`uv venv`, `uv pip install`)?

**Comment by takan1** [comment]
@zanieb I'm using `uv venv` and python version addition would be great. I'll keep using rye for now til uv supports it then!

**Comment by zanieb** [comment]
You can do `uv venv --preview --python <version>` and we'll fetch the version for you if we can't find it. There's going to be a setting to configure it soon (#4198).
