### ISSUE TITLE
Support enabling the `--system` flag via an env var?

### ISSUE THREAD

**Issue by hoechenberger** [astral-sh/uv#4338]
Hello, I'm using `uv` in a dev container with a global Python installation (no venv) to keep complexity low. Now, I naturally need to pass the `--system` flag to `uv pip install`. I was wondering if you'd consider adding support for switching this flag on / off via an environment variable (which I could then bake into the container). This would make things a little easier for the users of the container.

**Comment by zanieb** [comment]
Hi! This is already supported via `UV_SYSTEM_PYTHON` ([docs](https://github.com/astral-sh/uv?tab=readme-ov-file#environment-variables)).

**Comment by hoechenberger** [comment]
Oh, I entirely missed that! Sorry about this.
