### ISSUE TITLE
Adding interpreter metadata in debugging logs

### ISSUE THREAD

**Issue by kidrahahjo** [astral-sh/uv#4344]
## Context
Hey guys, I was going through how we compute interpreter information while creating virtual environment. 

## Request
Would it be useful to generate a debug message which prints out the the metadata for the interpreter?

For example, adding this following piece of code here https://github.com/astral-sh/uv/blob/main/crates/uv/src/commands/venv.rs#L129 
```rs
debug!("Using the following metadata for the interpreter. {:?}", interpreter)
```

## Rationale
Users when reporting issues on github could just paste that piece of information in the description so that it would get easier for the contributors to debug & support.

**Comment by kidrahahjo** [comment]
If this sounds like a good to have, I will be happy to take this up :)

**Comment by zanieb** [comment]
Hi! Which metadata do you think would be useful in particular? I don't think we want to dump the debug representation of a struct as a general rule.

**Comment by kidrahahjo** [comment]
The contents which would be useful can include platform metadata, which we have access to in `markers`. To avoid printing the debug representation of debug, do you think it would be a good idea to create a public repr function (probably with a better name)?

**Comment by zanieb** [comment]
Maybe. I'm pretty hesitant to add more output without a compelling case of "this would have helped me solve a bug". We haven't really had problems with not knowing the interpreter platform markers in bug reports.

**Comment by kidrahahjo** [comment]
Hmm that's a valid point. I guess if something comes up, it would help us know what's required and we could log that accordingly. I will close this one for now.

Thanks @zanieb

**Comment by zanieb** [comment]
Thank you! Appreciate that you're interested in improving it though.
