### ISSUE TITLE
`uv lock` doesn't indicate that it has updated the lock file

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4346]
The output is just "Resolved ... packages in ...", maybe we should indicate that we've updated the file or locked dependencies?

Even the verbose output doesn't show any indication of updating the lock file.

**Comment by zanieb** [comment]
It'd probably be nice to know if the file was left unchanged or if we updated it.

**Comment by kidrahahjo** [comment]
I agree. Would it also make sense to give a brief description of what changed (it can be enabled by default and users would be able to disable it using a `--no-summary` flag)? 

The output command can be
|  package | old version  | new version  | action
|---|---|---|---|
| xyz |   | 1.0.0  | ADDED |
| abc  |  0.0.1 |   | DELETED |
|  efg |  0.1.0 | 0.1.1  | UPDATED  |

Although this has a downside of a huge output on initial lock creation (and probably more things). Apart from this, for a usual development workflow, teams can always check the diff to see what has changed.

**Comment by zanieb** [comment]
Cargo has a nice example here

```

Updating lockfile...
    Updating uv v0.2.11 (/Users/zb/workspace/uv/crates/uv) -> v0.2.12
    Updating uv-version v0.2.11 (/Users/zb/workspace/uv/crates/uv-version) -> v0.2.12
note: pass `--verbose` to see 102 unchanged dependencies behind latest
```

**Comment by zanieb** [comment]
We have a tracking issue for that at https://github.com/astral-sh/uv/issues/1569, we need to do quite a bit of work around our tracing output levels eventually it's just not as high of a priority as the rest of the interface right now.
