### ISSUE TITLE
Should `uv sync` remove extraneous packages?

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#4358]
[It currently does not](https://github.com/astral-sh/uv/blob/67f1285ce3f00840e1833e4aa5a7e6480e94e489/crates/uv/src/commands/project/sync.rs#L191), while `uv pip sync` does. This would also affect whether `uv remove` removes *all* extraneous packages, or has to do extra work to only remove the affected packages.

**Comment by ibraheemdev** [comment]
`uv sync` now removes extraneous packages by default, which you can opt-out with `--no-clean`.

Currently `uv add` and `uv run` do not ever remove from the environment, and so `uv remove` should, for consistency, only remove the affected packages. An alternative approach to 3 is to have all project commands, `uv run`, `uv add`, and `uv remove`, always clean the virtual environment, which would simplify things and doesn't seem necessarily problematic.

**Comment by zanieb** [comment]
I don't think they should always clean the virtual environment. I think it's too common for people to manually manage packages in Python and without an explicit sync it seems excessive for us to purge extraneous packages. Changing remove to be more clearly scoped by default seems like a more intuitive user experience.

**Comment by charliermarsh** [comment]
> Update uv remove to allow extraneous packages by default, only removing the relevant dependency tree

Does this mean: `uv remove foo` uninstalls `foo`, or uninstalls `foo` and its dependencies?

**Comment by charliermarsh** [comment]
My current vote is that it uses the same semantics as `uv run`, and we add an `--exact` argument to enable exact syncing. But I would also be okay shipping with the current behavior.

**Comment by zanieb** [comment]
I think we made a decision on this — we have a toggle now.

**Comment by aberres** [comment]
For anyone coming here after not finding the switch when looking at `--help`: It is called `--inexact`.
