### ISSUE TITLE
uv toolchain python not in interpreter search path

### ISSUE THREAD

**Issue by fynnsu** [astral-sh/uv#4397]
Thank you for implementing the `uv toolchain` functionality, it's a very helpful feature.

That being said, I noticed a couple sharp edges when trying it out, the main one being that the installed interpreters are not found by `uv venv --python `.

```
❯ uv toolchain list
warning: `uv toolchain list` is experimental and may change without warning.
...
cpython-3.8.19-linux-x86_64-gnu /home/fynnsu/.local/share/uv/toolchains/cpython-3.8.19-linux-x86_64-gnu/install/bin/python3
...

❯ uv venv -p 3.8
  × No interpreter found for Python 3.8 in search path

❯ uv venv -p cpython-3.8.19-linux-x86_64-gnu
  × No interpreter found key cpython-3.8.19-linux-x86_64-gnu in search path

❯ uv venv -p /home/fynnsu/.local/share/uv/toolchains/cpython-3.8.19-linux-x86_64-gnu/install/bin/python3
Using Python 3.8.19 interpreter at: /home/fynnsu/.local/share/uv/toolchains/cpython-3.8.19-linux-x86_64-gnu/install/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
```

Presumably, they would be found if I added `/home/fynnsu/.local/share/uv/toolchains/` to my path but this seems like something that should work without doing so.

The other small thing I would mention is I initially tried `uv toolchain install py38` and `cp38` before eventually working out that I needed `3.8` or `cpython3.8`. It would be helpful if there was a recommended format, either in the error message or the subcommand help.

**Comment by zanieb** [comment]
We discover managed toolchains in `uv venv` with the `--preview` flag. It's not available by default yet because the behavior is still experimental. You can also globally opt in with `UV_PREVIEW=1` if you're using our preview features in general, this will drop the nag from preview commands like `uv toolchain`.

> The other small thing I would mention is I initially tried uv toolchain install py38 and cp38 before eventually working out that I needed 3.8 or cpython3.8.

Interesting. We're working on more documentation around this, but we could also add support for that syntax. What's that based on?

**Comment by fynnsu** [comment]
> Interesting. We're working on more documentation around this, but we could also add support for that syntax. What's that based on?

Hmm not entirely sure where I got this from. I think the `cp38` is likely from python package name conventions (ex. https://download.pytorch.org/whl/test/torch/)

I also think `py38` is a fairly common way to refer to python versions. A notable example of this being the `ruff` config settings: https://docs.astral.sh/ruff/settings/#target-version.

**Comment by zanieb** [comment]
Ah like wheel platform compatibility tags: https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/

Yeah we can support that. Tracking at https://github.com/astral-sh/uv/issues/4399

**Comment by zanieb** [comment]
And we'll track the documentation request at https://github.com/astral-sh/uv/issues/4400

**Comment by fynnsu** [comment]
> Ah like wheel platform compatibility tags: https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/

Yes exactly, thanks

**Comment by zanieb** [comment]
And https://github.com/astral-sh/uv/issues/4401 :)
