### ISSUE TITLE
Unable to release due to PyPI project size limits

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4432]
As previously encountered in Ruff https://github.com/astral-sh/ruff/issues/2136, we've reached the default project size limit on PyPI.

Unfortunately this was encountered in the middle of the 0.2.14 release, which is now _partially_ available. We're determining the next steps for that release, as only the `macOS 10.12+ x86-64` and `armv6l` wheels are uploaded (and no source distribution).

We'll be requesting a size increase and reporting progress here. Thanks!

**Comment by zanieb** [comment]
The size increase can be followed at https://github.com/pypi/support/issues/4260

**Comment by zanieb** [comment]
I've made the decision to yank 0.2.14 from PyPI. I do not believe any other artifacts are available and verified that our self-update and standalone installer both pull 0.2.13 still.

**Comment by zanieb** [comment]
I've noticed the [Docker image](https://github.com/astral-sh/uv/pkgs/container/uv) is available at 0.2.14 but I do not intend to remove it.

**Comment by charliermarsh** [comment]
Limit has been raised: https://github.com/pypi/support/issues/4260. Thanks @zanieb for initiating and to PyPI for the increase!
