### ISSUE TITLE
`uv pip tree` improvement

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#4439]
Some additional features that did not land as part of https://github.com/astral-sh/uv/pull/3859:
- [ ] Proper handling of extras
- [x] `--no-dedupe` (https://github.com/astral-sh/uv/pull/4449)
- [x] `--prune` and `--depth` (https://github.com/astral-sh/uv/pull/4440)
- [ ] `--package` (https://github.com/astral-sh/uv/pull/4655)
- [x] `--invert` (https://github.com/astral-sh/uv/pull/4621)
- [ ] Machine readable output (e.g. JSON with `-j`)

**Comment by zanieb** [comment]
Can you create specific issues for each of these so we can track contributions easier?

**Comment by ChannyClaus** [comment]
how would `--no-dedupe` and the current behavior for printing out dependency cycles would interact? wouldn't it end up with an infinite loop?

**Comment by zanieb** [comment]
We would need to deduplicate cycles still, but we can show anything that's not a cycle.

**Comment by ChannyClaus** [comment]
should we also print `(**)` instead of `(*)` for cyclic dependencies? it may be nice to disambiguate between the regular de-duplication and cyclic dependencies.

**Comment by zanieb** [comment]
If you use `--no-dedupe` we can just use `(*)` still and change the footnote to say it's a cycle. idk if we need to highlight cycles in the default output, sounds hard to read.

**Comment by kdeldycke** [comment]
May I propose to add a machine-readable output like JSON/CSV/Toml/whatever to the list of improvements?

So I can hack `uv pip tree` output to produce a mermaid graph of dependencies (and emulates `pipdeptree --mermaid > dependencies.mmd`)?

**Comment by dsully** [comment]
+1 on adding JSON `-j` to `pipdeptree` and other machine readable outputs. Example output:

```json
[
    ....
    {
        "package": {
            "key": "werkzeug",
            "package_name": "Werkzeug",
            "installed_version": "3.0.3"
        },
        "dependencies": [
            {
                "key": "markupsafe",
                "package_name": "MarkupSafe",
                "installed_version": "2.1.5",
                "required_version": ">=2.1.1"
            }
        ]
    }
]
```

**Comment by Peiffap** [comment]
@zanieb I think this accidentally got closed in #4449; #4440 hasn't been merged yet and contains some of the additional features being asked for (`--depth` and `--prune`).

You might also want to ask about creating follow-up issues for the output flags that were mentioned in comments (`--mermaid`, `-j`, etc.).

**Comment by hauntsaninja** [comment]
I mostly use `pipdeptree` with its `-p / --packages` and `-r / --reverse` flags; I'd love to see `uv pip tree` have equivalent functionality!

**Comment by zanieb** [comment]
We're on the loose with this issue right now — seems to be working fine since @ChannyClaus is just doing them all :)

Please chime in if you're interested in doing any of these improvements though!

**Comment by ChannyClaus** [comment]
oh okay yah i can add those (`--packages` and `--reverse` that is) 🌵 

was going to make a PR for the extras (since this would be a "breaking" change unless it's behind a flag?) once the other flag one merged but maybe i'll just stack them on top of each other or something...

**Comment by zanieb** [comment]
I don't think you need to worry about breaking changes in the text output since it's meant for users to "view".

**Comment by ChannyClaus** [comment]
re: extras, we only want to print the extra name _if and only if_ all packages belonging to that extra are present, right? _i think_ this requires adding some code in https://github.com/astral-sh/uv/blob/bbd59ff455bb52763791f568af7654b7c3da326c/crates/pypi-types/src/metadata.rs#L76 (since `provides_extras` doesn't retain the mapping between the extra and the underlying packages) but wanted to ask in case i'm missing something 😅
