### ISSUE TITLE
`requirements.txt` file issue

### ISSUE THREAD

**Issue by Jayllyz** [astral-sh/uv#4447]
uv version : 0.2.13

<img width="668" alt="image" src="https://github.com/astral-sh/uv/assets/16305216/4d4550b8-b991-4024-b473-e7d8fd672a45">

To reproduce : 

```bash

uv pip install pyqt5
uv pip freeze | uv pip compile - -o requirements.txt
```

The file generated : 
```txt 
# This file was autogenerated by uv via the following command:
#    uv pip compile - -o requirements.txt
pyqt5==5.15.10
pyqt5-qt5==5.15.14
    # via pyqt5
pyqt5-sip==12.13.0
    # via pyqt5
```

**Comment by zanieb** [comment]
Are you installing on a different machine / platform than you generated the requirements file on?

**Comment by Jayllyz** [comment]
Yes, does it change the requirements file result ?

**Comment by zanieb** [comment]
Yeah `pip compile` / `requirements.txt` does not encode a multi-platform resolution, the resolution is for the platform that it was created on. Hence, at runtime, you get this error that there is not a wheel with a matching platform.

We do support running resolution for alternative platforms, you can see the [documentation](https://github.com/astral-sh/uv?tab=readme-ov-file#multi-platform-resolution) for more details.

We're working on universal resolution with a `uv lock` command: https://github.com/astral-sh/uv/issues/3347

**Comment by Jayllyz** [comment]
Thanks for the information
