### ISSUE TITLE
Order of settings in CLI `help` is not intuitive

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4454]
For some reason, `quiet` and `verbose` are randomly in the middle (and non-consecutive).

**Comment by zanieb** [comment]
The help menu is also generally way more verbose than I need. I end up seeing options that are very advanced. I wonder if there's anything to be done about that?

**Comment by charliermarsh** [comment]
@zanieb - Did this also get fixed, by chance?

**Comment by zanieb** [comment]
Nope. I'll take care of it though.

**Comment by zanieb** [comment]
I did this now
