### ISSUE TITLE
slowish `uv lock` on pydantic

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#4473]
To reproduce:

```
$ git clone https://github.com/pydantic/pydantic
$ <edit pyproject.toml to copy [tool.pdm.dev-dependencies] section to existing [project.optional-dependencies] section>
$ hyperfine -w1 --prepare 'rm uv.lock' 'UV_PREVIEW=1 uv lock'
```

Some light profiling shows a lot of time being spent in `_PvEval_EvalFrameDefault`. This seems to happen even when running `uv lock` without `rm uv.lock`, although it is about 2x faster when not removing the lock file. I think perhaps there is some kind of caching problem that is unnecessarily leading to rebuilding.

**Comment by charliermarsh** [comment]
About 150ms is spent getting the project dependencies (since it uses dynamic metadata). But the main reason it's slow is because we have to do Git lookups every time. I think that's just unavoidable, unless we're content with using stale refs.

**Comment by charliermarsh** [comment]
With #4482 and #4487, I now get 506ms for `rm uv.lock && uv lock` and 224ms for `uv lock`.

Prior to those PRs, I get 921ms for `rm uv.lock && uv lock` and 452ms for `uv lock`.
