### ISSUE TITLE
[Feature Request] pyproject.toml validation?

### ISSUE THREAD

**Issue by charlesnicholson** [astral-sh/uv#4477]
I don't know if this is a FR for uv or ruff or neither- Our python tools are under CI for unit tests and ruff linting, but because they do complex work with IoT devices, don't get as much functional testing love as they deserve (it's very complicated to orchestrate).

Because of this, it's often the case that we forget to update our package dependencies in our per-project pyproject.toml files. We don't notice this locally because all of our packages are editably-installed into our venv, so all of our imports always work.

I broke our users (internal-only, mercifully) _again_ today because I forgot to update a pyproject.toml file when moving some code between packages. I stumbled across https://github.com/fpgmaas/deptry which validates pyproject.toml files, which includes a source code parser that reconciles import statements against the dependencies listed in pyproject.toml. If your Python code imports and uses a package that isn't listed in your pyproject.toml, it raises an error.

Tooling like this feels like a huge win for the Python ecosystem; is this a feature that Astral folks have any appetite for building out in uv / ruff?

**Comment by chrisrodrigue** [comment]
[validate-pyproject](https://github.com/abravalheri/validate-pyproject/) is another solution that has `pre-commit` support

**Comment by konstin** [comment]
Is https://github.com/astral-sh/ruff/issues/4100 the same feature as you're describing?

**Comment by charlesnicholson** [comment]
It appears to be, yes!

**Comment by konstin** [comment]
I'm closing this in favor of the ruff issue: This requires parsing python files, so it's in the realm of ruff features more than uv features.
