### ISSUE TITLE
Tag platform doesn't work

### ISSUE THREAD

**Issue by matth3wss** [astral-sh/uv#4553]
* I'm unable to set the platform.
`uv pip install --python-platform=linux -r .\src\requirements.txt`
`uv pip install --platform=linux -r .\src\requirements.txt`
* Output:
![image](https://github.com/astral-sh/uv/assets/12057302/5c726039-f669-4678-9dbf-0cc215eaa347)
* uv 0.1.17 (bb2d06cbb 2024-03-10)

**Comment by charliermarsh** [comment]
You're on a very old version of uv. I don't believe `--python-platform` exists in that version.

**Comment by matth3wss** [comment]
really? I even reinstalled it before sending this issue. I used pip install uv, should i use something else?

**Comment by charliermarsh** [comment]
Your issue says `uv 0.1.17` though, the current version is `uv 0.2.15`. Try `pip install -U uv` to upgrade?

**Comment by matth3wss** [comment]
![image](https://github.com/astral-sh/uv/assets/12057302/053112ef-50cf-43c9-aaf6-482f3328b12a)

**Comment by charliermarsh** [comment]
Can you run `where uv`? It seems like you have two versions of `uv` installed.

**Comment by matth3wss** [comment]
no return
![image](https://github.com/astral-sh/uv/assets/12057302/4cc21647-6f69-4011-86ae-3a3386dc53cd)

**Comment by charliermarsh** [comment]
`Get-Command uv`? I can't remember the exact command on Windows but you want to figure out where that old uv is installed so you can remove it.

**Comment by matth3wss** [comment]
I'm deleting python, I had two versions and apparently uv was intalled with 3.11
