### ISSUE TITLE
`--extra-index-url` fails to look up on pypi when there are no wheels built for my machine

### ISSUE THREAD

**Issue by baggiponte** [astral-sh/uv#4578]
Ciao! I am using `uv` to install a package from a private index. I noticed an error when trying to install anything that depends on `pydantic-core`. Basically, on the private index there are just these wheels:

![image](https://github.com/astral-sh/uv/assets/57922983/26d440b8-0d18-485d-afe5-10ffac71b073)

So when I try to install pydantic-core==2.18.4 on macOS, uv fails:

```bash
uv pip install --extra-index-url="https://$USER:$PWD@pkgs.dev.azure.com/$COMPANY/_packaging/$FEED/pypi/simple/" --verbose -- "pydantic-core==2.18.4"
DEBUG uv 0.2.17
DEBUG Searching for Python interpreter in system toolchains
DEBUG Found cpython 3.10.14 at `/private/tmp/test/.venv/bin/python3` (virtual environment)
DEBUG Using Python 3.10.14 environment at .venv/bin/python3
DEBUG Acquired lock for `.venv`
DEBUG At least one requirement is not satisfied: pydantic-core==2.18.4
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.10.14
DEBUG Adding direct dependency: pydantic-core==2.18.4
DEBUG No cache entry for: https://pkgs.dev.azure.com/$COMPANY/_packaging/$FEED/pypi/simple/pydantic-core/
DEBUG Searching for a compatible version of pydantic-core (==2.18.4)
  × No solution found when resolving dependencies:
  ╰─▶ Because pydantic-core==2.18.4 has no wheels are available with a matching Python implementation and you require pydantic-core==2.18.4, we can conclude that the requirements are unsatisfiable.
```

I think the correct behaviour is for uv to start looking on pypi?

**Comment by zanieb** [comment]
Hi! Check out our [pip compatibility guide](https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes) — you're probably looking for `--index-strategy unsafe-best-match`

**Comment by baggiponte** [comment]
Confirmed it works! 😊 Super cool that `uv` is so stringent/safe by default. Do you think you'd support specifying "only install X from index Y" and dependencies from pypi?

Close the issue whenever you want 😊

**Comment by zanieb** [comment]
Yeah we're definitely going to support that! See #171 for more details.

Thank you :)
