### ISSUE TITLE
pip compile --universal does not retain environment markers for dependencies

### ISSUE THREAD

**Issue by houbie** [astral-sh/uv#4584]
**Steps to reproduce:**
`echo poetry | uv pip compile --universal -`
adding `--no-strip-markers` yields the same result.

**Outcome:**
```
...
xattr==1.1.0
    # via poetry
```
xattr is not available for windows, so the generated requirements will fail to install on windows.

**Expected outcome:**
```
...
xattr==1.1.0; sys_platform == "darwin"
    # via poetry
```
From poetry's sdist: `Requires-Dist: xattr (>=1.0.0,<2.0.0) ; sys_platform == "darwin"`

**Comment by zanieb** [comment]
Thanks for the report, looks like a bug but someone who's working on the lock file will check in.

**Comment by charliermarsh** [comment]
Thanks, not immediately clear why it's being omitted there, looking now.

**Comment by charliermarsh** [comment]
(`uv lock` does correctly include the marker.)

**Comment by charliermarsh** [comment]
Ahh ok, the problem is that the dependency graph has a cycle, because `poetry-plugin-export` has a dependency on `poetry`. Very interesting... Will fix.

**Comment by houbie** [comment]
that was super responsive 🚀
I just replaced pip with uv in [pyprojectx](https://github.com/pyprojectx/pyprojectx) and the integration tests became 4x faster 🥳 
Looking forward to the next release

**Comment by charliermarsh** [comment]
Awesome, thanks!
