### ISSUE TITLE
Support `--disable-pip-version-check` and other pip flags

### ISSUE THREAD

**Issue by jeffgeee** [astral-sh/uv#4590]
`uv` is supposed to be a "Drop-in replacement for common pip, pip-tools, and virtualenv commands."

Recently testing with some python scripts which used `--disable-pip-version-check` I found this to not be the case, along with a few other flags. Was this being tracked anywhere?

**Comment by zanieb** [comment]
Please consult our compatibility guide: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md

If there are things that aren't documented there, feel free to let us know or add in a pull request.

**Comment by charliermarsh** [comment]
I guess we could add that to the compatibility args but it's obviously a weird one.
