### ISSUE TITLE
pip compile --universal using python version markers

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#4591]
Python version markers being used in an interesting way by pip compile --universal.

Bug summary: the emitted markers `python_version >= '3.12'` etc make the lockfile non-universal. Without -p argument the result depends on which python version uv selects by default.

uv 0.2.17
platform: linux (x86_64)

```shell
> echo pandas==2.2.2 | uv pip compile --universal - -p 3.12 --no-header
Resolved 6 packages in 18ms
numpy==2.0.0 ; python_version >= '3.12'
    # via pandas
pandas==2.2.2
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tzdata==2024.1
    # via pandas
```

```shell
> echo pandas==2.2.2 | uv pip compile --universal - -p 3.11 --no-header
Resolved 6 packages in 18ms
numpy==2.0.0 ; python_version == '3.11'
    # via pandas
pandas==2.2.2
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tzdata==2024.1
    # via pandas
```

```shell
> echo pandas==2.2.2 | uv pip compile --universal - -p 3.10 --no-header
Resolved 6 packages in 18ms
numpy==2.0.0 ; python_version < '3.11'
    # via pandas
pandas==2.2.2
python-dateutil==2.9.0.post0
    # via pandas
pytz==2024.1
    # via pandas
six==1.16.0
    # via python-dateutil
tzdata==2024.1
    # via pandas
```

**Comment by charliermarsh** [comment]
We need some way to understand the minimum Python version compatibility -- I don't think this is a "bug"?

**Comment by bluss** [comment]
It looks like a bug because the resolution done for python 3.10 is only valid for python 3.10 (not for higher versions). (The `numpy` dependency is not pinned for python 3.11, 3.12 - this "works" but there is no lock for that dependency?)

```
      --universal
          Perform a universal resolution, attempting to generate a single `requirements.txt` output
          file that is compatible with all operating systems, architectures and supported Python
          versions
```

The docs suggest that universal can create a lockfile that is valid for more than one python version I think?

**Comment by charliermarsh** [comment]
Yes, the Python version is meant to be a minimum. Just to clarify, there's no such thing as locking for "all" Python versions due to `requires-python`. You would need _all_ of your dependencies to support all Python versions in order to produce a resolution. So we need input on the minimum bound.

That being said, the marker output here is clearly a bit weird? Like `numpy==2.0.0 ; python_version < '3.11'` is clearly wrong for `-p 3.10` -- so I take it back. The intent is that `-p 3.10` locks for Python >= 3.10.

**Comment by zanieb** [comment]
@charliermarsh I thought you you intentionally had it pin for the current version instead of using it as a lower bound?

**Comment by charliermarsh** [comment]
The _intent_ was for it to be a minimum version.

**Comment by charliermarsh** [comment]
Ok this is a one-line change but we need to decide what we want: minimum version or exact version?
