### ISSUE TITLE
No error when PEP508 source and `tool.uv.sources` entry don't match

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#4603]
For example:
```
dependencies = [
    "uv-public-pypackage @ https://github.com/astral-test/uv-public-pypackage@0.0.2",
]

[tool.uv.sources]
uv-public-pypackage = { git = "https://github.com/astral-test/uv-public-pypackage", tag = "0.0.1" }
```

`uv lock/sync` currently run without error, preferring `tool.uv.sources`.

**Comment by charliermarsh** [comment]
I added test coverage to at least codify the existing behavior in https://github.com/astral-sh/uv/pull/6051.

**Comment by charliermarsh** [comment]
I found that we actually error here? So gonna close.
