### ISSUE TITLE
py -3.11 -m uv venv not working proprely 

### ISSUE THREAD

**Issue by zakimimit** [astral-sh/uv#4614]
Hello ;

> Python 3.11.9   and use also Python 3.11.7
> uv 0.2.17 (2024-06-26)

I have probelm with :

`py -3.11 -m uv venv
`
when run it i got 
```

DEBUG uv 0.2.17
DEBUG Searching for Python interpreter in system toolchains
DEBUG Found cpython 3.8.10 at `\AppData\Local\Programs\Python\Python38-32\python.exe` (search path)
Using Python 3.8.10 interpreter at: \AppData\Local\Programs\Python\Python38-32\python.exe
Creating virtualenv at: .venv
Activate with: .venv\Scripts\activate

```

the uv  installed only installed in python  3.11

I hope you can fix it 

not 

==========
I have this istalled on my pc :
>python 3.8 32bit
>python 3.8 64bit
>python 3.11 64bit

My best regards

**Comment by charliermarsh** [comment]
I would suggest running `uv venv -p 3.11`.

**Comment by charliermarsh** [comment]
I can take a look when I'm back with my Windows machine.

**Comment by zakimimit** [comment]
this uv venv -p 3.11 worked 

thank you
