### ISSUE TITLE
uv compile fails to find some packages when using --python-platform

### ISSUE THREAD

**Issue by jcugat** [astral-sh/uv#4616]
I'm trying to freeze some dependencies that I built locally for arm64 macs, but when using `uv pip compile` with the argument `--python-platform=macos` it fails the resolution, and removing the argument works perfectly even though I'm running it from an arm64 machine.

Detailed steps to reproduce:

```
❯ python -c 'import platform;import sys;print(f"{sys.platform=} {platform.machine()=}")'
sys.platform='darwin' platform.machine()='arm64'

❯ cat mydeps.in
ml-metadata==1.14.1.dev0

❯ la dist/ml-metadata/1.14.1.dev0/
total 37288
-rw-r--r--  1 josepc  staff    18M Jun 26 18:16 ml_metadata-1.14.1.dev0-cp38-cp38-macosx_13_0_arm64.whl

❯ uv pip compile --python-platform=macos --find-links /Users/josepc/work/python-arm64-packages/dist/ml-metadata/1.14.1.dev0/ mydeps.in -o mydeps.txt
  × No solution found when resolving dependencies:
  ╰─▶ Because ml-metadata==1.14.1.dev0 has no wheels are available with a matching platform and you require ml-metadata==1.14.1.dev0, we can conclude that the requirements are unsatisfiable.

❯ uv pip compile --find-links /Users/josepc/work/python-arm64-packages/dist/ml-metadata/1.14.1.dev0/ mydeps.in -o mydeps.txt
Resolved 6 packages in 1.62s
# This file was autogenerated by uv via the following command:
#    uv pip compile mydeps.in -o mydeps.txt
absl-py==1.4.0
    # via ml-metadata
attrs==21.4.0
    # via ml-metadata
grpcio==1.64.1
    # via ml-metadata
ml-metadata==1.14.1.dev0
    # via -r mydeps.in
protobuf==3.20.3
    # via ml-metadata
six==1.16.0
    # via ml-metadata
```

**Comment by charliermarsh** [comment]
Can you share the list of wheels in `/Users/josepc/work/python-arm64-packages/dist/ml-metadata/1.14.1.dev0/`?

**Comment by jcugat** [comment]
It's the third command I executed in my steps, do you need anything from inside the wheel?

**Comment by charliermarsh** [comment]
Ah sorry, I missed it.

The default macOS deployment target is 12.0. So if you pass `--python-platform macos`, it tries to resolve for a minimum of macOS 12.0, but your wheel only supports 13.0 and later.

You can set the `MACOSX_DEPLOYMENT_TARGET=13.0` environment variable to override it.

**Comment by charliermarsh** [comment]
(Or, of course, you can increase the compatibility of your wheel and try to lower the minimum supported macOS version.)

**Comment by jcugat** [comment]
Ah gotcha, I completely missed this env var in the documentation. Thanks for the help!

**Comment by charliermarsh** [comment]
No prob!
