### ISSUE TITLE
Bad experience: Mac, python from brew, pip install uv

### ISSUE THREAD

**Issue by anki-code** [astral-sh/uv#4624]
Hey! Thank you for this awesome thing!

I tried to install it but had bad experience on Mac. Let's take a look:

```xsh
which pip
# /opt/homebrew/bin/pip

pip -V
# pip 22.3.1 from /usr/local/lib/rustpython3.11/site-packages/pip

pip install uv
# ERROR: Could not install packages due to an 
# OSError: [Errno 13] Permission denied (os error 13): '/usr/local/bin/uv' -> 'None' 🔴 
# Consider using the `--user` option or check the permissions.

pip install --user uv
# Successfully installed uv-0.2.17
# WARNING: There was an error checking the latest version of pip. 🔴 

uv
# The command line interface for the uv binary.

uv pip install pandas
# error: No Python interpreters found in system toolchains 🔴 
```

**Comment by charliermarsh** [comment]
Do you have Python installed?

**Comment by charliermarsh** [comment]
You should run `uv venv` first to create a virtual environment. (That error message is fixed on `main`.)

**Comment by zanieb** [comment]
I believe I just fixed the error message you're seeing at https://github.com/astral-sh/uv/pull/4596

We require creation of a virtual environment, so you need to run `uv venv` because you can `uv pip install`.

We don't support pip's user flag (#2352)

**Comment by zanieb** [comment]
Glad it's sorted out. We'll add more suggestions to the error messages there soon :)
