### ISSUE TITLE
Universal resolver fails when multiple divergent constraints are provided

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4640]
Given:

```
requests
requests==2.32.3 ; python_version >= '3.12'
requests==2.32.0 ; python_version < '3.12'
```

Running `uv pip compile requirements.txt --universal` fails with:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because requests{python_version >= '3.12'}==2.32.3 depends on requests==2.32.3 and you require requests{python_version >= '3.12'}==2.32.3, we can conclude that your requirements and requests{python_version < '3.12'}==2.32.0 are
      incompatible.
      And because you require requests{python_version < '3.12'}==2.32.0, we can conclude that the requirements are unsatisfiable.
```

This seems a bit silly, but it's maybe not quite as silly if you view it as constraints. Imagine your `requirements.txt` is:

```
requests
```

And then your `constraints.txt` is:

```
requests==2.32.3 ; python_version >= '3.12'
requests==2.32.0 ; python_version < '3.12'
```

This would also fail.

**Comment by charliermarsh** [comment]
I added a test (that shows the failure) in https://github.com/astral-sh/uv/pull/4648.

**Comment by davidfritzsche** [comment]
It would be great if the universal resolver would support situations like this. For a software package at work we would like to support a very broad range of Python versions (Python 3.7 - Python 3.12) and a common problem is the numerical Python stack (numpy, pandas) the software depends on. Quite often there is no numpy version which would offer upstream wheels for all Python versions we want to support. Having support for a forked resolution of numpy in such cases would be great. Maybe the fact of having Python version specific requirements/constraints could be a marker when forking is wished for.

**Comment by charliermarsh** [comment]
To be clear, the resolver does support divergent requirements, for example this resolves without issue:

```
requests==2.32.3 ; python_version >= '3.12'
requests==2.32.0 ; python_version < '3.12'
```

It's the blanket `requests` that's causing problems (for details related to the internal implementation).

**Comment by davidfritzsche** [comment]
I have some difficulties with `numpy` (macOS, uv 0.2.18). With a requirements.in

```
numpy >=1.26; python_version>="3.9"
numpy <1.26; python_version<"3.9"
```

I cannot univeral-lock for Python >= 3.8:

```shell
$ uv pip compile -p 3.8 --universal requirements.in
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of numpy{python_version >= '3.9'} are available:
          numpy{python_version >= '3.9'}<=1.26.0
          numpy{python_version >= '3.9'}==1.26.1
          numpy{python_version >= '3.9'}==1.26.2
          numpy{python_version >= '3.9'}==1.26.3
          numpy{python_version >= '3.9'}==1.26.4
          numpy{python_version >= '3.9'}==2.0.0
      and the requested Python version (3.8) does not satisfy Python>=3.9, we can conclude that any of:
          numpy{python_version >= '3.9'}>=1.26.0,<1.26.2
          numpy{python_version >= '3.9'}>1.26.2,<1.26.3
          numpy{python_version >= '3.9'}>1.26.3,<1.26.4
          numpy{python_version >= '3.9'}>1.26.4,<2.0.0
          numpy{python_version >= '3.9'}>2.0.0
       are incompatible.
      And because the requested Python version (3.8) does not satisfy Python>=3.9 and you require
      numpy{python_version >= '3.9'}>=1.26, we can conclude that the requirements are unsatisfiable.
```

**Comment by charliermarsh** [comment]
Thanks, that should work but likely a separate issue.

**Comment by charliermarsh** [comment]
It works in the general case, e.g.:

```
anyio >= 3 ; python_version >= '3.9'
anyio < 3 ; python_version < '3.9'
```

My guess is that the issue in your case is that NumPy `numpy >=1.26` doesn't support Python 3.8, and we're still trying to lock for your `requires-python` in that branch. I will create a separate issue.

**Comment by charliermarsh** [comment]
I have the NumPy fork working:

```
# This file was autogenerated by uv via the following command:
#    uv pip compile -p 3.7 --universal req.in
numpy==1.21.6 ; python_version < '3.9'
    # via -r req.in
numpy==2.0.0 ; python_version >= '3.9'
    # via -r req.in
```

**Comment by charliermarsh** [comment]
Conceptually, could we model this as:

```
requests ; sys_platform != 'darwin' and sys_platform != 'linux'
requests==2.32.3 ; sys_platform == 'darwin'
requests==2.32.0 ; sys_platform == 'linux'
```

@BurntSushi?
