### ISSUE TITLE
uv fails to start because of jemalloc

### ISSUE THREAD

**Issue by adminy** [astral-sh/uv#4647]
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
[1]    22202 abort (core dumped)  uv
```

### A minimal code snippet that reproduces the bug.
`uv venv` or any uv command.
### The current uv platform.
[NixOS derivation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/uv/uv/package.nix) running on raspberry Pi latest kernel with the aarch64 target.
### The current uv version (`uv --version`).
0.2.15 ( I think, not sure because of the error)

**Comment by zanieb** [comment]
Looks like jemalloc is not supported on that operating system e.g. https://github.com/home-assistant/core/issues/105768

Home-assistant provides a `DISABLE_JEMALLOC` option to work-around this, we might need to do similar?

It looks like they also changed the page size (i.e. `JEMALLOC_SYS_WITH_LG_PAGE`) which may solve the issue? https://github.com/home-assistant/docker-base/pull/248

**Comment by konstin** [comment]
This is the same problem as we had in https://github.com/astral-sh/ruff/issues/3791, we can try the same mitigation (`JEMALLOC_SYS_WITH_LG_PAGE=16` during build)

**Comment by charliermarsh** [comment]
I believe we have that same mitigation in our build already @konstin.

**Comment by zanieb** [comment]
I'm going to close this as stale. #6528 tracks this issue for our own binaries.
