### ISSUE TITLE
Show tool versions in `uv tool list`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4653]
In addition to the name, it'd be nice to show the installed version. Should this be behind a flag? Are there other commands like `uv pip list` or `pipx list` we should take inspiration from?

A simple example:

```
$ uv tool list --show-versions
black v20.0.1
```

Related:

- #4654

**Comment by blueraft** [comment]
The cargo command which includes both the version and entrypoints could be used as an inspiration too.

```sh
❯ cargo install --list
sqlx-cli v0.7.3:
    cargo-sqlx
    sqlx
```

**Comment by zanieb** [comment]
Nice, I like the look of that

**Comment by caiquejjx** [comment]
I think the version should be showed by default because it doesn't add that much of information, the entrypoints maybe we should add a flag like `--entrypoints` because for cases where we have a lot of tools it might be too much

**Comment by charliermarsh** [comment]
Personally I'd probably do:

```
sqlx-cli==0.7.3:
    cargo-sqlx
    sqlx
```

Only because `sqlx-cli==0.7.3` matches `pip freeze`. But I don't feel strongly.

**Comment by zanieb** [comment]
I don't love the pinned requirement syntax for something that will _always_ be a specific version and isn't meant for consumption by another tool.

**Comment by caiquejjx** [comment]
I have created a pr based on @blueraft suggestion, lmk if it is the final design we want
