### ISSUE TITLE
Show tool entry points in `uv tool list`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4654]
We should display the name of the executable entry points that are provided by an installed tool e.g.

```
$ uv tool list
black
    black
    blackd
```

The format is up for debate, open questions include things like:

- Should we show the path to the executable?
- Should this be opt-in or display by default?
- Should we omit it for tools that provide a single entry points with the same name?

Another idea is like

```
$ uv tool list
black (provides: black, blackd)
```

When proposing a design here, we should take into account the output of other tools like `pipx`.

Related:

- #4653

**Comment by zanieb** [comment]
The proposal to match `cargo install --list` in https://github.com/astral-sh/uv/issues/4653#issuecomment-2198488484 seems nice.

**Comment by moreaupascal56** [comment]
Hello I would like to have a look on this; but I am relatively new to uv and rust so it will not be immediate, if this is urgent I will just collaborate and have a look at the proposed solution. 
However uv is amazing thanks for the tool !

**Comment by zanieb** [comment]
Thanks @moreaupascal56! Appreciate it :) 

It's likely someone will tackle this soon (or I will) but feel free to ask questions on the pull request. We'll be tagging more things as https://github.com/astral-sh/uv/labels/good%20first%20issue so keep an eye out.

**Comment by T-256** [comment]
> The proposal to match `cargo install --list` in [#4653 (comment)](https://github.com/astral-sh/uv/issues/4653#issuecomment-2198488484) seems nice.

I like it, another possible design could be `uv tool list` show entrypoints instead of installed tools:
```sh
$ uv tool list
black
blackd (from black)
```
By that, no indentions applied to output and user will know what names could be placed in `uv tool run <name>`.

**Comment by zanieb** [comment]
I kind of like that, but it gets a little tricky with versions. 

Nit: If you've used `uv tool install` you shouldn't use `uv tool run`, they're added to your path and invoked directly. To run `blackd` with `uv tool run` you'd need `uv tool run --from black blackd`.
