### ISSUE TITLE
Incomplete message for `uv tool install azure-cli --prerelease=allow`

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4688]
I get the following for `uv tool install azure-cli --prerelease=allow`:
```
warning: `uv tool install` is experimental and may change without warning.
Resolved 143 packages in 400ms
Installed 143 packages in 49ms
 + adal==1.2.7
 + antlr4-python3-runtime==4.13.1
...
 + wrapt==1.16.0
 + xmltodict==0.13.0
Installed: 
```
The part behind `Installed: ` is empty. Same problem for uninstall.

**Comment by charliermarsh** [comment]
Does it have any entrypoints

**Comment by konstin** [comment]
It has `azure_cli-2.61.0.data/scripts/` entrypoints, not regular `entry_point.txt`

**Comment by charliermarsh** [comment]
Ok thanks! Probably missing that. We should also fix the logging in the event that it legitimately has no entrypoints (warn).

**Comment by charliermarsh** [comment]
Another example (we use data scripts):

```
❯ uv tool install ruff
warning: `uv tool install` is experimental and may change without warning.
Resolved 1 package in 313ms
Prepared 1 package in 651ms
Installed 1 package in 7ms
 + ruff==0.5.0
Installed:
```
