### ISSUE TITLE
`uv tool` should install the latest version of the tool

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4689]
In https://github.com/astral-sh/uv/issues/4685, the installation of azure-cli failed because the latest version was incompatible. Should `uv tool` force to installing the latest version of a tool instead? I wouldn't know when i'd want `uv tool install foo` to install an older version of foo.

**Comment by zanieb** [comment]
Can you clarify what you mean here? I'm kind of confused.

**Comment by konstin** [comment]
In #4685, `uv tool install azure-cli` was backtracking from azure-cli 2.61.0 to 2.0.67, with no indication that we're not installing the latest version. When i install a cli tool by name, i'd expect it to install the latest version of that tool, not backtrack through the versions.

**Comment by charliermarsh** [comment]
I guess I don't see how that's different than `uv pip install azure-cli`.
