### ISSUE TITLE
`uv sync` fails when interpreter is not named `python[3]`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4709]
See discussion in https://github.com/astral-sh/uv/issues/4277

Instead of only searching for, e.g., `python3.12` executables when Python 3.12 is requested (and not during the default search), we should use `which_re` (or a manually implemented `which`) to find all possible Python executables then filter them to meet the version request (if necessary).

**Comment by zanieb** [comment]
See `python_executables_from_search_path` for the current implementation.

**Comment by konstin** [comment]
The current behaviour is a problem when using pyenv: When using `uv sync`, uv fails to find a python interpreter even if it exists if the default `python`/`python3` are incompatible.

For example with both `requires-python = "==3.10.*"` `requires-python = ">=3.10"`, where the default `python`/`python3` are any other version, say 3.9:

This fails:
```
uv sync --python-preference only-system
```

This passes:
```
uv sync --python-preference only-system -p 3.10
```

uv should find the python 3.10 interpreter in either case.

## Reproduction

```Dockerfile
FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -yy build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev curl git \
    libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev
RUN curl https://pyenv.run | bash
ENV PATH="/root/.pyenv/bin:$PATH"
RUN CONFIGURE_OPTS="--enable-optimizations" pyenv install 3.8.12 3.8.18
RUN CONFIGURE_OPTS="--enable-optimizations" pyenv install 3.9.18
RUN CONFIGURE_OPTS="--enable-optimizations" pyenv install 3.10.13
RUN CONFIGURE_OPTS="--enable-optimizations" pyenv install 3.11.7
RUN CONFIGURE_OPTS="--enable-optimizations" pyenv install 3.12.1
RUN pyenv global 3.8.12 3.8.18 3.9.18 3.10.13 3.11.7 3.12.1
# https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc \
    && echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc \
    && echo 'eval "$(pyenv init -)"' >> ~/.bashrc
```

Create a dummy pyproject.toml, any `requires-python` that mismatches the default active python will do:
```toml
[project]
name = "a"
version = "0.1.0"
requires-python = "==3.10.*"
dependencies = ["tqdm"]
```

Compile uv:
```
cargo build --release --target x86_64-unknown-linux-musl
```

Start the docker container, mount the uv dir to `/io` and run commands with
```
/io/target/x86_64-unknown-linux-musl/release/uv sync
```

**Comment by charliermarsh** [comment]
I think this needs an owner. @konstin?

**Comment by konstin** [comment]
Will do
