### ISSUE TITLE
`requires-python` normalization is unintuitive

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4719]
E.g., `python_version <= '3.9' or python_version > '3.9'` doesn't simplify out, nor does `python_version < '3.9' or python_version >= '3.9'`.

Related to #4714.

**Comment by charliermarsh** [comment]
If this were a Python package, it would actually be correct not to normalize these, due to pre-release handling and other details of PEP 440. But we generally want to ignore that stuff with `requires-python`.

**Comment by charliermarsh** [comment]
I think this can be solved alongside https://github.com/astral-sh/uv/issues/4714.

**Comment by ibraheemdev** [comment]
Is this a duplicate of https://github.com/astral-sh/uv/issues/4272?

**Comment by charliermarsh** [comment]
@ibraheemdev - Yeah, thank you.
