### ISSUE TITLE
Connection retry support for `uv pip install`

### ISSUE THREAD

**Issue by dannysepler** [astral-sh/uv#4739]
`pip install` supports the `--retries` command. According to `pip install --help`...

```
--retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
```

I currently develop within an internal package index that can flake when fetching packages. It'd be great for `uv pip install` to support retrying on a per-connection basis as well. I don't have a preference for if it should retry by default.

---

command invoked: `RUN UV_SYSTEM_PYTHON=1 NO_SQLITE=1 uv pip install -r requirements.txt --no-cache`
platform: docker
uv --version: `uv 0.2.17`

**Comment by zanieb** [comment]
I think we already support network retries, there's more discussion at https://github.com/astral-sh/uv/issues/3514 which should cover what you're looking for. We also added some logging around retries:

- #3933 
- https://github.com/astral-sh/uv/pull/4725

**Comment by zanieb** [comment]
(Feel free to let me know if you have any more questions though!)
