### ISSUE TITLE
Feature Request: Include version updating from when running `uv self update`

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#4748]
Very minor quality of life request, when you run `uv self update` it gives you an output like:

```
info: Checking for updates...
success: Upgraded `uv` to v0.2.20! https://github.com/astral-sh/uv/releases/tag/0.2.20
```

But it never told me what version I updated from, sometimes when I'm logging into an environment I've not logged into for a little bit I don't remember what uv version I was on.

Mostly this is a personal preference, but occasionally it's a little harder to identify where a fix or a regression happened because I don't know one of my two data points.

**Comment by zanieb** [comment]
If you use `uv self update -v` we'll display the current version before doing anything (and not include much else). Fair request though!
