### ISSUE TITLE
The python interpreter for linux installed by `uv toolchain` is debug built.

### ISSUE THREAD

**Issue by Di-Is** [astral-sh/uv#4774]
The python interpreter for linux installed by `uv toolchain` seems to be built in debug mode.
From a performance standpoint, it is better to use optimized binaries like pgo+lto instead.

#### Check command

```bash
# check version
uv version
uv 0.2.21

# install python
uv toolchain install 3.12.3

# check build type
uv run python -c "import sysconfig;print(sysconfig.get_config_var('Py_DEBUG'))"
1
```

**Comment by zanieb** [comment]
Hm we should be preferring the optimized one, let me check what's going on here.
