### ISSUE TITLE
`uv run` can fail to invoke `python`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4776]
```
❯ uv run --isolated -v crates/uv-python/fetch-download-metadata.py
DEBUG uv 0.2.21
warning: `uv run` is experimental and may change without warning.
DEBUG Running `python crates/uv-python/fetch-download-metadata.py`
error: Failed to spawn: `python`
  Caused by: No such file or directory (os error 2)
  ```

**Comment by charliermarsh** [comment]
What's going on here? Hah

**Comment by charliermarsh** [comment]
Should we use the absolute path to the Python interpreter that we found?

**Comment by charliermarsh** [comment]
Or are we not adding it to PATH, maybe?

**Comment by charliermarsh** [comment]
Hmm, no, we do add the scripts directory to `PATH` which should include `python`...

**Comment by zanieb** [comment]
My suspicion here, without investigating further, is that we didn't create an environment (since there are no requirements) and tried to invoke `python` outside of one?

**Comment by charliermarsh** [comment]
Yeah this makes sense. It's kinda the same as https://github.com/astral-sh/uv/issues/4846.
