### ISSUE TITLE
Use a relative path in `uv pip compile --emit-links`

### ISSUE THREAD

**Issue by oriori1703** [astral-sh/uv#4797]
When running `uv pip compile --emit-links` the lock file always contains `--find-links` with an absolute path.

For example the following:
```sh
echo "test-package --find-links ./wheels"  | uv pip compile - --emit-links
```
Will result in:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile - --emit-links
--find-links /home/user/project/./wheels

test-package==1.0.0
```

The resulting lock file will not be portable between different computers, because the absolute path will be different.

IMO this is less desirable than a relative path.

**Comment by charliermarsh** [comment]
Thanks, I'm surprised to see that.

**Comment by charliermarsh** [comment]
Ah ok yes, thanks.
