### ISSUE TITLE
`uv cache prune` should remove cached environments that refer to non-existent interpreters

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4802]

**Comment by charliermarsh** [comment]
Actually, maybe we take this one step further. Maybe `uv cache prune` removes _all_ cached environments, always.

**Comment by zanieb** [comment]
That doesn't quite feel "unreachable" though?

**Comment by charliermarsh** [comment]
It's technically not referenced by anything though.

**Comment by zanieb** [comment]
Hm okay 👍
