### ISSUE TITLE
`uv sync` should handle a missing `uv lock`.

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4803]
When trying to sync an empty workspace i got:

```
$ uv sync
warning: `uv sync` is experimental and may change without warning.
error: failed to read from file `/home/konsti/projects/workspace-git-path-dep-test/uv.lock`
  Caused by: No such file or directory (os error 2)
```

This error message should hint towards running `uv lock`.

**Comment by zanieb** [comment]
Or, as discussed on Discord, we should just create the lock file without a `--locked` option.

**Comment by charliermarsh** [comment]
I created a separate issue, since it still makes sense to have a better error here (e.g., if `--locked` is provided): https://github.com/astral-sh/uv/issues/4812
