### ISSUE TITLE
`uv sync` should lock (unless `--locked` is provided)

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4812]

**Comment by chrisrodrigue** [comment]
Just wanted to make sure this wasn't a typo... if locking is implicit shouldn't the command be `uv sync --no-lock` or `uv sync --without-lock`?

**Comment by zanieb** [comment]
`--locked` follows Cargo's command line interface, meaning assert the lock file would not change.`--no-lock` feels ambiguous as it might hint that we won't read or update the lock file — which isn't true.

Here's their help menu:

```
      --locked                Assert that `Cargo.lock` will remain unchanged
      --offline               Run without accessing the network
      --frozen                Equivalent to specifying both --locked and --offline
```

**Comment by chrisrodrigue** [comment]
Ahh I see, so `--locked` would imply that the lockfile is "locked" and be a signal to *not* update it. Got it -- is parity with cargo something you guys are shooting for (personally I'm not sure how much overlap there is between Rustaceans and Pythonistas... I wish the [TIOBE index](https://www.tiobe.com/tiobe-index/) showed multilingual demographics).

I am used to the `ruff` CLI with `ruff format --no-fix` / `ruff format --fix` so my brain tripped up.

**Comment by provinzkraut** [comment]
@charliermarsh For my own understanding, could you explain why it should lock by default? 

This was rather unexpected to me, as it deviates from the behaviour of most other package managers, and for most projects, it's almost never the desired default behaviour. 

I see that it makes sense for a `sync` command to also sync the lockfile, but seeing as there's no separate `install` command that just install everything from the lockfile, running `uv sync` without `--locked` / `--frozen` seems to defeat one of the purposes of a lockfile: Consistent installs. 
When I tell someone to check out my branch and run something, I'd like them to have the same packages installed as I do. Implicit updates is something I virtually never want, and might be consider a footgun instead :eyes: 

This extends to other commands such as `uv run`, where I'd argue this is even more unexpected. For example, what is the benefit of e.g. `uv run pytest` updating my dependencies? If I execute that command twice in a row, I would expected to not to run into any issues, but it could actually update my dependencies on the second run, breaking my test suite :see_no_evil:

Am I missing something here? Am I using uv wrong?

**Comment by charliermarsh** [comment]
It generally matches Cargo, as an example. We _only_ update the lockfile if it's out-of-sync with the `pyproject.toml`, i.e., if you've added a new dependency. We don't update arbitrary dependencies on `uv sync` or `uv run`.

**Comment by charliermarsh** [comment]
> If I execute that command twice in a row, I would expected to not to run into any issues, but it could actually update my dependencies on the second run, breaking my test suite.

As an example: this wouldn't happen unless you changed your dependencies.

**Comment by provinzkraut** [comment]
> It generally matches Cargo, as an example. We _only_ update the lockfile if it's out-of-sync with the `pyproject.toml`, i.e., if you've added a new dependency. We don't update arbitrary dependencies on `uv sync` or `uv run`.

Thanks for the clarification! So my expectations were correct, it's just that either I've misconfigured something somewhere, or found a bug :)
