### ISSUE TITLE
`uv toolchain uninstall` should either error or remove all Pythons

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4816]
Right now, it looks like it passes an empty request vector to the command.

Further down, there's a match against `matches!(requests.as_slice(), [PythonRequest::Any])`. Is that possible to trigger?

**Comment by zanieb** [comment]
I think we should probably not uninstall them all without some sort of explicit opt-in, although it would loosely match the semantics of `install`.

**Comment by zanieb** [comment]
That match statement is just copied from the `install` implementation but isn't easy to get right now, maybe we should make it easier to construct the `Any` case in `PythonRequest::parse` e.g. with "any"

**Comment by charliermarsh** [comment]
I think it should probably just error? Require at least one specifier.

**Comment by charliermarsh** [comment]
Right now, how does the `::Any` request work, how does one "create" that?

**Comment by charliermarsh** [comment]
We could _also_ accept `all` or have a `--all` flag that's mutually exclusive with `targets`.

**Comment by zanieb** [comment]
> Right now, how does the `::Any` request work, how does one "create" that?

I think it's just the default request and you can't ask for it explicitly which seems weird. "all" makes sense in this context but not for requests in general. Lots of reasonable approaches here, I think.
