### ISSUE TITLE
`uv python uninstall` error message for invalid requests is confusing

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4819]
e.g.

```
❯ cargo run -q -- python uninstall any
warning: `uv python uninstall` is experimental and may change without warning.
error: Cannot download managed Python for request: executable name `any`
```

We should wrap this error to be clearer, i.e. we're not trying to download here but instead trying to suggest the request can't be mapped to a managed Python key.

**Comment by charliermarsh** [comment]
Relatedly, do you want a way to uninstall all Pythons?

**Comment by zanieb** [comment]
Yeah we should probably support that, though I think it should require some sort of opt-in.

**Comment by charliermarsh** [comment]
I could either see... `python uninstall all` or `python uninstall --all` (mutually exclusive with a request).
