### ISSUE TITLE
Python downloads should show a progress bar

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4825]
When downloading a python toolchain for running a tool, i wait several seconds without any output. This is very untypical and feels wrong for uv. We should add a message indicating the start of a large download and a progress bar. The message should be shown anyway since non-interactive environments don't show progress bars. (The video is from the failing https://github.com/astral-sh/uv/pull/4810, but it applies also when this is fixed)

[Screencast from 2024-07-05 10-01-24.webm](https://github.com/astral-sh/uv/assets/6826232/19a39288-4f78-426a-8d9a-e9a5653c242e)

**Comment by charliermarsh** [comment]
Agree!

**Comment by charliermarsh** [comment]
We already have infra for this from wheel downloads so I’ll label it as a good first issue.

**Comment by zanieb** [comment]
Oh there were some tracing progress bars in the `uv-dev` implementation but I guess we lost that. Big 👍 to adding progress bars here.
