### ISSUE TITLE
Document `uv run`

### ISSUE THREAD

**Issue by torarvid** [astral-sh/uv#4832]
Hello hello 👋🏻 I recently discovered the command `uv run` by stumbling on it in the uv issues list here on Github. Not sure if this is intentional, but if I simply run `uv`, then the `run` subcommand is not listed under commands.

My platform: macOS Sonoma 14.5
uv: 0.2.21 (ebfe6d8fc 2024-07-03)

Current output from the Commands section:
```
Commands:
  pip        Resolve and install Python packages
  tool       Run and manage executable Python packages
  toolchain  Manage Python installations
  venv       Create a virtual environment
  cache      Manage the cache
  self       Manage the `uv` executable
  version    Display uv's version
  help       Print this message or the help of the given subcommand(s)
```

**Comment by konstin** [comment]
Hi! `uv run` is currently in preview and not yet part of stable, documented interface of uv. We will unhide them once they become more stable. Feel free to play around with them and report problems in the meantime!

**Comment by torarvid** [comment]
Ah, of course! Thanks for the reply, and sorry for the noise 😄
