### ISSUE TITLE
Use `install_only` archives for managed Python installations

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4834]
These have a significant size reduction and are automatically prioritized to the optimized version for each platform, see https://github.com/astral-sh/uv/pull/4775#discussion_r1666890324

What are the downsides to using these? Rye does not appear to use them. I don't think we're using any of the build metadata.

**Comment by j178** [comment]
Rye added support for toolchain installation without build info in https://github.com/astral-sh/rye/pull/917. It still fetches the`full` version and then renames the inner `install` directory to the final target, discarding the build info in the process. I think it is possible for uv to use an `install-only` archive, thereby reducing the fetch size.

**Comment by charliermarsh** [comment]
This makes sense.

**Comment by charliermarsh** [comment]
Although it seems like you can't get PGO and/or LTO with `install-only`.

**Comment by charliermarsh** [comment]
Oh nevermind, I misunderstood. They're already optimized. Let's use them!
