### ISSUE TITLE
Not working in Collab and Kaggle

### ISSUE THREAD

**Issue by dudegladiator** [astral-sh/uv#4844]
I run the the following command over kaggle and collab. 

`!pip install uv`
`!uv venv`
`!source .venv/bin/activate`

`!uv pip install thefuzz`
`from thefuzz import fuzz`

Error 
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[14], line 1
----> 1 from thefuzz import fuzz
      2 from thefuzz import process
      4 def fuzzy_match_items(item_list, output_items):

ModuleNotFoundError: No module named 'thefuzz'`

**Comment by FishAlchemist** [comment]
virtual environment cannot use the virtual environment for all cells just using ``source`` command.
![image](https://github.com/astral-sh/uv/assets/48265002/2cbaa9d1-81f1-4919-8f95-06921922aea9)
If you need a virtual environment because UV is installed into a virtual environment by default.
you can add ``--system`` flag.
e.g. 
```colab
!uv pip install --system [packages]
```
flag information in  0.2.21
```
      --system
          Install packages into the system Python.

          By default, `uv` installs into the virtual environment in the current working directory or any parent
          directory. The `--system` option instructs `uv` to instead use the first Python found in the system `PATH`.

          WARNING: `--system` is intended for use in continuous integration (CI) environments and should be used with
          caution, as it can modify the system Python installation.

          [env: UV_SYSTEM_PYTHON=]
```

**Comment by charliermarsh** [comment]
👍 Yeah that's correct.

**Comment by alirezanobakht13** [comment]
what if the reason venv is used is to change python version?
```
uv venv .venv -p 3.9
```
is there any way to create virtual env with different python version in colab?
