### ISSUE TITLE
"No download found" error should avoid debug representation

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4848]
E.g., given `cargo run -- run -vv --preview --isolated --python 3.12.4 python -V`:

```
error: No download found for request: PythonDownloadRequest { version: Some(MajorMinorPatch(3, 12, 4)), implementation: Some(CPython), arch: Some(Arch(Aarch64(Aarch64))), os: Some(Os(Darwin)), libc: Some(None) }
```

**Comment by zanieb** [comment]
We should never throw this error here either, e.g. when `find_or_fetch` is called if no download can be found we should use the `MissingPython` case. We could add a special error case noting that we could not find the interpreter on the system or as an available download if we want to note that we looked for a download.

**Comment by charliermarsh** [comment]
Okay got it, makes sense.
