### ISSUE TITLE
pip compile --universal is adding tags for python versions lower than requires-python

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#4852]
Hi everyone, thank you for adding the new `--universal` option to pip compile, it will simplify a lot my workflow.

One thing I believe is a bit weird is that it adds marks for python versions below the ones on `pyproject.toml` for the `requires-python` attribute.

Currently we have `requires-python = '>=3.9'` but I see several lines with markers like: 

```
tornado==6.4 ; python_version >= '3.5.2'
python3-openid==3.2.0 ; python_version >= '3.0'
```

I really don't know when it decides the marker is mandatory, but IMO it should be only for the supported versions of my app.

Thank you

**Comment by inoa-jboliveira** [comment]
I forgot to say, the reason it is important to me not having these marks is because we have a few legacy envs where we need to package all the new dependencies with our binaries and these lines make it appear as if the dependency has changed.

I will do a workaround for now, but would appreciate if the output was consistent with only the supported python versions

**Comment by charliermarsh** [comment]
Somewhat torn on whether we should be emitting these... not strongly opposed though.

**Comment by charliermarsh** [comment]
I have a fix for this, will push when I land.
