### ISSUE TITLE
`uv lock` should tell you whether the lockfile changed

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4854]
Currently, alternating between `uv lock --exclude-newer 2024-07-01 --upgrade`, `uv lock --exclude-newer 2024-07-02 --upgrade` and `uv lock --exclude-newer 2024-08-01 --upgrade` with a `transformers` requirement produces the same output each, even though the first produce use the same lockfile while the last one changes it. We should indicate whether the resolution changed.

**Comment by zanieb** [comment]
Related https://github.com/astral-sh/uv/issues/4346

**Comment by konstin** [comment]
Closing as duplicate of #4346
