### ISSUE TITLE
`uv tool list` warns about malformed tool `interpreter-v2`

### ISSUE THREAD

**Issue by oriori1703** [astral-sh/uv#4867]
It seems that when running `uv tool list`  it creates a directory called `interpreter-v2` in uv's tool directory, i.e.  `/home/orip/.local/share/uv/tools/interpreter-v2`.

This could be verified by running `uv tool list && ls "$(uv tool dir)/interpreter-v2"` .
The folder seems to conain .msgpack files.

This also causes a  the next time uv is run:
`warning: Ignoring malformed tool `interpreter-v2`: missing receipt`

```
 uv tool list
warning: `uv tool list` is experimental and may change without warning.
warning: Ignoring malformed tool `interpreter-v2`: missing receipt
build v1.2.1
    pyproject-build
dtrx v8.5.3
    dtrx
ipython v8.26.0
    ipython
    ipython3
mypy v1.10.1
    dmypy
    mypy
    mypyc
    stubgen
    stubtest
ruff v0.5.1
    ruff
```

I'm not sure if creating the directory in the tools dir is intentional, but even if it is, it should probably not give a warning.

p.s.
I have checked this on `v0.2.22`
This also seems to happen to other users as could be seen in #4823 in the 4th line of both of the code block.

**Comment by charliermarsh** [comment]
Thanks, I'll look into this.

**Comment by oriori1703** [comment]
Wow that was quick 😲

**Comment by charliermarsh** [comment]
Thanks for filing it :)
