### ISSUE TITLE
Remove extra duplication from lockfile

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4888]
When declaring a dependency `pandas[excel,html,plot]`, the lockfile shows:

```toml
dependencies = [
    { name = "pandas" },
    { name = "pandas", extra = "excel" },
    { name = "pandas", extra = "html" },
    { name = "pandas", extra = "plot" },
]
```

We should collapse those entries:

```toml
dependencies = [
    { name = "pandas", extra = ["excel", "html", "plot"] },
]
```

This makes more sense to the user (we don't install pandas four times, we install it once and then those extra packages, that's our internal abstraction into virtual packages leaking) and makes the lockfile more concise.

**Comment by BurntSushi** [comment]
Is this limited to the specific example shown here, or in general? In general, each of those dependency entries can have other fields on them that are different. For example, markers. In theory, I think, other fields could be different too, such as version and source. Or at least, that's what our data model supports. But I think the markers really could be different?

**Comment by konstin** [comment]
This should only collapse entries with the same markers. Say we have
```toml
dependencies = [
    "pandas[excel,html]; python_version == '3.13'",
    "pandas[excel,plot]",
]
```
we currently get
```toml
dependencies = [
    { name = "pandas" },
    { name = "pandas", extra = "excel" },
    { name = "pandas", extra = "html", marker = "python_version == '3.13'" },
    { name = "pandas", extra = "plot" },
]
```
which we could collapse to

```toml
dependencies = [
    { name = "pandas", extras = ["excel", "plot"] },
    { name = "pandas", extras = ["html"], marker = "python_version == '3.13'" },
]
```

**Comment by BurntSushi** [comment]
Right, okay. I think this LGTM. Although I don't totally mind our existing format, I am very sympathetic to the fact that it leaks our "virtual package" abstraction. So I think I would on balance favor your suggestion here to the status quo.
