### ISSUE TITLE
Bug with install Numpy

### ISSUE THREAD

**Issue by 17Reset** [astral-sh/uv#4890]
```
× No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of numpy are available:
          numpy<1.26.4
          numpy>=1.27.dev0
      and you require numpy>=1.26.4,<1.27.dev0, we can conclude that the requirements are unsatisfiable.

      hint: numpy was requested with a pre-release marker (e.g., numpy>=1.26.4,<1.27.dev0), but pre-releases
      weren't enabled (try: `--prerelease=allow`)
 ```

**Comment by charliermarsh** [comment]
Can you mind providing more information? E.g.:

- The command you ran
- The `uv` version
- The input requirements
- The output of running with the `--verbose` flag

**Comment by 17Reset** [comment]
1. I encountered this problem when I deployed llama.cpp
2. The latest version of uv used
3. Command used:
` ` `
uv venv llm_venv_llamacpp && source llm_venv_llamacpp/bin/activate
git clone https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
uv pip install --no-cache --requirement requirements.txt
` ` `

**Comment by charliermarsh** [comment]
You need to run with `--index-strategy unsafe-first-match`. The issue is that one of those requirements adds an extra index for PyTorch, and the PyTorch index includes NumPy but not at the requested version.

**Comment by charliermarsh** [comment]
See https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes for more.
