### ISSUE TITLE
Prefetch failures should be non-fatal

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#4901]
See: https://github.com/astral-sh/uv/pull/4900#issuecomment-2214420150

**Comment by zanieb** [comment]
If someone is interested in poking at this, I feel like it shouldn't be _too_ wild to store the error and only surface it if we access the prefetched result — I haven't looked into it though.

**Comment by charliermarsh** [comment]
Agreed!

**Comment by charliermarsh** [comment]
Oh, I fixed these!
