### ISSUE TITLE
Virtualenv auto-creation

### ISSUE THREAD

**Issue by chrisrodrigue** [astral-sh/uv#4908]
Greetings,

Since `uv` conveniently works in place of `venv` and `virtualenv`, I just wanted to propose a really handy development feature that many users of `pdm` and `poetry` are enjoying. 

When invoking `pdm install` from the project root, the default behavior (unless configured otherwise) is to create a `.venv` folder in the root of the project which installs all the dependencies annotated in `pyproject.toml`. This behavior is [described here](https://pdm-project.org/latest/usage/venv/#virtualenv-auto-creation). I think `pdm install` implicitly performs `pdm init` and generates a lockfile if no existing lockfile is detected.

`poetry` takes a slightly different approach and defaults to installing the virtualenvs in a separate location, and requires the user to set `virtualenv.in-project` to true (although not in `pyproject.toml`, it is in another config file used by `poetry`).  This behavior is [described here](https://python-poetry.org/docs/basic-usage/#using-your-virtual-environment). Most users have `.venv` added to their `.gitignore` and in general I think it's nice to keep the `.venv` close to where it is being consumed.

 I think this would be a great and important capability if and when `uv` builds out a `uv install` command.

**Comment by zanieb** [comment]
Hi!

We considered doing this for `uv pip install` in https://github.com/astral-sh/uv/pull/2665 but opted not after significant feedback from users. `uv sync` (which is our equivalent to the pdm or Poetry install commands) does this already.

**Comment by chrisrodrigue** [comment]
Ah okay, great! Thanks for the prompt reply!

**Comment by chrisrodrigue** [comment]
I guess this is a semi-related question: will `pdm sync` work if the lockfile has been generated on another platform? I am not sure where `uv` stands right now when it comes to cross-platform lockfile/dependency resolution.

**Comment by zanieb** [comment]
Yep! See #3347

**Comment by chrisrodrigue** [comment]
Incredible!! You guys are working on this at lightspeed. Eager to start using these features... might be worth updating the [README) (https://github.com/astral-sh/uv#limitations_to highlight the capabilities? 

Also, is there any plan to install the current project as editable into the `.venv` by default (or a configuration option to do so) similar to `pdm`?

**Comment by zanieb** [comment]
We'll update the README when we're ready :) we have documentation to write still

Yes, we do that too.
