### ISSUE TITLE
UCRT64 ~ # uv toolchain list warning: `uv toolchain list` is experimental and may change without warning. error: Running `py --list-paths` failed with status exit code: 2 

### ISSUE THREAD

**Issue by az49xcl** [astral-sh/uv#4918]
platfrom:msys64 UCRT64 win11
uv :0.2.15
cmd: uv toolchain list
python --version: 3.11.9

UCRT64 ~
# uv toolchain list
warning: `uv toolchain list` is experimental and may change without warning.
error: Running `py --list-paths` failed with status exit code: 2 with exit code: 2
--- stdout:

--- stderr:
unknown option --list-paths
usage: py [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
---

**Comment by charliermarsh** [comment]
I think this was fixed in a newer version.

**Comment by charliermarsh** [comment]
https://github.com/astral-sh/uv/issues/4522

**Comment by charliermarsh** [comment]
Can you try with the latest uv? 0.2.15 is several versions behind.

**Comment by az49xcl** [comment]
Unable to build uv under msys2(python -m pip install "uv=0.2.23")
 1.rust toolchain : stable-x86_64-pc-windows-gnu (default)
 2.cargo version: 1.79

error: failed to run custom build command for `libz-ng-sys v1.1.15`
Caused by: build-script-build_zng

**Comment by charliermarsh** [comment]
You're trying to build uv from source, is that intentional? Seems like you need a C++ toolchain for `libz-ng-sys`.
