### ISSUE TITLE
Tracking issue: Make sure universal resolution has great error messages

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4922]
Explaining a resolution error for a failed universal resolution is more complex than for regular resolution: A error may now be constraint to a specific fork, and the derivations may only happen due to the markers and requires-python bound of this fork. We need to check, fix and add tests for conflicts in universal resolution.

**Comment by charliermarsh** [comment]
@konstin: "The error messages are as good as the regular error messages. We should fix the one bug that I pulled out."

@BurntSushi: "One weird thing: the dependency relationship between `a==1` and `a==1{marker}` is exposed in the error messages themselves. If you know that, and you read the error message, it makes sense." (Let's create a separate issue for this.)

**Comment by BurntSushi** [comment]
> "One weird thing: the dependency relationship between `a==1` and `a==1{marker}` is exposed in the error messages themselves. If you know that, and you read the error message, it makes sense." (Let's create a separate issue for this.)

That's here: https://github.com/astral-sh/uv/issues/5618
