### ISSUE TITLE
`uv sync` should recreate venv when it's broken

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#4933]
I have a venv that's broken because i removed the python patch version it was pointing. `uv sync` then fails with the error:

> Python interpreter not found at `<project>/.venv/bin/python3`

It should instead remove and recreate the venv for me.

**Comment by charliermarsh** [comment]
Makes sense, thanks.

**Comment by charliermarsh** [comment]
Same with uv tools IMO.

**Comment by zanieb** [comment]
Presumably this is because we're using `from_root`, I believe discovery would normally skip these.

**Comment by charliermarsh** [comment]
Yeah, I think we just need to expand the fallback cases.
