### ISSUE TITLE
Add `--no-pager` option to `uv help`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4941]
To avoid paging if that's your deal.

**Comment by MadGanGithub** [comment]
Hey @zanieb 
I would like to work on this issue
Can you assign me?

**Comment by silvanocerza** [comment]
I'm confused by this issue, `uv help` doesn't seem to page its output. I actually couldn't find any other command that uses a pager by default. 🤔 

Could it be that I have some local config that messes things up?

**Comment by silvanocerza** [comment]
Nevermind, disregard my previous comment. I'm dumb and should search better. 🤦‍♀️ 

I also tested using an outdated version of `uv` instead of `main`.
