### ISSUE TITLE
Support more platforms in --python-platforms

### ISSUE THREAD

**Issue by cwiede** [astral-sh/uv#4956]
I'd like to use uv pip compile to create requirements.txt files for multiple combinations of python versions and platforms. I noticed that the platforms supported by uv are limited to (uv version 0.2.23):

- windows
- linux
- macos
- x86_64-pc-windows-msvc
- x86_64-unknown-linux-gnu
- aarch64-apple-darwin
- x86_64-apple-darwin
- aarch64-unknown-linux-gnu
- aarch64-unknown-linux-musl
- x86_64-unknown-linux-musl
- x86_64-manylinux_2_17
- x86_64-manylinux_2_28
- aarch64-manylinux_2_17
- aarch64-manylinux_2_28

Now I have stumbled over issues for the PySide6 package for aarch64. This package uses the platform aarch64-manylinux_2_31, which is not supported by uv, unfortunately. As far as I understand PEP 600, the glibc version identifier can be arbitrary, so I wonder why uv only seems to support 2_17 and 2_28?

**Comment by charliermarsh** [comment]
We can add `manylinux_2_31`. At one point I considered supporting arbitrary manylinux versions, but the help etc. then becomes really verbose.

**Comment by cwiede** [comment]
Thanks a lot 👍 

> At one point I considered supporting arbitrary manylinux versions, but the help etc. then becomes really verbose.

Maybe this is something which might be considered for mid-term or long-term future. The list will get longer and longer anyways :)
