### ISSUE TITLE
Add `--reinstall` support to `uv python install`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#4961]

**Comment by caiquejjx** [comment]
Hey @zanieb, can I work in this one?

**Comment by zanieb** [comment]
Definitely!

**Comment by caiquejjx** [comment]
@zanieb what would be the difference between `--reinstall`  from the `force` arg?

**Comment by charliermarsh** [comment]
Good question, defer to @zanieb... If nothing, though, we should consider removing `--force` and replacing it with `--reinstall`.

**Comment by zanieb** [comment]
Wow that's a great question — I forgot how my own CLI works. I honestly don't see what `--force` does differently today. Maybe we'll want `--force` to work similar to how it does in `uv tool install` once we install shim (or similar) for Python but we don't support that yet and I'm not sure what it will look like. Seems like we should just rename it!
