### ISSUE TITLE
Feature Request: Add Requires Python Version similar to Pipenv

### ISSUE THREAD

**Issue by vasudev-gm** [astral-sh/uv#4963]
I am always amazed with rust based tools made by Astral. Added Ruff more than a year ago and still loving it. During the course of years I had migrated few of my test projects from normal virtualenv to Pipenv when onboarding new team members we always had to double check the Python version through Chat or Readme file within project. Pipenv lock file includes the python version required along with pinned package version.

In my limited testing of uv and the performance is amazing and most of the packages are installed(unless it is bigger than my slow internet) in a blink of an eye which I had to double check by removing cached files twice and even passed no-cache argument. 

Not sure if I'm being greedy with too much feature requests linked to [uv lock format](https://github.com/astral-sh/uv/issues/4893) and asking to add Requires Python Version to make migration from pipenv easier.

It is alright if this feature is not in current roadmap but planned in future releases.

Thank you Charlie and team at Astral.

**Comment by zanieb** [comment]
I think this may be resolved by #4970 but we probably won't support writing the pin to the lock file since it's not part of the lock. You could pin `Requires-Python` itself and it'll be encoded there though, if you're only using a single version.

**Comment by vasudev-gm** [comment]
Thanks. At the moment I'm not seeing doc in the cli nor on GitHub.
________________________________

**Comment by vasudev-gm** [comment]
Does uv accept yaml or will a simple .python-version file with following contents work just fine?
```
[requires]
python_version = "3.12"
With multiple versions being supported should it declared with || or simply pass it as an list or array for example: ["3.11.8", "3.12.3", "3.13rc1"]
```

Would love to hear your thoughts as I would like to make the migration to uv as simple as possible while maintaining compatibility with pipenv.


________________________________

**Comment by zanieb** [comment]
We only support a `.python-version` file with a single line or a `.python-versions` file with a version per line right now. We don't support parsing YAML — what format is that?

**Comment by vasudev-gm** [comment]
YAML is used Docker compose and other config related to deployment.
Thanks for the insights. Much appreciated

________________________________

**Comment by charliermarsh** [comment]
I believe this is now covered by `.python-version`.
