### ISSUE TITLE
Windows Server 2019 uv access is denied when executing

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [astral-sh/uv#4980]
I installed pyenv 3.12.4 in a Windows Server 2019 using AWS EC2. Created a virtualenv then tried running `uv pip install -r requirements.txt`. This results in 

```
(.venv) PS C:\Users\andrew\Downloads> uv pip install bin/requirements/requirements-dev.txt
? `bin/requirements/requirements-dev.txt` looks like a local requirements file but was passed as a package name. Did you✔ `bin/requirements/requirements-dev.txt` looks like a local requirements file but was passed as a package name. Did you mean `-r bin/requirements/requirements-dev.txt`? · yes
Resolved 54 packages in 900ms
   Built tasks @ file:///C:/Users/andrew/Downloads/projects/tools/tasks
Prepared 2 packages in 7.40s
error: failed to remove file `C:\Users\andrew\Downloads\.venv\Lib\site-packages\../../Scripts/uv.exe`
  Caused by: Access is denied. (os error 5)
```

Running `uv help` works just fine.

### Interesting solution

Renaming uv.exe from `.venv/Scripts/uv.exe` actually makes installation work

**Comment by charliermarsh** [comment]
Did you install uv into the virtual environment itself? It looks like uv is trying to uninstall itself.

**Comment by charliermarsh** [comment]
I believe this is the same as #1368.

**Comment by Andrew-Chen-Wang** [comment]
Yes, we did `pip install uv`

**Comment by charliermarsh** [comment]
Typically you would install uv globally, since uv doesn't need to be in the virtual environment in order to create it or install into it. (But it's also a known issue on Windows that uv cannot uninstall itself.)

**Comment by charliermarsh** [comment]
I'm gonna merge into that other issue, but happy to answer questions there.

**Comment by Andrew-Chen-Wang** [comment]
Ahh that's not really clear from the instructions. I assumed it's like `pip` where it needs to be installed in the virtualenv!

<img width="757" alt="Screenshot 2024-07-10 at 18 08 31" src="https://github.com/astral-sh/uv/assets/60190294/4d3056fc-2f45-4a73-8299-48806f862ef5">

**Comment by charliermarsh** [comment]
Yeah uv will install into a currently-activated virtualenv even if it's not installed "in" the environment itself.
