### ISSUE TITLE
uv venv's activate command cannot work on MSYS2

### ISSUE THREAD

**Issue by pplmx** [astral-sh/uv#4984]
## Steps to Reproduce

At MSYS2, run the following command:

```bash
❯ uv venv
Using Python 3.12.4 interpreter at: C:\Users\xxx\AppData\Local\Programs\Python\Python312\python.exe
Creating virtualenv at: .venv
Activate with: source .venv\Scripts\activate
❯ source .venv\Scripts\activate
source: no such file or directory: .venvScriptsactivate

```

## Suggested Fix

Use the correct path to activate the virtual environment:

```bash
source .venv/Scripts/activate

```

## Environment Details

```bash
cat /etc/os-release
NAME=MSYS2
ID=msys2
PRETTY_NAME="MSYS2"
ID_LIKE="cygwin arch"
HOME_URL="https://www.msys2.org"
BUG_REPORT_URL="https://github.com/msys2/MSYS2-packages/issues"

uv version
uv 0.2.24 (527b711bc 2024-07-10)
```

**Comment by zanieb** [comment]
Thanks! Looks like we need to display a posix style path here, it should be relatively easy to fix?

**Comment by zanieb** [comment]
Considering something like

```diff
diff --git a/crates/uv/src/commands/venv.rs b/crates/uv/src/commands/venv.rs
index cb906898..7e669ead 100644
--- a/crates/uv/src/commands/venv.rs
+++ b/crates/uv/src/commands/venv.rs
@@ -312,7 +312,7 @@ async fn venv_impl(
 /// Quote a path, if necessary, for safe use in a POSIX-compatible shell command.
 fn shlex_posix(executable: impl AsRef<Path>) -> String {
     // Convert to a display path.
-    let executable = executable.as_ref().user_display().to_string();
+    let executable = executable.as_ref().portable_display().to_string();
 
     // Like Python's `shlex.quote`:
     // > Use single quotes, and put single quotes into double quotes
```

but I'm a little confused that `portable_display()` only uses portable slashes for relative paths? We might need another helper method that always uses the portable path? We'll want to add some tests if we can.

**Comment by pplmx** [comment]
> Thanks! Looks like we need to display a posix style path here, it should be relatively easy to fix?

Yes, if msys2 is found, directly printing a POSIX-style path is fine.

**Comment by MathiasAugustesen** [comment]
Is this one still up for grabs? If so I'd like to take a stab at it

**Comment by zanieb** [comment]
Yeah, https://github.com/astral-sh/uv/pull/5956 — sorry.

**Comment by MathiasAugustesen** [comment]
No problem, I'll look around for something else to tackle
