### ISSUE TITLE
Failure when tried to upgrade single package - No solution found when resolving dependencies:

### ISSUE THREAD

**Issue by ajaysoman1993** [astral-sh/uv#4987]
When I tried to upgrade single package using below command its not working
uv pip compile --upgrade-package=aenum --output-file=requirements_windows.txt requirements.in

 x No solution found when resolving dependencies:
  `-> Because tmp was not found in the package registry and you
      require tmp>=5.10.1, we can conclude that the requirements are
      unsatisfiable.

tmp is the internal package listed in requirement.in

uv --version
uv 0.2.4

**Comment by zanieb** [comment]
Hi! Does the command work without `--upgrade-package`? Also note you're on a pretty old version of uv, I'd recommend upgrading and confirming this still occurs.

**Comment by ajaysoman1993** [comment]
yes, multi package upgrade is working fine with belwo command
uv pip compile --output-file requirements_windows.txt requirements.in 

our requirement is to update single package same like pip does 
pip-compile --upgrade-package=package --output-file=requirements_windows.txt requirements.in

**Comment by charliermarsh** [comment]
Are you using multiple indexes? Have you reviewed https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes? Unfortunately we'll need more information to help you, like a minimum reproducible example.

**Comment by ajaysoman1993** [comment]
Let me put it in simple words, when I do it for single package with minimal packages in the requirements.in

$ **cat requirements_windows.txt**
# This file was autogenerated by uv via the following command:
#    uv pip compile --output-file requirements_windows.txt requirements.in
beautifulsoup4==4.12.3
    # via bs4
bs4==0.0.2
    # via -r requirements.in
importlib-metadata==8.0.0
    # via yapf
platformdirs==4.2.2
    # via yapf
soupsieve==2.5
    # via beautifulsoup4
tomli==2.0.1
    # via yapf
**yapf==0.24.0**
    # via -r requirements.in
zipp==3.19.2
    # via importlib-metadata

$ cat requirements.in
**yapf>0.24.0**
bs4

- Im updating yapf package alone to the latest and its works as expected 

$ uv pip compile **--upgrade-package=yapf** --output-file=requirements_windows.txt requirements.in
Resolved 8 packages in 11ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --upgrade-package=yapf --output-file=requirements_windows.txt requirements.in
beautifulsoup4==4.12.3
    # via bs4
bs4==0.0.2
    # via -r requirements.in
importlib-metadata==8.0.0
    # via yapf
platformdirs==4.2.2
    # via yapf
soupsieve==2.5
    # via beautifulsoup4
tomli==2.0.1
    # via yapf
**yapf==0.40.2**
    # via -r requirements.in
zipp==3.19.2
    # via importlib-metadata


But when I add my work internal package reference to requirements.in then the update is always giving below issue 

$ **uv pip compile --upgrade-package=yapf --output-file=requirements_windows.txt requirements.in**
x No solution found when resolving dependencies:
`-> Because tmp was not found in the package registry and you
require tmp>=5.10.1, we can conclude that the requirements are
unsatisfiable.

**tmp** is the internal package listed in requirement.in

**Comment by ajaysoman1993** [comment]
$ uv pip compile -v --upgrade-package=yapf --output-file=requirements_windows.txt requirements.in
DEBUG uv 0.2.24
DEBUG Starting Python discovery for any Python
DEBUG Looking for exact match for request any Python
DEBUG Searching for Python interpreter in system path or `py` launcher
DEBUG Found cpython 3.10.11 at `C:\Python310\python.exe` (search path)
DEBUG Using Python 3.10.11 interpreter at C:\Python310\python.exe for builds
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.10.11
DEBUG Adding direct dependency: yapf>0.24.0
DEBUG Adding direct dependency: bs4*
DEBUG Adding direct dependency: tmp>=10.11.1
DEBUG No cache entry for: https://pypi.org/simple/tmp/
DEBUG Found stale response for: https://pypi.org/simple/bs4/
DEBUG Sending revalidation request for: https://pypi.org/simple/bs4/
DEBUG Found stale response for: https://pypi.org/simple/yapf/
DEBUG Sending revalidation request for: https://pypi.org/simple/yapf/
DEBUG Found not-modified response for: https://pypi.org/simple/bs4/
DEBUG Found not-modified response for: https://pypi.org/simple/yapf/
DEBUG Searching for a compatible version of yapf (>0.24.0)
DEBUG Selecting: yapf==0.40.2 (yapf-0.40.2-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/51/bb/bf7aab772a159614954d84aa832c129624ba6c32faa559dfb200a534e50b/bs4-0.0.2-py2.py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/66/c9/d4b03b2490107f13ebd68fe9496d41ae41a7de6275ead56d0d4621b11ffd/yapf-0.40.2-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for yapf==0.40.2: importlib-metadata>=6.6.0
DEBUG Adding transitive dependency for yapf==0.40.2: platformdirs>=3.5.1
DEBUG Adding transitive dependency for yapf==0.40.2: tomli>=2.0.1
DEBUG Searching for a compatible version of bs4 (*)
DEBUG Selecting: bs4==0.0.2 (bs4-0.0.2-py2.py3-none-any.whl)
DEBUG Adding transitive dependency for bs4==0.0.2: beautifulsoup4*
DEBUG Found stale response for: https://pypi.org/simple/beautifulsoup4/
DEBUG Sending revalidation request for: https://pypi.org/simple/beautifulsoup4/
DEBUG Found stale response for: https://pypi.org/simple/tomli/
DEBUG Sending revalidation request for: https://pypi.org/simple/tomli/
DEBUG Found stale response for: https://pypi.org/simple/platformdirs/
DEBUG Sending revalidation request for: https://pypi.org/simple/platformdirs/
DEBUG Found stale response for: https://pypi.org/simple/importlib-metadata/
DEBUG Sending revalidation request for: https://pypi.org/simple/importlib-metadata/
DEBUG Found not-modified response for: https://pypi.org/simple/tomli/
DEBUG Found not-modified response for: https://pypi.org/simple/beautifulsoup4/
DEBUG Found not-modified response for: https://pypi.org/simple/platformdirs/
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b1/fe/e8c672695b37eecc5cbf43e1d0638d88d66ba3a44c4d321c796f4e59167f/beautifulsoup4-4.12.3-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl.metadata
DEBUG Found not-modified response for: https://pypi.org/simple/importlib-metadata/
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/68/13/2aa1f0e1364feb2c9ef45302f387ac0bd81484e9c9a4c5688a322fbdfd08/platformdirs-4.2.2-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/dc/ef/38766b2edb096260d9b1b6ad35adaa0bce3b0567abb452b21eb074af88c4/importlib_metadata-8.0.0-py3-none-any.whl.metadata
**DEBUG Searching for a compatible version of tmp (>=10.11.1)
DEBUG No compatible version found for: tmp
  x No solution found when resolving dependencies:**
  `-> Because tmp was not found in the package registry and you require
      tmp>=10.11.1, we can conclude that the requirements are unsatisfiable.

**Comment by ajaysoman1993** [comment]
I found the solution after adding --index-url it worked 
we can close this

**Comment by ajaysoman1993** [comment]
Fixed
