### ISSUE TITLE
`uvx`: a hash was expected but one was not found for direct URL source distribution

### ISSUE THREAD

**Issue by romeroyonatan** [astral-sh/uv#4990]
### Description
`uvx`/`uv tool run` cannot run a command **from a dependency URL** in **Windows 11**. 

### Steps to Reproduce
```
uvx --from 'awscli @ https://github.com/aws/aws-cli/archive/refs/tags/2.17.9.zip' aws
```
### Expected Behavior
The `aws` command should be executed displaying its usage message

```bash
$ uvx --from 'awscli @ https://github.com/aws/aws-cli/archive/refs/tags/2.17.9.zip' aws
warning: `uv tool run` is experimental and may change without warning.
Resolved 16 packages in 1.11s

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: command
```

### Actual Behavior
The command fails with the message `a hash was expected but one was not found for direct URL source distribution`

```powershell
PS > uvx --from 'awscli @ https://github.com/aws/aws-cli/archive/refs/tags/2.17.9.zip' aws
warning: `uv tool run` is experimental and may change without warning.
Resolved 16 packages in 1.25s
error: since the distribution `awscli==2.17.9 @ direct+https://github.com/aws/aws-cli/archive/refs/tags/2.17.9.zip` comes from a direct dependency, a hash was expected but one was not found for direct URL source distribution
```

### Logs
[logs-uvx-failure.txt](https://github.com/user-attachments/files/16175383/logs-uvx-failure.txt)

### Environment
**Operating System:** Windows 11 Pro 21H2 (Build 22000.2538)
**Shell:** Powershell 7.4.3
**Python version:** 3.11.9
**uv version**: 0.2.24

Thank you to the maintainers for your hard work and dedication in maintaining this project! Your efforts are greatly appreciated.

**Comment by charliermarsh** [comment]
Thanks! That’s unintentional — I’ll fix it.

**Comment by zanieb** [comment]
Thanks for the clear report!
