### ISSUE TITLE
Add `uv install` to install a specific packages from the workspace

### ISSUE THREAD

**Issue by bschoenmaeckers** [astral-sh/uv#5008]
I basically  want to install a subset of packages from my virtual workspace in a Dockerfile with respect to the uv.lock file.
Currently I use `uv sync` to install all locked packages including the whole workspace. But I don't see a way to install just one packages (including its dependencies).

I tried to do `uv pip install -c uv.lock packages/package_a` but this obviously does not work because uv.lock is not a constrain file.

**Comment by zanieb** [comment]
I thought we had `uv sync --package <name>` but I guess not? cc @konstin

**Comment by charliermarsh** [comment]
Oh me too. I will add it.

**Comment by charliermarsh** [comment]
To be clear, this would be intended to support installing a specific _member_ (like `package/package_a` above), rather than installing a specific transitive dependency (like `flask` or whatever).

**Comment by bschoenmaeckers** [comment]
Thanks a lot! This will do for my usecase.
