### ISSUE TITLE
`uv add` changes pyproject.toml indentation

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5009]
When using `uv add` on a `project.dependencies` with indentation 2, it changes the indentation to 4 for the entire list, creating a big diff. `uv add` should instead respect the existing indentation.

**Comment by flyaroundme** [comment]
To me it looks like not being possible if using only `toml_edit` rust crate that is currently used. Seems like it requires to fork `toml_edit` to respect indentation while (de)serializing toml files heh

**Comment by charliermarsh** [comment]
What about in `reformat_array_multiline`? It seems like we unequivocally add four spaces there.

**Comment by flyaroundme** [comment]
Ah yeah exactly, missed that

**Comment by flyaroundme** [comment]
I'm working on it, reworking `reformat_array_multiline`, so you can assign to me
