### ISSUE TITLE
Reject versions when there is no source dist and all wheels mismatch the python requirement

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5012]
For [torch 1.10.0](https://pypi.org/project/torch/1.10.0/#files), there are wheel for python 3.6 - python 3.9, and there is no source dist. We should reject this version when resolving for python >= 3.10 since there is never any compatible wheel.

**Comment by charliermarsh** [comment]
This actually seems pretty hard now that we do our `requires-python` checks outside of the version map... Not sure how to do it.
