### ISSUE TITLE
`uv tool install` should hint correct package when executable is provided by a dependency

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5018]
e.g. this command works:

```
uvx fastapi
```

but

```
uv tool install fastapi
```

fails because `fastapi` is provided by `fastapi-cli` (see #5017 for details).

In this error case, `uv tool install` should detect that an executable matching the requested package name is provided by a dependency and suggest `uv tool install fastapi-cli` instead.

**Comment by charliermarsh** [comment]
That's a nice idea. Somewhat expensive but not terrible (and it's an error case anyway).

**Comment by zanieb** [comment]
Yeah I don't love scanning the entire site packages for executables but since it's on-error 🤷‍♀️ we could limit to direct dependencies if we wanted to optimize later.

**Comment by charliermarsh** [comment]
Should be cheap, it's just reading `RECORD` files.

**Comment by blueraft** [comment]
I can pick this one up!
