### ISSUE TITLE
relative URLs in README show up as broken links on https://pypi.org/project/uv/

### ISSUE THREAD

**Issue by ben-albrecht** [astral-sh/uv#5030]
Relative paths, such as the links to `PIP_COMPATIBILITY.md` show up as broken links on [PyPI page](https://pypi.org/project/uv/), e.g. https://pypi.org/project/uv/PIP_COMPATIBILITY.md/

fwiw, the pypi page is the top result when google searching "uv python".

**Comment by charliermarsh** [comment]
Thanks, I’ll fix this shortly. We do it correctly in Ruff but it’s a little tedious.
