### ISSUE TITLE
Simplify union of marker expression and negation

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5044]
We currently don't simplify the union of marker expression and its negation, e.g. `sys_platform == 'darwin' or sys_platform != 'darwin'`.

As an example, for `echo "colabfold==1.5.5" | cargo run pip compile -p 3.12 --universal -`, we get:

```
[...]
tensorflow-macos==2.13.1 ; sys_platform == 'darwin'
    # via colabfold
[...]
werkzeug==3.0.3 ; sys_platform == 'darwin' or sys_platform != 'darwin'
    # via tensorboard
wheel==0.43.0 ; sys_platform == 'darwin' or sys_platform != 'darwin'
    # via
    #   astunparse
    #   tensorboard
wrapt==1.16.0 ; sys_platform == 'darwin' or sys_platform != 'darwin'
    # via
    #   tensorflow-cpu
    #   tensorflow-macos
zipp==3.19.2
    # via importlib-metadata
```

The above `sys_platform == 'darwin' or sys_platform != 'darwin'` markers should be elided, these package aren't fork dependent.

**Comment by charliermarsh** [comment]
Good call.

**Comment by charliermarsh** [comment]
\cc @ibraheemdev
