### ISSUE TITLE
Non-universal resolver should ignore requires-python upper bound

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5045]
Without universal resolution, we fail to resolve colabfold 1.5.5 on python 3.12, since it [only supports python 3.9 to 3.11](https://inspector.pypi.io/project/colabfold/1.5.5/packages/8e/74/52a6580a05c4f85980d449fbf71ead514bef0d0548c218abb808106f1a41/colabfold-1.5.5-py3-none-any.whl/colabfold-1.5.5.dist-info/METADATA#line.9):

```
$ echo "colabfold==1.5.5" | uv pip compile -p 3.12 -
    × No solution found when resolving dependencies:
    ╰─▶ Because the requested Python version (3.12.0) does not satisfy Python>=3.9,<3.12 and colabfold==1.5.5 depends on
        Python>=3.9,<3.12, we can conclude that colabfold==1.5.5 cannot be used.
        And because you require colabfold==1.5.5, we can conclude that the requirements are unsatisfiable.
```

We generally ignore upper version bounds (#4022), the universal resolver also resolves succesfully:

```
$ echo "colabfold==1.5.5" | uv pip compile -p 3.12 --universal -
Resolved 62 packages in 23ms
[...]
colabfold==1.5.5
[...]
```

We should change the regular resolver to ignore this requires-python upper bound, too, and make it clear in the docs that we ignore all requires-python upper bounds.

**Comment by charliermarsh** [comment]
Why is the extra relevant?

**Comment by konstin** [comment]
We should error both with and without extra due to the mismatch in the python requirement, after finding uv behaves different depending on whether an extra is present (#5043), i'm just testing both cases. Fwiw without the extra the resolution is simple (it's a stub, functionality-wise), with the extra it's a complex machine learning tree.

**Comment by charliermarsh** [comment]
This is correct though. We do _not_ respect upper-bounds on `requires-python`.

**Comment by charliermarsh** [comment]
`uv pip compile -p 3.12 -` is resolving for Python 3.12, while `uv pip compile -p 3.12 --universal -` is treated as `requires-python: ">=3.12"`. This is mentioned in the documentation.

**Comment by konstin** [comment]
I've changed the issue to changing the regular resolver instead of the universal resolver. We should also make it clearer in the docs that we ignore all upper bounds on requires-python, at least i couldn't find that information when looking for it.
