### ISSUE TITLE
Provide a flag to disable spinner during uv pip sync/install

### ISSUE THREAD

**Issue by samj1912** [astral-sh/uv#5082]
uv currently renders a spinner that might make it difficult to render logs in browser/web components easily as it can spew a lot of output. It would be great if uv could expose a flag similar to pip to disable the progress bar/spinner.

**Comment by charliermarsh** [comment]
Yeah we should support `--no-progress` or something.

**Comment by zanieb** [comment]
I felt like we had a discussion about this when adding the progress bars but can't find anything.

**Comment by silvanocerza** [comment]
A global `--no-progress-bar` option is a good idea I think. 

I can take care of this, though I don't know all the commands that print progress bars.

**Comment by charliermarsh** [comment]
IIRC we decided that we wanted to add it, but punted on it at the time :)
