### ISSUE TITLE
UV ignore pypi index-url when extra-index-url set.

### ISSUE THREAD

**Issue by kimdwkimdw** [astral-sh/uv#5096]
uv's index-url didn't work in ENVVAR or command args. https://github.com/astral-sh/uv?tab=readme-ov-file#environment-variables

## it should work, but didn't work - (1)
- pip's default index-url is "https://pypi.org/simple".

```
[tool.uv.pip]
extra-index-url = ["https://pypi.custom.ai/"]
```

## it should work, but didn't work - (2)
```
[tool.uv.pip]
index-url= "https://pypi.org/simple"
extra-index-url = ["https://pypi.custom.ai/"]
```

## current workaround

```
[tool.uv.pip]
extra-index-url = ["https://pypi.org/simple", "https://pypi.custom.ai/"]
```

**Comment by j178** [comment]
Please check https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes and `uv help compile`:
```   
   --extra-index-url <EXTRA_INDEX_URL>
          Extra URLs of package indexes to use, in addition to `--index-url`.

          Accepts either a repository compliant with PEP 503 (the simple repository
          API), or a local directory laid out in the same format.

          All indexes given via this flag take priority over the index in
          `--index-url` (which defaults to PyPI). And when multiple
          `--extra-index-url` flags are given, earlier values take priority.

          [env: UV_EXTRA_INDEX_URL=]    

   --index-strategy <INDEX_STRATEGY>
          The strategy to use when resolving against multiple index URLs.

          By default, `uv` will stop at the first index on which a given package is
          available, and limit resolutions to those present on that first index
          (`first-match`). This prevents "dependency confusion" attacks, whereby an
          attack can upload a malicious package under the same name to a secondary.

          [env: UV_INDEX_STRATEGY=]

          Possible values:
          - first-index:        Only use results from the first index that returns a
            match for a given package name
          - unsafe-first-match: Search for every package name across all indexes,
            exhausting the versions from the first index before moving on to the
            next
          - unsafe-best-match:  Search for every package name across all indexes,
            preferring the "best" version found. If a package version is in multiple
            indexes, only look at the entry for the first index
```

**Comment by kimdwkimdw** [comment]
@j178 

Sorry, I didn’t thoroughly review the documentation. It would be better if it supports the same functionality as pip in the future.

**Comment by notatallshaw** [comment]
> It would be better if it supports the same functionality as pip in the future.

FYI uv's default behavior is more secure than pip's and should mitigate real world attacks:  https://pytorch.org/blog/compromised-nightly-dependency/

**Comment by shoang22** [comment]
Hi, I'm running into this same issue. I'm not sure what I'm supposed to do to get UV to fall back to the default index.

**Comment by Sairam90** [comment]
If --extra-index-url and --index-url are both specified which url will be searched first ?
In my case I specify --index url <pypi> --extra-index-url <firm pypi> and uv only looks in extra index url and package is not installed as it's not available there - It doesnt search for the missing packages in index-url
