### ISSUE TITLE
Allow override of dependencies

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#511]
A user should be able to override the constraints of a package, ignoring transitive requirements that conflict.

This would, for example, allow "force" installation of a certain package version that the user _knows_ works even if a dependency does not allow it.

Related https://github.com/mitsuhiko/rye/issues/505
Discussion at https://discord.com/channels/1039017663004942429/1148719284013510676/1164668058644795453

At its simplest, for a `pip-compile` interface, this could just be another file with package version specifiers e.g. `overrides.txt` that you can pass via an `--overrides` flag. An override for a package would be specified as in `requirements.txt` and `constraints.txt`.

**Comment by aidando73** [comment]
Hello all. Thanks for implementing this.

It just came in handy today. My nodes needed a special pytorch version to leverage a special networking hardware for LLM training but there was a conflict with another package.

Thanks 🙏
