### ISSUE TITLE
`uv lock` rejects wheels from the PyTorch index

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5120]
These don't have hashes, so the lockfile rejects them. We either need to loosen that constraint, or compute hashes for all wheels from indexes that lack them.

**Comment by BurntSushi** [comment]
Ref #4924

**Comment by dimbleby** [comment]
per the last few comments at https://github.com/pytorch/pytorch/issues/76557: pytorch indexes mostly do have hashes these days.

While automating the process has apparently had its hiccups - they seem willing to engage with requests to fix cases where the hashes are missing.

**Comment by charliermarsh** [comment]
Oh nice! (We do still need this in general since not all registries will have hashes, but that's really helpful.)
