### ISSUE TITLE
Bug: `uv help pip compile` failing with `error: program not found`

### ISSUE THREAD

**Issue by jbw-vtl** [astral-sh/uv#5124]
Running the command `uv help pip compile -v` is failing with

```text
DEBUG uv 0.2.25
error: program not found
```

As advised by @zanieb, `uv help pip compile --no-pager` is working as expected.
Additionally `uv pip compile --help` is working aswell, however the output differs from the above command in structure & content.

```
uv==0.2.25
python==3.11.9
Running on Windows
```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by zanieb** [comment]
This sounds like the dreaded "`which` finds executables differently then spawning a process on Windows". I have no idea why Cargo doesn't have this problem, as we used their implementation here. We might be able to just pass the path discovered by `which` to the subprocess invocation?

**Comment by jbw-vtl** [comment]
Running the `uv help pip compile` in bash on windows works (with the same versions as stated above).
Running within Powershell (tried multiple versions) and CMD both fails with the `error: program not found`

`which` is by default not available in Powershell (using `get-command uv`) / Cmd (using `where uv`)

**Comment by zanieb** [comment]
Note I'm referring to the `which` implementation in Rust, not the executable program.

**Comment by zanieb** [comment]
I've remembered that Cargo uses a custom "resolve_executables" method instead of `which` which is probably why they do not suffer from this problem.

**Comment by zanieb** [comment]
Just to confirm, this works as intended if the pager is not found by `which`:

```
PATH="" ~/.cargo/bin/uv help pip
```

**Comment by charliermarsh** [comment]
@zanieb - Do you think we can fix this for a release today?

**Comment by charliermarsh** [comment]
I can test it.

**Comment by jbw-vtl** [comment]
Can confirm working well with the latest version, thanks a bunch

**Comment by charliermarsh** [comment]
Awesome, thank you.
