### ISSUE TITLE
BUG: resolution failure in `uv pip` where `python -m pip` suceeds

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/uv#5143]
Right now, trying to install `matplotlib` nightlies as follows
```shell
uv venv -p 3.12
source .venv/bin/activate
uv pip install matplotlib --only-binary ":all:" --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
```
fails with

```
  × No solution found when resolving dependencies:
  ╰─▶ Because pillow==11.0.0.dev0 has no wheels are available with a matching Python ABI and only the following versions of pillow are available:
          pillow<8
          pillow==11.0.0.dev0
      we can conclude that all versions of pillow cannot be used.
      And because all versions of matplotlib depend on pillow, we can conclude that all versions of matplotlib cannot be used.
      And because only the following versions of matplotlib are available:
          matplotlib==3.10.0.dev370+g6b7b999274
          matplotlib==3.10.0.dev378+g830361d544
          matplotlib==3.10.0.dev384+g8b33378746
          matplotlib==3.10.0.dev395+gdc649460f7
          matplotlib==3.10.0.dev401+g9b8a8c7246
      and you require matplotlib, we can conclude that the requirements are unsatisfiable.
```
(this is uv 0.2.25, but I've seen this with 0.2.18 too)
[example logs](https://github.com/yt-project/cmyt/actions/runs/9967437982/job/27541120876)

`pillow==11.0.0.dev0` is actually not a constraint I'm imposing, it's just the only version that's available at the moment from `https://pypi.anaconda.org/scientific-python-nightly-wheels/simple`, but there's only one wheel and it doesn't match my env (I request Python 3.12, this wheel is cp311). This looks like a bug to me: as I'm not imposing a constraint on `pillow`, and I'm only passing `--extra-index-url` (as opposed to `--index-url`), `uv` should be able to pick up a wheel from pypi.org

Furthermore, `pip` succeeds in the same scenario
```
python -m pip install matplotlib --only-binary ":all:" --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
```
```
...
Successfully installed contourpy-1.3.0.dev1 cycler-0.12.1 fonttools-4.53.1 kiwisolver-1.4.5 matplotlib-3.10.0.dev401+g9b8a8c7246 numpy-2.1.0.dev0 packaging-24.1 pillow-10.4.0 pyparsing-3.1.2 python-dateutil-2.9.0.post0 six-1.16.0
```

reporting the resulting with `uv pip tree` for legibility (and because this tool rocks)
```
❯ uv pip tree --package matplotlib
matplotlib v3.10.0.dev401+g9b8a8c7246
├── contourpy v1.3.0.dev1
│   └── numpy v2.1.0.dev0
├── cycler v0.12.1
├── fonttools v4.53.1
├── kiwisolver v1.4.5
├── numpy v2.1.0.dev0
├── packaging v24.1
├── pillow v10.4.0
├── pyparsing v3.1.2
└── python-dateutil v2.9.0.post0
    └── six v1.16.0
```

**Comment by konstin** [comment]
uv differs in its handling of extra index urls from pip (https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes). In your case, you need to pick a different `--index-strategy` value if you want uv to fallback to pypi.

**Comment by neutrinoceros** [comment]
Oh, I didn't remember this from when I read the compatibility guide, I should have gone back to it !
Thank you for your snappy response, `--index-strategy=unsafe-best-match` is indeed what I need.
