### ISSUE TITLE
Suggestion: Custom error message when resolution fails and there are multiple indexes specified

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#5146]
With the same reasoning as https://github.com/astral-sh/uv/pull/5041, a common support issue on this tracker is that the user needs to pick a different index strategy to replicate their pip workflow.

IMO this custom error message should point out the default behavior mitigates certain supply chain attacks, or give some reason why the default is the default. And to update the message if/when PyPI and uv supports PEP 708 to suggest that as the "correct" solution.

**Comment by zanieb** [comment]
Totally agree, but I think this is a duplicate of https://github.com/astral-sh/uv/issues/4389

**Comment by notatallshaw** [comment]
I agree it's close enough to your suggestion in comment https://github.com/astral-sh/uv/issues/4389#issuecomment-2177284244 to be a duplicate of that.

**Comment by zanieb** [comment]
Seems a little challenging but I'd love to see someone take it on :)
