### ISSUE TITLE
feature: support `--link-mode=symlink`

### ISSUE THREAD

**Issue by hutch3232** [astral-sh/uv#5147]
Currently `--link-mode` supports `copy`, `hardlink`, and `clone`. I have my `UV_CACHE_DIR` set to a mounted drive which prevents hardlinks and cloning ("invalid cross-device link"). Symlinks would work, however. This could really increase performance for my situation, rather than copying over a bunch of files. When I work in R, I use `renv` which uses symlinks to a central cache successfully in the proposed way: https://github.com/rstudio/renv.

More details about the specific use-case:
I work in ephemeral docker containers. My workflow is generally to start by running `uv pip sync requirements.txt` which currently is triggering a copy for each package. I mount a persistent drive to my container so that my `uv` cache persists from session to session. Also worth noting that some collaborators mount the same drive and use the same cache, so that we benefit from each others' install time. Hopefully that isn't too risky, but it has worked well so far and works great in the aforementioned `renv` package in R.

Related issue:
https://github.com/astral-sh/uv/issues/2103

Thanks for making this amazing project!

**Comment by charliermarsh** [comment]
I don't mind supporting this, I was kinda waiting for it to be requested.

**Comment by charliermarsh** [comment]
Should be straightforward-ish if anyone wants to submit a PR -- it'd basically be copying the hardlink code, but changing the operation we use at the end.

**Comment by danielenricocahall** [comment]
Hi @charliermarsh! Would it be a matter of swapping `fs::hard_link` for `std::os::unix::fs::symlink` (after adding a `Symlink` value to the enum and mapping it to a new callable?

**Comment by charliermarsh** [comment]
@danielenricocahall - Yeah that sounds roughly correct to me.

**Comment by charliermarsh** [comment]
We'll also need `std::os::windows::fs::symlink_file` or similar on Windows which will probably fail for most people due to how symlink permissions work on Windows, but that's fine, they just shouldn't opt-in to this mode if they haven't enabled symlinks :)

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/5208. Thanks @danielenricocahall!

**Comment by helderco** [comment]
I was about to ask for this for the same reasons and just found out it’s been released already! 🎉

**Comment by skshetry** [comment]
I wonder if `uv` can symlink packages directly instead of per-file (similar to `virtualenv --symlink-app-data`). On macOS, you can also clone a directory, but I see that `uv` already does just that.

**Comment by charliermarsh** [comment]
That’s a good idea. We should probably symlink at the directory level.

**Comment by charliermarsh** [comment]
https://github.com/astral-sh/uv/issues/5244

**Comment by frainfreeze** [comment]
are there docs for this?

**Comment by hutch3232** [comment]
https://docs.astral.sh/uv/reference/settings/#link-mode

The docs mention and I'll emphasize that the devs (with good reasons) discourage using symlinks.

Anecdotally they've worked tremendously well for me. I've been using them every work day since this feature was released.
