### ISSUE TITLE
Lockfile-normalized marker representation

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5179]
We need to decide on which normalization we want for markers in the lockfile, and implement the algorithm that performs this normalization. For example, #5163 introduces:
```
(python_full_version <= '3.10' and python_version == '3.10') or (python_full_version <= '3.10' and python_version < '3.10') or (python_full_version <= '3.10' and python_version < '3.10' and python_version > '3.10') or (python_full_version <= '3.10' and python_version > '3.10') or (python_full_version > '3.10' and python_version == '3.10') or (python_full_version > '3.10' and python_version < '3.10') or (python_full_version > '3.10' and python_version < '3.10' and python_version > '3.10') or (python_full_version > '3.10' and python_version > '3.10')
```

This marker can be (completely) collapsed, in the current form it's not readable.

Since the marker representation changes the lockfile, we need a stable representation.

**Comment by ibraheemdev** [comment]
We now markers in a simplified DNF form. Our simplification is not perfect, but it seems to work well in practice. See https://github.com/astral-sh/uv/issues/5992 for whether we should write as CNF in some cases, but for now I think we're in a good place.

**Comment by charliermarsh** [comment]
Awesome.
