### ISSUE TITLE
libgit2 shouldn't put write protection on git files in the cache

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#518]
Currently, when you try to remove a cache directory with a git checkout inside of it, `rm -r` complains.

```console
$ rm -r cache-all-kinds/
rm: remove write-protected regular file 'cache-all-kinds/git-v0/db/b49ffcfeb6c2e9d8/objects/pack/pack-c5780a0de30c59b83bb4638f5e8cd70797848444.pack'? 
```

Since this is only a cache directory, libgit2 shouldn't apply write protection that prevents removing it.

**Comment by charliermarsh** [comment]
Our `uv cache clean` handles this correctly.
