### ISSUE TITLE
Feature request: option to not update `uv.lock` file

### ISSUE THREAD

**Issue by kdeldycke** [astral-sh/uv#5185]
Using the latest `uv`:
```shell-session
$ uv --version
uv 0.2.26 (fe403576c 2024-07-17)
```

## Description

When I call a `uv run`, I get the `uv.lock` updated and kept in sync automatically. I would like to have a way to tell `uv` to not change the `uv.lock` file at all.

## Context

I am maintaining several Python-based CLI. To keep their Sphinx-based documentation up-to-date, I rely on a [reusable GitHub workflow that calls `uv run sphinx-apidoc`](https://github.com/kdeldycke/workflows/blob/5e7bc19e5d56453c42dd97979bcb773a0c412e3b/.github/workflows/docs.yaml#L264-L308).

The problem is that while `uv run sphinx-apidoc` is doing its job producing auto-generated documentation, that way of invoking it is also updating the `uv.lock` file at the base of the checked-out repository.

And because my [last step of the workflow](https://github.com/kdeldycke/workflows/blob/5e7bc19e5d56453c42dd97979bcb773a0c412e3b/.github/workflows/docs.yaml#L292-L308) is creating a PR with all local changes, I end up with a noisy PR that not only contain the changes from `sphinx-apidoc`, but also unexpected updates in `uv.lock` file.

My quick fix was to add an [extra step to force its exclusion](https://github.com/kdeldycke/workflows/blob/7a42f59feacdb0b398a5614a541384d3b6792f14/.github/workflows/docs.yaml#L305-L309):
```yaml
      - name: Reset uv.lock
        # Exclude `uv.lock` file which might be auto-updated by calls to `uv run`.
        run: |
          git checkout -- uv.lock
```

And that's how I end up with a clean PR with only the changes produced by `sphinx-apidoc`.

Now I just wonder if it might be a good idea to add a new option to `uv`, to let it restrain itself and keep `uv.lock` as it found it. Something like `uv run --no-lock-update`.

## Discussion

If keeping the `uv.lock` in sync is good for everyday run, the reason I do not need that behavior in automated workflows is because I already have [another dedicated job to keep it in sync](https://github.com/kdeldycke/workflows/blob/7a42f59feacdb0b398a5614a541384d3b6792f14/.github/workflows/autofix.yaml#L264-L304).

**Comment by charliermarsh** [comment]
We have these options on uv sync already, I meant to add them to uv run.

**Comment by charliermarsh** [comment]
I'll likely ship this today.

**Comment by kdeldycke** [comment]
Oh wow, that was fast! Thanks @charliermarsh for the quick addition! 🤗
