### ISSUE TITLE
Add `uv tool upgrade` to upgrade a tool

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5188]
e.g. given `uv tool upgrade <package name>` we'd upgrade the tool associated with the package to the latest version within the constraints. The user cannot specify new constraints here, they'd need to use `uv tool install` for that.

**Comment by zanieb** [comment]
I think the main benefit of this design is that we can provide an `upgrade --all` flag to upgrade all tools.

Otherwise I think this is equivalent to `uv tool install <name> --upgrade`?

**Comment by blueraft** [comment]
I can do this one
