### ISSUE TITLE
Make ``uv help <command>`` work on Windows(GUI) without using ``more``.

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/uv#5212]
**uv version**: build from commit 93ba676f(after uv v0.2.26)
In Windows(GUI), using the ``more`` is a bit cumbersome for me. It would be better to output everything at once and then I use the mouse to find the information I need.

![image](https://github.com/user-attachments/assets/78120cfb-81a7-43b7-a8d4-b7ef2ff10235)

**Comment by charliermarsh** [comment]
Defer to @zanieb.

**Comment by zanieb** [comment]
There's a `--no-pager` option to disable this behavior.

Can you say a bit more about "Windows(GUI)" and why that makes it preferable to scroll?

**Comment by FishAlchemist** [comment]
> There's a `--no-pager` option to disable this behavior.
> 
> Can you say a bit more about "Windows(GUI)" and why that makes it preferable to scroll?

``--no-pager`` seems to be a hidden parameter, I didn't see it in the help. <br>
But it does meet my requirements. <br>
Windows (GUI) only explicitly specifies the use of the graphical interface of Windows.
Q: why that makes it preferable to scroll? <br>
A: Since the help of CLI is not so much that I can't scroll through it with a mouse, I let it output all at once so I can use the mouse to find what I need, instead of using ``more`` to view it line by line.

**Comment by zanieb** [comment]
Yeah sorry I think there are some technical difficulties in getting it to display without displaying a bunch of other options. I've created an issue to track that at https://github.com/astral-sh/uv/issues/5221

Some of our help is really long and we only expect it to get longer. I think I'd prefer to stick to paging by default and let people opt-out as needed.
