### ISSUE TITLE
Support for "Updated" indicator on install/uninstall output

### ISSUE THREAD

**Issue by T-256** [astral-sh/uv#5213]
Ref https://github.com/astral-sh/uv/pull/5197#discussion_r1683553671

![image](https://github.com/user-attachments/assets/3c83a004-38a5-48ec-bf37-a3223fec27a1)

- only updated version of `from (url://)` is shown
- time is calculated on both uninstalling old version and installing new version

Example of output when installation contains all three actions (no color):
```
$ uv pip sync requirements.txt
Resolved 18 packages in 300ms
Prepared 1 package in 51ms
Uninstalled 1 package in 32ms
Installed 1 package in 28ms
Updated 1 package in 90ms
 ~ abc 0.1.3 -> 0.2.0 (from file:///E:/path/to/wheels/abc-0.2.0-py3-none-any.whl)
 - test==0.1.3
 + mypkg==0.2.0
```

**Comment by charliermarsh** [comment]
I think something like this would be a good change. I'm unsure on the right symbol (caret vs, e.g., dash?) and color for it. I assume that if the prior version was from a direct URL, we'd just omit it?

**Comment by T-256** [comment]
> I'm unsure on the right symbol (caret vs, e.g., dash?) and color for it.

Agree, since caret is stands for upper numbers, but we can have also downgraded numbers. I prefer it distinguished from -+ since it has both adding and removing. we can consider `~` or `*` since they are commonly used symbols in CLIs.



> I assume that if the prior version was from a direct URL, we'd just omit it?

We can either when both versions have url:
- show both urls (line becomes long)
- only show prior url (new version number will be on last of line)
- only show updated url (prior url not tracked)
- fallback to -+ when both have url (inconsistency)

**Comment by charliermarsh** [comment]
I think `~` would be reasonable... Or `>` and `<` for upgrade and downgrade...? Is that ridiculus? Not sure if there's prior art to draw on here.

**Comment by T-256** [comment]
> Or `>` and `<` for upgrade and downgrade...?

What if version number didn't change? using `=` ? I agree with `>`, '<' and '=' while they also come with reasonable colors. otherwise, they may bring some confusion.

**Comment by charliermarsh** [comment]
I think I'd be fine with `~` in either yellow or blue.

**Comment by j178** [comment]
or `↑`  (U+2191) and `↓`  (U+2193)?

**Comment by T-256** [comment]
> I think I'd be fine with `~` in either yellow or blue.

Updated description with tilde and blue color since yellow was hard to distinguished from white color.

> * only show updated url (prior url not tracked)

Do you know what's the point if someone may want to use prior url when updating a package? does it have any use case?

**Comment by charliermarsh** [comment]
I think simplest is to show just the updated URL, it seems rare that the prior URL would be important.

**Comment by T-256** [comment]
Do we need do different when version number was same? e.g. editables mostly: 
```
 ~ abc 0.1.2 -> 0.1.2 (from file:///E:/path/to/projects/abc)
```
Perhaps could merge `0.1.2 -> 0.1.2` into one?

**Comment by T-256** [comment]
When it implemented, I think it's reasonable change sorting to action types? e.g. Updated packages shown first.

**Comment by charliermarsh** [comment]
I believe we now have `~` for updates.
