### ISSUE TITLE
`uv pip tree` should show version specifiers for dependencies.

### ISSUE THREAD

**Issue by Enayaaa** [astral-sh/uv#5217]
With `uv==0.2.26` it is not possible to see version specifiers in dependency graph.

I have used `pipdeptree` to find why some package is staying back. With version specifiers in the dependency tree you could find what package that depends on `foo` causes some dependency shared between multiple packages to stay back on an older version.
```console
$  pipdeptree -lrp apeye
apeye==1.4.1
├── pypi-json==0.4.0 [requires: apeye>=1.1.0]
│   └── relic-radar==0.1.dev62+g0574a5f.d20240716093527 [requires: pypi-json>=0.3,<1]
└── relic-radar==0.1.dev62+g0574a5f.d20240716093527 [requires: apeye>=0.5,<2]
```
With `pipdeptree` they are shown inside brackets after the version.

**Comment by charliermarsh** [comment]
That's a neat idea.

**Comment by zanieb** [comment]
This was actually in the original implementation and I asked it to be made opt-in: https://github.com/astral-sh/uv/pull/3859#issuecomment-2181683137 

I still think it's probably much noise for the default output, but am happy to have a flag that adds it? cc @ChannyClaus

**Comment by charliermarsh** [comment]
Yeah opt-in is cool with me. That makes sense.

**Comment by ChannyClaus** [comment]
i can do this sometime this weekend 🌵
