### ISSUE TITLE
Write integration guide for GitHub Actions

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5222]

**Comment by zanieb** [comment]
Started work on this in #5239 but it's missing caching due to some outstanding work determining efficient cache setup in CI.

**Comment by jbw-vtl** [comment]
Not directly GitHub actions related, however keen on some recommendations for handling UV cache in a CI environment such as GitHub / Jenkins etc.

There's a statement in the docs clearly documenting it's not safe to modify the cache manually

> Note that it's not safe to modify the uv cache directly (e.g., uv cache clean) while other uv commands are running, and never safe to modify the cache directly (e.g., by removing a file or directory).

However often in CI environments we might not want to have an infinitely growing cache, using cleanup configurations such as max cache sizes / keep by last used etc. However reading the above, worried that policies such as these might corrupt the cache / cause issues.
How would we cleanup caches safely in a CI environment, without having to drop the whole cache?
I.e. clean all artifacts not used in the last week, etc.

Do let me know if this should be tracked under a separate issue.

**Comment by zanieb** [comment]
Let's chat over in https://github.com/astral-sh/uv/issues/5409 since I technically wrote this integration guide
