### ISSUE TITLE
Support specifying mirror for `indygreg/python-build-standalone` in `uv python` 

### ISSUE THREAD

**Issue by Vigilans** [astral-sh/uv#5224]
Simliar to nodejs `nvm`'s [`NVM_NODEJS_ORG_MIRROR`](https://github.com/nvm-sh/nvm/blob/master/README.md#use-a-mirror-of-node-binaries) environment variable, `uv` may provide variable like `UV_PYTHON_INSTALL_MIRROR` to allow user to specify a mirror for `indygreg/python-build-standalone`'s github release.

### Proposal

A new env variable `UV_PYTHON_INSTALL_MIRROR`, to replace `python-build-standalone`'s github-release download url:
* Before: `https://github.com/indygreg/python-build-standalone/releases/download/20240713/cpython-3.12.4%2B20240713-aarch64-apple-darwin-install_only.tar.gz`
* After: `${UV_PYTHON_INSTALL_MIRROR}/20240713/cpython-3.12.4%2B20240713-aarch64-apple-darwin-install_only.tar.gz`

### Use case

Allows stable network when building container images from areas with restricted access or poor link quality to GitHub (e.g. private environment, or users from China).

Source of mirrors could be:
* Dedicated mirror sites
* Self-hosted github-release proxy like [hunshcn/gh-proxy](https://github.com/hunshcn/gh-proxy)

**Comment by charliermarsh** [comment]
Seems reasonable to me.
