### ISSUE TITLE
Should the Python version used to generate documentation in CONTRIBUTING docs be explicitly specified?

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/uv#5225]
Explicitly specify the Python version when creating the Python virtual environment for generating documentation.
Instead of letting UV only look for the Python available in the environment, it is suggested to specify the minimum required Python version.
https://github.com/astral-sh/uv/blob/12dd450a8e0f61ab503f9b93ecae2ccb049bcd06/CONTRIBUTING.md?plain=1#L126
I recommend explicitly specifying the Python version because the minimum Python version is specified when generating requirements file
https://github.com/astral-sh/uv/blob/12dd450a8e0f61ab503f9b93ecae2ccb049bcd06/CONTRIBUTING.md?plain=1#L160-L163
```
  -p, --python-version <PYTHON_VERSION> The minimum Python version that should be supported by the resolved requirements (e.g., `3.8` or `3.8.17`)
```
While the requirements file generated by UV uses environment markers as described in PEP 508, and should work fine, using the same Python environment is likely to be more stable.

**Comment by zanieb** [comment]
Sure, thanks! Ideally this will all change away from creating a virtual environment but we need #4973

**Comment by FishAlchemist** [comment]
> Sure, thanks! Ideally this will all change away from creating a virtual environment but we need #4973

In that PR, you said that you would complete it this week, so I should just wait for it to be completed and then you modify CONTRIBUTING. Or should I new a PR first to explicitly mention the minimum Python version?

**Comment by zanieb** [comment]
Probably worth waiting, I may just make it redundant it in the next couple days.

**Comment by FishAlchemist** [comment]
> Sure, thanks! Ideally this will all change away from creating a virtual environment but we need #4973

Since the PR has been merged, can we close this issue?
![image](https://github.com/user-attachments/assets/1b781482-fb1f-454f-9107-aab94a69fbc4)
Should it provide the minimum UV version or just use the latest one? From what I see in the commit history, this PR should be included in 0.2.28.
![image](https://github.com/user-attachments/assets/90bf0136-8b8a-4d8f-bbc0-bc61e9e88e1d)

**Comment by zanieb** [comment]
I wonder if we still want `uvx --python 3.12` 🤔

**Comment by FishAlchemist** [comment]
> I wonder if we still want `uvx --python 3.12` 🤔

The generated requirements.txt specifies -p 3.12, meaning that only minimum support for version 3.12 is guaranteed. Therefore, there is no assurance that it will function correctly in the future if version 3.12 or higher is not locally available.
However, considering only the current dependencies, Environment Markers are not being used, making them unnecessary at present.
