### ISSUE TITLE
Universal resolution needs documentation

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5237]
e.g in `docs/resolution.md#multi-platform-resolution` or in a new section after it.

**Comment by zanieb** [comment]
I'll do a first draft, but I'd appreciate if you gave it an edit.

**Comment by charliermarsh** [comment]
@zanieb -- Is this still needed? What's the right spot, if so?

**Comment by konstin** [comment]
I'm planning to write something up with the resolution changes i'm doing right now.
