### ISSUE TITLE
Typo in tools guide

### ISSUE THREAD

**Issue by iw** [astral-sh/uv#5243]
Apologies, 👀 were drawn to this typo in [guides/tools.md](https://github.com/astral-sh/uv/blob/841edc3718463f88821f63a76c20e6d6851dd7f7/docs/guides/tools.md?plain=1#L21):

> Arguments can be passed afted the tool name:

to

> Arguments can be passed after the tool name:

❤️ uv

**Comment by charliermarsh** [comment]
Thanks! PR welcome if you’re interested :)

**Comment by iw** [comment]
Absolutely. Mini delay due to 🐶 walking duty, then submit.
