### ISSUE TITLE
Should `uv init` create nested workspaces?

### ISSUE THREAD

**Issue by j178** [astral-sh/uv#5251]
```sh
$ uv init work
Initialized project work in /tmp/work
$ uv init work/pkg-a
Adding pkg-a as member of workspace /tmp/work
Initialized project pkg-a in /tmp/work/pkg-a
$ uv init work/pkg-a/pkg-inside-a
Adding pkg-inside-a as member of workspace /tmp/work
Initialized project pkg-inside-a in /tmp/work/pkg-a/pkg-inside-a
```

Content of `work/pyproject.toml`:
```toml
[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = []

[tool.uv]
dev-dependencies = []

[tool.uv.workspace]
members = ["pkg-a"]
```

Content of `work/pkg-a/pyproject.toml`:
```toml
[project]
name = "pkg-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = []

[tool.uv]
dev-dependencies = []

[tool.uv.workspace]
members = ["pkg-inside-a"]
```

The message from `uv init work/pkg-a/pkg-inside-a` indicates `Adding pkg-inside-a as member of workspace /tmp/work`. However it seems to be added to `/tmp/work/pkg-inside-a`, essentially  creating a workspace inside a workspace. Do we allow a workspace member itself being a workspace?

**Comment by konstin** [comment]
That's a bug, we should add `pkg-inside-a` to the workspace root at `work/pyproject.toml` and error when there's a workspace declaration in a workspace member.
