### ISSUE TITLE
`uv init` creates unimportable package subdirectory

### ISSUE THREAD

**Issue by InSyncWithFoo** [astral-sh/uv#5255]
Steps to reproduce:

* `mkdir a-b && cd a-b`
* `uv init`

This creates a package subdirectory with the same name as the project, but the project name is itself not a valid package name:

```shell
$ tree
.
├── README.md
├── pyproject.toml
└── src
    └── a-b
        └── __init__.py
```

Instead, the subdirectory should be named `a_b`, with `-` normalized.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
We also need to clean the module name (in `pyproject.toml`), since the rules there are different from module names (e.g., can contain dashes): https://packaging.python.org/en/latest/specifications/name-normalization/#name-format
