### ISSUE TITLE
`uv pip install` should support reasonable variations on `pythonw.exe` e.g. `.pythonw.exe`

### ISSUE THREAD

**Issue by paveldikov** [astral-sh/uv#5256]
When generating GUI script executables on Windows, `uv` will take `python_executable` and [try to replace the filename with a constant `"pythonw.exe"`](https://github.com/astral-sh/uv/blob/12518a01a4a436ba4c8b8cfc51646a253bcc8c6c/crates/install-wheel-rs/src/wheel.rs#L236-L247).

Whereas `pip` is slightly more subtle in this regard. It would [take the filename and replace the `python` component with `pythonw`](https://github.com/pypa/pip/blob/8eadcab329a765571c849efe370afd5d5bba425c/src/pip/_vendor/distlib/scripts.py#L121-L126). This allows for the executable name to be renamed (within reason) e.g. `.python.exe` and `.pythonw.exe` respectively.

Our use case here is that we generate relocatable virtual environments, and we deliberately rename the interpreter executable so as to avoid shadowing existing Python interpreters on the `$PATH`.

Happy to raise a PR, although I am new to Rust so you might have to bear with me futzing around a bit :-)

**Comment by charliermarsh** [comment]
It seems like a reasonable change to me. For stuff like this, pip is effectively a spec. Feel free to give it a try, thanks.

**Comment by paveldikov** [comment]
Raised #5259 :-)
