### ISSUE TITLE
Expose more fine-grained control for `uv sync` command

### ISSUE THREAD

**Issue by Vigilans** [astral-sh/uv#5258]
`uv sync` can be roughly divided into three steps:
1. Sync venv (uses `project.requires-python` in pyproject.toml)
2. Sync dependencies (uses `project.dependencies` in pyproject.toml)
3. Install project

User may demand more specific behaviors in the sync process. For example:
1. User may only want to sync venv. (Create a venv based on current project's `project.requires-python` in pyproject.toml)
2. User may only want to sync venv and install the dependency, but do not install the project. (https://github.com/astral-sh/uv/issues/4028, https://github.com/astral-sh/uv/issues/1516)
3. User may want to fully sync the environment, but install the project in editable mode.

---
Example 2 and 3 can be achieved with workaround if we have 1:
2. Use `uv pip install -r pyproject.toml` on the synced venv.
3. Use `uv pip install -e .` on the synced venv.

I would like to know do we have a way to only create venv based on `requires-python` in pyproject.toml?

**Comment by zanieb** [comment]
To respond in part: I think, in the future, `uv venv` will respect the `pyproject.toml` by default.
