### ISSUE TITLE
docs(style): Navigation bar is not properly covered by the footer

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5262]
Not only does the navigation text obscure some of the footer text, the navigation links are responsive through the footer.

<img width="610" alt="Screenshot 2024-07-21 at 12 28 34 PM" src="https://github.com/user-attachments/assets/e97faa12-785a-4289-88f4-a736e387c416">

**Comment by charliermarsh** [comment]
Do you think you should report this upstream? I don't think we do anything custom here.

**Comment by zanieb** [comment]
Probably — just noting it for now before investigating.

**Comment by zanieb** [comment]
I can't reproduce this now. Can you?

**Comment by charliermarsh** [comment]
I don't see it, no.

**Comment by zanieb** [comment]
Huh.
