### ISSUE TITLE
Add `--extracted` flag to `uv cache prune` to remove unzipped wheels

### ISSUE THREAD

**Issue by Jorricks** [astral-sh/uv#5282]
First of all, thank you for the awesome package. It's working blazingly fast and our developers are loving the new speed they have locally.

In our pipelines, the speed has not really improved. The main reason is that pip tools cache is considerably smaller than _uv_. When we store the _uv_ cache, the Gitlab pipeline is spending much more time on zipping the small files, then it is spending on downloading the files new. The difference is considerable; it's 2 times slower when we use Gitlab caches on the _uv_ cache.

A small app easily generates 16000 small files in _uv_ cache and easily comes to 
```
/builds/my_user/my_repository/.cache/uv: found 16373 matching artifact files and directories 
```

This is not only visible in Gitlab, but also in Github as mentioned in this ticket;
https://github.com/actions/setup-python/issues/822#issuecomment-1963717925

Would it maybe be possible to add a flag for CI/CD to concentrate the cache in larger files?

**Comment by konstin** [comment]
The uv cache contains all the wheels we install unpacked (in the `archive-v0` bucket), so we can install them quickly by reflinking or hardlinking. Those should be the many small files you're seeing. Does it work better when excluding that directory?

**Comment by Jorricks** [comment]
> The uv cache contains all the wheels we install unpacked (in the `archive-v0` bucket, linked to `wheels-v1`), so we can install them quickly by reflinking or hardlinking. Those should be the many small files you're seeing. Does it work better when excluding those directories?

Same package, wildly different result after running `rm -rf .cache/uv/archive-v0`;
```
/builds/bigdata/adyen_pyspark/.cache/uv: found 2675 matching artifact files and directories 
```

**Comment by Jorricks** [comment]
> I think you instead want `rm -rf .cache/uv/wheels-v1`, and then `uv cache prune`.

You seem to be right;
```
Caused by: failed to read directory `/builds/bigdata/adyen_pyspark/.cache/uv/archive-v0/3vlR8U66f3qKdzSrxDtyR`
```

**Comment by charliermarsh** [comment]
I think we should consider adding some options to `uv cache prune` to streamline this, since it's not good for users to be manipulating the cache arbitrarily (even though I told you to do it 11 minutes ago here :))

It doesn't make a ton of sense to be storing `.cache/uv/wheels-v1` in the CI cache, since you're just downloading and unzipping it in future jobs anyway. The only difference being that you're getting it from GitLab rather than PyPI or similar.

**Comment by charliermarsh** [comment]
If you see improvement with something like `rm -rf .cache/uv/wheels-v1` and `uv cache prune`, that would be good to know...

**Comment by Jorricks** [comment]
Interestingly enough, when I execute;
```
    - rm -rf ${CI_PROJECT_DIR}/.cache/uv/wheels-v1
    - uv cache prune --cache-dir ${CI_PROJECT_DIR}/.cache/uv
```
I get
```
/builds/bigdata/adyen_pyspark/.cache/uv: found 3035 matching artifact files and directories 
```

I kinda expected less matching artifact files then when I just ran `rm -rf .cache/uv/wheels-v1`. Does it make sense it's more?

**Comment by charliermarsh** [comment]
I think "more" is correct. With `rm -rf .cache/uv/archive-v0`, you were likely removing some directories that were symlinked elsewhere in the cache (causing those `failed to read directory` errors). So you were removing too many entries before.

**Comment by Jorricks** [comment]
It seems most of it is coming from one big package; `pyspark==3.2.3`:
```
[2024-07-22 16:09:28] 269M	../.cache/uv/built-wheels-v3/index/fd2c9579c1c6f924/pyspark/3.2.3/unfW3Zpiflv9HaTeaDE6C/pyspark-3.2.3-py2.py3-none-any.whl
[2024-07-22 16:09:28] 35M	         ../.cache/uv/built-wheels-v3/index/fd2c9579c1c6f924/pyspark/3.2.3/unfW3Zpiflv9HaTeaDE6C/pyspark-3.2.3.tar.gz/deps/jars/rocksdbjni-6.20.3.jar
[2024-07-22 16:09:28] 35M	          ../.cache/uv/built-wheels-v3/index/fd2c9579c1c6f924/pyspark/3.2.3/unfW3Zpiflv9HaTeaDE6C/pyspark-3.2.3.tar.gz/build/lib/pyspark/jars/rocksdbjni-6.20.3.jar
```

It contains the large Wheel and then it also contains the extracted items. The 90 biggest files are all Jars from this specific wheel. Is there a way to remove these JARs / extracted files?

**Comment by charliermarsh** [comment]
You could run `uv cache clean pyspark` to remove the PySpark entries specifically. But you'll then have to rebuild it on every CI job?

**Comment by Jorricks** [comment]
> It seems most of it is coming from one big package; `pyspark==3.2.3`:

Wow.. It seems that was 858.0MB of the 1.2G, as we have 311MB remaining -> 73% was taken from one package.
While the wheel itself was 269MB.
```
[2024-07-22 17:49:34] $ uv cache clean pyspark --cache-dir .cache/uv
[2024-07-22 17:49:34] Removed 1474 files for pyspark (858.0MiB)
[2024-07-22 17:49:34] $ du -sh .cache/uv
[2024-07-22 17:49:34] 311M	.cache/uv
```

I think `uv` would really benefit from having an option to cache all the artifacts but not storing the extracted files.

**Comment by charliermarsh** [comment]
Like, store the built wheel, but none of the unzipped archives? We could probably support that.

**Comment by Jorricks** [comment]
> Like, store the built wheel, but none of the unzipped archives? We could probably support that.

Exactly that. At that point, caching the `uv cache` in CI/CD runners would make sense. At this point it's better to just discard it.

**Comment by charliermarsh** [comment]
It would be easy to support `uv cache prune --extracted` or something, to delete all the extracted files prior to uploading the cache. Think that's worth trying...?

We _could_ also support unzipping the wheel directly into the virtual environment (rather than to the cache first). That's probably the "right" solution for this use-case, but it's a lot more work. (For pre-built wheels that we download from a registry, we don't even _save_ the wheel itself -- we unzip the extracted files directly to disk.)

**Comment by Jorricks** [comment]
> It would be easy to support `uv cache prune --extracted` or something, to delete all the extracted files prior to uploading the cache. Think that's worth trying...?
> 
> We _could_ also support unzipping the wheel directly into the virtual environment (rather than to the cache first). That's probably the "right" solution for this use-case, but it's a lot more work. (For pre-built wheels that we download from a registry, we don't even _save_ the wheel itself -- we unzip the extracted files directly to disk.)

I think the first part would fit my use-case perfectly. At first I was thinking of an environment variable like `UV_MINIFY_CACHE`, but I think making it a separate action such as `uv cache prune --extracted` is probably more in line with what is really happening. That is because I am assuming that this directly hurts the performance of the next `uv` run as well in case it needs to reinstall one of the (earlier) unpacked packages? So if you run multiple `uv pip sync` operations, where run 1 installs, run 2 uninstalls and run 3 installs it again, you might still want the output of the previous runs around.
Also the cleanup commands are incredibly fast, so there is no problem for me running that 👍

**Comment by charliermarsh** [comment]
Added here: https://github.com/astral-sh/uv/pull/5391
