### ISSUE TITLE
Missing files after uv pip install

### ISSUE THREAD

**Issue by rnarma321** [astral-sh/uv#5315]
Command: ```uv pip install kivymd==1.1.1```
This package should have .kv files inside of it, but when i use uv pip install vs pip install they are missing.
There are no issues popped up during the install, even in verbose mode

The tar.gz is pulls from has these files, I checked manually, Im not exactly sure what is causing this, but I tried across two version 0.2.27 and 0.2.0, along with two different OSs with mac and debian 12 bookworm and got the same results with every combination.

``` DEBUG Adding direct dependency: kivymd==1.1.1
DEBUG Found fresh response for: https://pypi.org/simple/kivymd/
DEBUG Searching for a compatible version of kivymd (==1.1.1)
DEBUG Selecting: kivymd==1.1.1 (kivymd-1.1.1.tar.gz)
DEBUG Trying to lock if free: /Users/roshan/Library/Caches/uv/built-wheels-v3/pypi/kivymd/1.1.1/.lock
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/35/55/d979644cdc9070a9611ab023db986aa0d540fc8f5fdd2c0f49eaef558751/kivymd-1.1.1.tar.gz
DEBUG Using cached metadata for: kivymd==1.1.1
DEBUG Adding transitive dependency for kivymd==1.1.1: kivy>=2.0.0
DEBUG Adding transitive dependency for kivymd==1.1.1: pillow* ````

**Comment by charliermarsh** [comment]
Where are those files supposed to be exactly?

**Comment by rnarma321** [comment]
an example can be found under .venv/lib/python3.10/site-packages/kivymd/uix/button/button.kv. This file will exist under pip but never showed up with uv pip

**Comment by zanieb** [comment]
For reference, this is included in the `package_data`: https://github.com/kivymd/KivyMD/blob/b5bc79fb71312868be86580b7b32f676926ceb80/setup.py#L102

**Comment by rnarma321** [comment]
So actually that is interesting, it doesn't have the .pot files or the .po files. But it seems to have the .ttf files and the .pngs. Maybe something about the pathing it generates from the "glob_paths" function it calls breaks with uv but not with pip

**Comment by charliermarsh** [comment]
Do you see any more consistency when you run `pip install --use-pep517`, and compare that to uv?

**Comment by rnarma321** [comment]
Nope, the pip install using pep517 flag still gives the .kv files, unlike uv which is missing it

**Comment by charliermarsh** [comment]
Ok, I figured this out. Their `setup.py` assumes that there is no directory named `kivymd` in the path apart from the one at the top-level. But in our cache, we nest the build under a directory called `kivymd`

E.g., here's one path in the cache: `Users/crmarsh/workspace/uv/foo/built-wheels-v3/pypi/kivymd/1.1.1/_kyEDLdSRqebDVYQM_lQA/kivymd-1.1.1.tar.gz/kivymd/uix/textfield/textfield.kv`

So it's truncating at the first `kivymd`.

I consider this a bug in the package itself, it's effectively not relocatable. I think they need to change `out_files.append(filepath.split(f"kivymd{os.sep}")[1])` to `out_files.append(filepath.split(f"kivymd{os.sep}")[-1])` in the `setup.py`.

**Comment by charliermarsh** [comment]
I created an issue here: https://github.com/kivymd/KivyMD/issues/1722
