### ISSUE TITLE
`uv init` should support creating a workspace

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5338]
I want to create a workspace layout quickly :)

**Comment by j178** [comment]
How about something like `uv init root --members foo bar/baz` to create a workspace structure like this:
```console
root
├── README.md
├── bar
│   └── baz
│       ├── README.md
│       ├── pyproject.toml
│       └── src
│           └── baz
│               └── __init__.py
├── foo
│   ├── README.md
│   ├── pyproject.toml
│   └── src
│       └── foo
│           └── __init__.py
├── pyproject.toml
└── src
    └── root
        └── __init__.py
```

We might need another flag to determine whether the root project is virtual or not.

**Comment by zanieb** [comment]
Well... it might be fine to just create workspace members _after_ the first one is created. Maybe this was just blocked by one of the `init` bugs.

e.g.

```
❯ uv init
Initialized project `example`
❯ uv init ./foo
Adding `foo` as member of workspace `/Users/zb/workspace/example`
Initialized project `foo` at `/Users/zb/workspace/example/foo`
```

Seems okay? A `uv init --virtual` flag could cover the remaining use-case, right?

**Comment by charliermarsh** [comment]
Yeah that all seems ok. `--virtual` could be useful.
