### ISSUE TITLE
`Using uv in GitHub Actions` docs page is blank on website

### ISSUE THREAD

**Issue by schloerke** [astral-sh/uv#5345]
Source file with a lot of content: https://github.com/astral-sh/uv/blob/0f8186d9adde63be0b8ff4af28b5adb2f287374b/docs/guides/integration/github.md

Screenshot of hosted page with missing content: ![Screenshot 2024-07-23 at 12 32 58 PM](https://github.com/user-attachments/assets/b22759f9-f52e-476f-852a-251730dd8dfe)

-------------

I don't know why it's missing. But thank you for this section: https://github.com/astral-sh/uv/blob/0f8186d9adde63be0b8ff4af28b5adb2f287374b/docs/guides/integration/github.md#using-uv-pip !

**Comment by zanieb** [comment]
Thanks!

It's just not published yet because it was just written.

This documentation is not ready for public use yet :)

**Comment by schloerke** [comment]
Cool. Closing. 😄
