### ISSUE TITLE
Packages show as installed by uv but are not actually installed

### ISSUE THREAD

**Issue by jfmcdowell** [astral-sh/uv#5376]
When I install packages using `uv`, it appears that they are not actually installed. If I install my packages with `pip` they work as expected.

My Python code is based on AWS CDK Python and relies on [aws-cdk-lib](https://pypi.org/project/aws-cdk-lib/).
When running a simple CDK command to list stacks I get the following error that implies the modules were not actually installed

```bash
(aws-tag-policies-cdk) vscode ➜ /workspaces/aws-tag-policies-cdk (dev) $ cdk ls
Traceback (most recent call last):
  File "/workspaces/aws-tag-policies-cdk/app.py", line 2, in <module>
    import aws_cdk as cdk
  File "/workspaces/aws-tag-policies-cdk/.venv/lib/python3.12/site-packages/aws_cdk/__init__.py", line 1513, in <module>
    import jsii
ModuleNotFoundError: No module named 'jsii'
``` 
In the uv logs I see a warning:

**error (warning) message:**
```
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance. If this is intentional, use `--link-mode=copy` to suppress this warning.

hint: If the cache and target directories are on different filesystems, hardlinking may not be supported.
```
If I run `pip` things work as expected.

**uv version:** uv-0.2.28
**uv platform:** VSCode DevContainer
**commands invoked:**
```bash
pip install uv
uv venv  # Create a virtual environment at .venv.
uv pip install -r requirements.txt --verbose
```
requirements.txt:
```text
aws-cdk-lib==2.110.1
boto3
constructs>=10.0.0,<11.0.0
jinja2
netaddr
```

Output:
---
DEBUG uv 0.2.28
DEBUG Searching for Python interpreter in system path
DEBUG Found cpython 3.12.4 at `/workspaces/aws-tag-policies-cdk/.venv/bin/python3` (virtual environment)
DEBUG Using Python 3.12.4 environment at .venv/bin/python3
DEBUG Acquired lock for `.venv`
DEBUG At least one requirement is not satisfied: netaddr
DEBUG Using request timeout of 30s
DEBUG Solving with installed Python version: 3.12.4
DEBUG Adding direct dependency: aws-cdk-lib==2.110.1
DEBUG Adding direct dependency: boto3*
DEBUG Adding direct dependency: constructs>=10.0.0, <11.0.0
DEBUG Adding direct dependency: jinja2*
DEBUG Adding direct dependency: netaddr*
DEBUG No cache entry for: https://pypi.org/simple/aws-cdk-lib/
DEBUG No cache entry for: https://pypi.org/simple/constructs/
DEBUG No cache entry for: https://pypi.org/simple/boto3/
DEBUG No cache entry for: https://pypi.org/simple/jinja2/
DEBUG No cache entry for: https://pypi.org/simple/netaddr/
DEBUG Searching for a compatible version of aws-cdk-lib (==2.110.1)
DEBUG Selecting: aws-cdk-lib==2.110.1 [compatible] (aws_cdk_lib-2.110.1-py3-none-any.whl)
DEBUG No cache entry for: https://files.pythonhosted.org/packages/5f/c6/c7667ecb8fc463bdfa36e0b4ab8e707b64233f19f554eb449918cc2d8aed/aws_cdk_lib-2.110.1-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/12/cc/f4fe2c7ce68b92cbf5b2d379ca366e1edae38cccaad00f69f529b460c3ef/netaddr-1.3.0-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/8f/82/5b1407b9747a8c0133d56433dd9b67ec622558b4b47dad6b1751c9d5aeeb/constructs-10.3.0-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/29/ba/8fa4c6caed854fcfe54606694dc918c1c5b566f6446c376de58b90bf9d0d/boto3-1.34.147-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: aws-cdk-asset-awscli-v1>=2.2.201, <3.0.0
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: aws-cdk-asset-kubectl-v20>=2.1.2, <3.0.0
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: aws-cdk-asset-node-proxy-agent-v6>=2.0.1, <3.0.0
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: constructs>=10.0.0, <11.0.0
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: jsii>=1.91.0, <2.0.0
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: publication>=0.0.3
DEBUG Adding transitive dependency for aws-cdk-lib==2.110.1: typeguard>=2.13.3, <2.14.dev0
DEBUG Searching for a compatible version of boto3 (*)
DEBUG No cache entry for: https://pypi.org/simple/aws-cdk-asset-awscli-v1/
DEBUG Selecting: boto3==1.34.147 [compatible] (boto3-1.34.147-py3-none-any.whl)
DEBUG No cache entry for: https://pypi.org/simple/aws-cdk-asset-node-proxy-agent-v6/
DEBUG No cache entry for: https://pypi.org/simple/jsii/
DEBUG No cache entry for: https://pypi.org/simple/aws-cdk-asset-kubectl-v20/
DEBUG No cache entry for: https://pypi.org/simple/publication/
DEBUG No cache entry for: https://pypi.org/simple/typeguard/
DEBUG No cache entry for: https://files.pythonhosted.org/packages/52/12/9abbed9dcf7eb1d30563d0bd38d163b3e2386756d7fd0a9ef2575047b478/aws_cdk.asset_node_proxy_agent_v6-2.0.3-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/f8/d3/6308debad7afcdb3ea5f50b4b3d852f41eb566a311fbcb4da23755a28155/publication-0.0.3-py2.py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d9/97/b4eaa76c87a745ecf61b7ab49a712653e6f5c71f8bd476e1a0d5215b55d3/aws_cdk.asset_kubectl_v20-2.1.2-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/9a/bb/d43e5c75054e53efce310e79d63df0ac3f25e34c926be5dffb7d283fb2a8/typeguard-2.13.3-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/72/67/3e15a7bd6aa67e6e136b09fec7fc3e21483c7d8ad6ce38649117ae25a4dd/aws_cdk.asset_awscli_v1-2.2.202-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for boto3==1.34.147: botocore>=1.34.147, <1.35.0
DEBUG Adding transitive dependency for boto3==1.34.147: jmespath>=0.7.1, <2.0.0
DEBUG Adding transitive dependency for boto3==1.34.147: s3transfer>=0.10.0, <0.11.0
DEBUG Searching for a compatible version of constructs (>=10.0.0, <11.0.0)
DEBUG Selecting: constructs==10.3.0 [compatible] (constructs-10.3.0-py3-none-any.whl)
DEBUG Adding transitive dependency for constructs==10.3.0: jsii>=1.90.0, <2.0.0
DEBUG Adding transitive dependency for constructs==10.3.0: publication>=0.0.3
DEBUG Adding transitive dependency for constructs==10.3.0: typeguard>=2.13.3, <2.14.dev0
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Selecting: jinja2==3.1.4 [compatible] (jinja2-3.1.4-py3-none-any.whl)
DEBUG Adding transitive dependency for jinja2==3.1.4: markupsafe>=2.0
DEBUG Searching for a compatible version of netaddr (*)
DEBUG Selecting: netaddr==1.3.0 [compatible] (netaddr-1.3.0-py3-none-any.whl)
DEBUG Searching for a compatible version of aws-cdk-asset-awscli-v1 (>=2.2.201, <3.0.0)
DEBUG Selecting: aws-cdk-asset-awscli-v1==2.2.202 [compatible] (aws_cdk.asset_awscli_v1-2.2.202-py3-none-any.whl)
DEBUG No cache entry for: https://pypi.org/simple/botocore/
DEBUG No cache entry for: https://pypi.org/simple/jmespath/
DEBUG No cache entry for: https://pypi.org/simple/s3transfer/
DEBUG No cache entry for: https://pypi.org/simple/markupsafe/
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ac/61/7d34c4791ef96fcf31cb040d119ad0ba07bae7d390ff68dd32ec4623b5ab/jsii-1.101.0-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for aws-cdk-asset-awscli-v1==2.2.202: jsii>=1.93.0, <2.0.0
DEBUG Adding transitive dependency for aws-cdk-asset-awscli-v1==2.2.202: publication>=0.0.3
DEBUG Adding transitive dependency for aws-cdk-asset-awscli-v1==2.2.202: typeguard>=2.13.3, <2.14.dev0
DEBUG Searching for a compatible version of aws-cdk-asset-kubectl-v20 (>=2.1.2, <3.0.0)
DEBUG Selecting: aws-cdk-asset-kubectl-v20==2.1.2 [compatible] (aws_cdk.asset_kubectl_v20-2.1.2-py3-none-any.whl)
DEBUG Adding transitive dependency for aws-cdk-asset-kubectl-v20==2.1.2: jsii>=1.70.0, <2.0.0
DEBUG Adding transitive dependency for aws-cdk-asset-kubectl-v20==2.1.2: publication>=0.0.3
DEBUG Adding transitive dependency for aws-cdk-asset-kubectl-v20==2.1.2: typeguard>=2.13.3, <2.14.dev0
DEBUG Searching for a compatible version of aws-cdk-asset-node-proxy-agent-v6 (>=2.0.1, <3.0.0)
DEBUG Selecting: aws-cdk-asset-node-proxy-agent-v6==2.0.3 [compatible] (aws_cdk.asset_node_proxy_agent_v6-2.0.3-py3-none-any.whl)
DEBUG Adding transitive dependency for aws-cdk-asset-node-proxy-agent-v6==2.0.3: jsii>=1.96.0, <2.0.0
DEBUG Adding transitive dependency for aws-cdk-asset-node-proxy-agent-v6==2.0.3: publication>=0.0.3
DEBUG Adding transitive dependency for aws-cdk-asset-node-proxy-agent-v6==2.0.3: typeguard>=2.13.3, <2.14.dev0
DEBUG Searching for a compatible version of jsii (>=1.96.0, <2.0.0)
DEBUG Selecting: jsii==1.101.0 [compatible] (jsii-1.101.0-py3-none-any.whl)
DEBUG No cache entry for: https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/3c/4a/b221409913760d26cf4498b7b1741d510c82d3ad38381984a3ddc135ec66/s3transfer-0.10.2-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/51/b5/5d8ec796e2a08fc814a2c7d2584b55f889a55cf17dd1a90f2beb70744e5c/MarkupSafe-2.1.5-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl.metadata
DEBUG Adding transitive dependency for jsii==1.101.0: attrs>=21.2, <24.0
DEBUG Adding transitive dependency for jsii==1.101.0: cattrs>=1.8, <23.3
DEBUG Adding transitive dependency for jsii==1.101.0: importlib-resources>=5.2.0
DEBUG Adding transitive dependency for jsii==1.101.0: publication>=0.0.3
DEBUG Adding transitive dependency for jsii==1.101.0: typeguard>=2.13.3, <2.14.dev0
DEBUG Adding transitive dependency for jsii==1.101.0: python-dateutil*
DEBUG Adding transitive dependency for jsii==1.101.0: typing-extensions>=3.8, <5.0
DEBUG Searching for a compatible version of publication (>=0.0.3)
DEBUG Selecting: publication==0.0.3 [compatible] (publication-0.0.3-py2.py3-none-any.whl)
DEBUG Searching for a compatible version of typeguard (>=2.13.3, <2.14.dev0)
DEBUG Selecting: typeguard==2.13.3 [compatible] (typeguard-2.13.3-py3-none-any.whl)
DEBUG No cache entry for: https://pypi.org/simple/attrs/
DEBUG No cache entry for: https://pypi.org/simple/cattrs/
DEBUG No cache entry for: https://pypi.org/simple/importlib-resources/
DEBUG No cache entry for: https://pypi.org/simple/python-dateutil/
DEBUG No cache entry for: https://pypi.org/simple/typing-extensions/
DEBUG No cache entry for: https://files.pythonhosted.org/packages/e0/44/827b2a91a5816512fcaf3cc4ebc465ccd5d598c45cefa6703fcf4a79018f/attrs-23.2.0-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/b3/0d/cd4a4071c7f38385dc5ba91286723b4d1090b87815db48216212c6c6c30e/cattrs-23.2.3-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/75/06/4df55e1b7b112d183f65db9503bff189e97179b256e1ea450a3c365241e0/importlib_resources-6.4.0-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of botocore (>=1.34.147, <1.35.0)
DEBUG Selecting: botocore==1.34.147 [compatible] (botocore-1.34.147-py3-none-any.whl)
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d8/c2/694b4ad88010c20019aadd361fb0c994264835690b9d75a50e3860ee98ad/botocore-1.34.147-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for botocore==1.34.147: jmespath>=0.7.1, <2.0.0
DEBUG Adding transitive dependency for botocore==1.34.147: python-dateutil>=2.1, <3.0.0
DEBUG Adding transitive dependency for botocore==1.34.147: urllib3{python_version >= '3.10'}>=1.25.4, <2.2.0 | >2.2.0, <3
DEBUG Searching for a compatible version of jmespath (>=0.7.1, <2.0.0)
DEBUG Selecting: jmespath==1.0.1 [compatible] (jmespath-1.0.1-py3-none-any.whl)
DEBUG Searching for a compatible version of s3transfer (>=0.10.0, <0.11.0)
DEBUG Selecting: s3transfer==0.10.2 [compatible] (s3transfer-0.10.2-py3-none-any.whl)
DEBUG Adding transitive dependency for s3transfer==0.10.2: botocore>=1.33.2, <2.0a0
DEBUG Searching for a compatible version of markupsafe (>=2.0)
DEBUG Selecting: markupsafe==2.1.5 [compatible] (MarkupSafe-2.1.5-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of attrs (>=21.2, <24.0)
DEBUG Selecting: attrs==23.2.0 [compatible] (attrs-23.2.0-py3-none-any.whl)
DEBUG Searching for a compatible version of cattrs (>=1.8, <23.3)
DEBUG Selecting: cattrs==23.2.3 [compatible] (cattrs-23.2.3-py3-none-any.whl)
DEBUG No cache entry for: https://pypi.org/simple/urllib3/
DEBUG Adding transitive dependency for cattrs==23.2.3: attrs>=23.1.0
DEBUG Searching for a compatible version of importlib-resources (>=5.2.0)
DEBUG Selecting: importlib-resources==6.4.0 [compatible] (importlib_resources-6.4.0-py3-none-any.whl)
DEBUG Searching for a compatible version of python-dateutil (>=2.1, <3.0.0)
DEBUG Selecting: python-dateutil==2.9.0.post0 [compatible] (python_dateutil-2.9.0.post0-py2.py3-none-any.whl)
DEBUG Adding transitive dependency for python-dateutil==2.9.0.post0: six>=1.5
DEBUG Searching for a compatible version of typing-extensions (>=3.8, <5.0)
DEBUG Selecting: typing-extensions==4.12.2 [compatible] (typing_extensions-4.12.2-py3-none-any.whl)
DEBUG No cache entry for: https://pypi.org/simple/six/
DEBUG Searching for a compatible version of urllib3{python_version >= '3.10'} (>=1.25.4, <2.2.0 | >2.2.0, <3)
DEBUG Selecting: urllib3==2.2.2 [compatible] (urllib3-2.2.2-py3-none-any.whl)
DEBUG Adding transitive dependency for urllib3==2.2.2: urllib3==2.2.2
DEBUG Adding transitive dependency for urllib3==2.2.2: urllib3{python_version >= '3.10'}==2.2.2
DEBUG Searching for a compatible version of urllib3{python_version >= '3.10'} (==2.2.2)
DEBUG Selecting: urllib3==2.2.2 [compatible] (urllib3-2.2.2-py3-none-any.whl)
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ca/1c/89ffc63a9605b583d5df2be791a27bc1a42b7c32bab68d3c8f2f73a98cd4/urllib3-2.2.2-py3-none-any.whl.metadata
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl.metadata
DEBUG Searching for a compatible version of urllib3 (==2.2.2)
DEBUG Selecting: urllib3==2.2.2 [compatible] (urllib3-2.2.2-py3-none-any.whl)
DEBUG Searching for a compatible version of six (>=1.5)
DEBUG Selecting: six==1.16.0 [compatible] (six-1.16.0-py2.py3-none-any.whl)
DEBUG Tried 22 versions: attrs 1, aws-cdk-asset-awscli-v1 1, aws-cdk-asset-kubectl-v20 1, aws-cdk-asset-node-proxy-agent-v6 1, aws-cdk-lib 1, boto3 1, botocore 1, cattrs 1, constructs 1, importlib-resources 1, jinja2 1, jmespath 1, jsii 1, markupsafe 1, netaddr 1, publication 1, python-dateutil 1, s3transfer 1, six 1, typeguard 1, typing-extensions 1, urllib3 1
DEBUG Split specific environment resolution took 0.571s
Resolved 22 packages in 586ms
DEBUG Identified uncached requirement: attrs==23.2.0
DEBUG Identified uncached requirement: aws-cdk-asset-awscli-v1==2.2.202
DEBUG Identified uncached requirement: aws-cdk-asset-kubectl-v20==2.1.2
DEBUG Identified uncached requirement: aws-cdk-asset-node-proxy-agent-v6==2.0.3
DEBUG Identified uncached requirement: aws-cdk-lib==2.110.1
DEBUG Identified uncached requirement: boto3==1.34.147
DEBUG Identified uncached requirement: botocore==1.34.147
DEBUG Identified uncached requirement: cattrs==23.2.3
DEBUG Identified uncached requirement: constructs==10.3.0
DEBUG Identified uncached requirement: importlib-resources==6.4.0
DEBUG Identified uncached requirement: jinja2==3.1.4
DEBUG Identified uncached requirement: jmespath==1.0.1
DEBUG Identified uncached requirement: jsii==1.101.0
DEBUG Identified uncached requirement: markupsafe==2.1.5
DEBUG Identified uncached requirement: netaddr==1.3.0
DEBUG Identified uncached requirement: publication==0.0.3
DEBUG Identified uncached requirement: python-dateutil==2.9.0.post0
DEBUG Identified uncached requirement: s3transfer==0.10.2
DEBUG Identified uncached requirement: six==1.16.0
DEBUG Identified uncached requirement: typeguard==2.13.3
DEBUG Identified uncached requirement: typing-extensions==4.12.2
DEBUG Identified uncached requirement: urllib3==2.2.2
DEBUG No cache entry for: https://files.pythonhosted.org/packages/5f/c6/c7667ecb8fc463bdfa36e0b4ab8e707b64233f19f554eb449918cc2d8aed/aws_cdk_lib-2.110.1-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d9/97/b4eaa76c87a745ecf61b7ab49a712653e6f5c71f8bd476e1a0d5215b55d3/aws_cdk.asset_kubectl_v20-2.1.2-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/72/67/3e15a7bd6aa67e6e136b09fec7fc3e21483c7d8ad6ce38649117ae25a4dd/aws_cdk.asset_awscli_v1-2.2.202-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d8/c2/694b4ad88010c20019aadd361fb0c994264835690b9d75a50e3860ee98ad/botocore-1.34.147-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/12/cc/f4fe2c7ce68b92cbf5b2d379ca366e1edae38cccaad00f69f529b460c3ef/netaddr-1.3.0-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/52/12/9abbed9dcf7eb1d30563d0bd38d163b3e2386756d7fd0a9ef2575047b478/aws_cdk.asset_node_proxy_agent_v6-2.0.3-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ac/61/7d34c4791ef96fcf31cb040d119ad0ba07bae7d390ff68dd32ec4623b5ab/jsii-1.101.0-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/29/ba/8fa4c6caed854fcfe54606694dc918c1c5b566f6446c376de58b90bf9d0d/boto3-1.34.147-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/ca/1c/89ffc63a9605b583d5df2be791a27bc1a42b7c32bab68d3c8f2f73a98cd4/urllib3-2.2.2-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/3c/4a/b221409913760d26cf4498b7b1741d510c82d3ad38381984a3ddc135ec66/s3transfer-0.10.2-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/8f/82/5b1407b9747a8c0133d56433dd9b67ec622558b4b47dad6b1751c9d5aeeb/constructs-10.3.0-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/b3/0d/cd4a4071c7f38385dc5ba91286723b4d1090b87815db48216212c6c6c30e/cattrs-23.2.3-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/75/06/4df55e1b7b112d183f65db9503bff189e97179b256e1ea450a3c365241e0/importlib_resources-6.4.0-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/e0/44/827b2a91a5816512fcaf3cc4ebc465ccd5d598c45cefa6703fcf4a79018f/attrs-23.2.0-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/51/b5/5d8ec796e2a08fc814a2c7d2584b55f889a55cf17dd1a90f2beb70744e5c/MarkupSafe-2.1.5-cp312-cp312-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/9a/bb/d43e5c75054e53efce310e79d63df0ac3f25e34c926be5dffb7d283fb2a8/typeguard-2.13.3-py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
DEBUG No cache entry for: https://files.pythonhosted.org/packages/f8/d3/6308debad7afcdb3ea5f50b4b3d852f41eb566a311fbcb4da23755a28155/publication-0.0.3-py2.py3-none-any.whl
Prepared 22 packages in 6.57s
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance. If this is intentional, use `--link-mode=copy` to suppress this warning.

hint: If the cache and target directories are on different filesystems, hardlinking may not be supported.
Installed 22 packages in 1.62s
 + attrs==23.2.0
 + aws-cdk-asset-awscli-v1==2.2.202
 + aws-cdk-asset-kubectl-v20==2.1.2
 + aws-cdk-asset-node-proxy-agent-v6==2.0.3
 + aws-cdk-lib==2.110.1
 + boto3==1.34.147
 + botocore==1.34.147
 + cattrs==23.2.3
 + constructs==10.3.0
 + importlib-resources==6.4.0
 + jinja2==3.1.4
 + jmespath==1.0.1
 + jsii==1.101.0
 + markupsafe==2.1.5
 + netaddr==1.3.0
 + publication==0.0.3
 + python-dateutil==2.9.0.post0
 + s3transfer==0.10.2
 + six==1.16.0
 + typeguard==2.13.3
 + typing-extensions==4.12.2
 + urllib3==2.2.2

**Comment by charliermarsh** [comment]
Sorry, what do you mean by "are not actually installed"? How are you determining that?

**Comment by jfmcdowell** [comment]
> Sorry, what do you mean by "are not actually installed"? How are you determining that?

So when I try to use the aws-cdk-lib module in my code (by running the command)
```bash
cdk ls
```
I get a module error. I realize that I hit send prematurely so I will add additional detail above

**Comment by charliermarsh** [comment]
Did you activate the virtual environment prior to running Python (but after installing)?

**Comment by jfmcdowell** [comment]
🤦 
That was the issue. Thanks @charliermarsh and team. I love `uv`

**Comment by charliermarsh** [comment]
No problem, happy to help!
