### ISSUE TITLE
`uv lock` doesn't show when we drop versions

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5401]
See for example the "preferences-dependent-forking" packse scenario. In first call we split a version into two, in the second call we drop 2.0.0 but don't show that:

```
$ uv lock --upgrade --preview
Resolved 6 packages in 211ms
Updating preferences-dependent-forking-foo-5c5f76e6 v1.0.0 -> v1.0.0, 2.0.0
$ uv lock --preview
Resolved 5 packages in 115ms
```

We also seem to be inconsistent about the `v` prefix

**Comment by charliermarsh** [comment]
Should it?

**Comment by konstin** [comment]
Imo this counts as a version update (`v1.0.0, v2.0.0 -> v1.0.0`) and we should display such changes to the lockfile as part of the summary message.

**Comment by charliermarsh** [comment]
Oh, that seems right. But packages that are dropped entirely should not be shown, IMO.

**Comment by BurntSushi** [comment]
As another data point, I _love_ when I get see dependencies dropped after running `cargo update`. Usually this inspires me to investigate further and can turn up interesting curiosities. I believe this is what caused me to notice the migration from `winapi` to `windows-sys` in the Rust ecosystem, for example.

**Comment by charliermarsh** [comment]
What does it say?

**Comment by charliermarsh** [comment]
Oh right, `Removing` and `ADding`. Ok, I can do that. I agree with you.

**Comment by BurntSushi** [comment]
Yeah, and the same goes for adding a dependency, definitely. I pay very close attention to those! :)

**Comment by zanieb** [comment]
Yes please!

**Comment by charliermarsh** [comment]
Separately, we only show these when you run `uv lock --update` right now (not `uv sync`, `uv run`, or `uv lock` without `--update`). Should we... always show these, when a lock exists already? I guess Cargo doesn't.

**Comment by zanieb** [comment]
I was surprised that there was no output indicating a change to the lock file with a plain `uv lock`; I think it'd be great if there was / I don't see why it should be omitted.

**Comment by charliermarsh** [comment]
I'll change it separately. (But probably not for `uv run` and `uv sync`, I suppose.)
