### ISSUE TITLE
Document best practices for maintaining the cache

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5409]
e.g. as prompted in https://github.com/astral-sh/uv/issues/5222#issuecomment-2247510996

How to remove old entries? (`uv cache prune`?)
How to remove specific packages? (`uv cache clean <name>`)
How to optimize size in CI?

**Comment by zanieb** [comment]
See also:

- https://github.com/hynek/setup-cached-uv/issues/7
- https://github.com/actions/setup-python/issues/822

**Comment by zanieb** [comment]
See also:
- https://github.com/astral-sh/uv/pull/5391#p

**Comment by MarcusJellinghaus** [comment]
Maybe you also want to add information related to
- running several CI pipelines in parallel (eg several GitHub runners on one Windows machine) - should I have one cache for all or several caches?
- incorrect treatment of new packages - maybe also add this [comment](https://github.com/astral-sh/uv/issues/5351#issuecomment-2252911773)
- best practices for running CI pipelines on Windows servers ( i.e. where the CI server might stay the same for years, while kubernetes-based pods might get recreated from template regularly).
