### ISSUE TITLE
Editable install of tools 

### ISSUE THREAD

**Issue by ollebompa** [astral-sh/uv#5436]
Hi!

I have been trying `uv` out recently and it's fantastic! Thanks for the great work so far.

I'm trying to install a tool with `uv tool install` from a local directory and I would like it to install in editable mode. Is there a way to do this like you can with `pipx`, for example?  `uv tool install` (or `uv tool run`/`uvx`) does not accept an -e/--editable option it seems. 

If this is not possible to do today, I suggest it as a future feature.

**Comment by charliermarsh** [comment]
I don't believe this is possible today but certainly something we can consider.

**Comment by zanieb** [comment]
I think we should support this, yeah.
