### ISSUE TITLE
Support for editable dependencies with URLs

### ISSUE THREAD

**Issue by krmax44** [astral-sh/uv#5442]
While uv supports dependencies from URLs (like `uv pip install git+https://github.com/pallets/flask.git`), they can't be installed with the `-e` flag:

```
$ uv pip install -e git+https://github.com/pallets/flask.git
error: Editable must refer to a local directory, not a Git URL
```

For multi-repo projects, this would be nice to have.

**Comment by zanieb** [comment]
Hi! What does it mean to have an editable installing of a remote git dependency?

**Comment by krmax44** [comment]
From my understanding, there is little difference. With the `-e` flag however, an existing repository is updated upon re-running the install command (see below), without a new clone is made.

```
Updating ./.venv/src/froide-fax clone (to revision main)
  Running command git fetch -q --tags
  Running command git reset --hard -q 09a7bcec76d3da6b2003516a775ed5657a7cc062
```

**Comment by charliermarsh** [comment]
As of now we intentionally don't support this. It adds a lot of complexity and we actually don't re-clone at all upon re-running the install command (we have a cache that contains a copy of each repository, and we checkout-and-install as needed with incremental fetches).

**Comment by zanieb** [comment]
I think we always cache git clones anyway, though I'm not sure about the nuances of our behavior here. Are you having problems with our behavior specifically?

**Comment by krmax44** [comment]
Just dropping the `-e` works fine as of now :)

**Comment by zanieb** [comment]
Thanks! Let us know if you have more questions / a use-case that's not addressed.

**Comment by krmax44** [comment]
I found another difference: With `-e`, all files from the repository are available within `.venv/src`. WIthout, only relevant files (presumably as configured with setuptools) will be stored in `site-packages`. This is quite important to us, as we also include JavaScript files in the repo we need to access.

**Comment by edmorley** [comment]
Adding some keywords since I couldn't find this issue initially:
`uv add --editable`, Git, VCS

 ```
error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 12, column 12
   |
12 | gunicorn = { git = "https://github.com/benoitc/gunicorn", editable = true }
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cannot specify both `git` and `editable`
```

**Comment by charliermarsh** [comment]
Thanks, good form!

**Comment by ThrawnCA** [comment]
This can create problems if a package doesn't specify the metadata around its dependencies very well and they need manual handling.

For example, https://github.com/ckan/ckanext-dcat has a `requirements.txt` file to install what it needs, but that file won't be used automatically, and if you use a non-editable install, you won't get a copy of the file to install everything manually.
