### ISSUE TITLE
Store index URLs in tool receipts

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5443]
per https://github.com/astral-sh/uv/pull/5197#issuecomment-2248419637 we need the index urls to be able to upgrade the tool when alternative indexes are used.

**Comment by charliermarsh** [comment]
Do you think we need anything else? Like `no-binary`, `no-build`, `resolution-mode`, etc.?

**Comment by zanieb** [comment]
We probably need all of the `ResolverInstallerSettings`, right? :/

**Comment by charliermarsh** [comment]
I think the index URL is the only thing that would affect whether or not the resolution _succeeds_ (maybe `no-binary` and `no-build` in weird cases, like a package has a broken wheel or something that you want to avoid). So arguably it's in a slightly different class...

**Comment by charliermarsh** [comment]
We store a subset of these in the lockfile now if and only if they differ from the defaults. Ideally we would consider this holistically with the lockfile.

**Comment by charliermarsh** [comment]
The other problem with storing index URLs is that they could contain credentials, right?

**Comment by zanieb** [comment]
Strong agree around consistency with the lockfile, which I think includes the credential problem.

**Comment by zanieb** [comment]
Although for tool receipts, it's "okay" if we store credentials that the user handed us since it's not checked into version control.

**Comment by charliermarsh** [comment]
I'll look into this today.

**Comment by charliermarsh** [comment]
Done.
