### ISSUE TITLE
Installing into a virtualenv on Windows fails when the location changes

### ISSUE THREAD

**Issue by ak-gupta** [astral-sh/uv#5445]
Hi there!

`uv` is awesome, but we're running into an issue with installing into a virtualenv on Windows. If I run

```bash
uv pip install --python=/path/to/python
```

I sometimes get an error message similar to the following:

```
RuntimeError: Unable to run the following command: 

 uv pip install --python=C:\Users\RUNNER~1\AppData\Local\Temp\tmp3hg_0oka\.edgetest\core\Scripts\python .[tests]
WARNING  venv:__init__.py:165 Actual environment location may have moved due to redirects, links or junctions.
  Requested location: "C:\Users\RUNNER~1\AppData\Local\Temp\tmp3hg_0oka\.edgetest\lower_env\Scripts\python.exe"
  Actual location:    "C:\Users\runneradmin\AppData\Local\Temp\tmp3hg_0oka\.edgetest\lower_env\Scripts\python.exe"
```

this is running on GitHub Actions using `windows-latest` and `uv` version 0.2.28. If curious, the error log is in the job from [this PR](https://github.com/capitalone/edgetest/pull/81). Any help is greatly appreciated!

**Comment by charliermarsh** [comment]
Thanks, that's an interesting one. Those are indeed aliases for one another. Let me see why it's failing...

**Comment by charliermarsh** [comment]
In `utils.py`, can you modify the exception to include all of `stdout` and `stderr`? The directory mismatch _may_ be the problem, but it's also just a warning and so not the immediate cause of the failure.

https://github.com/capitalone/edgetest/blob/8ac71cdb26516e2120745934febc724732ab0e8d/edgetest/utils.py#L46

**Comment by charliermarsh** [comment]
Thanks! Just to confirm, is `.edgetest\core` a virtual environment?

**Comment by charliermarsh** [comment]
I think it needs to be `python.exe`.

**Comment by charliermarsh** [comment]
That may not matter here though. One sec.

**Comment by charliermarsh** [comment]
Ok yeah tracing the code, I think that might be the problem here.

**Comment by ak-gupta** [comment]
Ah. Let me try that!

**Comment by charliermarsh** [comment]
We can probably be robust to it, but can you try changing to add the `.exe` extension on your end?

**Comment by ak-gupta** [comment]
Yep, I'll push up a change and see if that fixes the issue

**Comment by ak-gupta** [comment]
The `.exe` extension fixed the issue! Thank you!

**Comment by charliermarsh** [comment]
Stellar. @zanieb do you think we should be robust to this? I.e., passing `--python .edgetest\core\Scripts\python` without the `.exe` suffix? (We detect that it's a "file" path, but we later fail to find the file.)

**Comment by charliermarsh** [comment]
I'll just fix it, easy and will be a common footgun.

**Comment by zanieb** [comment]
Seems okay to infer the `.exe` on Windows, yeah.
