### ISSUE TITLE
Add support for `install_only_stripped` variants

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5447]
See: https://github.com/indygreg/python-build-standalone/releases/tag/20240725

**Comment by zanieb** [comment]
We don't have any concept of users requesting specific downloads for each version i.e. we only include a single download per version. However, it seems important for people to be able to acquire builds with debug symbols. Maybe we should

1. Switch over to the stripped distributions by default
2. Create an issue to design a way for users to request installs with debug symbols

**Comment by charliermarsh** [comment]
Yeah, that sounds good.

**Comment by charliermarsh** [comment]
Do we want users to be able to request specific variants? Or would debug symbols be special (like `--debug` or similar)?

**Comment by zanieb** [comment]
I think they'd be special, idk what the use case is for requesting an unoptimized version though. Seems... dubious to allow them all.

**Comment by charliermarsh** [comment]
I'll swap over now.
