### ISSUE TITLE
Significantly reduce user-facing output in `uv run`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5458]
Right now, we show a bunch of information for both the base and the layered environment. We should slim this down substantially (at least, by default).

Also applies to `uv tool run` (i.e., `uvx`).

**Comment by zanieb** [comment]
I swear there's an issue for this but I can't find it.

**Comment by ibraheemdev** [comment]
https://github.com/astral-sh/uv/issues/4213?

**Comment by zanieb** [comment]
Nah this is more general. Maybe it was mentioned outside of GitHub — I looked relatively hard, let's just use this one.

**Comment by charliermarsh** [comment]
I'll do this next week.

**Comment by charliermarsh** [comment]
Will focus on this tomorrow.
