### ISSUE TITLE
A build backend flag for `uv init`

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#5461]
The default build backend, setuptools, is somewhat archaic and has undesirable behaviors, such as creating an `.egg-info` directory. We should add an `--build-backend` flag to `uv init` which some popular choices, such as hatch and flit.

**Comment by charliermarsh** [comment]
I'm wondering if we should just use a different default, to match Rye?

**Comment by konstin** [comment]
Flit or hatch seem to be the popular choices, both have been working well for me.

**Comment by charliermarsh** [comment]
FWIW, Hatchling is about an order of magnitude more popular than Flit (and setuptools is about an order of magnitude more popular than Hatchling).

**Comment by helderco** [comment]
I vote for hatchling.

**Comment by AlexWaygood** [comment]
@AndreuCodina -- "build backend" is the standard term here, however. If you google "build backend Python", you get more helpful results introducing you to the concept than if you google "package backend Python".

**Comment by bluss** [comment]
Is there a build backend that can interoperate well with uv's support for relative paths and workspaces?
