### ISSUE TITLE
`uv pip install -e .` does not recompute dynamic dependencies anymore

### ISSUE THREAD

**Issue by sbidoul** [astral-sh/uv#5484]
I have a project with dynamic dependencies.

With uv 0.2.29 `uv pip install -e .` does not install new dynamic dependencies when I add some to my project, while it did reinstall with uv < 0.2.28. 

This is likely due to https://github.com/astral-sh/uv/pull/5206. 

I understand the rationale for `uv run`, but for the scenario of reinstalling a project in editable mode, this behavior is surprising. Was this change intended?

**Comment by charliermarsh** [comment]
It was an intentional change. The decision was that if you want your editable project to "always reinstall", you should set `reinstall-package = ["foo"]` in your persistent configuration.

We could consider changing the behavior for explicit cases like `pip install -e .` though, and always reinstall those (as opposed to in `uv run` where it's sort of implicit). I don't love have separate semantics which is why I avoided it, and instead made it opt-in...

**Comment by sbidoul** [comment]
Ok, thanks.

And if I have a git dependency `foo @ git+https://github.com/org/foo@shaX` that I change to `foo @ git+https://github.com/org/project@shaY` and the `pyproject.toml` of `foo` over there has not changed between `shaX` and `shaY` but some dynamic dependency has changed, will it recompute the dependencies ?

**Comment by charliermarsh** [comment]
I will test it to be sure.

**Comment by sbidoul** [comment]
I just did my homework and it does indeed recompute in that case.

**Comment by sbidoul** [comment]
But I'm a little confused about when dynamic metadata is recomputed and when not.

**Comment by charliermarsh** [comment]
No worries. The rules only changed for source trees (i.e., directories), and they're the same regardless of whether it's editable or not, and regardless of whether it's dynamic or not: we recompute and reinstall if (1) a metadata file changes (`pyproject.toml`, `setup.py`, or `setup.cfg` -- this is a heuristic) or (2) the user passes `--reinstall`.

A few examples:

```shell
❯ cargo run pip install ./scripts/packages/black_editable
Resolved 1 package in 9ms
   Built black @ file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable
Prepared 1 package in 345ms
Installed 1 package in 1ms
 + black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)

❯ cargo run pip install ./scripts/packages/black_editable
Audited 1 package in 6ms

❯ touch scripts/packages/black_editable/pyproject.toml

❯ cargo run pip install ./scripts/packages/black_editable
Resolved 1 package in 8ms
   Built black @ file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable
Prepared 1 package in 109ms
Uninstalled 1 package in 0.59ms
Installed 1 package in 1ms
 - black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)
 + black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)

❯ cargo run pip install ./scripts/packages/black_editable
Audited 1 package in 6ms

❯ cargo run pip install ./scripts/packages/black_editable --reinstall black
Resolved 1 package in 7ms
   Built black @ file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable
Prepared 1 package in 178ms
Uninstalled 1 package in 0.71ms
Installed 1 package in 1ms
 - black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)
 + black==0.1.0 (from file:///Users/crmarsh/workspace/uv/scripts/packages/black_editable)
```

**Comment by sbidoul** [comment]
Thanks for the explanation. So it's not only about metadata, but the whole local directory, correct?

If I do a non-editable install of a local directory, then modify it, I have to use `--reinstall` (which reinstalls everything) or `--reinstall-package myprojectname` (for which I have to remember the project name).

When used from the command line this feels slightly awkward to me. When used from uv run or for a multi project workspace the new default may be better. I don't know if it's my how habits influencing my perception here or if there is something else.

BTW, in the example above it should be `--reinstall-package black` instead of `--reinstall black`, right? Perhaps this is indicative of a UX intuitiveness issue?

**Comment by Nomelas** [comment]
Thanks, this solution by @charliermarsh seems to work and suit my needs

**Comment by zanieb** [comment]
@charliermarsh can you own including this in the documentation somewhere?

**Comment by charliermarsh** [comment]
Yes for sure.
