### ISSUE TITLE
Force reinstall wheel in uvx --with

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#5493]
Here's a recipe for building a wheel and testing it in a project setup for pytest.

```
uvx --from build pyproject-build -s -w --installer uv
uvx --reinstall --refresh --with dist/*.whl pytest
```

Is there a way to force the wheel to always be reinstalled, even if name and version doesn't change? --reinstall --refresh are not enough in this particular case.

uv 0.2.30

**Comment by charliermarsh** [comment]
Hmm, `--reinstall` on its own should be enough. I'll look into it.

**Comment by charliermarsh** [comment]
Yeah I consider that a bug.

**Comment by charliermarsh** [comment]
There's actually a TODO for this hah.
