### ISSUE TITLE
`uv build` command?

### ISSUE THREAD

**Issue by nekitdev** [astral-sh/uv#5507]
I've searched through issues in this repository but I couldn't find anything concrete.
What's the progress/roadmap for this command? The only time I've seen it mentioned is in the [blog](https://astral.sh/blog/uv).

**Comment by chrisrodrigue** [comment]
Semi-related: #3957

**Comment by lambda-science** [comment]
> I've searched through issues in this repository but I couldn't find anything concrete. What's the progress/roadmap for this command? The only time I've seen it mentioned is in the [blog](https://astral.sh/blog/uv).

Interested as well to switch from Rye to uv, we need build publish command. Any news ?

**Comment by samypr100** [comment]
Re-publish, see https://github.com/astral-sh/uv/issues/6278

**Comment by zanieb** [comment]
I think this is a duplicate of #1510 — and yes we intend to do it.

**Comment by purajit** [comment]
It's here now! I switched all our workflows to `uv build` from 0.4.5. Works like a charm.

**Comment by charliermarsh** [comment]
Amazing!
