### ISSUE TITLE
feat: remove the old uv binary when another one is installed

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [astral-sh/uv#5522]
So this should be an easy one. I remember that I have installed `uv` using `pipx` in my arch linux which will install `uv` in `~/.local/bin` and then used the bash script to install the latest version but because of the placement of `~/.local/bin` in the `PATH` env variable I still got the old one when I executed `uv --version` and I had to remove it manually. One of the things you might do is to search for `uv` using the `which` command and the equivalent for other platforms as well and remove the binary.

**Comment by charliermarsh** [comment]
It's a little dubious for an installer to remove binaries that it didn't install. But maybe there's a world where we warn if we find a `uv` earlier in PATH after installing via the `curl` installers?
