### ISSUE TITLE
Add constraints (and overrides?) to build environments

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5561]
We should add a `--build-constraints` that apply to the build environments.

See: https://github.com/astral-sh/uv/issues/5551#issuecomment-2256055975

**Comment by hauntsaninja** [comment]
(Note that pip's behaviour is a little weird, only the env var affects the build environments, not the command line flag)

**Comment by charliermarsh** [comment]
Oh wow, that's interesting. I'm considering providing separate API for this (like `--build-constraints`).

**Comment by orsinium** [comment]
In [DepHell](https://github.com/dephell/dephell), I used to use [ensurepip](https://docs.python.org/3/library/ensurepip.html) with [fallbacks](https://github.com/dephell/dephell_venvs/blob/master/dephell_venvs/_ensurepip.py) to bootstrap build venvs. It uses the setuptools and pip versions bundled with stdlib that are always the same and guaranteed to be stable.

**Comment by charliermarsh** [comment]
Yeah we should add this. I'll make a separate issue.

**Comment by charliermarsh** [comment]
Tracking here: https://github.com/astral-sh/uv/issues/6913
