### ISSUE TITLE
uv 0.2.30 started installing some dependencies non-editably even though they are installed with -e

### ISSUE THREAD

**Issue by gibsondan** [astral-sh/uv#5567]
Still working on an MRE for you, but we are seeing that after the 0.2.30 upgrade, our 'dev install' command that tries to install a bunch of dagster packages editably is no longer installing them editably.

Here's the script that we run to install our modules: https://github.com/dagster-io/dagster/blob/master/scripts/install_dev_python_modules.py#L50-L105

We've reliably bisected to this uv release, after this command is no longer returning an empty string as expected after running that script (i.e. not every dependency was installed editably, even though they were all installed with the `-e` flag):

```
pip list --exclude-editable | grep -e dagster | grep -v dagster-hex | grep -v dagster-hightouch
```

Will update with an MRE once we have one, but based on multiple repros are fairly confident that something regressed (or at least changed in a breaking way) in uv 0.2.30

**Comment by charliermarsh** [comment]
I believe this is fixed #5545. I can cut a release shortly.

**Comment by gibsondan** [comment]
Ah I should have checked closed issues, that does look very likely to be the same thing.

**Comment by charliermarsh** [comment]
No worries, this was a confusing one.

**Comment by charliermarsh** [comment]
I have a new release going out shortly: https://github.com/astral-sh/uv/pull/5568

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/5545.
