### ISSUE TITLE
Avoid modifying `.bash_profile` every `uv self update`

### ISSUE THREAD

**Issue by scienceplease** [astral-sh/uv#5576]
Currently, the user's `.bash_profile` is modified by appending `. $CARGO_HOME/env` on every `uv self update`. I understand this behavior on initial install for making uv work out of the box for everyone, but `uv` should respect if a user has since (re)moved this line in their BASH configuration when updating. Is it possible to limit this behavior to the initial install and omit it on `uv self update`?

```bash
$ uv --version
uv 0.2.31
```

**Comment by charliermarsh** [comment]
It seems like a reasonable request. I will check with the axo team to see what they think.

**Comment by zanieb** [comment]
I think the problem is that the installer can't distinguish between a _newly_ supported shell config file and previously supported one so it just adds to _all_ configs. It does seem reasonable to add a flag to opt-out though?

**Comment by scienceplease** [comment]
Can the difference between an update and initial install be detected? If so, implicit/automatic modification to shell configuration can be reserved for just the initial installation process. A flag could then be used to enable explicit opt-in to shell configuration modification when updating e.g. `uv self update --config-shell`.
