### ISSUE TITLE
shared env: executables perms problem on install

### ISSUE THREAD

**Issue by stas00** [astral-sh/uv#5581]
As a follow up to https://github.com/astral-sh/uv/issues/5496 - there is another (new?) perms issue.

There are 2 possibly related issues

1. I have upgraded to 0.2.31

```
$ uv pip install py-spy
Resolved 1 package in 1m 33s
error: Failed to install: py_spy-0.3.14-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.http.whl (py-spy==0.3.14)
  Caused by: failed to set permissions for file `/env/lib/conda/stas-inference/bin/py-spy`
  Caused by: Operation not permitted (os error 1)
```
and the file has the correct perms, but is owned by another user in the cache and I think it copied the file from the cache:
```
-rwxrwxrwx 2 foo foo 9.4M Jul 17 05:13 /env/lib/conda/stas-inference/bin/py-spy
```

Not sure if it copies it from this file?
```
-rwxrwxrwx 3 foo foo 9.4M Jul 17 05:13 /env/cache/uv/archive-v0/KXNvF2h2RHusTTHhLSDxY/py_spy-0.3.14.data/scripts/py-spy
*
```

So that `0666` in this case has to be `0777` perhaps for executable files here https://github.com/astral-sh/uv/pull/5498

So currently nobody can use `uv` on our setup because of that.

2. another user reported a similar issue:

```
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to hardlink file from /data/env/cache/uv/archive-v0/v9yFzmI6xnIw5rZHZhlUq/deepspeed-0.14.4.data/scripts/ds_ssh to /env/lib/conda/graphrag_raw/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
  Caused by: Operation not permitted (os error 1)
```
the source file that the other user is trying to hardlink to via `uv pip install deepspeed` is owned by me and it has the correct perms:
```
l /data/env/cache/uv/archive-v0/v9yFzmI6xnIw5rZHZhlUq/deepspeed-0.14.4.data/scripts/ds_ssh
-rwxrwxrwx 2 stas stas 680 Jul 26 23:05 /data/env/cache/uv/archive-v0/v9yFzmI6xnIw5rZHZhlUq/deepspeed-0.14.4.data/scripts/ds_ssh
```
I think it's the same problem. But I'm not 100% sure, since this is hardlinking.

@charliermarsh

**Comment by charliermarsh** [comment]
Are the permissions `0o755`? And you want `0o777`?

**Comment by stas00** [comment]
The perms of the source file are correct, but `uv` fails. why is it trying to change perms?

**Comment by charliermarsh** [comment]
The file gets moved. We then set the executable bit on it.

**Comment by charliermarsh** [comment]
It's intended to be this: https://github.com/pypa/pip/blob/0f21fb920647f07439c3ec9fb29579c0e00072ec/src/pip/_internal/utils/unpacking.py#L88. Perhaps it's wrong as-is.

**Comment by stas00** [comment]
Everything works fine for the first user to win the race of being the first to install a new version of a package. The next user installing the same package version into a different conda env fails to install it.

**Comment by stas00** [comment]
Here is what is happening:
```
sudo su usera
touch /tmp/foo
chmod a+rwx /tmp/foo
l /tmp/foo
-rwxrwxrwx 1 usera usera 0 Jul 30 00:47 /tmp/foo*
```
then:
```
sudo su userb
chmod a+rwx /tmp/foo
```

**Comment by charliermarsh** [comment]
I see... So, in your case, only the first install works, since that user owns the file and can change its permissions? But subsequent installs fail, because they can't change the permissions?

I'll think on it. We can either make it robust to these kinds of failures, or _possibly_ remove the `chmod` for files that are copied directly from the cache.

**Comment by charliermarsh** [comment]
I need to test it out. It's very hard to get right.

**Comment by stas00** [comment]
I'm not able to reproduce the hardlinking problem outside of `uv` - it'd help to know how it does it.

```
sudo su usera
touch /tmp/foo
chmod a+rwx /tmp/foo
l /tmp/foo
-rwxrwxrwx 1 usera usera 0 Jul 30 00:47 /tmp/foo*
```
then:
```
sudo su userb
ln /tmp/foo /tmp/bar 
```
no `Operation not permitted` error in this case.

**Comment by stas00** [comment]
> We can either make it robust to these kinds of failures, or possibly remove the chmod for files that are copied directly from the cache.

or perhaps you need to check if you actually need to `chmod` when you copy from cache.

but from https://github.com/astral-sh/uv/issues/5581#issuecomment-2257256596 we now know that it's not the `0666` issue - so not related to the previous PR I linked to.

**Comment by charliermarsh** [comment]
Correct. I see the issue, I believe I can fix it.

**Comment by stas00** [comment]
Thank you, Charles

if after you merge the fix PR you could give me a wheel I could test with (or I guess I could try to patch 0.2.31) then it'd be easier - because as I said hardlinking is potentially another issue to resolve.

**Comment by stas00** [comment]
do you want me to create another issue for:

```
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to hardlink file from /data/env/cache/uv/archive-v0/v9yFzmI6xnIw5rZHZhlUq/deepspeed-0.14.4.data/scripts/ds_ssh to /env/lib/conda/graphrag_raw/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
  Caused by: Operation not permitted (os error 1)
```

as I don't see any treatment of hardlinking in the PR you proposed. Or we could work it out one item at a time. Whatever works for you.

**Comment by charliermarsh** [comment]
Sure. Any more info you can provide would be great, not sure what's going on there. (It doesn't say "Permission denied" so it may not be a permissions issue.)

**Comment by charliermarsh** [comment]
If you want, there are executables available on https://github.com/astral-sh/uv/pull/5582.

**Comment by stas00** [comment]
I confirm that this PR/executable resolves the first issue.

I need to figure out next how to reproduce the 2nd one.

**Comment by stas00** [comment]
ok, I can reproduce this w/ the binary you shared.

This works for the first user:
```
$ sudo su usera
$ /home/stas/uv pip uninstall deepspeed
Uninstalled 1 package in 2.69s
 - deepspeed==0.14.4
$ /home/stas/uv pip install deepspeed
Resolved 34 packages in 517ms
Installed 1 package in 2.42s
 + deepspeed==0.14.4
```

then 2nd user installing into a different conda env:
```
$ sudo su userb
$ /home/stas/uv pip uninstall deepspeed
Uninstalled 1 package in 2.65s
 - deepspeed==0.14.4
$ /home/stas/uv pip install deepspeed
Resolved 34 packages in 280ms
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to hardlink file from /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh to /env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
  Caused by: Operation not permitted (os error 1)
```
Is it possible that is wrong, it should most likely be File exists.

Observe, me doing it directly as a non-owner user:

```
ln /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh
ln: failed to create hard link '/data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh': File exists
```
and indeed the file already exists:
```
l /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh
-rwxr-xr-x 3 stas stas 680 Jul 29 23:14 /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh
```

so I think the same as `chmod` - you want to check if the hard link you want to create already exists.

but then if I do it as the owner of the file it fails too:
```
ln /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh
ln: failed to create hard link '/data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh': File exists
```

So is it possible the error message is reporting wrong file paths?

**Comment by charliermarsh** [comment]
Why would the hard link already exist though?

**Comment by stas00** [comment]
one, sec, I made a mistake. I edited my repro-comment above.

**Comment by stas00** [comment]
so it appears that if any parent dir is not owned by the user who is trying to hardlink - it'd fail.

symlinking works fine though:

```
$ ln /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
ln: failed to create hard link '/data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh' => '/data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh': Operation not permitted

$ ln -s /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
```

**Comment by stas00** [comment]
yes, it's the ownership of the source file that matters. The link's path must have the same ownership as the source it seems.

I `sudo chown`'ed the source to the target's username and then hardlink works.

**Comment by stas00** [comment]
why not use `cp` instead of `ln` if you're concerned the `cache` may go away? `cp` works just fine:

```
$ ln /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
ln: failed to create hard link '/data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh' => '/data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh': Operation not permitted

$ cp /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_ssh /data/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_ssh
# no error
```

**Comment by charliermarsh** [comment]
@stas00 -- The behavior is configurable. You can set `--link-mode=copy` on the command-line or `link-mode = copy` in `uv.toml` or `pyproject.toml`. Hardlinks are just the default on Linux -- they're much faster and much more space-efficient since you don't have isolated copies of every file in every project. (On macOS we use copy-on-write links which is ideal but not supported on most Linux filesystems.)

**Comment by stas00** [comment]
That's unfortunate. `uv` is advertising itself as a drop-in replacement. But if one needs to create a config file somewhere whereas `pip` just works and doesn't use hardlinks - your workaround is not going to work in a shared environment. I have no place to create `uv.toml` - this is meant to be a system-wide tool.

Will have to revert to the slow `pip` :(

**Comment by zanieb** [comment]
Sorry that this is frustrating, but we have made _some_ decisions differently from pip for performance and correctness.

You can set `UV_CONFIG_FILE` on your system and place the file wherever you please.

**Comment by stas00** [comment]
Also as I suggested earlier hardlinking is unsafe in this situation. One user modifying a file in their env will impact all conda envs. If they broke it it'll be broken elsewhere. So I think `copy` is the correct default in a shared environment.

**Comment by stas00** [comment]
> You can set UV_CONFIG_FILE on your system and place the file wherever you please.

That's very helpful, @zanieb - thank you. I will try that!

**Comment by charliermarsh** [comment]
You can also set UV_LINK_MODE=copy if you want to avoid a configuration file altogether.

**Comment by stas00** [comment]
All we want to do is to avoid each user having a copy of `uv` cache - instead we share it - what's so special about? We do the same for conda and pip and many other things - otherwise there will be an insane disk space usage when you multiply each cache by dozens of users.

Thank you for the `UV_LINK_MODE=copy` suggestion - that would work well. `UV_CONFIG_FILE` I can easily handle too. I will test it out and let you know if there are still any hiccups remaining.

I appreciate your amazing support, @charliermarsh and @zanieb and wanting to meet the needs of outliers too.

**Comment by stas00** [comment]
@charliermarsh, your suggestion doesn't work:
```
UV_LINK_MODE=copy /home/stas/uv pip install deepspeed
Resolved 34 packages in 211ms
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to copy file from /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_elastic to /env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_elastic
  Caused by: Operation not permitted (os error 1)
```

**Comment by zanieb** [comment]
The shared cache use-case makes sense, I don't think that's something we've focused on in particular yet — I'm surprised there haven't been more questions about it. I've created another issue to track documenting some recommendations https://github.com/astral-sh/uv/issues/5611

**Comment by stas00** [comment]
@charliermarsh, if I do it manually I get a different error:
```
cp /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_elastic /env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_elastic
cp: '/data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S/deepspeed-0.14.4.data/scripts/ds_elastic' and '/env/lib/conda/tr058-mistral-7b-ft-fin/lib/python3.10/site-packages/deepspeed-0.14.4.data/scripts/ds_elastic' are the same file
```

**Comment by stas00** [comment]
@charliermarsh, I started to get this error with your latest `uv` and `UV_LINK_MODE=copy`:

```
UV_LINK_MODE=copy /home/stas/uv pip install deepspeed
Resolved 34 packages in 175ms
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to fill whole buffer

UV_LINK_MODE=copy /home/stas/uv pip install deepspeed
Audited 1 package in 98ms
```

it then succeeds on the 2nd attempt.

**Comment by charliermarsh** [comment]
Is that a public package? Can I test it somehow?

**Comment by stas00** [comment]
It's the package you gave me yesterday. https://github.com/astral-sh/uv/issues/5581#issuecomment-2257313188

**Comment by charliermarsh** [comment]
Sorry, I meant, the package you're installing.

**Comment by stas00** [comment]
The culprit is `UV_LINK_MODE=copy` - removing it, removes the problem.

Yes, `deepspeed` is a public pypi package.

**Comment by charliermarsh** [comment]
Hmm, ok. Do you see it with the latest Ruff on PyPI? I've never seen that reported and can't reproduce it on main on macOS:

```
cargo run pip install deepspeed==0.14.4 --link-mode=copy  --no-deps
```

I can try it in GitHub Actions to see if it reproduces there.

**Comment by stas00** [comment]
```
cargo run pip install deepspeed==0.14.4 --link-mode=copy  --no-deps
error: could not find `Cargo.toml` in `/home/stas` or any parent directory
```

**Comment by charliermarsh** [comment]
Ah sorry, I meant, if you just `pip install uv` then run `uv pip install deepspeed==0.14.4 --link-mode=copy  --no-deps` in your environment, does that fail too? Trying to understand if it's a new regression from the latest release.

**Comment by stas00** [comment]
same issue w/ uv==0.2.31
```
$ pip install uv
Requirement already satisfied: uv in /data/env/lib/conda/stas-inference/lib/python3.10/site-packages (0.2.31)
$ uv pip uninstall deepspeed
Uninstalled 1 package in 1.87s
 - deepspeed==0.14.4
$ uv pip install deepspeed==0.14.4 --link-mode=copy  --no-deps
Resolved 1 package in 61ms
error: Failed to install: deepspeed-0.14.4-py3-none-any.whl (deepspeed==0.14.4)
  Caused by: failed to fill whole buffer
```

**Comment by charliermarsh** [comment]
It looks like it ran without error here: https://github.com/astral-sh/uv/pull/5615

**Comment by stas00** [comment]
You meant this one, right? https://github.com/astral-sh/uv/actions/runs/10167135512/job/28118835463?pr=5615

I was able to overcome this problem by first nuking the cache:

```
rm -rf /data/env/cache/uv/archive-v0/3bJMARV6EJsb_nzOq2K_S
uv pip uninstall deepspeed
Uninstalled 1 package in 2.14s
 - deepspeed==0.14.4
dojo-a3-ghpc-61:1-|stas-inference ~> uv pip install deepspeed==0.14.4 --link-mode=copy  --no-deps
Resolved 1 package in 7ms
Installed 1 package in 2.33s
 + deepspeed==0.14.4
```

works with `UV_LINK_MODE=copy /home/stas/uv pip install deepspeed` as well.

**Comment by charliermarsh** [comment]
Great!!!
