### ISSUE TITLE
Update `astral.sh` to reference new uv documentation

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5606]

**Comment by nikhilweee** [comment]
There's `rye.astral.sh`, there's `astral.sh/ruff`, and then there's `astral.sh/uv` which points to this github repo. Any plans for standardization? I'd love to see landing pages at `astral.sh/<tool>`, and the corresponding docs at `docs.astral.sh/<tool>`

**Comment by zanieb** [comment]
Yes. we'll need a landing page for uv. I don't know if we'll add Rye to the Astral website — we've taken over stewardship of the project but I'm not sure it's a "product under our brand".
