### ISSUE TITLE
Publish variants of Docker image

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5610]
Instead of only supplying a bare image, we should publish an alpine variant and a variant with Python so people can use our image without creating a custom derivative.

**Comment by zanieb** [comment]
For example, this is important for GitLab CI which requires `sh`.

This applies to Ruff as well.

**Comment by zanieb** [comment]
This should basically be trivial, we just need to setup a folder with a few variants, copy in the executable from the scratch image, and publish them each release.

**Comment by konstin** [comment]
When building an optimized production image, i'd need two base images: A builder with uv, my python version and ideally a bunch of dev libraries (curl, git, gcc, dev headers), and a runner image that has python in the same location as the builder, in which i only copy the venv and call `python` as entrypoint.

**Comment by zanieb** [comment]
I think we can describe a few goals here:

1. Allow uv to be used in GitLab CI, i.e. provide a image with a shell
2. Allow uv to be used as a Python image, i.e. provide an image for each Python version with development tools
3. Document best practices for deriving a minimal production image from (2)

**Comment by mayuresh-quartic** [comment]
I can suggest few approach to this:
- Pull latest python slim images
- Install uv latest version in global system

I can create Dockerfiles quickly for this

This will be minimal with no extra apt or system packages

**Comment by zanieb** [comment]
Sure, a couple notes:

- I think I'd use a single Dockerfile parameterized on Python version. 
- We should copy the `uv` executable from our scratch Docker image instead of installing from, e.g., curl

**Comment by mayuresh-quartic** [comment]
For example here is the uv image i created based on Python3.9 version: mayuresh14/uv-python39-slim

Dockerfile looks like this
```
FROM --platform=linux/amd64 python:3.9-slim

RUN pip install uv
```

I will keep in mind your mentioned notes and create a PR soon
