### ISSUE TITLE
Error messages should omit `a==1`-to-`a==1{marker}` relationships

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5612]
See: https://github.com/orgs/astral-sh/projects/11/views/8?pane=issue&itemId=70300371

**Comment by zanieb** [comment]
Is this a dupe of https://github.com/astral-sh/uv/issues/5618 now?

**Comment by charliermarsh** [comment]
Oh sorry.

**Comment by charliermarsh** [comment]
Wait mine was first :)

**Comment by zanieb** [comment]
His is better :)
