### ISSUE TITLE
If resolution fails after `uv add`, should we remove the dependency?

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5622]
It's confusing because running `uv add` again with a different dependency will continue to fail.

**Comment by ibraheemdev** [comment]
I think we should. If `uv add` fails the `pyproject.toml` should not be updated.

**Comment by charliermarsh** [comment]
I tend to agree.

**Comment by charliermarsh** [comment]
I will try to do this tomorrow.
