### ISSUE TITLE
Consistent usage of "pre-release" vs. "prerelease"

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#5630]
Similar to https://github.com/astral-sh/uv/pull/5629. Also `pre_release` vs. `prerelease` and `PreRelease` vs. `Prerelease` in code.

**Comment by charliermarsh** [comment]
I think it should be "prerelease" (single word) to match PEP 440.

**Comment by zanieb** [comment]
Sounds good to me.

**Comment by charliermarsh** [comment]
Oh no, PEP 440 uses "prerelease" once but "pre-release" many times. Rust also seems to use "pre-release": https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases. And SemVer uses pre-release too: https://semver.org/.

So I'm going back on my suggestion: we should use "pre-release", and thus `PreRelease` in code.

**Comment by charliermarsh** [comment]
Cargo uses "prerelease" in the code and error messages though.

**Comment by charliermarsh** [comment]
My preference is "pre-release" but then `Prerelease` in code, even though it's not fully consistent.

**Comment by charliermarsh** [comment]
Ok, let's do that then.

**Comment by charliermarsh** [comment]
I will fix it up now.
