### ISSUE TITLE
Workspace wildcard member should only match directory

### ISSUE THREAD

**Issue by jpambrun-vida** [astral-sh/uv#5725]
I have a project with the form
```
service/
   README.md
   service_a/
     pyproject.toml
     src/
   service_b/
     pyproject.toml
     src/
```

with
```toml
members = [
  "services/*"
]
```

I get
```
 uv sync
error: failed to read from file `/####/services/README.md/pyproject.toml`
  Caused by: Not a directory (os error 20)
```

A simple fix would be to filter out files. 
It also complains if any subfolder doesn't contain a pyproject.toml. Would it be better if it would ignore them?
Being able to recursively search for pyproject.toml would also be nice.

**Comment by charliermarsh** [comment]
That's funny, I just added #5724.

> It also complains if any subfolder doesn't contain a pyproject.toml. Would it be better if it would ignore them?

You should mark any such directories as excluded via `workspace.exclude`.

**Comment by jpambrun-vida** [comment]
I know about exclude, but I imagined it was to explicitly exclude a folder with a pyproject.toml while not erroring out of folder not containing any.

I can see it both ways..

**Comment by charliermarsh** [comment]
Yeah, Cargo rejects directories that are listed as members but aren't valid packages, so I think we followed that precedent.
