### ISSUE TITLE
uv 0.2.32 ignores development resolutions when running `pip compile`

### ISSUE THREAD

**Issue by A5rocks** [astral-sh/uv#5729]
The issue title isn't great, I'm not sure how to best describe this. However, here's a reproduction:

In `a.in`:
```
cffi
```

In `a.txt`:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile a.in -o a.txt
cffi==1.17.0rc1
    # via -r a.in
pycparser==2.22
    # via cffi
```

Now, run `uv pip compile a.in -o a.txt` and note that `a.txt` was modified to become:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile a.in -o a.txt
cffi==1.16.0
    # via -r a.in
pycparser==2.22
    # via cffi
```

Note that I'm not passing any sort of upgrade flag. This did not happen in `uv==0.2.26`. I can reproduce this on both Debian Linux and Windows. Found in https://github.com/python-trio/trio/pull/3043.

**Comment by notatallshaw** [comment]
For context, there was some previous discussion about prereleases with pip compile in the out file: https://github.com/astral-sh/uv/issues/3602.

**Comment by A5rocks** [comment]
Bisected to https://github.com/astral-sh/uv/commit/c8ac8ee57aa51d544d00af42d8ea96a282116532

@ibraheemdev

**Comment by charliermarsh** [comment]
I agree this is a bug, thanks.

**Comment by charliermarsh** [comment]
Working on it.
