### ISSUE TITLE
uv run --isolated does not use .python-version

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#5740]
From the description, it could be expected that uv run --isolated derives some of its settings from the active project, like python version. Here's a strange situation, with an active virtualenv, but it was from a real situation.

I was thinking `uv run` is anchored in the project and an active virtualenv should not matter for its behaviour.

Problem seen here: `uv run python` launches py 3.12, but `uv run --isolated python` runs 3.11.
Why this could be a problem: the current project is requires-python>=3.12, and we want to run it, so we should start in that end (?)

```shell
uv init uvpy12 -p 3.12
cd uvpy12/
uv python pin 3.12
uv venv -p 3.11 py311
# Using Python 3.11.9
# Creating virtualenv at: py311
# Activate with: source py311/bin/activate
source py311/bin/activate
# (py311)
uv run python
# Python 3.12.4 (main, Jul 25 2024, 22:42:01) [Clang 18.1.8 ] on linux
# Type "help", "copyright", "credits" or "license" for more information.
# >>> ^D

uv run --isolated python
```

```
warning: `uv run` is experimental and may change without warning
  × No solution found when resolving dependencies:
  ╰─▶ Because the current Python version (3.11.9) does not satisfy Python>=3.12 and uvpy12==0.1.0
      depends on Python>=3.12, we can conclude that uvpy12==0.1.0 cannot be used.
      And because only uvpy12==0.1.0 is available and you require uvpy12, we can conclude that the
      requirements are unsatisfiable.

```

Version: uv 0.2.33

**Comment by charliermarsh** [comment]
I think `--isolated` should still discover a `.python-version`, that was the intent at least. Will look into it.

**Comment by charliermarsh** [comment]
Nice bug, thank you!
