### ISSUE TITLE
`Ctrl-C` interruptes `uv python install` and leaves temporary files

### ISSUE THREAD

**Issue by j178** [astral-sh/uv#5747]
`uv python install` creates a temporary directory at `$HOME/Library/Application Support/uv/python`. If the process is interrupted with `Ctrl-C`, the temporary files are not deleted, resulting in numerous hidden directories left behind. It might be beneficial to change the temporary download location to the system-level `/tmp`, which is periodically cleaned by the system.

**Comment by charliermarsh** [comment]
Using `/tmp` has other problems, namely that the temporary directories won't be colocated with the final locations. This can cause problems, for example, you can't hardlink between them if they happen to be on separate filesystems. So we tend to use temporary directories colocated with wherever we're writing.
