### ISSUE TITLE
Incorrect default value for python-preference in ``docs/reference/settings.md``

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/uv#5754]
According to  https://github.com/astral-sh/uv/pull/5637 , the default value in the document should be changed to "``only-managed``" because the managed behavior requires ``--preview``. However, if the document is intended for post-stabilization behavior (without ``--preview``), it should also be changed to "``managed``" instead of using a removed value.
I'm not sure which one should be changed to so I won't create a PR for it
https://github.com/astral-sh/uv/blob/257007ccaf0912a41dfe91b534527a7b1f54e19a/docs/reference/settings.md?plain=1#L646

https://github.com/astral-sh/uv/blob/257007ccaf0912a41dfe91b534527a7b1f54e19a/crates/uv-python/src/discovery.rs#L61-L69

Edit (according to my PR):
After referring to https://github.com/astral-sh/uv/pull/5637 and doing additional testing.
The default value in a stable state seems more reasonable to be only-system. managed in preview.

**Comment by charliermarsh** [comment]
Apologies, this changed recently. PR welcome. We can include both the stable and preview value in the default field.
