### ISSUE TITLE
Show ephemeral progress bar in `uv run` and `uv tool run`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5758]
When the environment _isn't_ cached / readily available, I think these now show _too little_ logging (for large environments, it feels like it's just hanging, when in reality it's preparing the environment). We should just show a spinner in those cases at least.

**Comment by zanieb** [comment]
I guess `cargo run` isn't quiet by default, maybe we should reconsider? We should definitely show if we need to _build_ the root project.

**Comment by charliermarsh** [comment]
Yeah it's too quiet right now... Something ideas (not mutually exclusive):

- Show an ephemeral spinner (so, it disappears once complete) if we have to do any work? Unfortunately we might have to "always" show this for `uv tool run` because (if the tool isn't already-installed) we have to perform a resolution even if we end up using a cached environment.
- Show the "Building" and "Built" outputs always?
- Show the "Installed X packages..." output but not the full list of modifications?

**Comment by konstin** [comment]
Personally, i'd like `uv run` to be completely if everything is cached (i do `cargo run -q` often enough), show a spinner if something isn't and `Building`/`Built`/`Installed X packages in Yms` summary messages if something changes (but not the whole list of packages).

**Comment by charliermarsh** [comment]
I agree. The main problem there is that with `uv tool run`, we have to resolve in order to locate a cached environment 🤔
