### ISSUE TITLE
How to install an application that uses --index-url (in this example its pytorch/torch)

### ISSUE THREAD

**Issue by theogbob** [astral-sh/uv#5762]
Version: 
  ```
  $> uv --version
  uv 0.2.33
```
Command being ran:
```
uv pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.1
```
Issue:
It ignores index url and uses the pre-installed version, if i remove the current torch modules it just installs them like normal (for nvidia) and doesnt include the rocm support from index-url

**Comment by charliermarsh** [comment]
Can you include the logs of running with `--reinstall` and `--verbose`? `--reinstall` will cause uv to ignore the already-installed versions.

**Comment by cp2boston** [comment]
I have had success with `uv pip install --no-cache-dir torch==2.3.1+cpu -f https://download.pyto
rch.org/whl/torch_stable.html`

**Comment by stas00** [comment]
I was just about to report the same:

```
uv pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of torch==2.3.1 and you require torch==2.3.1, we can conclude that the requirements are unsatisfiable.


pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch==2.3.1
  Downloading https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl (781.0 MB)
  ...
```

**Comment by charliermarsh** [comment]
That's odd, I'll take a look.

**Comment by charliermarsh** [comment]
We generally require that you set local versions explicitly, like:

```
uv pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121
```

It's documented in more detail here: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#local-version-identifiers

**Comment by stas00** [comment]
The install command was copied from pytorch instructions https://pytorch.org/get-started/previous-versions/#linux-and-windows-1

perhaps we can convince them to add a `uv` section? in addition to `conda` and `pip`? :)

**Comment by theogbob** [comment]
oops forgot to check up on this issue, I see if the solution worked for me when ive got some time to test since i ended up just using pip and venv normally
