### ISSUE TITLE
uv run strips quotes

### ISSUE THREAD

**Issue by palfrey** [astral-sh/uv#5765]
`uv run` seems to strip quotes from the command, and I'm yet to figure out a way around it.

Demo of the problem:
1. Dump the following into `demo.sh`
```bash
#!/bin/bash 
for i; do 
   echo $i
done
```
2. Run `uv run bash demo.sh foo bar` and `uv run bash demo.sh "foo bar"` and see how both treat foo and bar as two args and not one in the second case. `uv run bash demo.sh ""foo bar""` also behaves exactly the same...

Version: 0.2.33

**Comment by charliermarsh** [comment]
Thanks, that seems off.

**Comment by charliermarsh** [comment]
Wait sorry, what's the expected behavior here?

```
❯ ./demo.sh "foo bar"
foo bar

❯ cargo run -- run bash demo.sh "foo bar"
foo bar
```

**Comment by palfrey** [comment]
Argh. Whoops, my fault. I've got a script I was running uv via (like https://github.com/palfrey/fenestra/blob/main/uv but in something currently unreleased) which I've just realised ends with the line `$UV $*` when it should have been `$UV "$@"` and fixing that removes the bug.

Apologies, thanks for checking things.
