### ISSUE TITLE
`uv lock` seems to ignore index-url from `uv.toml`

### ISSUE THREAD

**Issue by tinovyatkin** [astral-sh/uv#5789]
I'm having `uv.toml` in the current directory with `index-url` and it used by `uv pip install` without any problem. However `uv lock` seems to ignore that file and I need to provide `index-url` via extra CLI param. Is that by design?

```sh
→ uv --version                                                   
uv 0.2.33 (b14945a7b 2024-08-01)
```

**Comment by charliermarsh** [comment]
Is the `index-url` under `[pip]` or at the top-level? If it's under `[pip]`, it will only be used in the `pip` interface. If it's at the top-level, it will be used everywhere.

**Comment by tinovyatkin** [comment]
@charliermarsh thank you, it was under `pip`, I will try to move it top level.
