### ISSUE TITLE
0.2.28 broke Nox support by changing how local reinstallation works

### ISSUE THREAD

**Issue by hynek** [astral-sh/uv#5790]
I've run into the weirdness that Nox paired with uv stopped re-installing the local package and the tests ran against old code.

I've bisected the behavior and it looks like the change was introduced with uv 0.2.28 because it works with 0.2.27. It doesn't seem to be cache related since deleting the cache didn't help.

I've seen mentions of `--reinstall-package` for uv, but it used to work recently and I'd rather not hard-couple my noxfile to uv if it can be helped.

I've ran into it while working on https://github.com/hynek/stamina so it could be a decent way to test. I've even added debug output out the package versions when running pytest. The number behind dev should increment after each commit.

**Comment by konstin** [comment]
Are you using dynamic metadata? In that case it's probably https://github.com/astral-sh/uv/pull/5206

**Comment by hynek** [comment]
I do! hatch-vcs (which is setuptools-scm under the hood).

**Comment by konstin** [comment]
Does this option help? https://docs.astral.sh/uv/reference/settings/#reinstall-package

**Comment by hynek** [comment]
Hm yes but since I didn't want to couple my noxfile to uv (they support graceful fallbacks), I've set it in pyproject.toml using `tool.uv.reinstall-package`. Is that how it's supposed to be used or will that have some weird side-effects?

**Comment by charliermarsh** [comment]
@hynek -- That should be totally fine. If you want to "always reinstall the package" (the previous behavior), that's the right thing to do.

**Comment by hynek** [comment]
OK, I guess it's a documentation issue for Nox then – thanks!
