### ISSUE TITLE
Add `--no-sources` to allow locking, syncing, and installing without `tool.uv.sources`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5791]
It's seems important to be able to test this workflow, if you consider sources to be dev dependencies.

**Comment by charliermarsh** [comment]
If no one objects I can add it, not too hard.

**Comment by chrisrodrigue** [comment]
There are a couple of options that can accomplish similar things (`--offline`, `--no-index`, and now  `--no-sources`).

Would `--offline` imply both `--no-index` and `--no-sources`? Or would it still allow local indices/sources?

**Comment by zanieb** [comment]
I think `--offline` and `--no-index` have no effect on local sources i.e. paths — these things have relatively distinct meanings even if in some cases they could have the same effect.
