### ISSUE TITLE
Support `uv tool run {package}@latest`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5807]
We support, e.g., `uv tool run ruff@0.4.0`. We may want to add `uv tool run ruff@latest`. What should the semantics be, though?

**Comment by zanieb** [comment]
I think: implies `--refresh` (i.e. do not use the cache) and ignores installed tools.

**Comment by charliermarsh** [comment]
As part of this, we also want to remove `--upgrade` from `uv tool run`...
