### ISSUE TITLE
Invoking `python` can fail if the interpreter is named `python3`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5838]
e.g.

```
❯ uv run -v python -c "import anyio"
DEBUG uv 0.2.32
warning: `uv run` is experimental and may change without warning
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python interpreter in managed installations or system path
DEBUG Searching for managed installations at `/Users/zb/Library/Application Support/uv/python`
DEBUG Found managed installation `cpython-3.12.1-macos-aarch64-none`
DEBUG Found `cpython-3.12.1-macos-aarch64-none` at `/Users/zb/Library/Application Support/uv/python/cpython-3.12.1-macos-aarch64-none/bin/python3` (managed installations)
DEBUG Using Python 3.12.1 interpreter at: /Users/zb/Library/Application Support/uv/python/cpython-3.12.1-macos-aarch64-none/bin/python3
DEBUG Running `python -c import anyio`
error: Failed to spawn: `python`
  Caused by: No such file or directory (os error 2)
```

We should detect and special case `python`, I think.

**Comment by charliermarsh** [comment]
Huh. I thought there was always a `python` alias in there.

**Comment by zanieb** [comment]
Should we add one to our installs?

```
❯ ls '/Users/zb/Library/Application Support/uv/python/cpython-3.12.1-macos-aarch64-none/bin/'
2to3			idle3			pip			pip3.12			pydoc3.12		python3-config		python3.12-config
2to3-3.12		idle3.12		pip3			pydoc3			python3			python3.12
```

**Comment by charliermarsh** [comment]
I guess this would succeed if we always ran in a new environment...

**Comment by charliermarsh** [comment]
We should probably create a symlink there though. It's interesting that we have `pip` and `pip3` but not `python`.

**Comment by charliermarsh** [comment]
Doing some research, it looks like this was. added to `python-build-standalone` in https://github.com/indygreg/python-build-standalone/commit/e9427bd059465e6472ea6ac80e6dd849e53f3e64, and [PEP 394](https://peps.python.org/pep-0394/) says it's allowed. So wondering why it didn't appear here. I'll debug.

**Comment by charliermarsh** [comment]
Oh, maybe it was added for Linux but not macOS.

**Comment by charliermarsh** [comment]
I think the symlink is being filtered out when unzipping.

**Comment by zanieb** [comment]
Regardless of its presence in the python-build-standalone installations, should we special case `python` in `uv run`?

**Comment by charliermarsh** [comment]
I don’t think so personally.

**Comment by zanieb** [comment]
Alright, we can see if it comes up.

**Comment by charliermarsh** [comment]
(Do you mean: if they use `python`, we inject the full path to the interpreter?)

**Comment by charliermarsh** [comment]
On my machine at least, these _do_ have a `python`:

- cpython-3.8.18-macos-aarch64-none
- cpython-3.9.18-macos-aarch64-none
- cpython-3.10.13-macos-aarch64-none

While these do not:

- cpython-3.8.12-macos-aarch64-none
- cpython-3.11.7-macos-aarch64-none
- cpython-3.12.1-macos-aarch64-none

**Comment by charliermarsh** [comment]
Ah ok, it looks like those distributions actually don't contain a `python`. So it's an inconsistency in `python-build-standalone`.

**Comment by charliermarsh** [comment]
Ooooh those versions pre-date the introduction of that feature.

**Comment by charliermarsh** [comment]
I'm going to change our installer to add it
