### ISSUE TITLE
`uv add https://.../foo.git` throws a confusing error

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5858]
We interpret it as a direct URL (e.g., a path to a wheel), and then `.git` doesn't match `.whl` or `.tar.gz` etc.

```
❯ uv add https://github.com/ElmerCSC/elmer_circuitbuilder.git
warning: `uv add` is experimental and may change without warning
Using Python 3.12.4
Creating virtualenv at: .venv
error: Failed to extract archive
  Caused by: Unsupported archive type: elmer_circuitbuilder.git
```

**Comment by charliermarsh** [comment]
Arguably this should "just work"?

**Comment by charliermarsh** [comment]
(Instead, you need to do, e.g., ` add git+https://github.com/ElmerCSC/elmer_circuitbuilder.git`.)

**Comment by zanieb** [comment]
Yeah the `git+` seems overkill to require, let's special case `.git`.

**Comment by charliermarsh** [comment]
(I also want to improve that error message to list the supported extensions, it would be much clearer.)
