### ISSUE TITLE
`dependencies` cannot be missing when `requires-python` is present in inline script metadata

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5859]
e.g.

```python
# /// script
# requires-python = ">=3.12"
# ///

pass
```

```
❯ uv run script.py
warning: `uv run` is experimental and may change without warning
error: TOML parse error at line 1, column 1
  |
1 | requires-python = ">=3.12"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `dependencies`
```

I honestly cannot tell if this is complaint with the [specification](https://packaging.python.org/en/latest/specifications/inline-script-metadata/#inline-script-metadata).

> This document MAY include the top-level fields dependencies and requires-python, and MAY optionally include a [tool] table.

**Comment by charliermarsh** [comment]
I think we need to be robust to them being absent.
