### ISSUE TITLE
`uv add` should support adding dependencies without updating the environment

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5867]
e.g. `uv add --no-sync`

The same for `uv remove`.

**Comment by charliermarsh** [comment]
`--frozen` does this, unless you're describing something else.

**Comment by zanieb** [comment]
I want to update the lockfile, but not install into the virtual environment.

**Comment by charliermarsh** [comment]
Why?

**Comment by zanieb** [comment]
What if I don't have a virtual environment and I'm just trying to modify the declared dependencies in an automated script? Why have all the overhead of installing the project to a virtual environment?

**Comment by zanieb** [comment]
(This came up when writing documentation — we could wait until someone asks for it before adding but I do think it makes sense)

**Comment by charliermarsh** [comment]
It's reasonable! Just wary of adding too many flags here.
