### ISSUE TITLE
`uv lock --locked` false positive

### ISSUE THREAD

**Issue by tpgillam** [astral-sh/uv#5902]
Using uv `0.2.34`. A potentially similar issue to #5851 

Consider the following `pyproject.toml`:

```toml
[project]
name = "moo"
version = "0.1.0"
dependencies = ["pyelmer ~=1.2", "pymongo[srv] ~=4.3.3"]
requires-python = ">=3.11"
```

I then can run the following in an otherwise empty directory (`rm uv.lock` just lets me re-run quickly):
```bash
rm uv.lock && uv lock && cp uv.lock ref_uv.lock && uv lock && diff ref_uv.lock uv.lock && uv lock --locked
```

and get the output:
```
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 21 packages in 31ms
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 21 packages in 33ms
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 21 packages in 35ms
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```

So `uv.lock` wouldn't have actually changed, but `uv` fails because it think it would have done.

A few assorted things I've noticed:

- The `srv` extra in pymongo exists in 4.3.3, but not in the latest version. In 4.3.3 it's actually [an empty set of pacakges](https://github.com/mongodb/mongo-python-driver/blob/3d032768a0c617e4c594cb3f971df1cd06b3e0d4/setup.py#L289). In the `uv.lock`, we never actually get an `extra = "srv"` entry under pymongo - presumably because it finds that its empty. But possibly this is undesired.

- If I remove the `pyelmer` dependency then there isn't a problem. In this simpler case, the `uv.lock` does not contain an `environment-markers` section.

- If I remove the `[srv]` extra from pymongo there also isn't a problem.

- If I replace the `[srv]` extra with `[encryption]`, which is a non-empty set, then we have a slightly different scenario that doesn't fail per-se, but also seems fishy:

```bash
rm uv.lock && uv lock && cp uv.lock ref_uv.lock && uv lock && diff ref_uv.lock uv.lock || uv lock --locked
```

```
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 38 packages in 37ms
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 38 packages in 15ms
43c43
<     { name = "urllib3" },
---
>     { name = "urllib3", marker = "python_version == '3.11' or python_version >= '3.12' or (python_version < '3.12' and (python_version < '3.11' or python_version > '3.11'))" },
warning: `uv lock` is experimental and may change without warning
Using Python 3.11.9
Resolved 38 packages in 14ms
```

namely that the second call to `uv lock` does actually now change the lock file. This is probably a separate issue, and maybe not really a problem (I'm not sure how strong an idempotency guarantee on `uv lock` there is?)

**Comment by konstin** [comment]
Yes, the new markers will probably fix this

**Comment by ibraheemdev** [comment]
After https://github.com/astral-sh/uv/pull/5898, `uv lock` actually produces an invalid lockfile:
```
[[package]]
name = "moo"
version = "0.1.0"
source = { editable = "." }
dependencies = [
    { name = "pyelmer" },
    { name = "pymongo" },
    { name = "pymongo" },
]
```

Investigating further.

**Comment by charliermarsh** [comment]
I think this may need one of Andrew’s changes…? Is that plausible?

**Comment by ibraheemdev** [comment]
I think there's a simpler issue here.
