### ISSUE TITLE
Project reinstalls should be special cased in install summary

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#5912]
e.g.

```
❯ uv init
Initialized project `example`

❯ uv sync
Using Python 3.12.1
Creating virtualenv at: .venv
Resolved 1 package in 3ms
   Built example @ file:///Users/zb/workspace/example
Prepared 1 package in 152ms
Installed 1 package in 0.94ms
 + example==0.1.0 (from file:///Users/zb/workspace/example)

❯ uv add anyio
Resolved 4 packages in 5ms
   Built example @ file:///Users/zb/workspace/example
Prepared 4 packages in 151ms
Uninstalled 1 package in 0.34ms
Installed 4 packages in 2ms
 + anyio==4.4.0
 - example==0.1.0 (from file:///Users/zb/workspace/example)
 + example==0.1.0 (from file:///Users/zb/workspace/example)
 + idna==3.7
 + sniffio==1.3.1

❯ uv add anyio
Resolved 4 packages in 2ms
   Built example @ file:///Users/zb/workspace/example
Prepared 1 package in 152ms
Uninstalled 1 package in 0.41ms
Installed 1 package in 0.89ms
 - example==0.1.0 (from file:///Users/zb/workspace/example)
 + example==0.1.0 (from file:///Users/zb/workspace/example)

❯ uv remove anyio
Resolved 1 package in 5ms
   Built example @ file:///Users/zb/workspace/example
Prepared 1 package in 152ms
Uninstalled 4 packages in 3ms
Installed 1 package in 0.99ms
 - anyio==4.4.0
 - example==0.1.0 (from file:///Users/zb/workspace/example)
 + example==0.1.0 (from file:///Users/zb/workspace/example)
 - idna==3.7
 - sniffio==1.3.1
```

It's really noisy to see `example` (my own project) being reported as added and removed on every operation.

**Comment by charliermarsh** [comment]
Do you think we should omit them? Would it be solved by creating a better UI in general for reinstalls (i.e., one line that summarizes the reinstall, rather than a removal and addition)?

**Comment by zanieb** [comment]
I think it's probably safe to omit entirely in this case?

**Comment by charliermarsh** [comment]
I worry that's going to cause more confusion. Alternatively we could _not_ reinstall the project in these cases and use a more specific cache key (e.g., the `pyproject.toml` content rather than the timestamp).

**Comment by charliermarsh** [comment]
Wait sorry, that wouldn't work either, the `pyproject.toml` _is_ changing.

**Comment by zanieb** [comment]
In what case would it be important that the editable install of my package was re-created?

**Comment by zanieb** [comment]
Notably, I think we cover "something happens during build" with the "Built example @ file:///Users/zb/workspace/example" line.

**Comment by charliermarsh** [comment]
If you defined new entry points, for example. Those need to be added to the bin directory of the virtualenv.

**Comment by zanieb** [comment]
That doesn't seem critical to display on every dependency change though?

**Comment by charliermarsh** [comment]
When do we include the project(s) in the output, then? I also want to improve this but I think it's fairly nuanced... If the answer is "we never show it", what happens in the following cases:

- First time you sync a project, and it has no dependencies (so we'd show nothing, even though we installed the project).
- You do a strict sync with `--package`, and _want_ to know which workspace members were added or removed.
- You run with `--reinstall-package my-package`, and want visual confirmation that the package was reintalled.

I also worry about showing it conditionally, since then users will be unsure when / if the project was reinstalled.

Would a better solution be to... rebuild and reinstall the project less often?

**Comment by zanieb** [comment]
1) We should show installing the project if it was _not_ installed
2) We should show adding and removing workspace members, but not reinstalling editable workspace members
3) Hm...

I think as a starting point, we could improve the reinstall output so it only shows a single line then see how obtrusive it is?

Reducing the rebuilds and reinstalls seems complicated, I don't see how we can avoid a rebuild when the pyproject.toml changes, e.g., adding a dependency.

**Comment by charliermarsh** [comment]
I'll play around with this today. I know it can be improved, though I'm not sure what the best approach is.

**Comment by charliermarsh** [comment]
This happened thanks to @zanieb.
