### ISSUE TITLE
`uv lock` should invalidate lockfile if registries change

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#5920]
If a lockfile lists a package from a registry that isn't part of the index URLs passed to `uv lock`, we should probably not reuse it.

**Comment by charliermarsh** [comment]
I'm actually unsure about this. Like if you do:

```
uv add idna --index-url https://test.pypi.org/simple
```

And then `uv lock` later (no arguments)... should we "allow" the lockfile to use the existing entries, which reference https://test.pypi.org/simple?

**Comment by zanieb** [comment]
Definitely! Seems weird to force everything to use another index URL in an `add` operation.

**Comment by charliermarsh** [comment]
The only quirk is that if you don’t specify _any_ index URL, we treat it as PyPI, so the lock would be invalidated if you “stop” passing it on the command-line for any command.

**Comment by charliermarsh** [comment]
Actually, I think the type is rich enough that we can avoid enforcing this if no index URLs are provided (i.e., assume the lockfile is fine). It's a little strange because if we fail, we'll then resolve against PyPI. But probably fine in practice.
