### ISSUE TITLE
Resolve from lockfile cannot detect yanked versions

### ISSUE THREAD

**Issue by ibraheemdev** [astral-sh/uv#5928]
When resolving from the lockfile we don't query the registry and so cannot detect yanked versions. We should document this or add an explicit check for yanked versions even when resolving from the lockfile.

**Comment by zanieb** [comment]
I will document this caveat, it's probably infeasible to support warning here at runtime.

**Comment by zanieb** [comment]
Is this relevant for `uv run` and `uv sync` or more?
