### ISSUE TITLE
Parent uv.toml configuration not used when pyproject.toml present

### ISSUE THREAD

**Issue by ttrei** [astral-sh/uv#5929]
Given this project structure
```
==> uv.toml <==
[pip]
emit-index-url = true

==> foo/pyproject.toml <==
[project]
name = "foo"
dependencies = [
  "httpx",
]
```
uv should load configuration from uv.toml:
https://github.com/astral-sh/uv/blob/bf0497e652d4de8a880d047d15acd01c2de9b4ae/docs/configuration/files.md
> If a pyproject.toml file is found, uv will read configuration from the [tool.uv.pip] table. For example, to set a persistent index URL, add the following to a pyproject.toml:
> (If there is no such table, the pyproject.toml file will be ignored, and uv will continue searching in the directory hierarchy.)
> If a uv.toml file is found, uv will read from the [pip] table.

But it considers uv.toml only if pyproject.toml is not present:
```
> cd foo
> uv pip compile pyproject.toml --show-settings | grep emit_index_url
        emit_index_url: false,
> rm pyproject.toml
> uv pip compile pyproject.toml --show-settings | grep emit_index_url
        emit_index_url: true,
```

Reproduced with 0.2.12 and later versions (latest 0.2.34).
It works correctly in 0.2.11.

**Comment by charliermarsh** [comment]
I'll take a look, that seems wrong.
