### ISSUE TITLE
Activation prompt with invalid path on Windows Git Bash

### ISSUE THREAD

**Issue by BenediktMaag** [astral-sh/uv#5950]
Windows 11, uv 0.2.34 (c681c5a33 2024-08-07)

Activating a environment after creating it:

$ uv v
Using Python 3.12.0 interpreter at: C:\Users\MaagB\AppData\Local\Programs\Python\Python312\python.exe
Creating virtualenv at: .venv
Activate with: source .venv\Scripts\activate

$  source .venv\Scripts\activate
bash: .venvScriptsactivate: No such file or directory

Problem:
git bash on windows seems to resolve the escape sequences before making the source call. To properly activate the environment we either need to properly espace the backslash by another backslash:

$ source .venv\\Scripts\\activate
(tmpinstall)

Or use the Unix Path:
$ source .venv/Scripts/activate
(tmpinstall)

**Comment by zanieb** [comment]
Thanks for the report!

**Comment by charliermarsh** [comment]
Do we need to treat Windows Git Bash as its own shell?

**Comment by zanieb** [comment]
I think it should be sufficient to always use the portable path

**Comment by zanieb** [comment]
As in https://github.com/astral-sh/uv/pull/5956

It might make sense to special-case Windows Git Bash still, we see oddities with it.
