### ISSUE TITLE
Add link to documentation (docs.astral.sh/uv)

### ISSUE THREAD

**Issue by nikhilweee** [astral-sh/uv#5973]
For weeks, I thought `uv` did not have documentation available apart from the README. Then I stumbled upon [docs.astral.sh/uv](https://docs.astral.sh/uv/)

It would be great if this link could be advertised at least in two places:
1. In the repository "About" section
2. Relevant sections in the README.

A good comparison is `ruff`, which has a link to its docs in the repository "About" section and in various places in its README.

**Comment by nikhilweee** [comment]
Honestly I'm fine with just doing (1), but that needs to be done by an admin.

**Comment by zanieb** [comment]
You can follow https://github.com/astral-sh/uv/issues/5606 and #5607 

This documentation is not intended for public consumption yet, hence not being advertised anywhere. We'll announce it soon!

**Comment by zanieb** [comment]
If you have feedback though, please feel free to comment at #5605 — I'd love to hear your perspective on the documentation itself.

**Comment by nikhilweee** [comment]
Apologies for not searching enough, I remember searching the issues for any links to documentation a few days ago but those issues you refer to were opened last week. Eagerly waiting for the docs! Thank you for all the hard work!
