### ISSUE TITLE
Project manager frontend

### ISSUE THREAD

**Issue by orion160** [astral-sh/uv#6000]
I see that uv is incorporating functionality to interact with the new pyproject.toml project layout #5903.

Having that, I see that the build backend hatchling offers hatch CLI as frontend, but now this functionality is also being worked at uv

What will be the scope of this project in the long run?

**Comment by zanieb** [comment]
Yes, uv will be a full project manager. You can see a preview of the documentation for the new interface for a more expansive discussion of the scope #5605
