### ISSUE TITLE
Feature request: Implement `pip download`

### ISSUE THREAD

**Issue by zeevro** [astral-sh/uv#6006]
I would like to be able to download the resolved wheels/sdists without installing them.

**Comment by zanieb** [comment]
Please remember to check for existing issues, see https://github.com/astral-sh/uv/issues/3163

**Comment by zanieb** [comment]
If you have a specific use-case that's not described there, feel free to share

**Comment by zeevro** [comment]
> Please remember to check for existing issues, see #3163

I thought it was weird that no one asked for this before me, but I didn't find that one in my searches. My bad.

**Comment by zanieb** [comment]
Don't worry about it, GitHub Search is notoriously bad (I struggle to find things I know exist).
