### ISSUE TITLE
`uv pip install` fails when install from files with `-r`, but passes "regularly"

### ISSUE THREAD

**Issue by MarcoGorelli** [astral-sh/uv#6028]
Here's a minimal repro of what fails:

I have:
- `requirements-dev.txt`
  ```
  altair>=5.4.0
  ```
- `requirements-ci.txt`
  ```
  --extra-index-url https://download.pytorch.org/whl/cpu
  torch
  ```

Then:

✅ the following passes:
```
python3.11 -m venv .venv
. .venv/bin/activate
uv pip install altair --extra-index-url https://download.pytorch.org/whl/cpu torch
```

🔴 the following fails:
```
python3.11 -m venv .venv
. .venv/bin/activate
uv pip install -r requirements-dev.txt -r requirements-ci.txt
```

Output from the one that fails:
```
  × No solution found when resolving dependencies:
  ╰─▶ Because only typing-extensions{python_version < '3.13'}<4.10.0 is available and altair==5.4.0 depends on
      typing-extensions{python_version < '3.13'}>=4.10.0, we can conclude that altair==5.4.0 cannot be used.
      And because only altair<=5.4.0 is available and you require altair>=5.4.0, we can conclude that the requirements
      are unsatisfiable.
```

✅ the following also passes:
```
python3.11 -m venv .venv
. .venv/bin/activate
pip install -r requirements-dev.txt -r requirements-ci.txt
```

**Comment by zanieb** [comment]
```
uv pip install altair --extra-index-url https://download.pytorch.org/whl/cpu torch
```

This one probably passes because you're not including the `altair>=5.4.0`, just `altair` (and from the error, it's clear that's important)

```
pip install -r requirements-dev.txt -r requirements-ci.txt
```

This one probably passes because it's looking in multiple index URLs, you're probably looking for `--index-strategy unsafe-best-match`. See [the pip compatibility guide](https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#packages-that-exist-on-multiple-indexes) for details.

**Comment by MarcoGorelli** [comment]
Ah, thanks @zanieb ! https://download.pytorch.org/whl/typing-extensions/ only goes up to 4.9

So, installing `typing-extensions` separately and _before_ all the other requirements worked 🥳 
```
python3.11 -m venv .venv
. .venv/bin/activate
pip install -U uv
uv pip install typing-extensions>=4.10
uv pip install -r requirements-dev.txt -r requirements-ci.txt
```

**Comment by zanieb** [comment]
That'll do it too! Glad you found a solution.
