### ISSUE TITLE
Broken path parsing for install spec

### ISSUE THREAD

**Issue by flying-sheep** [astral-sh/uv#6032]
```console
$ uv --version
uv 0.2.35
$ uv pip install --editable '/home/phil/Dev/Python/Packaging, Docs/session-info2'
error: Failed to parse: `/home/phil/Dev/Python/Packaging, Docs/session-info2`
  Caused by: Expected path (`/home/phil/Dev/Python/Packaging,`) to end in a supported file extension: `.whl`, `.zip`, `.tar.gz`, `.tar.bz2`, `.tar.xz`, or `.tar.zst`
/home/phil/Dev/Python/Packaging, Docs/session-info2
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by zanieb** [comment]
Thanks!

cc @charliermarsh might a regression from #5888

**Comment by charliermarsh** [comment]
I can take a look.

**Comment by flying-sheep** [comment]
Ah, sorry, I should have said that there is also an error with older versions before that PR (e.g. 0.2.32)

The underlying issue of something splitting the path at the space is older.

**Comment by charliermarsh** [comment]
I think we currently require that you use a backslash here.

**Comment by charliermarsh** [comment]
(But of course it should work as-is.)

**Comment by flying-sheep** [comment]
I wasn’t aware that escape sequences in dependency specs are a thing at all!

**Comment by charliermarsh** [comment]
Yeah it's a bit tricky. Like this doesn't work:

```
-e /Users/crmarsh/workspace/uv/foo bar/black_editable
```

But it does work if you quote it, or pass it directly on the command-line etc.

**Comment by flying-sheep** [comment]
I am quoting it, see initial comment.

**Comment by charliermarsh** [comment]
Yeah I'm describing what the behavior _should_ be, not what we do today.

**Comment by flying-sheep** [comment]
I see! Thank you for clarifying!
