### ISSUE TITLE
uv 0.2.36 regression - `uv pip compile --universal` gives contradictory versions of same packages

### ISSUE THREAD

**Issue by notatallshaw-gts** [astral-sh/uv#6064]
uv 0.2.36 can give contradictory versions of the same package with the following command:
```
$ echo -e "pylint\ndill==0.3.1.1" | uv pip compile - --universal --python-version 3.11 --annotation-style line 2>/dev/null | grep "pylint=="
```

In uv 0.2.35 the output is:
```
pylint==2.15.8
```

In uv 0.2.36 the output is:
```
pylint==2.15.8
pylint==3.2.6
```

It seems `pylint==3.2.6` is not correctly filtered out as belonging to a Python version not compatible, if we switch `--python-version` to `3.10` we can see the markers that are applied when they are relevant:

```
$ echo -e "pylint\ndill==0.3.1.1" | uv pip compile - --universal --python-version 3.10 --annotation-style line 2>/dev/null | grep "pylint=="
pylint==2.15.8 ; python_version >= '3.11'
pylint==3.2.6 ; python_version < '3.11'
```

**Comment by zanieb** [comment]
Presuming this is 0.2.36?

**Comment by charliermarsh** [comment]
Thanks! I think this is related to #6059.

**Comment by notatallshaw-gts** [comment]
> Presuming this is 0.2.36?

Yeah, fixed post to correct typo

**Comment by charliermarsh** [comment]
Taking a look now.

**Comment by charliermarsh** [comment]
I think the problem here is:

- We end up solving an irrelevant fork (`python_version < 3.11`), because we don't test for `requires-python` disjointness.
- In the lockfile, we discard any markers that aren't relevant for the current Python version, so we throw out the markers from the irrelevant fork.

If you remove that block (e.g., the whole `petgraph.retain_edges(|graph, edge| !graph[edge].is_false())`) piece, the resolution is correct:

```
# This file was autogenerated by uv via the following command:
#    uv pip compile req.in --universal --python-version 3.11 -n
astroid==2.13.5 ; python_version >= '3.11'
    # via pylint
astroid==3.2.4 ; python_version < '3.11'
    # via pylint
colorama==0.4.6 ; sys_platform == 'win32'
    # via pylint
dill==0.3.1.1
    # via
    #   -r req.in
    #   pylint
isort==5.13.2
    # via pylint
lazy-object-proxy==1.10.0 ; python_version >= '3.11'
    # via astroid
mccabe==0.7.0
    # via pylint
platformdirs==4.2.2
    # via pylint
pylint==2.15.8 ; python_version >= '3.11'
    # via -r req.in
pylint==3.2.6 ; python_version < '3.11'
    # via -r req.in
tomlkit==0.13.0
    # via pylint
wrapt==1.16.0 ; python_version >= '3.11'
    # via astroid
```

**Comment by charliermarsh** [comment]
I think we should remove that block from `graph.rs`, and instead ensure that all the markers we see at that point have _already_ been simplified based on `requires-python`.
