### ISSUE TITLE
error: Failed to install cpython-3.12.4-macos-aarch64-none: Request failed after 3 retries

### ISSUE THREAD

**Issue by pdpark** [astral-sh/uv#6072]
Comand: `uv python install` 
Output: `error: Failed to install cpython-3.12.4-macos-aarch64-none: Request failed after 3 retries`

Re-ran command with verbose flag and got this output (three times):
```sh
DEBUG Transient request failure for https://github.com/indygreg/python-build-standalone/releases/download/20240726/cpython-3.12.4%2B20240726-aarch64-apple-darwin-install_only_stripped.tar.gz, retrying: error sending request for url (https://github.com/indygreg/python-build-standalone/releases/download/20240726/cpython-3.12.4%2B20240726-aarch64-apple-darwin-install_only_stripped.tar.gz)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
```

UV version: `uv 0.2.36 (Homebrew 2024-08-13)`
Platform: MacOS Sonoma 14.5 on M1 Pro Apple Silicon

Notes: Python version specified in `pyproject.toml`:
```toml
[project]
requires-python = ">=3.12"
```

**Comment by zanieb** [comment]
Hi! Do you have a proxy running? Are you using `UV_NATIVE_TLS`?

**Comment by pdpark** [comment]
Not using UV_NATIVE_TLS.

Looks like it may be a proxy issue, thanks.

Will have to fall back to pyenv for now. Thanks.

**Comment by zanieb** [comment]
I can only presume you are able to access GitHub normally? You can set `UV_NATIVE_TLS=true` or use the `--native-tls` flag if you need to use your system certificates with uv. We do not use the system certificate store by default, but I presume you're using a proxy with a certificate that is registered with your system.

**Comment by pdpark** [comment]
Just a suggestion since this may be an issue for others: instead of downloading pre-compiled versions of python you could build python locally like `pyenv` does. This zig project could make that a lot easier, I think (and, likely, faster): `https://github.com/allyourcodebase/cpython`. It would likely require significant contributions to mature that project to the point where it could act as a full replacement for `pyenv`, but it would be a great alternative.

**Comment by zanieb** [comment]
It's going to be _way_ slower to locally build optimized versions of Python — thats why we offer pre-built distributions. They're hosted on GitHub and you can use `UV_PYTHON_INSTALL_MIRROR` if you need to install them from a different host .

**Comment by pdpark** [comment]
Yep, of course, I meant faster than pyenv 😄.

Here's a great discussion about how pre-building Python wheels for PyPI (not exactly the same issue, but related...) is getting out of hand with the number of build targets exploding, and how the zig build system could be a better option: https://www.youtube.com/watch?v=i9nFvSpcCzo

Thanks for your help!

**Comment by zanieb** [comment]
No problem. Feel free to let us know if you have any more problems.

**Comment by pdpark** [comment]
> Hi! Do you have a proxy running? Are you using `UV_NATIVE_TLS`?

BTW I tried again this time using the `--native-tls` flag and it worked!

Interesting that it installed Python `3.12.4`, though. Python `3.12.5` is the latest version of `3.12`. It's only been out for about a week, so maybe it hasn't been compiled yet?

**Comment by charliermarsh** [comment]
Oh, thank I can add it. I'm annoyed, I thought I subscribed to release notifications!

**Comment by charliermarsh** [comment]
Adding here: https://github.com/indygreg/python-build-standalone/pull/299

**Comment by pdpark** [comment]
FYI: this issue (`uv python` not having 12.5 available) came up on the most recent episode of Python Bytes (they're big fans of UV): https://www.youtube.com/watch?v=0Sa0z2XXwwk

**Comment by Symbolk** [comment]
How did I resolve the issue by checking the uv-h: `uv venv openr1 --python 3.11 --native-tls --allow-insecure-host https://github.com`

**Comment by sjwyg** [comment]
I use pip install uv, and then execute "uv add requests" to add dependency, but it didn't work. like this:

uv add requests

Using CPython 3.12.4 interpreter at: C:\Users\g00026547\.conda\envs\py312\python.exe
Creating virtual environment at: .venv
⠋ uv-rumen==0.1.0                                                                                                                                                                                   
error: Failed to fetch: `https://pypi.tuna.tsinghua.edu.cn/simple/requests/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://pypi.tuna.tsinghua.edu.cn/simple/requests/)
  Caused by: client error (Connect)
  Caused by: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)
  Caused by: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)

**Comment by sjwyg** [comment]
and use chrome visit "https://pypi.tuna.tsinghua.edu.cn/simple/requests/" is successful, and use pip is also successful. 
only uv can't 

i think it's a problem about proxy, but i don't know how to resolve it

**Comment by Alphayellowcat** [comment]
> and use chrome visit "https://pypi.tuna.tsinghua.edu.cn/simple/requests/" is successful, and use pip is also successful. only uv can't
> 
> I think it's a problem about proxy, but I don't know how to resolve it

It should be a difference between the snapshot version and the official version, causing there to be no URL to fetch from.
