### ISSUE TITLE
Unable to install pyre2 with uv

### ISSUE THREAD

**Issue by sgrimee** [astral-sh/uv#6084]
Unable to install pyre2 with uv pip, it works with pip directly.

On mac, in a nix environment with python 3.12.4 and uv 0.1.45.
Using a venv created by uv.

Trying to install pyre2:
```
uv pip install pyre2==0.3.6          
Resolved 1 package in 2ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pyre2==0.3.6
  Caused by: Failed to build: `pyre2==0.3.6`
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
running build_ext
-- Configuring incomplete, errors occurred!
--- stderr:
CMake Error at CMakeLists.txt:3 (project):
  Running

   '/Users/sgrimee/Library/Caches/uv/.tmpRpC52h/.venv/bin/ninja' '--version'

  failed with:

   no such file or directory
```

It also fails if I first install:
```
uv pip install ninja setuptools wheel
Resolved 3 packages in 2ms
Installed 3 packages in 11ms
 + ninja==1.11.1.1
 + setuptools==72.2.0
 + wheel==0.44.0
```

**Comment by charliermarsh** [comment]
It looks like you might need `--no-build-isolation`?

**Comment by charliermarsh** [comment]
See: https://github.com/astral-sh/uv/blob/main/PIP_COMPATIBILITY.md#pep-517-build-isolation

**Comment by sgrimee** [comment]
Thanks for the response! So I try from a fresh venv, I install setuptools and ninja, then:
```
uv pip install --no-build-isolation  pyre2==0.3.6 
Resolved 1 package in 0.94ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pyre2==0.3.6
  Caused by: Failed to build: `pyre2==0.3.6`
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
running build_ext
-- Configuring incomplete, errors occurred!
--- stderr:
CMake Error at CMakeLists.txt:3 (project):
  Running

   '/Users/sgrimee/Library/Caches/uv/.tmpRpC52h/.venv/bin/ninja' '--version'

  failed with:

   no such file or directory
   ```

**Comment by charliermarsh** [comment]
Hmm, this works as expected for me:

```
❯ uv venv

❯ uv pip install setuptools ninja

❯ uv pip install --no-build-isolation  pyre2==0.3.6
Resolved 1 package in 1ms
   Built pyre2==0.3.6
Prepared 1 package in 3.23s
Installed 1 package in 0.64ms
 + pyre2==0.3.6
```

**Comment by sgrimee** [comment]
thanks for checking... are you on python 3.12?
I still see the error, and had a colleague test it to, but I see it only on 3.12.
With 3.9-11, I get [another error](https://github.com/facebook/pyre2/issues/24), I think not related, which I am trying to solve also by upgrading my c++ to v17.
Would you mind sharing your python version, as well as c++ version you are using?

**Comment by charliermarsh** [comment]
It actually worked as expected for me on Python 3.11 :(

**Comment by charliermarsh** [comment]
@sgrimee -- I just tested and it succeeds for me on both Python 3.11 and Python 3.12, unfortunately.

**Comment by charliermarsh** [comment]
Gonna close due to difficulty reproducing.

**Comment by vlcek** [comment]
Sorry for writing into an already closed issue, however, I hit the same problem with `pyre2` on Python 3.11 with uv 0.5.5.
I tried the `--no-build-isolation` with no success, however, once I nuked the uv's cache (`rm -rf ~/.cache/uv`) and run `uv sync` again, suddenly the `pyre2` build was successful.

Maybe this info will help anyone reading this issue.
