### ISSUE TITLE
Python 3.12.5 "No download found for request"

### ISSUE THREAD

**Issue by pdpark** [astral-sh/uv#6089]
I can see 3.12.5 builds in the latest [release](https://github.com/indygreg/python-build-standalone/releases/tag/20240814) but I am unable to install it:

```shell
uv python install --native-tls 3.12.5
warning: `uv python install` is experimental and may change without warning
Searching for Python versions matching: Python 3.12.5
error: No download found for request: cpython-3.12.5-macos-aarch64-none
```

**Comment by charliermarsh** [comment]
We bundle these with `uv`. They'll be available as of the next `uv` release.

**Comment by charliermarsh** [comment]
(Bundle the URLs, that is.)
