### ISSUE TITLE
Root unable to find uv.toml file

### ISSUE THREAD

**Issue by ryan-cpi** [astral-sh/uv#6144]
**Issue**

Running as the root user seems to be unable to find the uv.toml file.

**Steps to replicate**

1. docker run -it ubuntu:20.04 bash
2. update && upgrade
3. pip install uv
4. vim /root/.config/uv.toml
5. pip install private-package

**Output**

```
  root@7f40b5526c18:/# uv pip install core==3.4.6 --system --verbose
  DEBUG uv 0.2.37
  DEBUG Searching for Python interpreter in system path
  DEBUG Found `cpython-3.8.10-linux-x86_64-gnu` at `/usr/bin/python3` (search path)
  DEBUG Using Python 3.8.10 environment at usr/bin/python3
  DEBUG Acquired lock for `usr`
  DEBUG At least one requirement is not satisfied: core==3.4.6
  DEBUG Using request timeout of 30s
  DEBUG Solving with installed Python version: 3.8.10
  DEBUG Adding direct dependency: core==3.4.6
  DEBUG Found fresh response for: https://pypi.org/simple/core/
  DEBUG Searching for a compatible version of core(==3.4.6)
  DEBUG No compatible version found for: core
    x No solution found when resolving dependencies:
    `-> Because there is no version of core==3.4.6 and you require core==3.4.6, we can conclude that your requirements are unsatisfiable.

root@7f40b5526c18:/# cat /root/.config/uv.toml 
[pip]
index-url = "https://__token__:glpat-xxx@gitlab.com/api/v4/groups/123/-/packages/pypi/simple"
```

**Expected outcome**

Setting `--config-file /root/.config/uv.toml` fixes the issue for me but it should be able to find the config without this needing to be explicitly set.

**Versions**

**UV Version:** uv 0.2.37
**OS:** Docker ubuntu:20.04

**Comment by charliermarsh** [comment]
I think it's `/root/.config/uv/uv.toml`.

**Comment by zanieb** [comment]
Fooled me.. I was debugging this :D

**Comment by ryan-cpi** [comment]
Ah i see. Thanks.  I'm used to it being only one file off the home for pip. Sorry 
~/.pip/pip.conf vs ~/.conf/uv/uv.toml

**Comment by charliermarsh** [comment]
No prob. I wonder if we should warn or something here.

**Comment by ryan-cpi** [comment]
The docs are pretty clear but a debug line in the --verbose might be nice
