### ISSUE TITLE
Ignore forks that use a Python version above the `requires-python` upper-bound

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6150]
We generally ignore upper-bounds on `requires-python` for dependencies, for a variety of reasons. However, we _could_ ignore forks that are above the upper-bound of the _user's_ `requires-python`.

See: https://github.com/astral-sh/uv/issues/5818

**Comment by zanieb** [comment]
Linking to previous discussion https://github.com/astral-sh/uv/issues/4022
