### ISSUE TITLE
uv misinterprets `python_version in "2.6 2.7 3.2 3.3"` marker

### ISSUE THREAD

**Issue by sbidoul** [astral-sh/uv#6168]
It seems uv 0.2.37 misinterprets this marker:  `python_version in "2.6 2.7 3.2 3.3"`.

How to reproduce:

`uv pip install pickleshare` installs `pathlib2`, which is declared as `Requires-Dist: pathlib2; python_version in "2.6 2.7 3.2 3.3"` in the `pickleshare` wheel METADATA.

**Comment by charliermarsh** [comment]
Yeah this is known. We should fix it. There’s another issue somewhere.

**Comment by zanieb** [comment]
See https://github.com/astral-sh/uv/issues/3683
