### ISSUE TITLE
`uv venv --preview` now requires `[project]` table

### ISSUE THREAD

**Issue by branchvincent** [astral-sh/uv#6177]
Thanks for all your amazing work on `uv` and `ruff` :)

I noticed after https://github.com/astral-sh/uv/commit/0dcec9eba8fff90c7863451f6435de594c9c9624, `uv venv` now accidentally requires a `[project]` table if `pyproject.toml` exists:

```shell
$ cd "$(mktemp -d)"
$ touch pyproject.toml
$ uv venv --preview
× No `project` table found in: `$TMPDIR/tmp.t05D1l2KEK/pyproject.toml`
```

Of course, projects may have a `pyproject.toml` without having yet adopted PEP 621 (like https://github.com/pypa/trove-classifiers)

**Comment by zanieb** [comment]
Thanks for the report! We definitely shouldn't fail here.

Blocks #6166
