### ISSUE TITLE
Allow users to constrain universal locks to specific markers

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6184]
I think we should let users apply a global marker constraint to "universal" resolution. E.g., maybe you don't care about locking on Windows, so you specify `platform_system != 'Windows'` in your `pyproject.toml`, and we avoid solving any branches that are Windows-only. Later, when installing, we'd error if the user is on an unsupported platform, based on those markers.

This would (1) make resolution a lot faster for users that only care about certain platforms, (2) enable us to solve locks that legitimately don't have solutions on certain platforms.

This would also solve https://github.com/astral-sh/uv/issues/4087.

**Comment by zanieb** [comment]
I like it.

**Comment by BurntSushi** [comment]
I like this a lot. I feel like it's a good release valve.
