### ISSUE TITLE
`uv pip` inconsistencies with win32 platform

### ISSUE THREAD

**Issue by schlamar** [astral-sh/uv#6245]
Follow up of #6198

Right now, you can install Python packages with win32 platform tag when running uv from a 32bit Python interpreter.

However, you cannot target win32 platform from uv running in a 64bit Python interpreter, as there is no corresponding target triple in uv. Please add a target triple for Python's win32 platform tag.

Generally, I wonder why win32 isn't an officially supported platform as it is in [Python](https://peps.python.org/pep-0011/#tier-1) **and** [Rust](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools) tier 1 list?

**Comment by charliermarsh** [comment]
We can add this!
