### ISSUE TITLE
Allow flags in `uv run`'s  `--with` values

### ISSUE THREAD

**Issue by mgaitan** [astral-sh/uv#6254]
In a Makefile, I run something like this (where `app_dir` is an argument):

```
uv run --isolated --with-requirements $(app_dir)/requirements/requirements-test.txt pytest $(app_dir)/tests
```

I also need to install `-e .` to make a few other packages in my monorepo available for the app. For legacy reasons, I can't add that as part of `requirements-test.txt`, so I would like to install it ad hoc in the `uv run` call.

I expected this to work:

```
uv run --isolated --with "-e ." --with-requirements $(app_dir)/requirements/requirements-test.txt pytest $(app_dir)/tests
```

but it fails like this:

```
error: Failed to parse: `-e .`
  Caused by: Expected package name starting with an alphanumeric character, found '-'
-e .
^
```

The workaround I found is this:

```
echo "-e ." >> /tmp/local.txt
uv run --isolated --with-requirements /tmp/local.txt --with-requirements $(app_dir)/requirements/requirements-test.txt pytest -vv $(app_dir)/tests
```

So, could `--with` be more flexible and accept flags? Actually, with this change, `--with-requirements` would be equivalent to `--with "-r <file>"`.

**Comment by mgaitan** [comment]
well that would work but isn't too inefficient? I have several fairly large packages in the monorepo that would be installed  by copying to an isolated virtualenv every time I run my tests, right?

**Comment by zanieb** [comment]
It'd be good to have a concrete demonstration of it being inefficient, but yeah in theory an editable install would be faster.

**Comment by charliermarsh** [comment]
I'm not too opposed to supporting editables here, though I'd also prefer `--with-editable`.

**Comment by mgaitan** [comment]
`--with-editable` works for me
