### ISSUE TITLE
`uv add -r requirements.txt` should translate to `tool.uv.sources` where applicable

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6276]
See https://github.com/astral-sh/uv/issues/6275#issuecomment-2299785710

**Comment by charliermarsh** [comment]
I can take this.

**Comment by charliermarsh** [comment]
But I won't get to it until a little later, so I'll un-assign in case anyone is eager.

**Comment by Mrt3383x38** [comment]
Trasfer
