### ISSUE TITLE
Add a `uv publish` command

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6278]
e.g., to publish the project to PyPI.

This is a pretty large, but well isolated project — if you've contributed previously and are interested in working on it let me know.

**Comment by pplmx** [comment]
Add `uv build` and `uv test` too?

**Comment by zanieb** [comment]
Those are both out of scope for this issue — though `uv build` should be trivial once `uv publish` is set up.

**Comment by woodruffw** [comment]
Hi all! I'm neither a maintainer of PyPI nor `twine`, but I'm an active contributor to both who has touched a lot of the components related to uploading/API tokens/etc. It's very exciting to see `uv` consider adding publishing support!

A couple of things that might be worth considering as part of an implementation here:

* PyPI and TestPyPI both support [trusted publishing](https://docs.pypi.org/trusted-publishers/), i.e. credentialless package publishing via OIDC. This is handled transparently at the API token issuance layer to avoid any changes to PyPI's authentication parameters, but a future `uv publish` command could avoid the need for a separate token exchange step by performing the token exchange internally.
* PyPI and TestPyPI are nearing the completion of initial support for [PEP 740](https://peps.python.org/pep-0740/), i.e. index support for digital attestations over packages. `twine` has support for detecting and uploading attestations; a future `uv publish` command could consider adding support as well 🙂 

I'm happy to provide more details on the above or anything else related to publishing, to those interested. Just let me know!

**Comment by andrlik** [comment]
Adding this comment to the correct issue. 🤦 

Would be good to mimic the `rye publish` command where it prompts you to encrypt your PyPI token with a password.

**Comment by juan-abia** [comment]
Related @konstin:
https://github.com/astral-sh/uv/issues/8221
