### ISSUE TITLE
Question about system Python-created venv and uv-created venv

### ISSUE THREAD

**Issue by nth10sd** [astral-sh/uv#6282]
I just have a question. For 2 scenarios:

1) Download `uv` via Astral's script, have `uv` create a CUSTOMENV, activate the CUSTOMENV, install lockfile using `uv` via `uv pip sync --no-break-system-packages --strict --verify-hashes requirements.txt`
2) Using `venv` from the official system Python, run `python3 -u -m venv --upgrade-deps CUSTOMENV`, activate CUSTOMENV, run `pip` inside the CUSTOMENV to install `uv`, install lockfile using `uv` via `uv pip sync --no-break-system-packages --strict --verify-hashes requirements.txt`

Will I end up with virtually identical `venv`s?

i.e. Is a `venv` created by `uv`, any different from a `venv` created by system Python, then having `uv` installed?

**Comment by zanieb** [comment]
Yes, these should be roughly identical. The environment will have metadata indicating the tool that created it, e.g. `uv = 0.3.0` in the `pyvenv.cfg`.
