### ISSUE TITLE
`uv run` ignores `.python-version`

### ISSUE THREAD

**Issue by ketozhang** [astral-sh/uv#6285]
When there exists `.python-version` file (e.g., created by `uv python pin`), creating a virtual environment with UV does not create the correct version? I'm not sure if this behavior is intended.

```
/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.Fv2SE2ebMR
.venv ❯ uv python pin 3.11.9
Pinned `.python-version` to `3.11.9`

/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.Fv2SE2ebMR
.venv ❯ uv run python --version
Python 3.12.4

/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.Fv2SE2ebMR
.venv ❯ uv run python -m site
sys.path = [
    '/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.Fv2SE2ebMR',
    '/Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/lib/python312.zip',
    '/Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/lib/python3.12',
    '/Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/lib/python3.12/lib-dynload',
    '/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.cVJnZhhRMn/.venv/lib/python3.12/site-packages',
]
USER_BASE: '/Users/keto/.local' (exists)
USER_SITE: '/Users/keto/.local/lib/python3.12/site-packages' (exists)
ENABLE_USER_SITE: False
```

**Comment by charliermarsh** [comment]
Interesting ,this worked as expected for me:

```
❯ uv python pin 3.11.9
warning: No interpreter found for Python 3.11.9 in managed installations or system path
Updated `.python-version` from `3.12.1` -> `3.11.9`

❯ cat .python-version
3.11.9

❯ uv venv
Using Python 3.11.9
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate

❯ uv run python --version
Python 3.11.9
```

Was there maybe an existing `.venv` in the directory already?

**Comment by zanieb** [comment]
If there was an existing `.venv`, we should probably warn if it doesn't match the pinned version (I don't think we should delete it though).

**Comment by ketozhang** [comment]
That's right, I pasted the wrong output. Making sure no venv was activate, I'm still getting the same issue.

```console
❯ uv python pin 3.11.9
Pinned `.python-version` to `3.11.9`

❯ uv run python --version
Python 3.12.4

❯ python
zsh: command not found: python

❯ echo $VIRTUAL_ENV
```

```
❯ uv --version
uv 0.3.0 (Homebrew 2024-08-20)
```

**Comment by zanieb** [comment]
If there's a `.venv` in a parent directory we might be finding that. Can you include the output of `RUST_LOG=uv=trace uv run -v python --version`?

**Comment by ketozhang** [comment]
I was missing explicitly calling `uv venv` 🤦 . I assumed `uv run python` would have created the venv automatically for me. This works.

---

Rust logs when skipping `uv venv`

```console
/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.H7u3XUwsC0
❯ uv python pin 3.11.9
Pinned `.python-version` to `3.11.9`

/private/var/folders/dh/q65wqsbs3tn0993nc2j5dzy00000gn/T/tmp.H7u3XUwsC0
❯ RUST_LOG=uv=trace uv run -v python --version
DEBUG uv 0.3.0 (Homebrew 2024-08-20)
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python interpreter in managed installations or system path
DEBUG Searching for managed installations at `/Users/keto/Library/Application Support/uv/python`
DEBUG Found managed installation `cpython-3.12.4-macos-x86_64-none`
TRACE Cached interpreter info for Python 3.12.4, skipping probing: /Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/bin/python3
DEBUG Found `cpython-3.12.4-macos-x86_64-none` at `/Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/bin/python3` (managed installations)
DEBUG Using Python 3.12.4 interpreter at: /Users/keto/Library/Application Support/uv/python/cpython-3.12.4-macos-x86_64-none/bin/python3
DEBUG Running `python --version`
Python 3.12.4
```

**Comment by charliermarsh** [comment]
I feel like `uv run` should be respecting `.python-version` there 🤔 But I'll let Zanie chime in.

**Comment by charliermarsh** [comment]
`uv run` _will_ create a virtual environment for you if it's executed within a project directory!

**Comment by denkasyanov** [comment]
I just noticed similar behaviour on `uv 0.2.35 (e097f948c 2024-08-09)` WITH running `uv venv`

Fixed by upgrading to 0.3.0. So maybe this can help someone still on the old version.

Speaking about upgrading, pnpm bugs me about its new versions. Didn't like it in the beginning, but probably it will help to prevent creating duplicate/solved GH issues, because I was _almost_ ready to create a new issue, if I didn't find this one right at the top. I would definitely enable it.

For reference pnpm does it like that
![pnpm available update notification](https://user-images.githubusercontent.com/60206592/202073002-fcc4351b-2a66-49ab-a894-c16400ac116a.png)

**Comment by zanieb** [comment]
I'll look into some improvements in this area.

**Comment by ketozhang** [comment]
@denkasyanov That is probably what I saw today. I did upgrade to 0.3.0.

I've already changed the title :/ . I'll let folks here decide if another issue is warranted for `<0.3`

**Comment by TylerHillery** [comment]
I ran into similar issues, do I have to create a venv for `uv run` to respect the `.python-version`? This is not in a project directory?


```
sandbox/uv-test
➜ ls -la
total 16
drwxr-xr-x@  4 tyler  staff  128 Aug 21 07:28 .
drwxr-xr-x  27 tyler  staff  864 Aug 21 07:27 ..
-rw-r--r--@  1 tyler  staff    4 Aug 21 07:27 .python-version
-rw-r--r--@  1 tyler  staff   31 Aug 21 07:28 main.py
sandbox/uv-test
➜ cat .python-version
3.9
sandbox/uv-test
➜ RUST_LOG=uv=trace uv run -v python --version
DEBUG uv 0.3.0
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python interpreter in managed installations or system path
DEBUG Searching for managed installations at `/Users/tyler/.local/share/uv/python`
DEBUG Found managed installation `cpython-3.12.5-macos-aarch64-none`
TRACE Cached interpreter info for Python 3.12.5, skipping probing: /Users/tyler/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/bin/python3
DEBUG Found `cpython-3.12.5-macos-aarch64-none` at `/Users/tyler/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/bin/python3` (managed installations)
DEBUG Using Python 3.12.5 interpreter at: /Users/tyler/.local/share/uv/python/cpython-3.12.5-macos-aarch64-none/bin/python3
DEBUG Running `python --version`
Python 3.12.5
```

**Comment by zanieb** [comment]
Related https://github.com/astral-sh/uv/issues/5839

I think we just don't think we need to create a virtual environment so we don't ever check if the interpreter is correct.

**Comment by chrisrodrigue** [comment]
Is a `.python-version` file necessary when the pinned python version for a project can be obtained from `project.requires-python` in `pyproject.toml`?

**Comment by zanieb** [comment]
We don't recommend using `project.requires-python` for pins, it's "supposed" to be for listing the supported versions. You can use it instead of `.python-version` if you want — we'll use the first interpreter that satisfies the constraints in `project.requires-python` whether a pin or a range.
