### ISSUE TITLE
FR: A way to set the minimum python version for a virtual workspace

### ISSUE THREAD

**Issue by ilyagr** [astral-sh/uv#6289]
I set up a virtual workspace to run MkDocs as discussed [here](https://github.com/astral-sh/rye/discussions/1342#discussioncomment-10401062); the config is the same is in #6288 (which I worked around by not running `uv lock`).

A minor annoyance is that `uv lock` sets `requires-python = ">=3.12"` in `uv.lock`, and there is no way to decrease this requirement AFAICT. `uv` seems to only accept a field for the minimum Python version in *packages*, and there are none in my config.

Perhaps the `[tool.uv.workspace]` section in `pyproject.toml` should support setting a minimum python version, or there should be a way to have a "virtual project" that has dev-dependencies and sets a minimum Python version instead of having to create a weird empty workspace to put dev-dependencies in its root.

**Update:** Ah, looking at #6285, maybe I'm supposed to have a `.python-version`... OTOH, judging by that bug, it may or may not work.

**Comment by charliermarsh** [comment]
Yeah this is an awkward spot right now. The best you can do at present is a `.python-version`.

**Comment by charliermarsh** [comment]
This is now solved by using a virtual package. You can add `[project]` with a Python version to what was previously a virtual workspace root.

**Comment by ilyagr** [comment]
Thank you!
