### ISSUE TITLE
FR: Add support for `uv tool upgrade --python <PYTHON>`

### ISSUE THREAD

**Issue by weihenglim** [astral-sh/uv#6297]
It would be useful to have a way to reinstall/upgrade all installed tools to the latest Python version. 

Currently we are able to reinstall all tools via `uv tool upgrade --all --reinstall` but are unable to specify the Python version. The workaround is to perform `uv tool install --python <PYTHON> <PACKAGE>` for all tools individually. 

As an aside, it would also be nice if `uv tool list` displays the Python version that was used to install the tool (similar to how `pipx list` behaves)

**Comment by zanieb** [comment]
Upgrading Python versions makes a lot of sense.

Why is the version important for you to see in `uv tool list`? Aren't most tools Python version agnostic?
