### ISSUE TITLE
feature: support poetry version/pdm bump support

### ISSUE THREAD

**Issue by toppk** [astral-sh/uv#6311]
It would be nice if `uv` had native capability to update version information in pyproject.toml.

Both pdm and poetry have this capability, here are the links
https://python-poetry.org/docs/cli/#version 
https://github.com/carstencodes/pdm-bump

The pdm support is through a 3rd party pdm plugin.

for example:
```sh
pdm bump micro # creates 0.1.2 from 0.1.1
poetry version patch # creates 0.1.2 from 0.1.1
```

**Comment by zanieb** [comment]
Duplicate of https://github.com/astral-sh/uv/issues/6311
