### ISSUE TITLE
uv init reads stray `pyproject.toml` even with --no-config

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#6320]
See the following reproducer with uv 0.3.0.

There's an empty pyproject.toml file there. It blocks creating a new project below it, because the empty file is not valid.

```shell
mkdir /tmp/newroot
cd /tmp/newroot
touch pyproject.toml
uv init --no-config newproject
```

Actual output
```
error: No `project` table found in: `/tmp/newroot`
```

Same result when adding `--no-workspace`.

**Comment by charliermarsh** [comment]
Yeah this looks wrong.
