### ISSUE TITLE
Question: Where is `ruff` located when running `uvx ruff`?

### ISSUE THREAD

**Issue by pplmx** [astral-sh/uv#6325]
As title

**Comment by charliermarsh** [comment]
Good question. We create a content-addressed, ephemeral virtual environment in the cache.

You can run `uv cache dir` to find the cache:

```
❯ uv cache dir
/Users/crmarsh/.cache/uv
```

Then on my machine, it ends up at:

```
/Users/crmarsh/.cache/uv/environments-v1/409d7d054e15cc1d/23519598101eb3f1/bin/ruff
```

**Comment by charliermarsh** [comment]
If you install Ruff with `uv tool install ruff`, then `uvx ruff` will use _that_ binary by default (you can disable this with `uvx --isolated ruff`).

If you use `uv tool install ruff`, you can find the final binary directory with:

```
❯ uv tool dir --bin
/Users/crmarsh/.local/bin
```

**Comment by pplmx** [comment]
Thank you for your prompt response! I understand. :)  
I also noticed that if I run `uvx <package>` first and then run `uv install <package>`, the process is much quicker. It uses the cache, correct?

**Comment by charliermarsh** [comment]
Yeah they both use the same cached uv binary, and reflink or hardlink it into the appropriate places :) So there's no duplication either way (unless, e.g., you do something like `uvx ruff@0.6.0` and then `uv install ruff==0.5.0`, since we then need to install two different versions).

**Comment by baggiponte** [comment]
Uhm, I just noticed that if I run `uv cache dir` I get:

```zsh
$ uv cache dir
/Users/luca/Library/Caches/uv
```

even though I have XDG vars set 😱

**Comment by charliermarsh** [comment]
(If you run `uv cache clean`, we'll create any subsequent cache under XDG. We keep reading from `/Users/luca/Library/Caches/uv` if it exists for backwards compatibility.)
