### ISSUE TITLE
uv python install doesn't put artifacts in configured cache dir

### ISSUE THREAD

**Issue by MattiasDC** [astral-sh/uv#6327]
We have the environment variable `UV_CACHE_DIR` in combination with cache sharing across users. It seems that when a python version is downloaded, it doesn't end up in the cache dir. Resulting in each user downloading the python version separately.

I'm assuming this isn't intended behavior as `uv python install --help` does include the 'Cache options' section

**Comment by baggiponte** [comment]
You can also see the dir running `uv python dir` :)

**Comment by charliermarsh** [comment]
It's documented here: https://docs.astral.sh/uv/configuration/environment/
