### ISSUE TITLE
Handle Ctrl-C properly in `uvx`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6334]
As we do in `uv run`

**Comment by charliermarsh** [comment]
The setup is identical for both commands, I think...? What are you seeing.

**Comment by zanieb** [comment]
Oh. Mentioned at https://github.com/astral-sh/uv/issues/6329#issuecomment-2302211339 cc @bluss

**Comment by charliermarsh** [comment]
Thanks I'll check it out. Maybe has to do with the wrapper? Not sure yet.

**Comment by bluss** [comment]
> Thanks I'll check it out. Maybe has to do with the wrapper? Not sure yet.

That's a surprise, but it's the case, the problem is for uvx and not uv tool run.

**Comment by zanieb** [comment]
Oh, we invoke `uv tool run` as a subprocess in `uvx`. We'll need to be more sophisticated there.

**Comment by charliermarsh** [comment]
👍 👍

**Comment by prrao87** [comment]
Hang on, is `uvx` fundamentally different from `uv tool run` in the sense that it's invoked as a subprocess?
The docs page here seems to indicate that it's simply an alias:
https://docs.astral.sh/uv/guides/tools/#running-tools

**Comment by charliermarsh** [comment]
They're meant to be entirely equivalent. It's an "alias" but it's not literally a bash alias (since we don't have a way to "install" alias), it's a tiny wrapper script that just forwards on to `uv tool run`.

**Comment by charliermarsh** [comment]
Any perceptible or behavioral difference between `uvx` and `uv tool run` should be considered a bug.

**Comment by charliermarsh** [comment]
(...like this one :joy:)

**Comment by zanieb** [comment]
@prrao87 I'm a bit confused, I don't think we switch to `uv tool run`, we switch to `uv tool install` which is different.

**Comment by charliermarsh** [comment]
Closed by #6346.

**Comment by prrao87** [comment]
@zanieb I now understand it much better. Thanks for clarifying!
