### ISSUE TITLE
uv seems not to respect custom virtual env when installing a dependency

### ISSUE THREAD

**Issue by FilipLangr** [astral-sh/uv#6339]
It seems like `uv` does not respect custom virtual env.

my `uv` version is `0.3.0` running on Ubuntu 24.04

code to reproduce:
```bash
mkdir project_test
cd project_test
uv init
uv venv custom # creates ./custom folder
source custom/bin/activate
echo $VIRTUAL_ENV # prints the path to ./custom folder
uv add numpy --verbose
```
the last command prints (among others):
```
DEBUG Ignoring Python interpreter at `/.../project_test/custom/bin/python3`: system interpreter required
```
which I don't really understand why. It also creates a new virtualenv `.venv`, where it installs numpy. However, I would expect it to install it to `custom`. Is this a bug or feature? If feature, how to come around it and make `uv` to use `custom` venv? Thank you!

**Comment by zanieb** [comment]
Hi!

Thanks for the nice reproduction. We don't support reading `VIRTUAL_ENV` in the project APIs. See https://github.com/astral-sh/uv/issues/5229 for the feature request.

**Comment by FilipLangr** [comment]
> Hi!
> 
> Thanks for the nice reproduction. We don't support reading `VIRTUAL_ENV` in the project APIs. See #5229 for the feature request.

Ah my bad, didn't notice that one. Thank you for such a swift response!

**Comment by zanieb** [comment]
You're welcome!
