### ISSUE TITLE
Incorrect update all tools command in blog post

### ISSUE THREAD

**Issue by denkasyanov** [astral-sh/uv#6342]
### Issue 

According to blog post https://astral.sh/blog/uv-unified-python-packaging:

> `uv tool upgrade` to upgrade all installed tools to their latest supported versions.

According to [docs](https://docs.astral.sh/uv/guides/tools/#upgrading-tools) it is `uv tool upgrade --all`

I couldn't find a repo for blog posts to make a PR, so leaving it here

### Proposed solution

Looks like

"or `uv tool upgrade` to upgrade all installed tools to their latest supported versions."

should be

"or `uv tool upgrade --all` to upgrade all installed tools to their latest supported versions." in the [blog post](https://astral.sh/blog/uv-unified-python-packaging)

### Motivation

Maybe some people like me are more comfortable to follow along the blog post than docs. This change will align it with docs.

Confirmed to work according to the docs on version `uv 0.3.0 (dd1934c9c 2024-08-20)`

**Comment by charliermarsh** [comment]
Ah thanks, that makes sense.

**Comment by charliermarsh** [comment]
(Just pushed a fix, should deploy shortly.)
