### ISSUE TITLE
Some tools are installed without pkg_resources

### ISSUE THREAD

**Issue by acdha** [astral-sh/uv#6384]
Using `uv 0.3.0 (Homebrew 2024-08-20)` on macOS, I noticed that some packages are failing on a missing `pkg_resources` dependency. At first I thought this was the Python 3.12 deprecation but it's an issue with older version, too. This is package-specific and most things are not affected but I haven't looked into the common factor.

```fish
cadams@HOST ~> uv tool install -p 3.10 shodan
Resolved 13 packages in 5ms
Installed 13 packages in 10ms
 + certifi==2024.7.4
 + charset-normalizer==3.3.2
 + click==8.1.7
 + click-plugins==1.1.1
 + colorama==0.4.6
 + filelock==3.15.4
 + idna==3.7
 + requests==2.32.3
 + requests-file==2.1.0
 + shodan==1.31.0
 + tldextract==5.1.2
 + urllib3==2.2.2
 + xlsxwriter==3.2.0
Installed 1 executable: shodan
cadams@HOST ~> shodan scan list
Traceback (most recent call last):
  File "/Users/cadams/.local/bin/shodan", line 5, in <module>
    from shodan.__main__ import main
  File "/Users/cadams/.local/share/uv/tools/shodan/lib/python3.10/site-packages/shodan/__main__.py", line 33, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

This might also suggest that the equivalent of a `pipx inject` command would be useful for adding optional dependencies.

**Comment by charliermarsh** [comment]
I have good news... I believe this is already supported via `--with`:

```
❯ uv tool install -p 3.10 shodan --with setuptools
Resolved 14 packages in 5ms
Installed 1 package in 9ms
 + setuptools==73.0.1
Installed 1 executable: shodan

❯ shodan scan list
Error: Please run "shodan init <api key>" before using this command
```

**Comment by charliermarsh** [comment]
(Took me a second to realize that `pkg_resources` is distributed as part of `setuptools`, not a standalone package.)

**Comment by acdha** [comment]
Ah, I missed that in the docs. I found it interesting that it was just like the 3.12 breaking change on older versions but that’s something we all need to update anyway as part of 3.12 support.

**Comment by AzizNadirov** [comment]
I have some issue with uv `0.5.2`. My pyproject:
```toml
[project]
name = "tmp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-common>=1.1.28",
    "azure-core>=1.32.0",
    "azure-identity>=1.19.0",
    "azure-mgmt-authorization>=4.0.0",
    "azure-mgmt-core>=1.5.0",
    "azure-mgmt-resource>=23.2.0",
    "azure-mgmt-storage>=22.0.0",
    "azureml-dataprep>=5.1.6",
    "azureml-fsspec>=1.3.1",
    "azureml-pipeline>=1.59.0",
    "azureml-pipeline-core>=1.59.0",
    "azureml-pipeline-steps>=1.59.0",
    "fastparquet>=2024.11.0",
    "openpyxl>=3.1.5",
    "pandas>=2.1.0",
    "pyarrow>=19.0.0",
    "python-dotenv>=1.0.1",
]
```
And it gives 
```
Traceback (most recent call last):
  File "/home/tengo/Documents/tmp/build.py", line 4, in <module>
    from azureml.pipeline.steps import PythonScriptStep
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/pipeline/steps/__init__.py", line 25, in <module>
    from .adla_step import AdlaStep
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/pipeline/steps/adla_step.py", line 5, in <module>
    from azureml.pipeline.core._adla_step_base import _AdlaStepBase
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/pipeline/core/__init__.py", line 24, in <module>
    from .builder import PipelineStep, PipelineData, StepSequence
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/pipeline/core/builder.py", line 12, in <module>
    from azureml.data._dataset import _Dataset
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/data/__init__.py", line 31, in <module>
    from .tabular_dataset import TabularDataset
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/data/tabular_dataset.py", line 20, in <module>
    from azureml.data.dataset_error_handling import _validate_has_data, _validate_has_columns, _try_execute
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/data/dataset_error_handling.py", line 9, in <module>
    from azureml.exceptions import UserErrorException
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/exceptions/__init__.py", line 24, in <module>
    from azureml._restclient.exceptions import ServiceException
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/_restclient/__init__.py", line 11, in <module>
    from .models_client import ModelsClient
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/_restclient/models_client.py", line 11, in <module>
    from azureml._model_management._util import populate_model_not_found_details
  File "/home/tengo/Documents/tmp/.venv/lib/python3.11/site-packages/azureml/_model_management/_util.py", line 41, in <module>
    from pkg_resources import resource_string
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by zanieb** [comment]
@AzizNadirov just add `setuptools` to your dependencies — some packages just assume that it is available.

Please see #9452 regarding reporting issues.

**Comment by dwiandhikaap** [comment]
for anyone still facing this issue after adding `setuptools`, try installing version `setuptools==80.8.0` or older

**Comment by bergamonster** [comment]
> for anyone still facing this issue after adding `setuptools`, try installing version `setuptools==80.8.0` or older

This didn't work for me (I've tried a variety of version <82 as well as some different pip versions given I've seen mentions of that in other issues)

I've also attempted installing setuptools on a fresh venv before installing any requirements, and that didn't work either

**Comment by DanCInOz** [comment]
> > for anyone still facing this issue after adding `setuptools`, try installing version `setuptools==80.8.0` or older
> 
> This didn't work for me (I've tried a variety of version <82 as well as some different pip versions given I've seen mentions of that in other issues)
> 
> I've also attempted installing setuptools on a fresh venv before installing any requirements, and that didn't work either

I've tried all of that and it's also failing for me.    In my case it's a downstream dependency.
Strangely, I don't seem to have any issues on my workstation but trying to setup a uv python env in a github workflow - I just cannot get it to work.

I can't even understand what changed in the last few weeks to make this a problem all of a sudden - non of my code changed, my uv version was pegged.    Perhaps the wheel version of the downstream dependent package is not available suddenly causing it to be built from source..

**Comment by noreplydev** [comment]
> > for anyone still facing this issue after adding `setuptools`, try installing version `setuptools==80.8.0` or older
> 
> This didn't work for me (I've tried a variety of version <82 as well as some different pip versions given I've seen mentions of that in other issues)
> 
> I've also attempted installing setuptools on a fresh venv before installing any requirements, and that didn't work either
Same here, has anyone figure it out?

**Comment by bergamonster** [comment]
> > > for anyone still facing this issue after adding `setuptools`, try installing version `setuptools==80.8.0` or older
> > 
> > 
> > This didn't work for me (I've tried a variety of version <82 as well as some different pip versions given I've seen mentions of that in other issues)
> > I've also attempted installing setuptools on a fresh venv before installing any requirements, and that didn't work either
>  Same here, has anyone figure it out?

I tried a lot, but I think what ended up getting me past it was setting extra build dependencies (pandas install was where it was erroring for me)
```
[tool.uv.extra-build-dependencies]
pandas = ["setuptools==80.10.2"]
```
(along with pinning setuptools==80.10.2 and pip==25.2 in the project dependencies, though not positive that was necessary)

**Comment by indirect** [comment]
If you run something that depends on pkg_resources with setuptools 80.10.2, this warning prints out:

>UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
>   from pkg_resources import get_distribution, DistributionNotFound

As expected from that warning, it is only possible to run software that needs pkg_resources if you tell `uv` to use a version of `setuptools` that is older than `81`. This worked for me:

```
uv run --with setuptools==80.10.2 COMMAND
```

**Comment by konstin** [comment]
Consider settings [constraint-dependencies](https://docs.astral.sh/uv/reference/settings/#constraint-dependencies) for making this permanent in your project.

**Comment by KranzAklilu** [comment]
For anyone still struggling, try reinstalling your system setuptools. 
`sudo dnf reinstall python-setuptools`
