### ISSUE TITLE
`uv venv` with `pyproject.toml` or `uv.toml`

### ISSUE THREAD

**Issue by jonzamora** [astral-sh/uv#6387]
Hello,

I'm transitioning from using `mamba` to `uv` for my Python projects, and am hoping I could get some help with the following "setup" process for my projects.

Previously, with mamba, I could define the following installation procedure:

```bash
mamba env create -f environment.yaml
mamba activate my_env
pip install -e .
```

and this procedure would install project dependencies (with mamba) + my local python project (with pip).

**The Part Where I Need Help**

I'd like to run a command like `uv venv --config-file pyproject.toml` which installs all dependencies for the [project] and "just works" after I activate the environment.

However, when I try this, I get the following error:

```bash
warning: The `--config-file` argument expects to receive a `uv.toml` file, not a `pyproject.toml`. If you're trying to run a command from another project, use the `--directory` argument instead.
```

Does this mean the only way I can create a `venv` with `uv` which refers to my `pyproject.toml` is by creating a `uv.toml` file?

**Comment by charliermarsh** [comment]
You might be looking for `uv sync`, which will: lock the project dependencies, create a virtual environment, and install them (plus your project) into that environment, all from a `pyproject.toml` in that directory.

**Comment by jonzamora** [comment]
This worked like magic, thanks so much Charlie! Congrats on all the hard work and success 😄
