### ISSUE TITLE
uv init command got an error on windows

### ISSUE THREAD

**Issue by joe-cho** [astral-sh/uv#6393]
# Symptom
Whenever running ```uv init my-project```,  I am getting the same error:

```powershell
error: No `project` table found in: `C:\Users\joe`
```

# Context
The command I invoked on windows terminal.
```
uv init my-project
```

The uv platform
```
Windows 10 home edition
```

The uv version
```
uv 0.3.1 (be17d132a 2024-08-21)
```

**Comment by zanieb** [comment]
Weird! Thanks for the report. Is there a `pyproject.toml` in the working directory or any of the directories above it? e.g. at `C:\Users\joe`?

Does `uv init --no-workspace` work?

**Comment by joe-cho** [comment]
> Weird! Thanks for the report. Is there a `pyproject.toml` in the working directory or any of the directories above it? e.g. at `C:\Users\joe`?
> 
> Does `uv init --no-workspace` work?

It indeed worked with an warning:
```powershell
PS C:\Users\joe\Projects\others> uv init my-project --no-workspace
warning: Ignoring workspace discovery error due to `--no-workspace`: No `project` table found in: `C:\Users\joe`
Initialized project `my-project` at `C:\Users\joe\Projects\others\my-project`
```

The folder structure of newly-created my-project: 
```powershell
PS C:\Users\joe\Projects\others\my-project> tree /F
Folder PATH listing
Volume serial number is D62B-04B3
C:.
│   pyproject.toml
│   README.md
│
└───src
    └───my_project
            __init__.py
```

```--no-workspace``` option is intended to use when no folder (workspace) exist. Any section about it in official doc?

**Comment by charliermarsh** [comment]
I think this is working as intended. It sounds like you maybe had an invalid `pyproject.toml` at the top-level? So specifying `--no-workspace` tells us to ignore any `pyproject.toml` in the parent directories.

**Comment by zanieb** [comment]
@charliermarsh sounds like this error message isn't great though — we should probably include `pyproject.toml` in the path and add a context to the error (like we do for the warning)

**Comment by jonmatthis** [comment]
Similar error when trying to initialize a new project in Windows 11

```
C:\Users\jonma\github_repos\jonmatthis>uv init hello-world
error: No `project` table found in: `C:\Users\jonma`

C:\Users\jonma\github_repos\jonmatthis>uv init            
error: No `project` table found in: `C:\Users\jonma`
```

I worked through the rest of the installation instructions as listed in the docs. 

---

Speaking supportively and constructively as a fellow FOSS developer - I'd prioritize a fix on this if I were y'all. I'm an experienced developer who followed all the instructions in your docs and I was met with a completely show-stopping error with no obvious route for a fix. Adding the `--no-workspace` flag fixes the issue, but I had to come to repo Issues to find that.

If I wasn't so excited about this project, that would have been enough for me to bounce away from this project and never look back. Generally when I see this kind of breaking bug in a project's intro tutorial, my brain immediately tags it as 'not ready for prime time' 

Thanks for your work on this! I look forward to using this tool! gl;hf!❤️

**Comment by charliermarsh** [comment]
Thanks, I can make some improvements here now.

**Comment by Badhansen** [comment]
I am facing a similar issue. When I try to create a project using `uv`, it does not work.

```
➜  Projects mkdir hello-world      
➜  Projects cd hello-world               
➜  hello-world uv init            
error: No interpreter found for executable name `venv` in managed installations or search path
➜  hello-world 

```

**OS and Version**
`macOS Version 15.1.1 (24B91)`


**The uv version**
`uv 0.6.5 (bcbcd0a1e 2025-03-06)`

**Comment by Badhansen** [comment]
> I am facing a similar issue. When I try to create a project using `uv`, it does not work.
> 
> ```
> ➜  Projects mkdir hello-world      
> ➜  Projects cd hello-world               
> ➜  hello-world uv init            
> error: No interpreter found for executable name `venv` in managed installations or search path
> ➜  hello-world 
> ```
> 
> **OS and Version** `macOS Version 15.1.1 (24B91)`
> 
> **The uv version** `uv 0.6.5 (bcbcd0a1e 2025-03-06)`

To create a FastAPI project, I have to run the following command. 
```
uv init --app --python $(which python3)  
```
Is this the right way to do this? According to the documentation, the command to create a project is 'uv init project-name'.

**Comment by charliermarsh** [comment]
A few small things:

- `--app` is the default, so you can omit it or include it.
- If you run `uv init project-name`, it will create a project in a directory named `project-name`; if you omit `project-name`, it will initialize the project in the current directory.
- You shouldn't need `--python $(which python3)` unless there's something in your PATH getting in the way. You might prefer `--python 3.10` or similar to make sure you get the right version without worrying about where it is.
