### ISSUE TITLE
FR: Support installing and managing `uv` with `uv tool`

### ISSUE THREAD

**Issue by weihenglim** [astral-sh/uv#6400]
Currently the documentation's [recommended way](https://docs.astral.sh/uv/getting-started/installation/#pypi) of installing `uv` is via `pipx`. With the release of `uv tool`, it would be great to let `uv` manage itself, similar to how you can do `pipx install pipx`.

When testing on my Windows 11 machine, `uv tool install uv` works but the tool breaks when attempting to upgrade `uv` to the latest version:
```sh
> uv tool upgrade uv 
Resolved 1 package in 38ms
Prepared 1 package in 1ms
Installed 1 package in 8ms
 + uv==0.3.1
error: failed to remove file `C:\Users\User\.local\bin\uv.exe`
  Caused by: Access is denied. (os error 5)

> uv tool list
warning: Ignoring malformed tool `uv` (run `uv tool uninstall uv` to remove)
```

**Comment by charliermarsh** [comment]
Ahh yeah, that's a known issue on Windows: https://github.com/astral-sh/uv/issues/1368. You _should_ be able to do `uv self update` if you installed via the standalone installers (as opposed to through `pip` or similar).

**Comment by zanieb** [comment]
I'm not sure it makes sense to manage uv with uv, it creates a weird chicken and egg problem. You can definitely do `uvx uv@version` though!

**Comment by konstin** [comment]
`rustup update` updates both its managed toolchains, then does a self update, we should consider a similar convenience function for uv.

**Comment by zanieb** [comment]
Hm like `uv upgrade`?

- Upgrade self
- Upgrade all tools
- Upgrade all Python versions

Could be cool.
