### ISSUE TITLE
[Feature request] Explicit dry-run cli option

### ISSUE THREAD

**Issue by birdhackor** [astral-sh/uv#6408]
If I want to know which packages versions will change when I do a upgradable relock, I might want to do the following command

``` shell
$ uv lock -U --dry-run
```

Currently, there seems to be no direct instruction to achieve a similar effect. The following command will report an error and cannot achieve the effect I want.

``` shell
$ uv lock -U --locked
Resolved 10 packages in 126ms
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```

**Comment by charliermarsh** [comment]
This makes sense to me.

**Comment by zanieb** [comment]
Makes sense. There's also `uv lock -U && git diff && git reset --hard`, but we can do better.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/7783.
