### ISSUE TITLE
uv tool upgrade forgets username for git packages

### ISSUE THREAD

**Issue by mil-ad** [astral-sh/uv#6420]
I installed a package directly from a git repo using `uv tool install git+ssh://git@github.com/foo/bar.git`. This works fine but when I try to upgrade the package with `uv tool upgrade bar` it tries to use $USER instead of `git` username and fails to upgrade the package. Is this a known bug?

**Comment by charliermarsh** [comment]
I thought I had fixed this in v0.3.1, but let me take another look right now...

**Comment by charliermarsh** [comment]
Do you mind doing `uv tool uninstall bar`, reinstalling, and trying to upgrade again? I think this _was_ fixed in v0.3.1 but you might have an "invalid" install receipt leftover from 0.3.0. Sorry!

**Comment by mil-ad** [comment]
You're right. Works if uninstall and do install/upgrade in 0.3.1

**Comment by charliermarsh** [comment]
Sorry about that!
