### ISSUE TITLE
`uv run` doesn't work on .pyw files

### ISSUE THREAD

**Issue by Gaiko-sw** [astral-sh/uv#6435]
Platform: Both Windows 10 & Ubuntu 24.04
uv version: uv 0.3.1

I have a python UI application at work that we start through `main.pyw` in order to prevent a console window opening if it's double clicked in Windows Explorer.
It's now managed through poetry, which launches it fine through the main.pyw file. In trying to switch the project to uv, I found that it's not able to start. I've attempted this minimal example on Ubuntu and got a similar result:

- `pip` or `pipx install uv`
- `uv init pyw_test`, `cd pyw_test`
- Put a tkinter hello world in `main.pyw`:
```
import tkinter as tk
root = tk.Tk()
root.mainloop()
```
- `uv run main.pyw`

You get an error like **"Failed to spawn: main.pyw"** then an OS specific **"Caused by: No such file/%1 is not a valid Win32 application"**

Changing main.pyw to main.py works fine

I think this might just be that pyw files aren't handled like py files. The .pyw only has an effect on the windows launcher, but I still think it should be handled by uv.

**Comment by zanieb** [comment]
Thanks for the report! This should be a quick fix.

**Comment by zanieb** [comment]
Does `uv run python main.pyw` work too?
