### ISSUE TITLE
install cli scripts into the virtual environment

### ISSUE THREAD

**Issue by natelandau** [astral-sh/uv#6445]
Platform and UV information: `uv 0.3.1 (Homebrew 2024-08-21)` running on `MacOS Sonoma 14.1.2`

I am working to migrate a number of packages from Poetry to uv.  Perhaps I'm just not understanding the documentation, but I can't figure out how to install CLIs into the venv created by uv. 

I manage multiple CLIs out of single packages. During development, I need to run the CLIs within the virtual environment. How would this be accomplished using uv?

Minimal package layout:
```
├── pyproject.toml
├── src/
    └── package_name/
        ├── __init__.py
        ├── cli1.py
        ├── cli2.py
        ├── models/
        ├── utils/
        ├── ...
```

This was easily accomplished in Poetry using `tool.poetry.scripts` in the `pyproject.toml` file. This would allow invoking any of the cli scripts within the virtual environment rather than the running the globally installed version

```toml
[tool.poetry.scripts]
    cli1 = "package_name.cli1:app"
    cli2 = "package_name.cli2:app"
```

is similar functionality available in uv?  or a workaround that I'm not seeing?

**Comment by zanieb** [comment]
Hey! We support the standard [`[project.scripts]`](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts) table instead of declaring some tool-specific section :)
