### ISSUE TITLE
Feature request: Allow script dependency inline with file docstring

### ISSUE THREAD

**Issue by aaronsteers** [astral-sh/uv#6461]
I am thrilled about `uv` and have been testing it with custom scripts.

One small ergonomics issue I ran into is the competing placement of a file-level docstring with the inline metadata. I think it could be cleaner to allow `///script` elements to exist inside the file-level docstring.

Today I have this:

```py
"""Simple script to download secrets from GCS.

Usage:
    pipx install uv
    uv run scripts/fetch_test_secrets.py
"""
# Inline dependency metadata for `uv`:
# /// script
# requires-python = "==3.10"
# dependencies = [
#     "airbyte",  # PyAirbyte
# ]
# ///

from __future__ import annotations

...
```

But I would love to be collapse the dependency declarations into the docstring like this:

```py
"""Simple script to download secrets from GCS.

Usage:
    pipx install uv
    uv run scripts/fetch_test_secrets.py

Inline dependency metadata for `uv`:

/// script
requires-python = "==3.10"
dependencies = [
    "airbyte",  # PyAirbyte
]
///
"""

from __future__ import annotations

...
```

Or using a markdown triple-backtick block like this:

````py
"""Simple script to download secrets from GCS.

Usage:
    pipx install uv
    uv run scripts/fetch_test_secrets.py

Inline dependency metadata for `uv`:

```toml-uv-script
requires-python = "==3.10"
dependencies = [
    "airbyte",  # PyAirbyte
]
```
"""

from __future__ import annotations

...
````

Thanks for considering! And thanks for all your work on this project!

**Comment by charliermarsh** [comment]
Thanks!

The use of `# /// script` is actually codified in a standard ([PEP 723](https://peps.python.org/pep-0723/)), so we don't have control over the structure in that way, since it needs to be interoperable with other tools (e.g., maybe you're using Ruff, and want to put your Ruff configuration for the file in that block).

**Comment by aaronsteers** [comment]
@charliermarsh - Thanks for your reply. After reviewing PEP 723 more closely (I only glanced at it previously), I see what you mean.

I also found that this iteration is a middle-ground that I find cleaner - and testing confirmed it still works! Feels weird to have comments inside a docstring block, but it doesn't violate the PEP and `uv` handles is just fine. 😄 

```py
"""Simple script to download secrets from GCS.

Usage:
    pipx install uv
    uv run scripts/fetch_test_secrets.py

Inline dependency metadata for `uv`:

# /// script
# requires-python = "==3.10"
# dependencies = [
#     "airbyte",  # PyAirbyte
# ]
# ///

"""
```

**Comment by aaronsteers** [comment]
Thanks again for your help - closing as resolved.

**Comment by charliermarsh** [comment]
Oh, that's true! Thanks for following up.
