### ISSUE TITLE
Add `uv sync --dev-only` or equivalent

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6472]
This was a feature request, it seems reasonable to me.

**Comment by zanieb** [comment]
Including the root project, I presume? `--only-dev` for consistency with `--with` and `--no-install`?

**Comment by charliermarsh** [comment]
Yeah I prefer `--only-dev`. I was thinking exclusive of the root project but... I'm not sure?

**Comment by uptickmetachu** [comment]
We also need the ability to `uv pip install pyproject.toml --dev` (including dev requirements). 

Necessary to install dev requirements into a docker containers `--system`.

**Comment by charliermarsh** [comment]
I wonder if this should instead be `--prod` and `--no-prod`, like `--dev` and `--no-dev`.

**Comment by zanieb** [comment]
I feel like `--prod` might imply something more, like ignoring development sources?
