### ISSUE TITLE
Respect output-file symlinks

### ISSUE THREAD

**Issue by dpoznik** [astral-sh/uv#6485]
`uv 0.2.36` respected output-file symlinks, whereas `uv 0.3.1` does not.

Let's say we have the following symlink:
```sh
macos.txt  ->  macos.312.txt
```
With `uv 0.2.36`, invoking the following command would update `macos.312.txt`, leaving the symlink in place, as expected.
```sh
uv pip compile macos.in --output-file macos.txt
```

With `uv 0.3.1`, invoking the command removes the symlink and creates a new regular file in its place, `macos.txt`, contrary to expectation.

I did not see a note about this behavior change in the release notes. Was it intentional?
If not, would it be possible to revert this behavior?

Thanks!

**Comment by charliermarsh** [comment]
Ah ok, this was _not_ intentional but I see why it changed.

**Comment by charliermarsh** [comment]
I'll mark it as a bug.

**Comment by dpoznik** [comment]
Thanks @charliermarsh!
