### ISSUE TITLE
`uv add` adds a depencency even if there is a failure during installation

### ISSUE THREAD

**Issue by tjquillan** [astral-sh/uv#6486]
When running `uv add` fails to install the package, it is still added to the dependency array of `pyproject.toml` causing future invocations of `uv add` to fail as well.

# Reproduction Steps
1. Run `uv add pytorch` in a blank project
  * This will fail notifying you that `Exception: You tried to install "pytorch". The package named for PyTorch is "torch"`
 2. Observe that the `pyproject.toml` added it to the dependencies array despite this failure.
 3. When you then attempt to run `uv add torch` as instructed, it will fail in the same way as `pytorch` is now in the dependency array.

**Comment by charliermarsh** [comment]
I think it _probably_ makes sense to remove the dependency here. We already remove the dependency if _resolution_ failed.

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/6526. Thanks for the contribution.
