### ISSUE TITLE
`uv add` should assume `--dev` if in a virtual workspace root

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6492]
I find it somewhat tedious that you have to add `--dev`:

```
❯ uv add flask
error: Found a virtual workspace root, but virtual projects do not support production dependencies (instead, use: `uv add --dev`)
```

**Comment by TomerBin** [comment]
What do you think about suggesting to add the new dependency to a specific workspace member as another solution?

**Comment by zanieb** [comment]
This may not be applicable if we allow virtual projects.

**Comment by charliermarsh** [comment]
No longer relevant as of [v0.4.0](https://github.com/astral-sh/uv/releases/tag/0.4.0) -- these "virtual workspace roots" were deprecated. Instead, users can just omit `[build-system]`, and uv will avoid building and installing it by default (but will still resolve and include its dependencies).
