### ISSUE TITLE
`uv lock` and platform-specific resolution

### ISSUE THREAD

**Issue by SamyAB** [astral-sh/uv#6503]
The documentation says:

> By default, uv's pip interface, i.e., [uv pip compile](https://docs.astral.sh/uv/pip/compile/), produces a resolution that is platform-specific, like pip-tools. There is no way to use platform-specific resolution in the uv's project interface.

Does the last sentence mean that there is _currently_ no way to create a platform-specific lockfile with `uv lock`, or there will _never_ be one?

If it's the latter, I am curious to know why.

The reason I am asking this is because it happens quite often that I work on both `x86` and `armv7l` architectures, and having a lockfile for x86 that points to `pypi`-like registry and a lockfile for `armv7l` that points to a [piwheels](https://www.piwheels.org/)-like registry is very useful.

Thank you for the awesome work!

**Comment by SamyAB** [comment]
That gets me 95% of the way there, thanks!

**Comment by charliermarsh** [comment]
See: https://docs.astral.sh/uv/concepts/projects/config/#limited-resolution-environments
