### ISSUE TITLE
Too many open files when syncing a big project

### ISSUE THREAD

**Issue by yoav-orca** [astral-sh/uv#6508]
* The current uv platform - macOS
* The current uv version (`uv --version`): `uv 0.3.2 (c5440001c 2024-08-23)`

When trying to resolve a very big project (413 direct dependencies and 673 indirect dependencies).
I can't share the specific requirements.
I'm consistently running out of fds:

```
error: Failed to write to the client cache
  Caused by: Too many open files (os error 24) at path "/Users/yoavalon/.cache/uv/simple-v12/pypi/.tmpPKond8"
```

**Comment by charliermarsh** [comment]
macOS has a very low open-file limit. Running `ulimit -n 16000` should unblock you here.

**Comment by FCamborda** [comment]
if you are running this when building with Docker, there are CLI flags to control the file handle limit during that process.

**Comment by zanieb** [comment]
Unfortunately not much we can do about this — the default is weirdly low.

**Comment by charliermarsh** [comment]
Going to close. The answer is above for future readers, but if it continues to come up we can add to the docs explicitly.
