### ISSUE TITLE
Support `uv tool install package@version` to match `uvx`

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6535]
Otherwise, going from `uvx` to `uv tool install` can be surprising.

**Comment by baggiponte** [comment]
I wonder whether using `@` is appropriate over `package==version`. The `@` is documented for example [here](https://docs.astral.sh/uv/pip/packages/#installing-a-package) for `uv pip install "ruff @ ./projects/ruff"`.

**Comment by charliermarsh** [comment]
`package==version` does work here already. But `uvx` uses `package@version` because it does _not_ accept an arbitrary version specifier, just a single version, and we want to disambiguate.

**Comment by chrisrodrigue** [comment]
`@` is very commonly used for specifying locations/paths, for example `person@company.com` or `package@path/to/pkg/src`.

Maybe this could cause some confusion/surprises.

**Comment by zanieb** [comment]
It might not be worth it, but... I'm not sure if it's that common? We had a lot of complaints about requiring `package @ path` and I'm not sure how `person@company` applies? Regardless, we can easily 

1) Tell if it's a path and/or
2) Treat it as we would now if it's not a valid PEP 440 version — that's what we do in `uvx tool@version`

**Comment by chrisrodrigue** [comment]
Ah sorry, I should have clarified that `person@company.com` is an email address 😆

I’m not sure what PEPs might govern tokens used in the context of package paths/versions but [RFC 3986](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) could be a good standard to reference that covers allowed uses of `@` in URIs if there isn’t anything more relevant.

**Comment by zanieb** [comment]
To be clear — we already support `uvx ruff@0.6.1` and `uvx ruff@latest` so we already have clear semantics around this. This issue is about extending those semantics to `uv tool install` to avoid confusion.

**Comment by chrisrodrigue** [comment]
That makes sense 😁

(By the way, it looks like [PEP440 covers `@` for direct references with explicit URLs](https://peps.python.org/pep-0440/#direct-references).)

**Comment by charliermarsh** [comment]
Gonna do this now.

**Comment by damienrj** [comment]
This would also make sense given the [docs](https://docs.astral.sh/uv/reference/cli/#uv-tool-run) indicate that the `@` is the method for doing the install.
`The name of the command can include an exact version in the format <package>@<version>, e.g., uv run ruff@0.3.0. If more complex version specification is desired or if the command is provided by a different package, use --from.`

**Comment by charliermarsh** [comment]
(Separately, there's a typo there, it should be `uv tool run ruff@0.3.0`.)
