### ISSUE TITLE
Can't `uv run --with` private package index

### ISSUE THREAD

**Issue by jacob-bush-shopify** [astral-sh/uv#6537]
```
> uv -V
uv 0.3.2 (c5440001c 2024-08-23)
```

We have a private package index:
```
> pip config list
global.extra-index-url='https://pypi.python.org/simple'
global.index-url='https:*****'
```

Private packages can be installed with `uv` without any issue:
```
> uv pip install privately-hosted-package
Resolved 38 packages in 3.54s
Installed 38 packages in 44ms
```

But trying to run a command using `--with` does not work:
```
> uv run --with privately-hosted-package echo "success"
  × No solution found when resolving `--with` dependencies:
  ╰─▶ Because privately-hosted-package was not found in the package registry and you require
      privately-hosted-package, we can conclude that your requirements are unsatisfiable.
```

Note that manually specifying the index urls seems to work fine:
```
> uv run --with privately-hosted-package --index-url 'https://*****' --extra-index-url 'https://pypi.python.org/simple' echo "success" 
success
```

**Comment by zanieb** [comment]
Hi! We don't read the pip configuration file (see #1404)

**Comment by jacob-bush-shopify** [comment]
> Hi! We don't read the pip configuration file 

Interesting. Any idea why `uv pip install` worked then?

**Comment by jacob-bush-shopify** [comment]
> You can specify your index URL in a uv configuration file? https://docs.astral.sh/uv/configuration/files/

That could be a good option, thank you.

**Comment by charliermarsh** [comment]
Is it possible you have the index URL set in a configuration file somewhere already?

**Comment by zanieb** [comment]
Oh, sorry I missed that part. That's confusing. Were they run in the same directory?

**Comment by zanieb** [comment]
Is the index URL in a uv configuration file in a `[uv.pip]` section instead of `[uv]`?

**Comment by jacob-bush-shopify** [comment]
> Is the index URL in a uv configuration file in a [uv.pip] section instead of [uv]?

This was the issue
Removing the table header from the `uv.toml` file lets me execute `uv run --with privately-hosted-package echo "success"`

**Comment by zanieb** [comment]
Awesome! Documentation on that at https://docs.astral.sh/uv/configuration/files/#configuring-the-pip-interface
