### ISSUE TITLE
uv run --no-project fails due to missing pyproject.toml sections

### ISSUE THREAD

**Issue by meastham** [astral-sh/uv#6550]
Similar issue to https://github.com/astral-sh/uv/issues/6177

If I run `uv run --no-project ...` in a directory with a `pyproject.toml` with a missing `project` table, I get an error:

```
❯ uv -V
uv 0.3.2 (c5440001c 2024-08-23)
❯ cd $(mktemp -d)
❯ touch pyproject.toml
❯ uv run --no-project python
error: No `project` table found in: `/private/var/folders/1s/0jgtfqgd1wqc327r1kxgrh3w0000gn/T/tmp.mAGDf4eLya/pyproject.toml`
```

Same result with `--no-config`

(this is on MacOS / apple silicon)

**Comment by charliermarsh** [comment]
Thanks, my bad, I'll fix that now.
