### ISSUE TITLE
Add Prompts to use System or Managed Python versions or add "auto" option for python preferences

### ISSUE THREAD

**Issue by vasudev-gm** [astral-sh/uv#6592]
Well sorry for another late Feature request. Ran into an issue at work wherein the downloaded python versions through uv were not detected when passing the command:
`uv venv --python 3.8`

until I had to re-check the documentation and pass the python preference to be system or managed with command:
`uv venv --python 3.8 -p managed `

Will it be possible for uv to prompt the user which version to install or can we set it globally to prefer only managed versions? 

Thanks.

**Comment by charliermarsh** [comment]
Just confirming, is this on `v0.3.0` or later?

**Comment by vasudev-gm** [comment]
Yes 0.3.0 and later. I am using uv 0.3.2.


________________________________

**Comment by vasudev-gm** [comment]
I did install the python versions. Currently I have pipenv installed and managing venv.
So there's no way to declare globally besides using toml config? I had to declare --python- preference managed in cmdline



________________________________

**Comment by zanieb** [comment]
I still don't quite follow what you're saying, because `--python-preference managed` matches out default and should have no effect. Anyway, you can also use `UV_PYTHON_PREFERENCE` to configure this globally.

**Comment by vasudev-gm** [comment]
> I still don't quite follow what you're saying, because `--python-preference managed` matches out default and should have no effect. Anyway, you can also use `UV_PYTHON_PREFERENCE` to configure this globally.

I will try to be clear as possible. So I wanted to ask if uv options can be set globally without needing .toml file OR uv should prompt the user asking whether to use system or managed installed when python runtimes are detected without the need for passing --python-preference [managed|system] in the command line.

**Comment by zanieb** [comment]
I don't think we'll block commands for interactive prompting on which Python interpreter to use. We use whatever interpreter we can find to satisfy the Python version — this default is very intentional. If you don't want to use the system interpreters at all, we have several ways to configure that globally and per invocation.

**Comment by vasudev-gm** [comment]
I'll try the uv commands. Is there a documentation link for global commands for uv.


________________________________

**Comment by zanieb** [comment]
Like https://docs.astral.sh/uv/reference/cli/ ?

**Comment by vasudev-gm** [comment]
Didn't know there it's a web version of entire commands. Been using uv --help to find how to use the commands. Thanks


________________________________
