### ISSUE TITLE
Shims like in pyenv or rye

### ISSUE THREAD

**Issue by martenlienen** [astral-sh/uv#6598]
Does uv plan to add shims as they exist in rye or pyenv? With this, I mean a bunch of executables that dispatch to the correct executable when called depending on a local `.python-version` file or an environment variable. For example, in pyenv I can run `cd ~/src/some-project; pyenv local project-venv` and then, whenever I change into `~/src/some-project` or a subdirectory, running `python` or another executable from some package will automatically dispatch to the environment `project-venv` without me having to explicitly activate it.

**Comment by charliermarsh** [comment]
Thanks! We plan to add this kind of behavior for Python, but likely not for other executables. I believe that's tracked here: #6265.

**Comment by charliermarsh** [comment]
(Gonna merge into that other issue.)

**Comment by martenlienen** [comment]
That is great! Is there a reason why you plan to support it only for the python executable?

**Comment by n-gao** [comment]
@zanieb Another example would be our experiment management library [`seml`](https://github.com/TUM-DAML/seml) which must be executed from the same environment as the project environment. At the moment, I always have to manually activate my uv virtual environment. The actual project environment is needed to resolve configurations and discover loaded source files.

**Comment by zanieb** [comment]
Yeah until we have project-level tools (as described in #3560), I think a development dependency and `uv run` is the solution for tools that require the project to be installed.
