### ISSUE TITLE
Docs missing uv add --editable

### ISSUE THREAD

**Issue by ion-elgreco** [astral-sh/uv#6601]
`UV version 0.3.3`

uv add --editable isn't documented yet even though it's extremely useful :)

**Comment by charliermarsh** [comment]
I think the CLI help is inverted here -- we show `--no-editable` but should show `--editable`. (I assume you're referring to `uv add --help` here?)

**Comment by ion-elgreco** [comment]
@charliermarsh yes, and the website docs as well
