### ISSUE TITLE
Specify build args during uv sync

### ISSUE THREAD

**Issue by ion-elgreco** [astral-sh/uv#6602]
When we run uv sync it builds the package but sometimes we want to specify build args to the underlying build tool. Is there any way to allow this passthrough at the moment?

**Comment by charliermarsh** [comment]
Have you seen https://docs.astral.sh/uv/reference/settings/#config-settings?

**Comment by charliermarsh** [comment]
Closing for lack of follow-up but happy to answer any further questions.

**Comment by ion-elgreco** [comment]
@charliermarsh but how can you make this dynamic? I want to specify new build_args whenver

**Comment by charliermarsh** [comment]
Can you expand on your comment? You can just pass these via the CLI.

**Comment by ion-elgreco** [comment]
> Can you expand on your comment? You can just pass these via the CLI.

Ah you mean like uv build -C ?

**Comment by charliermarsh** [comment]
Yeah
