### ISSUE TITLE
shared env cache: copy fails on install

### ISSUE THREAD

**Issue by stas00** [astral-sh/uv#6648]
This is a continuation of trying to use `uv` in a shared uv-cache https://github.com/astral-sh/uv/issues/5581

With `uv==0.3.3` we have a new issue:

The settings are:
```
export UV_LINK_MODE=copy
export UV_CACHE_DIR=/env/cache/uv
```

This is installing into a just-created fresh conda env:
```
$ conda create -y -n stas-test-123 python=3.10
$ pip install uv
$ uv pip install -e .
[...]
Prepared 1 package in 5.77s
Uninstalled 2 packages in 2.29s
error: Failed to install: setuptools-69.5.1-py3-none-any.http.whl (setuptools==69.5.1)
  Caused by: failed to copy file from /data/env/cache/uv/archive-v0/kYFrh3jfzM6r7gQ92HOcR/distutils-precedence.pth to /env/lib/conda/stas-test-123/lib/python3.10/site-packages/distutils-precedence.pth
  Caused by: Operation not permitted (os error 1)
```
The permissions are all correct so it shouldn't be failing.

```
ls -l /data/env/cache/uv/archive-v0/kYFrh3jfzM6r7gQ92HOcR/distutils-precedence.pth
-rw-rw-rw- 3 user1 user1 151 Aug 19 18:39 /data/env/cache/uv/archive-v0/kYFrh3jfzM6r7gQ92HOcR/distutils-precedence.pth

ls -l /env/lib/conda/stas-test-123/lib/python3.10/site-packages/distutils-precedence.pth
-rw-rw-rw- 8 user2 user2 0 Aug 26 18:48 /env/lib/conda/stas-test-123/lib/python3.10/site-packages/distutils-precedence.pth

ls -l /env/lib/conda/stas-test-123/lib/python3.10/ | grep site-pac
drwxrwxrwx  1 user3 user3    0 Aug 26 18:48 site-packages/
```

In fact I can copy the file just fine:
```
cp /data/env/cache/uv/archive-v0/kYFrh3jfzM6r7gQ92HOcR/distutils-precedence.pth /env/lib/conda/stas-test-123/lib/python3.10/site-packages/distutils-precedence.pth
```
no error and then if I rerun the command - uv pip install succeeds.

Please note 3 users are involved here. The source file is owned by user1, the destination file is owned by user2 and I'm user3 running `uv`.

Thank you.

@charliermarsh

**Comment by charliermarsh** [comment]
Interesting, thanks. Does this affect certain packages or files? E.g., is it always `.pth` files or something like that?

**Comment by stas00** [comment]
Interesting, inspecting the logs from conda I run into this:

```
$ conda create -y -n stas-test-123 python=3.10
[...]
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: / 
SafetyError: The package for setuptools located at /env/cache/conda/pkgs/setuptools-72.2.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/distutils-precedence.pth'
has an incorrect size.
  reported size: 151 bytes
  actual size: 0 bytes
```

so it looks like the first package came from conda.

Let me try and fix that and retry

**Comment by stas00** [comment]
I'm pretty convinced that it has to do with some IO failure on the shared network fs and nothing to do with `uv`, since we had other IO issues this morning. So I'm closing this.

**Comment by charliermarsh** [comment]
Ok thanks for following up -- appreciate it. Please feel free to reopen in the future if you hit it again and think uv is involved.

**Comment by stas00** [comment]
Thank you for your amazing support, Charlie!
