### ISSUE TITLE
Export `uv.lock` to `requirements.txt`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6668]

**Comment by mikeleppane** [comment]
+1 

After using Poetry for years, I've decided to try uv. And it's great. Here are some thoughts I had while using uv. Some of these may have been discussed already.
- export only dev-dependencies from uv.lock to requirements-dev.txt (this is useful at least in the CI) 
- _uv sync/pip install_ only dev-dependencies (like above useful in the CI) 
- show the latest version but only for outdated packages; _poetry show --outdated_ / _poetry show --outdated --only=dev_ has been useful. 
- how do get info about the current virtual env? E.g. Poetry has _poetry env info_ command to display info about current env
- is it possible to only update dev-dependencies like _poetry update --only=dev_?

Thanks!
