### ISSUE TITLE
Support `uv pip install -r uv.lock`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#6670]

**Comment by leddy231** [comment]
I think this makes a lot of sense, this would allow installing packages from one or more lockfiles directly to the system python, without removing any packages (which `uv sync` would do). We need this for painless switch from poetry to uv :smile:

**Comment by charliermarsh** [comment]
I'm currently more in favor of adding `uv export` to `requirements.txt`, then `uv pip install -r requirements.txt`, since it's more flexible and composable.

**Comment by leddy231** [comment]
That would work too, and would be a clearer separation between project tools `uv ...` and raw pip tools.

Could they be piped together? A `uv export | uv pip install --system` oneliner in the dockerfile would be nice, instead of a intermediate file

**Comment by shaunhegarty** [comment]
> That would work too, and would be a clearer separation between project tools `uv ...` and raw pip tools.
> 
> Could they be piped together? A `uv export | uv pip install --system` oneliner in the dockerfile would be nice, instead of a intermediate file

This would be nice for github actions too. Alternatively offer a way to specify the system interpreter when doing `uv sync`

**Comment by zanieb** [comment]
@shaunhegarty can you share more about why `uv run` is not suitable for use in GitHub Actions in your use-case?

**Comment by shaunhegarty** [comment]
> @shaunhegarty can you share more about why `uv run` is not suitable for use in GitHub Actions in your use-case?

Knowledge deficit on my part. `uv run` works for all the actions so far. Thanks!
