### ISSUE TITLE
Add semver-compatible docker tag prefixes

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#6678]
Currently, we only tag latest and specific versions in [ghcr.io/astral-sh/uv](https://github.com/astral-sh/uv/pkgs/container/uv). We should also tag and update e.g. `0.3`, so you can do `COPY --from=ghcr.io/astral-sh/uv:0.3 /uv /bin/uv` and also get the latest compatible 0.3 release.

**Comment by zanieb** [comment]
Definitely. 

Example at https://github.com/PrefectHQ/prefect/blob/0b747dc7b4c9f94d5e8ffe7e6ab7a045de7451e0/.github/workflows/docker-images.yaml#L110-L116
