### ISSUE TITLE
Install uv with uv

### ISSUE THREAD

**Issue by ewjoachim** [astral-sh/uv#6679]
Now that uv supports tools, is it a good id that uv manages its own installation ?
If I do:
```console
$ uv tool install uv
```

and then uninstall the uv I used to run this, am I likely to get into problems ?

Also, should that be what the install script does ? Is there a good reason that I need to add multiple paths to my PATH, and `uv` itself is not in `~/.local/bin` and instead in `~/.cargo/bin` ?

**Comment by zanieb** [comment]
Hi! I think this is a duplicate of https://github.com/astral-sh/uv/issues/6662 and #6400

> then uninstall the uv I used to run this, am I likely to get into problems ?

Uhh.. I guess it'd work. I wouldn't recommend it.

>  Is there a good reason that I need to add multiple paths to my PATH

What other paths do you need? Isn't there just one?

> and uv itself is not in ~/.local/bin and instead in ~/.cargo/bin ?

Yes, we want to move it but haven't for backwards compatibility. We will eventually.

**Comment by ewjoachim** [comment]
Oh, sorry, I tried searching and didn't see those :(
Thanks for your answer ! Sorry for the time waste.
