### ISSUE TITLE
Error message for malformed `tool.uv.sources` section

### ISSUE THREAD

**Issue by tpgillam** [astral-sh/uv#6681]
A feature / documentation request, applicable to uv 0.3.4.

For reasons that I can't quite remember, I ended up with an extraneous `editable = true` in a workspace source. In an older version of `uv` (pre 0.3, but I'm afraid I can't recall which version) this 'worked', but the latest version complains.

For example:

```toml
[project]
name = "moo"

[tool.uv.sources]
foo = { workspace = true, editable = true}
```

Running `uv sync` with the above gives the error:
```
error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 5, column 7
  |
5 | moo = { workspace = true, editable = true}
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
data did not match any variant of untagged enum Source
```

By digging around in the source code I did find the `Source` enum that told me that it should have only the `workspace` field and not the `editable` field, but it'd be great if the error message specified what the expected fields are (or possibly a link to the appropriate docs section).

**Comment by charliermarsh** [comment]
I believe this is now fixed.
