### ISSUE TITLE
`--no-install-workspace` needs the pyproject.toml of each workspace member to be present

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#6685]
`uv sync --no-dev --no-install-workspace --locked` doesn't work when only the root `pyproject.toml` and `uv.lock` are present. We should allow installing the entire workspace with `--no-install-workspace --locked` when only the top level `uv.lock` is present.

Reproducer failing:

```dockerfile
FROM ubuntu AS builder

RUN mkdir /app
WORKDIR /app
ENV UV_PYTHON_INSTALL_DIR=/app/python

COPY --from=ghcr.io/astral-sh/uv /uv /bin/uv

# Install the dependencies
ADD pyproject.toml uv.lock /app/
RUN uv sync --no-dev --no-install-workspace --locked

# Install the project itself
ADD src /app/src
ADD packages /app/packages
RUN uv sync --no-dev --locked
```

Passing:
```dockerfile
FROM ubuntu AS builder

RUN mkdir /app
WORKDIR /app
ENV UV_PYTHON_INSTALL_DIR=/app/python

COPY --from=ghcr.io/astral-sh/uv /uv /bin/uv

# Install the dependencies
ADD pyproject.toml uv.lock /app/
ADD packages/bird-feeder/pyproject.toml /app/packages/bird-feeder/pyproject.toml
ADD packages/seeds/pyproject.toml /app/packages/seeds/pyproject.toml
RUN uv sync --no-dev --no-install-workspace --locked

# Install the project itself
ADD src /app/src
ADD packages /app/packages
RUN uv sync --no-dev --locked
```

**Comment by charliermarsh** [comment]
The same in spirit as #6573 though makes sense to keep separate; it might be separately fixable.

**Comment by konstin** [comment]
Will probably fix them in one go but i wanted to document the test case.

**Comment by charliermarsh** [comment]
I _think_ this one is easier to fix.

**Comment by AnkitSiva** [comment]
I'm still running into this issue. I have a minimal reproducible setup [here](https://github.com/AnkitSiva/uv_minimal_repro). I think you may have fixed the `--frozen` but not the `--locked` case?

**Comment by charliermarsh** [comment]
Locked requires all the members to be present. Locked requires that we validate the lockfile, which requires a resolution, which requires the member pyproject.toml files.

**Comment by AnkitSiva** [comment]
Gotcha, thanks for the blazing fast reply!

**Comment by leonardocustodio** [comment]
In that case, this guide should be reviewed: https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers

> If you're using a [workspace](https://docs.astral.sh/uv/concepts/projects/workspaces/), then use the --no-install-workspace flag which excludes the project and any workspace members.

It gives the impression that you should use `--no-install-workspace` and it will work out of the box, even if it is being suggested to use `--lock` just above

Though I also get the error without the `--lock`, maybe there is some other issue?

**Comment by charliermarsh** [comment]
I believe we only fixed this for `--frozen`. I don't think we should or even can fix it for `--locked`.

**Comment by leonardocustodio** [comment]
I mean without it it gives the same error, I suppose it defaults to `--locked` if you don't specify? I think just adding that in the highlight, which needs to be used with frozen, would be sufficient.
