### ISSUE TITLE
Path back to using released tl crate dependency?

### ISSUE THREAD

**Issue by musicinmybrain** [astral-sh/uv#6687]
As required by Fedora’s [guidelines for bundling](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling) – do you anticipate being able to go back to using the released `tl` crate at some point? It looks like all that’s needed is for https://github.com/y21/tl/pull/69 to be merged and released – is that correct? Thanks!

**Comment by zanieb** [comment]
Yes that sounds correct — we'd love to use the released `tl` crate but we also want to deliver that fix to our users.

**Comment by musicinmybrain** [comment]
Thanks! Closing this since the question is adequately answered.
