### ISSUE TITLE
What is the intended workflow for updating dependencies with uv?

### ISSUE THREAD

**Issue by christianplatta1012** [astral-sh/uv#6692]
Hi,
I am looking into uv for several days now and try to determine whether my team should switch from poetry to uv.
One thing that seems completely absent in the documentation is a way to update dependencies.

We are a python-only team with more than 40 separate projects. We get information about available updates/security issues from dependabot and then usually do a `poetry update` to update all dependencies to the latest minor version or a `poetry add <packagename>@latest` if we change major versions. This is usually faster an easier compared to merging dependabot pull requests.

What is the intended workflow in uv to update dependencies? 
I've found https://github.com/astral-sh/uv/issues/1419 that talks about a feature request similar to `poetry update` .
I could probably script something around uv until such a feature exists, but currently I am totally lost how even a single dependency update is intended to work...

Do I really need to know the latest version number for all my dependencies in the pyproject.toml and do a manual uv add <dependecy==version_number>?

**Comment by zanieb** [comment]
Hi! In short, you can do `uv lock --upgrade` to upgrade all of the locked versions of your packages.

We don't support "bumping" the dependency constraints in your `pyproject.toml` yet. That's definitely something we're interested in, but we haven't done any design work for that yet.

**Comment by christianplatta1012** [comment]
Thank you, this helps a lot.
Maybe worth to update this as an example to the docs. Searching for "upgrade" in https://docs.astral.sh/uv/ does not yield this as result.

**Comment by zanieb** [comment]
Thanks! https://github.com/astral-sh/uv/pull/6698

**Comment by Sam1320** [comment]
> We don't support "bumping" the dependency constraints in your pyproject.toml yet. That's definitely something we're interested in, but we haven't done any design work for that yet.

Any progress on this direction in the meantime? @zanieb  It would be really useful to auto-bump the .toml along with the .lock upgrade. I find myself constantly manually removing `uv remove [package]` and then re-adding it to update the pyproject.toml dependencies.

**Comment by mbeijen** [comment]
> > We don't support "bumping" the dependency constraints in your pyproject.toml yet. That's definitely something we're interested in, but we haven't done any design work for that yet.
> 
> Any progress on this direction in the meantime? @zanieb It would be really useful to auto-bump the .toml along with the .lock upgrade. I find myself constantly manually removing `uv remove [package]` and then re-adding it to update the pyproject.toml dependencies.
> 
> (also, is there a better workaround than `remove & add` ?)

I found a solution, it works fine but I'm not fully sure if it is the _best_ way;

 - in your `pyproject.toml` do *not* specify explicit versions, if you don't need to.
 - If you require a specific range, such as latest 4.2 release of Django, use `"Django>=4.2,<4.3"`
 - Install your dependencies using `uv sync` and commit `uv.lock`.
 - Now all your installs, co-workers and deploys use the exact same versions
 - If you want to upgrade, use `uv lock --upgrade` and uv will fetch the latest updates, based on your specified requirements

**Comment by zed** [comment]
To update specific dependency: `uv lock --upgrade-package <package>`

**Comment by Goldziher** [comment]
also interested in this

**Comment by zanieb** [comment]
See https://github.com/astral-sh/uv/issues/6794

**Comment by qiuxiaomu** [comment]
> Thanks! [#6698](https://github.com/astral-sh/uv/pull/6698)

Reading the help page for this command, i.e., 

> Allow package upgrades, ignoring pinned versions in any existing output file. Implies `--refresh`

I interpreted it as that it would ignore whatever the locked version is and as long as there's version newer than the one in lock file, uv is going to ignore whatever is locked and allowed in the lock file and update it to the latest available; this isn't he behaviour at the moment right? I see that uv is smart enough to only update what's not going to break the dependencies. 

If I was wrong, the help page is a bit confusing then, in that uv is not ignoring the locked version.

**Comment by cesarqdt** [comment]
> To update specific dependency: `uv lock --upgrade-package <package>`

this does not update to a latest available version, it just updates to the latest defined in the `pyproject.toml`

**Comment by mbeijen** [comment]
> > To update specific dependency: `uv lock --upgrade-package <package>`
> 
> this does not update to a latest available version, it just updates to the latest defined in the `pyproject.toml`

Yeah, if you have restrictions in pyproject.toml stating django < 5 you'll not get updated to django 5.x when running uv lock --upgrade, the lockfile must adhere to the constraints in the lockfile. You can remove those constraints, or you can see which newer versions would be available using `uv pip list --outdated`
