### ISSUE TITLE
Dockerfile question

### ISSUE THREAD

**Issue by itayporezky** [astral-sh/uv#6693]
[Dockerfile ](https://github.com/astral-sh/uv/blob/main/Dockerfile) basically builds the UV project and final step is to take the complete binary and add it as last layer on "scratch" image.

Maybe a more time-effective way is to take the already built binaries from UV's releases and add them instead of re-building the project?
It will also simplify the dockerfile

Please let me know your opinion and If applicable I can offer to work on the pipeline and dockerfile.

**Comment by zanieb** [comment]
We've considered this before, but we want to build the binary in a container for consistency. We don't mind the additional time and complexity.

cc @konstin
