### ISSUE TITLE
--require-hashes option does not work as with pip

### ISSUE THREAD

**Issue by thierryba** [astral-sh/uv#6701]
so I was trying to install my requirements.txt with uv pip install --require-hashes requirements.txt

My file contains urls with hashes. Example: borgbackup @ https://3rdparty.s3.amazonaws.com/borgbackup-1.2.8-cp312-cp312-macosx_11_0_universal2.whl#sha256=aca0a62c0e359b7663ebd4ee65e7bf7cdcbaecc8a001838eb49e8c886948ae6d

But uv is complaining saying that there is no hash. Is this expected?

**Comment by charliermarsh** [comment]
What does the `requirements.txt` contain exactly, in the above command?

**Comment by charliermarsh** [comment]
Right now you need to do:

```
borgbackup @ https://3rdparty.s3.amazonaws.com/borgbackup-1.2.8-cp312-cp312-macosx_11_0_universal2.whl --hash sha256:aca0a62c0e359b7663ebd4ee65e7bf7cdcbaecc8a001838eb49e8c886948ae6d
```

But I thought we supported reading hashes from the fragment directly. I'll look into it.

**Comment by charliermarsh** [comment]
Fixed in the next release.
