### ISSUE TITLE
uv run doesn't pass signals to children

### ISSUE THREAD

**Issue by overfl0** [astral-sh/uv#6724]
When you pass `uv run` as the command in `compose.yml`, you can't gracefully stop the process by pressing Ctrl+C. I'm guessing it's because it's not passing sigterm to its children.

Steps to reproduce:

- Clone https://github.com/astral-sh/uv-docker-example
- Open `compose.yml` and add `command: uv run fastapi dev --host 0.0.0.0 src/uv_docker_example`
- `docker compose build`
- `docker compose up`
- Press Ctrl+C

You will have to wait 10 seconds until docker forcibly sigkills the process.

Then:

- remove `uv run` from the command: `command: fastapi dev --host 0.0.0.0 src/uv_docker_example`
- `docker compose up`
- Press Ctrl+C

Compose will shutdown the process almost instantaneously.

uv 0.3.3 (according to uv-docker-example's Dockerfile)

**Comment by zanieb** [comment]
Thanks for the report!

**Comment by charliermarsh** [comment]
Interesting... We do pass Ctrl+C, so I would expect this to work.

**Comment by overfl0** [comment]
According to https://hynek.me/articles/docker-signals/ the signal that docker is supposed to send you is SIGTERM (so not SIGINT, which is sent on Ctrl+C), but I'm not an expert on this so all i can do is link you to that page

**Comment by overfl0** [comment]
Although I have to add that both adding `STOPSIGNAL SIGINT` to the Dockerfile and `stop_signal: SIGINT` to compose.yml failed for me, for some reason, as well.

**Comment by shaneikennedy** [comment]
Would it be possible to get a new patch release with this issue now close, please? Not properly handling  SIGTERM is negatively impacting anyone running uv in production with containers. For those who know it's a problem in their workloads they could mitigate this by running uv with something like [tini](https://github.com/krallin/tini) but would prefer to get a new version here if possible 🙏
