### ISSUE TITLE
`uv run` with a different root directory

### ISSUE THREAD

**Issue by haarisr** [astral-sh/uv#6733]
```bash
uv init bird
echo "import bird\n print(bird.hello())" > bird/main.py
uv run bird/main.py
```

```console
Traceback (most recent call last):
  File "/home/dev/bird/main.py", line 3, in <module>
    print(bird.hello())
AttributeError: module 'bird' has no attribute 'hello'
```

I would like to run `bird/main.py` from any directory that the user is in. 

If the user could specify the package root or `uv` could start searching for the `pyproject.toml` from the script path towards the root directory, that would help fix the issue.

uv version: `uv 0.3.2`

**Comment by JamesMTSloan** [comment]
Something like `uv -C bird/ run` would be useful. Missing this was one of the only slight pain-points I had migrating from Poetry. git also provides an equivalent `-C` option.

**Comment by charliermarsh** [comment]
`uv --directory` exists already -- is this what you're looking for?

**Comment by bluss** [comment]
uv --directory is hidden, I guess because it is not yet ready?

**Comment by zanieb** [comment]
Oh.. I want this to. Why do we hide it? haha

**Comment by charliermarsh** [comment]
I think we hide it because we wanted to change the semantics such that relative paths were resolved relative to the CWD rather than `--directory`.

**Comment by charliermarsh** [comment]
See: https://github.com/astral-sh/uv/issues/5613. We should unhide it though. I think I originally added it to facilitate benchmarking, and there wasn't consensus on the team at the time.

**Comment by zanieb** [comment]
Oh.. hm.. I guess it might make sense to sort that out since it'll be a breaking change.

**Comment by haarisr** [comment]
`--directory` works great. Didn't know that existed, thanks!

> I think we hide it because we wanted to change the semantics such that relative paths were resolved relative to the CWD rather than `--directory`.

This makes more sense to me. You can use shell autocomplete to find the file instead of knowing the script name relative to the project directory

**Comment by zanieb** [comment]
I think it makes sense but it seems non-trivial and I can see people getting confused either way.

**Comment by bluss** [comment]
I would feature request that it should work like this: https://github.com/astral-sh/uv/pull/5579#issuecomment-2257207224

But it doesn't have to be --directory that does it. It could be some other command on `uv run` with those requested semantics? It is not just about convenience, if the user can't control the current working directory (user "can't control it" here because the --directory has to be equal to the project directory with the uv project) then some commands can't be used correctly at all.

But the current rules for --directory have precedent in cargo -C and git -C.

**Comment by zanieb** [comment]
@bluss to clarify, `cargo -C` and `git -C` work like our current behavior?

**Comment by bluss** [comment]
@zanieb Yep, at least for git I'm sure of that, git says "Run as if git was started in <path> instead of the current working directory"

**Comment by charliermarsh** [comment]
We now support `--project` which accepts a path to a directory like this.

**Comment by mdengler** [comment]
> We now support `--project` which accepts a path to a directory like this.

Can I help to point to some documentation on how to use this?  As a poetry user, it's unclear how `--project` (or `--directory`) is helping here:

```
$ uv --version
uv 0.5.25

$ mkdir bird-uv-6733
$ cd bird-uv-6733/
$ mkdir bird
$ echo -e 'def hello():\n  print("hello bird")' > bird/__init__.py
$ mkdir examples
$ echo -e "import bird\nprint(bird.hello())" > examples/example1.py
$ tree .
.
├── bird
│   └── __init__.py
└── examples
    └── example1.py

3 directories, 2 files

$ uv run examples/example1.py 
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'


$ uv --project=$PWD run examples/example1.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'

$ uv --project=. run examples/example1.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'

$ uv --directory=$PWD run examples/example1.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'

$ uv --directory=. run examples/example1.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'

$ uv --directory=examples run examples/example1.py
error: Failed to spawn: `examples/example1.py`
  Caused by: No such file or directory (os error 2)

  $ uv --directory=examples run example1.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733/examples/example1.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'

```

I can file a new issue, but it seems something like what I've tried should actually work; that is, changes including:

1. add `$PWD` (or `--project` argument) to `PYTHONPATH` (this is not done; the script directory gets added to `PYTHONPATH`, regardless of the value of `--project` or `--directory`)
2. run `examples/example1.py`

**Comment by mdengler** [comment]
@charliermarsh sure; I opened #11490.

> > > We now support --project which accepts a path to a directory like this.

> > Can I help to point to some documentation on how to use this? 

> please open a new issue

I asked for help documenting how the new feature was going to be used, though.  Also, the original report does not seem to be resolved with either `--project` or `--directory`:

```
$ mkdir bird-uv-6733-orig
$ cd bird-uv-6733-orig
$ mkdir bird
$ uv init bird
$ echo -e "import bird\nprint(bird.hello())" > bird/main.py
$ uv run bird/main.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733-orig/bird/main.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'
$ uv --project=. run bird/main.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733-orig/bird/main.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'
$ uv --directory=. run bird/main.py
Traceback (most recent call last):
  File "/home/martin/src/bird-uv-6733-orig/bird/main.py", line 1, in <module>
    import bird
ModuleNotFoundError: No module named 'bird'
```


Should this issue be re-opened?  Or could you point me to where in the documentation it describes how to use `--project` to address this (#6733) issue?

**Comment by mdengler** [comment]
Happy to add to documentation.  I was surprised to find no examples of `uv run bird/main.py` that worked, including with `--project=.`.  I'd just like to help avoid other people getting stuck like I did/am.

**Comment by charliermarsh** [comment]
Thanks @mdengler -- I appreciate it. I just find it hard to keep track of outstanding work when there's discussion in closed issues since there's so much activity in the repo. I'm happy to discuss this all in https://github.com/astral-sh/uv/issues/11490!

**Comment by mdengler** [comment]
Understood -- you all are doing tons.  Thanks for `uv` and the great work.
