### ISSUE TITLE
Need to activate venv for nvim to recognize venv

### ISSUE THREAD

**Issue by pdadi74** [astral-sh/uv#6736]
Nvim doesn't recognize venv unless it is explicitly activated. Is this an expected behaviour?

**Comment by zanieb** [comment]
Hi! We'll need way more details to help out here. This sounds like a nvim configuration problem?

**Comment by pdadi74** [comment]
I am using lazyvim config.  code completion doesn't recognize packages I have added. If I activate venv explicitly then it works.  Not sure what other info do you need.

**Comment by jfgordon2** [comment]
@pdadi74 I think this is the default behavior for most IDEs.  Check out [venom](https://github.com/rafi/neoconf-venom.nvim) for automatic venv discovery with python.
