### ISSUE TITLE
`extra-index-url` config parameter works like the `index-url`

### ISSUE THREAD

**Issue by frague59** [astral-sh/uv#6743]
# `pyproject.toml`

```sh
$ cat pyproject.toml
[tool.uv.pip]
extra-index-url = [
    "https://example.com/simple/"
]
```

# `uv venv --seed`

... an error about unable to find / download `pip`,`setuptool` and `wheel`

# Version
```sh
$ uv --version 
uv 0.3.5
```

**Comment by charliermarsh** [comment]
What is the error you're seeing? Do you need `index-strategy = "unsafe-first-match"`?

**Comment by zanieb** [comment]
See https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes for more context.

**Comment by frague59** [comment]
Hi, 

I've read the doc, OK...
