### ISSUE TITLE
List specifier used to install a tool

### ISSUE THREAD

**Issue by paidhi** [astral-sh/uv#6747]
Currently (uv v0.3.5) if a constraint is used with `uv tool install` the version/restriction is pinned and subsequent `uv tool upgrade` commands might not update to a newer release. E.g. `uv tool install "pyinfra<3.0".

Over time I imagine it's easy to forget that a tool was installed this way. And as a result one might start wondering why e.g. `uv tool upgrade --all` misses newer versions for some tools.

I think it would help if the output from `uv tool list` shows what specifier was used to install a tool (which is stored in `$(uv tool dir)/${package_name}/uv-receipt.toml`).

Example (mockup):
```
$ uv tool install "pyinfra<3.0"

$ uv tool list
pyinfra v2.9.2 (specifier: "<3.0")
- pyinfra
```

**Comment by charliermarsh** [comment]
`--show-specifiers` would be fine with me.

**Comment by zanieb** [comment]
We have this as `--show-version-specifiers` in `uv pip tree`

**Comment by paidhi** [comment]
Maybe opt-in as part of a `--verbose` option (`uv tool list -v`).

**Comment by zanieb** [comment]
That's fine with me too.
