### ISSUE TITLE
Duplicate code found in `mkdocs` template file

### ISSUE THREAD

**Issue by Joaopeuko** [astral-sh/uv#6756]
Duplicate code found in `mkdocs` template file

<https://github.com/astral-sh/uv/blob/main/mkdocs.template.yml#L51>

```
  - pymdownx.highlight:
      anchor_linenums: true
```

**Comment by Joaopeuko** [comment]
Thank you, I already did!

https://github.com/astral-sh/uv/pull/6757

**Comment by charliermarsh** [comment]
Thank you!
