### ISSUE TITLE
Unable to use uv tool install for specific versions 

### ISSUE THREAD

**Issue by damienrj** [astral-sh/uv#6759]
```
❯ uv --version
uv 0.3.5 (6c62d9fbf 2024-08-27)
```

OSX

```
❯ uv tool install codecov-cli@0.7.4
error: Failed to parse: `codecov-cli@0.7.4`
  Caused by: Expected path (`/Users/damien/Development/mlkite/0.7.4`) to end in a supported file extension: `.whl`, `.zip`, `.tar.gz`, `.tar.bz2`, `.tar.xz`, or `.tar.zst`
codecov-cli@0.7.4
```

I am trying to install a specific version but get the above error.

**Comment by charliermarsh** [comment]
Ahh, this needs to be `uv tool install codecov-cli==0.7.4`.

Tracked here: https://github.com/astral-sh/uv/issues/6535.

**Comment by charliermarsh** [comment]
We'll do this today, you're not the first to run into it.

**Comment by damienrj** [comment]
Thanks, I didn't find that when I was searching. Great project!
