### ISSUE TITLE
dist-info entry in site-packages for editable install

### ISSUE THREAD

**Issue by letrec** [astral-sh/uv#6793]
`uv pip install -e` creates a dist-info entry in site-packages, which python -m pip does not seem to do.

uv venv --python 3.10 --no-python-downloads --link-mode hardlink
source .venv/bin/activate
uv pip install -e ~/src/my_package

% ls .venv/lib/python3.10/site-packages/ | grep my_package
__editable__.my_package-0.5.0.16.pth
__editable___my_package_0_5_0_16_finder.py
my_package-0.5.0.16.dist-info

% uv --version
uv 0.4.0

% uname -a
24~22.04.1-Ubuntu SMP Thu Jul 18 10:43:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

I don't think it's a wrong behavior, but it's different from what pip does and it confuses Pylance.
The packages is completely functional in Python.

**Comment by charliermarsh** [comment]
I think you need `--config-setting editable_mode=compat` in order to get these working with Pylance.

**Comment by charliermarsh** [comment]
I also chimed in on the Pylance issue.

**Comment by letrec** [comment]
The suggested doesn't seem to work.
When I install my package as `python -m pip install --config-settings editable_mode=compat -e ~/src/package`, Pylance is able to recognize it properly -- imports from it are not higligted as errors and go to definition is able to jump to the underlying code.
But running `uv pip install --config-setting editable_mode=compat -e ~/src/package` results in Pylance reporting 
> Import "package" could not be resolved

I just checked it with uv 0.4.7, pip 24.2 and Pylance v2024.8.2.

**Comment by charliermarsh** [comment]
Did you clear the cache first?

**Comment by letrec** [comment]
The cache of uv?

**Comment by charliermarsh** [comment]
Yeah. If you’ve built the package previously, we may not rebuild it even if you provide a config setting like that (there’s an open PR that fixes this). So just to verify, I’d suggest running with the —reinstall flag.

**Comment by letrec** [comment]
Running `uv cache clean package` didn't seem to help, so I deleted the egg-info dir and run `uv pip install --reinstall --config-setting editable_mode=compat -e ~/src/package` and Pylance is happy now.
Thank you very much!
