### ISSUE TITLE
False positive in warning: uv does not recognize "~" in $PATH

### ISSUE THREAD

**Issue by paravoid** [astral-sh/uv#6802]
uv warns about `/home/$user/.local/bin` not being in my PATH, although `~/.local/bin` is, i.e. not recognizing the tilde.

Demo:
```
$ uv --version
uv 0.4.0

$ echo $SHELL
/bin/bash

$ cat /etc/debian_version 
trixie/sid

$ echo $PATH
~/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

$ uv tool install ruff
Resolved 1 package in 7ms
Installed 1 package in 1ms
 + ruff==0.6.2
Installed 1 executable: ruff
warning: `/home/paravoid/.local/bin` is not on your PATH. To use installed tools, run `export PATH="/home/paravoid/.local/bin:$PATH"` or `uv tool update-shell`.

$ which ruff
/home/paravoid/.local/bin/ruff
```

**Comment by charliermarsh** [comment]
Thanks!

**Comment by charliermarsh** [comment]
Oddly, this doesn't seem to work for me on macOS. Do you know if support here is OS-specific?

**Comment by paravoid** [comment]
I can't imagine this being OS-specific (but I don't know for sure). It may be shell-specific, though: are you using bash or zsh? bash expands the tilde, but zsh does not, AFAIK.

**Comment by charliermarsh** [comment]
Ah yeah, I'm using Zsh. That would explain it.

**Comment by paravoid** [comment]
Thanks so much!
