### ISSUE TITLE
Add an option to `uv run` to run a `.py` script with `pythonw.exe` instead of `python.exe`

### ISSUE THREAD

**Issue by piepero** [astral-sh/uv#6805]
I am using `uv run` for a simple Python script with inline dependencies.

This script is used in two ways/environments.

First, it is run from the console. In this case, it should be run using `python.exe`, thus showing stout/stderr on the console.

Second, the same script is run by the Windows 11 Task Scheduler. In this case, I would like to use the windowless `pythonw.exe` to run the script without opening another window.

Currently, the only way to get `uv run` to choose either one or the other interpreter, is by naming the script either `myscript.py` or `myscript.pyw`.

In other words, I have to maintain two otherwise identical copies of the same script.

There may be workarounds, but the ideas I came up with either did not work (`uv run pythonw myscript.py` does not parse the inline metadata) or were cumbersome and error prone (i.e. using Windows soft or hard links, or importing the `.py` script from a second `.pyw` script and keeping the inline dependencies in sync).

It would be very convenient, if there was an additional flag for `uv run` to instruct `uv` to use `pythonw.exe` on a file with the `.py` extension (e.g. `uv run --pythonw myscript.py`).

**Comment by zanieb** [comment]
We could parse the metadata with `pythonw myscript.py`, I think? Alternatively, we can provide a `--script-exec` option that we use to execute scripts.

**Comment by zanieb** [comment]
We added a `--script` flag in #7739 but we don't have a `--gui-script` flag — which would be Windows-only but reasonable to include, I think.

**Comment by Choudhry18** [comment]
@zanieb I just got interested in the project and was looking at good first issues to start, this issue is still open but after reading the pull request #9152 it seems the issue should be closed.

**Comment by zanieb** [comment]
Yep this is implemented, sorry!
