### ISSUE TITLE
Avoid requiring a README or any module structure

### ISSUE THREAD

**Issue by michaelmior** [astral-sh/uv#6806]
I've experienced this on both macOS and Linux with uv 0.32. `uv init` will create `README.md` and an `src` folder with the skeleton of a module. However, if I don't need either of those with my project, then trying to use `uv run` fails. It would be nice if neither of these were required. It's unclear why the README is necessary. I can see some logic behind requiring the module, but it would be nice to skip over it if it doesn't exist. Sometimes I just want dependency management for a set of scripts then I never intend to redistribute as a package.

**Comment by my1e5** [comment]
Try uv 0.4.0 - there have been many changes. `uv init` now creates a simple script project not a library.

**Comment by charliermarsh** [comment]
Yeah, I believe `uv init --app` should solve this for you!

**Comment by michaelmior** [comment]
@charliermarsh Thanks for the fast reply. uv 0.4.does indeed seem to solve the problem. Specifically, removing the following from my existing `pyproject.toml` resolved the issue.

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
