### ISSUE TITLE
Windows _netrc not recognized for pip auth

### ISSUE THREAD

**Issue by corby** [astral-sh/uv#6809]
I cross compile a python application with lots of C libraries.
uv works fine on *nix based platforms, but on Windows the ~/.netrc file is called ~/_netrc (who knows why)

Copying the ~/_netrc to ~/.netrc fixed uv.
Can we have uv scan for ~/.netrc and fall back to ~/_netrc on windows platform?

**Comment by zanieb** [comment]
Hm I presumed support was added when they did upstream https://github.com/gribouille/netrc/issues/1 but maybe not. We should follow-up here.

**Comment by delreluca** [comment]
I read https://github.com/astral-sh/uv/issues/3471 and after setting the environment variable `HOME` on Windows (to `USERPROFILE`) it works on Windows as well.
