### ISSUE TITLE
Dynamic dependencies in setup.py are not considered when editing dependencies

### ISSUE THREAD

**Issue by AbdealiLoKo** [astral-sh/uv#6822]
Here is a reproducible example in a docker container:
```bash
docker run --rm -it ubuntu:22.04
$ apt update
$ apt install -y curl
$ curl -LsSf https://astral.sh/uv/install.sh | sh
$ echo 'eval "$(uv generate-shell-completion bash)"' >> ~/.bashrc
$ source ~/.bashrc
$ uv init myapp
$ cd myapp
$ echo "babel==2.15.0" > pinned.txt
$ echo -e "from setuptools import setup\nsetup(install_requires=[i.strip() for i in open('pinned.txt', 'r').readlines()])" > setup.py
$ sed -i '/^dependencies/d' pyproject.toml
$ echo 'dynamic = ["dependencies"]' >> pyproject.toml
$ uv venv
$ uv pip install -e .
$ echo "babel==2.16.0" > pinned.txt

$ uv pip install -e . -v
DEBUG uv 0.4.0
DEBUG Searching for Python interpreter in system path
DEBUG Found `cpython-3.12.5-linux-x86_64-gnu` at `/myapp/.venv/bin/python3` (virtual environment)
DEBUG Using Python 3.12.5 environment at .venv/bin/python3
DEBUG Acquired lock for `.venv`
DEBUG Requirement satisfied: babel==2.15.0  <--------------------- This should have been 2.16.0
DEBUG Requirement satisfied: file:///myapp
Audited 1 package in 5ms

$ uv pip tree
myapp v0.1.0
└── babel v2.15.0
```

I expected that the second `uv pip install -e .` should have noticed that the dependencies for `myapp` have changed.
But it looks like it is not.

Seems related: https://github.com/astral-sh/uv/issues/2844

Workarounds I have seen:
- `uv pip install -e . --reinstall`
- `uv clean; uv pip install -e .`

**Comment by charliermarsh** [comment]
You'll need to mark your package as requiring reinstallation if you want it to be reinstalled on every operation. This is documented here: https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata.

**Comment by AbdealiLoKo** [comment]
Sighs ... not sure how I missed that in the documentation !
Thanks for the pointer, I'll read it and try it out !

**Comment by AbdealiLoKo** [comment]
@charliermarsh was thinking about this a bit more ... is there any benefit of making a heuristic here that if a package is being installed from a local path + The package has dynamic fields in pyproject.toml -- uv would automatically reinstall it in every operation to be safe ?

1. Local path - I assume uv already has this information
2. Dynamic fields - If the [project.dynamic](https://peps.python.org/pep-0621/#dynamic) field is defined in pyproject.toml then we know if has dynamic fields ?

**Comment by charliermarsh** [comment]
We have a new API whereby you can add additional files to consider when invalidating the cache. You can also include the current Git commit (i.e., invalidate whenever the SHA changes).

Looks like this:

```toml
[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "requirements.txt" }, { git = true }]
```

See: https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata.
