### ISSUE TITLE
uv fails to compile proper `--universal` txt file with `openai-whisper`

### ISSUE THREAD

**Issue by stasbel** [astral-sh/uv#6852]
**platform: macos**
**version: 0.4.0**

openai-whisper has following dependency:
```
triton>=2.0.0,<3;platform_machine=="x86_64" and sys_platform=="linux" or sys_platform=="linux2"
```
however, running `uv pip compile` with `--universal` on macos does't preserve platform tags
what you can see in the output is plain:
```
triton==2.0.0
```
this results in inability to install packages on macos

**Comment by charliermarsh** [comment]
Do you mind including the full command you ran to reproduce?

**Comment by stasbel** [comment]
sure

**reqs.in**
```
openai-whisper==20231117
```

**command**
```
uv pip compile --no-strip-extras --universal reqs.in -o reqs.txt
```

**Comment by stasbel** [comment]
if I insert platform tags manually after, everything works fine :)

**Comment by charliermarsh** [comment]
I think this is an issue with `openai-whisper`. See: https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/setup.py#L15, which does:

```python
requirements = []
if sys.platform.startswith("linux") and platform.machine() == "x86_64":
    requirements.append("triton>=2.0.0,<3")
```

They should apply those constraints as environment markers, they shouldn't depend on the host machine... I can file a PR.

**Comment by charliermarsh** [comment]
Actually confused because that variable isn't even used.

**Comment by charliermarsh** [comment]
Ah ok, unfortunately this change is unreleased: https://github.com/openai/whisper/pull/1887. You'll have to use:

```
openai-whisper @ git+https://github.com/openai/whisper.git@ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab
```

In order to access it.
