### ISSUE TITLE
Buggy interplay between `--python`, `--python-version` and dependency with Python upper bound in `pip compile`

### ISSUE THREAD

**Issue by BarrensZeppelin** [astral-sh/uv#6859]
I use uv@0.4.0 to `pip compile` the dependency specifier `scipy==1.9.0`.
`scipy==1.9.0` has a Python version requirement of `>=3.8,<3.12`.

The command I'm running is
`echo "scipy==1.9.0" | uv pip compile --python X.Y --python-version X.Y [--universal] -`

When the command fails, the error message is always:
```
  × No solution found when resolving dependencies:
  ╰─▶ Because the current Python version (3.12.5) does not satisfy Python>=3.8,<3.12 and scipy==1.9.0 depends on Python>=3.8,<3.12, we can
      conclude that scipy==1.9.0 cannot be used.
      And because you require scipy==1.9.0, we can conclude that your requirements are unsatisfiable.
```

I've compiled a table of results with different combinations of `--python` and `--python-version` arguments + `--universal` mode.

| --python | --python-version | --universal | Success | Expected |
|----------|------------------|-------------|---------|----------|
| 3.12     | 3.12             | X           | X       | ✓        |
| 3.12     | 3.11             | X           | X       | X        |
| 3.12     | 3.10             | X           | ✓       | ✓        |
| 3.11     | 3.12             | X           | X       | ✓        |
| 3.11     | 3.11             | X           | ✓       | ✓        |
| 3.12     | 3.12             | ✓           | X       | ✓        |
| 3.12     | 3.11             | ✓           | X       | X        |
| 3.12     | 3.10             | ✓           | ✓       | ✓        |
| 3.11     | 3.12             | ✓           | ✓       | ?        |
| 3.11     | 3.11             | ✓           | ✓       | ✓        | 

There are two failures that definitely look unexpected to me.
I'm not certain whether `--python 3.11 --python-version 3.12 --universal` is expected to succeed.
Also, I had the impression that python version upper bounds were ignored (in `--universal` mode?), so maybe some of the cases I marked as expected failures are actually unexpected.

**Comment by charliermarsh** [comment]
I believe that Python version upper-bounds being ignored is true in `uv lock` but not yet in `uv pip compile`, for somewhat historical reasons.

**Comment by BarrensZeppelin** [comment]
Alright. It would be useful (for me) to have that behaviour in `uv pip compile` (possibly behind a flag?).

**Comment by charliermarsh** [comment]
I think we just need to change it. There's an open issue somewhere... I may be able to do it today.

**Comment by charliermarsh** [comment]
https://github.com/astral-sh/uv/issues/5045

**Comment by BarrensZeppelin** [comment]
Right. I actually found that issue earlier, but found that the universal resolver also fails to resolve the dependency tree.

**Comment by charliermarsh** [comment]
I think this actually might be a separate problem, which is that we're refusing _source_ distributions based on the upper-bound because we assume we can't build them. I don't think we should be doing that.

**Comment by charliermarsh** [comment]
Ok, I've confirmed this works in https://github.com/astral-sh/uv/pull/6882:

```
# This file was autogenerated by uv via the following command:
#    uv pip compile --python 3.12 --python-version 3.12 --universal -
numpy==1.24.4
    # via scipy
scipy==1.9.0
```

I don't think it will ship today, but in the next few days.

**Comment by BarrensZeppelin** [comment]
Very nice! 🥳
