### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by dbohdan** [astral-sh/uv#6861]
Could you enable GitHub Discussions like you have [for Ruff](https://github.com/astral-sh/ruff/discussions)?

**Comment by zanieb** [comment]
I'm not sure — issues seem to be working fine for us here right now. What's your reasoning?

**Comment by dbohdan** [comment]
What I like about Discussions is "show and tell", where people present their work related to the project. I think [Djot](https://github.com/jgm/djot/discussions/categories/show-and-tell) is a great example of how "show and tell" can generate value. It has let the followers of the project discover things they are interested in, like integrations and implementations.

For uv, there is something I'd share in "show and tell". I have [benchmarked uv](https://dbohdan.com/scripts-with-dependencies#python-comparison) against other script runners that download dependencies. It is the fastest that implements PEP 723.

If Discussions fit poorly with your workflow, maybe you could create a single issue for "show and tell"?

**Comment by zanieb** [comment]
Thanks for sharing your use case! We'll chat about this internally and see if we feel like it makes sense for us right now. A pinned "Show and tell" issue seems like a reasonable alternative too.
