### ISSUE TITLE
Running `uv pip compile` with `--find-links` pointing towards a local wheel does not produce the expected output

### ISSUE THREAD

**Issue by williamglasse** [astral-sh/uv#6876]
Hello!

Unsure whether this is a bug, or I could be misusing uv!

I'm trying to migrate over from pip-tools to using UV instead. I've got a local wheel that I'd like to install, that lives within my repository as a .whl file. In pip-compile world, I'd run `pip-compile --find-links=./local_wheels --output-file=requirements.txt pyproject.toml` and this generated a requirements.txt file. The resultant requirement.txt file would contain `--find-links ./local_wheels` at the top of the file. This would mean that when I run pip-sync, it would make use of wheels found within the /local_wheels directory

I expected `uv pip compile --find-links ./local_wheels --output-file=requirements.txt pyproject.toml` to return a similar output to requirements.txt, but it doesn't have the expected `--find-links ./local_wheels` in the autogenerated output

Am I missing something or is this a bug?

**Comment by charliermarsh** [comment]
I think you can pass `--emit-find-links` to include them (we just don't do it by default).

**Comment by charliermarsh** [comment]
It's mentioned here for index URLs, but I should probably add a reference to `--emit-find-links` to help with search: https://docs.astral.sh/uv/pip/compatibility/#pip-compile-defaults

**Comment by williamglasse** [comment]
> It's mentioned here for index URLs, but I should probably add a reference to `--emit-find-links` to help with search: https://docs.astral.sh/uv/pip/compatibility/#pip-compile-defaults

Thank you @charliermarsh that was what I was looking for! Thank you for such a speedy response.

Out of interest, I have another issue, where for some reason setuptools is being added to requirements.txt, whereas it wasn't before. Is there another flag I'm missing that will make uv behave similar to how pip-tools was?

**Comment by charliermarsh** [comment]
You could add `--no-emit-package setuptools`. I think `pip-compile` may omit it by default right now? But IIRC that's being removed in future versions of `pip-tools`.

**Comment by charliermarsh** [comment]
You should be able to set these things in your `pyproject.toml` if you want:

```toml
[tool.uv.pip]
emit-find-links = true
no-emit-package = ["setuptools"]
```

(Something like that -- didn't test it before writing :))

**Comment by williamglasse** [comment]
A big thank you @charliermarsh, that is exactly what I needed! Thank you for solving both of my issues, I had started going around in circles, so much appreciated <3

**Comment by charliermarsh** [comment]
No prob! I can add some things to the compatibility guide so it's easier to reference in the future.
