### ISSUE TITLE
uv pip install fails while pip install success

### ISSUE THREAD

**Issue by rakeshksr** [astral-sh/uv#6892]
`uv pip install unstructured[pdf]` fails with following error
```
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: pycrypto==2.6.1
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit code: 1
```
`pip install unstructured[pdf]` success without error.

After some debugging found that issue caused by two packages `unstructured-inference` and `pdfminer.six`

### Steps to Reproduce:
1. `uv venv`
2. `.venv\Scripts\activate`
3. `uv pip install pdfminer.six unstructured-inference`

It's strange that installing packages individually( `uv pip install pdfminer.six; uv pip install unstructured-inference`) working fine.

**uv platform:** Windows 11
**uv version:** uv 0.4.1 (823f23e22 2024-08-30)

**Comment by charliermarsh** [comment]
Have you seen this behavior repeatedly?

**Comment by rakeshksr** [comment]
Yes, I have tested in different windows machines.

**Comment by dhofstetter** [comment]
can confirm that with uv version `0.4.6` something has changed, so that uv now wants to build pycrypto wheel (and considers it as being an explicit dependency!) but I have no deps requiring pycrypto.

Is there a way to figure out why uv wants to install a certain package?

**Comment by charliermarsh** [comment]
Can you share the output with `--verbose`? That will tell us exactly why it's being included.

**Comment by dhofstetter** [comment]
hmm good to know, I got the dependency that requires pycrypto now

And there it is indeed a direct dependency. Im just uncertain, why this dependency `jose` is within my project.

**Comment by charliermarsh** [comment]
I think this is all reasonable behavior... The difference is that if you run `uv pip install pdfminer.six`, then `uv pip install unstructured-inference`, we end up _downgrading_ `pdfminer.six`:

```
 - pdfminer-six==20240706
 + pdfminer-six==20231228
```

Whereas if you run `uv pip install pdfminer.six unstructured-inference`, we prefer using a more recent `pdfminer.six` and a less recent transitive dependency (`pdfplumber`). Both are completely valid resolutions.

If you specifically want to avoid using an old `pdfplumber`, you should add a constraint for `pdfplumber>0.6` or similar. You need to give more information to the resolver if you want and are expecting a specific outcome like that.

**Comment by rakeshksr** [comment]
@charliermarsh  thanks for information.
