### ISSUE TITLE
Failed to fetch wheel: pystemmer==2.2.0.1

### ISSUE THREAD

**Issue by sadaisystems** [astral-sh/uv#6897]
Hello! I've recently started experiencing issue when installing `fastembed` package. Seems like it depends on `pystemmer` library, which has some problems with building in `uv`. 

Trace:

```bash
❯ uv add fastembed-haystack
Resolved 181 packages in 76ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: pystemmer==2.2.0.1
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
running build_ext
skipping 'src/Stemmer.c' Cython extension (up-to-date)
building 'Stemmer' extension
clang -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fPIC -fPIC -Ilibstemmer_c-2.2.0/include -I/home/magnesium/.cache/uv/builds-v0/.tmpR7wWFl/include -I/home/magnesium/.local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/include/python3.12 -c libstemmer_c-2.2.0/libstemmer/libstemmer_utf8.c -o build/temp.linux-x86_64-cpython-312/libstemmer_c-2.2.0/libstemmer/libstemmer_utf8.o
--- stderr:
error: command 'clang' failed: No such file or directory
---
```

Any ideas how to fix it? Also fails with `uv pip install`.

uv version: 0.4.0.
platform: WSL2
python: 3.12.5, also fails on 3.11.9, 3.11.6, and seems like all 3.11+???

Why am I assuming that it might be related to `uv` specifically: I was able to install and build the same packages in `pyenv 3.12.0b4`.

UPD: Full logs: [log.txt](https://github.com/user-attachments/files/16825770/log.txt).

UPD2: was able to install on python 3.10.12 (`uv`).

UPD3:  Was able to install on 3.12.5. I just installed pip using uv pip install pip and then added my dependency:

```bash
uv pip install pip # in case you dont have regular pip in your env
pip install pystemmer
uv add fastembed-haystack
```

Question: are there more elegant solutions, and how can i avoid doing those workarounds and just install normally in the future?

UPD4: Got a response in pystemmer github. Apparently, when you directly specify that you want to use a `gcc` instead of clang as a compiler during installing this package using regular uv means, it works:

```bash
CC=gcc-11 uv pip install pystemmer # or
CC=gcc-11 uv add fastembed-haystack
```

Is there a way to use gcc by default (instead of clang)?

**Comment by charliermarsh** [comment]
I think this is likely necessary since the Pythons we use use clang by default.

**Comment by sadaisystems** [comment]
Yeah, seems like that! I think the issue can be considered resolved. However, IMO it would be nice to have an option to choose default compiler used in uv without environment variables.
