### ISSUE TITLE
uv python install with configurable installation path

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#6906]
Context: 
Any pypy install fails on Windows on paths that contain non ascii characters as noted here https://github.com/pypy/pypy/issues/5000 

So when I do 

```
$ uv run --python pypy -- python --version
error: Querying Python at `C:\Users\JoãoBernardoOliveira\AppData\Roaming\uv\data\python\pypy-3.10.14-windows-x86_64-none\python.exe` failed with exit status exit code: 1
--- stdout:

--- stderr:
ModuleNotFoundError: No module named 'encodings'
debug: OperationError:
debug:  operror-type: ModuleNotFoundError
debug:  operror-value: No module named 'encodings'
---
```
Notice the tilde in the username (this is an account provided by a MS account which does not allow me to pick the actual username).

Since the run command is auto downloading pypy just for the 1st time, it is not the best place to have this config. So my suggestion is something like:

```
$ uv python install pypy@3.10 --path C:\uv\
```

UV will need to be able to find these installs in custom places which could be tricky

**Comment by charliermarsh** [comment]
I believe `UV_PYTHON_INSTALL_DIR` works for this -- any issues using that?

**Comment by inoa-jboliveira** [comment]
Sorry, I just searched for config options and could not find one.
It does work, thank you.

Please close this issue

**Comment by charliermarsh** [comment]
Thanks for following up, no prob!
