### ISSUE TITLE
Two-step cache clean and prune needed to remove package from cache

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#6909]
Removing a big package like torch or similar requires both cache clean and prune to remove it from cache. It's expected that the first clean would remove it?

```shell
uv cache clean triton
# Removed 3 files for triton (1.5KiB)
uv cache prune
# Pruning cache at: 
# Removed 316 files (553.1MiB)

uv cache clean nvidia-cudnn-cu11
# Removed 3 files for nvidia-cudnn-cu11 (1.2KiB)
uv cache prune
# Pruning cache at: 
# Removed 31 files (974.5MiB)
```

The packages were installed like in #6907

We can also try with another package like hatch

```shell
uvx hatch
uv cache clean hatch
# Removed 4 files for hatch (61.7KiB)
uv cache prune
# Pruning cache at: 
# Removed 1848 files (79.6MiB)
```

Using uv 0.4.1

**Comment by charliermarsh** [comment]
No this shouldn't be required. It looks like a bug.

**Comment by charliermarsh** [comment]
Should be fixed in the linked PR.

**Comment by charliermarsh** [comment]
Sorry, it was but what you’re seeing isn’t the same thing. We remove all ephemeral environments when you prune. That will also remove other dependencies besides hatch.
