### ISSUE TITLE
Failed to run on Windows 7. Please, remove support for Python v3.8. Because Python v3.8 still supports Windows 7

### ISSUE THREAD

**Issue by GaneJ** [astral-sh/uv#6928]
Started from version 0.1.40, uv failed to run on Windows 7.

This is because the import "ProcessPrng" in bcryptprimitives.dll is missing in Windows 7 (uv.exe and uvx.exe).

![UV_Combine](https://github.com/user-attachments/assets/e76483ed-40bd-4678-8dbb-ee8057493e59)

![UVX_Combine](https://github.com/user-attachments/assets/70a73d2b-92e9-443e-8ac9-78b0bfa68dd7)

That function is only available in Windows 10 and above.

Since Python v3.8 still supports Windows 7, uv has to drop Python v3.8 support.

Thanks.

Note:
I got uv from [https://pypi.org/](https://pypi.org/)

**Comment by mitsuhiko** [comment]
Rust would require a separate build for windows 7 if that is still intended to be supported: https://github.com/rust-lang/rust/pull/121337

**Comment by charliermarsh** [comment]
> Since Python v3.8 still supports Windows 7, uv has to drop Python v3.8 support.

I don't think this is quite right. We support Python 3.8, but that doesn't mean we have to support all of the platforms it runs on. We have a separate platform support policy (https://docs.astral.sh/uv/reference/platforms/) which states that Windows 10 is our minimum supported version.
