### ISSUE TITLE
Option to stop `uv self update` from adding `. $HOME/.local/share/cargo/env`?

### ISSUE THREAD

**Issue by baggiponte** [astral-sh/uv#6932]
Ciao! With rust on my machine already, my shell already sources the `cargo/env` script. Every time that I upgrade uv to a newer version with `uv self update`, the line is added to my zshrc and fish conf dir (which I do not use). This is absolutely nothing high priority, but I was wondering if you would consider setting an option to disable this behaviour.

**Comment by AbdealiLoKo** [comment]
I think you may be looking for `--no-modify-path` ?

**Comment by baggiponte** [comment]
> I think you may be looking for `--no-modify-path` ?

Interesting. I don't see it as an option for `uv self update` though.

**Comment by tpgillam** [comment]
Seconded - I upgraded from `uv` 0.4.3 -> 0.4.4 just now with `uv self update`, and it appended `~/.bashrc` with:
```

. "$HOME/.cargo/env"
```

I would certainly prefer if the `self update` command by default did not modify any configuration files. My reasoning is that, if updating, the user has presumably already set their paths in the way that they want (in my case I want my `.bashrc` portable between different machines, so I don't put any paths directly in that file).

Only a small niggle though. I just have to do a `git restore` on it every time I upgrade, which is mildly inconvenient at worst!

**Comment by baggiponte** [comment]
Maybe one could do `uv self update --ensurepath` or a flag like that and have this behaviour to be opt-in.

**Comment by zanieb** [comment]
Looking into upstream support for this — I don't think we can add it until they do.

**Comment by zanieb** [comment]
Can you try setting `INSTALLER_NO_MODIFY_PATH=1` during the update?

**Comment by tpgillam** [comment]
I'm on a different machine today (Fedora 39), where it doesn't try to modify `~/.bashrc`, but instead creates or modifies `~/.profile`

> Can you try setting INSTALLER_NO_MODIFY_PATH=1 during the update?

Yes - this seems to do the trick (installed 0.4.4 and tested on `uv self upgrade` thereafter).

**Comment by zanieb** [comment]
Great — we can document that.

**Comment by baggiponte** [comment]
Confirm too, setting `INSTALLER_NO_MODIFY_PATH=1` works :)
