### ISSUE TITLE
"Why is it fast" documentation

### ISSUE THREAD

**Issue by valentincalomme** [astral-sh/uv#6936]
I've been trying to track down some info related to "why is uv" faster than `pip` and I was somehow successful. I found that this is often the first question I get when I mention `uv` to people. I say "it's faster than `pip`" and people say "yeah, but how, you're still downloading the same stuff?".

I would find it extremely helpful to have some section explaining the performance gains.

Obviously, no need to delve into `rust`-specific optimization or even internal secrets, but I think it would be great to have some sort of blog-like section explaining why `uv` works as fast as it does

**Comment by zanieb** [comment]
I think this probably makes more sense as a blog post than documentation that we maintain, but yeah it'd be cool to write! cc @konstin who did some work on this previously.

**Comment by charliermarsh** [comment]
I'm also giving two talks on this over the next two months, which will be public and recorded.

**Comment by timotk** [comment]
Here's one of the talks: https://www.youtube.com/watch?v=gSKTfG1GXYQ

Thanks Charlie!

**Comment by charliermarsh** [comment]
Here's the other: https://www.youtube.com/watch?v=zOY9mc-zRxk. I think I'll close this for now!
