### ISSUE TITLE
Question: Does `uv` support multiple environements?

### ISSUE THREAD

**Issue by asmith26** [astral-sh/uv#6942]
Hi there,

Just wondering, does `uv` support multiple environments (I see I can specify "application dependencies" and "dev dependencies", but could I e.g. create an env for "cpu" and another for "gpu")?

Many thanks for any help, and for this lib!

**Comment by zanieb** [comment]
No we don't have multiple environment support right now — the closest is probably to use different groups of `optional-dependencies`.

**Comment by asmith26** [comment]
Thanks for your help and info @zanieb

**Comment by ameya98** [comment]
Sorry for re-opening this, but is this still the case? If I want two environments in the same folder, I get this error: 
```bash
warning: `VIRTUAL_ENV=.venv-analysis` does not match the project environment path `.venv` and will be ignored
```
which doesn't make a lot of sense to me.

**Comment by renardeinside** [comment]
Hi @zanieb , 
`hatch` provides quite a convenient way to actually separate envrionments, not just groups. 

This might be useful in scenarios when packages are incompatible and you need to use a couple of envs, or when you want cross-python testing. Would you consider this feature in future?

**Comment by sohang3112** [comment]
@asmith26 Is there any way currently to have multiple environments (eg. gpu, cpu) in the same folder? If not, this issue should be re-opened - this is a very common use case.

**Comment by konstin** [comment]
@adrianloy While uv does not support multiple environments, it has support for declaring [conflicting dependencies](https://docs.astral.sh/uv/concepts/projects/config/#conflicting-dependencies).

**Comment by sohang3112** [comment]
>While uv does not support multiple environments, it has support for declaring [conflicting dependencies](https://docs.astral.sh/uv/concepts/projects/config/#conflicting-dependencies).

@konstin That sounds useful!
