### ISSUE TITLE
[Question] Why not publish it on crateio?

### ISSUE THREAD

**Issue by chatblanc-ciel** [astral-sh/uv#6956]
I usually use the Rust language as my primary programming language. Therefore, I prefer to install via cargo rather than the standalone installer.

- Easy to install
  ```
   cargo install uv
  ```
- Easy to manage
  ```
  cargo uninstall uv
  ```

Would you please consider this?

**Comment by eth3lbert** [comment]
I believe this is the same as https://github.com/astral-sh/uv/issues/6310.

**Comment by chatblanc-ciel** [comment]
@eth3lbert 
Thank you for your quick reply.

I can't find this issue and it solves my question.
Thank you.
