### ISSUE TITLE
Feature:  have 'uv export' support --only-deps

### ISSUE THREAD

**Issue by RomainBrault** [astral-sh/uv#6960]
Have `uv export` support `--only-deps`

This would be useful to support building `requirements.txt` from `uv.lock` without including build dependencies.

Example: in a `Dockerfile` with a custom hatch build the following fails:

```dockerfile
COPY pyproject.toml ./
RUN set -ex && \
    ${UV_BIN}/uv export \
        --format="requirements-txt" \
        --all-extras \
        --no-dev
```

So I must do

```dockerfile
COPY pyproject.toml hatch.toml hatch_build.py ./
RUN set -ex && \
    ${UV_BIN}/uv export \
        --format="requirements-txt" \
        --all-extras \
        --no-dev
```

It would be nice to be able to have

```dockerfile
COPY pyproject.toml ./
RUN set -ex && \
    ${UV_BIN}/uv export \
        --format="requirements-txt" \
        --all-extras \
        --no-dev \
        --only-deps
```
working.

This would also enable doing

```shell
uv pip install --require-hashes
```

without `uv` complaining about

```bash
error: In `--require-hashes` mode, all requirement must have a hash, but none were provided for: file:///src
```

**Comment by RomainBrault** [comment]
Related: #6573

**Comment by charliermarsh** [comment]
Do you need `--frozen` for these commands, so that you don't resolve?

**Comment by charliermarsh** [comment]
In other words: if you add `--frozen` to the above examples, do the commands execute without error?

**Comment by RomainBrault** [comment]
Thanks, this solve the build problem; with `--frozen` I am able to generate the `requirements.txt` from the `uv.lock`. 

However I am unable to `pip install --require-hashes` due to the line -e .` in the `requirements.txt`.

A solution is to remove the line in a post-processing step. A flag to avoid this line would still be useful as well as a flag to save the result to a file. (This would avoid post-processing and stream redirections).

**Comment by RomainBrault** [comment]
Related: #6995
