### ISSUE TITLE
`uv` fails to retrieve right version with `setuptools_scm` in clone after new release

### ISSUE THREAD

**Issue by lkstrp** [astral-sh/uv#6964]
When a package uses [setuptools-scm](https://github.com/pypa/setuptools-scm), the version is not correctly retrieved if reinstalling in editable mode after new release.

`uv 0.4.3 (Homebrew 2024-09-02)` on macOS

**Example**
Let's take the [PyPSA](https://github.com/pypsa/pypsa) package for example.
Works fine initially and retrieves correct version (`0.30.0.post1.dev2+g191bea7c` currently):
``` bash
git clone https://github.com/PyPSA/PyPSA.git
cd PyPSA
uv venv
uv pip install -e .
```

But when coming back to the repo at a later stage after a new release  (let's say `0.30.1` as an example)
``` bash
git pull --tags
> From https://github.com/PyPSA/PyPSA
> * [new tag]           v0.30.1    -> v0.30.1
``` 
uv will not retrieve the new version (`v0.30.1`) but will just add a new dev version to the previous one (e.g. `v0.30.0.post1.devx+x`). 

You have to remove the env and install without cache to retrieve the correct version again. Just deleting the env or just ignoring the cache will not work.
``` bash
rm -r .venv
uv venv
uv pip install -e . -n
```

While `pip` installs the correct version immediately, without ignoring the cache or creating a new environment.

This is a made up case. To reproduce you need a cloned repo with the package installed and wait for a new release to see the behavior.

**Comment by charliermarsh** [comment]
It sounds like you're working with a package with dynamic metadata? If you want it to be reinstalled, you should mark it as such via `reinstall-package`: https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata. We cache local source trees based on the `pyproject.toml`.

**Comment by lkstrp** [comment]
I see, thanks! 
Isn't it a bit counterintuitive that local editables need to be uncached and explicitly reinstalled to update their dynamic metadata? I guess you have your reasons and it makes sense with the aggressive caching. But only after reading [Caching | uv](https://docs.astral.sh/uv/concepts/cache/) and `pip` is behaving very differently. 

To get the same behaviour of `pip install -e .`, I need to run
```
uv pip install -e . -n --reinstall-package package_name
```

**Comment by charliermarsh** [comment]
It's a tradeoff but non-dynamic, non-extension modules never need to be rebuilt, and unfortunately we can't reliably know when a local editable with dynamic metadata would need to be rebuilt. We have commands like `uv run` that automatically keep the user's environment in-sync with their dependencies, without the need to explicitly lock, sync, or activate an environment. If we always rebuilt dynamic modules in that context, you'd get a rebuild on every command, so we made the decision to require explicit opt-in for rebuilds.

**Comment by charliermarsh** [comment]
There's an interesting suggestion here (#6255) to allow users to mark certain files as part of the cache key (e.g., if they read from `requirements.txt`); we could probably also extend that to reading from Git.

**Comment by charliermarsh** [comment]
In v0.4.8, you can do the following to invalidate the cache on commit:

```toml
[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = true }]
```

**Comment by lkstrp** [comment]
Thanks for tackling this so quickly!
