### ISSUE TITLE
uv can't find commands within virtualenv until executed once with uv run <command>

### ISSUE THREAD

**Issue by klaytron** [astral-sh/uv#6967]
When invoking a command (.e.g. `pytest`) within a uv venv, the command is not found until first run with the explicit `uv run <command>` one time, at which point the package installations take place, and running commands with the venv without `uv run` works.

DESIRED: package installations already take place upon creating or entering the venv.

```
$ curl -LsSf https://astral.sh/uv/install.sh | sh
downloading uv 0.4.3 x86_64-unknown-linux-gnu
installing to /home/clayton/.cargo/bin
  uv
  uvx
everything's installed!

$ uv sync --frozen
Audited 94 packages in 0.19ms

$ uv venv
Using Python 3.12.3 interpreter at: /usr/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
$ source .venv/bin/activate

(venv) $ pytest
Command 'pytest' not found, but can be installed with:
sudo apt install python3-pytest

(venv) $ uv run pytest
Installed 94 packages in 41ms
# pytest output

(venv) $ pytest
# pytest output
```

platform linux -- Python 3.12.3
uv 0.4.3

**Comment by charliermarsh** [comment]
`uv venv` replaces the virtual environment that was created by `uv sync`.

**Comment by charliermarsh** [comment]
(You should remove `uv venv` from the above and just activate it.)

**Comment by klaytron** [comment]
thank you for quick reply!
