### ISSUE TITLE
Allow conflicting optional dependencies and dependency groups

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#6981]
A project should be able to declare mutually exclusive optional dependencies, which have conflicting requirements and are solved separately.

This problem is challenging because if any optional dependency group can be incompatible with any other group, we need to perform a resolution for every possible dependency group combination.

Note, following the recent standardization of local dependency groups, this issue includes allowing conflicts in those as well. The underlying changes that need to happen in the resolver are the same.

See also https://github.com/astral-sh/uv/issues/6729

**Comment by WelanderJacob** [comment]
We're currently adopting uv in our company and recently encountered this issue. I was wondering if there are any updates or timeline on when this feature might be addressed? It would be really valuable for us.

Anyway, thanks for all the fantastic work on uv!

**Comment by zanieb** [comment]
We're working on this now, but we consider it a difficult / high risk problem so I'm not sure when we'll have a solution.

**Comment by zanieb** [comment]
@BurntSushi since this tracks dependency groups as well, I've reopened it.

**Comment by Ben-grmbl** [comment]
To anyone arriving here from google, this was implemented, [here is the documentation ](https://docs.astral.sh/uv/concepts/projects/config/#conflicting-dependencies) on how to use it
