### ISSUE TITLE
Undocumented change to workspaces?

### ISSUE THREAD

**Issue by brynbellomy** [astral-sh/uv#6993]
I followed the workspaces documentation with versions 0.4.3 and 0.4.4, and it seems that importing modules from the same workspace is broken (perhaps only for certain directory structures?) in recent versions, whereas 0.3.5 worked exactly as expected.

```
- rootdir/
    - pyproject.toml (has tool.uv.workspace.members which contains 'common' and 'thing')
    - libs/
        - common/
            - pyproject.toml
            - src/
                - common/
                    - __init__.py etc
    - services/
        - thing/
            - pyproject.toml (has tool.uv.sources with common = {workspace = true})
            - some_script.py
```

`some_script.py`:
```python
import foo from common
```

command: `uv run --refresh --package=thing services/thing/some_script.py`
- v0.4.x: Module common not found
- v0.3.5: works

I've been clearing the cache at every step of the investigation, deleting `uv.lock`, re-running `uv sync`, and also using the `--refresh` flag when calling `uv run`.

One last interesting tidbit.  When I switch from 0.3.5 back up to 0.4.4, clean the cache, delete the lockfile, and then run `uv sync --package=thing`, it deletes the `common` dependency.  So for some reason, it's not even recognizing it as a dependency despite it being in the `dependencies` array, and also having a `tool.uv.sources` callout.

It looks like there were significant changes at 0.4.0, so maybe something fundamental regressed there.  I read through changelogs and docs and couldn't get to the bottom of it, though.

**Comment by charliermarsh** [comment]
Is `common` declared as a dependency in `rootdir/services/thing/pyproject.toml`? Or only at the root?

**Comment by charliermarsh** [comment]
If you can help put together a small reproducible example I'm happy to help.

**Comment by brynbellomy** [comment]
It's declared a dependency only on the leaf, not the root.  Would making it one at the root help?  And sure, I can try to put together a reproducible example.

**Comment by charliermarsh** [comment]
Yeah I would only expect it to be declared as a dependency in `rootdir/services/thing/pyproject.toml`, and not in the root -- so that sounds right. Was just a guess. A small reproducible example would help a ton, thanks.
