### ISSUE TITLE
How to configure a script path? 

### ISSUE THREAD

**Issue by TiansuYu** [astral-sh/uv#6998]
I am building a CLI tool and tries to bind the script path to cli name. e.g. in Poetry this is https://python-poetry.org/docs/pyproject/#scripts. However, I could not find any instructions on how to do this in UV. Could you enlighten me please?

**Comment by bwt-sloanj** [comment]
With uv this can just be done via the normal `[project]` table in the `pyproject.toml` file. https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts

**Comment by TiansuYu** [comment]
I have a project that i want to add a script entrypoint to run `src/xyz/main.py:main` (`main()` function inside `src/xyz/main.py`), and my section in `pyproject.toml` looks like this
```toml
[project.scripts]
xyz = "src.xyz.main:main"
```
`uv` errors out with 
```shell
-> % uv run xyz
error: Failed to spawn: `xyz`
  Caused by: No such file or directory (os error 2)
```
The error messages looks a bit cryptic for me to understand how have I configured the path wrong.

**Comment by zanieb** [comment]
Do you have a `[build-system]` defined for your project?
