### ISSUE TITLE
"Project API" equivalent to `uv pip list`?

### ISSUE THREAD

**Issue by matterhorn103** [astral-sh/uv#7006]
Maybe I am the only one who ever does this, but especially when it comes to non-package projects I often like to reassess the dependencies of my project.

At the moment this can be done with `uv pip list`, but that a) shows the *currently installed* packages, not the dependencies as listed in `uv.lock` or `pyproject.toml`, and therefore b) doesn't show the constraints that are placed on the dependencies but rather the currently installed versions, and c) is part of the pip compatibility API.

Naturally just inspecting `pyproject.toml` is an option, but that kind of argument could be used to argue against the need for `uv add`/`uv remove` as well.

Is an equivalent `uv list` or something planned for the "project" API? Or should I expect to continue using `uv pip list` for the foreseeable future?

(It is of course also common to use `pip list` with flags for other purposes like [checking for outdated packages](https://github.com/astral-sh/uv/issues/2150).)

---

By the way, just wanted to at the same time express my gratitude for the changes you introduced in uv 0.4! Having first-class support for non-package projects in this way, along with workspaces, has really improved its usability for scientific work, really makes uv stand out as a potentially universal tool, and it is really appreciated that you focussed on such use-cases even before the initial stable release. :)

**Comment by matterhorn103** [comment]
Related to the actual use-case I alluded to, of trimming down dependencies that are no longer needed by the project, would it be an idea to have some kind of functionality to audit a project for unused dependencies? Thought I'd ask here before spamming you with another issue.

**Comment by charliermarsh** [comment]
Have you tried `uv tree`?

**Comment by matterhorn103** [comment]
Ah, no, I hadn't, I guess I overlooked it cause of the name difference. `uv tree` gives a really nice overview! Far more useful than `pip list`.

So I guess in part that answers my original question, if `uv tree` is the intended analogue to `uv pip list`. 

But some way to display the list of dependencies as recorded in `pyproject.toml`/produced by the use of `uv add` would be nice though don't you think?

And as far as I can see none of the options of `uv tree` provide filtering by outdated or unused, right? Might these be future options, or are they out-of-scope for `uv tree`?

**Comment by charliermarsh** [comment]
Closing for now, I believe outdated is tracked elsewhere.
