### ISSUE TITLE
`uv` shouldn't modify `pyproject.toml` on failed install

### ISSUE THREAD

**Issue by kdheepak** [astral-sh/uv#7011]
I ran the following:

```
$ uv add dsfkdsjfldskfjds
error: Request failed after 3 retries
  Caused by: error sending request for url (https://pypi.org/simple/dsfkdsjfldskfjds/)
  Caused by: client error (Connect)
  Caused by: invalid peer certificate: UnknownIssuer
````

But that resulted in a change to `pyproject.toml`:

<img width="867" alt="image" src="https://github.com/user-attachments/assets/8cec1411-f244-4e53-a89e-92cd2e635273">

**Comment by kdheepak** [comment]
This seems to happen only if there's a certificate failure. After setting `export UV_NATIVE_TLS=true`, and running the same thing, I get a different error:

<img width="870" alt="image" src="https://github.com/user-attachments/assets/60753b64-7472-4f8d-8cfb-31c878a4a2a9">

But this time `dependencies` is not updated in `pyproject.toml`.

**Comment by charliermarsh** [comment]
Interesting, thanks.

**Comment by zanieb** [comment]
Ah I encountered this too recently.
