### ISSUE TITLE
uv fails to install gym 0.21.0

### ISSUE THREAD

**Issue by locifazi** [astral-sh/uv#7014]
I'm using `uv 0.4.2` on `AlmaLinux-8.9`, and encounter following problem:

```
$ uv pip install gym==0.21.0
                                                                                                             
error: Failed to download and build `gym==0.21.0`
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
/home/USER/.cache/uv/builds-v0/.tmpwd1OEy/lib/python3.11/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
---
```

**Comment by charliermarsh** [comment]
Are you able to install the package with `uv pip install --use-pep517 gym==0.21.0`?

**Comment by locifazi** [comment]
No, the flag `--use-pep517` isn't recognized by uv, but apparently uv follows [by default pep517](https://docs.astral.sh/uv/pip/compatibility/#pep-517-build-isolation).

I can also mention that this package is successfully installed through `pip install gym==0.21.0` and `pip install gym==0.21.0 --use-pep517`

**Comment by charliermarsh** [comment]
(Sorry, I meant `pip install gym==0.21.0 --use-pep517`.)

**Comment by locifazi** [comment]
I found the cause: gym 0.21.0 has incorrect metadata, but I was able to install it using pip due to some custom configurations I've made to pip.

Therefore uv's error message is valid.

**Comment by seif9116** [comment]
😭😭😭 What are those custom configurations @locifazi 🥹🥹🥹. 

I tried in a venv managed by uv (python 3.9). `uv pip install gym==0.21.0` as well as `pip install gym==0.21.0 --use-pep517`. Both times I get the error

```
  × Failed to build `gym==0.21.0`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stderr]
      /home/seif/.cache/uv/builds-v0/.tmpyKq7Tf/lib/python3.9/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

      hint: This usually indicates a problem with the package or the build environment.
```

**Comment by konstin** [comment]
Usually I would recommend upgrading to a more recent version or reporting the problem upstream, but the gym package has been abandoned.

**Comment by pelson** [comment]
The problem with gym is that you have to build the wheel yourself... and build dependencies get resolved at build time (so something that used to be able to build, can get newer dependencies and no longer build). In this case, setuptools moved forwards... you have to pin back some of the dependencies:

```
$ cat foo.txt
setuptools==65.*

$ PIP_CONSTRAINT=foo.txt uv run --python=3.9 --with 'pip<24.1' pip wheel --no-binary=:all: gym==0.21.*
```

**Comment by zanieb** [comment]
See also, https://docs.astral.sh/uv/reference/settings/#build-constraint-dependencies
