### ISSUE TITLE
Automatic Git Repository Initialization for `uv init` Command

### ISSUE THREAD

**Issue by akmalsoliev** [astral-sh/uv#7016]
Implement a feature that automatically initializes a Git repository and generates a `.gitignore` file when the `uv init` command is executed. This functionality should mirror the behavior of `cargo new` or `cargo init --vcs` in the Cargo package manager for Rust.

**Comment by akmalsoliev** [comment]
> See #5476

great! looking forward to it.

**Comment by zanieb** [comment]
We can track here — not sure if there's another issue

**Comment by charliermarsh** [comment]
Done!

**Comment by debnath-d** [comment]
The currently used `.gitignore` file is quite bare-bones. Would you consider using https://github.com/github/gitignore/blob/main/Python.gitignore instead?
