### ISSUE TITLE
uvx (and uv) considerably slower in windows command prompt but fine in powershell

### ISSUE THREAD

**Issue by geophpherie** [astral-sh/uv#7025]
Running `uvx jupyter` in windows command prompt really chokes up for me, the progress bars start freezing up and progress becomes unclear. But in powershell everything runs with reasonable speed. This is using 0.4.4. 

I settled on this as a MRE, but I first came across this when using `uv run` with a script that launches `jupyter`. Was seeing terrible performance in command prompt, but fine in powershell, and fine on a mac on the same wifi. 

This snippet was my ultimate goal, to be run with `uv run`.
```
# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "jupyter",
#     "pandas",
# ]
# ///
import subprocess
from pathlib import Path

subprocess.run([
    "jupyter",
    "notebook",
])
```

Originally came to the GitHub issues through (https://github.com/astral-sh/uv/issues/5073) but I think maybe it's not quite similar enough. Any thoughts or tips would be much appreciated! 

![export](https://github.com/user-attachments/assets/6ced3616-9e8b-4498-a165-33fd2b49cf38)

**Comment by zanieb** [comment]
Can you try using `--no-progress`? Maybe it's a rendering issue.

**Comment by geophpherie** [comment]
Thanks for the quick response!

Running `uvx --no-progress jupyter` seems to result in the same thing.

In CMD it takes a long time, haven't got it to complete yet, but in PS it finishes up quick. So maybe same issue still there?

`Installed 96 packages in 1.90s`

**Comment by geophpherie** [comment]
Well so if i launch `cmd.exe` _in_ powershell it works as expected ... idk what's going on there but doesn't seem like a `uv` problem that I can tell. Gonna close this.

thank you for the time!

**Comment by geophpherie** [comment]
Well so if i launch cmd.exe in powershell it works as expected ... idk what's going on there but doesn't seem like a uv problem that I can tell. Gonna close this.

thank you for the time!

**Comment by geophpherie** [comment]
Sort of wondering if there's something that's slowing down cache lookups for some reason. Some of these take up to 10s - i'm guessing it shouldn't take near that long. 

![image](https://github.com/user-attachments/assets/f1dd4ad2-9617-4272-a659-6196c2876234)
