### ISSUE TITLE
Docker image tag documentation for `uv:python3.12-slim-bookworm` does not match published tag

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#7029]
cc @samypr100 

We transform this to be different than the official image https://github.com/astral-sh/uv/blob/37e25e2b1d0ff78caf9da61380f70f23076bae8f/.github/workflows/build-docker.yml#L174

Any particular reason why? We should either swap that or fix the documentation.

**Comment by samypr100** [comment]
> cc @samypr100
> 
> We transform this to be different than the official image
> 
> https://github.com/astral-sh/uv/blob/37e25e2b1d0ff78caf9da61380f70f23076bae8f/.github/workflows/build-docker.yml#L174
> 
> Any particular reason why? We should either swap that or fix the documentation.

The intent was to match formal debian's upstream pattern which is with -slim standard as a suffix.

`debian:bookworm-slim`

**Comment by zanieb** [comment]
It's weird since it doesn't match the Python image tag format but 🤷‍♀️ idk why they do that.
