### ISSUE TITLE
Support certain extras of the current project as dev dependencies

### ISSUE THREAD

**Issue by lengau** [astral-sh/uv#7033]
It would be nice to be able to support adding specific extras as dev dependencies.. For example, a project that is migrating to `uv` may have optional dependency groups that they'd like to keep separate but add as dev dependencies like so:

```toml
[project.optional-dependencies]
test = [
    "pytest~=8.0",
    "pytest-cov~=5.0",
    "pytest-time~=0.3",
]
lint = [
    "ruff>=0.6.0",
]
types = [
    "pyright==1.1.377",
]

[tool.uv]
dev-dependencies = [
    ".[test,lint,types]"
]

**Comment by charliermarsh** [comment]
I think this makes sense but we might want to wait until https://peps.python.org/pep-0735/ is resolved?

**Comment by lengau** [comment]
@charliermarsh I was playing around for unrelated reasons and discovered that `"<project-name>[extra] @ /"` works in the dev-dependencies resolver. Is this something we could expect to continue to work, or should that be considered a bug?

**Comment by lengau** [comment]
In the PEP-0735 dependency-groups area, using `<project-name>[extra,other]` does work correctly. It's not quite as simple as using `.`, but it's a decent workaround and meets my use case. I'll leave this open for the Astral folks to decide whether they want to implement it with the shorthand, but I'm content as-is.

**Comment by charliermarsh** [comment]
👍 I think we can close this now that PEP 735 is accepted and implemented, since we wouldn't go beyond what's in the spec.
