### ISSUE TITLE
Allow virtual packages inside of workspaces

### ISSUE THREAD

**Issue by quodlibetor** [astral-sh/uv#7039]
I have several directories that hold static data that just exists to be fed into some tool defined elsewhere -- documentation, source definitions for codegen, etc.

AFAICT there are two options for virtual packages both of which have some downsides. Not sure if there are better patterns or I'm missing something obvious.

1. add tools as dev-dependencies in the root workspace

    - exactly which directories require which dev dependencies isn't obvious from the pyproject.toml file.
    - ci or users that needs to do anything also needs to install everything else in the root dev-dependencies.

2. create several virtual packages (workspace roots)

    - dependencies aren't guaranteed to be in sync
    - the root workspace.members list doesn't include the virtual packages

This is related to #4025 and https://github.com/astral-sh/rye/discussions/1342#discussioncomment-10400593

Thanks for great tools! Love the focus and design y'all have.

**Comment by zanieb** [comment]
I think @charliermarsh has the most context on this.

Glad you're enjoying the tools :)

**Comment by charliermarsh** [comment]
You can create a `pyproject.toml` in each of those directories and then add them as normal dependencies (rather than dev dependencies), which should work fine as long as you omit a `[build-system]` from the `pyproject.toml`.

**Comment by zanieb** [comment]
See https://docs.astral.sh/uv/concepts/projects/#build-systems for more details on that.

**Comment by quodlibetor** [comment]
That makes sense! I read through that page but didn't process it correctly.

FWIW I think that if that page had a "Virtual projects" or "Dependency only projects" section I ... may ... have figured this out on my own.

- Creating projects
    - Applications
    - Libraries
    - Packaged applications
    - Dependency only projects <--

**Comment by quodlibetor** [comment]
oh wow I entirely missed the [0.4 release](https://github.com/astral-sh/uv/releases/tag/0.4.0) which clearly defines all this 🤦 , congrats on it!

**Comment by zanieb** [comment]
Thanks :D no problem.
