### ISSUE TITLE
Support curl uv/0.x/install.sh in addition to uv/0.x.y/install.sh

### ISSUE THREAD

**Issue by quodlibetor** [astral-sh/uv#7042]
It would be nice to be able to write docs and CI in a way that ensures that users get the most recent non-breaking version of uv.

It might be nice if this also prints a warning during install if 0.x is not the latest x.

**Comment by zanieb** [comment]
Duplicate of https://github.com/astral-sh/uv/issues/4109

**Comment by ChefMonies1** [comment]
curl -LsSf https://astral.sh/uv/install.sh | sh
