### ISSUE TITLE
Documentation on non-existent functionality (building distributions)?

### ISSUE THREAD

**Issue by seppzer0** [astral-sh/uv#7043]
Hi, I was researching on how to build PIP distributions with uv and have found a piece of documentation on `uv build` command which as of 0.4.4 version does not exist.

https://docs.astral.sh/uv/concepts/projects/#building-projects

Is this documentation on a not yet existing functionality? If so, building wheels with uv would definitely be a big step for me personally towards migrating from another packager manager for my bigger projects.

**Comment by zanieb** [comment]
Ah sorry that's my bad — I published some documentation fixes before the release. It'll be in the next release https://github.com/astral-sh/uv/pull/6895

**Comment by seppzer0** [comment]
Got it, excited for it to get released 🎉
