### ISSUE TITLE
`uv venv` and `uv sync` has different default shell prompts

### ISSUE THREAD

**Issue by leddy231** [astral-sh/uv#7049]
`uv venv` creates a .venv where the default shell prompt is the name of the current folder. Nice!
`uv sync` creates a .venv (if there is none) where the default shell prompt is just `(.venv)`. Confusing for monorepos.
And `uv sync` does not allow specifying the prompt when invoking.

Its a bit odd that they have different defaults, and personally I think the folder name as the default prompt is the better option.

**Comment by tpgillam** [comment]
I just realised this was addressed a few hours ago: https://github.com/astral-sh/uv/pull/7021

With `uv sync` as-of uv 0.4.5 it works very nicely.

**Comment by leddy231** [comment]
Haha race condition with the issue, I could not find an open issue and the latest release at the time (0.4.4) did not have the fix yet.
