### ISSUE TITLE
Ability to invoke `uv run` without `[project]` in `pyproject.toml`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#7068]
I have a repo that I am slowly moving to use `uv`. For now, it doesn't have a `[project]` table in a particular `pyproject.toml`, but this seems to stop me from using `uv run`.

What I want to do is essentially this:

```bash
> curl -LsSf https://astral.sh/uv/install.sh | sh
> uv pip install -r requirements.txt
> ls
pyproject.toml requirements.txt script.py
> uv run script.py
error: No `project` table found in: `/path/to/repo/pyproject.toml`
```

I am using `uv==0.4.5`. The last command is the issue, I would like `uv run` to be able to invoke a Python script, even if the `pyproject.toml` has no `[project]` section in it.

**Comment by AlexWaygood** [comment]
If all of your requirements are specified in `requirements.txt` rather than `pyproject.toml`, you should be able to do something like this:

```console
> curl -LsSf https://astral.sh/uv/install.sh | sh
> uv run --no-project --with-requirements requirements.txt script.py
```

**Comment by jamesbraza** [comment]
<img src="https://media2.giphy.com/media/LfGGW219qNzLP6IzTA/giphy.gif"/>

I did not know `--no-project` existed 😻. I promise I had even read the `uv run --help` manu. Sorry for false positive request, closing this out
