### ISSUE TITLE
uv roadmap and project direction

### ISSUE THREAD

**Issue by cambriancoder** [astral-sh/uv#7072]
Hi,

Love this project! I've been tracking this project for only a couple weeks and the pace of feature development is incredible. 

My company is deciding on our next set of tools for Python application and library development (which is currently a mix of setuptools with make, and poetry), and I discounted uv due to its lack of universal lock file support only two weeks ago. If there was a roadmap with rough timelines it would help with our decision making e.g. I'm currently proposing hatch with uv as the installer backend, but uv now has build support, and will likely replace a lot of other hatch cli features at this rate. 

Is there a roadmap for future features/releases and/or a target feature set for a stable (v1) release?

**Comment by MrFizzyBubbs** [comment]
https://github.com/orgs/astral-sh/projects/11

**Comment by zanieb** [comment]
That project is actually relatively outdated, as those were tasks we wanted to accomplish before announcing all the recent new features.

We don't have a public roadmap and, if we add one, we're very unlikely to provide timelines. We do intend to continue to grow the features for parity with other project management tools like Hatch, Rye, and Poetry.
