### ISSUE TITLE
error: Failed to prepare distributions, Caused by: Failed to fetch wheel: sentence-transformers==2.2.2

### ISSUE THREAD

**Issue by B-M-S-West** [astral-sh/uv#7075]
I'm currently setting up a new project using uv following using
uv init
uv version = 0.4.5
python version = 3.11
windows 11

When trying to add graphrag
uv add graphrag

I get the following error:
$ uv add graphrag
Resolved 242 packages in 785ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: sentence-transformers==2.2.2
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit code: 1

Some further information printed out:
        ********************************************************************************
        Usage of dash-separated 'description-file' will not be supported in future
        versions. Please use the underscore name 'description_file' instead.

        By 2024-Sep-26, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.

        See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
        ********************************************************************************

!!
  opt = self.warn_dash_deprecation(opt, section)
error: could not create 'build\bdist.win-amd64\wheel\.\sentence_transformers\cross_encoder\evaluation\CEBinaryAccuracyEvaluator.py': No such file or directory
---

Any ideas on the issue and how I can resolve it?

**Comment by charliermarsh** [comment]
Are you able to `pip install sentence-transformers==2.2.2 --use-pep517`? Or does that also show an error?

**Comment by B-M-S-West** [comment]
I was able to use pip install to get it working and it would appear in the uv.lock
Since then everytime I use uv add for another depenency the same error will come up as before, as it tries to add sentence-transformers to the dependency of the pyproject.toml?

**Comment by jimmy3142** [comment]
I'm also having a similar issue with many other packages. Anything else you can suggest here @charliermarsh?

**Comment by charliermarsh** [comment]
Can you elaborate on the issue you're seeing? The commands you're running, the error you're seeing, how I might reproduce it, etc.

**Comment by jimmy3142** [comment]
I solved my issue. Sorry for the delayed reply. I didn't want to hijack the thread, as it was a slightly different issue.
