### ISSUE TITLE
Poetry's lock file compatibility

### ISSUE THREAD

**Issue by skhaz** [astral-sh/uv#7087]
Recently, I noticed that support for adding dependencies in the `pyproject.toml` file was added, which is excellent, thank you very much.

However, in almost all the projects I work on, and there are quite a few, we use Poetry.

For example, I could install with UV and add the `uv.lock` file to Git, but the other team members are not interested (no way) in migrating to UV.

That said, the only way I could use UV professionally would be if UV, for example, gave up its own lock file and had a compatibility layer with Poetry.

Or even better, if someone created a PEP to specify a lock file for everyone to use, since it seems that just having the dependencies in `pyproject.toml` doesn’t seem to be enough.

What do you think?

**Comment by zanieb** [comment]
Sounds like you're looking for https://peps.python.org/pep-0751/

It's in progress and we're engaging heavily.

We won't be supporting Poetry's format though.

**Comment by skhaz** [comment]
That PEP sounds great to me. Poetry is very slow, and having this compatibility between teams would be fantastic. Thank you.
