### ISSUE TITLE
Specify URL dependencies with environment markers

### ISSUE THREAD

**Issue by tudoroancea** [astral-sh/uv#7097]
Hi there, 

First let me thank you for all the incredible work you put into uv, it really is becoming a tool I am trying to use in every one of my python projects. One use case I still can't really solve with uv is the following: I have a dependency that does not have (yet) a published PyPI wheel (it's a nightly release) and only wheels available through a [GitHub release](https://github.com/casadi/casadi/releases/nightly-main). 
I wanted to know if there was a way to specify an URL dependency that can incorporate environment markers to provide one wheel URL for Linux and one for macOS. 
Based on the documentation it doesn't look like it, but it would definitely be useful for using dependencies to scientific packages (or any non-pure-python packages) in a truly cross-platform way.

Thanks in advance,

Ted

**Comment by charliermarsh** [comment]
I think you should be able to do something like this:

```toml
dependencies = [
   "package_name @ https://github.com/path/to/wheel.whl ; sys_platform == 'darwin'",
   "package_name @ https://github.com/path/to/other_wheel.whl ; sys_platform == 'linux'",
]
```

**Comment by tudoroancea** [comment]
This works after also adding the following in the `pyproject.toml`:
```toml
[tool.hatch.metadata]
allow-direct-references = true # to allow the syntax 'pkg @ url' in dependencies
```
Thanks!
