### ISSUE TITLE
When I click `Docs ⌄` from the blog I'm taken to the ruff docs, but I was looking for the uv docs

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#7105]
1. Go to https://astral.sh/blog
2. Click here:

![image](https://github.com/user-attachments/assets/37d92cbb-7c2a-4232-9e1a-730206808e36)

3. End up on ruff docs: https://docs.astral.sh/ruff/ 🙁

This happens because I google "uv python" , which gives me this blog post "https://astral.sh/blog/uv", I go to click docs as either the uv docs or being an old timer and associating clicking with opening a menu, and I end up with the ruff docs.

**Comment by zanieb** [comment]
Oops yeah this shouldn't go somewhere on click anymore. Thanks!

**Comment by charliermarsh** [comment]
Pushed a fix, should deploy soon.
