### ISSUE TITLE
uv-installed PyPy versions take precedence over non-uv CPython versions

### ISSUE THREAD

**Issue by hynek** [astral-sh/uv#7118]
`uv 0.4.6 (84f25e8cf 2024-09-05)`

I've been playing a bit with `uv python` and installed pypy3.9 with it and forgot about it.

Now, whenever I run `uv venv --python python3.9` I get pypy3.9 instead. It just says `Using Python 3.9.19`.

My guess is that uv-installed Pythons take hard precedence, because uninstalling it starts giving me my proper Python 3.9 from homebrew, despite the fact I still have a pyp3.9 installed, too.

**Comment by zanieb** [comment]
Hm yeah we'll use a managed Python over an unmanaged one. You think we should prefer the system CPython in this case? You can do `--python cpython3.9` or `--python cp3.9` to avoid getting PyPy.

**Comment by hynek** [comment]
Hmmm, fair enough for me, but kinda surprising. I would've never expected to get a PyPy when asking for "Python 3.9". IDK, maybe I'm just set in my ways, by in my mind python3.9 is CPython and pypy3.9 is PyPy.

**Comment by zanieb** [comment]
Yeah that makes sense. We should probably change the ordering, though it'll be a bit of a pain.

**Comment by henryiii** [comment]
> I would've never expected to get a PyPy when asking for "Python 3.9". IDK, maybe I'm just set in my ways, by in my mind python3.9 is CPython and pypy3.9 is PyPy.

I've argued this before too. :)

**Comment by zanieb** [comment]
Oh I might be fixing this by accident while working on #7286 haha

**Comment by saucoide** [comment]
To add a datapoint, i'm just running into this and also found the behavior unexpected, especially because the output of a command depends on what other uv-managed pythons were previously installed

```sh
uv python install python3.8 pypy.38
uv venv --python python3.8 .venv  # venv created with cpython 3.8
```

vs

```sh
uv python install pypy.38
uv venv --python python3.8 .venv  # venv created with pypy 3.8
```

Also this produces different results whether run together or separately:

```sh
uv python install pypy3.8 python3.8  # installs both cpython & pypy

uv python install pypy3.8
uv python install python3.8  # wont install anything -> already found a 3.8 python pypy

```
