### ISSUE TITLE
--extra-index-url in requirements.in breals pip compile

### ISSUE THREAD

**Issue by esbennielsenkvantify** [astral-sh/uv#7119]
Using the following requirements.in
```
--extra-index-url https://download.pytorch.org/whl/cpu
numpy==1.26.4

```
and running
`uv pip compile -p 3.11 requirements.in -o requirements.lock`
gives
` × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of numpy==1.26.4 and you require
      numpy==1.26.4, we can conclude that your requirements are unsatisfiable.`

When removing the --extra-index-url line, it works fine.

Happened with uv 0.4.6 on Ubuntu x86_64.

**Comment by charliermarsh** [comment]
You very likely want `--index-strategy unsafe-best-match`. Please see here: https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes.
