### ISSUE TITLE
Behavior of `uv pip install` different from docs

### ISSUE THREAD

**Issue by kdheepak** [astral-sh/uv#7123]
From the docs - https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments:

> When running a command that mutates an environment such as uv pip sync or uv pip install, uv will search for a virtual environment in the following order:
>
>  - An activated virtual environment based on the VIRTUAL_ENV environment variable.
>  - An activated Conda environment based on the CONDA_PREFIX environment variable.
>  - A virtual environment at .venv in the current directory, or in the nearest parent directory.
>
> If no virtual environment is found, uv will prompt the user to create one in the current directory via uv venv.

Specifically, the docs say "if no virtual environment is found, uv will prompt the user to create one in the current directory via uv venv".

I'm not experiencing this:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/d68d9a06-c2be-430b-bd7a-92e9ac108187">

I'm getting `error: No virtual environment found`.

This is either a bug or the documentation should be updated.

```
$ uv --version
uv 0.4.6 (84f25e8cf 2024-09-05)
```

**Comment by zanieb** [comment]
Yes we should improve this error message.

**Comment by charliermarsh** [comment]
Gonna fix this.
