### ISSUE TITLE
`uv python`: Python installation keys must have valid Python versions

### ISSUE THREAD

**Issue by pythonweb2** [astral-sh/uv#7129]
In my environment, some old code still uses python 3.6, so I have it installed. When I run `uv python list`, this happens:

```
>>> uv python list
thread 'main' panicked at crates\uv-python\src\installation.rs:247:14:
Python installation keys must have valid Python versions: "Python version `3.6.8` must be >= 3.7"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This feels like a bug, since I would expect it to just show me the supported versions, instead of the whole command being broken if an old python version is installed.

**Comment by zanieb** [comment]
Eek! Sorry about that.
