### ISSUE TITLE
Why is install.sh (installers) not part of the repo? Where is that hosted?

### ISSUE THREAD

**Issue by hoegge** [astral-sh/uv#7158]
The installers are also an important part of the user experience, e.g., currently lacking setting path op so installation is a bit tedious. 

Arend't the installers / shouldn't they be part of the project?

**Comment by charliermarsh** [comment]
They're included in the GitHub Releases, but they're created with [`cargo-dist`](https://github.com/axodotdev/cargo-dist). You're welcome to file issues with the installers here or there.
