### ISSUE TITLE
UV not installing current package

### ISSUE THREAD

**Issue by danieleades** [astral-sh/uv#7162]
I'm seeing a change in UV behaviour where the current package is not being installed (either with `uv sync` or `uv run`)

This is causing CI failures

I can work around this locally by manually installing the current package in the virtual environment

see https://github.com/danieleades/sphinx-graph/actions/runs/10750436290/job/29816576192?pr=175

**Comment by dimbleby** [comment]
https://github.com/astral-sh/uv/blob/main/CHANGELOG.md#040

**Comment by danieleades** [comment]
note to self: read the release notes

**Comment by zanieb** [comment]
See also https://docs.astral.sh/uv/concepts/projects/#build-systems
