### ISSUE TITLE
Can not install an earlier futures version with uv

### ISSUE THREAD

**Issue by selimt** [astral-sh/uv#7170]
Installing a package that has the "futures" package dependency results in the following error:
```
> uv pip install futures
Resolved 1 package in 19ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: futures==3.4.0
  Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
--- stdout:

--- stderr:
This backport is meant only for Python 2.
It does not work on Python 3, and Python 3 users do not need it as the concurrent.futures package is available in the standard library.
For projects that work on both Python 2 and 3, the dependency needs to be conditional on the Python version, like so:
extras_require={':python_version == "2.7"': ['futures']}
```
with uv 0.4.2 the same command goes through without any issues. And regular `pip install` command succeeds as well.

I agree that the upstream package should specify the Python requirement as specified above but at least we should be able to install an earlier version of `futures` (3.1.1) that doesn't have the "python<3" requirement.

**Comment by charliermarsh** [comment]
> with uv 0.4.2 the same command goes through without any issues.

Do you mean that this changed in newer versions?

**Comment by selimt** [comment]
Correct. 0.4.3 through 0.4.7 has this issue.

**Comment by charliermarsh** [comment]
This seems ok to me. You _can_ install `uv pip install futures==3.1.1` or earlier versions (though the package warns you not to do this). But if you try to build the latest, we fail.

**Comment by charliermarsh** [comment]
We don't respect upper bounds on `requires-python` which is why we stopped backtracking.

**Comment by selimt** [comment]
OK, thanks, did not realize the change in behavior for backtracking. We updated our setup.py, so all good here.
