### ISSUE TITLE
trying to install a jupyter extension no module pip found

### ISSUE THREAD

**Issue by thunder-007** [astral-sh/uv#7173]
steps to reproduce 
```
uv venv venv
source venv/bin/activate
uv install jupyter
juypter lab
```
open the url shown on terminal

![image](https://github.com/user-attachments/assets/0a102986-326f-46eb-a921-7fee6d81b6f9)

```
Error when performing an action.

Reason given:

Error: /home/thunder/Kaggle/.venv/bin/python3: No module named pip
```
jupyter lab is expecting pip to present in the virtual environment

**Comment by charliermarsh** [comment]
We don't include pip in the virtual environment by default. You can `uv pip install pip` or use `uv venv --seed`.
