### ISSUE TITLE
Duplicate binaries in uv cache

### ISSUE THREAD

**Issue by yankeexe** [astral-sh/uv#7184]
## Issue
`uv` is creating duplicate binaries for the same version in the cache, increasing the cache size.
Ideally, if the same version exists in the cache then there should not be multiple copies of it. 

<img width="1242" alt="image" src="https://github.com/user-attachments/assets/d6a3cfc4-10d9-4f96-9391-232fc0bdbe6a">

## Solution maybe? 

To optimize storage, would it be possible to create a symbolic link (softlink) or hardlink to the existing binary instead of duplicating it? This approach could maintain any internal indexing or read mechanisms without increasing the cache size.

## System
**uv version:** uv 0.4.5 (42b6bfbad 2024-09-04)
**platform**: Darwin -  Sonoma 14.6.1

**Comment by zanieb** [comment]
Thanks for the report. Not sure what's up here, but @charliermarsh might have an idea. Does this behavior persist if you clear the cache? I wonder if we changed our cache key function so there's a duplicate here from an old version of uv.

**Comment by yankeexe** [comment]
@charliermarsh Tried installing, uninstalling, re-installing the `ruff` package with `uv tool install` and ` uv pip install`. 
This is what I was doing when I noticed this issue. 

I don't see this issue anymore.

**Comment by zanieb** [comment]
Thanks for following up!
