### ISSUE TITLE
Custom task runner

### ISSUE THREAD

**Issue by dbrtly** [astral-sh/uv#7203]
`npm run build`

npm allows developers to specify the meaning of `build` in package.json. 

This reduces/eliminates the need for a Makefile/justfile/etc. 

`uv task my_task` or `uv my_task` could execute a task defined in pyproject.toml.

**Comment by zanieb** [comment]
Please remember to search for duplicates.

This is a duplicate of https://github.com/astral-sh/uv/issues/5903
