### ISSUE TITLE
`uv run` is causing an SSL_CERT error

### ISSUE THREAD

**Issue by mattpodolak** [astral-sh/uv#7235]
I'm using uv from Git Bash on Windows, loaded in a conda env
```
$ uv --version
uv 0.4.1 (823f23e22 2024-08-30)
```

Whenever I do `uv run <script>` I get the following error:
```
$ uv run script.py 
warning: Ignoring invalid `SSL_CERT_FILE`. File does not exist: C:\Users\mattpnaconda3vs\lingocat-scraper\Library\ssl.
```

I think this mightve started happening after running `uv tool update-shell`. This error doesnt happen when doing `python script.py` from the same directory with the same conda env and venv activated.

Also worth noting, the path for the SSL file is wrong, it should be `C:\Users\mattp\anaconda3\envs\lingocat-scraper`

**Comment by charliermarsh** [comment]
Is `SSL_CERT_FILE` set? Does `echo $SSL_CERT_FILE` show anything?

**Comment by mattpodolak** [comment]
thanks for the quick response again @charliermarsh 🙏🏽, yes it prints out the invalid path

**Comment by mattpodolak** [comment]
Also interesting is that when I open Git Bash in another directory (no uv venv) `echo $SSL_CERT_FILE` doesnt print out anything

**Comment by zanieb** [comment]
It sounds like something is setting `SSL_CERT_FILE`, but we don't do that ever.
