### ISSUE TITLE
inconsistent behaviour of uv export with --no-emit-workspace option for the root project

### ISSUE THREAD

**Issue by lucidfrontier45** [astral-sh/uv#7241]
- uv platform: linux gnu
- uv version: 0.4.8
- uv command: `uv export --no-emit-workspace`

https://docs.astral.sh/uv/reference/cli/#uv-export
```
--no-emit-workspace
Do not emit any workspace members, including the root project.

By default, all workspace members and their dependencies are included in the exported requirements file, with all of their dependencies. The --no-emit-workspace option allows exclusion of all the workspace members while retaining their dependencies.
```

From this documentation I expected that passing `--no-emit-workspace` will also prevent emitting `-e .` to the requirements.txt. For a project with sub modules I confirmed that 

```
-e .
-e sub1
-e sub2
...
```
disappeared.

However if I use this option to a project that has no sub modules, i.e. no entries of `tool.uv.workspace.members`, `-e .` is still emitted. Isn't `-e .` supposed to be removed in this case?

**Comment by charliermarsh** [comment]
Yes. Can you provide a full reproduction though? I.e., a file that I can use to reproduce this, or a series of commands to run?

**Comment by lucidfrontier45** [comment]
@charliermarsh 

Thank you for reply. Just type those commands and you can see `-e .` is included in the exported output.

```sh
uv init --lib new_project
cd new_project
uv export --no-emit-workspace
```
