### ISSUE TITLE
Add --proxy CLI option

### ISSUE THREAD

**Issue by IvanciuVlad** [astral-sh/uv#7243]
Platform: Windows 11
uv version: 0.4.7

**WHAT**
Allow setting the proxy in the CLI similar to how pip allows you too.

**WHY**
For us, uv is being blocked by the corporate proxy, and we cannot set the correct proxy as environmental variables due to rights issues as the docs suggest.

**HOW**

- uv --proxy=http://**.**.**.**:port add pandas

**Comment by charliermarsh** [comment]
What is the use-case for a proxy as opposed to setting the index URL via `--index-url`?

**Comment by IvanciuVlad** [comment]
Hi, sorry for long delay in response. Yes, we would need http proxy, otherwise the corporate network will block allow us from installing packages.

**Comment by YangNianYi** [comment]
`reqwest`: System proxies are enabled by default.
set environment variables
`HTTP_PROXY`
`HTTPS_PROXY`
`ALL_PROXY`
https://github.com/seanmonstar/reqwest/blob/master/src/lib.rs#L138
