### ISSUE TITLE
Support directories in `uv.tool.cache-keys`

### ISSUE THREAD

**Issue by vivienm** [astral-sh/uv#7246]
I work on projects using both Python and Rust. I'd like to make uv rebuild the project when the Rust code is modified, typically when any `*.rs` file in the `src` directory is modified.

The new configuration entry `uv.tool.cache-keys` is promising, but doesn't seem to work with directories.

Possibly related: https://github.com/astral-sh/uv/issues/2152.

**Comment by charliermarsh** [comment]
I've been hesitant to add this because in some cases it may just be slower than building the project. Perhaps not for an extension module like that, though.

**Comment by vivienm** [comment]
Also, it looks like entries such as `{ file = "some-directory" }` are silently ignored. Maybe it could be nice to have a warning?
