### ISSUE TITLE
`uv run pytest` does not work

### ISSUE THREAD

**Issue by shinybrar** [astral-sh/uv#7260]
## Ten words or less
`uv run pytest` does not work in my project.

## Description
I have a very small project trying our `uv` and the next-gen tooling provided by `astral`. (I ❤️ the work you guys are doing). I am coming from a `poetry` background and trying to convince my workplace to transition from `poetry|conda|nothing` to `uv`.

You can find the entire, source code of the project [here](https://github.com/shinybrar/releaseer) which looks something like this,

### Structure
```
.
├── LICENSE
├── README.md
├── pyproject.toml
├── releaseer
│   ├── __init__.py
│   ├── app.py
│   └── names.yaml
├── tests
│   ├── conftest.py
│   └── test_base.py
└── uv.lock
```

```python
# Contents of releaseer/app.py
from typing import Dict, List
from litestar import Litestar, get
from yaml import load, Loader

@get("/")
async def hello() -> Dict[str, str]:
    return {"message": "Hello from releaseer!"}

@get("/names")
async def names() -> Dict[str, List[str]]:
    with open("names.yaml") as f:
        names = load(f, Loader=Loader)
    return names

@get("/healthy")
async def healthy() -> bool:
    return True

app = Litestar(route_handlers=[hello, names, healthy])
```

```python
# Contents of tests/conftest.py

from typing import TYPE_CHECKING
from collections.abc import AsyncIterator

import pytest

from litestar.testing import AsyncTestClient

from releaseer.app import app

if TYPE_CHECKING:
    from litestar import Litestar

@pytest.fixture(scope="function")
async def client() -> AsyncIterator[AsyncTestClient[Litestar]]:
    async with AsyncTestClient(app) as client:
        yield client
```

## The Error

```
uv sync --verbose
shinybrar@saturn releaseer % uv sync --verbose
DEBUG uv 0.4.6 (Homebrew 2024-09-05)
DEBUG Found project root: `/Users/shinybrar/Workspace/releaseer`
DEBUG No workspace root found, using project root
DEBUG Reading requests from `/Users/shinybrar/Workspace/releaseer/.python-version`
DEBUG The virtual environment's Python version satisfies `Python 3.12`
DEBUG Using request timeout of 30s
DEBUG Acquired lock for `/Users/shinybrar/.cache/uv/built-wheels-v3/path/fbac97741b8da1f8`
DEBUG Found static `pyproject.toml` for: releaseer @ file:///Users/shinybrar/Workspace/releaseer
DEBUG No workspace root found, using project root
DEBUG Released lock at `/Users/shinybrar/.cache/uv/built-wheels-v3/path/fbac97741b8da1f8/.lock`
DEBUG Existing `uv.lock` satisfies workspace requirements
Resolved 58 packages in 1ms
DEBUG Using request timeout of 30s
DEBUG Requirement already installed: annotated-types==0.7.0
DEBUG Requirement already installed: anyio==4.4.0
DEBUG Requirement already installed: argcomplete==3.5.0
DEBUG Requirement already installed: certifi==2024.8.30
DEBUG Requirement already installed: charset-normalizer==3.3.2
DEBUG Requirement already installed: click==8.1.7
DEBUG Requirement already installed: colorama==0.4.6
DEBUG Requirement already installed: commitizen==3.29.0
DEBUG Requirement already installed: decli==0.6.2
DEBUG Requirement already installed: editorconfig==0.12.4
DEBUG Requirement already installed: faker==28.4.1
DEBUG Requirement already installed: fast-query-parsers==1.0.3
DEBUG Requirement already installed: h11==0.14.0
DEBUG Requirement already installed: httpcore==1.0.5
DEBUG Requirement already installed: httptools==0.6.1
DEBUG Requirement already installed: httpx==0.27.2
DEBUG Requirement already installed: idna==3.8
DEBUG Requirement already installed: iniconfig==2.0.0
DEBUG Requirement already installed: jinja2==3.1.4
DEBUG Requirement already installed: jsbeautifier==1.15.1
DEBUG Requirement already installed: litestar==2.11.0
DEBUG Requirement already installed: markdown-it-py==3.0.0
DEBUG Requirement already installed: markupsafe==2.1.5
DEBUG Requirement already installed: mdurl==0.1.2
DEBUG Requirement already installed: msgspec==0.18.6
DEBUG Requirement already installed: multidict==6.0.5
DEBUG Requirement already installed: packaging==24.1
DEBUG Requirement already installed: pluggy==1.5.0
DEBUG Requirement already installed: polyfactory==2.16.2
DEBUG Requirement already installed: prompt-toolkit==3.0.36
DEBUG Requirement already installed: pydantic==2.9.0
DEBUG Requirement already installed: pydantic-core==2.23.2
DEBUG Requirement already installed: pygments==2.18.0
DEBUG Requirement already installed: pytest==8.3.2
DEBUG Requirement already installed: python-dateutil==2.9.0.post0
DEBUG Requirement already installed: python-dotenv==1.0.1
DEBUG Requirement already installed: pyyaml==6.0.2
DEBUG Requirement already installed: questionary==2.0.1
DEBUG Requirement already installed: rich==13.8.0
DEBUG Requirement already installed: rich-click==1.8.3
DEBUG Requirement already installed: ruff==0.6.4
DEBUG Requirement already installed: six==1.16.0
DEBUG Requirement already installed: sniffio==1.3.1
DEBUG Requirement already installed: termcolor==2.4.0
DEBUG Requirement already installed: tomlkit==0.13.2
DEBUG Requirement already installed: typing-extensions==4.12.2
DEBUG Requirement already installed: tzdata==2024.1
DEBUG Requirement already installed: uvicorn==0.30.6
DEBUG Requirement already installed: uvloop==0.20.0
DEBUG Requirement already installed: watchfiles==0.24.0
DEBUG Requirement already installed: wcwidth==0.2.13
DEBUG Requirement already installed: websockets==13.0.1
Audited 52 packages in 0.37ms
```

```bash
shinybrar@saturn releaseer % uv run pytest --verbose
ImportError while loading conftest '/Users/shinybrar/Workspace/releaseer/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from releaseer.app import app
E   ModuleNotFoundError: No module named 'releaseer'
```

I am hoping, I am missing something obvious and this is something really trivial.

**Comment by charliermarsh** [comment]
Interesting. I seem to get the same error when I run directly after activating the virtualenv, though:
```console
❯ pytest
ImportError while loading conftest '/Users/crmarsh/workspace/puffin/releaseer/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from releaseer.app import app
E   ModuleNotFoundError: No module named 'releaseer'
```

I'll have to take a look at how this typically works.

**Comment by charliermarsh** [comment]
Adding this to `pyproject.toml` resolves it for me:
```toml
[tool.pytest.ini_options]
pythonpath = ["."]
```

**Comment by charliermarsh** [comment]
Creating `tests/__init__.py` also resolves it, which I think is the right fix based on https://docs.pytest.org/en/stable/explanation/pythonpath.html.

**Comment by shinybrar** [comment]
Thank you so much @charliermarsh -- that was a simple enough fix. i.e. The correct way would be to use `tests/__init__.py`. Thank you so much for the help!

**Comment by charliermarsh** [comment]
No problem, I learned something too!

**Comment by rafalkrupinski** [comment]
I had the same problem, the project was missing `[build-system]` section

**Comment by acorello** [comment]
Same problem here: I ran `uv run pytest` as suggested by the docs but it failed to import a package installed in the virtual environment.

I've added the following to an `__init__.py` placed in the folder of the file with the failing import:

```python
import sys
print(sys.path)
```

And I got `['~/Projects/MyProject', '~/.local/share/uv/tools/pytest/bin', '~/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/lib/python313.zip', '~/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/lib/python3.13', '~/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/lib/python3.13/lib-dynload', '~/.local/share/uv/tools/pytest/lib/python3.13/site-packages']`

(NOTE: I've replaced my home folder with `~` in this comment, the result were absolute paths).

I can see `'~/Projects/MyProject'` which I configured by adding

```toml
[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--import-mode=importlib", ]
```

but no virtual env.

However, if I run `uv run python` the `sys.path` in the console does include the virtual-environment folder `'~/Projects/MyProject/.venv/lib/python3.13/site-packages'` as last item.

I fixed the issue adding the virtual-env folder under `[tool.pytest.ini_options]` as well.

VERSIONS:

`uv 0.5.1 (dac8c41af 2024-11-09)` (built locally with cargo)

```
uv run python --version
Python 3.13.0
```

I shouldn't need to add the virtual env folder under the tools settings, isn't it?

Do you have any idea or request?

**Comment by seangies** [comment]
I'm hitting a similar issue and none of the above suggestions work. I tried adding `__init__.py` to my tests module, and adding `pythonpath == "."` to `pyproject.toml`. Either way, the tests pick up the project's default venv, ignoring the one-time venv `uv run` creates to satisfy `--with` options.

**Comment by hon-gyu** [comment]
`uv add pytest --dev` fixed my problem. 

I found that when running `uv run pytest` without `pytest` in dependencies, it somehow does not use the venv `uv` has set up.

**Comment by terrycojones** [comment]
I get the same as @hon-gyu. Putting `__init__.py` into the test dir didn't help. `uv add pytest --dev` did.

**Comment by mawildoer** [comment]
> I'm hitting a similar issue and none of the above suggestions work. I tried adding `__init__.py` to my tests module, and adding `pythonpath == "."` to `pyproject.toml`. Either way, the tests pick up the project's default venv, ignoring the one-time venv `uv run` creates to satisfy `--with` options.

I noticed the same thing. This line (no longer? I've used it successfully [elsewhere](https://github.com/atopile/fastapi-github-oidc/blob/main/.github/workflows/test.yml#L21)) works in my test actions workflow:

`uv run --with pytest-github-actions-annotate-failures pytest`

**Comment by post-human-world** [comment]
> > I'm hitting a similar issue and none of the above suggestions work. I tried adding `__init__.py` to my tests module, and adding `pythonpath == "."` to `pyproject.toml`. Either way, the tests pick up the project's default venv, ignoring the one-time venv `uv run` creates to satisfy `--with` options.
> 
> I noticed the same thing. This line (no longer? I've used it successfully [elsewhere](https://github.com/atopile/fastapi-github-oidc/blob/main/.github/workflows/test.yml#L21)) works in my test actions workflow:
> 
> `uv run --with pytest-github-actions-annotate-failures pytest`

*mawildoer* solution helps me resolved the error. And i found removing `.venv` then sync again also work for me.

My environment is
```
uv 0.7.15 (4ed9c5791 2025-06-25)
pytest>=8.4.1
```
