### ISSUE TITLE
Nexus PyPi causing early exit on package resolution

### ISSUE THREAD

**Issue by JTCroft** [astral-sh/uv#7273]
I have an issue related to an internal nexus-hosted PyPi. When using a repo group in nexus the page returned when a package is NOT present in any of the PyPis grouped together in a repo group will cause `uv` to believe that the package WAS found in the repo but with no versions available, invariably causing it to fail to install anything hosted in any package index after the internal nexus one in resolution order

Unlike nexus repos, using repo groups means that when a package isn’t found it returns a page with `Links to <package>` and then no links below.

Would it be possible for uv to treat an empty list of files as the package not being found in the index and continue through any remaining extra-index-urls and the index-url?

this was with uv 0.4.8, caused by running `uv pip install <exernal package>` with a nexus repo group included in a uv.toml `extra-index-url = [“<internal nexus repo group>”]`

**Comment by zanieb** [comment]
Have you tried changing the index strategy? https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes

**Comment by JTCroft** [comment]
Thanks for suggesting that, it’s a much better solution

Happy this to be closed if you don’t think it is a uv bug since it’s kind of a nexus issue - but other nexus users may well see this behaviour where packages that don’t exist in the index will be ‘found’
