### ISSUE TITLE
 Failed to hardlink files: Issue with ruff cache

### ISSUE THREAD

**Issue by PhantomSpike** [astral-sh/uv#7285]
When I run `uv add` or `uv pip install` I get this warning:
```
░░░░░░░░░░░░░░░░░░░░ [0/6] Installing wheels...                                                                                                                                            warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
  ```
  and uv is very slow. What could be causing this?
  
  Could it be that the uv cache is somewhere different from my current directory? If so, how do I move/link it properly?
  
  Thanks!

**Comment by charliermarsh** [comment]
You can set `UV_CACHE_DIR` to some directory on the same drive as your project. You can run `uv cache dir` to view the current cache location too.

**Comment by notatallshaw-gts** [comment]
FYI, I need to set my cache to a different drive than my Python environment (for reasons), I use `UV_LINK_MODE=symlink` and it works great.

**Comment by Quba1** [comment]
Sorry for reviving this issue. Does `This may lead to degraded performance` part of the warning message refer to the uv performance or installed package performance?

**Comment by konstin** [comment]
This only affects uv's performance, not the installed packages.

**Comment by pplmx** [comment]
Hi @konstin,

I noticed the use of `$env:UV_LINK_MODE="symlink"`. Is this the configuration officially recommended by uv on Windows? If so, could you explain why it isn’t enabled by default?

Thanks for your insights!

**Comment by charliermarsh** [comment]
No, symlinks aren’t recommended. We recommend hard links, which is the default.

The issue with symlinks is that if you remove files from the cache or clear the cache, your environment will break. Hard links don’t have that problem.

**Comment by kamiertop** [comment]
On windows, I had the same problem, I used `uv cache dir` and found that the cache was in `C:Users\xxx\AppDataloca\pip`, and then I set the environment variables `UV_CACHE_DIR`, putting the cache directory and the project directory in a **same disk partition**. Also, I use `zsh` on windows, so I write env to `~/.vimrc`, hope it helps.

**Comment by rsconsuegra** [comment]
Sorry to open again this thread, but I am using uv in windows and, for reasons, I have multiple projects in different locations (E:, F: and G:, and cache is currently in C:\Users\xxx\AppData\Local\uv\cache), so right now I get the warning ` Failed to hardlink files;` in all the projects, and certainly I don't think having a cache in each disk would be the intended solution... or is it?

**Comment by pengyou200902** [comment]
> Sorry to open again this thread, but I am using uv in windows and, for reasons, I have multiple projects in different locations (E:, F: and G:, and cache is currently in C:\Users\xxx\AppData\Local\uv\cache), so right now I get the warning ` Failed to hardlink files;` in all the projects, and certainly I don't think having a cache in each disk would be the intended solution... or is it?

same situation here

**Comment by charliermarsh** [comment]
(If you have further questions, please redirect them to Discord or open a new issue; we prefer that folks don't comment on closed issues.)

**Comment by dima333750** [comment]
I fixed one warning by moving to disk C:
