### ISSUE TITLE
Relative paths in script sources don't work

### ISSUE THREAD

**Issue by SnirShechter** [astral-sh/uv#7292]
## The error
```
PS C:\whatever> uv run .\scripts\myscript.py
Reading inline script metadata from: .\scripts\myscript.py
error: path could not be converted to a URL: libs\mypackage
```
![image](https://github.com/user-attachments/assets/dcc2a159-33fa-478d-a2e8-417f51657d38)

## In short
Script sources (`[tool.uv.sources]`) use full paths, do not allow for relative paths e.g. `../libs/mypackage` and are thus not platform-agnostic and can't be used by multiple developers.

## In depth

Consider this script:
```python
from mypackage import hello

hello("John")
```

Running `uv add --script myscript.py ./libs/mypackage --editable` results in this:
```python
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "mypackage",
# ]
#
# [tool.uv.sources]
# mypackage = { path = 'C:\whatever\libs\mypackage', editable = true }
# ///
from mypackage import hello

hello("John")
```

But obviously `C:\...` is not platform agnostic, so to make it work for all developers I need to change it to `..\libs\mypackage`, but that doesn't work (see the error above)

**Comment by charliermarsh** [comment]
Thanks, these look like bugs.
