### ISSUE TITLE
uv run equivalent to python -m

### ISSUE THREAD

**Issue by johnkangw** [astral-sh/uv#7297]
Is it possible to add a flag to `uv run` to make it equivalent to what happens when we run `python -m`.  When running pytest using `uv run` it does not work because I have some relative imports I am using in some of the testing files. It works when I use a `python -m` command.

**Comment by zanieb** [comment]
Hi! This is a duplicate of https://github.com/astral-sh/uv/issues/6638

**Comment by zanieb** [comment]
I think we should add this though.

**Comment by johnkangw** [comment]
Oh nice, I did not realize this was a duplicate. Thanks @zanieb
