### ISSUE TITLE
uv equivalent to pipx inject

### ISSUE THREAD

**Issue by zachvalenta** [astral-sh/uv#7312]
I searched through issues but didn't find anything similar - apologies if there's already an issue that I missed.

pipx let's you install (['inject'](https://pipx.pypa.io/stable/#inject-a-package)) additional packages into an env e.g. add `psycopg2` into the env for `visidata` so you can connect to Postgres:
```sh
pipx install visidata
pipx inject visidata psycopg2
```

Does `uv` have this capability now or, if not, is it on the roadmap?

**Comment by zanieb** [comment]
I think we explicitly won't provide this — you should enumerate all the dependencies in the installation.

There's #3560 but I'm not sure if it's explicitly discussed.

**Comment by zachvalenta** [comment]
Based on the issue you linked, seems like the way this works in `uv` is via the [`--with`](https://docs.astral.sh/uv/concepts/tools/#including-additional-dependencies) arg, yes?

```sh
# pipx
pipx install visidata
pipx inject visidata psycopg2

# uv
uv tool install --with psycopg2 visidata
```

**Comment by zanieb** [comment]
Yep! This is covered in https://docs.astral.sh/uv/concepts/tools/#including-additional-dependencies — the RFC isn't necessarily exactly what was implemented.

**Comment by zanieb** [comment]
That's #6314
