### ISSUE TITLE
FR: Do not update PATH on `uv self update`.

### ISSUE THREAD

**Issue by ilyagr** [astral-sh/uv#7319]
https://docs.astral.sh/uv/getting-started/installation/#upgrading-uv currently explains that `uv self update` will attempt to update the user's PATH unless the environment variable `INSTALLER_NO_MODIFY_PATH=1` is set.

I think it shouldn't; if the user installed `uv` requesting that it doesn't modify the path, they probably don't expect it modified during an update. I suspect you're well aware of this, but I feel like having a thread for this that I and others could subscribe to might be nice.

It seems that https://docs.rs/axoupdater/latest/axoupdater does not support another behavior, but perhaps a feature could be added to it that sets `INSTALLER_NO_MODIFY_PATH=1` before it calls the installer script.

Thank you for resolving all the other related issues I previously reported, by the way! The speed with which this tool is evolving is impressive.

**Comment by zanieb** [comment]
Related https://github.com/astral-sh/uv/issues/5576 — though I think that requests that we don't update it at all during updates and this requests that we respect the option that was provide at install time?

**Comment by zanieb** [comment]
I think, generally, the shell profile files are changed on update because the new installer might have new target files.
