### ISSUE TITLE
[Feature request] Avoiding .venv in production

### ISSUE THREAD

**Issue by pkucmus** [astral-sh/uv#7342]
Related to: https://github.com/astral-sh/uv/issues/7341

When making a Docker image with my application I would like to achieve the equivalent of Poetry's `POETRY_VIRTUALENVS_CREATE=false` to use the only Python interpreter in the container. This would reduce need for consideration over the .venv directory being mixed in the host and in the container (as the container would not have one)

**Comment by jond01** [comment]
Don't the following satisfy your request:
* `--system` flag:
  https://docs.astral.sh/uv/reference/settings/#pip_system
* `UV_SYSTEM_PYTHON=true` environment variable:
  https://docs.astral.sh/uv/configuration/environment/

?

**Comment by zanieb** [comment]
Please see https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path and https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment

**Comment by zanieb** [comment]
This was addressed in https://github.com/astral-sh/uv/pull/6834

**Comment by pkucmus** [comment]
Sorry, I saw this but did not connect the dots that it's about that problem, for anyone else, https://github.com/astral-sh/uv/pull/6834#issuecomment-2319253359 this is a perfect solution.

**Comment by pkucmus** [comment]
> Don't the following satisfy your request:
> 
>     * `--system` flag:
>       [docs.astral.sh/uv/reference/settings#pip_system](https://docs.astral.sh/uv/reference/settings/#pip_system)
> 
>     * `UV_SYSTEM_PYTHON=true` environment variable:
>       [docs.astral.sh/uv/configuration/environment](https://docs.astral.sh/uv/configuration/environment/)
> 
> 
> ?

Don't see the `--system` flag in 0.4.9 but I do see --python-preference=only-system
but then when I set `ENV UV_PYTHON_PREFERENCE=only-system` `uv sync --frozen --no-install-project --no-dev` still creates `.venv`
`uv --system sync` errors out `error: unexpected argument '--system' found`
