### ISSUE TITLE
`uv run` spawns another process.

### ISSUE THREAD

**Issue by pkucmus** [astral-sh/uv#7343]
In the documentation `uv run hello.py` is used as an example (or the main way) on how to run a project. This assigns the PID 1 to uv and whatever uv spawns is another process - this is problematic when using Docker and need to send signals to your application, like [sending `SIGHUP`, `SIGTTIN`, `SIGTTOU` to your container to inform Uvicorn](https://www.uvicorn.org/deployment/#built-in) to do something. Docker will only send the signals to the process sunning under PID 1 ([here](https://www.kaggle.com/code/residentmario/best-practices-for-propagating-signals-on-docker) it's explained better then I ever could).

If the UV process can proxy all signals then I guess that would be fine but still I would not be too keen on running a different process in front of my web server, not for the reason of dependency management.

Might be related to: https://github.com/astral-sh/uv/issues/7342 if uv could install into a non-virtual env (container's only Python)

**Comment by zanieb** [comment]
You can easily bypass `uv run` in this context, with one of:

- `UV_PROJECT_ENVIRONMENT`: https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path
- Adding the `bin/` to the `PATH`: https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment
- Specifying the full path to your application, e.g., `./.venv/bin/foo`

There's some active discussion about signal handling in https://github.com/astral-sh/uv/pull/6738

**Comment by pkucmus** [comment]
My main concern of running the web server as the PID 1 process can be solved with the points you mentioned and I'll move the rest of the discussion into #6738.
