### ISSUE TITLE
Add `--system` flag to `uv sync` command to use it in Docker

### ISSUE THREAD

**Issue by rfsan** [astral-sh/uv#7344]
I have the current Dockerfile

```Dockerfile
FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
RUN apt-get update && \
    apt-get install -y git libgomp1 && \
    rm -rf /var/lib/apt/lists/*
ARG CODE=/app
WORKDIR $CODE
COPY pyproject.toml uv.lock ./
RUN --mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
    uv sync --frozen --no-cache --compile-bytecode --no-dev
COPY src/ src/
CMD [".venv/bin/python", "-m", "src.api_sample"]
```

I would like to install the dependencies using the system Python so that the final command is `CMD ["python", "-m", "src.api_sample"]`

I tried using `uv pip install -r pyproject.toml --system` but this approach does not use the `uv.lock` file

**Comment by Xdynix** [comment]
> To force uv to use the system Python, provide the `--python-preference only-system` option.

Maybe consider this?

Ref: <https://docs.astral.sh/uv/concepts/python-versions/#adjusting-python-version-preferences>

**Comment by zanieb** [comment]
Please see https://docs.astral.sh/uv/guides/integration/docker/#using-the-environment and https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path

This use-case should be resolved by https://github.com/astral-sh/uv/pull/6834
