### ISSUE TITLE
System-wide configuration files

### ISSUE THREAD

**Issue by tmct** [astral-sh/uv#7354]
Hi,

Does uv support global/system-wide configuration files, analogous to /etc/pip.conf? The [docs](https://docs.astral.sh/uv/configuration/files) only mention the project- and user- level.

Thanks,
Tom

**Comment by JamesMTSloan** [comment]
See #6742

**Comment by tmct** [comment]
Sorry for not finding that in my searches!

**Comment by tmct** [comment]
I will close this and watch that one, many thanks

**Comment by JamesMTSloan** [comment]
No worries, I just happened to have seen the linked issue before.
