### ISSUE TITLE
uv pip install reinstalls packages that are available via --system-site-packages

### ISSUE THREAD

**Issue by BubuOT** [astral-sh/uv#7358]
When creating a virtualenv (either with `python -m venv --system-site-packages` <dir>` or with `uv venv --system-site-packages` the packages installed in the system python installation are not recognized by uv at all. We then install a wheel into our venv, expecting uv to only download the missing dependencies. uv redownloeads and reinstalls a lot of additional packages which are already available in the system though. pip correctly installs only the missing packages.

Our targets are embedded devices which ship a python installation with most dependencies installed and updated via the firmware image, for custom deployments and prototyping we'd like an easy way to "overlay" the available system packages with newer versions or additional dependencies. (Also this happens via mobile network, so downloading an additional maybe 30MB of dependencies could be a big deal, depending on the connection quality)

Platform: linux-aarch64, uv 0.4.9

**Comment by charliermarsh** [comment]
We don't really support `--system-site-packages` -- it's the same as https://github.com/astral-sh/uv/issues/4466 etc. Instead you'd need to use `uv pip install --system` and other commands, or feel free to comment on https://github.com/astral-sh/uv/issues/4466.
