### ISSUE TITLE
Add support for remaining file extension aliases

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#7365]
See: https://github.com/pypa/pip/blob/111eed14b6e9fba7c78a5ec2b7594812d17b5d2b/src/pip/_internal/utils/filetypes.py#L8.

It's an identical change to #7201, but with a different set of aliases. Good first PR for anyone interested.

**Comment by Aditya-PS-05** [comment]
Hey Charlie, Please review my pull request.

**Comment by charliermarsh** [comment]
Thanks @Aditya-PS-05, I will take a look and fix the tar part if needed.
