### ISSUE TITLE
 Hopefully, you can consider using a global configuration file instead of relying solely on adding environment variables to modify configuration one

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#7385]
Hopefully, you can consider using a global configuration file instead of relying solely on adding environment variables to modify configuration one

**Comment by charliermarsh** [comment]
uv reads from user-level configuration files (e.g., `~/.config/uv/uv.toml`) -- see https://docs.astral.sh/uv/configuration/files/.
