### ISSUE TITLE
In  addition ,  uv can't  implement function of    running  script  commands  ,just  like    pdm run script  or  npm run script 

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#7386]
In  addition ,  uv can't  implement function of    running  script  commands  ,just  like    pdm run script  or  npm run script

**Comment by Super1Windcloud** [comment]
Except for its speed advantage, PDM cannot compete with UV. The experience in other aspects is top-notch. However, the next version of PDM will soon integrate UV. In time, PDM will be completely reborn.

**Comment by charliermarsh** [comment]
Thanks :) Follow this issue here which is focused on that kind of task runner / script runner capability: #5903
