### ISSUE TITLE
No interpreter found in system path or `py` launcher

### ISSUE THREAD

**Issue by michelkluger** [astral-sh/uv#7391]
❯ uv venv env
  × No interpreter found in system path or `py` launcher

❯ uv python install 3.11
warning: `uv python install` is experimental and may change without warning
Searching for Python versions matching: Python 3.11
Found existing installation for Python 3.11: cpython-3.11.9-windows-x86_64-none

❯ uv venv env
  × No interpreter found in system path or `py` launcher
  
details, uninstalled previous python from computer (also did not work with)
windows 11,  uv==0.4.10

**Comment by charliermarsh** [comment]
I think you're on an older version of uv (unintentionally). "warning: uv python install is experimental and may change without warning" was removed in 0.3.

**Comment by charliermarsh** [comment]
How did you install uv? I'd suggest uninstalling it and reinstalling.

**Comment by michelkluger** [comment]
> How did you install uv? I'd suggest uninstalling it and reinstalling.

let me try that, thank you for the prompt answer

**Comment by michelkluger** [comment]
solved most of my issue

but still I have

❯ uv sync
warning: `VIRTUAL_ENV=env` does not match the project environment path `.venv` and will be ignored
error: Querying Python at `\\?\C:\Users\MichelKluger\mypath\myproj\.venv\Scripts\python.exe` failed with exit status exit code: 103
--- stdout:

--- stderr:
No Python at '"C:\Users\MichelKluger\AppData\Roaming\uv\data\python\cpython-3.11.9-windows-x86_64-none\python.exe'
---


❯ uv pip install -r .\requirements-dev.txt
Audited 98 packages in 41ms

**Comment by michelkluger** [comment]
❯ uv python list
cpython-3.13.0rc2-windows-x86_64-none    <download available>
cpython-3.12.6-windows-x86_64-none       <download available>
cpython-3.11.10-windows-x86_64-none      C:\Users\MichelKluger\AppData\Roaming\uv\python\cpython-3.11.10-windows-x86_64-none\python.exe
cpython-3.10.15-windows-x86_64-none      <download available>
cpython-3.9.20-windows-x86_64-none       <download available>
cpython-3.8.20-windows-x86_64-none       <download available>
cpython-3.7.9-windows-x86_64-none        <download available>
pypy-3.10.14-windows-x86_64-none         <download available>
pypy-3.9.19-windows-x86_64-none          <download available>
pypy-3.8.16-windows-x86_64-none          <download available>
pypy-3.7.13-windows-x86_64-none          <download available>

**Comment by charliermarsh** [comment]
Can you try removing the `.venv` directory? They're likely using different Pythons.

**Comment by zanieb** [comment]
If you want to change the path of the target for `uv sync`, you need to set `UV_PROJECT_ENVIRONMENT=env`. However, I'd generally not recommend this. Is there a reason you need a non-default name?

**Comment by michelkluger** [comment]
> If you want to change the path of the target for `uv sync`, you need to set `UV_PROJECT_ENVIRONMENT=env`. However, I'd generally not recommend this. Is there a reason you need a non-default name?

sorry, I dont understand the question

I am just trying to use uv sync, but is not working as expected on windows (maybe I dont understand something), uv pip install works

**Comment by zanieb** [comment]
`uv sync` does not allow syncing to arbitrary active virtual environments, it targets the _project_ virtual environment which is at a fixed path (unless you configure the variable I shared). That's why you are getting a warning.

**Comment by michelkluger** [comment]
> `uv sync` does not allow syncing to arbitrary active virtual environments, it targets the _project_ virtual environment which is at a fixed path (unless you configure the variable I shared). That's why you are getting a warning.

make sense, thank you for the clarifications
