### ISSUE TITLE
Allow users to pre-define dependency metadata

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#7393]
For packages that don't declare static metadata, it can be a pain to require building the package just to resolve. For example, you might have a dependency that can't be built on ARM, but doesn't declare static metadata. In that case, users can't resolve on ARM, even if the dependency is never installed on ARM (i.e., it has an environment marker).

I think it'd be neat to allow users to define static metadata for their dependencies as an escape hatch, like:

```toml
[tool.uv.dependencies]
my-dependency = ["click>0.8"]
```

**Comment by YouJiacheng** [comment]
I planned to file this issue separately, haha.
![image](https://github.com/user-attachments/assets/b9d28a18-dcfb-46ac-ae6c-aac66fe80bfc)

**Comment by charliermarsh** [comment]
Yeah this would at least make it possible to `uv lock` without having to build Chumpy at all in your case :)

**Comment by YouJiacheng** [comment]
I think this should be beyond the direct dependency of the user's project. It should act as hand-crafted resolution rules.

**Comment by charliermarsh** [comment]
Yeah I think this should be "allowed" for any dependency.

**Comment by zanieb** [comment]
Does this override existing metadata or only get used when not available? I'm a little so-so on the naming because it collides with general dependency groups but otherwise it sounds cool.

**Comment by charliermarsh** [comment]
I think it would override... It would also allow you to (e.g.) remove dependencies unlike `--overrides`, if you know all packages that were pulling them in.

**Comment by charliermarsh** [comment]
(I agree `tool.uv.dependencies` is bad.)
