### ISSUE TITLE
Can cache prune remove unpacked source trees?

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#7394]
Building wheels from source leaves unpacked source trees after the build, such as this for cython:

`~/.cache/uv/built-wheels-v3/pypi/cython/3.0.11/4c57QS8T3uI0oPlqtRE1W/cython-3.0.11.tar.gz`

In this case it's 127 MB after build, 85 MB of which are in the ./build/ subtree with build artifacts.
If these files are not necessary after the .whl is produced and cached, can the build tree be removed? For example by uv cache prune.

**Comment by charliermarsh** [comment]
Hmm... We do need them in case we have to re-build the wheel. For example, if you then try to install `cython` on a different Python version, we would need to rebuild (since the `cython` wheels are Python-minor-version specific, like 
`Cython-3.0.11-cp39-cp39-win32.whl`).

**Comment by charliermarsh** [comment]
Perhaps we could add a setting for this, though...? Or make it part of `uv cache prune --ci`?

**Comment by charliermarsh** [comment]
I think we should remove these in `uv cache prune --ci`.

**Comment by bluss** [comment]
Ok I understand now, they are downloaded and unpacked where they are, and the build happens in the tree. It sounds good to remove them in some mode at least of pruning. I realize the process for building wheels don't leave a lot of control for how to handle details of the build (cleaning the tree after build -- removing build intermediates -- and before reusing the unpacked source for another build?)
