### ISSUE TITLE
Run a file without .py extension

### ISSUE THREAD

**Issue by sequoiayoav** [astral-sh/uv#7396]
if I make this file and name it `example.py`

```py
#!/usr/bin/env uv run --quiet

# /// script
# dependencies = [
#     "requests",
# ]
# ///

from requests import get

resp = get("https://example.com")
print(resp)
```
```sh
chmod +x example.py
```
running `example.py` in my shell just works, 
But if I rename the file to just `example` and try to run it, uv doesn't recognize it as a python file.
this isn't a bug, just want some help on this. (or recommendations)
thanks!

**Comment by charliermarsh** [comment]
Does `uv run python ./example` work as expected?

**Comment by kbernhagen** [comment]
Possible workaround:
```
#!/usr/bin/env uv run -q --no-project --python 3.12 --with requests
```

It would be nice if `uv run` had option `--script` that did not need to have an explicit path to the script.

**Comment by kbernhagen** [comment]
> Does `uv run python ./example` work as expected?

Does not work for me
```sh
% uv run python /usr/local/bin/fahctl 
Missing python3-websocket library
```

**Comment by kbernhagen** [comment]
The best thing would probably be for python3 itself to understand PEP 723.

**Comment by charliermarsh** [comment]
We may want an explicit `--script` option to treat a path as PEP 723 script without sniffing the extension.

**Comment by zanieb** [comment]
Seems reasonable to me.

**Comment by sequoiayoav** [comment]
Sounds like the perfect solution

**Comment by charliermarsh** [comment]
`--script` now exists to power this use-case.
