### ISSUE TITLE
uv init --script

### ISSUE THREAD

**Issue by jbvsmo** [astral-sh/uv#7402]
According to the docs, you can `uv add --script foo bar.py` and it will add the PEP 723 boilerplate to an existing script

https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies

There is no way to do this without a adding a dependency nor without an existing python file. E.g. this kinda works as a uv init

```
touch foo.py
uv add --script foo.py requests --python 3.12
```

It would also be nice to add the main function and `if __name__ == "__main__":` 

So I propose `uv init --script foo.py` to exist and be consistent with `uv init foo`.

Rationale: PEP 723 syntax is very forgettable and I don't know of a single person or [ai bot](https://chatgpt.com/share/66e634db-4ccc-8002-9fcd-c47143723d0b) that can write it by heart

Thank you!

**Comment by zanieb** [comment]
I'm supportive of this

**Comment by charliermarsh** [comment]
Added in https://github.com/astral-sh/uv/pull/7565.
