### ISSUE TITLE
Support for mirrors when installing Python versions

### ISSUE THREAD

**Issue by dillydill123** [astral-sh/uv#7403]
Apologies if this was brought up before or exists as a feature already, but I could not find either in documentation or existing issues.

It would be useful to have the ability to pass a flag or environment variable to tell `uv` where to download pre-built python interpreters as opposed to always choosing `python-build-standalone`. This would be useful for machines which may not access to the internet. In this case a mirror could be supplied.

**Comment by Werni2A** [comment]
The `UV_PYTHON_INSTALL_MIRROR` environment variable may help you in this case. Search for the term in the official [docs](https://docs.astral.sh/uv/configuration/environment/) for more details.

**Comment by zanieb** [comment]
Yep! We support this via that variable and `UV_PYPY_INSTALL_MIRROR`.

**Comment by zanieb** [comment]
We can probably call this out in the Python version concept doc if we don't already.
