### ISSUE TITLE
uv sync --no-sources doesn't install dev dependencies

### ISSUE THREAD

**Issue by GalOzRlz** [astral-sh/uv#7406]
Hi! Maybe this is a feature I'm missing.

uv sync --no-sources is supposed to remove dev dependencies? ( those that are set in [tool.uv.dev-dependencies])

when I run a normal uv sync it does install them - but with the --no-sources it removes them (acts like I have the --no-dev flag) --  but I don't want to do this inside my docker.

I'm running uv 0.4.10 (690716484 2024-09-13)

**Comment by charliermarsh** [comment]
I think I consider this a bug. Thanks for pointing it out.
