### ISSUE TITLE
uv GitHub actions on a server by SSH, not on the runner

### ISSUE THREAD

**Issue by bolinocroustibat** [astral-sh/uv#7424]
Is there a way to run the [uv GitHub actions](https://docs.astral.sh/uv/guides/integration/github/) on a server accessible by SSH, instead of running them on the GitHub Actions runner?

If not, is it recommended to install uv on a production server, so that it speeds up deployments installs?

**Comment by zanieb** [comment]
> If not, is it recommended to install uv on a production server, so that it speeds up deployments installs?

I would recommend doing this! There's no reason to use the GitHub action if you're not on GitHub Actions.
