### ISSUE TITLE
`uv add --branch` is broken solely on a particular repo

### ISSUE THREAD

**Issue by Xmaster6y** [astral-sh/uv#7433]
## Problem

`uv` doesn't resolve the good commit when using `--branch <branch>` but `@<branch>` does (the repo: https://github.com/Xmaster6y/vec_noise)

When I use:
```
uv add git+https://github.com/Xmaster6y/vec_noise@refacto 
```

I get (good rev):

```
Updated https://github.com/Xmaster6y/vec_noise (1e281ec)
Updated https://github.com/Xmaster6y/vec_noise (1e281ec)
```

But when I use:
```
uv add git+https://github.com/Xmaster6y/vec_noise --branch refacto
```

I get:

```
Updated https://github.com/Xmaster6y/vec_noise (7c3865d)
...
```

### Same for `--rev`

Using
```
uv add git+https://github.com/Xmaster6y/vec_noise --rev 1e281ec
```
gives :
```
Updated https://github.com/Xmaster6y/vec_noise (7c3865d)
...
```

### Specificities

- The repository is a second order fork
- The original repository is fairly old -> a fork belongs to the original repository network

## What didn't work

- I tried to add from a branch on a fork -> worked as expected
- I tried to add from a branch on a second order fork -> worked as expected

## Details

- Plateform: MacOS (Darwin 23.5.0 arm64)
- `uv` version: uv 0.4.10 (690716484 2024-09-13)

**Comment by zanieb** [comment]
Thank you for the well-written report!

**Comment by zanieb** [comment]
As a note, `7c3865d` is the head commit on `main` and the upstream repository.

**Comment by Xmaster6y** [comment]
Puzzling edit:

I previously add:

```
uv add git+https://github.com/astral-sh/ruff --branch sys-version-info
```

giving:

```
 Updated https://github.com/astral-sh/ruff (bb12fe9d0)
 Updated https://github.com/astral-sh/ruff (61a5a86a7)
 ...
 ```
 
 But now:
 
 ```
uv add git+https://github.com/astral-sh/ruff --branch sys-version-info
```

giving:

```
 Updated https://github.com/astral-sh/ruff (bb12fe9d0)
 ...
 ```

**Comment by zanieb** [comment]
The difference in behavior appears to be because of https://github.com/astral-sh/uv/blob/cafc1f986a6efda0c2f384e63930333a812c9ea4/crates/uv/src/commands/project/add.rs#L244-L245

We only pass the `requirements` in here:

```
[crates/uv/src/commands/project/add.rs:240:5] &requirements = [
    Package(
        "git+https://github.com/Xmaster6y/vec_noise",
    ),
]
```

but when you use the `--branch` syntax the source is tracked separately from the package requirement.

**Comment by Xmaster6y** [comment]
Is this wanted/expected?

**Comment by Xmaster6y** [comment]
My later observation seems unrelated to my first issue

This happen when my `uv.lock` is not sync.

### To reproduce:

Run (should break, otherwise interupt it mid-course):
```
uv add git+https://github.com/astral-sh/ruff --branch sys-version-info 
```

Run the command again (not calling `uv sync/lock`):

```
uv add git+https://github.com/astral-sh/ruff --branch sys-version-info 
```

Does it deserve another issue?

**Comment by zanieb** [comment]
We later fail at

https://github.com/astral-sh/uv/blob/cafc1f986a6efda0c2f384e63930333a812c9ea4/crates/uv/src/commands/project/add.rs#L316-L324 

> Is this wanted/expected?

No, I don't think the behavior we're seeing is wanted or expected. I'm just debugging and sharing some notes.
