### ISSUE TITLE
uv add `numpy` on legacy PyPI mirror does not respect Python version

### ISSUE THREAD

**Issue by cambriancoder** [astral-sh/uv#7435]
platform: `linux`
`uv` version: `0.4.10`
caveat: I'm using a private mirror (Nexus) for PyPI that only supports the "simple" repository API, this not an issue when using the public PyPI. 

Running `uv add numpy` when the Python version is set to `>=3.9` fails. 

`uv` will discover the latest version of `numpy` is `2.1.1` but then fail to find any wheels for py39 (`numpy` 2.1.* dropped py39 support), causing it to attempt to build from source, which then fails. 

Adding `--no-build-package numpy` also fails because it still resolves the version to `2.1.1` and then fails to find compatible wheels. Explicitly setting `numpy<2.1.0` does succeed in adding the package but requires I know ahead of time what python versions a package supports.

I would expect `uv add` to attempt to find the latest compatible version? For comparison, running the same command with `poetry` succeeds in adding numpy to the project with version 2.0.2 (albeit 100x slower). 

Is this is known issue? Is `poetry` doing something terribly inefficient, like downloading every version until it finds one that works?

**Comment by charliermarsh** [comment]
I'm guessing that the API response from the mirror doesn't include `requires-python`? I don't quite know what Poetry would be doing there. Could you share the logs (redacted is fine) with `--verbose`?

**Comment by cambriancoder** [comment]
I can't provide the logs sorry, the network is air-gapped, but I did check the HTML output for the package and it doesn't provide a `requires-python` (or `data-requires-python`) tag.
