### ISSUE TITLE
 × No interpreter found for Python 3.11.9 

### ISSUE THREAD

**Issue by Praveensenpai** [astral-sh/uv#7452]
```uv venv --python 3.11.9```

when I use this on windows it works fine

but when I use it on linux ubuntu it shows 
 × No interpreter found for Python 3.11.9 
 
 
 In both linux and windows I'm using python 3.12.3

**Comment by charliermarsh** [comment]
Can you confirm the output of `uv --version` on both machines?

**Comment by zanieb** [comment]
In a clean Docker container on the latest version, we download Python 3.11.9 and create an environment

```
❯ docker run -it ghcr.io/astral-sh/uv:0.4.10-bookworm-slim uv venv --python 3.11.9
Using Python 3.11.9
Creating virtualenv at: .venv
``
