### ISSUE TITLE
`uv install` installs incompatible package for python version

### ISSUE THREAD

**Issue by timvink** [astral-sh/uv#7462]
First of all, `uv` is 🔥 ! Really enjoying working with it!

I am able to install packages with `uv pip install` that I cannot install with `pip install` because the python version is incompatible. Consider the [dataclasses ](https://pypi.org/project/dataclasses/) library which `Requires: Python >=3.6, <3.7` : 

```bash
python -V
# Python 3.10.14

pip install dataclasses==0.8
# Looking in indexes: http://<redacted>@<redacted>/artifactory/api/pypi/<redacted>/simple, https://pypi.org/simple
# ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
# ERROR: Could not find a version that satisfies the requirement dataclasses==0.0.8 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
# ERROR: No matching distribution found for dataclasses==0.0.8

uv pip install dataclasses==0.8 --verbose
# DEBUG uv 0.4.8
# DEBUG Searching for Python interpreter in system path
# DEBUG Found `cpython-3.10.14-linux-x86_64-gnu` at `/anaconda/envs/redacted/bin/python3` (conda prefix)
# DEBUG Using Python 3.10.14 environment at /anaconda/envs/redacted/bin/python3
# DEBUG Acquired lock for `/anaconda/envs/redacted`
# DEBUG At least one requirement is not satisfied: dataclasses==0.8
# DEBUG Using request timeout of 30s
# DEBUG Solving with installed Python version: 3.10.14
# DEBUG Solving with target Python version: >=3.10.14
# DEBUG Adding direct dependency: dataclasses==0.8
# DEBUG No cache entry for: https://artifactory<redacted>
# DEBUG Found fresh response for: https://pypi.org/simple/dataclasses/
# DEBUG Searching for a compatible version of dataclasses (==0.8)
# DEBUG Selecting: dataclasses==0.8 [compatible] (dataclasses-0.8-py3-none-any.whl)
# DEBUG Found fresh response for: https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl.metadata
# DEBUG Tried 1 versions: dataclasses 1
# DEBUG Split specific environment resolution took 0.104s
# Resolved 1 package in 107ms
# DEBUG Requirement already cached: dataclasses==0.8
# DEBUG Unnecessary package:  # <-- long list of these
# Installed 1 package in 0.70ms
#  + dataclasses==0.8
# DEBUG Released lock at `/tmp/uv-0ef8d6f78fde4fb3.lock`
```

Using uv `0.4.10` on ubuntu. I have confirmed this problem in two different systems (one with custom index, one without). And also on uv versions `0.4.9`, `0.4.8`, `0.4.7`. And I tried using `uv pip install --python 3.10.14` explicitly.

This has some downstream problems. In my case, the `dataclasses` dependency appeared in my `requirements.txt` file after `uv pip compile`, and the ML model logged to `mlflow ` with the `requirements.txt` file, could not be loaded back, because `pip` could not install the dependency.

**Comment by zanieb** [comment]
Thanks for the well written report!

We ignore upper bounds on Python versions during resolution, so we will resolve as though the `dataclasses` only declares `Requires: Python >=3.6`. The reasons for this are quite complicated, there's some context in https://github.com/astral-sh/uv/issues/4022

I'm  think you may need to declare a lower bound on dataclasses, which would be ideal anyway if that version truly doesn't support Python 3.10.

**Comment by timvink** [comment]
Thanks for the context! Not sure there is much we can do then.

I cannot declare the lower bound myself, as in my case `dataclasses` is a downstream dependency that was resolved during `uv pip compile`.

For anyone hitting this issue, my workaround was using `uv` in the inference environment :)

**Comment by zanieb** [comment]
@timvink you can add a lower bound using constraints or overrides https://docs.astral.sh/uv/concepts/resolution/#dependency-constraints
