### ISSUE TITLE
export dependencies from an extra only

### ISSUE THREAD

**Issue by mivanit** [astral-sh/uv#7476]
Have `uv export` support exporting only the requirements listed in an extra, without package dependencies or dev dependencies.

# Use Case

For CI, it's common to have a separate job which only does some lint checks or something similar, where the package itself and dependencies are not required. With poetry, I'd do something like
```
[tool.poetry.group.lint.dependencies]
pycln = "^2.1.3"
ruff = "^0.4.8"
```
and then
```
poetry export --only lint --output lint-requirements.txt
```
and then in CI just pip install from this `lint-requirements.txt` file. This significantly speeds up setting up the CI environment for these checks.

# Feature suggestion

add an option to `uv export` called `--only-extra <extra>` or something similar, which only resolves the dependencies listed under the passed extra.

`uv export --no-emit-project` prevents the current project from being emitted as a dep, but the current project's dependencies still are. `--only-dev` added in #7367 is very close to this, but unless there is a way to group dev dependencies that I'm unaware of it still doesn't fully support what I'm requesting here (ie `pytest` is in the dev dependencies but not required for just running `ruff`)

This is a pretty niche use case, and doesn't actually restrict functionality (only slightly less CI time wasted).

# potential workarounds

I haven't yet tried the `--only-dev` option from #7367 since the latest release at time of writing is `0.4.10`, but it may be possible to have dev dependencies be empty, and just have those deps be in extras called `dev-test` and `dev-lint` or something, and use `--only-dev` in combination with `--extra dev-lint`

**Comment by nsoranzo** [comment]
Looks like this should be solved by https://github.com/astral-sh/uv/pull/8332 ?
