### ISSUE TITLE
 uv generate-shell-completion powershell script error in uv 0.4.11.

### ISSUE THREAD

**Issue by FishAlchemist** [astral-sh/uv#7482]
**UV Version:** uv 0.4.11 (e5dd67f58 2024-09-17)
**Error:** A 'using' statement must appear before any other statements in a script.
(Error message. Since my computer's language is not English, I'm just translating it.)
I think it's because the new version added uvx completion (https://github.com/astral-sh/uv/pull/7388), but it didn't consistently place "using" statements at the beginning.

**Comment by charliermarsh** [comment]
\cc @bluss

**Comment by bluss** [comment]
Ok, not good, that means not all shells csn handle having this output in one stream. I think uv an uvx completions then needs to be in separate commands, like `uvz --generate-shell-completion`
