### ISSUE TITLE
Warning using pre-commit and uv

### ISSUE THREAD

**Issue by Kludex** [astral-sh/uv#7489]
I'm running ruff on the pre-commit job on the GitHub CI.

```
      - id: ruff
        name: Ruff
        entry: uv run ruff
        args: ["check", "--fix"]
        types: [python]
        language: system
      - id: ruff-format
        name: Ruff Format
        entry: uv run ruff
        args: [format]
        language: system
        types: [python]
```

But it causes this:

<img width="986" alt="Screenshot 2024-09-18 at 11 52 53" src="https://github.com/user-attachments/assets/6e59b941-6c1d-45d4-b776-97cbaca97c51">

Using `uvx` doesn't solve the issue, it just changes the message to get the tools cache.

How can I not see the warning?

**Comment by charliermarsh** [comment]
I don't think this message should be user-facing \cc @zanieb

**Comment by Kludex** [comment]
We do use the `--verbose` flag on `pre-commit`. FYI

**Comment by zanieb** [comment]
Yeah idk why this is user-facing, maybe because it could take a while?
