### ISSUE TITLE
uv build setuptools setup should default to or honor index-url pip config

### ISSUE THREAD

**Issue by blackduckx** [astral-sh/uv#7501]
Running `uv build` command without the `[build-system]` section defined in `pyproject.tom` installs `setuptools` by default.

Right now it connects directly to *pypi* and does not honor the `pip` `index-url` configuration in the *toml* config files.

-> Defaulting to `pip` `index-url` seems to be the expected default
-> Corporate Users mostly have to go through a pypi proxy

*Context*

* uv version: 0.4.11
* `uv.toml` configured with corporate pypi proxy 
* `uv pip install` command running fine (Installation through the corporate pypi proxy)

*Failure*
```
(XXX) > uv build

Building source distribution...
error: Failed to install requirements from `setup.py` build (resolve)
  Caused by: No solution found when resolving: setuptools>=40.8.0
  Caused by: Could not connect, are you offline?
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://pypi.org/simple/setuptools/)
  Caused by: client error (Connect)
  Caused by: dns error: Hôte inconnu. (os error 11001)
  Caused by: Hôte inconnu. (os error 11001)
```

**Comment by charliermarsh** [comment]
Builds do use the user-provided index. For example, given:

```toml
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
hello = "foo:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
index-url = "https://test.pypi.org/simple"
```

`uv build` correctly fails, because it can't find `hatchling` on the Test PyPI.

My guess is you have an error in your configuration. Can you share a reproducible example?

Note that you need to use `[tool.uv]` in your configuration, not `[tool.uv.pip]`.

**Comment by blackduckx** [comment]
@charliermarsh thanks for taking care of my case. I used an old version of the documentation to setup my `uv.toml`

I confirm the [current documentation on configuration is accurate](https://docs.astral.sh/uv/configuration/files/)

I simply moved the `uv.toml` file from

```
[pip]
index-url = xxx
```
To
```
index-url = xxx
```
And it now does work fine. Sorry for the trouble. Closing this ticket.

**Comment by charliermarsh** [comment]
No worries!
