### ISSUE TITLE
uv version should allow you to increment the project version like the poetry version command

### ISSUE THREAD

**Issue by krishan-patel001** [astral-sh/uv#7507]
Currently the `uv version` command only prints out the current version. This could be updated to take in an argument or major, minor or patch or a custom version to increment the version in the `pyproject.toml` similarly to how poetry does this.

If the current version was 1.0.0 in the pyproject.toml the commands would change that value as follows
- `uv version patch` -> 1.0.1
- `uv version minor` -> 1.1.0
- `uv version major` -> 2.0.0
- `uv version 1.1.1.dev101212312` -> 1.1.1.dev101212312

**Comment by zanieb** [comment]
Please remember to search for existing issues https://github.com/astral-sh/uv/issues/6298
