### ISSUE TITLE
Feature Request: `uv run --with-source`

### ISSUE THREAD

**Issue by ahal** [astral-sh/uv#7518]
This would be the opposite of the `--no-sources` flag, where we would temporarily resolve dependencies using a source that is *not* defined in `pyproject.toml`.

One use case for this is when you're working on something in one project, that's blocking some feature work in another project. Sometimes the upstream work needs to be tested in the downstream project. Currently you can accomplish this by temporarily adding a source that points at a local path or a pull request, e.g:
```
[tool.uv.sources]
foo = { path = "/path/to/my/wip" }
```

But it's all too easy to forget to remove this again and editing the config file twice just to run one command is a bit clunky. I'd love to see something like:
```
uv run --with-source "foo=path:/path/to/my/wip"
```
as a way to temporarily *add* a source. I think this would complement `--no-sources` nicely.  I don't have any strong preferences on the format of the argument.

**Comment by zanieb** [comment]
We layer environments so I think this should just work with `uv run --with /path/to/my/wip ...`. Is that not the case for you?

**Comment by ahal** [comment]
Thanks, I got tunnel visioned in on the sources config that it didn't occur to me to check `--with`. This works great!
