### ISSUE TITLE
Support `--with-editable` in `uv tool install` 

### ISSUE THREAD

**Issue by gaborbernat** [astral-sh/uv#7528]
Would it be possible to specify the editable flag for the with options too? Something like:

```
 uv tool install -e tox@/Users/bernat/git/github/tox  \
					   --with-editable tox-uv@/Users/bernat/git/github/tox-uv  \
						--force-reinstall --force
```

**Comment by charliermarsh** [comment]
Yeah I think this probably _should_ exist, it may be an oversight \cc @zanieb in case you know otherwise.

**Comment by zanieb** [comment]
Yeah I presumed the contribution at https://github.com/astral-sh/uv/pull/6744 did this but it only was `uv tool run`.

**Comment by kyoto7250** [comment]
@zanieb 
Let me work on it!

**Comment by kyoto7250** [comment]
I think I'll be able to publish a PR on the weekend.

**Comment by kyoto7250** [comment]
I still have the will to work on this issue, but I've been busy with work for a while, so I don't think I'll be able to do it this month.

If there is someone who is interested, it would be nice if that person could be in charge.
