### ISSUE TITLE
Add pip shortcut to venv script

### ISSUE THREAD

**Issue by PaleNeutron** [astral-sh/uv#7534]
I'm using uv 0.2.15 at ubuntu 22.04 and I found that if I create virtual env with uv venv, and active it with ` source .venv/bin/activate`, the pip command is still global pip.

This will cause a lot of problem if I forget which project's venv is managed by uv. The most common story is installed a new package to venv and not work.

A shortcut of `uv pip` named `pip` to venv is a really vital feature for me.

**Comment by xqm32** [comment]
I just add an alias `pip` to `uv pip` globally in my `.zshrc`, and use `pip3` as the "real" pip. This makes me never incorrectly install some packages outside my venv :-)

**Comment by zanieb** [comment]
@weihenglim's response matches our official recommendation.
