### ISSUE TITLE
UV exported requirements with editable can't be installed with `pip`

### ISSUE THREAD

**Issue by ion-elgreco** [astral-sh/uv#7535]
When exporting the UV lockfile into a requirements.txt with `uv export > requirements.txt`, will not allow you to install it with pip due to this error:

```
ERROR: The editable requirement file:///home/<redacted>/<redacted> (from -r requirements.txt (line 3)) cannot be installed when requiring hashes, because there is no single file to hash.
```

Minimal exported UV requirements.txt:
```
# This file was autogenerated by uv via the following command:
#    uv export
-e .
aiohappyeyeballs==2.4.0 \
    --hash=sha256:55a1714f084e63d49639800f95716da97a1f173d46a16dfcfda0016abb93b6b2 \
    --hash=sha256:7ce92076e249169a13c2f49320d1967425eaf1f407522d707d59cac7628d62bd
```
**- uv version: 0.4.12**

**Comment by sbidoul** [comment]
This is a pip limitation, that is tracked in https://github.com/pypa/pip/issues/4995. There is a also a related issue for VCS URLs: https://github.com/pypa/pip/issues/6469.

**Comment by charliermarsh** [comment]
I think you should use `--no-hashes` here (`uv export --no-hashes`).
