### ISSUE TITLE
Python installation from local folder

### ISSUE THREAD

**Issue by andreas-vester** [astral-sh/uv#7539]
Using ``uv`` behind a corporate firewall isn't always easy. One of the problems I am facing is related to ``uv python install``. I am not allowed to simply connect to github.com to download files using a command line program. What I can do, on the other hand, is to browse to the GitHub release page and manually download the required cpython tar.gz file.

I am wondering if I can point ``uv python install`` to the local folder where I saved the cpython archive file?

**Comment by zanieb** [comment]
You can use `UV_PYTHON_INSTALL_MIRRO` to point to a directory that matches the structure of the URL.

See #6950
