### ISSUE TITLE
Is is a problem sharing uv cache between different versions

### ISSUE THREAD

**Issue by freand76** [astral-sh/uv#7547]
We use uv in a CI/CD environment where the .cache is shared within a build node.

When building from the tip of the repository the uv version will always be increasing 0.1.x -> 0.2.x - > ... > 0.4.x
But when running older change set och when recreating an old build there might be a jump for version 0.4.x to version 0.2.x (version decreasing).

Do you consider it a problem sharing the cache between uv versions?
Is it necessary that the version is **static** or **strictly increasing** when using the cache?

**Comment by zanieb** [comment]
Yeah it is important that the version is strictly increasing. While we generally try to avoid this, there are cases where old uv versions will not be able to read the cache from a new version. The version should not need to be static though.

**Comment by charliermarsh** [comment]
It should _typically_ be ok because we version the cache buckets, so if we change the schema, we'll use a different cache version. But there are occasional bugs (like we saw in 0.4.10) that would make that not the case. I would say, in general, it should work -- modulo bugs.

**Comment by freand76** [comment]
Thank you for quick answer!

We will change our setup to force the uv cache folder to **.cache/uv_<uv_version>/**

Consider this one closed/resolved for our sake ;-)
