### ISSUE TITLE
How do "unpin" a Python version from my project?

### ISSUE THREAD

**Issue by big88chungus** [astral-sh/uv#7555]
Hi everyone,

I am using uv for the first time and a beginner at pretty much everything. So I have made a Python project and downloaded 3.10..., 3.12... and 3.13... Python. At first, 3.10 was pinned and I could only use that. Then I pinned 3.12 and now I can only use 3.12. Is there a way where I can remove the pin feature, so I can switch between versions better?

Thank you! :)

**Comment by zanieb** [comment]
You can remove the `.python-version` file to remove the pin, but it's only a default and you can always pass `--python <version>` to any uv command to switch versions regardless.

**Comment by zanieb** [comment]
Welcome to the project!

**Comment by big88chungus** [comment]
thank you for the answer
