### ISSUE TITLE
`uv export --only-dev` does not work if used with `--frozen`

### ISSUE THREAD

**Issue by mikeleppane** [astral-sh/uv#7577]
If I want to export only development dependencies using `--only-dev`, it does not seem to work with the `frozen` option.

```bash
uv export --frozen --only-dev -o requirements-dev.txt
```
This is the output I get; only the header and the actual dependencies are missing.
```txt 
 # This file was autogenerated by uv via the following command:
 # uv export --frozen --only-dev
```
But when I remove `--frozen,` it works. I don't want `uv` to touch the lock file when I only want to export dependencies.

**Comment by charliermarsh** [comment]
I can take a look today.

**Comment by mikeleppane** [comment]
@charliermarsh I was wondering whether we should avoid re-locking the project when exporting. The `uv` will only update the lock file when requested or not allow it at all. What's the use case for updating the lock file during export? It would be surprising if I didn't know the behavior.

**Comment by charliermarsh** [comment]
The whole uv project API works that way (`uv lock`, `uv sync`, `uv run`, `uv export`) -- we make sure that the environment is always consistent with your dependencies. You can always skip it with `--frozen` (or ensure that it's up-to-date, but don't modify iy, with `--locked`).

**Comment by charliermarsh** [comment]
This is actually working as expected for me:

```
❯ uv export --frozen --only-dev
# This file was autogenerated by uv via the following command:
#    uv export --frozen --only-dev
anyio==4.5.0 \
    --hash=sha256:c5a275fe5ca0afd788001f58fca1e69e29ce706d746e317d660e21f70c530ef9 \
    --hash=sha256:fdeb095b7cc5a5563175eedd926ec4ae55413bb4be5770c424af0ba46ccb4a78
exceptiongroup==1.2.2 ; python_full_version < '3.11' \
    --hash=sha256:47c2edf7c6738fafb49fd34290706d1a1a2f4d1c6df275526b62cbb4aa5393cc \
    --hash=sha256:3111b9d131c238bec2f8f516e123e14ba243563fb135d3fe885990585aa7795b
idna==3.10 \
    --hash=sha256:12f65c9b470abda6dc35cf8e63cc574b1c52b11df2c86030af0ac09b01b13ea9 \
    --hash=sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3
sniffio==1.3.1 \
    --hash=sha256:f4324edc670a0f49750a81b895f35c3adb843cca46f0530f79fc1babb23789dc \
    --hash=sha256:2f6da418d1f1e0fddd844478f41680e794e6051915791a034ff65e5f100525a2
typing-extensions==4.12.2 ; python_full_version < '3.11' \
    --hash=sha256:1a7ead55c7e559dd4dee8856e3a88b41225abfe1ce8df57b7c13915fe121ffb8 \
    --hash=sha256:04e5ca0351e0f3f85c6853954072df659d0d13fac324d0072316b67d7794700d
```

Can you help provide a minimal example I can reproduce?

**Comment by charliermarsh** [comment]
No prob!
