### ISSUE TITLE
Investigate slow first range request

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#758]
The first request of fetching range metadata is notably slow, in the no cache case sometimes the single biggest item (https://github.com/astral-sh/puffin/pull/744#issuecomment-1875153595). We should investigate why that is and if we can optimize it.

**Comment by charliermarsh** [comment]
@konstin - Do you think this was just the thing where we had to add the extra `await`, to kick-start the threading?

**Comment by konstin** [comment]
yeah this is not a problem anymore
