### ISSUE TITLE
Bug/Feature with uv pip install from github

### ISSUE THREAD

**Issue by freand76** [astral-sh/uv#7581]
When using **uv pip install** from a github repository, a working SHA from any of the repository forks will be picked up as valid.

_Example:_

uv pip install "python-usbtmc @ git+https://github.com/python-ivi/python-usbtmc@7c15a9d2138160024c4069ecf4b2edc33f15e40e"

_Problem/Feature:_

The repo **https://github.com/python-ivi/python-usbtmc** does not contain a commit with the SHA **7c15a9d2138160024c4069ecf4b2edc33f15e40e** but the fork **https://github.com/FOSSBOSS/python-usbtmc** does, i.e. **uv pip install** will install a packet from another repository than expected.

Tested on uv 0.4.10

**Comment by charliermarsh** [comment]
I'll take a look at this.

**Comment by charliermarsh** [comment]
I think this is a consequence of GitHub's storage model for repositories. All GitHub repositories and their forks share the same backing storage, so you can access commits from forks through any sibling repository. For example, you can see that commit here: https://github.com/python-ivi/python-usbtmc/commit/7c15a9d2138160024c4069ecf4b2edc33f15e40e.

I need to look into whether other installers also behave this way, and what we can do to avoid it (if desired).

**Comment by freand76** [comment]
As I wrote in the heading it might be a feature, but at the same time it might also be a security issue in this (maybe unlikely) scenario:

uv pip install <trusted package> @ <link to trusted git repository>@<SHA to an evil forked repository>

Great that you will look into this!

**Comment by charliermarsh** [comment]
I agree with your assessment, though it may be somewhat unsolvable / inherent to GitHub. If you run this, you will successfully fetch the commit in that fork:
```
git fetch --force --update-head-ok https://github.com/python-ivi/python-usbtmc +7c15a9d2138160024c4069ecf4b2edc33f15e40e:refs/remotes/origin/HEAD
```

**Comment by freand76** [comment]
Interesting, then it is out of our / your hands. 

Issue can be closed.
