### ISSUE TITLE
Sync with system python broken in 0.4.13

### ISSUE THREAD

**Issue by b-phi** [astral-sh/uv#7582]
For some use cases, I had been using `UV_PROJECT_ENVIRONMENT=/usr/local` to sync with the system python based on this comment https://github.com/astral-sh/uv/pull/6834#issuecomment-2319253359. With 0.4.13, this now breaks with 
> Project virtual environment directory `/usr/local/` cannot be used because it is not a virtual environment and is non-empty

Which was added in https://github.com/astral-sh/uv/pull/7527.

I've looked through the docs, but can't find any official recommendation for what path to use to sync with the system python `/usr/local/bin/python`.

**Comment by zanieb** [comment]
Sorry about this. The problem is #7522 

I have a fix up in #7585

**Comment by zanieb** [comment]
This will be fixed in the next release (sometime today)

New integration test in #7591

**Comment by b-phi** [comment]
Thank you!
