### ISSUE TITLE
Enable CLI package installed with `uv add` to be accessed from the virtual env

### ISSUE THREAD

**Issue by PatrickAlphaC** [astral-sh/uv#7587]
Let's say I add the following package that is a CLI:

First, let's setup and activate a virtual environment.

```bash
uv init
uv venv
source .venv/bin/activate
```

Then, add our package that has an executable. 

```bash
uv add moccasin
```

Assuming `moccasin` has an executable named `mox`, if I do the above, I am able to run the tool with:

```bash
uv run mox --help
```

However, I cannot do:

```
mox --help
```

By itself. If I instead run:

```
uv pip install moccasin
```

I am then able to run it's executable in the virtual environment without `uv run`:

```
mox --help
```

It would be nice if `uv add` had a flag to expose the executable without calling `uv run`. Maybe like:

```
uv add moccasin --expose-script
```

Or something.

**Comment by charliermarsh** [comment]
Did you activate the virtual environment in `.venv` prior to running `mox --help`?

**Comment by PatrickAlphaC** [comment]
@charliermarsh yes. I can send a video if that's helpful?

**Comment by charliermarsh** [comment]
Sure, anything to help reproduce would be appreciated.

**Comment by PatrickAlphaC** [comment]
https://github.com/user-attachments/assets/21080fc0-e502-4735-bd37-c033957530bd

**Comment by PatrickAlphaC** [comment]
I also updated the original issue so that the steps are more specific (included the virtual environment setup to make reproducing it more straightforward)

**Comment by charliermarsh** [comment]
Hopefully my answer helped but let me know if you have any follow-up questions.

**Comment by PatrickAlphaC** [comment]
I still had issues here, but maybe something else is going on. Thanks for being so attentive. 

The active virtual environment was/is in the `.venv` directory, and that was the active directory. Perhaps something else was happening if you're unable to reproduce.
