### ISSUE TITLE
pynmstar failure to compile sub package

### ISSUE THREAD

**Issue by varioustoxins** [astral-sh/uv#7589]
HI 
if I do `uv tool install nef-pipelines` it all appears to work
However, when I run the command `nef` [the main entry point to my application in nef-pipelines], I get

`raise ImportError('Could not import cnmrstar sub-module! Your installation appears to be broken.')`

This appears to be because the dependant c file from the package pynmstar.cnmrstar doesn't appear to be compiled properly. I appear to have had similar but different problems  as the c component seems to require the latest setup tools to compile. So when using pip I have to do 

`pip install --upgrade wheel setuptools`

and sometimes

`pip install  --upgrade wheel setuptools backports.tarfile`

to get the installation to work, this is on a centos 7 system but I have had this problem elsewhere

this is with the latest uv at time of writing  0.4.13

**Comment by varioustoxins** [comment]
this is also discussed here, binary wheels are provided so it shouldn't need to build the c

**Comment by charliermarsh** [comment]
Can you share the output of `uv tool install` with `--verbose`?

**Comment by varioustoxins** [comment]
here you go
[output.txt](https://github.com/user-attachments/files/17078117/output.txt)

**Comment by charliermarsh** [comment]
So for one: `pynmrstar` only ships wheels for Python 3.9 and earlier. You're on Python 3.12, so I think it's correct that it's building from source.

**Comment by charliermarsh** [comment]
See [here](https://pypi.org/project/pynmrstar/3.3.2/#files) (look at `cp39` etc.).

**Comment by charliermarsh** [comment]
It seems to install ok for me:

```
❯ nef
Usage: nef [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.

Commands:
  chains     - carry out operations on chains
  csv        - read [rdcs]
  deep       - read deep [peaks]
  echidna    - read echidna data [peaks]
  entry      - carry out operations on the nef file entry
  fasta      - read and write fasta sequences
  fit        - carry out fitting operations [alpha]
  frames     - carry out operations on frames in nef files
  globals    - add global options to the pipeline [use save as your last...
  header     - add a header to the stream
  help       - help on the nef pipelines tools and their usage
  loops      - carry out operations on loops in nef frames
  mars       - read and write mars [shifts and sequences]
  modelfree  - write modelfree [relaxation data]
  nmrpipe    - read nmrpipe [peaks shifts & sequencess]
  nmrstar    - read NMR-STAR [sequences & shifts]
  nmrview    - read and write nmrview [peaks, sequences & shifts]
  pales      - read and write pales/dc [rdcs]
  pdbx       - read pdb [sequences]
  peaks      - carry out operations on nef peaks
  rpf        - write rpf shifts
  save       - save the entries in the stream to a file / files or stdout...
  series     - carry out operations on a data series
  shifts     - carry out operations on shifts [average]
  shiftx2    - read shiftx2 data [shifts]
  shifty     - write shifty [shifts]
  simulate   - simulate data
  sink       - read the current stream and don't write anything
  sparky     - read sparky files [shifts]
  stream     - stream a nef file
  talos      - read and write talos files [shifts & restraints]
  test       - run the test suite
  xcamshift  - write xcamshift for xplor [shifts]
  xeasy      - read xeasy files [flya dialect: sequence]
  xplor      - read xplor [sequences, dihedral & distance restraints]
```

Do you see a failure when running just `nef`? Or when you run `nef` within a project, some specific subcommand, etc.?

**Comment by varioustoxins** [comment]
just running it as a command as you did...

**Comment by charliermarsh** [comment]
Are you able to put together a reproduction, e.g., with Docker?

**Comment by varioustoxins** [comment]
Hi Charlie

I should be able to, but it will take a little while as I am currently on holiday till the 24th and I will need an hour or two to sort something out.

gary

**Comment by charliermarsh** [comment]
No problem, thanks for following up. Enjoy your holiday.

**Comment by varioustoxins** [comment]
hi Charlie so back from holidays illness and family emergencies

here is a docker build file to make a working centos 7 system

FROM centos:7

RUN useradd -u 1000 -p test test

RUN cat /etc/yum.repos.d/CentOS-Base.repo

RUN sed -i -e 's/mirrorlist.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i -e 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
RUN sed -i -e 's/#baseurl/baseurl/' /etc/yum.repos.d/CentOS-Base.repo

RUN cat /etc/yum.repos.d/CentOS-Base.repo

RUN yum -y groupinstall 'Development Tools'

RUN su test

RUN echo pwd

USER test

WORKDIR /home/test

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

RUN source $HOME/.local/bin/env


CMD ["/bin/bash"]


once run  with

docker build  -f uv_nef_test.docker --progress=plain -t uv_nef_test  .

login with 

docker run  -it uv_nef_test

and do 

uv tool install --python 3.12 nef-pipelines

this does a complete installation of nef-pipelines but when nef is run it reproduces the error with installing pynmrstar described above 

have fun
gary

**Comment by varioustoxins** [comment]
I did some ore digging...

with the same image if I do

    1  uv python install 3.12
    2  uv venv test
    3  source test/bin/activate
    4  uv pip install pynmrstar
    5  python

and then 

>>> import pynmrstar
>>> import cnmrstar

it all seems to be fine

**Comment by charliermarsh** [comment]
Ack, thanks.

**Comment by charliermarsh** [comment]
If you look at the build logs:

```
DEBUG /usr/bin/aarch64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -fPIC -I/home/test/.cache/uv/builds-v0/.tmpYyg39I/include -I/home/test/.local/share/uv/python/cpython-3.12.8-linux-aarch64-gnu/include/python3.12 -c c/cnmrstarmodule.c -o build/temp.linux-aarch64-cpython-312/c/cnmrstarmodule.o -funroll-loops -O3
DEBUG warning: build_ext: building extension "cnmrstar" failed: command '/usr/bin/aarch64-linux-gnu-gcc' failed: No such file or directory
```

**Comment by charliermarsh** [comment]
Oh sorry, I need to emulate x86

**Comment by charliermarsh** [comment]
Ok, so it looks like the issue is that `nef` ultimately installs `pynmrstar==3.3.2` due to its dependency graph. And that version is reported as failing on that operating system: https://github.com/bmrb-io/PyNMRSTAR/issues/126.

If you look at the build logs:

```
DEBUG c/cnmrstarmodule.c: In function 'str_to_lowercase':
DEBUG c/cnmrstarmodule.c:149:5: error: 'for' loop initial declarations are only allowed in C99 mode
DEBUG      for(int i = 0; orig[i]; i++){
DEBUG      ^
DEBUG c/cnmrstarmodule.c:149:5: note: use option -std=c99 or -std=gnu99 to compile your code
DEBUG warning: build_ext: building extension "cnmrstar" failed: command '/usr/bin/cc' failed with exit code 1
```

So, it seems like a somewhat irresolvable problem.

What you _can_ do is add an `overrides.txt` file:

```
pynmrstar>=3.3.3
```

And then run `uv tool install nef-pipelines --overrides overrides.txt`.

That would instruct uv to ignore any dependency declarations and use a newer version of `pynmrstar`. But other than that, I think you need to find a way for `nef` to raise its `pynmrstar` constraint.
