### ISSUE TITLE
Interference with local python releases

### ISSUE THREAD

**Issue by krstp** [astral-sh/uv#7604]
First, thank you for a great tool which is `uv`. I am really enjoying it.

However, I am running into issue. Conflicts with existing python installations. It turns out:
- I have system wide python `3.12.6` version, probably installed with `brew`
- I have other python releases (multiple versions) installed with `pyenv`

Now a gist:
- I do have `3.12.4` installed with `uv`, no problem here; everything works as desired.
- when specifying in `.python-version` version `3.12.6` regardless of what command I invoke with `uv` I get the following error:
```
pyenv: version `3.12.6' is not installed (set by /Users/<user>/<dev_path>/sample_git_project/.python-version)
```

I was trying to go through `~/.config/uv` and `~/.local/` but I am not finding any `json` or other conf file that would allow me to re/point to the right python release `~/.local/share/uv/python/cpython-3.x...` 

Any tips would be appreciated.

**Comment by zanieb** [comment]
Hm that looks like a pyenv error message not a uv error message. Can you share more of the error with the `-v` flag?

**Comment by krstp** [comment]
This is also not clear to me. After running `uv venv` the `.venv` is created and looking inside it I see `uv` creates `pyvenv.cfg`, but despite even changing it to the install of my liking say `3.12.6` path instead of `3.12.4` it will still revert to `.4` 🤔 

And indeed, weirdly `uv` picks up `pyenv` version not the `uv` installed version and I am having trouble finding where could this be defined in `uv` 🤔 

`uv -v venv` does not yield any additional input.

The solution here would be to force `uv` to use its own install.... and sorry, but I will not be uninstalling `pyenv`, this is what I used to rely on and still large part of my solution run on it, before I battle-test the `uv` ;)

**Comment by krstp** [comment]
Rather my main question is... where does the `uv` config live where it picks up given python version? When I type `uv python list` it will show me what version are installed where, but still even if `3.12.6` is the one from `uv` it will still somehow pick up previously installed version with `brew`... btw: `pyenv` does not have `3.12.6` in its repository (or I havent updated mine)... so this is also weird that it reference `pyenv` 🤔

**Comment by krstp** [comment]
Some more insight:
```
~/<path>/sample_git_project> uv python --python-preference managed install 3.12.6
Searching for Python versions matching: Python 3.12.6
Found existing installation for Python 3.12.6: cpython-3.12.6-macos-aarch64-none

~/<path>/sample_git_project > uv venv 3.12.6 
Using Python 3.12.4
Creating virtual environment at: 3.12.6
Activate with: source 3.12.6/bin/activate

~/<path>/sample_git_project> cat 3.12.6/pyvenv.cfg                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       │ File: 3.12.6/pyvenv.cfg
   1   │ home = /Users/<user>/.local/share/uv/python/cpython-3.12.4-macos-aarch64-none/bin
   2   │ implementation = CPython
   3   │ uv = 0.4.13
   4   │ version_info = 3.12.4
   5   │ include-system-site-packages = false

  ~/<path>/sample_git_project>

**Comment by zanieb** [comment]
Sounds like you want to create a `uv.toml` for your user (https://docs.astral.sh/uv/configuration/files/)

Then change the `python-preference` to `only-managed` (https://docs.astral.sh/uv/reference/settings/#python-preference)

**Comment by zanieb** [comment]
`uv venv 3.12.6` creates a directory called `3.12.6`. You want `uv venv --python 3.12.6`

**Comment by krstp** [comment]
So...
- created `~/.config/uv/uv.toml` so it will be used globally, the content of the file is:
```
python-preference = "managed"
```
- I also copied the same file into project directory

Then I run `python --version` as well as `uv venv --python 3.12.6` and in each case I get:
```
pyenv: version `3.12.6' is not installed (set by /Users/<path>/sample_git_project/.python-version)
```

**Comment by krstp** [comment]
Update:

I have manually disabled `pyenv` from the whole env: `PATH=$(echo $PATH | tr ':' '\n' | grep -v pyenv | tr '\n' ':' | sed 's/:$//')`
then `uv venv --verbose`
This way I get feedback on 3.12.6 avaibility:
```
Using Python 3.12.6
Creating virtual environment at: .venv
DEBUG Removing existing directory
Activate with: source .venv/bin/activate
```
but `source .venv/bin/activate` doesn't do a thing, such as:
```
> python --version                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
zsh: command not found: python
```
on the other hand:
```
> .venv/bin/python3.12 --version                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
Python 3.12.6
```
checking `python` installation path more:
```
> which python
python not found

> which python3
/opt/homebrew/bin/python3
```

So in summary, now `.venv` carries right python version, but global aliases to `python` and `python3` will not recognize it 🤔

**Comment by krstp** [comment]
OK, never mind. I opened a fresh terminal and reloaded `.zshrc` ... whatever I have setup up upon `deactivation` it still seems to stay into somehow initialized under the hood pyenv (this is my global setup), but at least now everything works. I will close it for how. If this comes back I will reopen.

**Comment by krstp** [comment]
One detail should be added here for reference, the folder I was tested it in was nested in the other folder that already had `uv init`; this means it was double nested `.venv` without activation and I believe this was party the reason why it was referencing external (one level up) `.venv`.

I hope this helps to pin point the exact `uv` behavior.

**Comment by SwatGetmann** [comment]
I don't know if that helps, but I had the same issue on Ubuntu, right after `uv init`. What helped me is removing `.python-version` file (with a single line `3.13` in it) and then run `uv sync` - it worked and initialized venv with CPython 3.13.3 (which is the latest I have downloaded).
