### ISSUE TITLE
there is no version of certifi==2024.8.30

### ISSUE THREAD

**Issue by robinjhuang** [astral-sh/uv#7607]
uv: 4.14 on Windows

Called this: `python.exe -m uv pip install -r C:\Users\...\requirements.compiled`

Got this error. I am confused because certifi 2024.8.30 DOES exist on pypi.

```
[2024-09-21 11:25:01.188] [error] stderr:   × No solution found when resolving dependencies:
   Because there is no version of certifi==2024.8.30 and you require
      certifi==2024.8.30, we can conclude that your requirements are
      unsatisfiable.
```

requirements.compiled:
```
# This file was autogenerated by uv via the following command:
#    uv pip compile C:\Users... --emit-index-annotation --emit-index-url --index-strategy unsafe-best-match -o C:\Users\...requirements.compiled --override C:\Users\..override.txt
--index-url https://pypi.org/simple
--extra-index-url https://download.pytorch.org/whl/cu121

aiohappyeyeballs==2.4.0
    # via
    #   --override C:/Users/robin/electron/assets/override.txt
    #   aiohttp
    # from https://pypi.org/simple
aiohttp==3.10.5
    # via
    #   --override C:/Users/robin/electron/assets/override.txt
    #   -r requirements.txt
    # from https://pypi.org/simple
aiosignal==1.3.1
    # via
    #   --override C:/Users/robin/electron/assets/override.txt
    #   aiohttp
    # from https://pypi.org/simple
attrs==24.2.0
    # via
    #   --override C:/Users/robin/electron/assets/override.txt
    #   aiohttp
    # from https://pypi.org/simple
certifi==2024.7.4
    # via
    #   --override C:/Users/robin/electron/assets/override.txt
    #   requests
    # from https://pypi.org/simple
    ```

**Comment by zanieb** [comment]
I think you'll need to provide the `--index-strategy unsafe-best-match` (as in the header of the file)

See https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes for details

**Comment by robinjhuang** [comment]
Thanks for the quick response. @zanieb 

Why is `unsafe-best-match` needed? I thought the default `first-match` behavior is to search all the indexes until a match is found? If it cannot find it on the `https://download.pytorch.org/whl/cu121` url, it should look on pypi simple?

 The error makes it seem like it cannot find the match on any index?

**Comment by zanieb** [comment]
I think the error message could be improved. With `first-match` if there's _another_ version of the package on the first index we won't look at further indexes for that packages (to defend against dependency confusion attacks).

**Comment by robinjhuang** [comment]
So it found another version of the package and stopped looking. Thanks for explaining!

**Comment by zanieb** [comment]
I'll be adding a hint to the error message explaining this soon.
