### ISSUE TITLE
can't install jax[tpu]

### ISSUE THREAD

**Issue by GallagherCommaJack** [astral-sh/uv#7616]
here's a snippet to reproduce

```
uv add jax==0.4.33 --extra tpu --prerelease=allow -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

and here's the error:

```
  × No solution found when resolving dependencies:
  ╰─▶ Because there is no version of libtpu-nightly==0.1.dev20240916 and jax[tpu]==0.4.33 depends on
      libtpu-nightly==0.1.dev20240916, we can conclude that jax[tpu]==0.4.33 cannot be used.
      And because your project depends on jax[tpu]==0.4.33, we can conclude that your project's requirements are unsatisfiable.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and
        syncing.
```

fix suggested in #2010 doesn't seem to work, doing `uv pip install` has the same error

**Comment by charliermarsh** [comment]
You probably need to add `libtpu-nightly==0.1.dev20240916+nightly`, I guess? Just looking at the releases here: https://storage.googleapis.com/jax-releases/libtpu_releases.html

**Comment by GallagherCommaJack** [comment]
that's painful... pip can figure it out automatically, why can't uv?

**Comment by charliermarsh** [comment]
Local version identifiers are hard to get right and we don't support the full spec (the semantics / behaviors break a lot of assumptions about version-solving). You can read more here: https://docs.astral.sh/uv/pip/compatibility/#local-version-identifiers.
