### ISSUE TITLE
uv sync does not respect [tool.uv.pip] settings

### ISSUE THREAD

**Issue by GalOzRlz** [astral-sh/uv#7617]
Hello again! I believe this might be another issue, but if i have misunderstood the documentation please let me know.

I have this in my pyproject.toml file:
[tool.uv.pip]
resolution = "lowest-direct"

However I am getting higher resolution results with "uv sync" than what I get with "uv sync --resolution lowest-direct"

Am I missing something?

**Comment by charliermarsh** [comment]
You need to remove the “pip” part — so use [tool.uv] instead of [tool.uv.pip]. The latter only applies to uv pip commands; the former applies everywhere.

**Comment by zanieb** [comment]
See also https://docs.astral.sh/uv/configuration/files/#configuring-the-pip-interface
