### ISSUE TITLE
uv tool shouldn't use Python from homebrew version directories

### ISSUE THREAD

**Issue by frostming** [astral-sh/uv#7634]
On a macos machine with homebrew python installed, when installing executables using `uv tool install`, the base interpreter of the venv points to a python inside homebrew's version directory, for example:

```
❯ cat '/Users/fming/Library/Application Support/uv/tools/posting/pyvenv.cfg' -p
home = /opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/bin
implementation = CPython
uv = 0.2.23
version_info = 3.12.4
include-system-site-packages = false
```

And the `bin/python` also symlinks to the same interpreter.

This is subject to breakage when users upgrade the version of `python@3.12` formula, because the new intepreter will be in a different directory. It's a huge pain when user run `brew upgrade` and suddenly all venvs become broken.

To compare, this is what pipx creates:

```
home = /opt/homebrew/opt/python@3.12/bin
include-system-site-packages = false
version = 3.12.6
executable = /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/bin/python3.12
command = /opt/homebrew/opt/python@3.12/bin/python3.12 -m venv --without-pip /Users/fming/.local/pipx/venvs/posting
```

**Comment by frostming** [comment]
ok, the issue actually lies in `uv venv`, where it should not resolve symlinks for the python executable passed in:

```
$ uv venv .venv -p /opt/homebrew/opt/python@3.12/bin/python3
$ ls -l .venv/bin/python
lrwxr-xr-x  1 fming  staff    96B  9 23 11:56 .venv/bin/python -> /opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/bin/python3.12
```

**Comment by zanieb** [comment]
I believe this is a duplicate of https://github.com/astral-sh/uv/issues/1640

**Comment by zanieb** [comment]
And yeah, sorry this sounds painful.

**Comment by frostming** [comment]
Yeah, that is duplicate. Closing this now.
