### ISSUE TITLE
implement uv pip config

### ISSUE THREAD

**Issue by woutervh** [astral-sh/uv#7636]
I've been searching in the uv docs and issue-tracker, but I did not find my answer.
Apologies if I overlooked something.

As a pip-user, I  regularly use  "pip config list" to display the config pip is actually seeing.
see https://pip.pypa.io/en/stable/cli/pip_config/

## Questions:
 -  is there currently a way to see what config uv is actually using (after merging several sources)?
 -  is there a plan to implement something like "pip config" 

# Usecase
I'm currently  troubleshooting why an (private) index-url in pyproject.toml does not have any effect:

```
[tool.uv]
# see https://docs.astral.sh/uv/reference/settings/
index-url = "https://__token__:<TOKEN>@gitlab.com/api/v4/groups/<GROUPID>/-/packages/pypi/simple"

```

> uv --version
0.4.15

**Comment by agustinvalencia** [comment]
Similar case, I couldn't manage to set an self-hosted pypi repository. This pushed me back to poetry
Unfortunately I cannot share logs as it is company related, but back your issue up

**Comment by wimglenn** [comment]
Hi @zanieb, could this use a stable serialization format for ease of use with a deserializer? Something like TOML or [RON](https://github.com/ron-rs/ron), perhaps?
