### ISSUE TITLE
Support checking `uv.lock` aligns with latest changes to `pyproject.toml`

### ISSUE THREAD

**Issue by butterlyn** [astral-sh/uv#7639]
Request for a feature to check that no (relevant) changes to `pyproject.toml` have been made since `uv.lock` was last updated.
For reference, this is implemented in Poetry via the command `poetry check --lock` (previously under `poetry lock --check`).

**Comment by BurntSushi** [comment]
Does `uv lock --locked` work for you?

**Comment by zanieb** [comment]
We might want to add an alias for `--locked` in the `uv lock` command — `--locked` exists to match the rest of the commands but it's non-obvious what it means.

**Comment by charliermarsh** [comment]
I think everything you've outlined there is also true of `uv lock --locked`.

**Comment by zanieb** [comment]
Yeah similarly:

```
❯ uv lock --locked --offline
Resolved 1 package in 2ms

❯ uv add anyio --frozen

❯ uv lock --locked --offline
Resolved 4 packages in 5ms
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
```

**Comment by butterlyn** [comment]
Thank you :) will use `uv lock --locked --offline` in that case

Reading the command description ("Assert that the `uv.lock` will remain unchanged"), I didn't pick up that this was the intended usage... if it's outlined in the docs then I missed it

**Comment by zanieb** [comment]
I'll follow up with some improvements here.

**Comment by danyeaw** [comment]
If I set a constraint on a dependency, like `dependencies = [ 'exceptiongroup>=1.0.0; python_version < "3.11"',]`, then running `uv lock --locked --offline` results in an error:

```
Using CPython 3.12.6 interpreter at: /opt/hostedtoolcache/Python/3.12.6/x64/bin/python
  × No solution found when resolving dependencies:
  ╰─▶ Because only exceptiongroup{python_full_version < '3.11'}<1.0.0 is
      available and your project depends on exceptiongroup{python_full_version
      < '3.11'}>=1.0.0, we can conclude that your project's requirements are
      unsatisfiable.
```

**Comment by zanieb** [comment]
We presume we can't query the index to discover more versions of `exceptiongroup` — it sounds correct that we fail there?

**Comment by danyeaw** [comment]
Do I need to query / build the index somehow before running the `--locked --offline` command, then?

**Comment by zanieb** [comment]
@danyeaw what's your goal? If the lockfile is up to date, I don't think we'll query the index and the command should succeed. If not, it'll fail.

**Comment by danyeaw** [comment]
@zanieb I have one extra dependency for my project that is only applicable for older versions of Python. I want to then check the lock file integrity in CI, and it fails with the error above. The lock file is up to date.

**Comment by hbelmiro** [comment]
Native uv requires uv sync --locked which attempts to sync the environment. My tool performs the static check you are looking for.

https://github.com/hbelmiro/uv-lock-check
