### ISSUE TITLE
is it possible to add a source directory to a project?

### ISSUE THREAD

**Issue by ophiry** [astral-sh/uv#7646]
I want to add either the projects source directory - expecting it to be added to sys.path of the venv

similar to the effect of pip install -e .

my assumption was that uv add -editable . would do this, but it doesn't seem to work

**Comment by ophiry** [comment]
for future use, adding the lines:

```
[tool.uv]
package = true

```

**Comment by ophiry** [comment]
follow up:
is it possible to add an external directory (in this case - the parent directory)?

the use case is a monorepo with several different apps
they are basically standalone applications, but the internal imports rely on fully qualified names based on the repo root directory

for example:
a/main.py
a/lib/somelib.py
b/main.py
b/lib/somelib.py

where a/main.py has:
import a.lib.somelib

a and b have different dependencies, so relying on a single pyproject.toml file will be problematic

**Comment by NicholasPini** [comment]
> follow up: is it possible to add an external directory (in this case - the parent directory)?
> 
> the use case is a monorepo with several different apps they are basically standalone applications, but the internal imports rely on fully qualified names based on the repo root directory
> 
> for example:
> 
> ```
> a/main.py
> a/lib/somelib.py
> b/main.py
> b/lib/somelib.py
> ```
> 
> where a/main.py has: `import a.lib.somelib` a and b have different dependencies, so relying on a single pyproject.toml file will be problematic

I would also like to know if something like this is possible. I can add an external package using `uv add`, but it's a bit annoying that despite appearing in the toml file, this local package is not in `syspath`.

**Comment by flipbit03** [comment]
I believe you might be able to get by with something like this
```toml
[tool.setuptools]
py-modules = ["<main_package>", "<your>", "<other>", "<packages>"]
```

**Comment by ezyang** [comment]
Sorry, adding a comment here because this is the top result for "uv add directory use source directly". In my case, I wanted to add a local directory to a uv project as a dependency using its source code directly,  for a case where I needed to temporarily vendor a dependency. `uv add --editable --reinstall-package PATH/TO/PACKAGE` is probably what you want here (don't forget the editable!)
