### ISSUE TITLE
An invalid netrc file does not produce a warning

### ISSUE THREAD

**Issue by mathialo** [astral-sh/uv#7685]
I recently migrated one of our projects from poetry to uv, and one thing that made me stumble was a syntax error in my netrc file. Uv would just silently ignore the error and move on as if the netrc file did not exist, which made it a bit hard to figure out what was going on.

I think a better approach would be if the [`Netrc::new()`](https://github.com/astral-sh/uv/blob/84e5f6e871f344aa8b414c52bf95b22a992b382d/crates/uv-auth/src/middleware.rs#L33) call returns a _parsing error_, to log a warning about it before ignoring it, to let users know why the netrc file is being ignored.

**Comment by zanieb** [comment]
Seems reasonable, but we'd want to be careful to only display this once and only if we needed credentials.
