### ISSUE TITLE
Allow trusted-host in requirements source file

### ISSUE THREAD

**Issue by gma2th** [astral-sh/uv#7702]
## Description 

uv allows to specifiy `--index-url` in the requirements source file for `uv pip install` or `uv pip compile`.
However it doesn't allow to specify `--trusted-host`.
This is useful when the host doesn't support https.

## Example

```
$ cat req.in
--index-url https://pypi.org/simple

$ uv pip install -r req.in 
Audited 1 package in 1ms

$ cat req.in
--index-url https://pypi.org/simple
--trusted-host pypi.org

$ uv pip install -r req.in
error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement at req.in:2:1
```

```
uv version
uv 0.4.16 (e81ed8ec5 2024-09-24)
```

**Comment by zanieb** [comment]
Generally we don't want to add options to requirements files and it seems less than ideal to do so for trusting an insecure host. Why not pass the option during invocation?

**Comment by gma2th** [comment]
To not having to pass it every time one want to install/compile the requirements.

**Comment by zanieb** [comment]
Yeah but can you see how it is a security concern to allow that?

**Comment by charliermarsh** [comment]
Yeah I'd prefer not to support this. It doesn't seem like the right security / usability tradeoff. You can already put this in your `pyproject.toml` if you want to avoid passing it repeatedly.
