### ISSUE TITLE
Can't install pypi package dtale

### ISSUE THREAD

**Issue by kjyv** [astral-sh/uv#7703]
Hey there,
I'm trying to install [dtale](https://github.com/man-group/dtale) with a simple pyproject.toml running `uv sync` (.venv deleted, .cache/uv deleted). Even if it is the only package, I see this error:
`error: distribution kaleido==0.2.1.post1 @ registry+https://pypi.org/simple can't be installed because it doesn't have a source distribution or wheel for the current platform`

Installing with `uv pip install dtale` work fine though and the same package combination works well with pipenv.
I'm on macOS 15.0, uv 0.4.16.

**Comment by kjyv** [comment]
Ok, thank you for the detailed explanation. So the contraint fixes our problem but I guess it's not ideal if users like me run into this and the error message is not saying much about how to go forward. Rather than changing the resolver for the sync which I guess is tricky for all platforms with such packages, could this case be detected by uv and a more specific error message shown?

**Comment by charliermarsh** [comment]
I think this is a case of the more general #7816.

**Comment by LuchiLucs** [comment]
I'm trying to install the package `connectorx` on `py3.9` but it fails it `uv add`. What are the available options here? I also checked [7816](https://github.com/astral-sh/uv/issues/7816) and [7435](https://github.com/astral-sh/uv/issues/7435) but I would like to know if there is a recommended option

**Comment by konstin** [comment]
@LuchiLucs Can you please open a new issue with a minimal reproduction of your example and information about your platform?

**Comment by LuchiLucs** [comment]
@konstin Sure, sorry about this.
