### ISSUE TITLE
Request: ability to `uv pip install` the `dev-dependencies`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#7719]
Multiple of my teammates are not fully integrated with `uv sync`, and just want to install the core package editably with the [`dev-dependencies`](https://docs.astral.sh/uv/reference/settings/#dev-dependencies) from a `pyproject.toml`'s `[uv.tool]`.

Can we have some way for `uv pip install` to install `dev-dependencies`?

My best idea for this is something like `uv pip install -e .[dev]`, if there is no `dev` extra, will fall back on `dev-dependencies`.

Disclaimer: this may be considered in https://github.com/astral-sh/uv/issues/3560 or https://github.com/astral-sh/uv/issues/4730

**Comment by zanieb** [comment]
You can use `uv export --only-dev | uv pip sync -`

**Comment by jamesbraza** [comment]
Okay sounds good, thank you @zanieb ! 👍
