### ISSUE TITLE
How to get `dev-dependencies` in a few different `uv` repos at once

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/uv#7720]
We have a few repos that center on `uv` (with `dev-dependencies`). I have a teammate who uses one virtual environment for all projects, and he wants to install:
- All repos editably
- All repos' `dev-dependencies`

Doing something like:

```bash
python -m venv .venv && source .venv/bin/activate && pip install uv
cd repo_a
uv sync
cd ../repo_b
uv sync
```

Doesn't work because `uv sync` doesn't seem to respect the parent folder's `venv`.

This is a total question, but how can `uv` support this use case of multiple editable installs with separate `dev-dependencies`?

**Comment by zanieb** [comment]
You could set [`UV_PROJECT_ENVIRONMENT`](https://docs.astral.sh/uv/concepts/projects/#configuring-project-packaging) and use `uv sync --inexact`

**Comment by jamesbraza** [comment]
Okay thank you, that gets me _much_ closer, but still not quite there:

```bash
python -m venv .venv && source .venv/bin/activate && pip install uv
cd repo_a
UV_PROJECT_ENVIRONMENT=../.venv uv sync --inexact
cd ../repo_b_that_depends_on_repo_a
UV_PROJECT_ENVIRONMENT=../.venv uv sync --inexact
```

The issue is the second `uv sync` of `repo_b_that_depends_on_repo_a` will uninstall the editable install of `repo_a` for a non-editable install.

Is there some way to have the second `uv sync` not clobber the editable install of `repo_a`?

**Comment by zanieb** [comment]
Of course :) `--no-install-package repo_a` in the second invocation should work?

**Comment by jamesbraza** [comment]
Ah why am I bad at reading `--help`, I promise I was looking for some arg like that. Thank you again, closing this out
