### ISSUE TITLE
[Error]stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by sdbds** [astral-sh/uv#7726]
command: uv pip install hdbscan==0.8.38.post1
platform:windows
version:uv 0.4.16 (e81ed8ec5 2024-09-24)

```
error: Failed to prepare distributions Caused by: Failed to fetch wheel: hdbscan==0.8.38.post1 
Caused by: Failed to run `C:\Users\qinglongshengzhe\AppData\Local\uv\cache\builds-v0\.tmp4iKplS\Scripts\python.exe` 
Caused by: stream did not contain valid UTF-8
```

**Comment by Paillat-dev** [comment]
Same with `uv add git+https://github.com/feldberlin/timething.git`

**Comment by charliermarsh** [comment]
I'm going to close in favor of #7733 which has more info.

**Comment by charliermarsh** [comment]
Should be fixed by https://github.com/astral-sh/uv/pull/7757.
