### ISSUE TITLE
Can install pypi package pmtiles

### ISSUE THREAD

**Issue by giswqs** [astral-sh/uv#7728]
Get the following error.  However, the pmtiles source distribution does have `setup.py`.  Any advice?

Error: https://github.com/opengeos/leafmap/actions/runs/11061972073/job/30735570607

> Resolved 237 packages in 1.10s
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: pmtiles==3.4.0
  Caused by: /home/runner/work/_temp/setup-uv-cache/built-wheels-v3/pypi/pmtiles/3.4.0/KFhLlWVwzsoZmsd89qTP3/pmtiles-3.4.0.tar.gz does not appear to be a Python project, as neither `pyproject.toml` nor `setup.py` are present in the directory

Workflow: https://github.com/opengeos/leafmap/blob/master/.github/workflows/docs-build.yml#L40

pmtiles: https://pypi.org/project/pmtiles/3.4.0/#files

Install pmtiles on a local computer:

![image](https://github.com/user-attachments/assets/da298d10-a1a8-42d8-bc08-cb520ca5deb5)

**Comment by zanieb** [comment]
This looks like a cache bug (https://github.com/astral-sh/uv/issues/7485) can you upgrade to a newer version of uv?

**Comment by giswqs** [comment]
@zanieb Many thanks for your prompt response! Update uv to v0.4.16 solves the issue.
