### ISSUE TITLE
uv equivalent to running "python -m"

### ISSUE THREAD

**Issue by tomaszbk** [astral-sh/uv#7738]
I want to migrate to uv, and my actual project is under an "app/" folder, and we use python -m app.main.py to run it.

How can I achieve the same command using uv?

**Comment by zanieb** [comment]
Generally, you'd use `uv run python -m app/main.py` — does that work for you?

**Comment by zanieb** [comment]
Related https://github.com/astral-sh/uv/issues/6638

**Comment by zanieb** [comment]
It'd be the same, but with `uv run` instead of `poetry run`.

**Comment by tomaszbk** [comment]
Yes it works! sorry for not seeing the related github issue before
