### ISSUE TITLE
Incorporate knowledge of disjoint markers into simplification

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#7760]
There are some markers that we "know" cannot be true at the same time, despite the fact that it's not encoded in the grammar or schema at all.

For example, this is never true: `platform_system == 'Linux' and sys_platform == 'darwin'`.

If we encode knowledge about the markers that we "know" are disjoint, we can omit more forks, wheels, etc.

**Comment by charliermarsh** [comment]
\cc @ibraheemdev

**Comment by charliermarsh** [comment]
I have this working, but it does mean all expressions like `sys_platform == 'linux'` get expanded to `sys_platform == 'linux' and platform_system == 'Linux'" in the lockfile.

**Comment by charliermarsh** [comment]
I could just replace `sys_platform == 'linux'` with `platform_system == 'Linux'`, but then we wouldn't detect disjointness in cases like:

```
flask ; sys_platform == 'linux'
flask ; sys_platform == 'java1.8.0_51'
```

**Comment by mitsuhiko** [comment]
> I have this working, but it does mean all expressions like `sys_platform == 'linux'` get expanded to `sys_platform == 'linux' and platform_system == 'Linux'"` in the lockfile.

Could you not keep the knowledge around what the original marker expression was and serialize that into the lockfile instead.  At read it should be rather trivial to expand it out when the lockfile is read?  Performance wise this will be slightly worse but you presumably there won't be that many cases where that is necessary.
