### ISSUE TITLE
Could we use `uv.lock` file as constraints when performing a pip install/tool install?

### ISSUE THREAD

**Issue by Coruscant11** [astral-sh/uv#7768]
Hi!

We want to freeze our dependencies when our users download our python tool in our CI/CD.
While we can `pip freeze` and then use the generated `requirements.txt` as a constraint file (`pip install -c` or `tool install --with-requirements`), this file does not contain platform specific dependencies resolutions. Something that is inside the `uv.lock`

Is it technically feasible? Does it depends first on the uv build backend for example?
Thanks!

**Comment by zanieb** [comment]
You can use `uv export` to get get a `requirements.txt` file with platform-specific pins included.

We might allow some form of `uv pip install --locked` in the future but the design is a bit unclear still.

**Comment by my1e5** [comment]
Duplicate of https://github.com/astral-sh/uv/issues/5815 I believe

**Comment by Coruscant11** [comment]
Sh

> You can use `uv export` to get get a `requirements.txt` file with platform-specific pins included.
> 
> We might allow some form of `uv pip install --locked` in the future but the design is a bit unclear still.

This is exactly what I was searching! Sorry, I don't know how I could missed it from the documentation.
Thanks!

**Comment by knowaywood** [comment]
> You can use `uv export` to get get a `requirements.txt` file with platform-specific pins included.
> 
> We might allow some form of `uv pip install --locked` in the future but the design is a bit unclear still.

have this feature designed?

**Comment by zanieb** [comment]
No
