### ISSUE TITLE
Nvidia Apex Installation

### ISSUE THREAD

**Issue by mishra-tapas** [astral-sh/uv#7771]
I tried installing NVIDIA Apex (https://github.com/NVIDIA/apex) with uv (version 0.4.8) using
"uv pip install -v --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./".
However, this does not work: the error i am getting is 'error: unexpected argument '--build-option' found'.
Is there a way around this problem?
Thanks in advance.

**Comment by zanieb** [comment]
Can you share the full output?

**Comment by BitPhinix** [comment]
```
uv pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-setting "--build-option=--c
pp_ext" --config-setting "--build-option=--cuda_ext" git+https://github.com/NVIDIA/apex
error: unexpected argument '--build-option' found

  tip: a similar argument exists: '--build-isolation'

Usage: uv pip install --verbose... --no-cache <PACKAGE|--requirement <REQUIREMENT>|--editable <EDITABLE>> <--disable-pip-version-check|--user>

For more information, try '--help'.
```

**Comment by BitPhinix** [comment]
As a quick fix, you can fork apex and set these args in the setup.py (super hacky fork you enough to give you an idea: https://github.com/NVIDIA/apex/compare/master...BitPhinix:apex:master

**Comment by zanieb** [comment]
When you provide `--config-setting "--build-option=--cpp_ext"` I think your shell will remove the quotes and we will parse it as a flag?

In my shell, the CLI doesn't complain if I do something like this `uv pip install anyio --config-setting '"--build-option=--cpp_ext"'`

**Comment by pplmx** [comment]
hi, @zanieb 
I’d like to manage the NVIDIA Apex dependency through my pyproject.toml. Could you please advise how to configure it correctly?
