### ISSUE TITLE
Ability to choose the lowest supported Python version

### ISSUE THREAD

**Issue by lengau** [astral-sh/uv#7779]
When running `uv sync` it would be nice to be able to choose the lowest Python version supported by the project dynamically (rather than having to specify that version). e.g. `uv sync --python=lowest`

**Comment by malikrohail** [comment]
can i fix this?

**Comment by charliermarsh** [comment]
As in, the project defines a `requires-python` in the `pyproject.toml`, and you want to use the lowest-supported version rather than the highest?

**Comment by zanieb** [comment]
I think we might need a `--python-strategy <lowest | highest | first>` or something. Similar to https://github.com/astral-sh/uv/issues/7562

**Comment by lengau** [comment]
@charliermarsh yes that would be the idea :-)

**Comment by zanieb** [comment]
Turns out this was previously requested in https://github.com/astral-sh/uv/issues/5609 let's track there
