### ISSUE TITLE
Preserve case-insensitive sorts in `uv add`

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/uv#7801]
i like to keep my dependencies alphabetically sorted, it would appreciate it if `uv` did the same

**Comment by charliermarsh** [comment]
`uv add` does keep them sorted if they were already sorted (but it does not sort unsorted dependencies). Are you seeing otherwise?

**Comment by KotlinIsland** [comment]
turns out it was because there was `PyYAML` in the list, i think the capitalization threw it off

**Comment by charliermarsh** [comment]
I think it would be reasonable to check if the list is case-insensitive-sorted, and preserve that.
