### ISSUE TITLE
Debug uv applications with Visual Studio Code

### ISSUE THREAD

**Issue by AndreuCodina** [astral-sh/uv#7803]
You can use Python or a Python tool (such as `.env/bin/fastapi`) to debug an application in Visual Studio Code. You just have to add a `.vscode/launch.json` file with the configuration. For example, you set a breakpoint and run a FastAPI application with `.venv/bin/fastapi dev src/main.py`.

I've prepared a demo: https://github.com/AndreuCodina/api-to-debug

The issue is this is not possible with `uv`. Therefore, if you update the configuration to:

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "api",
        "type": "debugpy",
        "request": "launch",
        "program": "uv",
        "args": [
          "run",
          "fastapi",
          "dev",
          "src/main.py"
        ],
        "console": "integratedTerminal",
        "justMyCode": false,
        "preLaunchTask": "uv-sync"
      }
    ]
  }
```

You'll see the next error: `[Errno 2] No such file ot directory: '/Users/me/api-to-debug/uv'`

This issue is also related to https://github.com/astral-sh/uv/issues/5903 because when `uv` has a task runner, it should provide debug capabilities. I've done tests with `poe`, but the breakpoints were ignored. Maybe the tool `fastapi` (@tiangolo) is doing some special to provide debug capabilities.

**uv:** 0.4.17
**OS:** MacOS 15.0

**Comment by zanieb** [comment]
Sounds like you need to provide the full path to `uv`? It looks like it's searching for it in your project (and for FastAPI, you show a relative path within the project)

**Comment by zanieb** [comment]
Have you tried creating a symlink to the `uv` binary in your project?

I'm not quite sure what you expect us to change in uv here — this seems like a VS Code usage question

**Comment by AndreuCodina** [comment]
> Have you tried creating a symlink to the `uv` binary in your project?
> 
> I'm not quite sure what you expect us to change in uv here — this seems like a VS Code usage question

Well, I think it's about how uv is integrated in all IDEs and it's very important: you need to debug code and tests with your IDE. I don't know what's the solution, but for example, the tool https://fastapi.tiangolo.com/fastapi-cli/ provides debug integration.

The symlink doesn't work:

```bash
$ ln -s /usr/local/bin/uv .venv/bin/uv

$ .venv/bin/uv --help
...
```

Error in VS Code: `source code string cannot contain null bytes`.

**Comment by PhilHem** [comment]
VSCode can only run python modules with the module option, as far as I've seen. One workaround for now that I use is to just run `uv add uv`. Then it works. It would be nicer though to not have uv itself in the dependencies.

**Comment by zanieb** [comment]
(Not sure this is actionable for us)

**Comment by markwitt1** [comment]
Any update on this?

**Comment by michelkok** [comment]
I stumbled upon this issue as well. My issue was resolved using [this](https://stackoverflow.com/a/66971688/18276367) SO answer. This is how you can use uv with launch.json.

**Comment by YanSte** [comment]
I'm posting this here for those who want to use the FastAPI launcher.

Note: Using uv didn't work, but that give the same results as using the FastAPI module.

```
{
  "version": "0.0.1",
  "configurations": [
    {
      "name": "API:DEV",
      "type": "debugpy",
      "request": "launch",
      "module": "fastapi",
      "cwd": "${workspaceFolder}/api/api/", # Edit path where main.py
      "args": [
        "dev" # Dev mode
      ],
      "justMyCode": false,
      "env": {
        "ENVIRONMENT": "dev"
      }
    },    
    {
      "name": "API:PROD",
      "type": "debugpy",
      "request": "launch",
      "module": "fastapi",
      "cwd": "${workspaceFolder}/api/api/",  # Edit path where main.py
      "args": [
        "run" # Prod mode
      ],
      "justMyCode": false,
      "env": {
        "ENVIRONMENT": "prod"
      }
    }, 
  ]
}

```

**Comment by xavriley** [comment]
For those using a venv created with `uv venv`:

1) Open the Command Palette (shift + apple + p)
2) select "Python: Select Interpreter"
3) select the python version at `.venv/bin/python`

This works with the VSCode debugger

**Comment by kelvincesar** [comment]
I could debug using this python env extension: https://marketplace.visualstudio.com/items?itemName=teticio.python-envy

**Comment by tremu** [comment]
> FYI for me, setting the Interpreter to the bin/python in the virtualenv didn't work, but selecting the .venv folder itself did - vscode seemed to understand that meant "use this venv" and all was well from there.

you just saved my bacon tysm

**Comment by lambdakris** [comment]
I was able to debug a Streamlit app with an environment managed by UV using the following VS Code `launch.json`.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Streamlit Debugger",
            "type": "debugpy",
            "request": "launch",
            "python": ".venv/bin/python",
            "module": "streamlit",
            "args": ["run", "app/frontend/main.py", "--server.address", "localhost", "--server.port", "8501"]
        }
    ]
}
```

The "secret" is the setting `"python": ".venv/bin/python"` which points the debugger to use the python for the UV managed venv (UV by default creates a venv in `{projectDir}/.venv`) and which picks up any packages etc available in the venv. As far as I can tell, the path `.venv/bin/python` should be constant across os/platforms when using UV, and you can always [customize the venv path for UV](https://docs.astral.sh/uv/pip/environments/#using-arbitrary-python-environments) if necessary.

**Comment by yslbit** [comment]
> For those using a venv created with `uv venv`:
> 
> 1. Open the Command Palette (shift + apple + p)
> 2. select "Python: Select Interpreter"
> 3. select the python version at `.venv/bin/python`
> 
> This works with the VSCode debugger

Thanks, for the third step, i succeeded when i selected  ".venv/bin/python3" instead of ".venv/bin/python".

**Comment by jamiekt** [comment]
Hi folks,
The solutions here work when the virtualenv created by uv is in a known location. However, when I use `uv run script.py` uv will create an ephemeral environment. This is useful because I'm declaring dependencies in my script as described at https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies

I'm keen to find a way that I can run my script using `uv run` while still using the Code/Cursor debugger.
