### ISSUE TITLE
`uv version` enhancement for changing the project version

### ISSUE THREAD

**Issue by butterlyn** [astral-sh/uv#7818]
Request for an enhancement to the feature `uv version` to enable the command to dynamically set/update the project version (in the `pyproject.toml` file), similar to the Poetry command `poetry version` ([link](https://python-poetry.org/docs/cli/#version)).

**Example proposed functionality**:
`uv version 1.4.2` would update the `pyproject.toml` file with version `1.4.2`.

**Use case**:
To use `uv build` within CI pipelines that include automatic version incrementing, there needs to be a way to dynamically set/update the project version within the CI pipeline. This is currently blocking migration from Poetry to uv for my projects that have CI pipelines with automatic version incrementing.

**Comment by zanieb** [comment]
This is a duplicate of #6298
