### ISSUE TITLE
uv pip install ... --extra-index-url bug

### ISSUE THREAD

**Issue by Ruhrozz** [astral-sh/uv#7831]
I have specific torch version in my extra-index-url and some other packages. When I trying to install my python library with `uv pip install -e .` it searches `torch` in extra-index-url and throws an error that you have a single torch version which does not meet the requirements.

I expected that it will try to find it on PyPI, because pip itself cope with that situation somehow

I don't know how to make a reproducible example for it =(

**Comment by zanieb** [comment]
Hi! Sounds like your encountering this [intentional difference from pip](https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes).

**Comment by Ruhrozz** [comment]
Thanks for help!

**Comment by FelixSchwarz** [comment]
Just wanted to mention that I encountered the same issue and @zanieb's answer was helpful for me as well :-)
