### ISSUE TITLE
Direct dependency is incorrectly treated as indirect dependency

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#7863]
We incorrectly treat numpy as a transitive instead of a direct dependency, which means we don't emit the correct diagnostic about a missing lower bound:

```
[project]
name = "dummy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
  "numpy",
]
```

Relevant log line from `RUST_LOG=uv=debug uv lock`:

```
DEBUG Adding transitive dependency for dummy==0.1.0: numpy*
```

We need to change this check to consider workspace packages:

https://github.com/astral-sh/uv/blob/30e11c6debf2ceb53710fdfbafcb87c6d478aa1b/crates/uv-resolver/src/resolver/mod.rs#L2163

**Comment by mstepan** [comment]
I was trying to reproduce this issue using posted `pyproject.toml` file but seems it's working as expected:

```
uv/target/debug/uv pip compile example/pyproject.toml -o example/requirements.txt
...

DEBUG Adding direct dependency: numpy*
INFO add_decision: example @ 0a0.dev0 
```

**Comment by charliermarsh** [comment]
Try using `uv lock` instead of `uv pip compile`.

**Comment by Aditya-PS-05** [comment]
I am setting this type of diagnostic message,

![Screenshot from 2024-10-16 18-39-54](https://github.com/user-attachments/assets/6a7a486f-f2bc-4071-bfaf-bcabe45777eb)

Is this the required behavior or somethingelse

**Comment by konstin** [comment]
We should treat numpy as a direct dependency here, which means we should show the `The direct dependency `{package}` is unpinned.` message [here](https://github.com/astral-sh/uv/blob/2153c6ac0d692b9eccedbd7567087907667645fb/crates/uv-resolver/src/resolver/mod.rs#L2254) for numpy: We should have an additional check that the `for_package` isn't a workspace member.

**Comment by Aditya-PS-05** [comment]
How should I check if it's a workspace member? Should I need to explicitly define that these are the workspace members or something else?

**Comment by konstin** [comment]
`ResolverState::workspace_members` has this information
