### ISSUE TITLE
cp27 wheels selected for psutil on windows

### ISSUE THREAD

**Issue by bluss** [astral-sh/uv#7873]
See wheel `psutil-6.0.0-cp27-none-win32.whl` in lockfile. 

```console
uv init -p 3.12 test-psutil
cd test-psutil/
uv add psutil
# Using CPython 3.12.5
# Creating virtual environment at: .venv
# Resolved 2 packages in 1ms
# Installed 1 package in 0.59ms
#  + psutil==6.0.0
rg -u cp27
```

```
uv.lock
10:    { url = "https://files.pythonhosted.org/packages/c5/66/78c9c3020f573c58101dc43a44f6855d01bbbd747e24da2f0c4491200ea3/psutil-6.0.0-cp27-none-win32.whl", hash = "sha256:02b69001f44cc73c1c5279d02b30a817e339ceb258ad75997325e0e6169d8b35", size = 249766 },
11:    { url = "https://files.pythonhosted.org/packages/e1/3f/2403aa9558bea4d3854b0e5e567bc3dd8e9fbc1fc4453c0aa9aafeb75467/psutil-6.0.0-cp27-none-win_amd64.whl", hash = "sha256:21f1fb635deccd510f69f485b87433460a603919b45e2a324ad65b0cc74f8fb1", size = 253024 },
```

uv 0.4.18

For the record, the wheel is selected for install on gh actions platform Microsoft Windows Server 2022 (?)

`2024-10-02T16:53:24.1443510Z DEBUG Selecting: psutil==6.0.0 [preference] (psutil-6.0.0-cp27-none-win32.whl)`

And the functionality of psutil which my test required [worked](https://github.com/bluss/pyproject-local-kernel/actions/runs/11148088268/job/30983917110) without problem.

**Comment by samypr100** [comment]
Interesting, I would expect `psutil-6.0.0-cp37-abi3-win_amd64.whl` to be the one selected

**Comment by zanieb** [comment]
I see logs for both the cp37 and cp27 wheels getting selected,  e.g.

> 2024-10-02T16:53:42.6934365Z DEBUG Selecting: psutil==6.0.0 [compatible] (psutil-6.0.0-cp37-abi3-win_amd64.whl)

I'm confused about what's going on here.

**Comment by charliermarsh** [comment]
@zanieb - That message is just from the resolver. The choice of wheel there is arbitrary.

**Comment by charliermarsh** [comment]
Are you sure that we're actually using that wheel @bluss? Those `Selecting:` logs are all from the resolver where we choose an arbitrary wheel to determine the version metadata.

**Comment by bluss** [comment]
Not sure, I was just misunderstanding the logs, then.

**Comment by charliermarsh** [comment]
How can we make this logging clearer? It's not the first time we've had this issue.

**Comment by zanieb** [comment]
Would it be a challenge to stop reading cp27 wheels entirely? I feel like their metadata shouldn't be relevant anymore.

**Comment by charliermarsh** [comment]
Probably not but it admittedly doesn't solve the root problem.

**Comment by charliermarsh** [comment]
I think we can omit them though, yes.

**Comment by charliermarsh** [comment]
#7381 also makes this way better, because we'll prefer compatible wheels here.

**Comment by zanieb** [comment]
It sort of looks like we should be using the sdist name there?

https://github.com/astral-sh/uv/blob/14507a1793f12bf884786be49d716ca8f8322340/crates/uv-distribution-types/src/prioritized_distribution.rs#L465-L467

**Comment by charliermarsh** [comment]
We would do that after https://github.com/astral-sh/uv/pull/7381. Right now we don't match on tags _at all_ in the universal resolver. All wheels are considered compatible.

**Comment by bluss** [comment]
You could log explicitly when wheels are installed, that's one way to make it more clear? 

> DEBUG: Installing `psutil` from wheel `..whl`

I guess the strongest signal for bug here though was the presence of python 2.7 wheels in a python >= 3.8 resolution?
