### ISSUE TITLE
Failed to install: certifi-2024.8.30-py3-none-any.whl 

### ISSUE THREAD

**Issue by Pdsantos73** [astral-sh/uv#7906]
Trying to install fastapi "uv add fastapi[standard]" is showing the following error:

error: Failed to install: certifi-2024.8.30-py3-none-any.whl (certifi==2024.8.30)
Caused by: failed to hardlink file from C:\Users\paulodo\AppData\Local\uv\cache\archive-v0\ez_A-yAgnUYbpxYugeHkX\certifi\py.typed to C:\Users\paulodo\OneDrive - Genesys Telecommunications Laboratories, Inc\DeveloperProject\Python\GenesysClould\middleware_a.venv\Lib\site-packages\certifi\py.typed
Caused by: The cloud operation cannot be performed on a file with incompatible hardlinks. (os error 396)

**Comment by zanieb** [comment]
It looks like your cache is on a different file system than your project. Can you set `UV_LINK_MODE=copy`?

**Comment by zanieb** [comment]
cc @charliermarsh we might want a fallback for this specific error.

**Comment by Pdsantos73** [comment]
Yes,

I included  env variable but de issues persistes
![image](https://github.com/user-attachments/assets/1d0490ff-b339-4d77-9459-42d910b20e9a)

![image](https://github.com/user-attachments/assets/e3bb89fa-a472-4afc-9533-63fcb5f53f7d)

**Comment by Pdsantos73** [comment]
I recently updated UV to the latest version.
This problem only occurs in some dependencies.

**Comment by Pdsantos73** [comment]
I'm using:
Windows 11
uv 0.4.18 (7b55e9790 2024-10-01)
Python 3.12.6

**Comment by Pdsantos73** [comment]
Criei um novo projeto e consegui instalar com a opção uv add "fastapi[standard]" --link-mode=copy

Thanks

**Comment by Pdsantos73** [comment]
I created a new project and managed to install it with the **uv add option "fastapi[standard]" --link-mode=copy_**

Thanks

**Comment by Pdsantos73** [comment]
I created a new project and managed to install it with the **uv add "fastapi[standard]" --link-mode=copy**

**Comment by Pdsantos73** [comment]
I created a new project and managed to install it with the **uv add "fastapi[standard]" --link-mode=copy**

It worked!!

Thanks

**Comment by charliermarsh** [comment]
I sort of doubt we can react to this error specifically, unless it maps to a clear error kind on `io::Error`.

**Comment by samozturk** [comment]
I had the same problem the solutions above didn't work for me. So I did `uv cache clean`, tried to install again. Solved the issue.

**Comment by jromal** [comment]
Unfortunately it happens very often to me. I have to clean the cache too.
It may be that I am working on Windows and many python projects are on a "OneDrive" folder, that is considered sometimes as a local folder but sometimes with a different very long name. OneDrive is a shit, but for space reasons I have to use it in the companies laptop.

Someone else having problems with OneDrive?

**Comment by delreluca** [comment]
> Someone else having problems with OneDrive?

Yes, at work I also use OneDrive and I experience this same error (os error 396). `uv cache clean` or moving the cache location fixes the problem.

It doesn’t always happen when I use OneDrive, but I have the suspicion that creating a venv on OneDrive somehow taints the cache and breaks it.

**Comment by TJMac93** [comment]
@delreluca's latest comment mirrors my experience. I didn't have any issues running `uv add {package}` but after absentmindedly doing `uv pip install {package}` instead, that's when everything stopped working
