### ISSUE TITLE
[feat] Adding multiple modules to --with flag on uvx startup

### ISSUE THREAD

**Issue by noamteyssier** [astral-sh/uv#7908]
Hello!

I love `uv` and very much appreciate all the work the team is doing for python development! 

I am proposing a minor change to the `uvx --with` API to allow for multiple arguments.

## Current API (`uv==0.4.18`)

```bash
uvx --with numpy --with polars --with matplotlib ipython
```

## Desired API
```bash
uvx --with numpy,polars,matplotlib ipython
```

**Comment by charliermarsh** [comment]
Closed by https://github.com/astral-sh/uv/pull/7909. Thanks!
