### ISSUE TITLE
Help on Windowns when dowloading from pip

### ISSUE THREAD

**Issue by brunocarlin** [astral-sh/uv#7926]
Hi, how do I register uv to the command line when doing a pip install of uv, the reason I want that is because uv is not findable by the venv's I am using because it is only installed on my base python

**Comment by zanieb** [comment]
Maybe you want `pip install --system uv` or `pipx install uv`? I'm not sure how Windows handles the base Python's bin directory. I'd really recommend just not installing from pip.

**Comment by brunocarlin** [comment]
I can't not install from pip because my company only allow installations from pip in this case...

**Comment by brunocarlin** [comment]
Just to be clear uv does work and is installed on system but I can`t from a venv use python-m uv...

**Comment by zanieb** [comment]
Oh why are you using `python-m uv` instead of just `uv`? You could provide the path to your system interpreter... i.e., before activating your environment `which python` then `\path\to\python -m uv`. I imagine you can create an alias for that?

**Comment by brunocarlin** [comment]
I trid to add the uv path to system variables, but that didn't work, but honestly I don't know enough windows to create an alias that when I would run uv it would point to that

**Comment by zanieb** [comment]
I think you'll need to just look up how to add a path to your system — there's not much we can do for you here. This is why we have a separate installer that handles these things.

**Comment by brunocarlin** [comment]
when I add to path which uv file should I use?

**Comment by brunocarlin** [comment]
I think I can solve this be using temp names and aliases and doskey, thanks for the ideas!
