### ISSUE TITLE
document internal data dependencies & flow

### ISSUE THREAD

**Issue by BurntSushi** [astral-sh/uv#793]
This ticket is a little open ended, but one thing I'd like to try and do is document how data flows through Puffin and what is actually used in each step.

Part of the purpose of doing this is to build a better mental model for myself about how Puffin works.

But I think this sort of analysis can help with optimization. That is, if we know what is actually required at each step, that might expose some optimization opportunities by, say, deserializing less data.

I'm not sure if it makes sense for the output of this ticket to just be a comment here or if I should write a short doc and commit it to the repo. (The doc seems likely to get stale, but we could mitigate that by putting a timestamp with a warning on it.)

**Comment by charliermarsh** [comment]
We've had a few attempts at this -- going to close for now as not super actionable.
