### ISSUE TITLE
Feature request: Add ability to exclude certain file/directory patterns from `uv build` output

### ISSUE THREAD

**Issue by pirate** [astral-sh/uv#7938]
Currently it seems `uv build` includes everything found in the root directory, but it would be great to be able to exclude certain files/directories.

For example, I don't want to bundle these in my `sdist`/`bdist` wheel:

```
**/.DS_Store
**/*.pyc
**/__pycache__
tests
```

It would also be great if I could force it to include my `pyproject.toml` and `.git/refs/HEAD` from the source code root dir as I like to ship it inside the sdist (so that I can print more useful debug info including installed commit hash and more).

Should this be accomplished by adding `MANIFEST.in` support? Or perhaps just some `pyproject.toml` config options? No strong opinions on my side, up to you.

Thanks for building `uv`!

**Comment by kahojyun** [comment]
`uv` is just a build frontend right now, and the file selection is handled by `build-backend` specified in `pyproject.toml`. For example, you can configure [`hatchling`](https://hatch.pypa.io/latest/config/build/#file-selection) (the `build-backend` in the `pyproject.toml` generated by `uv init --lib`).

**Comment by zanieb** [comment]
Yeah we're working on our own build backend but right now this is configurable using other tools (the default build backend is `setuptools` if one is not declared).

**Comment by edsu** [comment]
One thing you can do is add things you want to exclude to your `.gitignore` and it looks like `uv build` will ignore them too?
