### ISSUE TITLE
after I   uv tool  install   httpie  , I  try  to  run  "uvx   http  google.com "  ,but   happen  unexpected    error* 

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#7939]
# win11  uv@latest  

##*after I   uv tool  install   httpie  , I  try  to  run  "uvx   http  google.com "  ,but   happen  unexpected    error* 

![image](https://github.com/user-attachments/assets/3c6dcc57-91f0-4526-8e39-010579146bb2)

**Comment by Wurstnase** [comment]
You need to run `http` with `--from httpie`, else `uvx` will look for `http`.

```
uv tool run --from httpie http google.com
```

**Comment by Super1Windcloud** [comment]
thank you  very much

**Comment by zanieb** [comment]
If you do `uv tool install httpie`, then `http` should "just be available" without `uvx`.

**Comment by iddqd3** [comment]
> If you do `uv tool install httpie`, then `http` should "just be available" without `uvx`.

yes, if you add to PATH `$HOME/.local/bin`

After installing the tool, uv will notify you if the paths are not specified in the PATH
```
....
Installed 3 executables: http, httpie, https
warning: `/home/username/.local/bin` is not on your PATH. To use installed tools, run `export PATH="/home/username/.local/bin:$PATH"` or `uv tool update-shell`.
```
