### ISSUE TITLE
Docker integration: Suggest COPYing `uvx` in addition to `uv`

### ISSUE THREAD

**Issue by salty-horse** [astral-sh/uv#7947]
The [Docker integration guide](https://docs.astral.sh/uv/guides/integration/docker/) suggests "copying the binary from the official distroless Docker image":
```
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
```

For the "full experience", I think it should suggest copying the `uvx` tool as well:
```
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
```

**Comment by zanieb** [comment]
👍 yep

**Comment by zaira-bibi** [comment]
Hey! I'd like to work on this issue please.

**Comment by Aditya-PS-05** [comment]
hey @zanieb , 
Can you assign me this issue, if nobody is assigned already.

**Comment by zanieb** [comment]
This is small enough that we don't need to assign someone to prevent duplicate work — just put up a pull request.

**Comment by Aditya-PS-05** [comment]
@zanieb , 
please review it.
