### ISSUE TITLE
Track plugin dependencies in uv.lock

### ISSUE THREAD

**Issue by runfalk** [astral-sh/uv#7960]
This issue is similar but not quite the same as https://github.com/astral-sh/uv/issues/7911.

I make use of `hatch-protobuf` for building protobufs. This package in turn depends on `grpcio-tools`, but since `uv` doesn't track plugin dependencies in its lockfile, my CI pipeline just broke due to a version mismatch between `grpcio-tools` codegen and `grpcio` runtime.

Working around this directly in `pyproject.toml` by specifying all dependencies would be annoying as `grpcio-tools` has its own set of dependencies.

I believe it makes sense for build dependencies to be properly locked to prevent CI pipelines from breaking.

**Comment by charliermarsh** [comment]
I think this can probably be merged into https://github.com/astral-sh/uv/issues/7052 which is the general issue we're using to track build dependency locking.
