### ISSUE TITLE
Instal via brew results in an outdated/old version (i.e. 0.1.xx)

### ISSUE THREAD

**Issue by mgiugliano** [astral-sh/uv#7962]
On my mac (M3, Sonoma, 14.6.1 (23G93)), typing 

```brew install uv```

does install uv but an old version (0.1.xx).
As an absolute beginner of uv, typing 
```uv init example```

returns an error (unknown command 'init').

The install via curl results in version 0.4.18 and "init" is now a command of uv.

**Comment by charliermarsh** [comment]
I see 0.4.19 here: https://formulae.brew.sh/formula/uv

**Comment by charliermarsh** [comment]
I'm not sure what's going on there. Maybe you had an old uv installed somewhere else?

**Comment by charliermarsh** [comment]
(Happy to help if you have any follow-up questions.)

**Comment by mgiugliano** [comment]
@charliermarsh I did see (on the brew formula website) mention to the last version of uv but that was not what it was installed. It was my first install ever of uv. I nonetheless resorted to other installation method.
