### ISSUE TITLE
uv python pin 3.13t gives a VersionParseError

### ISSUE THREAD

**Issue by olivierfriard** [astral-sh/uv#7964]
Hi,

thank you for uv!

I am using uv (v0.4.18) on Linux.

The command:
`uv python pin 3.13t`
gives the following error message
```
thread 'main' panicked at crates/uv/src/commands/python/pin.rs:173:69:
called `Result::unwrap()` on an `Err` value: VersionParseError { kind: UnexpectedEnd { version: "3.13", remaining: "t" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

while 
`uv python pin 3.12t`
correctly reports
`error: Invalid version request: Python <3.13 does not support free-threading but 3.12t was requested.`

**Comment by zanieb** [comment]
Thanks I'll look into this.
