### ISSUE TITLE
Update uv on winget to v0.4.18

### ISSUE THREAD

**Issue by timrid** [astral-sh/uv#7968]
At `winget` the latest available version of `uv` is v0.4.15. But currently v0.4.18 is already released. It would be good if the latest version of uv could also be obtained via winget.

See here: https://winstall.app/apps/astral-sh.uv
![image](https://github.com/user-attachments/assets/24265c76-3b0d-4c2b-8e08-e56720854b6b)

**Comment by FishAlchemist** [comment]
https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+astral-sh.uv
If you need it on winget, maybe it would be faster to open a PR to provide the new version?

**Comment by timrid** [comment]
Ok, thanks. I assumed that it is officially supported as it is also mentioned in the [official documentation](https://docs.astral.sh/uv/getting-started/installation/#winget).

**Comment by charliermarsh** [comment]
Yeah we don't control this distribution unfortunately.

**Comment by zanieb** [comment]
I don't see any reason you'd be prohibited from creating an update pull request — our project is permissively licensed and I  think the CLA is just for your code changes over there.

**Comment by Ravencentric** [comment]
A project I'm familiar with uses <https://github.com/vedantmgoyal9/winget-releaser> to keep winget distribution in sync. Might be worth looking into if you haven't already.

**Comment by FishAlchemist** [comment]
@zanieb I'm unsure about the specific licensing terms for distributing binaries under MIT and Apache-2.0 licenses, and I want to avoid violating any CLA agreements. However, based on my understanding of these licenses, as long as I provide the original source and licensing terms, I should be fine.

**Comment by Dragon1573** [comment]
> A project I'm familiar with uses [WinGet Releaser v2](https://github.com/vedantmgoyal9/winget-releaser) to keep `winget` distribution in sync. Might be worth looking into if you haven't already.

Also, as the pull request is directly created by the package publisher & author, the pull request will be "privileged" and can immediately merged after validation pipeline is passed. Contributors & volunteers don't have these privileges, and they might not be noticed at once, leading "always outdated" problem.

Please refer to [JanDeDobbeleer/oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh), he performs version updates frequently and all these updates are synced and merged to `winget` source soon after the release action. 🙏🏼
