### ISSUE TITLE
Patch version resolve

### ISSUE THREAD

**Issue by matthias-Q** [astral-sh/uv#7981]
Hi,
I want to migrate from a setup.py to pyproject.toml + uv setup. In my current configuration I use patch version pinning, e.g. `package==1.8.*`. Pip installs version 1.8.10, which is the latest version. `uv` installs 1.8.0, which I find odd. The same happens for `package~=1.8`. I think this is a bug.

I use uv 0.4.11 on Linux.

**Comment by zanieb** [comment]
I can't reproduce this

```
❯ uv venv
Using CPython 3.12.1
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
❯ uv pip install 'sniffio==1.3.*' --no-cache
Resolved 1 package in 176ms
Prepared 1 package in 27ms
Installed 1 package in 4ms
 + sniffio==1.3.1
❯ uv venv
Using CPython 3.12.1
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
❯ uv pip install 'sniffio~=1.3' --no-cache
Resolved 1 package in 94ms
Prepared 1 package in 18ms
Installed 1 package in 1ms
 + sniffio==1.3.1
```

**Comment by matthias-Q** [comment]
Hmm, I was running this today in an CI pipeline and tested it extensively. Now I also cannot reproduce this. Ok sorry for the hassle. I will close this issue.
