### ISSUE TITLE
Cannot install piper-tts due to missing wheel (but pip install works fine)

### ISSUE THREAD

**Issue by halflings** [astral-sh/uv#7987]
Repro steps:
uv init
uv pip install piper-tts

Output:
Using CPython 3.12.4 interpreter at: /usr/bin/python
Creating virtual environment at: .venv
Resolved 13 packages in 426ms
error: distribution piper-phonemize==1.1.0 @ registry+https://pypi.org/simple can't be installed because it doesn't have a source distribution or wheel for the current platform

Expected:
piper-tts to be installed correctly.
pip works fine in this case:
... Downloading piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (25.0 MB)
(maybe using a different Python version somehow?)

**Comment by zanieb** [comment]
Looks like you're using Python 3.10 with pip and 3.12 with uv.
