### ISSUE TITLE
`test_prepare_metadata` hash changes on uv version bump

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#8017]
See failure at https://github.com/astral-sh/uv/actions/runs/11242534493/job/31256449318?pr=8016 and fix at https://github.com/astral-sh/uv/pull/8016/commits/6a7c2962143be7b238e57d96554c5572cec186bd

I did not verify the cause of this, I figure @konstin will know.

**Comment by konstin** [comment]
We should redact that hash, it pulls in the uv version number because it's listed as generator in the WHEEL file.
