### ISSUE TITLE
Support managed downloads of 3.13t (no-gil / freethreaded)

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#8019]
Right now, we only support a single build per CPython version. We need to add support for other build options to allow installing the [freethreaded builds](https://github.com/indygreg/python-build-standalone/releases/tag/20241008). This will require changes to our download metadata fetch and template scripts. We should probably aim support debug builds too.

**Comment by Crypto-Spartan** [comment]
In addition, I'd love it if `uv` were able to support other builds from [python-build-standalone](https://github.com/indygreg/python-build-standalone), such as `x86_64-unknown-linux-gnu-pgo+lto-full.tar.zst`, `x86_64_v3-unknown-linux-gnu-install_only_stripped.tar.gz`.

I know we talked about this in the other issue, just wanted to add the request here specifically.

**Comment by charliermarsh** [comment]
Can I ask why you need / want to use those other builds?

**Comment by Crypto-Spartan** [comment]
Those other builds provide optimizations done by the compiler that aren't done in the base `-install_only_stripped.tar.gz` builds. I just chose those 2 as examples, but I believe `uv` should support any build from [python-build-standalone](https://github.com/indygreg/python-build-standalone).

**Comment by charliermarsh** [comment]
The install-only-stripped builds include PGO and LTO.

**Comment by Crypto-Spartan** [comment]
Ah, I didn't realize that. when I checked the docs at https://gregoryszorc.com/docs/python-build-standalone/main/running.html#obtaining-distributions, it didn't seem that way. I found https://gregoryszorc.com/docs/python-build-standalone/main/distributions.html#install-only-archive had it listed, all the way at the bottom of the page.

**Comment by Crypto-Spartan** [comment]
What about the newer CPU architectures such as `x86_64_v3`?

**Comment by zanieb** [comment]
> What about the newer CPU architectures such as `x86_64_v3`?

Yes, those also prefer the optimized builds.

**Comment by Crypto-Spartan** [comment]
I figured that. I was trying to ask:
Is `uv` open to supporting installing builds with newer CPU architectures such as `x86_64_v3`? I didn't see any of those builds listed in https://github.com/astral-sh/uv/blob/f6fd849f2c63e3b319ab03c936beab866dc303ba/crates/uv-python/download-metadata.json

**Comment by zanieb** [comment]
We should chat about that in another issue as it's totally unrelated to this thread — but, yes? If we can detect the architecture reliably.

**Comment by zanieb** [comment]
I actually had already opened an issue to track this at https://github.com/astral-sh/uv/issues/7193
