### ISSUE TITLE
`uv publish` uploads every file in `/dist`

### ISSUE THREAD

**Issue by david-waterworth** [astral-sh/uv#8033]
I'm not sure if this expected but I noticed `uv publish` uploaded every single file it found in `/dist` to (our private) pypi. On the plus side this surfaced a build script bug (post-build clean step not running) - but it was a little suprising.

The behaviour of `poetry publish` is to only publish the `the package, previously built with the build command` - i.e. (I'm assuming) it uses the version from pyproject.toml to ensure the correct sdist / wheel is uploaded.

**Comment by TiansuYu** [comment]
potentially duplicate to this one https://github.com/astral-sh/uv/issues/7917

**Comment by zanieb** [comment]
I don't think this is a duplicate, though this is sort of discussed there.

I think this behavior is pretty reasonable, though maybe we can improve it or have different modes? I think we'd need to read the package from the `pyproject.toml` if we wanted to limit the scope.

**Comment by david-waterworth** [comment]
Also wheel/sdist filenames contain a version string that's "canonicalised" and doens't necesarily match the version string in `pyproject.toml` - in order to get the filename of the wheel in my ci process (in which the version is generated by `python-semantic-version` I had to use the `packaging` package, i.e.

```
from packaging.version import Version

def canonicalise(version: str):
    return str(Version(version))
```

**Comment by konstin** [comment]
Canonicalizing the name is a requirement from the Python packaging specs (https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode)

**Comment by david-waterworth** [comment]
Yeah but that’s just the {version} in the package filename though right? The actual package version doesn’t have to be canonical as far as I’m aware?

**Comment by konstin** [comment]
The spec says:

> Version numbers should be normalised according to the [Version specifier specification](https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers). Normalised version numbers cannot contain -.

The critical part is that we can't have the `-` in a version because then you can't tell whether it's part of the version or starting the next section in the wheel filename.

I'd recommend cleaning the dist directory before doing a new publish, basically a workflow below

```
rm -r dist/
uv build
[other uv build command if you publish a workspace]
[smoke test commands, such as installing the source dist and wheel in a fresh venv and running `python -c "import mypkg"`]
uv publish
```

Would a workflow like that work for your use case?

**Comment by konstin** [comment]
Thanks - will close.
