### ISSUE TITLE
There's no intuitive way to Managing Environments.

### ISSUE THREAD

**Issue by farzbood** [astral-sh/uv#8037]
Hi,
I couldn't find any command or options to **Manage the Environments** created once by `uv venv `and needed to be **Modified/Removed/Switched Between** appropriately, like the ones available in [Poetry](https://python-poetry.org/docs/managing-environments/).

**Comment by ilyagr** [comment]
You are probably looking for the `uv pip` commands, e.g. `uv pip list`, `uv pip install`, ...

I kind of wish `uv pip` was `uv env` instead, and `uv venv` was `uv env create`.

**Comment by farzbood** [comment]
No, `pip `commands are about managing the **dependencies** of the project installed in the `env`, not the **virtual environment** itself.
I'm looking for commands like: `poetry env remove`, `poetry env use`, ... to manage the `env`. ([check the link to the Poetry docs](https://python-poetry.org/docs/managing-environments/).) that let you associate more than one `env `to a project and switch between them, remove unwanted ones, etc.
