### ISSUE TITLE
Add `uv pip install --exact`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#8041]
To remove extraneous packages, similar to `uv sync --inexact`.

**Comment by ashb** [comment]
@charliermarsh I don't think this is 100% working. Or at least it's not working how I expected to be able to use it:

In the apache/airflow repo:

1. `uv venv build/.k8s-env`
2. `VIRTUAL_ENV=$PWD/build/.k8s-env uv pip install --exact -r scripts/ci/kubernetes/k8s_requirements.txt`
3. `VIRTUAL_ENV=$PWD/build/.k8s-env uv pip install kgb` (Or any module not currently installed)
4. Run `VIRTUAL_ENV=$PWD/build/.k8s-env uv pip install --exact -r scripts/ci/kubernetes/k8s_requirements.txt` and expect it to remove the `kgb` module I've just installed manually.

Sorry, I should have thought to check the PR.

**Comment by charliermarsh** [comment]
Thanks Ash, let me give it a try today. It should be working as you expect based on the above.

**Comment by ashb** [comment]
If `uv pip sync` is a better command for this workflow I'd be happy to use that, but using it on that same requirments file I end up with a venv with only these three

```
-e file:///Users/ash/code/airflow/airflow
-e file:///Users/ash/code/airflow/airflow/task_sdk
-e file:///Users/ash/code/airflow/airflow/providers
```

And non of the deps or extras.

**Comment by ashb** [comment]
Stange, it doesn't for me:

```
❯ VIRTUAL_ENV=$PWD/build/.k8s-env uv pip install kgb
Using Python 3.12.5 environment at build/.k8s-env
Resolved 1 package in 25ms
Installed 1 package in 2ms
 + kgb==7.1.1

❯ VIRTUAL_ENV=$PWD/build/.k8s-env uv pip install --exact -r scripts/ci/kubernetes/k8s_requirements.txt
Using Python 3.12.5 environment at build/.k8s-env
Audited 3 packages in 74ms

❯ uv version 
uv 0.4.21 (0c5d05d9e 2024-10-14)
```

**Comment by charliermarsh** [comment]
@ashb -- Do you want to send me the `--verbose` logs from the second command? You can email if you prefer.

**Comment by charliermarsh** [comment]
Oh you know what, I can imagine why this might be happening.

**Comment by blueraft** [comment]
I think it's the perf optimisation that checks if the env satisfies the requirements, I can reproduce it now by running the command a few times

**Comment by blueraft** [comment]
I'll create a PR in a bit

**Comment by ashb** [comment]
Oh yes, passing `--reinstall` does fix it, and also there was def a timing element as you expected. I came back to it and just ran the `install --exact` and that time it did uninstall kgb.

Sounds like you don't need logs, right?

**Comment by charliermarsh** [comment]
Yeah no need -- we'll get it fixed.

**Comment by ashb** [comment]
Thanks for the speedy fix! All working now. On step closer to my goal of the complete uv-ification of Airflow's CI!
