### ISSUE TITLE
Python 3.13 Versions

### ISSUE THREAD

**Issue by Odud** [astral-sh/uv#8042]
A question, not really an issue. When I install Python 3.13 I see that it is picking up release candidate 3 `Python 3.13.0rc3 (main, Oct  2 2024, 16:40:04)` and not the final version released on Oct 7. it probably makes no difference to me but I was wondering when the version that uv sees gets updated.

**Comment by charliermarsh** [comment]
Are you on the latest version of uv? We released Python 3.13 last night, but the versions are tied to the uv version, so you need to update uv itself.
