### ISSUE TITLE
Paths not working as expected with `--find-links`

### ISSUE THREAD

**Issue by xenago** [astral-sh/uv#8057]
Hello,

The behaviour of `--find-links` seems to have changed, possibly with #7912 (shipped in version `0.4.19`). In version `0.4.18`, the following line works to install a `.whl` stored in a local directory e.g. `Sentiment Analysis/en_core_web_sm/en_core_web_sm-3.7.1-py3-none-any.whl`:

`uv pip install --find-links="Sentiment Analysis/en_core_web_sm" en_core_web_sm`

![image](https://github.com/user-attachments/assets/e7fce811-0aea-49f7-8aad-3c197b13b4ae)

However, in versions >`0.4.18`, the following error is printed:

`error: invalid value 'Sentiment' for '--find-links <FIND_LINKS>': relative URL without a base`

![image](https://github.com/user-attachments/assets/0b36b2eb-493c-4500-b107-468b3327bf6e)

It looks like it is treating the file path as a URL and also splitting it on the space character?

**Comment by charliermarsh** [comment]
Thanks, that's a bug on my part.
