### ISSUE TITLE
[QUESTION] 3.13 docker images

### ISSUE THREAD

**Issue by chrisemke** [astral-sh/uv#8066]
Is there any plan about the docker 3.13 images? I wish to know better the workflow around this, thanks guys nice work!

**Comment by charliermarsh** [comment]
@samypr100 -- Do you know if we can add this yet?

**Comment by samypr100** [comment]
Yes, should be trivial now that the official images our out, I can have a PR ready later

**Comment by charliermarsh** [comment]
Wow, thanks!

**Comment by chrisemke** [comment]
<3
