### ISSUE TITLE
uv --native-tls doesn't seem to work

### ISSUE THREAD

**Issue by andreamoro** [astral-sh/uv#8070]
On my Mac OS Sequoia 15.0 (24A335), I'm trying to run uv and as I'm behind a company proxy, I need to use the system certificates which are not recognised by default.

In running the `uv --native-tls` command the help keeps being prompted. Conversely, using an `export UV_NATIVE_TLS=truez` and then running whatever I need, uv execute without issues.

**Comment by charliermarsh** [comment]
Interesting, will take a look.

**Comment by charliermarsh** [comment]
Can you include the exact command you're running? `uv --native-tls venv --show-settings` shows that `native_tls` is being set as expected.

**Comment by WSF-SEO-AM** [comment]
I was going just with UV --native-tls because I thought this was helping to set the parameter once and for all 
This doesn't sound too be the case, right?

**Comment by zanieb** [comment]
`uv --native-tls` doesn't set a configuration value in a persistent way, it changes the behavior for a single invocation of `uv`.

**Comment by Sairam90** [comment]
Could you provide an example of how I can use a pem file similar to --cert for pip ?

**Comment by zanieb** [comment]
You can use `SSL_CERT_FILE=/path/to/file.pem` instead.

**Comment by Sairam90** [comment]
Thank you!..setting SSL_CERT_FILE env worked .. but could you let me know how --native-tls arg could be used ?

**Comment by WSF-SEO-AM** [comment]
This SSL_cert_file for me never worked. I got airways error messages circa a file not being valid when I use that one elsewhere

**Comment by WSF-SEO-AM** [comment]
@zanieb I was hoping if there is any change and or chance to get more informations on how uv retrieve the local PEM file.
A --debug doesn't show the file being targeted. And I get that in the end it should be also sourcing from the SSL_CERT_FILE environment variable. 

But a valid certiificate specified in that folder keep triggering an UnknownIssuer certificate output, but when I ran a pip install all works fine.

Do you have any clue?

**Comment by zanieb** [comment]
We don't implement the TLS stack ourself, so it's really hard for me to say what the problem is. `RUST_LOG=trace` might have more information. The certificate type might just not be supported by the library we use for TLS, in which case we'd need enough details to open an issue there.
