### ISSUE TITLE
`uv publish` interactive like twine?

### ISSUE THREAD

**Issue by hauntsaninja** [astral-sh/uv#8073]
I've been doing `uvx twine upload dist/*` instead of `uv publish` because twine gives you a nice prompt for token and you don't have to worry about leaking a credential into shell history or something. Maybe this is something `uv publish` could also do?

**Comment by konstin** [comment]
Mentoring instructions: When there are no token, no trusted-publishing and no keyring, we should ask for the username (if not given) and the password. For this, the `console` crate should be used, so we don't add another heavy depedency, like in https://github.com/astral-sh/uv/blob/71d5661bd8d5d6c60dbb02c4285c22fd06894c17/crates/uv-console/src/lib.rs. We should provide an interactive hint that tokens can be used as username/password with username `__token__`.
