### ISSUE TITLE
when  I run  `uv  pip  sync requirements.txt`   , the  environment  is  not be  updated  

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#8088]
win11

![image](https://github.com/user-attachments/assets/6c962536-4e1f-4647-8e6a-e498eb254a3d)

#  but   pyproject.toml    
![image](https://github.com/user-attachments/assets/bc5c6734-a0e8-4977-bdf9-d8ca026255ba)

**Comment by Super1Windcloud** [comment]
So,  I  think this command   of  ` uv add -r requirements.txt   ` can  instead it  .

**Comment by charliermarsh** [comment]
Yeah I think you're looking for `uv add` here as you mentioned above.
