### ISSUE TITLE
Add frozen config in settings

### ISSUE THREAD

**Issue by ygorpontelo** [astral-sh/uv#8094]
uv is an excellent project, thanks for developing it!

From what i read in the docs, the run and sync command will always try to update the lock file. This is not really the behaviour i want, so i need to pass the flag --frozen to those commands everytime. Other people involved in the project also need to remember to add that flag as well. It would be nice to have a setting i can put in pyproject.toml to indicate i want those two commands to always have that flag. Something like:

```
[tool.uv]
frozen = ["sync", "run"]
```

Maybe other flags could have this too? I mainly want the frozen because it's easy to forget and i had to revert the lock files a couple times. I'm also a bit concerned with the add command that also always updates the other deps, but the flag for that one would be "no-sync" right?

**Comment by czechnology** [comment]
This seems related to #8321.

**Comment by ygorpontelo** [comment]
@czechnology  you are right. That should solve the use case i want, closing it.

**Comment by provinzkraut** [comment]
I'm in the same boat, but I would actually prefer if this were a config option / "install without updating" a separate command. I prefer not having my uv config spread between env vars and `pyproject.toml`, and would rather it just be in one place. Maybe this can be reopened? :)
