### ISSUE TITLE
Feature suggestion: Auto create of venv

### ISSUE THREAD

**Issue by rafaeljcd** [astral-sh/uv#8119]
https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments

> When running a command that mutates an environment such as uv pip sync or uv pip install, uv will search for a virtual environment in the following order:
> An activated virtual environment based on the VIRTUAL_ENV environment variable.
> An activated Conda environment based on the CONDA_PREFIX environment variable.
> A virtual environment at .venv in the current directory, or in the nearest parent directory.
>
> If no virtual environment is found, uv will prompt the user to create one in the current directory via uv venv.

According to the docs, this is the current flow of environment discovery. Instead of prompting user to create a venv, it would automatically create venv in order to skip some steps and save developer time.

**Comment by charliermarsh** [comment]
We do automatically create it for the "project" APIs (`uv run`, `uv sync`, etc.), but not for the "pip" APIs (`uv pip install`, etc.). I think that's the right call -- it would be too surprising to users to automatically create it in the "pip" API commands which are intended to be closer to existing `pip` workflows.
