### ISSUE TITLE
support scripts defined in `pyproject.toml`

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/uv#8122]
pdm supports a `scripts` section in `pyproject.toml` where you can define scripts specific top your project that can be called from the command line [or from vscode](https://marketplace.visualstudio.com/items?itemName=GabDug.pdm). npm has the same thing in `package.json`.

it would be nice if uv supported this too, perhaps under `[tool.uv.scripts]`

**Comment by b0o** [comment]
Related: https://github.com/astral-sh/uv/issues/5903

**Comment by DetachHead** [comment]
looks like the same thing, closing this as a duplicate
