### ISSUE TITLE
Using UV to manage the system installation

### ISSUE THREAD

**Issue by guillemc23** [astral-sh/uv#8126]
I don't think that this is an issue, it's most likely a question.

In my case, I am using the [GDAL official docker image](https://github.com/OSGeo/gdal/pkgs/container/gdal/259415026?tag=ubuntu-small-3.9.2) that already comes with its bindings and Python packages properly installed. I would like to use UV to manage this system's Python installation and to add other packages on top of it. I have seen the flag `--system` but I'm not certain what it does, it definitely doesn't let me to do this.

For example, the system's installation has the `gdal` package properly installed but not `pandas`, so I would like to use UV to install `pandas` on the system's installation and run my scripts without the need for creating a virtual environment.

I have tested as well setting the following environment variables:
```
ENV UV_SYSTEM_PYTHON "true"
ENV UV_PYTHON_PREFERENCE "only-system"
```
But still, when I run `uv run --frozen python main.py`, it creates a virtual environment instead of running over the system instalation. This also happens when running `uv sync` 🤔 

FYI: GDAL is a geospatial set of tools that are usually quite tedious to install, so using the official docker image is a practical way to do so, better than just starting from the Python image and installing GDAL to it

**Comment by Super1Windcloud** [comment]
#  I think that    you can    ` uv pip install --system`

**Comment by guillemc23** [comment]
What about the running something using the system python?

**Comment by charliermarsh** [comment]
You can set `UV_PROJECT_ENVIRONMENT` to a system interpreter -- see here: https://github.com/astral-sh/uv/pull/6834#issuecomment-2319253359
