### ISSUE TITLE
Support for script-files

### ISSUE THREAD

**Issue by petrprikryl** [astral-sh/uv#8134]
Hi, are there any plans for `script-files` support like in [setuptools `tool.setuptools.script-files`](
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration)? E.g. for shell scripts.

Maybe useful:
* https://discuss.python.org/t/are-python-package-developers-just-not-supposed-to-package-shell-scripts-as-a-general-practice/25665
* https://docs.python.org/3.11/distutils/setupscript.html#installing-scripts
* https://github.com/python-poetry/poetry/issues/2310

**Comment by charliermarsh** [comment]
@konstin -- Would this be part of the build backend work (eventually), or is it separate?

**Comment by BenConstable9** [comment]
Is there any plan for this? 

I would like to move from Poetry to UV but this is blocking it for one of my projects. 

I would like the equivalent of: `tool.poetry.scripts`

**Comment by my1e5** [comment]
@BenConstable9 - I believe `[project.scripts]` which is part of the official `pyproject.toml` specification will cover the functionality you are looking for? See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts

**Comment by zanieb** [comment]
Note that packages using `script-files` have been the cause of various bug reports already. The `[project.scripts]` table is the recommended way to create cross-platform scripts. You can use that today https://docs.astral.sh/uv/concepts/projects/config/#command-line-interfaces (and you can also use `setuptools` and `script-files` with uv)

**Comment by konstin** [comment]
There are three different features known as "scripts":
* `project.scripts` and `project.gui-scripts`: These are standards that should be supported by every build backend, and will also be supported by uv's build backend (https://github.com/astral-sh/uv/pull/9635). Note that they already work with any build backend you're using: After installing the package, the scripts are installed and added to PATH by `uv run` or virtual environment activation. Poetry calls those `tool.poetry.scripts`.
* The `scripts` data folder. Similar to `project.scripts` and `project.gui-scripts`, they are standards and already supported if your build backend uses them . The difference to `project.scripts` is that they aren't generated on installation, but just files copied to the correct target, so they are less portable.
* A task runner, such as https://github.com/astral-sh/uv/issues/5903

If you move from poetry to uv, you currently need to configure this for the build backend your using, not in uv itself.

**Comment by BenConstable9** [comment]
Thank you all. I had somehow missed this in the documentation. I will look to use it.
