### ISSUE TITLE
brew install exceeds expectations

### ISSUE THREAD

**Issue by wu-clan** [astral-sh/uv#8141]
I ran `brew install uv` on an intel Macbook Pro and the build took hours, unbelievable!

![image](https://github.com/user-attachments/assets/a188fd91-ad45-4fdb-86b7-f4c9391fb502)

**Comment by kahojyun** [comment]
It seems that you are using old macos version `monterey` and lots of brew packages drop prebuilt binary support for it, including `xz`, `cmake`, `python`, `llvm`. You can check if a package has prebuilt binary for your system [here](https://formulae.brew.sh/formula/uv#default).

**Comment by wu-clan** [comment]
Thanks for clearing this up, brew has already issued a MacOS 12 deprecation warning, I think that's exactly why!
