### ISSUE TITLE
What is the origin of the name `uv`?

### ISSUE THREAD

**Issue by johnthagen** [astral-sh/uv#8149]
When I introduce `uv` to my colleagues, a surprising number of them ask me "what does `uv` stand for?" or "where did that name come from?".

Some come up with their own interpretations such as "ultraviolet light = fast", etc.

Is there anything documented about the origin of the name "uv", if only so I can point the extra curious folks at? Was it simply chosen as a short CLI name that didn't conflict with other Linux utilities? Is there a deeper meaning known only to Charlie? 😄

**Comment by alphavector** [comment]
> We considered a ton of names — it's really hard to pick a name without collisions this day so every name was a balance of tradeoffs.
> 
> uv was given to us on PyPI, is Astral-themed (i.e. **ultraviolet** or **universal**), and is short and easy to type.
> 
> 🤷‍♀️

https://github.com/astral-sh/uv/issues/1349#issuecomment-1986451785

**Comment by charliermarsh** [comment]
Yeah for me it's short for "ultraviolet" though we liked that there were a few different possible interpretations. We wanted something that was (1) available on PyPI and elsewhere, (2) had minimal conflicts with other software projects, and (3) was easy to type!
