### ISSUE TITLE
`pip-compile` usage statistics

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#815]
I performed the following GitHub code searches:

- `"pip-compile"` [79.4k files](https://github.com/search?q=%22pip-compile%22&type=code)
- `"pip compile "` [71.2k files](https://github.com/search?q=%22pip-compile%20%22&type=code)
- `"pip-compile-multi"` [3.2k files](https://github.com/search?q=%22pip-compile-multi%22&type=code).  
- `"This file is autogenerated by pip-compile"` [50.7k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22&type=code)
- `"This file is autogenerated by pip-compile" language:text` [50.4k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext&type=code)
- `"This file is autogenerated by pip-compile" language:text  NOT is:archived` [45.6k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived&type=code)
- `"This file is autogenerated by pip-compile" language:text  NOT is:archived NOT is:fork` [25k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork&type=code)
- `"This file is autogenerated by pip-compile-multi"` [2.6k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile-multi%22&type=code)
- `"This file is autogenerated by pip-compile-multi" language:text  NOT is:archived` [2.5k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile-multi%22+language%3Atext++NOT+is%3Aarchived&type=code)
- `"This file is autogenerated by pip-compile-multi" language:text  NOT is:archived NOT is:fork` [1k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile-multi%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork&type=code)
- `"This file is autogenerated by pip-compile" language:text NOT is:fork repo:DataDog/dd-trace-py` [2k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork+repo%3ADataDog%2Fdd-trace-py+&type=code)
- `"This file is autogenerated by pip-compile" language:text  NOT is:archived NOT is:fork org:DataDog` [3.6k files](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork+org%3ADataDog&type=code)
- `"This file is autogenerated by pip-compile" language:text  NOT is:archived NOT is:fork NOT org:DataDog` [21.5k](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork+NOT+org%3ADataDog&type=code)

From which we can derive that:

- At most, 5% of `pip-compile` users opt for the derivative `pip-compile-multi` project
- There are probably less than 20k public projects on GitHub using `pip-compile`
    - Many projects generate more than one requirement file
    - Alarmingly `DataDog` has 3.6k generated files with 2k in a single repository

A [search for projects](https://github.com/search?q=%22This+file+is+autogenerated+by+pip-compile%22+language%3Atext++NOT+is%3Aarchived+NOT+is%3Afork+NOT+org%3ADataDog+NOT+repo%3Asaltstack%2Fsalt&type=code) shows some notable users:

- [trio](https://github.com/python-trio/trio/blob/ec011f48cc78e70a51c3ad36e9fa61fa7b1e8d50/docs-requirements.txt)
- [lyft](https://github.com/lyft/confidant/blob/d3c8239c9003ef02fd8911ea0795c08c8d442e8b/requirements3.txt)
- [jinja](https://github.com/pallets/jinja/tree/d594969d722ceb4e8f3da8861befc9c0ac87ae1b/requirements)
- [ray](https://github.com/ray-project/ray/blob/363ebac4c1871076d4fc36ba7b6159a5fb8269c6/ci/ray_ci/requirements.txt)
- [llvm](https://github.com/intel/llvm/blob/0502d114e6d86ef08ae41cb2614c25338e708cf0/llvm/utils/git/requirements_formatting.txt)
- [watchfiles](https://github.com/samuelcolvin/watchfiles/tree/9f19a18da5323d0e63a2ee16c47ed6c819f89be5/requirements)
- [readthedocs](https://github.com/readthedocs/readthedocs.org/tree/5ab5019928262ece61e3c67f1a02616c84636b8f/requirements)
- [click](https://github.com/pallets/click/tree/cab9483a30379f9b8e3ddb72d5a4e88f88d517b6/requirements)
- [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/056864d9c558131d2706b46f6ddf084671b428b6/build_tools/azure/python_nogil_lock.txt)
- [json-schema-spec](https://github.com/json-schema-org/json-schema-spec/blob/2cb7c7447f9b795c9940710bf0eda966a92c937f/requirements.txt)

**Comment by txomon** [comment]
My two cents, I would expect applications and not libraries to make more use of pip-compile-multi, as many times, running VS testing requirements are separate in these (it's been the case in all companies I have seen pip-compile / pip-compile-multi being used).

Libraries are less likely to rely on external dependencies (at least in python) than applications. Having requirements pinned is usually only used for tests, because runtime dependencies can't be pinned.

**Comment by charliermarsh** [comment]
(Gonna close this for now.)
