### ISSUE TITLE
uv tool version must be shared for all developers on a project

### ISSUE THREAD

**Issue by benjs** [astral-sh/uv#8165]
We very much like the "uv tool" command, because tools can be installed in a separate venv.

However, when working with a CI and multiple developers, everyone needs to know what the current version of the tool is.
It would be nice if the tool versions can be shared, e.g. via the pyproject.toml.

uv version:
```
uv 0.4.18
```

**Comment by charliermarsh** [comment]
I believe we have a design for "project-level tools" in https://github.com/astral-sh/uv/issues/3560. I think that will cover the use-case you're describing -- gonna merge into that issue.
