### ISSUE TITLE
FORCE_COLOR wins over `--color never`

### ISSUE THREAD

**Issue by aberres** [astral-sh/uv#8173]
```
❯ uv --version
uv 0.4.20 (0e1b25a53 2024-10-08)
```

The following call uses color codes. As coloring is explicitly disabled, I would expect no colors.

`FORCE_COLOR=1 uv pip compile pyproject.toml --color never`

I ran into this when converting a legacy CI pipeline to use `UV`. Piping the `uv` result into the next tool leads to funny results. Only using `-o` helps to get rid of the colors.

**Comment by Aditya-PS-05** [comment]
Now, I read about it and you are experiencing the right behavior as the environment variables have more precedence or value than the cli commands.

**Comment by Aditya-PS-05** [comment]
@charliermarsh, 
I have made the changes instructed by you sir.
