### ISSUE TITLE
Make UV_PYTHON_INSTALL_MIRROR configurable in uv.toml

### ISSUE THREAD

**Issue by Vynce** [astral-sh/uv#8186]
Please consider making `UV_PYTHON_INSTALL_MIRROR` and `UV_PYPY_INSTALL_MIRROR` configurable in the user-scoped `uv.toml` config file. I think this is a separate use case from the similar `pyproject.toml` request in #8166.

Related:
#8015
#8068

**Comment by zanieb** [comment]
I have no problem with supporting this!

**Comment by paveldikov** [comment]
I think I mentioned this somewhere else, but this would be a good one for enterprises who may want to adopt `uv python install` in a way that complies with internal security policy/tooling.

**Comment by benjs** [comment]
With my issue #8166 I did not mean to specify it in exactly pyproject.toml, I am also fine if it can be specified somewhere else with the code :) 
So I also would support this !
