### ISSUE TITLE
`uv python uninstall 3.13` does not uninstall 3.13t

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#8189]
Should it?

**Comment by zanieb** [comment]
I'm not sure. They're intentionally distinct.

`uv run -p 3.13 python -c "import sys; print(sys.base_prefix)"` matches the free-threaded version if it's installed which is sort of problematic — I don't know if we should ever consider 3.13 and 3.13t equivalent.

**Comment by charliermarsh** [comment]
Yeah interesting. This was also mentioned on Discord:

```
uv run -p cpython-3.13.0-linux-x86_64-gnu python
Python 3.13.0 experimental free-threading build
```
