### ISSUE TITLE
feature: uvx for github repos

### ISSUE THREAD

**Issue by sslivkoff** [astral-sh/uv#8199]
`uvx` is an awesome feature. It would be very nice to have something like

`uvx <github_repo_url>`

to run packages/commits that are not on python pypi

Use cases
1) execute the latest commit of a package without needing to cut a pypi release
2) execute private github repos that cannot go on pypi
3) if able to execute specific commits, this would enable an efficient form of git bisect

**Comment by snth** [comment]
I believe you can do this with the [`--from`](https://docs.astral.sh/uv/guides/tools/#commands-with-different-package-names) option, for example:

    uvx --from git+https://github.com/snth/markdown-crawler@uvx markdown-crawler

In general

    uvx --from git+https://github.com/<USER>/<REPO>@<TREEISH> <ENTRYPOINT>

**Comment by cbrnr** [comment]
Is there an easy way to check out a PR using its number? I know that it works by appending the branch name associated with the PR, but I'd find it easier to just use the PR number.

This works:

```
uvx --from git+https://github.com/cbrnr/mnelab@export-bv-events mnelab
```

But this doesn't (the PR corresponding to the `export-bv-events` branch is 417):

```
uvx --from git+https://github.com/cbrnr/mnelab/pr/417 mnelab
```

**Comment by thatch** [comment]
> Is there an easy way to check out a PR using its number?

Yes, for github specifically see 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

Append `@pull/$num/head` as if it were a branch name.

**Comment by richardkmichael** [comment]
The tools-related documentation does not mention this, but `--from` is not required, and neither is the command name if it matches the repository ("package") name.

This permits a tidy invocation to run the command named `bar`:

`uvx git+https://github.com/foo/bar`
