### ISSUE TITLE
Inability to Switch Between Python 3.13 and 3.13t Using uv on macOS and Docker

### ISSUE THREAD

**Issue by mrchoke** [astral-sh/uv#8207]
I encountered an issue when switching between different versions of Python (3.13 and 3.13t) on macOS, specifically when Python 3.13 is installed via Homebrew. This issue is also reproducible within a Docker image of Python 3.13.

**Steps to reproduce:**

1.	If Python 3.13 is already installed on the system (e.g., installed via Homebrew on macOS), I run the script with Python 3.13t using the command:

```
uv run -p3.13t script.py
```

2. uv correctly downloads the Python 3.13 free-thread binary, and the script runs successfully.
3.	However, if I try to run the script with Python 3.13 afterwards (without the “t” suffix), it continues to use Python 3.13t and does not switch back to Python 3.13 as expected.
4.	In a scenario where Python 3.13 is not pre-installed on the system:
* If I run the script with Python 3.13t first, I can no longer switch back to Python 3.13 later.
* Conversely, if I start by running the script with Python 3.13, uv downloads the correct binary, and I am able to switch between Python 3.13 and 3.13t freely.
5.	This issue can also be reproduced within a Docker container running Python 3.13.

**Expected Behavior:**

After running the script with Python 3.13t, I should be able to switch back to Python 3.13 without it being stuck on Python 3.13t.

**Actual Behavior:**

Once Python 3.13t is used, it does not allow switching back to Python 3.13, even if explicitly requested.

Any suggestions or fixes for this issue would be appreciated!

uv version: 0.4.21

**Comment by charliermarsh** [comment]
\cc @zanieb

**Comment by zanieb** [comment]
I believe this was fixed in https://github.com/astral-sh/uv/pull/8191 and will be released today

**Comment by charliermarsh** [comment]
Thanks!
