### ISSUE TITLE
Support cpython 3.7.9 on linux

### ISSUE THREAD

**Issue by timendum** [astral-sh/uv#8213]
Commit 5f33915e03faffbad46aa0720410dca3f76dcc03 removed the download configuration for CPython 3.7 on linux.

I think it was by accident, the current `uv` version should support python from 3.7.

This issue blocks my tests on 3.7 via Github Actions, it returns:

    Searching for Python versions matching: Python 3.7
    error: No download found for request: cpython-3.7

**Comment by bergentroll** [comment]
Still `no download` for `cpython-3.7-linux-x86_64-gnu` on `v0.8.18`.

**Comment by NyaMisty** [comment]
Still no download for cpython-3.7-linux-x86_64-gnu on v0.9.21

**Comment by konstin** [comment]
Python 3.7 has been end-of-life for 2.5 years now with no bugfix and no security updates (https://devguide.python.org/versions/). We won't add support for this version anymore.

**Comment by bergentroll** [comment]
@konstin, nevertheless it us EoL, some people have to support code for it.

**Comment by bergentroll** [comment]
OK, [pyenv](https://github.com/pyenv/pyenv) is still in charge.

```bash
pyenv install 3.7  # Or whatever version
pyenv local 3.7  # Creates .python-version file
pyenv exec python -m venv .venv  # Wokrs without modifying ~/.bashrc
source .venv/bin/activate
python -V  # Now we have a fair Python 3.7 environment
uv init
# And go on...
uv add ipython
ipython  # Should display chosen Python version at header
```

`pyenv install --list` to know available versions.
