### ISSUE TITLE
How can I test that my package will do the right thing when it is installed?

### ISSUE THREAD

**Issue by vedantroy** [astral-sh/uv#8232]
I have written a simple Python package -- is there a way to test that people will be able to import it (if they install it from PyPi, etc.), and call the expected functions -- without me having to publish the package to the test PyPi registry.

Also (this is probably not be the right place to ask this, but maybe the responder will just know the answer off the top of their head) ... I'm trying to do the following:
```
pyproject.toml
src/
    foo/
        bar.py <-- imports from baz.py using "from foo.baz import some_function"
        baz.py
```

And I want people to be able to run bar with `python3 -m foo.bar:main`, but right now I'm getting errors that the module "foo" does not exist.

The FluxAI repository somehow has made this work: https://github.com/black-forest-labs/flux. Do anyone know how?

**Comment by samypr100** [comment]
This might help

1. Build it with `uv build`, copy the wheel from dist
2. Make a new virtual env, `uv pip install /path/to/wheel`
3. Run it using something like `uv run python -m foo.bar:main`

**Comment by paveldikov** [comment]
^ the above high-level approach is also encapsulated by frameworks such as `tox` (and you can use `tox-uv` so that you benefit from the performance boost of `uv venv` and `uv build`)
