### ISSUE TITLE
Support https://astral.sh/uv/install.sh running as Nobody

### ISSUE THREAD

**Issue by VirtualTim** [astral-sh/uv#8242]
I would like to use uv as a jenkins action, similar to https://github.com/astral-sh/setup-uv.
When I'm running inside a docker container, Jenkins runs as `Nobody` (specifically `-u 1000:1000`).
`$HOME` evaluates to `/`, which I do not have permission to write to.

It seems like I can get things working by running:
```sh
export CARGO_HOME=$WORKSPACE/cargo
export HOME=$CARGO_HOME/uv
curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -v --no-modify-path
export UV_CACHE_DIR=$CARGO_HOME/.cache/uv
```

I have concerns about how future-proof this is. Is the file written to `$HOME/.config/uv/uv-receipt.json` important?
Is this likely to cause other things to break?
It would be nice if I could install this without having to temporarily modify `$HOME`.

**Comment by charliermarsh** [comment]
In the next release, you should be able to set `UV_UNMANAGED_INSTALL` to the exact location you want to use, without a receipt: https://opensource.axo.dev/cargo-dist/book/installers/usage.html#receipt. It seems like a good fit for your use-case.

**Comment by VirtualTim** [comment]
Awesome. Thanks for the quick response, and for updating the documentation.

**Comment by VirtualTim** [comment]
@charliermarsh I just tried out uv 0.4.23 and 0.4.24, and I still need to modify `HOME`.
Installing like this works fine:
```
export CARGO_HOME=$WORKSPACE/cargo
export UV_UNMANAGED_INSTALL=$CARGO_HOME/uv
export UV_CACHE_DIR=$CARGO_HOME/.cache/uv
curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -v --no-modify-path
```

However when I attempt to setup a venv I get the following error:
```
uv venv --python 3.13
  x failed to create directory `/.local/share/uv/python`
  `-> Permission denied (os error 13)
```
same command with a modified `$HOME`:
```
export HOME=$(pwd)
uv venv --python 3.13
Using CPython 3.13.0
Creating virtual environment at: .venv
```

Should I create a separate issue?

**Comment by charliermarsh** [comment]
@VirtualTim -- That looks a bit different. You may need to set `UV_PYTHON_INSTALL_DIR` if you want the `python` installs to go elsewhere (see: https://docs.astral.sh/uv/configuration/environment/).

**Comment by VirtualTim** [comment]
I'm now running with:
```sh
export UV_UNMANAGED_INSTALL=$WORKSPACE/cargo
export UV_PYTHON_INSTALL_DIR=$UV_UNMANAGED_INSTALL/python
export UV_CACHE_DIR=$CARGO_HOME/.cache/uv
export uv=\$UV_UNMANAGED_INSTALL/uv
curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -v

```

**Comment by VirtualTim** [comment]
Also, if you'd like, I could add a quick guide here https://docs.astral.sh/uv/guides/ on how to run as Nobody?
The guide would basically just be a copy/paste of the snippet I commented above.

**Comment by zanieb** [comment]
I don't think is a common enough use-case to cover in the top-level guides. I'd definitely appreciate some content on it though. If you put up a pull request with the content I can try to figure out where it fits.
