### ISSUE TITLE
Docs: Mention that `.python-version` is obsolete if `project.requires-python` is present in `pyproject.toml`?

### ISSUE THREAD

**Issue by jnussbaum** [astral-sh/uv#8247]
First a big thumbs up for the great work you're doing with ruff and uv! We have adopted both in our company, and we're overwhelmed!

I have just a quick request for clarification: https://docs.astral.sh/uv/guides/projects/ implies that it is always necessary (or at least best practice) to have the file `.python-version` checked in. But for standards-compliant projects that define `project.requires-python` in `pyproject.toml`, this seems obsolete. I tried it out, and in fact, uv correctly detects `project.requires-python` and installs the intended python version, even without `.python-version`. 

In our project, I wanted to remove `.python-version`, so that we don't have the python version defined in 2 separate places. But then I became insecure because of the documentation.

Therefore, I think it would be helpful to add a remark to https://docs.astral.sh/uv/guides/projects/, mentioning that `.python-version` is obsolete in this case. WDYT?

**Comment by charliermarsh** [comment]
The `.python-version` file is not quite obsolete with `requires-python` -- they're subtly different. `requires-python` is the range of versions supported by your project. `.python-version` is the exact version you want to use when developing. For example, if you're working on a library, your `requires-python` might be `>= "3.10"`. But when developing on your machine, you might want to use `3.12.4` by default -- so you'd set that in a `.python-version`.

**Comment by jnussbaum** [comment]
Thanks for this information, that makes sense 👍

**Comment by apoorvkh** [comment]
Hey, I wonder if we can just add a `tool.uv.python-resolution` (which could be `highest`, `lowest`, `lowest-major`, `3.10.15`, etc.) but would be overriden if `.python-version` does exist.

This would save projects from one excess file (`.python-version`) in the git tracking. And would permit maintainers to specify a certain Python version for development, but give contributors a hook to change this if desired (and without altering any git-tracked file).

Happy to attempt a PR if this sounds reasonable!

**Comment by zanieb** [comment]
See #5609 and https://github.com/astral-sh/uv/issues/7779

Yeah; I'd like to have a `python-strategy` or something, it just hasn't been implemented. If you're interested, you're welcome to give it a go.

**Comment by ANL06488** [comment]
I understand the need for specifically specifying a python version, but I would argue a better default behaviour for `uv init` should be to specify this as a setting within pyproject.toml with the same reasoning as in #8920

**Comment by charliermarsh** [comment]
They have different meanings though. `requires-python` is not meant for that purpose -- it's meant to indicate your minimum-supported Python version. They're distinct concepts, and I don't think it's a good practice to encourage them to be mixed like that.

**Comment by ANL06488** [comment]
> They have different meanings though. `requires-python` is not meant for that purpose -- it's meant to indicate your minimum-supported Python version. They're distinct concepts, and I don't think it's a good practice to encourage them to be mixed like that.

No, I'm saying add a specific `tools.uv` setting like `python-version` inside pyproject.toml apart from the existing `requires-python` setting.

Yes there's a need to specify a specific python version, but there's no need for it to be specified in a separate file.

**Comment by zanieb** [comment]
There's already an issue tracking that at https://github.com/astral-sh/uv/issues/4970 and https://github.com/astral-sh/uv/issues/4359

There is a reason to have it in a separate file — other tools can read it. For example, GitHub Actions's `setup-python` action can read a version from a `.python-file` but not from a `[tool.uv]` option.

**Comment by ANL06488** [comment]
I see, once those PRs are merged, I'd still argue that the default behaviour should still be to put it in pyproject.toml first, and if needed a user can always move it to it's own file.

**Comment by edmorley** [comment]
IMO this issue should be wontfixed, since the `.python-version` file is not equivalent to the `pyproject.toml` `requires-python` field. The latter can be a range, which is not suitable/safe for bootstrapping/deployment purposes.

I'd love for there to be an official single-version field in `pyproject.toml` (where the single version can be either the full `X.Y.Z` version, or a major `X.Y` version), but until there is, there is no like-for-like replacement for `.python-version` defined in the `pyproject.toml` spec. (If people would like to see one, then I'd recommend starting a [PEP](https://peps.python.org/) upstream)

**Comment by zanieb** [comment]
I agree, we won't be saying it's obsolete. Perhaps there's room to improve the documentation though? @charliermarsh I'm not sure if you were planning on revisiting that. Regardless, we can track in a clearer issue.
