### ISSUE TITLE
Does uv provide package handling for multiple code locations?

### ISSUE THREAD

**Issue by GellertPalfi** [astral-sh/uv#8251]
I would like to switch to uv, however Im running dagster that have multiple code locations with some common dependencies but some are only there for one project some only the other, they are now listed in 2 req.txt files:
Location A:
```
dagster==1.7
dagster-dbt==0.23
pandas==2.1.4
```  
Location B:
```
dagster==1.7
dagster-dbt==0.23
pyarrow==16.0.0
```
Is it possible to set this with only one pyproject.toml file?   
Something like this:
```
Common:
dagster==1.7
dagster-dbt==0.23

Location A:
pandas==2.1.4

Location B:
pyarrow==16.0.0
```  
Im open to suggestions if this looks completly wrong.  
Also i dont necessarily want to have multiple `.python_version` files as python is always the same for all locations

**Comment by charliermarsh** [comment]
By code locations, do you mean indexes, like PyPI?

**Comment by GellertPalfi** [comment]
No, sorry. This is a dagster concept, basically they are just different folders, with seperate requirements as seen above but still in one project

**Comment by zanieb** [comment]
Sounds like https://docs.astral.sh/uv/concepts/workspaces/

**Comment by zanieb** [comment]
We don't let you define the common dependencies in the workspace root yet though

**Comment by GellertPalfi** [comment]
I looked at this, but we have conflicting dependencies, so i see that i should use path dependencies. However its not super clear for me how to use it based on the example in the documentation. Do you have any more examples?

**Comment by tspencerdata** [comment]
Did you ever find a solution on this one? 

I have a similar situation and am thinking of moving to uv. I was thinking of setting it up along these lines:

/dagster-project/
├── workspace.yaml
├── code_loc1/
│   ├── pyproject.toml
│   ├── uv.lock
│   └── src/...
├── code_loc2/
│   ├── pyproject.toml
│   ├── uv.lock
│   └── src/...
├── code_loc3/
│   ├── pyproject.toml
│   ├── uv.lock
│   └── src/...
├── .venvs/
│   ├── code_loc1/
│   ├── code_loc2/
│   └── code_loc3/
