### ISSUE TITLE
`uv pip install` fails when building from git repo

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/uv#8252]
when installing my package from github, uv seems to hang forever during building.

it's an npm package bundled inside a pypi package, using pdm's build backend. it seems to hang forever during the stage where it installs its npm dependencies with lerna.

# to reproduce

sorry the build process is quite convoluted, i've commented out some stuff in this branch to make it not take as long to build. i could probably try and cut out some more of the process to try and make a minimal repro, but i've been at this for hours so i hope this repro on github is enough

```
uv pip install --verbose git+https://github.com/detachhead/basedpyright@b9080d7c9d2065259cfb900a44cd7ca1dafc79e3`
```

# logs
this is just an excerpt from where it hangs, but i can provide more if needed
```
DEBUG Writing record name=PackageName("nodejs-wheel-binaries")
DEBUG Creating PEP 517 build environment
DEBUG Calling `pdm.backend.get_requires_for_build_wheel()`
DEBUG Calling `pdm.backend.build_wheel("C:\\Users\\user\\AppData\\Local\\uv\\cache\\sdists-v4\\git\\2a2c7b145eaadab9\\b9080d7c9d206525\\.tmpg3uvN5", {}, None)`
DEBUG npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much 
more comprehensive and powerful.
DEBUG npm warn deprecated read-package-json@6.0.4: This package is no longer supported. Please use @npmcli/package-json instead.
DEBUG npm warn deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
DEBUG npm warn deprecated npmlog@6.0.2: This package is no longer supported.
DEBUG npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
DEBUG npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
DEBUG npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
DEBUG npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
DEBUG npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
DEBUG npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
DEBUG npm warn deprecated gauge@4.0.4: This package is no longer supported.
DEBUG 
DEBUG > postinstall
DEBUG > node ./build/skipBootstrap.js || npm run install:others
DEBUG
DEBUG 
DEBUG > install:others
DEBUG > cross-env SKIP_LERNA_BOOTSTRAP=yes lerna exec --no-bail npm install
DEBUG
DEBUG lerna notice cli v8.1.8
```
it hangs at that last line.

# environment info

i've tested this on a couple different environments:

uv 0.4.22, 0.4.19
python 3.12, 3.13
windows 10, windows 11, ubuntu 22.04

# things i've tried

when installing it via any of these other methods, it builds successfully and doesn't hang (though it still takes a couple minutes to build):

- installing it with pip instead of uv:
    `pip install git+https://github.com/detachhead/basedpyright@b9080d7c9d2065259cfb900a44cd7ca1dafc79e3`
- installing it with pdm
    `pdm add --dev git+https://github.com/detachhead/basedpyright@b9080d7c9d2065259cfb900a44cd7ca1dafc79e3`
- installing it from a local file path
    `uv pip install C:\Users\user\basedpyright` (the root of my local checkout of the repo)

(possibly related? #8225)

**Comment by charliermarsh** [comment]
Thanks for the repro.

**Comment by charliermarsh** [comment]
Interestingly, it works fine if I clone the repo and install.

**Comment by charliermarsh** [comment]
Is there any way to get more logging out of lerna?

**Comment by charliermarsh** [comment]
Alright, it looks like Lerna is failing due to this:

```rust
// Add a phony .git, if it doesn't exist, to ensure that the cache isn't considered to be
// part of a Git repository. (Some packages will include Git metadata (like a hash) in the
// built version if they're in a Git repository, but the cache should be viewed as an
// isolated store.).
// We have to put this below the gitignore. Otherwise, if the build backend uses the rust
// ignore crate it will walk up to the top level .gitignore and ignore its python source
// files.
fs_err::OpenOptions::new().create(true).write(true).open(
    root.join(CacheBucket::SourceDistributions.to_str())
        .join(".git"),
)?;
```

I'm not sure how to resolve -- we need this for the reason described in the comment.

**Comment by charliermarsh** [comment]
It's something specific to Lerna, related to the use of a blanket `.gitignore` in the cache:

```rust
// Add the .gitignore.
match fs_err::OpenOptions::new()
    .write(true)
    .create_new(true)
    .open(root.join(".gitignore"))
{
    Ok(mut file) => file.write_all(b"*")?,
    Err(err) if err.kind() == io::ErrorKind::AlreadyExists => (),
    Err(err) => return Err(err),
}
```

I have no idea why that's causing problems for Lerna though. I tried a bunch of other tricks like adding a non-empty `.gitignore` one subdirectory below, but none of them helped.

**Comment by charliermarsh** [comment]
You can reproduce this without uv.

```
mkdir foo
cd foo
cat "*" > .gitignore
git clone https://github.com/detachhead/basedpyright
cd basedpyright
git checkout b9080d7c9d2065259cfb900a44cd7ca1dafc79e3
npm i
npm run postinstall
```

This just hangs. I think it should be filed with Lerna to be honest.

**Comment by DetachHead** [comment]
thanks! i'll raise an issue there

**Comment by charliermarsh** [comment]
Thank you, feel free to tag me if needed.
