### ISSUE TITLE
How to add extra to a dependency of a tool?

### ISSUE THREAD

**Issue by grejioh** [astral-sh/uv#8279]
I installed a tool use `requests`.
I want to use `requests[socks]` instead of the default `requests` package. I have tried the following commands:

```shell
uv tool install open-webui --with requests[socks]
uv tool install open-webui --with requests --optional socks
uv tool upgrade open-webui --reinstall-package requests[socks]
....
```

Finally, could you please confirm whether it's necessary for `uv tool` to support adding extras to dependencies?

**Comment by zanieb** [comment]
`uv tool install open-webui --with 'requests[socks]'` should work — did it not?

**Comment by LoicGrobol** [comment]
Sort of related: I installed xonsh using uv, then some plugins (xontribs) using xonsh's own manager, which amounts to installing new packages in the environment. Upon `xonsh tool upgrade xonsh`, it removed these extra packages. Is there a way to specify a list of packages that should be kept in the environment?

**Comment by KaKi87** [comment]
> `uv tool install open-webui --with 'requests[socks]'`

Thank you, I would like to suggest adding this to the documentation.

**Comment by zanieb** [comment]
https://docs.astral.sh/uv/concepts/tools/#including-additional-dependencies
