### ISSUE TITLE
How to fetch packages from a private package repo (not git repo)

### ISSUE THREAD

**Issue by dbogdoll** [astral-sh/uv#8283]
Hi all,

I couldn't find how I can specify which package should be retrieved from which package repository.
Most of the packages are retrieved from pypi, but for some packages we would like to retrieve
them from a gitlab instance, either via a group URL or a project URL. How can I specify that?

In poetry we could add the different URLs and bind them to kind an identifier and then with poetry config
I could add then authentication to those identifiers. Is there something similiar in uv?

Thanks.

**Comment by charliermarsh** [comment]
Yeah we support a similar scheme -- check out the newly updated [index](https://docs.astral.sh/uv/configuration/indexes/) documentation.

**Comment by charliermarsh** [comment]
It allows you to assign packages to indexes, define credentials in environment variables, etc.

**Comment by dbogdoll** [comment]
That looks great, but could I suggest one improvement. In addition to the ENV variables, could you also add an mechanism to store them in a file somewhere centrally? Or could you add to uv the possibility to point to a .env file where it picks up additional env variables?

Tbh. I would like to have a user and also system wide configuration file, where we could store such informations or at least link to those informations.

**Comment by charliermarsh** [comment]
You can already define indexes at the system or user level. See the docs: https://docs.astral.sh/uv/configuration/files/.
