### ISSUE TITLE
Cannot install with `uv pip install -r requirements.txt` when `--extra-index-url` is present

### ISSUE THREAD

**Issue by NF-ada** [astral-sh/uv#8290]
Hey, 

We have our own package index and when I specify deps in a `requirements.txt` I have: 

```
--extra-index-url <link>
--trusted-host <host>
my_pkg
```
I am able to use regular `pip` like `pip install -r requirements.txt` but when I try to use `uv pip install -r requirements.txt` I get: 

```
error: Unexpected '-', expected '-c', '-e', '-r' or the start of a requirement at requirements.txt:3:1)
```
Which seems to imply the file isn't parsed properly.

For compatibility with other tools, I can't do away with the `requirements.txt` sadly. Is this a bug or is there a way to fix it? 

Thanks!

**Comment by NF-ada** [comment]
> We don't support `--trusted-host` in a `requirements.txt` file.

Is there a plan to support it in the future or an alternative?

**Comment by charliermarsh** [comment]
We do support the behavior -- just not in a `requirements.txt` file. You can use `--allow-insecure-host` on the command-line or in a `uv.toml` file (https://docs.astral.sh/uv/reference/settings/#allow-insecure-host).

**Comment by zanieb** [comment]
(And no we don't intend to support it in the file https://github.com/astral-sh/uv/issues/7702)

**Comment by NF-ada** [comment]
Fair enough, thanks for the quick answer guys!
