### ISSUE TITLE
Feature request: Install only packages from an optional group

### ISSUE THREAD

**Issue by chris48s** [astral-sh/uv#8292]
Sometimes it would be useful to be able to install only the packages from an optional group (but not the main or dev dependencies).

For example: When building a documentation site, or deploying an application in CI it might be useful to only install the packages relating to documentation or deployment without also installing the application's full tree of runtime and/or dev dependencies - particularly for larger projects.

Poetry does heave this feature via the `--only` flag e.g: `poetry install --only <group>`

As far as I can tell, `uv sync` doesn't allow this via any combination of flags.

**Comment by charliermarsh** [comment]
I think we have this -- `uv sync --only-group dev` or similar.

**Comment by chris48s** [comment]
Awesome - thanks.
Yes this issue was raised on 17 Oct. Looks like this feature is new in 0.4.27 which was released on 25 Oct.

I will give this a look. Thanks
