### ISSUE TITLE
uv index feature will leak credentials to uv.lock

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#8296]
Hi, 

Maybe I am doing things wrong, but is there a way to use the new index feature without it sending credentials to uv lock?

E.g.: With something like this

```
[[tool.uv.index]]
name = "ixname"
url = "https://user:password@mynexusrepo.example.com/repository/hosted/simple/"

[tool.uv.sources]
mypackage = { index = "ixname" }

```

I will get the user and password on the index name on uv.toml

```
{ name = "mypackage", specifier = "==5.4.1", index = "https://user:password@mynexusrepo.example.com/repository/hosted/simple/" },
```

Notice this won't happen to the URL portion, which remains the same after using the new syntax

```
{ url = "https://mynexusrepo.example.com/repository/hosted/packages/mypackage/5.4.1/...", hash = "sha256:..." }
```

**Comment by inoa-jboliveira** [comment]
Hi @charliermarsh 
Thank you for looking into it. 
I did try uv 0.4.24 and I get the exact same result.

I believe the credentials should not be added to this portion of the uv lock file.
```
{ name = "mypackage", specifier = "==5.4.1", index = "https://user:password@mynexusrepo.example.com/repository/hosted/simple/" },
```

That's why I asked if I am doing something wrong. I tend to have the credentials on dev environment, but then I can supply uv.lock as is (which didn't have credentials on it before) and the client credentials would be different for each one and passed more securely in an env variable, not on the file.

**Comment by charliermarsh** [comment]
Just to confirm, did you remove the `uv.lock` before locking?

**Comment by charliermarsh** [comment]
The second thing you're describing should already be supported: https://docs.astral.sh/uv/configuration/indexes/#providing-credentials

**Comment by inoa-jboliveira** [comment]
> The second thing you're describing should already be supported: https://docs.astral.sh/uv/configuration/indexes/#providing-credentials

Very cool! I see a typo here: 

``` 
url = "https://public:koala@https://pypi-proxy.corp.dev/simple"
```

There is a 2nd https:// in the middle of the url

**Comment by charliermarsh** [comment]
Oops, thank you.

(I'll try that repro in a bit.)

**Comment by charliermarsh** [comment]
Ok looks like I missed something here. Will fix.

**Comment by charliermarsh** [comment]
Embarrassingly I had tests for this but the tests had the wrong assertion: https://github.com/astral-sh/uv/pull/8333
