### ISSUE TITLE
`uv add --index` does not accept special characters in the index name

### ISSUE THREAD

**Issue by vinibrsl** [astral-sh/uv#8315]
uv throws an error when adding a custom index with a name that includes characters like hyphens or underscores. While the equal sign (=) is understandably restricted as the separator, other characters should be allowed in the index name.

```
$ uv add --index my_custom_index=https://customindex.test/path/to/index my_package
error: invalid value 'my_custom_index=https://customindex.test/path/to/index' for '--index <INDEX>': relative URL without a base

For more information, try '--help'.
```

If I rename my_custom_index to mycustomindex, the command works as expected, e.g. `uv add --index mycustomindex=https://customindex.test/path/to/index my_package`.

## Version

```
$ uv --version
uv 0.4.24 (b9cd54913 2024-10-17)
```

Related: https://github.com/astral-sh/uv/pull/7746

**Comment by zanieb** [comment]
Yeah right now they must be alphanumeric https://github.com/astral-sh/uv/blob/2153c6ac0d692b9eccedbd7567087907667645fb/crates/uv-distribution-types/src/index.rs#L161

**Comment by charliermarsh** [comment]
Yeah that seems fine.
