### ISSUE TITLE
`uv tool run` could be more helpful when a package name and tool don't match

### ISSUE THREAD

**Issue by akx** [astral-sh/uv#8319]
macOS arm64, uv 0.4.24

```
$ uv tool run cyclonedx-bom
The executable `cyclonedx-bom` was not found.
warning: An executable named `cyclonedx-bom` is not provided by package `cyclonedx-bom`.
The following executables are provided by `cyclonedx-bom`:
- cyclonedx-py
```

Suggestions:

* This help text could tell me what to do to make this work (the magic spell `uv tool run --from cyclonedx-bom cyclonedx-py`).
  * `uv tool run cyclonedx-py --from cyclonedx-bom` already has this sort of warning in place: `warning: An executable named `cyclonedx-py` is not provided by package `cyclonedx-py` but is available via the dependency `cyclonedx-bom`. Consider using `uv tool run --from cyclonedx-bom cyclonedx-py` instead.`

* Alternatively, this could Do What I Mean and at least prompt me if I want to run the similarly-named single option, if not run it directly?

**Comment by charliermarsh** [comment]
I like adding the `uv tool run --from cyclonedx-bom cyclonedx-py` hint at the end.
