### ISSUE TITLE
`UV_FROZEN` env var please

### ISSUE THREAD

**Issue by samuelcolvin** [astral-sh/uv#8321]
uv is great, thank you!

It would be great if uv respected a `UV_FROZEN` env var with the same behaviour as `--frozen`.

This would match `UV_NO_SYNC`.

It would be particularly helpful in CI where:
1. I could set `UV_FROZEN` globally rather than adding it to every line
2. I could tell uv to run in "frozen" mode even when commands are withing makefiles or bash scripts, where it's not possible to set the `--frozen` cli arg

**Comment by charliermarsh** [comment]
This makes sense, thanks!
