### ISSUE TITLE
More strict dependency version rules that PEP508

### ISSUE THREAD

**Issue by Veritaris** [astral-sh/uv#8326]
command that was invoked: `uv lock`
platform: `macOS Sonoma 14.6.1`
current uv version: `uv 0.4.24 (b9cd54913 2024-10-17)`

Hi team! 
Found such more strict beahaviour rather that described in PEP508
If I define dependency as following in `pyproject.toml`:
```toml
dependencies = [
    "httpx==*",
]
```
than after `uv lock` I get the following error:
```
ValueError: invalid pyproject.toml config: `project.dependencies[0]`.
configuration error: `project.dependencies[0]` must be pep508
```

In [docs](https://docs.astral.sh/uv/concepts/dependencies/#pep-508) at PEP508 paragraph it's told that
> A star can be used for the last digit with equals, e.g. foo ==2.1.* will accept any release from the 2.1 series. Similarly, ~= matches where the last digit is equal or higher, e.g., foo ~=1.2 is equal to foo >=1.2,<2, and foo ~=1.2.3 is equal to foo >=1.2.3,<1.3.

But according to PEP508 [grammar](https://peps.python.org/pep-0508/#complete-grammar)
```
wsp           = ' ' | '\t'
version_cmp   = wsp* <'<=' | '<' | '!=' | '==' | '>=' | '>' | '~=' | '==='>
version       = wsp* <( letterOrDigit | '-' | '_' | '.' | '*' | '+' | '!' )+>
version_one   = version_cmp:op version:v wsp* -> (op, v)
version_many  = version_one:v1 (wsp* ',' version_one)*:v2 -> [v1] + v2
versionspec   = ('(' version_many:v ')' ->v) | version_many
```
it is also valid to define version via bare wildcard (`*`)

Was restricting of wildcard usage done intentionally? I understand that I can just remove version constraint, but `uv add httpx` adds line as in my example
```bash
uv add httpx
```
```toml
dependencies = [
    "httpx==0.27.2",
]
```

**Comment by notatallshaw** [comment]
Packaging also considers this invalid:

```
>>> import packaging.requirements

>>> packaging.requirements.Requirement("httpx==1")
<Requirement('httpx==1')>

>>> packaging.requirements.Requirement("httpx==1.*")
<Requirement('httpx==1.*')>

>>> packaging.requirements.Requirement("httpx==*")
Traceback (most recent call last):
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/_parser.py", line 124, in _parse_requirement_details
    marker = _parse_requirement_marker(
        tokenizer,
    ...<5 lines>...
        ),
    )
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/_parser.py", line 145, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        f"Expected end or semicolon (after {after})",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        span_start=span_start,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
    ...<3 lines>...
    )
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    httpx==*
         ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    packaging.requirements.Requirement("httpx==*")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/damian/opensource/support/uv/8326/.venv/lib/python3.13/site-packages/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    httpx==*
         ^
```

> it is also valid to define version via bare wildcard (*)

Are you *sure*? I would prefer this issue either raised on the [packaging repo](https://github.com/pypa/packaging/issues) or the [packaging discussion board ](https://discuss.python.org/c/packaging/14) before uv breaks compatibility with packaging here (and this breaking a uv generated `pyproject.toml` with anything build on top of packaging).

**Comment by charliermarsh** [comment]
I'm fairly certain that `==*` is not valid. From a glance, there are lots of things that are valid in the grammar that aren't actually valid PEP 508 requirements. For example, it looks like `==!+!+!` would be valid? But yes, I agree with @notatallshaw that this would be better discussed elsewhere since we're in conformance with all the rest of the ecosystem's behavior.

**Comment by Veritaris** [comment]
I've also looked into **packaging** tool repo and didn't find if they write anything about PEP508 in their [docs](https://packaging.pypa.io/en/stable/index.html):
> This library provides utilities that implement the interoperability specifications which have clearly one correct behaviour (eg: [PEP 440](https://peps.python.org/pep-0440/)) or benefit greatly from having a single shared implementation (eg: [PEP 425](https://peps.python.org/pep-0425/)).

So, I even wouldn't complain about this problem in uv but this project _does_ mention PEP508 rules

**Comment by konstin** [comment]
> I understand that I can just remove version constraint, but uv add httpx adds line as in my example

That should not happen and is a bug in uv. Can you provide a reproducer? I tried `uv init foo && cd foo && uv add httpx` and got:

```
[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.2",
]
```

---

The syntax defined by the PEP 508 grammar is more lenient than the semantically valid values. https://peps.python.org/pep-0440/#version-matching says:

> The specified version identifier must be in the standard format described in [Version scheme](https://peps.python.org/pep-0440/#version-scheme), but a trailing .* is permitted on public version identifiers as described below.

That is, there needs to be a dot before the star, which in turn needs a number before it to be valid,

I don't think we need to extend the spec here, allowing all versions is covered by a plain `httpx`.

**Comment by Veritaris** [comment]
Hi konstin!
Ohhh, sorry, I see a code block is lost in my original post – there is no problem with `uv add X`, just a little bit of work, required to define that I want to use every possible version  (to remove >= and version itself and leave bare requirement name). I'll edit orig post now

**Comment by charliermarsh** [comment]
> Yes, and it is, let's compile grammar from PEP508 and see parse result:

Right, I'm not claiming that the grammar forbids it. I'm claiming that it's not a valid PEP 508 specifier despite the grammar allowing it. As Konsti said, the grammar is more lenient than the semantically valid values, like my `==!+!+!+` example above. (I've also never seen this used or supported in any Python project.) It would be better to raise this elsewhere if you have a problem with the spec itself!

**Comment by Veritaris** [comment]
Well, I agree that PEP 508 is too wide and allows something that other devs are not using 

In such case can we please stop mentioning it in wiki (https://docs.astral.sh/uv/concepts/dependencies/#pep-508) and use PEP 440 instead?

**Comment by konstin** [comment]
PEP 508 refers to PEP 440 for version specifiers, since dependency specifiers include a version specifier as substring (and PEP 508 doesn't specify any version or version specifier semantics):

> Versions may be specified according to the [PEP 440](https://peps.python.org/pep-0440/) rules. (Note: URI is defined in [std-66](https://datatracker.ietf.org/doc/html/rfc3986.html)):

The canonical source has move to https://packaging.python.org/en/latest/specifications/dependency-specifiers/ though, and PEP 440 to https://packaging.python.org/en/latest/specifications/version-specifiers/, so we should refer to those specs instead: #8411
