### ISSUE TITLE
`uv remove` should remove `tool.uv.sources` entries if it's the only reference

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#8330]
e.g. as described in https://github.com/astral-sh/uv/issues/8328#issuecomment-2422598725

**Comment by charliermarsh** [comment]
Oh nice.

**Comment by j178** [comment]
`uv remove` actually removes entries from `tool.uv.sources`:
https://github.com/astral-sh/uv/blob/4b0a4dadb7a0a22f7d0fd3acab8286eaa29b96e0/crates/uv-workspace/src/pyproject_mut.rs#L455

The issue in https://github.com/astral-sh/uv/issues/8328#issuecomment-2422598725 is that the key in `tool.uv.sources` is ` example_python_library`, but the package name is normalized to `example-python-library`, so the source is not removed. I think we need to normalize keys in `tool.uv.sources` before comparison.
