### ISSUE TITLE
Executables not found in Docker after installing with uv

### ISSUE THREAD

**Issue by victor-ajayi** [astral-sh/uv#8342]
I'm trying to use uv in my Docker container but the image keeps failing, because of a `Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "fastapi": executable file not found in $PATH: unknown` error.

Here's my Dockerfile, it's basically the same as the example from the uv docs, this specific one is from tiangolo's fullstack FastAPI template.

```
FROM python:3.12

ENV PYTHONUNBUFFERED=1

WORKDIR /app/

COPY --from=ghcr.io/astral-sh/uv:0.4.15 /uv /bin/uv

ENV PATH="/app/.venv/bin:$PATH"

ENV UV_COMPILE_BYTECODE=1

ENV UV_LINK_MODE=copy

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

ENV PYTHONPATH=/app

COPY ./pyproject.toml ./uv.lock ./alembic.ini /app/

COPY ./app /app/app

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

CMD ["fastapi", "run", "--workers", "4", "app/main.py"]
```

The final command keeps failing, how do I get this to work?

**Comment by charliermarsh** [comment]
Does `CMD ["/app/.venv/bin/fastapi", "run", "--workers", "4", "app/main.py"]` work as expected?

**Comment by victor-ajayi** [comment]
No, it doesn't. ((

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/.venv/bin/fastapi": stat /app/.venv/bin/fastapi: no such file or directory: unknown`

**Comment by zanieb** [comment]
Sounds like the Python executable is missing. What does `/app/.venv/bin/python` point to?

**Comment by victor-ajayi** [comment]
Well on my local machine, it's pointing to a homebrew installed Python. But on Docker, I don't really know. I can't exec into the image to inspect, because it's not starting up at all. Shouldn't the `FROM python:3.12` handle that?

**Comment by zanieb** [comment]
But what does `ls -lah /app/.venv/bin` show?

**Comment by victor-ajayi** [comment]
`ls: cannot access '/app/.venv/bin': No such file or directory`

**Comment by zanieb** [comment]
Yeah the `python` is pointing to a file that does not exist, hence the error. My best guess is that, you don't have a `dockerignore` file that excludes your virtual environment and it's being copied into the container or something?

I'd recommend checking out https://github.com/astral-sh/uv-docker-example/

**Comment by victor-ajayi** [comment]
The uv-docker-example works! I'm not sure exactly what about the tiangolo example Dockerfile wasn't right, it seemed to me like the same thing. Thank you!

Also, my apologies for creating an issue that really has more to do with Docker than uv itself. I appreciate the help!

**Comment by zanieb** [comment]
No problem. That message when a Python executable can't be found is really confusing, but I'm not sure what we can do about it. Glad you got it working.

**Comment by gabo71096** [comment]
I have the same issue, not even the uv-docker-example works :( I really want to use uv in Docker because it really speeds build time, but has been a pain, I've tried many things and always hit the same spot of

`exec /app/.venv/bin/fastapi: no such file or directory`

or

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "fastapi": executable file not found in $PATH: unknown.`

Here's the Dockerfile, it's basically the same as the example:

```
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev
ADD . /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

# Then, use a final image without uv
FROM python:3.12-slim-bookworm
# It is important to use the image that matches the builder, as the path to the
# Python executable must be the same, e.g., using `python:3.11-slim-bookworm`
# will fail.

# Copy the application from the builder
COPY --from=builder --chown=app:app /app /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Run the FastAPI application by default
CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "80"]
```

If I run `CMD ls -lah /app` I can see that the `.venv` folder doesn't exist, so it makes sense I think that the command wasn't found, is it supposed to be like this, though?

I am doing this in Windows, and also tried WSL, none works :(, a little help please.

**Comment by petebachant** [comment]
Had a similar problem, and noticed that the Docker Compose config was mounting the local directory, which in turn mounted the local `.venv` directory, messing up the path to the Python executable in the `fastapi` script shebang line. The fix was to ensure that directory was not mapped, e.g., in `docker-compose.yml`:

```yaml
  backend:
    restart: "no"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
      - /app/.venv
    build:
      context: ./backend
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
```

**Comment by gabo71096** [comment]
> I have the same issue, not even the uv-docker-example works :( I really want to use uv in Docker because it really speeds build time, but has been a pain, I've tried many things and always hit the same spot of
> 
> `exec /app/.venv/bin/fastapi: no such file or directory`
> 
> or
> 
> `Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "fastapi": executable file not found in $PATH: unknown.`
> 
> Here's the Dockerfile, it's basically the same as the example:
> 
> ```
> FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder
> ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy
> WORKDIR /app
> RUN --mount=type=cache,target=/root/.cache/uv \
>     --mount=type=bind,source=uv.lock,target=uv.lock \
>     --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
>     uv sync --frozen --no-install-project --no-dev
> ADD . /app
> RUN --mount=type=cache,target=/root/.cache/uv \
>     uv sync --frozen --no-dev
> 
> # Then, use a final image without uv
> FROM python:3.12-slim-bookworm
> # It is important to use the image that matches the builder, as the path to the
> # Python executable must be the same, e.g., using `python:3.11-slim-bookworm`
> # will fail.
> 
> # Copy the application from the builder
> COPY --from=builder --chown=app:app /app /app
> 
> # Place executables in the environment at the front of the path
> ENV PATH="/app/.venv/bin:$PATH"
> 
> # Run the FastAPI application by default
> CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "80"]
> ```
> 
> If I run `CMD ls -lah /app` I can see that the `.venv` folder doesn't exist, so it makes sense I think that the command wasn't found, is it supposed to be like this, though?
> 
> I am doing this in Windows, and also tried WSL, none works :(, a little help please.

I stopped trying since this comment, and today I got it working.
Stupid error as always.
I was bind mounting in my docker-compose file.

End of story.

Thanks guys.
