### ISSUE TITLE
uv does not respect position of comments in `pyproject.toml`

### ISSUE THREAD

**Issue by notatallshaw** [astral-sh/uv#8343]
uv 0.4.24

Maybe this is already reported but I couldn't find it.

**Steps to reproduce:**

1, `uv init temp`
2. `cd temp`
3. `uv add requests`
4. `uv add whenever~=0.6.9`
5. Edit `project.dependencies` in `pyproject.toml` from:
```toml
dependencies = [
    "requests>=2.32.3",
    "whenever~=0.6.9",
]
```

To:
```toml
dependencies = [
    "requests>=2.32.3", # Should not expect to be updated frequently
    "whenever~=0.6.9", # Pinned to 0.6 due to API not yet being stable
]
```

6. `uv add uv zope`
7. Check `project.dependencies` in `pyproject.toml`:

**Actual output:**

```toml
dependencies = [
    "requests>=2.32.3",
    "uv>=0.4.24",
    # Should not expect to be updated frequently
    "whenever~=0.6.9",
    "zope>=5.11",
     # Pinned to 0.6 due to API not yet being stable
]
```

**Expected output:**

```toml
dependencies = [
    "requests>=2.32.3", # Should not expect to be updated frequently
    "uv>=0.4.24",
    "whenever~=0.6.9", # Pinned to 0.6 due to API not yet being stable
    "zope>=5.11", 
]
```

**Context:**

I often leave comments in my `pyproject.toml` to explain why a particular dependency is pinned or given an upper bound.

I appreciate that comments are a hard problem when reading and writing toml, and there will always be edge cases where the user needs to manually update them (e.g. a requirement is removed), but I don't think this example is an edge case.

**Comment by charliermarsh** [comment]
I suppose that's a legitimate bug though end-of-line comments are my mortal enemy and I don't know if I can work up the courage to fix it myself :)

**Comment by flyaroundme** [comment]
Tricky one. The fun thing is that the "current dependency line comment" in this case is becoming a next dependency `prefix`, so in case it is the comment on the last line it is becoming part of `trailing`.
I am digging into it so feel free to assign on me, but can send the fix more to the end of the weekend, so I'm totally fine if somebody solves it beforehand
