### ISSUE TITLE
Add a way to add a file to a build

### ISSUE THREAD

**Issue by ebits21** [astral-sh/uv#8346]
Right now I've been able to do this by adding an include in a MANIFEST.in file.

I'm wondering if there could be a setting in pyproject.toml or an uv command to do this.

Sorry if I missed something if this is already possible.

**Comment by zanieb** [comment]
Unfortunately this is build-backend specific, i.e. that file is [setuptools-specific](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html). As a a build frontend, we can't easily provide a way to do this across various build backends. When we have our own build backend (which is in progress), we'll be able to provide this if you're using our backend.

**Comment by ebits21** [comment]
Ah I understand. Thanks!
