### ISSUE TITLE
uv sync: project dev dependencies does not get installed

### ISSUE THREAD

**Issue by bugzpodder** [astral-sh/uv#8353]
prior to uv 0.4.9, if i do `uv sync` in workspace, both dev-dependencies in worspace and project gets installed.  after uv 0.4.10+ `uv sync` in workspace removes project dev-dependencies

root workspace pyproject.yaml
```
[project]
name = "workspace"
version = "0.1.0"
dependencies = ["project"]

[tool.uv.sources]
project = { workspace = true }

[tool.uv.workspace]
members = ["project"]

[tool.uv]
package=false
dev-dependencies = [
    "coverage==7.5.3",
]
```

project pyproject.yaml
```
[project]
name = "project"
version = "0.1.0"
description = ""
dependencies = [
    ...
]

[tool.uv]
dev-dependencies = [
    "basedpyright==1.17.0"
]

[tools.uv]
package=false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["workspace"]
```

**Comment by FishAlchemist** [comment]
I believe this is related to modification https://github.com/astral-sh/uv/pull/7318. 
The PR and its related issue should provide you with more details.

**Please note that I am not a member of the UV team, so I can only provide PR that I believe are relevant for your reference. If you have any other ideas, I am not in a position to make decisions.**

**Comment by zanieb** [comment]
That sounds correct, thanks @FishAlchemist.

cc @charliermarsh

**Comment by bugzpodder** [comment]
closing as a dupe of #7541.  thanks for the quick feedback guys
