### ISSUE TITLE
[Feature request] pull configuration details on a global level from some config file

### ISSUE THREAD

**Issue by GalOzRlz** [astral-sh/uv#8378]
Mainly what interests me is a global extra-url or global main url for uv to use - instead of setting these from environment variables. 
One might imagine other configuration parameters being set on a global level via some config file (not unlike pip/poetry).

**Comment by charliermarsh** [comment]
We support this. Look for the "user-level configuration" information here: https://docs.astral.sh/uv/configuration/files/
