### ISSUE TITLE
Ability to specify package data to be included in distributed package

### ISSUE THREAD

**Issue by butterlyn** [astral-sh/uv#8383]
Ability to specify package data to be included in the distribute package built with `uv`.

Equivalent within setuptools: https://setuptools.pypa.io/en/latest/userguide/datafiles.html#package-data
Equivalent within Poetry: https://python-poetry.org/docs/pyproject/#include-and-exclude

**Comment by Ravencentric** [comment]
This is controlled by your build-backend. `uv` currently defaults to hatchling and if that's what you're using, you can configure it via https://hatch.pypa.io/latest/config/build/#file-selection

**Comment by zanieb** [comment]
Similar https://github.com/astral-sh/uv/issues/8346
