### ISSUE TITLE
`init_app_build_backend_maturin` test timed out on macOS

### ISSUE THREAD

**Issue by zanieb** [astral-sh/uv#8404]
```
--- STDERR:              uv::it init::init_app_build_backend_maturin ---

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Unfiltered output ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
----- stdout -----

----- stderr -----
Initialized project `foo`

────────────────────────────────────────────────────────────────────────────────


     TIMEOUT [  90.027s] uv::it init::init_lib_build_backend_maturin
```

**Comment by konstin** [comment]
Can you see where it got stuck?

**Comment by zanieb** [comment]
Unfortunately no, that's all I got.

**Comment by zanieb** [comment]
Here's another https://github.com/astral-sh/uv/actions/runs/11446571344/job/31855447015 also macOS

**Comment by konstin** [comment]
We can speed them up by switching to cffi (no rust deps), pyo3 is quite slow to compile in an uncached integration test.

**Comment by zanieb** [comment]
I'm not sure how to do that, but that makes sense to me.

**Comment by davidhewitt** [comment]
Was part of the problem that the tests were building release binaries? I wonder if setting `MATURIN_PEP517_ARGS=--profile=dev` might have helped if so.

**Comment by konstin** [comment]
At least in the maturin test suite itself, even building with dev is slow, and the cache artifacts would be too large to store (https://github.com/PyO3/maturin/issues/2272)
