### ISSUE TITLE
please add  feature of  `uv search `  to search  pip  source package 

### ISSUE THREAD

**Issue by Super1Windcloud** [astral-sh/uv#8405]
#  please add  feature of  `uv search `  to search  pip  source package

**Comment by ivan-toriya-precis** [comment]
That's probably not gonna happen, as the PyPi API for that was deprecated in 2020. You can read more about that [here](https://discuss.python.org/t/pip-search-is-still-broken/18680) and [here](https://www.theregister.com/2021/05/25/pypi_search_error/).

**Comment by Super1Windcloud** [comment]
yes , and  it's  already exits    pip_search

**Comment by dcunited001** [comment]
> yes , and it's already exits pip_search

that's news to me, but i live on tom hanks island ... so yeh

https://x.com/aionfork/status/2009278046319017996
