### ISSUE TITLE
uv build failing to build wheel correctly when project.name != package folder name

### ISSUE THREAD

**Issue by david-waterworth** [astral-sh/uv#8406]
I have a project with a name (i.e. foo) that's not the same as the source folder / package name (`src/bar`). 

```
[project]
name = "foo"
version = "1.2.3"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/bar"]

[tool.hatch.build.targets.sdist]
packages = ["src/bar"]
```

If I run `uvx hatch build` I get a wheel and sdist that contain the files I expect - i.e. the wheel `{project.name}-{version}-py3-none-any.whl`  contains

```
{project.name}-{version}.distinfo/
    METADATA
    RECORD
    WHEEL
bar/
     {contents of src/bar}
```

But if I run `uv build` the sdist is correct, but the wheel only contains the project metadata - i.e. the contents of the archive `{project.name}-{version}-py3-none-any.whl` is

```
{project.name}-{version}.distinfo/
    METADATA
    RECORD
    WHEEL
```
i.e. `bar/` is missing

It works if I set the project name the same as the packages folder. I would expect that `uv build` and `uvx hatch build` would behave exactly the same?

I'm using uv v0.4.24

**Comment by bluss** [comment]
Could you create the sdist and check if it has the contents you expect. I think it's missing files because of your sdist config.

**Comment by david-waterworth** [comment]
The sdist  works fine, the wheel is built correctly when I use hatch but not uv with the same pyproject file. Both have the same configSent from my iPhoneOn 21 Oct 2024, at 6:37 pm, bluss ***@***.***> wrote:﻿
Could you create the sdist and check if it has the contents you expect. I think it's missing files because of your sdist config.

**Comment by konstin** [comment]
Could this be another case of https://github.com/astral-sh/uv/pull/8220?

**Comment by charliermarsh** [comment]
I assume `uv build --wheel` and `uv build --sdist` produce the right artifacts? (That's not the same as running `uv build`, which builds the wheel from the sdist.)

**Comment by david-waterworth** [comment]
@charliermarsh yes it does

**Comment by charliermarsh** [comment]
Does `python -m build` work on your project, or does it produce similar builds? (https://github.com/pypa/build)

**Comment by david-waterworth** [comment]
@charliermarsh no that does the same thing as `uv build` and only includes the metadata in the wheel, but the source is included in the sdist

**Comment by charliermarsh** [comment]
@david-waterworth -- You may have a real issue with your project then. `pypa/build` is effectively the reference implementation for the spec. My guess is that `uvx hatch build` builds the wheel and the sdist from source, rather than building the wheel from the sdist as is the default in `pypa/build` and `uv`. You'll either need to figure out why your sdist isn't working as expected or use `uv build --sdist --wheel` (but, again, your sdist may have a real problem?).

**Comment by david-waterworth** [comment]
[foo.zip](https://github.com/user-attachments/files/17468438/foo.zip)

I created a minimal example - maybe there is something wrong with the sdist, I've not actually tried to install it. Also https://hatch.pypa.io/latest/config/build/#packages doesn't appear to explicitly cover the case where project.name doesn't equal package name - maybe it's not supported, the accepted answer to https://stackoverflow.com/questions/77070305/how-to-distribute-a-python-package-where-import-name-is-different-than-project-n was to switch to setuptools?

**Comment by david-waterworth** [comment]
Adding

```
[tool.hatch.build.targets.wheel]
packages = ["src/bar"]
include = [
  "src/bar/**",
]
```

Seems to work

**Comment by charliermarsh** [comment]
I'm going to close for now as I don't _think_ it's uv-specific.
