### ISSUE TITLE
Outdated pip reference in "Strictness and spec enforcement" docs

### ISSUE THREAD

**Issue by edmorley** [astral-sh/uv#8412]
On https://docs.astral.sh/uv/pip/compatibility/#strictness-and-spec-enforcement it says:

> uv tends to be stricter than pip, and will often reject packages that pip would install. For example, uv omits packages with invalid version specifiers in its metadata, which pip similarly plans to exclude in a [future release](https://github.com/pypa/pip/issues/12063).

As of pip 24.1, pip now rejects those versions too - so it's no longer a "future release".

I was going to open a PR to remove that last sentence, however, it seems that it would be useful if this section of the docs still had an example - so I thought you might want to add another in its place (and I don't know of any)?

**Comment by charliermarsh** [comment]
I found something to replace this with.
