### ISSUE TITLE
Adding git tags to cache keys causes pyproject.toml parse error

### ISSUE THREAD

**Issue by kwaegel** [astral-sh/uv#8421]
When I try to use the code suggested in the [uv caching of dynamic metadata](https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata) help doc to include git tags, I get a parse error. I suspect this is just a typo in the docs.

Minimal pyproject.toml file:
```
[project]
name = "uv-cache-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.uv]
cache-keys = [{ git = { commit = true, tag = true } }]
```

Error message:
```
$ uv sync
warning: Failed to parse `pyproject.toml` during settings discovery:
  TOML parse error at line 10, column 14
     |
  10 | cache-keys = [{ git = { commit = true, tag = true } }]
     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  data did not match any variant of untagged enum CacheKey
```

If I change this to `tags = true` (note the plural), it doesn't report an error, so this might just be a typo in the docs.

uv 0.4.25

**Comment by charliermarsh** [comment]
Yeah that's just a typo. Thanks.
