### ISSUE TITLE
Recommended way to install tool for all users on system

### ISSUE THREAD

**Issue by lambda674** [astral-sh/uv#8431]
I have CLI package `foo` that is published to PyPi. At work, we have a few servers that many users use for one off tasks. I want to distribute `foo` on these servers.

The [tools section of the docs](https://docs.astral.sh/uv/guides/tools/) seems to be uv's answer for this, but I'm not sure how to install a tool system wide. For my use case, all it would take is allowing `uv tool install` to install to `/usr/local/bin`.

A workaround for now is to manually manage a script in `/usr/local/bin` called `foo`:
```
#!/usr/bin/env bash

uv pipx foo "$@"
```

However, the CLI will be run many times and upgraded only once a day. The docs indicate that `uv pipx` isn't good for a tool run many times.

Any suggestions?

**Comment by zanieb** [comment]
So you can do this with
```
UV_TOOL_BIN_DIR=/usr/local/bin uv tool install foo
```

For most purposes `uvx foo` is probably fine too. The overhead is maybe 10ms

```
❯ time black -q
...
black -q  0.09s user 0.02s system 91% cpu 0.119 total
❯ time uvx black -q
...
uvx black -q  0.09s user 0.03s system 92% cpu 0.127 total
```

**Comment by zanieb** [comment]
You can set `UV_TOOL_DIR` to change the storage directory too.

**Comment by gaby** [comment]
@lambda674 Look at my comment here https://github.com/astral-sh/uv/issues/8435#issuecomment-2428240406 using those 2 variables seems to work. I was able to test this in a python container.
