### ISSUE TITLE
Error message when running uv venv and having a .python-version file

### ISSUE THREAD

**Issue by TheUncharted** [astral-sh/uv#8442]
In my project i have a .python-version file 
I want to create a virtual env with the commands 

```bash
uv venv

or

uv venv myvenv
```

But I got this error message "No interpreter found for executable name `myproject` in managed installations or system path"
Is there a way to force the creation of the virtual env ?

**Comment by zanieb** [comment]
What's in your `.python-version` file? Sounds like it's `"myproject"` which tells us to look for an executable with that name.

**Comment by zanieb** [comment]
Maybe you want `uv venv --no-config` to avoid reading the file?

**Comment by TheUncharted** [comment]
yes it works , thanks !
