### ISSUE TITLE
Option to disable linehaul

### ISSUE THREAD

**Issue by eaubin** [astral-sh/uv#8474]
https://github.com/astral-sh/uv/pull/2493 added linehaul metadata to the uv user-agent string. For example,

* Windows GHA: uv/0.1.21 {"installer":{"name":"uv","version":"0.1.21"},"python":"3.12.2","implementation":{"name":"CPython","version":"3.12.2"},"distro":null,"system":{"name":"Windows","release":"2022Server"},"cpu":"AMD64","openssl_version":null,"setuptools_version":null,"rustc_version":null,"ci":true}

I'd like to use uv at work, but this is causing my network admins some grief. Could an option to disable the linehaul metadata be added?

**Comment by zanieb** [comment]
Do you know if pip includes an opt-out for this? (just wondering)

**Comment by eaubin** [comment]
I believe that's controlled through [$PIP_USER_AGENT_USER_DATA](https://pip.pypa.io/en/stable/user_guide/#using-a-proxy-server)

**Comment by charliermarsh** [comment]
I think that's additive; it doesn't look like it disables linehaul.

https://github.com/pypa/pip/blob/6958e28f366f00373343efcd5a7e776a810cb133/src/pip/_internal/network/session.py#L203

**Comment by samypr100** [comment]
iirc pip doesn't allow opt-out either

**Comment by eaubin** [comment]
My network admins loosened their rules, so its not a requirement for my org anymore. I still think its a good idea to allow opt out (or better yet opt in), but since it's very low priority I'll close the issue.
