### ISSUE TITLE
Improving netrc documentation

### ISSUE THREAD

**Issue by BrendanJM** [astral-sh/uv#8482]
Is it possible to have a bit of clarification what it means when the docs say uv supports netrc? I understand there are a few ways projects usually support this:
- Look for a file at `~/.netrc`
- Look for a file reference in the env var `NETRC`

Even just confirming uv does either, both, or none could be helpful. Thanks!

**Comment by charliermarsh** [comment]
We'll document this, but uv will look for the `NETRC` env var and then check `~/.netrc` if it's not defined.
