### ISSUE TITLE
uv pip not use pip.conf ,

### ISSUE THREAD

**Issue by linpan** [astral-sh/uv#8486]
i custom pip.conf (custom pypi proxy ) , uv pip not use it,

**Comment by konstin** [comment]
See https://docs.astral.sh/uv/pip/compatibility/#configuration-files-and-environment-variables and https://github.com/astral-sh/uv/issues/1404 and

**Comment by gaby** [comment]
@konstin Problem is the configuration options in uv.toml are super different than pip.conf. It's also missing critical features that are being pushed to ENV variables.

Having to append ENV variables everytime we use uv is very non intuitive

**Comment by konstin** [comment]
@gaby please use #1404 for discussing pip.conf
