### ISSUE TITLE
Wrong uv version listed under astral.sh -> tools

### ISSUE THREAD

**Issue by roteiro** [astral-sh/uv#8489]
Astral.sh shows v0.4.16 under tools while v0.4.25 is the most recent at the time of issue creation
![image](https://github.com/user-attachments/assets/b398790c-134d-4245-8acd-af3fab806104)
Thank you for a great tool!

€: Slightly out of scope, the same is true for ruff v0.6.7 vs v0.7.0

**Comment by charliermarsh** [comment]
Thanks, just pushed a fix.
