### ISSUE TITLE
Also add `.gitignore` if I am in an existing git repository

### ISSUE THREAD

**Issue by kamulos** [astral-sh/uv#8494]
My `uv` versuin is `0.4.25`.

I just initialized a folder in my existing git repo with a new `uv` project. In this case it seems to skip creating the `.gitignore` file in that folder even though the folder was completely empty when I executed `uv init`. My preference would be to create the default `.gitignore` in this case, but maybe some other thoughts went into it when it was implemented. What do you think?

**Comment by charliermarsh** [comment]
I think this was done intentionally to match Cargo.

**Comment by charliermarsh** [comment]
I'm going to close as "working as intended" though I know it's sometimes desired.
