### ISSUE TITLE
How to config Jfrog api key in pyproject.toml

### ISSUE THREAD

**Issue by yuhao-postnl** [astral-sh/uv#8518]
Hey!!
I'm migrating from `poetry` to `uv` and wondering how to configure API keys for JFrog in the `pyproject.toml` file. Here's an example of my current configuration:
```
[project]
name = "test-dev"
version = "0.0.1"
description = "About test-dev"
authors = []
requires-python = ">=3.9,<4.0"
dependencies = [
    "sageflow>=1.7.0",
    "aiplatform>=0.4.0",
]

[tool.uv.sources]
sageflow = { index = "jfrog" }
aiplatform = { index = "jfrog" }

[[tool.uv.index]]
name = "jfrog"
url = "https://<user_name>:<key>@lpe.jfrog.io/artifactory/api/pypi/<virtual-repo>/simple"


```
For poetry, we have such command to config credentials:
```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring 
poetry config http-basic.jfrog <email-address> <JFROG_APIKEY>
```
Is there an equivalent way like `uv config http-basic.jforg`

I checked the doc [here](https://docs.astral.sh/uv/guides/integration/alternative-indexes/#other-indexes), seems no further explanation on how to config jfrog.

**Comment by zanieb** [comment]
You can set the `UV_INDEX_JFROG_USERNAME` and `UV_INDEX_JFROG_PASSWORD` environment variables.

**Comment by zanieb** [comment]
(We don't recommend writing credentials to your `pyproject.toml`)

**Comment by yuhao-postnl** [comment]
> You can set the `UV_INDEX_JFROG_USERNAME` and `UV_INDEX_JFROG_PASSWORD` environment variables.

Thank you for the quick reply! Does it mean we put these two env vars in zsh file and source it? And the run uv sync

**Comment by yuhao-postnl** [comment]
Seems I miss export in zsh file, close this issue now. Thanks again!
```
export UV_INDEX_JFROG_USERNAME=
export UV_INDEX_JFROG_PASSWORD
```
