### ISSUE TITLE
the message  "or pass `--system` to install into a non-virtual environment" needs greater detail or is wrong. or something

### ISSUE THREAD

**Issue by twobob** [astral-sh/uv#8522]
d:\dev\genmoai-smol>`uv pip install somethingoutsideanenv`
error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment

Give the above error output one would most likely do the following:

d:\dev\genmoai-smol>`uv --system pip install somethingoutsideanenv`
error: unexpected argument '--system' found

Usage: `uv [OPTIONS] <COMMAND>`

For more information, try '--help'.

it says `UV [OPTIONS] <COMMAND>`

and yet

**`uv pip install sageattention --system`**  is the command which is not at all  `UV [OPTIONS] <COMMAND>`

Can someone explain why this is the case

thank you Great Sages
<img src="https://github.com/user-attachments/assets/1bcde921-01c5-4ca0-85c2-55921414d79a" alt="greatSage" width="300" height="300">

**Comment by twobob** [comment]
Thanks Charlie. perhaps I should have been more specific

`error: No virtual environment found; run uv venv to create an environment, or pass --system **AFTER ALL THE COMMANDS** to install into a non-virtual environment
`

would make more sense as a message.  Since it is an exception as you have noted.

**Comment by zanieb** [comment]
Generally, I wouldn't recommend passing any arguments immediately after `uv ...` when using subcommands. It's more normal to just provide them all at the end.

**Comment by twobob** [comment]
> Generally, I wouldn't recommend passing any arguments immediately after `uv ...` when using subcommands. It's more normal to just provide them all at the end.

Fair,
