### ISSUE TITLE
Cannot 'add' module depending on tkinter

### ISSUE THREAD

**Issue by Barrowcroft** [astral-sh/uv#8560]
Using UV and Python 3.12 I can create a script that imports tkinter without any problems.

But when I try to add the module 'tkinterdnd' i get the message:

  × No solution found when resolving dependencies:
  ╰─▶ Because tkinter was not found in the package registry and tkinterdnd==0.0.0 depends on tkinter, we can conclude
      that tkinterdnd==0.0.0 cannot be used.
      And because only tkinterdnd==0.0.0 is available and your project depends on tkinterdnd, we can conclude that
      your project's requirements are unsatisfiable.
  help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip
        locking and syncing.

How can I solve this?
thanks

**Comment by zanieb** [comment]
I think `tkinter` and `tkinter.dnd` are both standard library modules and don't need to be "added" to be used

- https://docs.python.org/3/library/tkinter.html
- https://docs.python.org/3/library/tkinter.dnd.html

**Comment by Barrowcroft** [comment]
Thank you for your reply, but that's my point. Why does UV not install 'tkinterdnd' which depends on the, built-in, 'tkinter?'

**Comment by zanieb** [comment]
[`tkinterdnd`](https://pypi.org/project/tkinterDnD/) does not look like a real project, it's only version is `0.0.0`. Are you looking for the `tkinter.dnd` module instead? Or perhaps [`tkinterdnd2`](https://pypi.org/project/tkinterdnd2/)?

**Comment by Barrowcroft** [comment]
thanks, but here is a real 'tkinterdnd' on pypi.
https://pypi.org/project/tkinterDnD/

**Comment by Barrowcroft** [comment]
I wonder if the problem is that UV doesn't like the 0.0.0 version number.

**Comment by FishAlchemist** [comment]
Even pip can't install tkinterDnD(https://pypi.org/project/tkinterDnD/)!
![image](https://github.com/user-attachments/assets/b122af53-094e-4cf6-8cce-4a00d266b400)

**Comment by zanieb** [comment]
Yeah that's not a valid package. It has nothing to do with the version number. As described, it erroneously requires `tkinter` which is not an installable package, it is a standard library module.

**Comment by Barrowcroft** [comment]
Very odd.

**Comment by zanieb** [comment]
Yeah nothing to do with uv though, just someone a while back uploaded a bad package.
