### ISSUE TITLE
Trusted publishing support for GitHub Actions + TestPyPI via `uv publish`

### ISSUE THREAD

**Issue by nathanjmcdougall** [astral-sh/uv#8584]
Currently, `uv publish` supports trusted publishing support via GitHub Actions with PyPI, but not with TestPyPI. For testing purposes, it would be great if support could be extended to TestPyPI.

**Comment by konstin** [comment]
The trusted publishing support exists for both TestPyPI and PyPI, is there anything specific not working?

**Comment by nathanjmcdougall** [comment]
OK, that's great to hear, I guess in that case I just haven't worked out how to set up trusted publishing properly yet. I'm experimenting here:
https://github.com/nathanjmcdougall/postmodern-python-ci/blob/main/.github/workflows/release.yml

[I get errors](https://github.com/nathanjmcdougall/postmodern-python-ci/actions/runs/11550297410/job/32144983240) about missing credentials:

> error: Failed to publish `dist/postmodern_ci-0.1.0-py3-none-any.whl` to https://upload.test.pypi.org/legacy/
>  Caused by: Failed to send POST request
>  Caused by: Missing credentials for https://upload.test.pypi.org/legacy/

My TestPyPI config is here:
![image](https://github.com/user-attachments/assets/74456a34-2c6d-42ab-bf06-36489d89f89e)

I don't actually know where the TestPyPI upload endpoint is, I've tried manually using API tokens but I get the following:

- https://test.upload.pypi.org/legacy/  -> `dns error: No such host is known. (os error 11001)`
- https://upload.test.pypi.org/legacy/  -> `dns error: No such host is known. (os error 11001)`
- https://upload.pypi.org/legacy/ ->`Permission denied (status code 403 Forbidden)`

Probably I need to do more work to diagnose my issue, so I'm closing for now. Any support appreciated but not expected.

**Comment by konstin** [comment]
The publish endpoint for TestPyPI is https://test.pypi.org/legacy/

**Comment by konstin** [comment]
To help with debugging trusted publishing, I recommend `uv publish --trusted-publishing always`, this will show errors earlier when there is a problem.

**Comment by nathanjmcdougall** [comment]
Great, great to know the endpoint and the suggestion to `--trusted-publishing` was also helpful. The message I got was:

> error: Failed to obtain token for trusted publishing
> Caused by: environment variable not found

This was a tad cryptic without knowing the ins-and-outs of trusted publishing, but the issue was that I had not set `id-token` write permission, [as described here](https://docs.pypi.org/trusted-publishers/using-a-publisher/). Once this was set, everything worked.

Thank you so much for your help.
