### ISSUE TITLE
Dependency source path and uv venv

### ISSUE THREAD

**Issue by CharlesPerrotMinotHCHB** [astral-sh/uv#8586]
Hi,

I think there's an issue when switching from a local source (`path=`) to an index one (`index=`).
Say I have a dependency in an index `dependency = { index = "myindex" }`

In the virtual environment, I get:
```
$ uv pip show dependency
Name: dependency
Version: 2.5.40
(...)

$ uv pip list -e --format json
[]
```

If I put as an editable local, it works all good
`dependency = { index = "../../libraries/dependency" }`

In the virtual environment, I get:
```
$ uv pip show dependency
Name: dependency
Version: 2.5.40
Editable project location: /Users/cperrotminot/Workspace/libraries/dependency
(...)

$ uv pip list -e --format json
[{"name":"dependency","version":"2.5.40","editable_project_location":"/Users/cperrotminot/Workspace/libraries/dependency"}]
```

But if I change it back to an index, the info stays the same (aka shown as local)
```
$ uv pip show dependency
Name: dependency
Version: 2.5.40
Editable project location: /Users/cperrotminot/Workspace/libraries/dependency
(...)

$ uv pip list -e --format json
[{"name":"dependency","version":"2.5.40","editable_project_location":"/Users/cperrotminot/Workspace/libraries/dependency"}]
```

The only way to fix the issue that I found is to rebuild the virtual environment (`uv venv`, without `--allow-existing`).
Thanks!

**Comment by charliermarsh** [comment]
Are you running an install command between those? uv pip list just tells you what’s currently installed.

**Comment by CharlesPerrotMinotHCHB** [comment]
So! Hum.
- I'm running `uv lock` and `uv sync`
- For some reason I cannot reproduce at all. I was sourcing the environments, got the issue even doing `uv run`, but now it works all the time, with or without `uv venv`.
-so... sorry :(
