### ISSUE TITLE
Add `--all-group` option to `uv sync`

### ISSUE THREAD

**Issue by shoucandanghehe** [astral-sh/uv#8594]
When installing multiple dependency groups you need to specify `--group` multiple times, which can be annoying if you want to install many dependency groups at the same time

Also `--all-group` should be able to be used in conjunction with `--no-group` in case you don't want to actually install all the dependencies.

**Comment by zanieb** [comment]
Sure, we could add `--all-groups` throughout to match `--all-extras`

**Comment by frfahim** [comment]
The `--all-group` command would be very helpful to install all groups with a single command.
Also it would be great to support multiple groups together within one `--group` argument like this `uv sync --group "lint,docs"` instead of `uv sync --group lint --group docs`

**Comment by drmikehenry** [comment]
Though it's not completely portable, you can use brace expansion in many Unix shells (Bash, Zsh, Ksh, Fish, etc.) to get the desired behavior because the `--group groupname` syntax may use an `=` as in `--group=groupname`.  To show this using the `echo` command:

```
echo uv sync --group={lint,docs}
```

with output:

```
uv sync --group=lint --group=docs
```

**Comment by bluss** [comment]
Groups can also include each other, so you can add a group "all" that includes all other groups, if you want to.

**Comment by frfahim** [comment]
How can I combine groups? I tried these two ways but not worked for me
In dependency groups,
`all = ["package_name[lint]", "package_name[docs]"]`
another one 
`all = ["package_name[lint,docs]"]`
Then, I tried to run this
`uv sync --group all`

**Comment by bluss** [comment]
The PEP has the syntax for group inclusion here https://peps.python.org/pep-0735/#dependency-group-include

**Comment by amoralesc** [comment]
Just referencing here that I temporally solved this issue by defining [default groups](https://docs.astral.sh/uv/concepts/dependencies/#default-groups):

```toml
# pyproject.toml
[tool.uv]
default-groups = ["lint", "docs"]
```

This makes the `uv sync` command sync all groups contained there. This obviously has the disadvantage that now I need to specify `--no-group` or `--only-group` when I don't want any of those groups.

**Comment by amoralesc** [comment]
@zanieb In line with the [above comment](https://github.com/astral-sh/uv/issues/8594#issuecomment-2442915709), I also can't find a way to **only** install the project-level dependencies (those under `[project].dependencies`), regardless of what the default groups property defines.

For example, Poetry achieves this behavior by using the `--only main` flag (although badly documented). This seems equivalent to the `--only-group` flag, with the caveat that the project-level dependencies don't seem to belong to a group.

My workaround for achieving both behaviors (sync with default groups and sync only main) is creating a `main` group.

**Comment by zanieb** [comment]
@amoralesc it seems like we might want a `--no-default-groups` flag, which I was sort of hoping we could avoid (just because we have so many flags)
