### ISSUE TITLE
uv lock/add selects package versions not available for current platform

### ISSUE THREAD

**Issue by per11235813** [astral-sh/uv#8603]
First, I would like to thank you for `uv`, it is just awesome, but I do have a problem

The pyqt5 package has different versions available for linux and windows, Linux:
```
$ pip index versions pyqt5-qt5
pyqt5-qt5 (5.15.15)
Available versions: 5.15.15, 5.15.14, 5.15.2
```
and Windows:
```
(Notes) > pip index versions pyqt5-qt5
pyqt5-qt5 (5.15.2)
Available versions: 5.15.2
```

On windows `uv lock` wants to use 5.15.15, which is not available so I get a lock file that does not work on Windows. `uv add` fails with similar logic:
```
> uv add pyqt5-qt5            
Resolved 2 packages in 762ms
error: distribution pyqt5-qt5==5.15.15 @ registry+https://pypi.org/simple can't be installed because it doesn't have a source distribution or wheel for the current platform
```

Are there any way to specify a platform requirement for package selection for `uv lock` and `uv add`?

For now I use `uv pip compile` and `uv pip sync`.

**Comment by FishAlchemist** [comment]
If you don't mind relying on different versions across platforms, you can actually use PEP 508's Environment Markers.
https://docs.astral.sh/uv/concepts/dependencies/#dependency-specifiers-pep-508

You can modify the pyproject.toml file like this, or include Environment Markers when using uv add.
```toml
dependencies = [
    "pyqt5-qt5==5.15.15 ; platform_system != 'Windows'",
    "pyqt5-qt5==5.15.2 ; platform_system == 'Windows'",
]
```
Or do you think UV should use a version that is compatible across all platforms(Windows、Linux、Macos)?

**Comment by bluss** [comment]
One special case, that 'pyqt5-qt5' has no windows wheels and no sdist, so it can't be built from source either. A windows-only resolution of the project generates a lockfile with no artifacts at all (no sdist and no wheels)


Forcing only locking for windows looks like this configuration pyproject.toml - but as stated above does not help.

```
[tool.uv]
environments = ["platform_system == 'Windows'"]
```

**Comment by charliermarsh** [comment]
This is tracked in https://github.com/astral-sh/uv/issues/5182. I wrote a long explanation of it here: https://github.com/astral-sh/uv/issues/8536#issuecomment-2436123242. But in this case, the above solutions are correct: you can either tell the resolver to only solve for Windows, or you can tell the resolver to use different versions on Windows or non-Windows.

**Comment by charliermarsh** [comment]
(Happy to answer follow-ups but the core issue is tracked elsewhere.)

**Comment by bluss** [comment]
I was probably going out on a confusing tangent: but my comment does not have a solution. Instead with `environments` the experience for the user is the same. It ends up in a scenario where uv could throw a warning or error - the package has no installable artifacts in the lockfile, so uv knows that resolution is 'bad'.  (Do you see what I mean - no sdist and no wheels at all in the lockfile for that package?)
