### ISSUE TITLE
Skip `get_requires_for_build_wheel` for build backends that always return `[]`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#861]
This is a probably-unsafe optimization we could perform, but e.g., poetry-core always returns `[]` (https://github.com/python-poetry/poetry-core/blob/21b00338544f52df7c3ba320f5f242a2fc815b65/src/poetry/core/masonry/api.py#L20C1-L20C1). So if we're using a version of poetry-core that we _know_ always returns `[]`, we could skip that step entirely.

**Comment by sbidoul** [comment]
> setuptools doesn't need it (I think)

Actually setuptools does need it. By default it returns `wheel`, but it also returns `setup_requires`.

Related: https://github.com/astral-sh/uv/issues/1582

**Comment by charliermarsh** [comment]
@sbidoul -- Thank you!

**Comment by charliermarsh** [comment]
I think this isn't gonna work.
