### ISSUE TITLE
how  find comma, when check code

### ISSUE THREAD

**Issue by linpan** [astral-sh/uv#8629]
sometime, use forget comma in code end.  this is error issues. how check it or support it .

![CleanShot 2024-10-28 at 09 58 08](https://github.com/user-attachments/assets/10fac284-388b-479e-96a4-332e7fccfc1a)

**Comment by FishAlchemist** [comment]
Are you looking for Ruff? I don't think UV supports code lint or format.
https://github.com/astral-sh/ruff

**Comment by charliermarsh** [comment]
Yeah looks like this is intended for Ruff.
