### ISSUE TITLE
uv export should not need to have python installed

### ISSUE THREAD

**Issue by mjpieters** [astral-sh/uv#8634]
We are running a CI pipeline that includes a mend.io license compliance scanner, which looks for a `requirements.txt` file (it doesn't yet support uv.lock as an input file). We run the mend scanner in a minimal docker container with no Python installed. I can trivially install uv into that container, but without a python installation, I can't export the lock file to `requirements.txt` file:

```sh
$ uv --version
uv 0.4.27
$ uv export --output-file requirements.txt
error: No interpreter found for Python >=3.12 in managed installations or system path
```

Python should not be necessary here, all that is needed is that uv produces a requirements.txt file for another tool to then process.

The same applies to the `tree` command; uv has all the information needed already, a Python interpreter should not be necessary.

**Comment by zanieb** [comment]
I think we could do this with `--frozen` by making this block conditional https://github.com/astral-sh/uv/blob/291c4c496d6513d1da5e4b8d7ac31d7aa536c87a/crates/uv/src/commands/project/export.rs#L84-L95

Otherwise, we need an interpreter to check if the lockfile is up to date.

**Comment by charliermarsh** [comment]
I think we need an interpreter either way, because we need to know the platform markers.

**Comment by charliermarsh** [comment]
(In `uv tree`, we need an interpreter unless the user passes `--universal`.)

**Comment by zanieb** [comment]
Are you talking about `uv pip tree`?

**Comment by mjpieters** [comment]
Right, it didn't occur to me that `tree` would be platform dependant. I'm happy to ignore `uv tree` in this bug report, I am much more concerned with `uv export` in CI environments.
