### ISSUE TITLE
Unable to install dedupe

### ISSUE THREAD

**Issue by mackenziedott** [astral-sh/uv#8644]
I'm able to install the python library dedupe in a conda environment, but am unable to succeed in uv.

Command: `uv add dedupe` (or `uv pip install dedupe`)

Log:
`error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: dedupe-levenshtein-search==1.4.5
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
running build
running build_ext
building 'Levenshtein_search' extension
clang -pthread -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fPIC -fPIC -I/home/[USER_DIR]/.cache/uv/builds-v0/.tmpKRPfEs/include -I/home/[USER_DIR]/.local/share/uv/python/cpython-3.12.5-linux-x86_64-gnu/include/python3.12 -c Lev_search.c -o build/temp.linux-x86_64-cpython-312/Lev_search.o
--- stderr:
/home/[USER_DIR]/.cache/uv/builds-v0/.tmpKRPfEs/lib/python3.12/site-packages/setuptools/_distutils/cmd.py:111: SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated
!!

        ********************************************************************************
        With Python 2.7 end-of-life, support for building universal wheels
        (i.e., wheels that support both Python 2 and Python 3)
        is being obviated.
        Please discontinue using this option, or if you still need it,
        file an issue with pypa/setuptools describing your use case.

        By 2025-Aug-30, you need to update your project and remove deprecated calls
        or your builds will no longer be supported.
        ********************************************************************************

!!
  self.finalize_options()
error: command 'clang' failed: No such file or directory
---`

running regular `pip install dedupe` succeeds, but `uv sync` will of course erase the package.

uv version = 0.4.0

**Comment by charliermarsh** [comment]
Does setting `CC=gcc CXX=g++` fix this?

**Comment by mackenziedott** [comment]
It does!

**Comment by charliermarsh** [comment]
Another case of  https://github.com/astral-sh/uv/issues/8429 / https://github.com/astral-sh/uv/issues/8036. We're tracking over there. Sorry about that!
