### ISSUE TITLE
Create venv from script metadata

### ISSUE THREAD

**Issue by satwell** [astral-sh/uv#8652]
Being able to `uv run` a script with PEP 723 metadata is really cool.

But it seems like uv is missing a way to create a venv for the script.  Having a venv with script dependencies is useful for development, so that my editor can provide auto-completion, type checking, etc.

My workaround is to maintain the same dependency list in a separate `pyproject.toml` file, which lets me easily sync to a venv.  But that means I need to maintain the same dependency list in two places, which is not ideal.

**Comment by zanieb** [comment]
#8609 would be a step towards this

**Comment by gnosys-nmercer** [comment]
May be duplicate of #6637

**Comment by bgrove-s7** [comment]
> Being able to `uv run` a script with PEP 723 metadata is really cool.
> 
> But it seems like uv is missing a way to create a venv for the script. Having a venv with script dependencies is useful for development, so that my editor can provide auto-completion, type checking, etc.
> 
> My workaround is to maintain the same dependency list in a separate `pyproject.toml` file, which lets me easily sync to a venv. But that means I need to maintain the same dependency list in two places, which is not ideal.

This would be a hugely helpful feature.

**Comment by zanieb** [comment]
Let's track in the other issue.
