### ISSUE TITLE
Using `uv` w/ Databricks

### ISSUE THREAD

**Issue by soneill-pure** [astral-sh/uv#8671]
Has anyone had success using `uv` with Databricks? I'm loving `uv` for local project development and I'd like the ability to quickly offload heavy ML compute jobs to Databricks which would involve replicating my local virtual env on Databricks. I'd prefer to use `uv` to replicate the env for speed and parity. My initial thoughts are to create a [custom docker container](https://docs.databricks.com/en/compute/custom-containers.html) that uses `uv` instead of vanilla `virtualenv` & `pip` that they currently use in their [base images](https://github.com/databricks/containers/blob/master/ubuntu/python/Dockerfile).

**Comment by zanieb** [comment]
Nice, that seems reasonable. Let us know if you have more questions.

**Comment by astrojuanlu** [comment]
Similar to #4379

**Comment by frbelotto** [comment]
Sorry do reopen it, but does it still work?
I am really struggling to using UV as package manager for my project on databricks

**Comment by zanieb** [comment]
@frbelotto open an issue with details please.

**Comment by Hangzhi** [comment]
@frbelotto @soneill-pure Databricks engineer here. 

We already supported `%uv pip install` in Serverless environment v5+. https://docs.databricks.com/aws/en/libraries/notebooks-python-libraries#faster-installs-with-uv-pip 

Other API support will be available soon. Can you please let us know your current workflow?

**Comment by frbelotto** [comment]
Hi! 
As far as I know uv pip works just like a proxy to pip install using rust for speed, but does not keep the pyproject.toml tracking of dependencies. 

I really avoid it. 

Today I am keeping %pip install in my notebook but is not really fast. At least uv pip is faster !

**Comment by Hangzhi** [comment]
@frbelotto Thanks for the feedback! It's very helpful!

In what kind of scenario would you like to use pyproject.toml? 

Curious if you are using git repository or DABs together with pyproject.toml or you are expecting to use pyproject.toml in any Databricks workspace folder? 

Would you find a pyproject.toml attaching to specific notebook through the serverless environment panel helpful?

**Comment by frbelotto** [comment]
I think that pyproject is easier for cloning a repository or moving a project among teams than setting up notebook dependencies manually in the databricks instance.

**Comment by svroonland** [comment]
This worked for me: with this command there is no need to set the `UV_PROJECT_ENVIRONMENT` env variable, as `uv` will detect the active virtual env and use it:

```
%sh uv sync --locked --no-editable --active
```

**Comment by bthorsted** [comment]
> [@frbelotto](https://github.com/frbelotto) [@soneill-pure](https://github.com/soneill-pure) Databricks engineer here.
> 
> We already supported `%uv pip install` in Serverless environment v5+. https://docs.databricks.com/aws/en/libraries/notebooks-python-libraries#faster-installs-with-uv-pip
> 
> Other API support will be available soon. Can you please let us know your current workflow?

Will `uv` be supported for task dependencies in the near future? I have a task that depends on ProjectA that in turn depends on an unpublished fork of a well-known python library, LibraryB. ProjectA is wheel in the workspace, but LibraryB is a Github URL. The job fails because Databricks installs the wheel for ProjectA with pip.

**Comment by Hangzhi** [comment]
@bthorsted 

Yes, uv support for dependencies is on our roadmap. Stay tuned!

**Comment by yiweidai-db** [comment]
@frbelotto @svroonland @bthorsted 

Frequently used uv commands, ncluding `%uv pip install`, `%uv add`, and `%uv sync`, are now supported on Serverless with environment version 5 or later. 

https://docs.databricks.com/aws/en/libraries/notebooks-python-libraries#manage-a-project-environment-with-uv

Let me know if you have any further feedbacks!

**Comment by svroonland** [comment]
I'm curious, is there anything blocking from supporting this on non-serverless compute?
