### ISSUE TITLE
CI flakiness: run_from_directory

### ISSUE THREAD

**Issue by konstin** [astral-sh/uv#8681]
`run_from_directory` sometimes recreates the venv: https://github.com/astral-sh/uv/actions/runs/11578473249/job/32232394993

> --- STDOUT:              uv::it run::run_from_directory ---
> 
> running 1 test
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> Snapshot: run_from_directory-7
> Source: crates/uv/tests/it/run.rs:1823
> ────────────────────────────────────────────────────────────────────────────────
> Expression: snapshot
> ────────────────────────────────────────────────────────────────────────────────
> -old snapshot
> +new results
> ────────────┬───────────────────────────────────────────────────────────────────
>     3     3 │ 3.10.[X]
>     4     4 │ 
>     5     5 │ ----- stderr -----
>     6     6 │ warning: `VIRTUAL_ENV=[VENV]/` does not match the project environment path `.venv` and will be ignored
>           7 │+Using CPython 3.10.[X] interpreter at: [PYTHON-3.10]
>           8 │+Removed virtual environment at: .venv
>           9 │+Creating virtual environment at: .venv
>     7    10 │ Resolved 1 package in [TIME]
>     8       │-Audited 1 package in [TIME]
>          11 │+Installed 1 package in [TIME]
>          12 │+ + foo==1.0.0 (from file://[TEMP_DIR]/project)
> ────────────┴───────────────────────────────────────────────────────────────────
> Stopped on the first failure. Run `cargo insta test` to run all snapshots.
> test run::run_from_directory ... FAILED

**Comment by zanieb** [comment]
Isn't this the one Charlie just fixed in #8673 ?

**Comment by konstin** [comment]
Thank you!
