### ISSUE TITLE
uv remove and uv add on a package produces missing `RECORD` file error on `dist-info` folder

### ISSUE THREAD

**Issue by akozlu** [astral-sh/uv#8690]
Hey team, experiencing an issue w.r.t. `uv remove` and then `uv add` operations, was looking for direction/wondering if there's a known fix. One similar closed issue I found is this one: https://github.com/astral-sh/uv/issues/1525

```
uv is already installed.
uv 0.4.27 (36b729e92 2024-10-25)
Searching for Python versions matching: Python 3.8.20
Found existing installation for Python 3.8.20: cpython-3.8.20-linux-x86_64-gnu
Using CPython 3.8.20
```

The problem seems to be the leftover `dist-info` folder after running the remove command. Once that file is deleted manually, the re-installation occurs as expected. I've looked around and there are some suggestions to pass `--ignore-installed` as a flag through pip: https://github.com/pypa/pip/issues/4785. 
Appreciate any direction & assistance.
```
# uv remove xgboost
Resolved 67 packages in 115ms
   Built ds-reports @ file:///home/user/ds_reports
Prepared 1 package in 4.61s
Uninstalled 2 packages in 2.06s
Installed 1 package in 122ms
 ~ ds-reports==1.0.2 (from file:///home/user/ds_reports)
 - xgboost==0.90
# uv add xgboost==2.0.0
Resolved 68 packages in 132ms
   Built ds-reports @ file:///home/user/ds_reports
Prepared 2 packages in 5.88s
warning: Failed to uninstall package at .venv/lib/python3.8/site-packages/xgboost-0.90.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
# cd .venv/lib/python3.8/site-packages/xgboost-0.90.dist-info
total 0
# ls -la 
total 16
drwxr-xr-x.   2 root root  6144 Oct 29 22:06 .
drwxr-xr-x. 156 root root 14336 Oct 29 22:06 ..
```

Example tail of verbose prints the following
```
DEBUG Unnecessary package: nvidia-nccl-cu12==2.23.4
DEBUG Unnecessary package: xgboost==0.90
DEBUG Unnecessary package: xgboost==2.1.2
warning: Failed to uninstall package at .venv/lib/python3.8/site-packages/nvidia_nccl_cu12-2.23.4.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
warning: Failed to uninstall package at .venv/lib/python3.8/site-packages/xgboost-0.90.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
warning: Failed to uninstall package at .venv/lib/python3.8/site-packages/xgboost-2.1.2.dist-info due to missing `RECORD` file. Installation may result in an incomplete environment.
```

**Comment by akozlu** [comment]
i guess https://github.com/astral-sh/uv/issues/2467 also implies that previous remove command has gone wrong but not seeing any error/warnings come from the preceding `uv remove` command.

**Comment by charliermarsh** [comment]
Is this something you're able to reproduce repeatedly, or just the state of a current environment?

**Comment by akozlu** [comment]
Hey Charlie, yes, we've been able to reproduce repeatedly. The team looked into this further today, and we have a possible lead tied back to the `warning: Failed to hard link files; falling back to a full copy.` you produce. 
In our Linux environment, we have an EFS mount on the `/home/` directory, so the `/tmp/` and `/home/` are on different filesystems, and we think this is leading into issue in downstream `uv add` or `uv remove` operations. Example: 
```
DEBUG Failed to hardlink `/home/<REPO>/.venv/lib/python3.11/site-packages/pytz/__init__.py` to `/tmp/.tmphrEC5x/archive-v0/mMQe5cXzRdbHNG9Qcjta6/pytz/__init__.py`, attempting to copy files as a fallback
[...]
error: Failed to install: jmespath-1.0.1-py3-none-any.whl (jmespath==1.0.1)
  Caused by: failed to remove directory `/home/<REPO>/.venv/lib/python3.11/site-packages/jmespath-1.0.1.data`
  Caused by: Device or resource busy (os error 16)
```
However, if we run `uv pip check` afterward, everything looks fine, but we experience the issue mentioned in initial post.
```
# uv pip check 
Checked 103 packages in 439ms
All installed packages are compatible
```

Is it an option to point `uv` to use a different temporary directory for the above operations other than `/tmp` directory was the question. If so we could test that and report back. Thank you!

**Comment by zanieb** [comment]
You can use `--cache-dir <path>` instead of `--no-cache`

**Comment by akozlu** [comment]
I was about to make this edit :) The reason we went for the `--no-cache` option were the build/wheel issues we experienced with packages like `pandasql=0.7`, `deap-1.4.1`, again related to filesystem setup we have on linux
 
Understand that it's not intuitive to provide a `--no-cache` flag and then ask to write that to a different temporary directory other than `/tmp/`. 
looking to confirm then there's no redirecting to another folder then `/tmp/` with `no-cache` option.  Looking at [environment variables ](https://docs.astral.sh/uv/configuration/environment/#environment-variables), I thought `XDG_CACHE_HOME` is something that can be attempted to change. Thanks for the direction again.

**Comment by akozlu** [comment]
one idea is to change the venv path to be created under the persistent filesystem. Not fully sure about the downsides of that approach and whether project directory is persistenly linked towards that venv that exists outside

**Comment by zanieb** [comment]
`--no-cache` is equivalent to setting `--cache-dir <path>` then discarding the directory.

We don't respect `XDG_CACHE_HOME` for `--no-cache`, https://github.com/astral-sh/uv/blob/e9f1161b953b017d21e70761a52b3fd426a8c111/crates/uv-cache/src/lib.rs#L139-L147

However, we are just using the standard `tempdir` function which looks like it [respects `TMPDIR` on Unix](https://doc.rust-lang.org/std/env/fn.temp_dir.html#platform-specific-behavior).

**Comment by akozlu** [comment]
That should do it - appreciate the direction :saluting_face:
