### ISSUE TITLE
Publish Docker images to Docker Hub

### ISSUE THREAD

**Issue by gaby** [astral-sh/uv#8699]
When using a Docker Registry to reduce network i/o and bandwidth costs you can't mirror images from `ghcr.io` as stated here: https://docs.docker.com/docker-hub/mirror/#gotcha

It would be great if the Docker images for `uv` were published to Docker Hub too.

**Comment by zanieb** [comment]
I don't think we'll do this — I'm not comfortable spending time maintaining the images across multiple registries.

**Comment by gaby** [comment]
Seems reasonable, thanks!
