### ISSUE TITLE
`uv sync --upgrade` always gives warning about an old extra for typer

### ISSUE THREAD

**Issue by taranlu-houzz** [astral-sh/uv#8710]
Previously, I was using an older version of `typer` where you needed to add the `typer[all]` extra to get full functionality. I deleted that extra since it is no longer needed, but for some reason, whenever I run `uv sync --upgrade`, I get warning messages about it. Seems like maybe this old dep config is sticking around in a cache somewhere?

```
❯ uv sync --upgrade
Resolved 79 packages in 956ms
warning: The package `typer==0.12.5` does not have an extra named `all`
Audited 75 packages in 0.28ms
```

```toml
[project]
dependencies = [
  .
  .
  .
  "sqlmodel>=0.0.22",
  "stamina>=24.3.0",
  "tenacity>=9.0.0",
  "typer>=0.12.5",
  "ujson>=5.10.0",
  "uvicorn[standard]>=0.32.0",
]
```

**Comment by samypr100** [comment]
Hello, do you have a way to reproduce? I wasn't able to reproduce.

I don't see an extra in [typer ](https://github.com/fastapi/typer/blob/master/pyproject.toml) called `all` in 0.12.5.
It seems [0.11.x](https://github.com/fastapi/typer/blob/0.11.1/pyproject.toml) did have it.

When I installed 0.11.x with all and upgraded it to 0.12.5 I didn't get a warning unless `all` was still referenced in pyproject.toml.

**Comment by taranlu-houzz** [comment]
I need to try a minimal example as well, but what you are describing is more or less what I believe I did. I do have other deps that also rely on `typer` and it may be possible that they had `typer[all]` in their `pyproject.toml`, but I also did not see anything that looked like an extra related to `typer` anywhere in my project.

**Comment by zanieb** [comment]
It seems likely the request comes from a transitive dependency?

We just display this warning whenever we look at a package request https://github.com/astral-sh/uv/blob/5ab860be20e75451c3c9c779c5f552b3fd0cb2ad/crates/uv-resolver/src/resolution/graph.rs#L347-L354

I don't think it'd be easy for us to display where the request came from in this context.

**Comment by seapagan** [comment]
I was getting this exact warning today when i was upgrading a FastAPI app from Poetry to uv. Turns out I had forgotten to delete the OLD `.venv` from Poetry which still had an older version of **something** that wanted `typer[all]`. Deleted the `.venv` and issue was gone.

**Comment by taranlu-houzz** [comment]
@zanieb @seapagan Okay, that makes sense. Thanks for the confirmation!
