### ISSUE TITLE
uv sync groups from workspace member packages in a virtual workspace

### ISSUE THREAD

**Issue by drmason13** [astral-sh/uv#8722]
uv 0.4.29

I have a virtual workspace. I want to install a union of all my members' dependencies _including_ development dependencies.

With dependency-groups I had hoped this would now be easy:

```
uv sync --group dev
error: Group `dev` is not defined in the project's `dependency-group` table
```

but this simply complained saying that no group `dev` existed _in the workspace root_ (which is true, but I do have a dependency-group named dev in one of my members).

I've tried two approaches to workaround this:

1. Move all dev dependencies into the workspace root
2. Duplicate all dev dependencies in workspace root and each member package

Both have downsides, in the case of 1. (moving), my packages can no longer be tested independently since they lack their own development dependencies. In the case of 2. (duplicating), that is its own downside. To add development dependencies I am editing multiple pyproject.toml files, which is the kind of thing I hoped to avoid by using a virtual workspace.

# Suggested solution

Within a virtual workspace, I want `uv sync` to have visibility of each members' dependency-groups specified within pyproject.toml, as well as their dependencies.

How to request that those groups be included or not could go one of two ways:

## 1. Implicit
* Have `uv sync --group dev` include dependencies from all members' dependency groups, and the root.

## 2. Explicit
* Have `uv sync --group dev` only see groups in the root project (behaviour unchanged).
* Have `uv sync --group dev --include-dependency-groups-of-all-workspace-members` include dependencies from all members' dependency groups, and the root. Same as in the implicit case.

`--include-dependency-groups-of-all-workspace-members` is obviously too long, pending a suitable alternative. I don't have a strong opinion on the name of the option. It could also/instead be a config file option.

With 2. it would be natural to extend the request to list specific members to include the group from, though that's harder to think of syntax for. i.e. I want group `dev` from members `foo` and `bar` where `foo` and `bar` are the package names of an arbitrary subset of my workspace members. I don't have a good use case for this myself though.

**Comment by charliermarsh** [comment]
Sorry yeah -- this is a bug. I actually just noticed it in a separate context. Will fix it now.

**Comment by christian512** [comment]
As far as I understand https://github.com/astral-sh/uv/pull/8734 it only removes the error when using  `--group` and there is no such group defined in the workspace, but in an included package. 
However, it would great to enable installation of dependency-groups of packages inside of workspaces, as described by @drmason13  above.

Is this a planned feature?
