### ISSUE TITLE
Add `uv sync --all` and `uv run --all`

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#8724]
To sync the entire workspace.

**Comment by zanieb** [comment]
Should we do like `--all-members` or `--all-packages`? Or is that just verbose for no reason? Is there something else someone that's not working in a workspace context would think `--all` means?

**Comment by jackvreeken** [comment]
Probably related, but it would then also be nice to have `uv export --all` . I think that `uv build` already has an `--all` option to "build all packages in the workspace", as far as consistency of naming is concerned. Might clash a little with the `--all-*` (extras, platforms, versions) that some other commands like `run` have.

**Comment by samypr100** [comment]
How about an explicit `--workspace` to imply all?

**Comment by charliermarsh** [comment]
I don't mind a `--workspace` alias, I think I advocated for that with `uv build` though and was overruled :)
