### ISSUE TITLE
uv add with constraints gives unexpected result

### ISSUE THREAD

**Issue by itrase** [astral-sh/uv#8726]
To reproduce (on uv 0.4.29)
```
mkdir project_a
cd project_a
uv init
uv add torch>=2.4.0
```

This results in the toml file:
```
[project]
name = "project-a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.5.1",
]
```

Why is the constraint different than what I asked for? Is this the intended behavior, and if so, what is the right way to specify a lower bound using uv add?

**Comment by itrase** [comment]
Figured it out - I was missing quotes.
`uv add torch>=2.4.0` doesn't work, and silently drops the requirement
`uv add "torch>=2.4.0"` works totally fine
So that solves the problem, but I wonder if uv should maybe give a warning when a user gives a constraint that isn't used?

**Comment by zanieb** [comment]
That's a shell problem, uv doesn't even see the `>=2.40`, your shell removes that before it gets to us, e.g., for `echo "test" > file` syntax.

**Comment by itrase** [comment]
ah got it - thanks! This can definitely be closed then
