### ISSUE TITLE
uv offers wrong Python when inside Docker with Rosetta in AMD linux on Mac ARM

### ISSUE THREAD

**Issue by bepuca** [astral-sh/uv#8745]
The situation is a bit special: I usually work on [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers). Sadly, there are still many packages that do not have support for ARM architecture. Thus, many times I end up within a Docker container running rosetta since my Mac is sillicon.

## Minimal Example

```Dockerfile
# devcontainer/Dockerfile
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.4.29 /uv /uvx /bin/
```

```json
// devcontainer/devcontainer.json
{
    "name": "minimal",
    "build": { "dockerfile": "Dockerfile" },
    "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
    "remoteEnv": {
        // Ensure venv is always first in PATH
        "PATH": "${containerWorkspaceFolder}/.venv/bin:${containerEnv:PATH}",
    },
    "remoteUser": "vscode",
}
```

To reproduce you will need:
- A Mac with AppleSillicon
- VSCode with the [devcontainer extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) installed
- Docker in your machine

Then, open the command palette of VSCode (if not directly prompted) and "reopen in container".

Once it builds, if I go to the terminal and run:
```shell
$uv python list

cpython-3.13.0+freethreaded-linux-aarch64-gnu    <download available>
cpython-3.12.7-linux-aarch64-gnu                 <download available>
cpython-3.11.10-linux-aarch64-gnu                <download available>
cpython-3.10.15-linux-aarch64-gnu                <download available>
cpython-3.10.12-linux-x86_64-gnu                 /usr/bin/python3.10
cpython-3.10.12-linux-x86_64-gnu                 /usr/bin/python3 -> python3.10
cpython-3.10.12-linux-x86_64-gnu                 /bin/python3.10
cpython-3.10.12-linux-x86_64-gnu                 /bin/python3 -> python3.10
cpython-3.9.20-linux-aarch64-gnu                 <download available>
cpython-3.8.20-linux-aarch64-gnu                 <download available>
pypy-3.10.14-linux-aarch64-gnu                   <download available>
pypy-3.9.19-linux-aarch64-gnu                    <download available>
pypy-3.8.16-linux-aarch64-gnu                    <download available>
pypy-3.7.13-linux-aarch64-gnu                    <download available>
```

As we can see, it finds the AMD arch python that comes pre-installed but everything else it offers is ARM. Thus, nothing works because it crashes when trying to use any of these pythons because they have the wrong architecture. For reference, this is the error:

```shell
$uv sync

error: Failed to query Python interpreter at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11`
  Caused by: No such file or directory (os error 2)
```

I am not sure if I am installing uv wrong somehow or if I can do something to direct it to the right arch. Any help will be super appreciated, thank you!

**Comment by bepuca** [comment]
The logs with verbose (if I understand correctly how to get them):

```shell
$ uv sync -v

DEBUG uv 0.4.29
DEBUG Found project root: `/workspaces/minimal`
DEBUG No workspace root found, using project root
DEBUG Reading requests from `/workspaces/minimal/.python-version`
DEBUG Searching for Python 3.11 in managed installations or system path
DEBUG Searching for managed installations at `/home/vscode/.local/share/uv/python`
DEBUG Found managed installation `cpython-3.11.10-linux-aarch64-gnu`
DEBUG Failed to inspect Python interpreter from managed installations at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11` 
error: Failed to inspect Python interpreter from managed installations at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11`
  Caused by: Failed to query Python interpreter at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11`
  Caused by: No such file or directory (os error 2)
 ```
 
 And running the command you suggest:
 
 ```shell
 $ uv sync -p cpython-3.11.10-linux-x86_64-gnu -v

DEBUG uv 0.4.29
DEBUG Found project root: `/workspaces/minimal`
DEBUG No workspace root found, using project root
DEBUG Searching for cpython-3.11.10-linux-x86_64-gnu in managed installations or system path
DEBUG Searching for managed installations at `/home/vscode/.local/share/uv/python`
DEBUG Found managed installation `cpython-3.11.10-linux-aarch64-gnu`
DEBUG Failed to inspect Python interpreter from managed installations at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11` 
error: Failed to inspect Python interpreter from managed installations at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11`
  Caused by: Failed to query Python interpreter at `/home/vscode/.local/share/uv/python/cpython-3.11.10-linux-aarch64-gnu/bin/python3.11`
  Caused by: No such file or directory (os error 2)
```

Let me know if there is anything else I can do to provide more info.

**Comment by zanieb** [comment]
I think it's a bug, in that when we fill the platform information at

https://github.com/astral-sh/uv/blob/893257bb0b2a0df4196410f279d5a837effafee0/crates/uv-python/src/downloads.rs#L192-L194

and

https://github.com/astral-sh/uv/blob/2b0e16cb75911bc291c92f7186512223c2d2d899/crates/uv-python/src/platform.rs#L76-L78

we think it's `aarch64` instead of `x86_64`. I'm not really sure why yet.

You could put that full version tag in a `UV_PYTHON` environment variable and we should respect it.

**Comment by zanieb** [comment]
Are you copying uv from the right image?

https://github.com/astral-sh/uv/pkgs/container/uv/298017082?tag=latest

<img width="830" alt="Screenshot 2024-11-01 at 6 30 24 PM" src="https://github.com/user-attachments/assets/b7a578e2-af18-4226-afa1-b9c81f61de98">

**Comment by samypr100** [comment]
Agreed with @zanieb. Usually you'd pass `--platform` to your `docker buildx build --platform=linux/amd64 -t foo-linux-amd64 /path/to/context` to resolve this as it will then pick the right manifest entry.

That would allow you to cleanup the `Dockerfile`

```dockerfile
# devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/base:jammy

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.4.29 /uv /uvx /bin/
```

Alternatively would be using raw sha

```dockerfile
# devcontainer/Dockerfile
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:jammy

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.4.29@sha256:c17127bc372350d61bae20be54c85540a8937eaa691c61840a7abc80e284fc8d /uv /uvx /bin/
```

**Comment by samypr100** [comment]
On VSCode, you may be able to do this by leveraging devcontainers extension [build.options](https://containers.dev/implementors/json_reference/#image-specific) setting. e.g.

```json
    "build": { 
        ...
        "options": [
            "--platform=linux/amd64"
        ]
    },
```

**Comment by zanieb** [comment]
We should add some notes to the documentation about using cross-platform images.

**Comment by bepuca** [comment]
It does seem I might have been using the wrong uv using a naive copy. I would still have expected that to work but using curl is an option and does seem to solve the issue. Thank you very much for the help!
