### ISSUE TITLE
uv does not pass PID 1 to child processes

### ISSUE THREAD

**Issue by ejungcl** [astral-sh/uv#8761]
uv version: uv 0.4.23 (83f835b0d 2024-10-17)

When using uv to run a containerized gunicorn app, it will not pass along SIGTERM to children.

If I install a flask app with pip and run it with gunicorn as the ENTRYPOINT or CMD, it will handle SIGTERM as expected. However, if I use 'uv run', it will hang.

The only difference between the two run command is this:
CMD ["gunicorn", "--config", ...]
vs.
CMD["uv", "run", "gunicorn", "--config", ...]

http://blog.dscpl.com.au/2015/12/issues-with-running-as-pid-1-in-docker.html
https://petermalmgren.com/signal-handling-docker/

**Comment by zanieb** [comment]
This is a duplicate of https://github.com/astral-sh/uv/issues/6724
