### ISSUE TITLE
config prerelease does not take effect in pyproject.toml

### ISSUE THREAD

**Issue by eruvanos** [astral-sh/uv#8763]
uv: 0.4.29

adding the config:
```
[tool.uv.pip]
prerelease = "allow"
```

does not take any effect, but the following does:

```
[tool.uv]
prerelease = "allow"
```

> Not sure which one is intended, but the documentation is not correct at the moment: [Link](https://docs.astral.sh/uv/reference/settings/#pip_prerelease)

**Comment by zanieb** [comment]
Please see https://docs.astral.sh/uv/configuration/files/#configuring-the-pip-interface

**Comment by eruvanos** [comment]
I see, my fault. Thank you
