### ISSUE TITLE
Feature Reqeust: Add shell command to uv cli

### ISSUE THREAD

**Issue by tleonhardt** [astral-sh/uv#8782]
I love how fast `uv` is and I am beginning to use it as a replacement for `pipenv`. The one thing I really miss is the ability to do something like `uv shell` to quickly and easily activate the venv.  This could be a very simple command that takes no arguments and just runs `source .venv/bin/activate` where `.venv` is the path to the virtual env created by `uv`.

**Comment by charliermarsh** [comment]
Thanks! I believe this is the same as #1910 -- you can track that issue instead.

**Comment by tleonhardt** [comment]
@charliermarsh Ah sorry, I searched but didn't see that one.  Thanks!

**Comment by charliermarsh** [comment]
No prob!
