### ISSUE TITLE
xgboost==0.90 fails to install on Windows 10

### ISSUE THREAD

**Issue by RyanBlace** [astral-sh/uv#8798]
```
C:\Users\Ryan\xgboostinstall>uv init
Initialized project `xgboostinstall`

C:\Users\Ryan\xgboostinstall>uv add xgboost==0.90
Using CPython 3.12.7
Creating virtual environment at: .venv
Resolved 4 packages in 14ms
error: Failed to install: xgboost-0.90-py2.py3-none-win_amd64.whl (xgboost==0.90)
  Caused by: RECORD file doesn't match wheel contents: Could not find entry for xgboost-0.90.data\data\xgboost\vcomp140.dll (C:\Users\Ryan\xgboostinstall\.venv\Lib\site-packages\xgboost-0.90.data\data\xgboost\vcomp140.dll)

C:\Users\Ryan\xgboostinstall>uv --version
uv 0.4.29 (85f9a0d0e 2024-10-30)

C:\Users\Ryan\xgboostinstall>ver
Microsoft Windows [Version 10.0.19045.5011]
```

This does work with pyenv. 

I realize that xgboost 0.90 is from May 2019, so this might not be worthwhile. But, I want to report it in case it hints at some larger issue.

Thank you so much for uv, it is changing how we work!

**Comment by konstin** [comment]
I've checked and confirmed that this is a bug in the packaging of that xgboost version:

In https://inspector.pypi.io/project/xgboost/0.90/packages/5e/49/b95c037b717b4ceadc76b6e164603471225c27052d1611d5a2e832757945/xgboost-0.90-py2.py3-none-win_amd64.whl/xgboost-0.90.dist-info/RECORD#line.18, it records a `xgboost-0.90.data/data/xgboost/xgboost.dll`, but the package contains a `./xgboost-0.90.data/data/xgboost/vcomp140.dll` (https://inspector.pypi.io/project/xgboost/0.90/packages/5e/49/b95c037b717b4ceadc76b6e164603471225c27052d1611d5a2e832757945/xgboost-0.90-py2.py3-none-win_amd64.whl/).

**Comment by RyanBlace** [comment]
Thank you for explaining what is going on.

Is there a switch to tell uv to ignore extra files missing from the RECORD? I'm guessing that is what pip is doing.

**Comment by konstin** [comment]
As far as i know, pip is basically just ignoring the RECORD. We need the RECORD properly, since we use it for uninstalling files. I recommend upgrading to a newer xgboost version that has this bug fixed.
