### ISSUE TITLE
[discussion] Will uv consider to add groups information in uv.lock for dependencies?

### ISSUE THREAD

**Issue by monchin** [astral-sh/uv#8801]
Hello, as PEP 735 is already supported by uv, I'm curious whether there is a plan to add groups information in `uv.lock` for dependencies? I think it would be great if we can realize which groups the packages belong to directly in `uv.lock` by just adding for example
```
[[package]]
name = "python-dotenv"
version = "1.0.1"
groups = ["Default"]
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/bc/57/e84d88dfe0aec03b7a2d4327012c1627ab5f03652216c63d49846d7a6c58/python-dotenv-1.0.1.tar.gz", hash = "sha256:e324ee90a023d808f1959c46bcbc04446a10ced277783dc6ee09987c37ec10ca", size = 39115 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl", hash = "sha256:f7b63ef50f1b690dddf550d03497b66d609393b40b564ed0d674909a68ebf16a", size = 19863 },
]

[[package]]
name = "mypy"
version = "1.13.0"
groups = ["lint"]
source = { registry = "https://pypi.org/simple" }
dependencies = [
    { name = "mypy-extensions" },
    { name = "tomli", marker = "python_full_version < '3.11'" },
    { name = "typing-extensions" },
]
```
Of course I know that there is `package.dev-dependencies` information in `uv.lock`, but maybe `groups` in `package` would be more intuitive. And for example, `mypy` depends on `mypy-extensions`, so `mypy-extensions` should also be in `lint` group, which cannot be expressed just by `package.dev-dependencies`.

Actually, [PEP 751](https://peps.python.org/pep-0751/#packages-groups) also supports groups in package info, [for example](https://peps.python.org/pep-0751/#examples)
```
[[packages]]
name = 'numpy'
version = '2.1.2'
groups = ['Default']
index_url = 'https://pypi.org/simple/numpy'
direct = false
requires_python = '>=3.10'
dependencies = [

]
editable = false
wheels = [
  { tags = ['cp312-cp312-manylinux2014_x86_64', 'cp312-cp312-manylinux_2_17_x86_64'], url = 'https://files.pythonhosted.org/packages/9b/b4/e3c7e6fab0f77fff6194afa173d1f2342073d91b1d3b4b30b17c3fb4407a/numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', hash = '6d95f286b8244b3649b477ac066c6906fbb2905f8ac19b170e2175d3d799f4df', upload_time = 2024-10-05T18:36:20.729642+00:00, size = 16041825 },
  { tags = ['cp312-cp312-win_amd64'], url = 'https://files.pythonhosted.org/packages/4c/79/73735a6a5dad6059c085f240a4e74c9270feccd2bc66e4d31b5ca01d329c/numpy-2.1.2-cp312-cp312-win_amd64.whl', hash = '456e3b11cb79ac9946c822a56346ec80275eaf2950314b249b512896c0d2505e', upload_time = 2024-10-05T18:37:38.159022+00:00, size = 12568254 }
]
```
Although it is just in draft, I think it's quite reasonable. Even though it would be rejected finally, I still believe groups info would be helpful, for example installing packages in certain groups or collecting licenses of packages in  certain groups would be easy. So maybe it's a good idea to add this feature?

**Comment by charliermarsh** [comment]
We track all this information in the lockfile already via `package.dev-dependencies` and `package.metadata.requires-dev` -- they just have that "dev" naming for backwards compatibility, to avoid breaking older uv clients. The PEP uses `groups` to achieve something slightly different, and it doesn't really make sense in our schema today. We can already do all the things you describe with the current format: `uv sync --group lint` or `uv sync --only-group lint`, etc.

**Comment by zanieb** [comment]
(See #8599)

**Comment by monchin** [comment]
> We can already do all the things you describe with the current format: `uv sync --group lint` or `uv sync --only-group lint`, etc.

@charliermarsh Thank you for your reply, but sorry to bother you again. 

Actually, my motivation is that I'm developping a program by python, and I need to include all the licenses of dependencies I'm using. But I'd like to exclude licenses of pytest in test group, licenses of mypy (and  mypy's dependencies, e.g., mypy-extensions) and types-pstuils in lint group, black (and black's dependencies, e.g., click) in format group, etc. 

I mean, if like PEP751, there is `groups` in package, I can just iterate all the packages in the lock file and read each package's groups. If the package is in the groups I need to include, I'll read its dist-info and find its license and copy it to the License dir.  now I need to read `package.dev-dependencies`, and read their dependencies. And I need to be careful that if one dependency is both in default and in for example format group, I still need to include its license, this means that I need to create the whole dependency-graph myself, that's the only way I can think of for this requirement.  Would you please give me some hint for this requirement?

**Comment by charliermarsh** [comment]
Yeah, you'll need to walk the dependency graph, or use `uv tree --only-group lint` and try to parse that. (We should have programmatic output, like JSON, for `uv tree`, but we don't currently.)

**Comment by monchin** [comment]
> Yeah, you'll need to walk the dependency graph, or use `uv tree --only-group lint` and try to parse that. (We should have programmatic output, like JSON, for `uv tree`, but we don't currently.)

Thank you! got it!
