### ISSUE TITLE
Does `uv venv` automatically use system-wide packages?

### ISSUE THREAD

**Issue by AVHopp** [astral-sh/uv#8805]
Hello everyone :) Unsure if this is the right place to ask, but to me it seems like creating virtual environments with `uv` always puts the system wide packages into the environment. Is this actually the case or did I mess something up locally and hence get this behavior? Thanks in advance?

**Comment by konstin** [comment]
`uv venv` does not add system wide package to the environment by default. Can you share the commands you used, your operating system and the uv version you're using?

**Comment by AVHopp** [comment]
I can try to see if I can re-create this in a MWE style, this happened in a quite convoluted setup. But I'll try my best :)

**Comment by AVHopp** [comment]
I wasn't able to recreate this behavior. I guess that I messed up with other stuff (conda environments) and that it was not a real `uv`issue. Since I cannot reproduce, I'll close this for now and re-open if I encounter this again.
