### ISSUE TITLE
can't do local pip install of whl files in requirements.txt when sys_platform is used 

### ISSUE THREAD

**Issue by hsnoil** [astral-sh/uv#8831]
When you have a local whl entry inside the requirements.txt and add `; sys_platfom ==`  to it, it fails to work.

Here is an example:

```
#uv pip install -r requirements.txt
error: Couldn't parse requirement in: `requirements.txt` at position 612
  Caused by: Expected path (./test.whl;`) to end in a supported file extension: `.whl`, `.zip`, `.tar.gz`, `.tar.bz2`...
./test.whl; sys_platfom == "win32"
^^^^^^^^
```

As you can see the `;` is for some reason included in the file type

**Comment by charliermarsh** [comment]
You need to include a space before the `;`. I believe this is compliant with the grammar.

**Comment by hsnoil** [comment]
@charliermarsh I took a quick look and from what I understand the whitespace is optional.

https://pip.pypa.io/en/stable/reference/requirement-specifiers/#requirement-specifiers

says it is based on PEP508 which says

> Non line-breaking whitespace is mostly optional with no semantic meaning. The sole exception is detecting the end of a URL requirement.

https://peps.python.org/pep-0508/#whitespace

**Comment by zanieb** [comment]
The key is "**The sole exception is detecting the end of a URL requirement.**" — paths are URLs

**Comment by charliermarsh** [comment]
Yeah it's not optional in the [grammar](https://peps.python.org/pep-0508/#complete-grammar).

**Comment by zanieb** [comment]
This is important because there can be `;` in a URI, e.g.

```
❯ touch 'foo;bar'
❯ ls
foo;bar
```

**Comment by hsnoil** [comment]
I see, I saw it more of a path than a URL as a url would be like file://, path is though a part of the url. I guess I misunderstood.

That said, the code is anyways looking for extensions like "whl", correct? So if whl; is seen as an extension, it should be possible to fix it right? And this would make it compatible with way pip does it. If not at the very least an error to explain why it doesn't work otherwise people coming from pip may just assume the issue is on uv's end.

**Comment by charliermarsh** [comment]
I thought we _did_ show a custom error here. That part I can look into. Maybe it regressed at some point.

**Comment by hsnoil** [comment]
Another question, looking at the spec to do urls you have to do:

```
test@./test.whl ; sys_platform == 'win32'
```
In the case of:
```
./test ; sys_platform == 'win32'
```
it is already not a url by the spec as the spec needs a `@` sign. Running the spec tester script in PEP508 confirms that. But it works without `@` sign on both UV and pip

I am trying to find the spec for this implementation without `@` but can't seem to find it. It is possible pip supports it because it uses a different spec for it.

**Comment by charliermarsh** [comment]
Yeah `./test ; sys_platform == 'win32'` isn't actually spec-compliant to begin with -- it's not covered by PEP 508. It's something that pip supports but AFAIK it's just implementation-defined.

**Comment by charliermarsh** [comment]
Ok it looks like we show the "right" error message for HTTPS URLs, but not file paths.

**Comment by hsnoil** [comment]
So if it isn't in the grammar to begin with and was added as pip compatibility, then it makes sense to include `./test.whl; sys_platform == 'win32'` as well, no? Especially since you are already looking for extensions like `.whl` so if the extension ends with `whl;` it can just remove the `;` and re-evaluate it. That shouldn't cause any errors of compatibility with urls that use `;`

**Comment by charliermarsh** [comment]
Candidly, I don't want to have incompatible parsing between the two URL formats. It's a source of bugs and confusion for users if the behaviors differ between the two.

**Comment by charliermarsh** [comment]
Okay, I think we can make this work. I agree it's not super intuitive right now.
