### ISSUE TITLE
Failure to use wheels

### ISSUE THREAD

**Issue by RedUndercover** [astral-sh/uv#8849]
Hi! I don't know if I'm doing anything wrong but when i try to install tiktoken==0.8.0, uv fails to grab the proper wheels.
I am running python 3.13t.

```sh
uv python pin 3.13t
uv add tiktoken==0.8.0
```
I believe it should be grabbing the same wheel the comparable pip command does. `uv pip install` also fails similarly, while `pip install tiktoken` works well enough outside of uv.

uv version:
uv 0.4.25 (97eb6ab4a 2024-10-21)

**Comment by RedUndercover** [comment]
Yeah, it's building from sources but not building completely.

[building_error.txt](https://github.com/user-attachments/files/17647013/building_error.txt)

I'll check titkoken to see if there's a way to solve this issue

**Comment by slimshreydy** [comment]
Was this ever resolved? Running into a similar issue trying to use `uv` to install `tiktoken`

**Comment by zanieb** [comment]
@slimshreydy can you open a new issue with a reproduction and verbose logs please?
