### ISSUE TITLE
Can UV minimize dependency updates when adding new dependencies, updating only to the minimum required version?

### ISSUE THREAD

**Issue by TonyYanOnFire** [astral-sh/uv#8854]
Scenario: Adding dependency foo, which requires bar >= 1.5.0. The latest version of bar is 1.9.0, but the project currently locks bar at version 1.0.0. In this case, pip will upgrade bar directly to 1.9.0. However, what i want is to upgrade bar only to 1.5.0. My goal is to minimize changes to the existing project dependencies. 

Can UV help achieve this?

**Comment by FishAlchemist** [comment]
Would setting a minimum compatible resolution resolve your issue?
https://docs.astral.sh/uv/reference/settings/#resolution

**Comment by TonyYanOnFire** [comment]
Thanks @FishAlchemist .  This feature is just what I'm looking for.
