### ISSUE TITLE
support for "uv config --list"

### ISSUE THREAD

**Issue by woutervh** [astral-sh/uv#8861]
Using uv 0.4.30

uv can be configured in several ways:

- environment variables
- .env-file
- pyproject.toml 
- ~/.config/uv/uv.toml

I find myself situations where I need to troubleshoot why uv is not seeing the correct index-url.

Currently there is no direct easy way to see which settings uv is actually seeing and where they originate from.

I wish for a "uv config --list"  to display the settings,

equivalent to git:

```
> git config --global --list
user.name=...
...
```

and poetry:
```
> poetry config --list
virtualenvs.create = true
...
```

**Comment by zanieb** [comment]
There's `uv run --show-settings` but it's not very user friendly.

**Comment by zanieb** [comment]
Going to close this in favor of https://github.com/astral-sh/uv/issues/6042

**Comment by maltevesper** [comment]
> There's `uv run --show-settings` but it's not very user friendly.

Is there a recommended way of parsing the output? It doesn't look like json or anything easily accessible through a tool like jq. It looks close to what Pydantic might give you with a data model. The `Some` in the output makes me guess it is a dump from rust?

I know that there is #6042, but in the meantime I was wondering if there is something to work with the `show-settings` output.
