### ISSUE TITLE
`uv pip install regex` reports installation success but library cannot be imported (pip works)

### ISSUE THREAD

**Issue by ssbarnea** [astral-sh/uv#8865]
Apparently MacOS specific issues:

```
uv --version
uv 0.4.30

> python3.12 -m uv pip install --force-reinstall regex
...
> python3.12 -c "import regex"
ModuleNotFoundError: No module named 'regex._regex'
```

- [ ] python3.13t broken, fail to import
- [ ] python3.13 broken, fail to import
- [ ] python3.12 broken, fail to import
- [ ] python3.11 broken, fail to import
- [ ] python3.10 works!

If the package is reinstalled using pip itself, it will work.

References: https://github.com/mrabarnett/mrab-regex/issues/547

**Comment by zanieb** [comment]
I cannot reproduce this

```
❯ uv run --python 3.12 --with regex==2024.9.11 python -c "import regex; print(regex)"
<module 'regex' from '/Users/zb/Library/Caches/uv/archive-v0/7fA06VFYeGmOUsVkY2G6i/lib/python3.12/site-packages/regex/__init__.py'>
❯ uv venv
Using CPython 3.12.7
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
❯ uv pip install regex==2024.9.11
Resolved 1 package in 3ms
Installed 1 package in 0.89ms
 + regex==2024.9.11
❯ .venv/bin/python -c "import regex"
```

**Comment by ssbarnea** [comment]
Update: while I initially suspected this to be specific to macos-arm64, it seems to no to be true as I seen the exact same error on linux with intel architectures at https://github.com/ansible/tox-ansible/actions/runs/11705926832/job/32601848111?pr=389#step:9:91

So, it can happen on both arm64 and amd64, linux and macos and multiple versions of python.

**Comment by ssbarnea** [comment]
@zanieb Thanks for the very fast reply. Apparently that failure is caused by something else. For sure is not a specific local setup issue because I was able to reproduce it on my macos and but also on the github runners.

I suspect it might be related to how python was compiled?

Using uv provided pythons seems to be working, by I am currently using asdf ones on mac and on github runners, I am not sure where github is taking the pythons from.

Any ideas about what else to invetigate?

**Comment by ssbarnea** [comment]
I was able to find that uv installs wrong binary for regex. While using py312, I found that the installed package had `_regex.cpython-310-darwin.so`... so that is why python failed to import it.

Now trying to find why this happened...

**Comment by ssbarnea** [comment]
Closing is as it seems to caused by #3883

**Comment by zanieb** [comment]
Thank you for following up!
