### ISSUE TITLE
Add support for updating dependencies in project

### ISSUE THREAD

**Issue by diachkow** [astral-sh/uv#8880]
I am looking for something similar to the [`poetry update`](https://python-poetry.org/docs/cli/#update) command that is able to update the listed dependencies to the maximum possible version that meets the requirements from the `pyproject.toml` file.

I'm now running uv version `0.4.29` and couldn't find anything like this in uv docs/uv --help.

Having this feature will make it easier to maintain long running projects and stay up-to-date with the latest package versions for our web app

**Comment by FishAlchemist** [comment]
If you're using project-specific commands, there's actually an --upgrade parameter that can update the lock file to the latest version.

**Comment by my1e5** [comment]
Duplicate of https://github.com/astral-sh/uv/issues/7681

**Comment by diachkow** [comment]
> If you're using project-specific commands, there's actually an `--upgrade` parameter that can update the lock file to the latest version.
> 
> https://docs.astral.sh/uv/concepts/projects/#upgrading-locked-package-versions

Thank you! Seems that is what I was looking for. I was trying to search by `update` through the docs, but it happened to be `upgrade` not `update` 🤦‍♂️
