### ISSUE TITLE
error: Failed to spawn

### ISSUE THREAD

**Issue by xplosionmind** [astral-sh/uv#8882]
Hi! I am trying to start a Django app, but I am having problems.

## Steps to reproduce

1. `uv init test-app`
2. `cd test-app`
3. `uv add django`
4. `uv run -- django --version || uv run django --version`

and I get:
```
error: Failed to spawn: `django`
  Caused by: No such file or directory (os error 2)
```

## Info

OS: Fedora 41  
uv version: 0.4.30

**Comment by konstin** [comment]
django does not install a runnable binary, but a module entrypoint you can access through `python -m`:
```console
$ uv run python -m django --version
5.1.3
```

**Comment by xplosionmind** [comment]
Oooh, that is wonderful. Thank you! Sorry forma the dumb question, I am a newbie 😬

**Comment by FishAlchemist** [comment]
@konstin I'm not sure which version started supporting it, but there's actually another way to do it.
![image](https://github.com/user-attachments/assets/3e02d2a4-2e15-4b14-949a-188d20bc5ad9)
```bash
uv run -m django --version
```

**Comment by FishAlchemist** [comment]
Actually, django has an executable file, but it's not called ``django``
https://docs.djangoproject.com/en/5.1/ref/django-admin/
