### ISSUE TITLE
ModuleNotFoundError: No module named 'mymodule' from jupyter notebook 

### ISSUE THREAD

**Issue by AlexAtCCRI** [astral-sh/uv#8891]
**context**: i have a project called `mymodule`  that i am using `uv` to manage. i would like to use `mymodule`'s   venv to test out some notebooks that make use of `mymodule` (but the notebooks live in a different repo). 

i can import the module from within the venv, 
`uv run  --all-extras --with jupyter -- python -c 'import mymodule'`
works. but,  i can not import the module from within a notebook (run from a jupyter server within mymodules venv)

`uv run  --all-extras --with jupyter   jupyter-lab ~/path/to/notebooks/`

then create notebook, add cell with  `import mymodule`
fails with `ModuleNotFoundError`

* on linux 
* uv 0.4.30

**Comment by AlexAtCCRI** [comment]
thanks for the reply! i have updated the issue to give more context, and description

**Comment by AlexAtCCRI** [comment]
some more context. 
`mymodule` is a python package. i would like to use  `uv`'s  venv to build/install  `mymodule`  and run some test notebooks, which live somewhere outside of `mymodule`. 

previously i would make a venv,  install `mymodule` in editable mode, and then install a whole jupyter stack in the venv,  and run the notebooks.  i was hoping i could do this faster/ligher/more reproducably with `uv` venv. 

please let me know if this still doesnt make sense?  thanks again!

**Comment by bluss** [comment]
I have tried this, and I can't reproduce it, importing a library module from the current project works.

I have the following suggestion as the next thing to test, please run this:

`uv run  --all-extras --with jupyter -- python -I -c 'import mymodule'`

`-I` for isolated would demonstrate that mymodule is really installed in the virtual environment. If that fails, it is relevant for the issue.  (When I try this command executes without problem.)

**Comment by AlexAtCCRI** [comment]
```
uv run  --all-extras --with jupyter -- python -I -c 'import mymodule'
Installed 96 packages in 61ms
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mymodule'
```
