### ISSUE TITLE
uv-pip-install: force-rebuild scikit-build-core based projects on changes to the source files?

### ISSUE THREAD

**Issue by Thibaulltt** [astral-sh/uv#8901]
Hi all, I'm using `scikit-build-core` to build a set of C++ CMake targets that then get installed in a python module local to the folder, basically like this:

```txt
project-root
- package-namespace
  | - cpp
  |   | - include/
  |   | - src/
  |   | - tests/
  |   | - CMakeLists.txt
  | - package-py
  |   | - __init__.py
  | - pyproject.toml
- ...other files...
```

And I run `uv pip install --editable .` from `package-namespace` in order to install it in a conda environment. But the changes on C++ files do _not_ get picked up when performing a `uv pip install`, even with the `--refresh` flag. Can I specify in `pyproject.toml` what files should be watched in order to invalidate uv's cache ?

**Comment by zanieb** [comment]
Did you try setting a `cache-key`? https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata

**Comment by Thibaulltt** [comment]
Ah, missed that in the documentation. Thanks! Works like a charm.
