### ISSUE TITLE
latest release fails on widonws CICD

### ISSUE THREAD

**Issue by joamatab** [astral-sh/uv#8913]
Amazing job on uv, tests run very fast now,

however last release broke our tests for windows

https://github.com/gdsfactory/gdsfactory/actions/runs/11734371332/job/32690273059

**Comment by charliermarsh** [comment]
It looks like it can't find uv? We now install to `~/.local/bin` by default and it's not on your path. Check out the release notes including the breaking change from v5: https://github.com/astral-sh/uv/releases/tag/0.5.0.

**Comment by TimChild** [comment]
Yep, that got my CI too... But a pretty quick fix as charliermarsh pointed out.

You also have the option to specify the version when you install to avoid issues in future. 
e.g. `curl -LsSf https://astral.sh/uv/0.5.0/install.sh | sh` (or 0.4.30) if you want the latest version before this change.

**Comment by hutcho** [comment]
I did a uv self update, and my windows lost the location of uv. After the update, uv wasn't a recognised command anymore.

**Comment by zanieb** [comment]
Oh awkward. Sorry this broke your CI — I presume it only worked before because the Cargo path is special-cased on their runners?

>  did a uv self update, and my windows lost the location of uv. After the update, uv wasn't a recognised command anymore.

Can you open a new issue? This one is for CI / CD. Briefly, a `uv self update` should not change the install location so I'm curious how it broke.

**Comment by TimChild** [comment]
@zanieb Yea, I had the Cargo path set in a Docker file that my CI depended on. So CI was just where I happened to notice it. Easy to fix, and now I know that I can version the install too. Thanks for the good work!

**Comment by zanieb** [comment]
Thanks for following up!
