### ISSUE TITLE
Platform-Specific Dependencies in requirements.in Not Working as Expected with `--universal`

### ISSUE THREAD

**Issue by ewianda** [astral-sh/uv#8915]
**Description**:  
When specifying platform-specific dependencies in `requirements.in` for `optimum[onnxruntime]` and `optimum[onnxruntime-gpu]`, the generated `requirements.txt` file consolidates dependencies inappropriately. Specifically, `optimum[onnxruntime-gpu]; sys_platform == 'linux'` and `optimum[onnxruntime]; sys_platform == 'darwin'` results in `optimum[onnxruntime,onnxruntime]==1.18; sys_platform == 'linux'` in the output `requirements.txt`, which causes the Darwin platform dependency to be ignored.

**Steps to Reproduce**:
1. Create a `requirements.in` file with the following lines:
    ```plaintext
    optimum[onnxruntime-gpu]; sys_platform == 'linux'
    optimum[onnxruntime]; sys_platform == 'darwin'
    ```
2. Run `uv pip compile --universal requirements.in` to generate `requirements.txt`.
3. Open the resulting `requirements.txt`.

**Expected Behavior**:
`requirements.txt` should list both platform-specific dependencies separately, like:
```plaintext
optimum[onnxruntime-gpu]==1.18; sys_platform == 'linux'
optimum[onnxruntime]==1.18; sys_platform == 'darwin'
```

**Actual Behavior**:
The generated `requirements.txt` incorrectly merges dependencies, resulting in:
```plaintext
optimum[onnxruntime,onnxruntime-gpu]==1.18; sys_platform == 'linux'
```
This line omits the macOS (Darwin) dependency entirely.

**Environment**:
- `uv` version: 0.4.30
 
- Operating System: Linux

**Comment by charliermarsh** [comment]
I can guess at what's going on here, thanks.

**Comment by charliermarsh** [comment]
I saw that, but I think it's acceptable personally.

**Comment by ewianda** [comment]
Hi @charliermarsh 

>optimum==1.23.3 ; sys_platform == 'darwin' or sys_platform == 'linux'
optimum[onnxruntime]==1.23.3 ; sys_platform == 'darwin'
optimum[onnxruntime-gpu]==1.23.3 ; sys_platform == 'linux'  


This has become an issue with our Bazel setup. It is now considered a duplicate, and Bazel fails to create a repository. Could this be addressed? 

Thanks

**Comment by charliermarsh** [comment]
@ewianda -- Do you mind filing a new issue to track it, with a repro?
