### ISSUE TITLE
uv self update to 0.5.0 loses uv

### ISSUE THREAD

**Issue by hutcho** [astral-sh/uv#8916]
After `uv self update` uv not found.
I had to reinstall uv using installation instructions to get it working again.
Windows 10. I think i was on 0.4.29 previously but could have been 1 or 2 versions before that. I update frequently and this has never happened before.

**Comment by zanieb** [comment]
It looks like a bug in the updater library we use. We're investigating. Thanks for the report!

**Comment by zanieb** [comment]
The self update should be fixed now.

The upstream issue is at https://github.com/axodotdev/axoupdater/issues/210
