### ISSUE TITLE
CI/CD pipelines on Github Actions are breaking

### ISSUE THREAD

**Issue by vfilter** [astral-sh/uv#8919]
All our pipelines on Github Actions just started breaking. We've been installing uv until now like this:
```yaml
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
```

Tried this but it also breaks:
```yaml
      - name: Set up uv
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.5.0/uv-installer.sh | sh
```

Error is this:
![image](https://github.com/user-attachments/assets/849a8779-9db8-4701-866d-079552718e07)

**Comment by fraser-langton** [comment]
same as #8917

`curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.4.30/uv-installer.sh | sh` works, but downgrading also has breaking changes to PATH 🥺

**Comment by zanieb** [comment]
It should be fixed now. Please let me know if not.
