### ISSUE TITLE
Confusion about adding new dependencies using uv add

### ISSUE THREAD

**Issue by TonyYanOnFire** [astral-sh/uv#8921]
Hello. I'm new to uv and trying to incorporate it into my existing project.

I executed the following command and got an error:
```
$uv add rdrobust==1.2.1
× No solution found when resolving dependencies for split (python_full_version >= '3.8' and python_full_version < '3.10'):
╰─▶ Because rdrobust==1.2.1 depends on scikit-learn>=1.2.0 and your project depends on rdrobust==1.2.1, we can conclude that your project depends on scikit-learn>=1.2.0.
And because your project depends on scikit-learn==1.0.2, we can conclude that your project's requirements are unsatisfiable.
help: If you want to add the package regardless of the failed resolution, provide the `--frozen` flag to skip locking and syncing.
```

I understand the reason for the error. What I am confused about is: I set `resolution = "lowest-direct"`. In such a situation that "the current foo dependency version is too low to meet the new bar dependency conditions", I expected that uv would Update the foo dependency to the minimum necessary version and update the lock file. Am I misunderstanding `uv add`? Or what should be the best practice for uv in this case?

**Comment by charliermarsh** [comment]
A difference would be if you did like... `uv add rdrobust>=1 --resolution lowest-direct`. Then we'd try to find the _lowest_ version of `rdrobust` that's greater than or equal to version 1, and still satisfies the rest of the requirements.
