### ISSUE TITLE
uv pip list --outdated does not use UV_INDEX_URL setting

### ISSUE THREAD

**Issue by jenshnielsen** [astral-sh/uv#8927]
Trying to use the new `uv pip list --outdated` feature with a custom `UV_INDEX_URL` I get an error that a random private pacakge cannot be found in the registry. Such as ```error: Package `mypackagename` was not found in the registry```

Activating verbose mode the problem seems to be that packages are not looked up in the custom registry but on pypi

```
❯ uv pip list --outdated --verbose
DEBUG uv 0.5.0 (8d665267c 2024-11-07)
DEBUG Searching for default Python interpreter in virtual environments, registry, or search path
DEBUG Found `cpython-3.12.7-windows-x86_64-none` at `somepath` (active virtual environment)
DEBUG Using Python 3.12.7 environment at .venv
DEBUG Using request timeout of 30s
DEBUG No cache entry for: https://pypi.org/simple/adlfs/
DEBUG No cache entry for: https://pypi.org/simple/aiohttp/
...
```

* A minimal code snippet that reproduces the bug. run `uv pip list --outdated --verbose` with `UV_INDEX_URL` configured to use an index different from pypi. Notice that packages are looked up on pypi.
* The command you invoked: `uv pip list --outdated --verbose`
* The current uv platform. `Windows 11`
* The current uv version (`uv --version`). uv `0.5.0`

This is similar to #8926 but I guess a separate issue.

**Comment by charliermarsh** [comment]
Thanks, that's a bug.
