### ISSUE TITLE
Pruned versions make specific uv versions unable to compile

### ISSUE THREAD

**Issue by Flamefire** [astral-sh/uv#8932]
I recently tried to recompile uv 0.2.30 (for testing) which has a dependency on reqwest-middleware and reqwest-retry:  
https://github.com/astral-sh/uv/blob/0.2.30/Cargo.lock#L3123

However that specific commit does no longer exist/is dangling: https://github.com/astral-sh/reqwest-middleware/commit/21ceec9a5fd2e8d6f71c3ea2999078fecbd13cbe

It will be removed from GitHub when the reflog expires (about 90 days IIRC)

Can you please do either of

1. avoid removing commits from repositories that are used elsewhere
2. tag such commits (e.g. as `reqwests-uv-2.x`) to avoid them from expiring
3. avoid using commits not in some branch that will not be deleted, such as `main`

Otherwise this creates headaches for maintainers of "build scripts", e.g. packages for distros, container images or us at EasyBuild (software build software for HPC)

**Comment by charliermarsh** [comment]
I don't know what happened there but in general we always tag commits that we use in VCS for this reason. It looks like an oversight by @konsti. We can tag that commit to fix this one up.

**Comment by charliermarsh** [comment]
Is there a way to get Cargo to fail when building this? Or rather, how did you even detect this?

**Comment by charliermarsh** [comment]
Thanks @konstin (https://github.com/astral-sh/reqwest-middleware/releases/tag/uv-0.2.30).

**Comment by charliermarsh** [comment]
(I think it worked for me because Konsti had already fixed it, and I didn't realize.)

**Comment by konstin** [comment]
Upstreamed this to ask for crates.io releases: https://github.com/TrueLayer/reqwest-middleware/pull/198

I've also tagged the version we're using in uv 0.5.0 in the meantime.
