### ISSUE TITLE
Should `uv` graduate from 'beta' on PyPI?

### ISSUE THREAD

**Issue by paveldikov** [astral-sh/uv#8941]
The release announcement for 0.5.0 alludes to `uv`'s increasing maturity; maybe the time is now?

Cf. `ruff` already having been classified as `5 - Production/Stable` for quite some time now.

IME it's not a big issue, but it does on occasion raise some eyebrows: _'is it appropriate to cast our lot with a package that is marked as beta?'_

**Comment by charliermarsh** [comment]
Good call -- done in the next release!
