### ISSUE TITLE
Difference in package versions between uv lock and uv pip compile

### ISSUE THREAD

**Issue by vangelem** [astral-sh/uv#8945]
Hello uv team,

We've been trying to implement lock files in our projects but got stopped many times due to the slowness of the available tools until we found uv, that is a very brilliant and promising app :-)
However, I'm facing a strange behaviour while evaluating the `uv lock` command, and I'm not sure whether it's an actual bug or due to my lack of understanding of what the command is meant to do.

When using `uv lock`, it looks like it is resolving the wrong version for some dependencies, as in the MRE below. We're on Windows 10 with python 3.9.13 and uv 0.5.0.

```
# pyproject.toml
[project]
name = "eval_uv"
requires-python = "~=3.9"
version = "1.0.0"
dependencies = [
    "nidaqmx",
    "numpy<1.25",
    "pandas",
]
```

Installing using `pip install .`, `uv pip install .` or via `uv pip compile` (as below) all lead to the same list of installed versions:
`uv venv`
`uv pip compile pyproject.toml -o requirements.txt`
`uv pip install -r requirements.txt`

```
Resolved 19 packages in 1.36s
Installed 19 packages in 6.58s
 + certifi==2024.8.30
 + charset-normalizer==3.4.0
 + click==8.1.7
 + colorama==0.4.6
 + deprecation==2.1.0
 + hightime==0.2.2
 + idna==3.10
 + nidaqmx==1.0.1
 + numpy==1.24.4
 + packaging==24.2
 + pandas==2.2.3
 + python-dateutil==2.9.0.post0
 + python-decouple==3.8
 + pytz==2024.2
 + requests==2.32.3
 + six==1.16.0
 + tzdata==2024.2
 + tzlocal==5.2
 + urllib3==2.2.3
```

However, `uv lock` / `uv sync` installs pretty much the same versions, except for a few exceptions as for `pandas`, here in `2.1.0` as opposed to `2.2.3` in the previous case.
`uv venv`
`uv lock`
`uv sync --frozen`

```
Prepared 19 packages in 13ms
Installed 19 packages in 6.68s
 + certifi==2024.8.30
 + charset-normalizer==3.4.0
 + click==8.1.7
 + colorama==0.4.6
 + deprecation==2.1.0
 + hightime==0.2.2
 + idna==3.10
 + nidaqmx==1.0.1
 + numpy==1.24.4
 + packaging==24.2
 + pandas==2.1.0
 + python-dateutil==2.9.0.post0
 + python-decouple==3.8
 + pytz==2024.2
 + requests==2.32.3
 + six==1.16.0
 + tzdata==2024.2
 + tzlocal==5.2
 + urllib3==2.2.3
```

I'd thought that `uv lock` followed by `uv sync` would produce the same result as a `pip install` approach but it not always does. Is this a bug then? Or something correct according to the lock file philosophy?

Thanks!
Matt

**Comment by zanieb** [comment]
Have you read about the differences between universal and platform specific resolution? https://docs.astral.sh/uv/concepts/resolution/#universal-resolution

**Comment by zanieb** [comment]
Well, you can use the `--universal` flag in `uv pip compile` to get a universal resolution or define a [limited set of environments](https://docs.astral.sh/uv/concepts/projects/#limited-resolution-environments) for your project to perform resolution for less platforms in `uv.lock`. It's more of a question of if you want to manually manage your environments (via `uv pip`) or have it be automated with the top-level interface.

I'd basically only use `uv pip compile` without the `--universal` flag if you are targeting a single platform.

**Comment by charliermarsh** [comment]
(Closing as this looks answered but happy to take any follow-up questions.)
