### ISSUE TITLE
Uv fails to activate environment in folder with apostrophe

### ISSUE THREAD

**Issue by mak448a** [astral-sh/uv#8947]
I tried these commands in a folder with an apostrophe and a space.
```shell
uv venv
source .venv/bin/activate
```
Version: 0.4.25
Installation Method: Dnf package 
OS: Fedora Linux 41 KDE Spin

**Comment by konstin** [comment]
What operating system are you on, and what's the name of the folder verbatim?

**Comment by mak448a** [comment]
Fedora Linux 41. `Testing's test`. I think it's the apostrophe.

**Comment by konstin** [comment]
Documenting the background on shell escaping:

We want our `activate` script to support basically any posix shell. There's two kind of quotes: Single and double quotes. In bash, single quotes must not contain another single quote, you can't even escape it (https://linux.die.net/man/1/bash under "QUOTING"). Double quotes have escaping rules different from shell to shell, which we can't do. bash has `$'\''`, but that's not universal enough.

As a workaround, we can go through printf:

```
VIRTUAL_ENV=$(printf '/home/konsti/projects/uv/Testing\047s/.venv')
```

**Comment by bluss** [comment]
You could maybe use what shlex suggests (python stdlib shlex), both `''` and `""` strings.

```python
print(shlex.quote("/home/Testing's/.venv"))
'/home/Testing'"'"'s/.venv'
```
