### ISSUE TITLE
VS Code not detecting uv installed python 3.13.0

### ISSUE THREAD

**Issue by kb-cov** [astral-sh/uv#8964]
I have been using uv for months without issue on a MAC both in terminal and VS Code.  I uninstalled uv version 0.4.30 by following uninstall instructions and removing all uv related content from my .zshrc file.  I re-installed uv version 0.5.0 and have since updated to 0.5.1 therefore moving the uv and uvx binaries to the .local/bin directory and `export PATH="/Users/kevban/.local/bin:$PATH"` has been added to my .zshrc file.  I have confirmed that .local/bin is in my PATH.  Since doing this I have re-installed both python 3.13.0 and python 3.12.7 using uv however neither Python install shows up in the VSCode interpreter selection menu.  If I create a venv using uv with 3.13 then it works fine and the venv shows in interpreter list but the basic python interpreter itself is not.  I'm sure I'm doing something obviously wrong here but would be great if you could point me in the right direction.  Thanks.

**Comment by charliermarsh** [comment]
Unfortunately not immediately obvious to me how / why this would be different in 0.5. We moved the location of uv itself, but _not_ the uv-installed Pythons -- they should be in the same place as before?

**Comment by kb-cov** [comment]
so the uv-installed pythons are in ~/.local/share/uv/python/ is his what you would expect?   if I manually enter is as interpreter path in VS code then it works fine....but for some reason no uv python installs are appearing in the drop down interpreter selection by default....its listing system and brew python versions, but nothing from uv ?  Maybe a VS code glitch I guess...

**Comment by zanieb** [comment]
Yeah that's where we'd expect the Python interpreters to be stored — they're been there for a long time.

You might want to try `uv python install --preview` which will put versions on your `PATH` and presumably make them discoverable by VSCode? It's still a work in progress though.
