### ISSUE TITLE
UV Environment Management Tool Confuses Package Paths Across Environments

### ISSUE THREAD

**Issue by jo-pillar** [astral-sh/uv#8965]
**Description**

I encountered an issue with the UV environment management tool when working with local Python packages.

**Steps to Reproduce:**
1. Create two separate project folders, `A` and `B`, on the same system, both containing the same local Python package.
2. Register two different environments, e.g., `env-A` and `env-B`, using the same Python version.
3. Make changes to the package code in folder `B`, then run `pip install .` to update the package in the `env-B` environment.
4. The changes do not take effect, and the old version of the package is still used.

**Observed Behavior:**
- UV mistakenly identifies the package installed in folder `A` as the package for folder `B`.
- Changes made in folder `B` are not applied correctly.

**Expected Behavior:**
- The `env-B` environment should correctly identify and use the package installed from folder `B`.

**Environment Details:**
- Operating System: Ubuntu20.04
- Python Version: 3.12.7
- UV Version: 0.5.0

**Possible Cause:**
- UV may not be properly isolating environments when using the same Python version, leading to path conflicts.

**Suggested Fix:**
- Investigate the path isolation mechanism for environments in UV.
- Implement stricter handling of package paths to ensure no cross-environment confusion occurs.

**Additional Information:**
Please let me know if additional logs or example files are needed to reproduce this issue.

**Comment by charliermarsh** [comment]
Can you please provide a more complete reproduction? Like a series of commands I can run to reproduce? (I think what you're describing is almost certainly not what's happening -- we definitely don't mix environments like that, maybe you still have the previous environment activated or something? -- but I'd like to help you figure out your workflow.)

**Comment by jo-pillar** [comment]
I have found another question but maybe the same reason.
```bash
mkdir uv-test
cd uv-test/
mkdir mypackage
cd mypackage/
git clone https://github.com/navdeep-G/setup.py # a very simple project can use pip install .
cd setup.py
uv venv --python 3.12
source .venv/bin/activate
uv pip install .
python -c "import mypackage as mp" # no output
echo "print(\"mychange\") > mypackage/core.py   # make some change
uv pip install .
python -c "import mypackage as mp"  #  mychange printed
cd ~ # back to home
python -c "import mypackage as mp"  # Try again, but no output!!!
```

**Comment by FishAlchemist** [comment]
Respond to https://github.com/astral-sh/uv/issues/8965#issuecomment-2466597230.
@jo-pillar The reason you could successfully run it within the setup.py directory is that you imported the mypackage module (folder) from the current working directory. Therefore, whether you installed it or not, it could function.

Unlike ``pip install``, ``uv pip install`` doesn't reinstall packages every time it runs. I think that uv seems that as long as setup.py remains unchanged, uv won't choose to reinstall packages.

**Comment by jo-pillar** [comment]
It behaves differently from `pip install .`, which can be both frustrating and confusing. I think it should be fixed, but it's up to you.

**Comment by charliermarsh** [comment]
It’s an intentional difference. If you’re modifying a package, you should likely update the version. If you’re developing, you’re probably looking for an editable install which updates alongside the source without a need to re-install.

**Comment by FishAlchemist** [comment]
> It’s an intentional difference. If you’re modifying a package, you should likely update the version. If you’re developing, you’re probably looking for an editable install which updates alongside the source without a need to re-install.

@charliermarsh Have you considered adding this to https://docs.astral.sh/uv/pip/compatibility/#pip-compile-defaults?
