### ISSUE TITLE
`--no-system` flag does not appear on the latest CLI help

### ISSUE THREAD

**Issue by pesap** [astral-sh/uv#9035]
I was reading through the documentation of `uv pip install`  and found the `--no-system` flag [here](https://docs.astral.sh/uv/guides/integration/github/#using-uv-pip). However, the latest `uv` CLI help (from `uv pip install` does not appear to list it or describe it. Only `--system` appears on the help.  I think it would nice to include it to the CLI help. Any thoughts?

### My UV version 

uv 0.5.1 (f399a5271 2024-11-08)

**Comment by charliermarsh** [comment]
We generally have negation flags with `--no-` for each boolean, but adding them to the CLI help would be too verbose.

**Comment by pesap** [comment]
Totally agree it would be to verbose to add the description for each boolean. I was wondering the rationale, since this flag does exist on CLI help of `uv pip tree`. Anywho, thanks for the amazing tool!

**Comment by charliermarsh** [comment]
Ohh that might be a mistake on `uv pip tree`! Thanks!
