### ISSUE TITLE
`uv python install` gives `error: Could not acquire lock for '.local/share/uv/python' at '.local/share/uv/python/.lock': Function not implemented (os error 38)`

### ISSUE THREAD

**Issue by maximilianigl** [astral-sh/uv#9050]
When running `uv python install`, I get the error 
```
error: Could not acquire lock for `.local/share/uv/python` at `.local/share/uv/python/.lock`: Function not implemented (os error 38)
```

It's on a linux cluster node (running Slurm), so the home directory is shared across nodes.
`uv` version is 0.5.1

**Comment by zanieb** [comment]
Does your system not support [`flock`](https://linux.die.net/man/2/flock)? We need to be able to take locks to prevent concurrent access to state.

**Comment by maximilianigl** [comment]
Thanks for the prompt response! 
I didn't realize it was related to `flock`. They recently (temporarily?) disabled it.
I'll close the issue as this is a problem on our system.

**Comment by gashon** [comment]
I was able to move .lock location w `export UV_CACHE_DIR=/tmp/uv_cache`

**Comment by mil-ad** [comment]
@zanieb does this mean that it's safe to call `uv sync` concurrently from multiple processes if the filesystem supports flock?

And apologies for commenting on a closed thread.

**Comment by zanieb** [comment]
Yes we lock environments for safe concurrency.

**Comment by mil-ad** [comment]
Amazing! I think flock doesn't work on NFS but [fcntl](https://man7.org/linux/man-pages/man2/fcntl.2.html) does, at least for more recent versions of NFS and linux kernel
