### ISSUE TITLE
Uv recognise my ubuntu as windows

### ISSUE THREAD

**Issue by sharmas1ddharth** [astral-sh/uv#9051]
❯ uv run main.py
warning: `VIRTUAL_ENV=/home/siddharth/uv_envs/wms_invoice_ocr` does not match the project environment path `.venv` and will be ignored
  x No solution found when resolving dependencies for split (python_full_version == '3.11.*' and platform_system == 'Windows' and sys_platform == 'darwin'):
  `-> Because there is no version of torch==2.3.0+cu121 and your project depends on torch==2.3.0+cu121, we can conclude that your project's requirements are unsatisfiable.
  
platform: ubuntu
uv version = uv 0.4.16

**Comment by FishAlchemist** [comment]
I think you've got it wrong. This is because uv run by default checks if the lock file is up-to-date. The lock file is used to find cross-platform compatible dependencies that meet your requirements.

**Comment by konstin** [comment]
If your project does only support linux, you can set [`tool.uv.environments`](https://docs.astral.sh/uv/reference/settings/#environments) to e.g. exclude windows.

On uv's side, we shouldn't try resolving `(python_full_version == '3.11.*' and platform_system == 'Windows' and sys_platform == 'darwin')`: `platform_system == 'Windows' and sys_platform == 'darwin'` doesn't exist, and we shouldn't consider it.
