### ISSUE TITLE
Retaining Default Registry in `uv.lock` While Using PyPI Mirror

### ISSUE THREAD

**Issue by liblaf** [astral-sh/uv#9053]
I understand that the current behavior is **NOT** a bug but **BY DESIGN**.

#### Description

I am using `uv` to manage my Python project and have configured it to use a PyPI mirror for faster downloads. However, I have encountered an issue where the `uv.lock` file records the index configuration of the mirror, which is not ideal for CI/CD environments or for collaborators who do not use the same mirror.

#### Configuration

I have set up my `~/.config/uv/uv.toml` to use the PyPI mirror as follows:

```toml
index-url = "https://mirrors.cernet.edu.cn/pypi/web/simple"

[pip]
index-url = "https://mirrors.cernet.edu.cn/pypi/web/simple"
```

#### Problem

When `uv` generates the `uv.lock` file, it includes the mirror's URL in the `source` field for each package, as shown below:

```toml
[[package]]
name = "attrs"
version = "24.2.0"
source = { registry = "https://mirrors.cernet.edu.cn/pypi/web/simple" }
sdist = { url = "https://mirrors4.tuna.tsinghua.edu.cn/pypi/web/packages/fc/0f/aafca9af9315aee06a89ffde799a10a582fe8de76c563ee80bbcdc08b3fb/attrs-24.2.0.tar.gz", hash = "sha256:5cfb1b9148b5b086569baec03f20d7b6bf3bcacc9a42bebf87ffaaca362f6346", size = 792678 }
wheels = [
    { url = "https://mirrors4.tuna.tsinghua.edu.cn/pypi/web/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl", hash = "sha256:81921eb96de3191c8258c199618104dd27ac608d9366f5e35d011eae1867ede2", size = 63001 },
]
```

#### Expected Behavior

I would like the `uv.lock` file to retain the default PyPI registry URL (`https://pypi.org/simple`) instead of the mirror URL, while still allowing me to use the mirror for faster downloads. The expected `uv.lock` content should look like this:

```toml
[[package]]
name = "attrs"
version = "24.2.0"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/packages/fc/0f/aafca9af9315aee06a89ffde799a10a582fe8de76c563ee80bbcdc08b3fb/attrs-24.2.0.tar.gz", hash = "sha256:5cfb1b9148b5b086569baec03f20d7b6bf3bcacc9a42bebf87ffaaca362f6346", size = 792678 }
wheels = [
    { url = "https://files.pythonhosted.org/packages/6a/21/5b6702a7f963e95456c0de2d495f67bf5fd62840ac655dc451586d23d39a/attrs-24.2.0-py3-none-any.whl", hash = "sha256:81921eb96de3191c8258c199618104dd27ac608d9366f5e35d011eae1867ede2", size = 63001 },
]
```

#### Additional Information

- `uv --version`: `uv 0.5.1 (f399a5271 2024-11-08)`
- The content on the PyPI mirror is the same as the original PyPI.

#### Request

Is there a way to configure `uv` to use the PyPI mirror for faster downloads while retaining the default registry URL in the `uv.lock` file? This would be beneficial for maintaining consistency across different environments and for collaborators who may not use the same mirror.

**Comment by FishAlchemist** [comment]
Based on your needs, instead of setting index-url to a mirrored PyPI, you should expect uv to search for PyPI packages from a mirrored PyPI, right?
If I've understood your requirements correctly, this should be a better solution. There seems to be a related issue regarding this approach.

**Comment by liblaf** [comment]
@FishAlchemist

> Based on your needs, you should expect uv to search for PyPI packages from a mirrored PyPI, right?

Yes, and uv does indeed search for packages from the mirror. However, I would like the `uv.lock` file to record the default PyPI URL (<https://pypi.org>) instead of the mirror I am using.

> If I've understood your requirements correctly, this should be a better solution.

By "this," do you mean the solution I mentioned using `sd` to replace the URLs in `uv.lock` after each update?

> There seems to be a related issue regarding this approach.

I have searched for related issues and found [#8828](https://github.com/astral-sh/uv/issues/8828). However, this issue does not mention that the `uv.lock` file still records the PyPI mirror.

**Comment by liblaf** [comment]
Let me clarify a bit:

1. I want to search for packages from a PyPI mirror for faster download speeds.
2. I wish to retain the default PyPI URL (<https://pypi.org>) in the `uv.lock` file for consistency across different environments.

Based on my understanding of uv's configurable options, I currently cannot achieve both of these points at the same time without introducing additional steps.

I would like to ask:

1. Is there a way to configure uv's settings to meet both of my requirements within the existing uv framework?
2. If not, could we implement an additional feature, such as adding a `mirror` option in `uv.toml`, to support this?

**Comment by FishAlchemist** [comment]
@liblaf 
Actually, what I mean is, based on your expectation, UV should support fetching packages from the mirrored PyPI. In other words, when the expected source is PyPI, it should look for the package in the mirrored PyPI instead.

If I'm not mistaken, UV doesn't seem to have this feature yet.
Perhaps you can open an issue requesting that project APIs support mirror PyPI?
Or we could wait for the UV team to respond to the issue, as they will be the ones to decide whether to support this feature.

**Comment by liblaf** [comment]
@FishAlchemist Thanks! I am opening a feature request to support configuration of mirrors.

**Comment by liblaf** [comment]
Closing in favor of [#9056](https://github.com/astral-sh/uv/issues/9056)

**Comment by liblaf** [comment]
Closing in favor of [#9056](https://github.com/astral-sh/uv/issues/9056)
