### ISSUE TITLE
`ENV UV_SYSTEM_PYTHON=1` still creates `.venv` and dependencies aren't able to be found

### ISSUE THREAD

**Issue by theelderbeever** [astral-sh/uv#9067]
I am building inside of a docker container and am setting `ENV UV_SYSTEM_PYTHON=1` prior to ever running `uv sync`. However, despite setting this per the documentation a `.venv` directory is still created and packages are installed there. This result in none of my python dependencies being found by the environment. How can I force `uv` to not create a `venv`? 

```
uv 0.5.1
ubuntu 18.04 devcontainer
```

**Comment by charliermarsh** [comment]
`UV_SYSTEM_PYTHON` doesn't affect the project interface (`uv sync`, `uv lock`, `uv add`, etc.).

See: https://docs.astral.sh/uv/concepts/projects/#configuring-the-project-environment-path.

**Comment by theelderbeever** [comment]
> `uv sync` will remove extraneous packages from the environment by default and, as such, may leave the system in a broken state.

Yikes.... So when using `ENV UV_SYSTEM_PYTHON=1` is the "correct"/"only" way to install to the system packages without removing whats there to use the following? I know its bad practice to not use a venv but this project has some strange limitations unfortunately.

```
COPY pyproject.toml .
RUN uv pip install -r pyproject.toml
COPY . .
RUN uv pip install -e .
```

**Comment by zanieb** [comment]
I would use `uv export` and `uv pip install` so you get the locked versions.

**Comment by theelderbeever** [comment]
Thank you @zanieb

**Comment by thclark** [comment]
To use the system python environment in a `devcontainer`, I use:
```
# Use system python and dependencies
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
```
