### ISSUE TITLE
`uv pip install` fails to install package while `pip install` succeeds

### ISSUE THREAD

**Issue by arpitg-sh** [astral-sh/uv#9078]
**Description:** I'm encountering an issue when using uv pip to install Python packages. Specifically, the build process for jsmin==2.2.2 fails, while doing the same with native pip passes.

**Steps to Reproduce**

Using uv:

```
uv pip install setuptools
uv pip install azure-cli
```
This results in a failure:
```
9.923   × Failed to download and build `jsmin==2.2.2`
9.923   ╰─▶ Build backend failed to determine requirements with `build_wheel()`
9.923       (exit status: 1)
9.923
9.923       [stderr]
9.923       /root/.cache/uv/builds-v0/.tmpdkIMOq/lib/python3.9/site-packages/setuptools/_distutils/dist.py:261:        
9.923       UserWarning: Unknown distribution option: 'test_suite'
9.923         warnings.warn(msg)
9.923       error in jsmin setup command: `use_2to3` is invalid.
```
Using regular pip(v24.0):

```
pip install setuptools
pip install azure-cli
```
This works successfully without errors.
Additional Information
```
uv Platform: "Debian GNU/Linux 10 (buster)"
uv Version: uv 0.5.1
```

**Comment by dimbleby** [comment]
You will want to allow prereleases when adding azure-cli

**Comment by charliermarsh** [comment]
Yeah adding `--pre` seems to get this to work. I think this is correct as-is -- without `--pre`, we end up trying to build a dependency but failing.

**Comment by charliermarsh** [comment]
Actually, I think this is failing during pre-fetching, maybe? I have a separate solution to this, so I'll leave it open.

**Comment by dimbleby** [comment]
It's failing because when pre-releases are disallowed, uv searches way back to old versions of azure-cli that no-one should want. 

I think it's understood (by those who know!) that uv takes a different view of pre-releases than other installers, and different also than the specs. Of course there are reasons, but this is an example of the downsides.

**Comment by charliermarsh** [comment]
Yeah -- I generally agree. The thing I noticed in this specific case though is that we don't actually seem to ever consider `jsmin`, we just "pre-fetch" it when looking at certain `azure-cli` versions. So we should be able to delay the error here such that the resolution still succeeds.

**Comment by arpitg-sh** [comment]
@charliermarsh Do you know when will this be released?
