### ISSUE TITLE
uv python install 3.12 -> but no python at command line

### ISSUE THREAD

**Issue by pitosalas** [astral-sh/uv#9090]
I am trying to go all uv. I uninstalled python from home-brew so that all I have now is the default python that came with my Mac. It's an old one. So next I did:

$ uv python install 3.12

Which worked without error. But I want 3.12 to be the python I get at a bare shell, even without having created an environment or whatever the equivalent is with uv. I want it to work like pyenv.

Is that possible?

**Comment by zanieb** [comment]
Please see https://github.com/astral-sh/uv/issues/6265

**Comment by charliermarsh** [comment]
(Thanks for the enthusiasm! Happy to answer more questions but feel free to track the behavior you're looking for in #6265.)
