### ISSUE TITLE
Unable to configure basic HTTP auth via env for `UV_DEFAULT_INDEX`

### ISSUE THREAD

**Issue by qbedard** [astral-sh/uv#9104]
It looks like there's no way to configure the default index authentication via environment variables without incorporating it into the index URL itself. This gets a bit tricky when you need to set a rotating password separately from the URL (such as for CodeArtifact). The current hack is to do some string manipulation to jam the password into the URL when publishing, but it would be really nice to avoid that.

It would seem easy enough to add `UV_DEFAULT_INDEX_USERNAME` and `UV_DEFAULT_INDEX_PASSWORD` as available environment variables.

That wouldn't help with using multiple indexes via `UV_INDEX`, but maybe that's fine.

**Comment by charliermarsh** [comment]
I believe this is possible today? E.g., if you do:

```toml
[[tool.uv.index]]
default = true
name = "internal"
url = "..."
```

Then `UV_INDEX_INTERNAL_USERNAME` and `UV_INDEX_INTERNAL_PASSWORD` will be respected.

**Comment by zanieb** [comment]
I think the problem is if you change the default index via environment variable instead of defining it in a configuration file.

**Comment by charliermarsh** [comment]
Why is that? I think `UV_DEFAULT_INDEX=internal=https://` would work as above?

**Comment by zanieb** [comment]
Oh, well that answers the question I think :) I didn't realize you could use that syntax, but it makes sense.

**Comment by qbedard** [comment]
> Why is that? I think `UV_DEFAULT_INDEX=internal=https://` would work as above?

Oh, that’s interesting. Is that syntax documented somewhere?

**Comment by charliermarsh** [comment]
I guess not? I thought it was but can't find it. I'll add something.

**Comment by qbedard** [comment]
Thanks!
