### ISSUE TITLE
`pip list` in activated venv differs from `uv pip list`

### ISSUE THREAD

**Issue by nataziel** [astral-sh/uv#9111]
This may be working as intended but is extremely confusing.

I understand that `uv` creates a virtual environment called `.venv` by default when first adding requirements to a project, or running `uv sync` or `uv venv` etc.

If you are in the project folder but don't have the venv activated, when you run the command `uv pip list` it will list the packages installed in that venv, but running `pip list` will list the packages in your base environment. This makes sense.

By extension, say I have `pytest` installed in the venv, but not my base python installation, if I run `pytest`, pytest won't be on $PATH and the command will fail. If I run `uv run pytest` it works as expected, again this makes sense.

When you activate that venv by running `source .venv/Scripts/activate`, you can now run `pytest` and it will work, which again matches my expectations. 

However, if you run `pip list` with the venv activated it will list the packages installed in your base python installation, not the activated venv. If you had created the venv via `python -m venv .venv`, and activated it exactly the same way, `pip list` would list the packages in the activated venv, not the base python installation. This creates a very confusing situation where `pip list` and `uv pip list` don't agree on what packages are available.

What I think it all boils down to is the presence of `pip` in the venv.

Some experimentation has found that this doesn't happen if you create the venv with `python -m venv .venv`, then use `uv sync` to install the project packages (`pip` is available within the activated venv!). This only works if the python version specified in `pyproject.toml` and `.python-version` match the base python installation. 

If they don't match, `uv` destroys the existing `.venv/` directory and creates a new one. The venv created by `uv` doesn't have `pip`, so if you run `pip list` it uses the `pip` from the base environment. Therefore, it lists different packages to the what is listed by `uv pip list`

Is this expected behaviour? If it is, is there a way it can be made less confusing? Even just showing a warning that the listed packages refer to a different environment than the activated venv would make this way more clear.

**Comment by charliermarsh** [comment]
All expected. We don't include pip in the virtual environment, so running `pip list` is calling the pip installed on your system.

**Comment by nataziel** [comment]
Ok yep understood. Is there a way you could intercept the call to `pip` and print a warning of that surprising behaviour?
