### ISSUE TITLE
Q: how to run `python -m build` with uvx?

### ISSUE THREAD

**Issue by dimaqq** [astral-sh/uv#9114]
I just can't figure it out.

I was going to use `pip install build; python -m build` as a stepping stone towards converting the project to uv... so I figured I'd `uvx` it, and can't figure out the syntax... if it's possible at all.

**Comment by charliermarsh** [comment]
Yeah, it's `uvx --from build pyproject-build`.

**Comment by charliermarsh** [comment]
If you run `uvx build`, it should point you to that:

```
❯ uvx build
Installed 3 packages in 7ms
The executable `build` was not found.
warning: An executable named `build` is not provided by package `build`.
The following executables are provided by `build`:
- pyproject-build
Consider using `uvx --from build <EXECUTABLE_NAME>` instead.
```

(The extra `--from` is necessary because `build` names its executable `pyproject-build`, not `build`.)

**Comment by dimaqq** [comment]
Ahh it doesn't I must've had a brain freeze and couldn't substitute EXECUTABLE_NAME correctly!
