### ISSUE TITLE
Question: Possible to get interactive output from stdout/stderr?

### ISSUE THREAD

**Issue by robinjhuang** [astral-sh/uv#9129]
I am using uv to install a python environment in an Electron application.

Command: 
```
uv venv  --python 3.12.4
uv pip install -r requirements.txt
```

I notice that when I run this in a `ChildProcess` in node, the interactive output like progress bars and download progress are not shown. I tried adding the `FORCE_COLOR=1` environment variable, and `--verbose` but that didn't work. 

```node
const childProcess = spawn('path/to/uv.exe', ['--color',  'always', '--verbose', 'pip', 'install', '-r', this.requirementsPath], {
    cwd: this.venvRootPath,
    env: {
      ...process.env,
     VIRTUAL_ENV: this.venvPath,
     FORCE_COLOR: '1'
    },
    shell: true,
    stdio: ['inherit', 'pipe', 'pipe']
  });

childProcess.stdout?.on('data', (data) => {
    console.log(data.toString());
});

childProcess.stderr?.on('data', (data) => {
    console.log(data.toString());
});
```

My issue is mostly that I don't get any indication of progress until everything is downloaded:
```bash
Resolved 64 packages in 760ms
```
After 35s this appears:
```bash
Prepared 64 packages in 35.11s

Installed 64 packages in 1.75s
 + aiohappyeyeballs==2.4.3
 + aiohttp==3.11.1
 + aiosignal==1.3.1
 + attrs==
 ...
```

**Comment by zanieb** [comment]
Not feasible, and it looks like it'd be hard as it's not supported upstream(?) https://github.com/console-rs/indicatif/issues/87

**Comment by robinjhuang** [comment]
Thanks for letting me know! I will try streaming it with node-pty as a workaround.
