### ISSUE TITLE
[Question] How should one install dev dependencies declared in pyproject.toml [dependency-groups]

### ISSUE THREAD

**Issue by TonyYanOnFire** [astral-sh/uv#9140]
Hi.

I'm trying to introduce uv into my project. I did the following things to simulate the scenario of installing development dependencies when other members switch to using uv:
1. uv add --dev pycowsay
2. uv pip uninstall pycowsay
At this point, `pyproject.toml` has:
```
[dependency-groups]
dev = [
"pycowsay>=0.0.0.1",
]
```
But `pycowsay` is not installed in the environment, just like what other members may encounter.
At this time, if you run `uv pip install -r pyproject.toml`, `pycowsay` will not be installed.
Trying to add `--extra dev` results in an error:
```
$ uv pip install -r pyproject.toml --extra dev
error: Requested extra not found: dev
```

How can I achieve my goal?  Or am I trying to solve the wrong problem?

**Comment by charliermarsh** [comment]
See also: https://github.com/astral-sh/uv/issues/8590
