### ISSUE TITLE
Feature request: add --no-deps support for TOML head dependencies section

### ISSUE THREAD

**Issue by shelper** [astral-sh/uv#9141]
I am using uv 0.5.2, 
i am trying to run a script with head of something like:
```
# /// script
# requires-python = ">=3.8,<3.9"
# dependencies = [
# "onnx",
# "onnxruntime",
# "numpy",
# "openvino2tensorflow==1.34.0",
# "tensorflow-datasets==4.9.1",
# "protobuf==3.20.3",
# "openvino==2021.4.2 --no-deps",
# ]
# ///
```

what i am looking for is a way to  override uv to install certain packages with option --no-deps so it ignores the conflicts as needed.

**Comment by charliermarsh** [comment]
We might need to support overrides and constraints in PEP 723 scripts.
