### ISSUE TITLE
sync does not pull latest commit from github dependency

### ISSUE THREAD

**Issue by fccoelho** [astral-sh/uv#9146]
I have a dependency on one of my projects, which is based on GitHub.

When I used Poetry, the `poetry update` command would always pull the latest commit in the repo of the dependency. 
That allowed my project to be in sync with the very latest changes in the main branch of the dependency.

`uv sync` does not do that by default. apparently it pulls the latest release or tag, I am not sure.

Is there some flag or option to change this default behavior to match that of poetry?

**Comment by FishAlchemist** [comment]
``uv sync``: Syncing ensures that all project dependencies are installed and up-to-date with the lockfile.
Therefore, you need to relock your dependencies. You can do this using ``uv lock --upgrade``. If you want to specify a package to upgrade, use ``--upgrade-package <package>``
https://docs.astral.sh/uv/concepts/projects/#upgrading-locked-package-versions

**Comment by charliermarsh** [comment]
Yeah you want `uv lock --upgrade` or `uv lock --upgrade package <package>`, as @FishAlchemist said.

**Comment by charliermarsh** [comment]
I'm not sure that that's true. Is it possible that it just worked on first `uv sync`, when you added it?

**Comment by fccoelho** [comment]
> I'm not sure that that's true. Is it possible that it just worked on first `uv sync`, when you added it?

Yes, you're right. It worked before because I had also created a new tag in the dependency repo. So `uv sync` automatically upgraded to it. Now I tested without adding a new tag, after a new commit, and it didn't upgrade. 

The `uv lock --upgrade-package <package name>` worked as expected, though.

**Comment by charliermarsh** [comment]
I think this _is_ working as expected then.
