### ISSUE TITLE
auto completion didn't work with zsh and oh my zsh

### ISSUE THREAD

**Issue by amirreza8002** [astral-sh/uv#9158]
running 
`echo 'eval "$(uv generate-shell-completion zsh)"' >> ~/.zshrc`
did not start auto-completion
this was done weeks ago and never once worked

what i have done now, is 
```
cd $ZSH_CUSTOM/plugins
touch uv.plugin.zsh
uv generate-shell-completion zsh >> uv.plugin.zsh
```
and then adding `uv` to `plugin` section of `.zshrc`

but i think something like [poetry](https://python-poetry.org/docs/#oh-my-zsh)'s way should be implemented

let me know what you think

**Comment by toyourheart163** [comment]
step 1

```bash
uv generate-shell-completion zsh >> ~/.zshrc
```

step 2

```bash
exec zsh
```

**Comment by amirreza8002** [comment]
> mkdir uv && cd uv  # add this line

well actualy it's not necessery
i'm not even sure if it should be there, haven't tested, i went with the way that omz maintainer had written

also you need to add `uv` to `.zshrc`'s `plugin` section

**Comment by toyourheart163** [comment]
you are right. don't need to `mkdir uv`

but `echo 'eval "$(uv generate-shell-completion zsh)"' >> ~/.zshrc` work for me.

> Maybe you should show `your ~/.zshrc`

### my zsh version

```bash
zsh --version zsh 5.9 (aarch64-unknown-linux-android) 
```

### my `~/.zshrc`

```bash
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ys"
plugins=(git
    aliases
    history
    zsh-completions
    zsh-syntax-highlighting
    zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
eval "$(uv generate-shell-completion zsh)"
```

**Comment by amirreza8002** [comment]
zsh is installed via pacman and is at latest version
OMZ auto updates and is at latest version

running `echo 'eval "$(uv generate-shell-completion zsh)"' >> ~/.zshrc` did not work for me

`uv generate-shell-completion zsh >> ~/.zshrc` did work, but it added too many lines to my file
so i did what i described

**Comment by samypr100** [comment]
To clarify, is the issue with stock zsh or only with zsh + omz enabled? It sounds like it's omz related only, but I might be wrong.

Does stock zsh not work with the [documented](https://docs.astral.sh/uv/getting-started/installation/#shell-autocompletion) steps? 

Can you provide a reproducible configuration steps (e.g. zsh + omz install + plugins + uv command that doesn't auto-complete)?

**Comment by amirreza8002** [comment]
```
sudo pacman -S zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo 'eval "$(uv generate-shell-completion zsh)"' >> ~/.zshrc
```

```
plugins=(
    git
    poetry
    asdf
    zsh-autosuggestions
    uv
  )
```

nothing i used worked with auto-complation

**Comment by samypr100** [comment]
@amirreza8002 Thanks.

Using `uv 0.5.4` and `zsh 5.9`, I tried `echo 'eval "$(uv generate-shell-completion zsh)"' >> ~/.zshrc` and reloaded the shell.

I tried on stock zsh and it works as expected.
I also tried with omz using above and it also seems to work as expected. Note, only tried with `git` and `zsh-autosuggestions` plugins.

```zsh
➜  ~ uv <TAB or ^I>
add                        -- Add dependencies to the project
build                      -- Build Python packages into source distributions and wheels
build-backend              -- The implementation of the build backend
cache                      -- Manage uv's cache
clean                      -- Clear the cache, removing all entries or those linked to specific packages
export                     -- Export the project's lockfile to an alternate format
generate-shell-completion  -- Generate shell completion
help                       -- Display documentation for a command
init                       -- Create a new project
lock                       -- Update the project's lockfile
pip                        -- Manage Python packages with a pip-compatible interface
publish                    -- Upload distributions to an index
python                     -- Manage Python versions and installations
remove                     -- Remove dependencies from the project
run                        -- Run a command or script
self                       -- Manage the uv executable
sync                       -- Update the project's environment
tool                       -- Run and install commands provided by Python packages
tree                       -- Display the project's dependency tree
venv                       -- Create a virtual environment
version                    -- Display uv's version
```

**Comment by amirreza8002** [comment]
hi
seems like i had older uv version, it got fixed with an update.
tho the docs at the time were the same, perhaps it's been fixed in later versions

sorry for the false alarm 🙏

**Comment by samypr100** [comment]
Thanks for checking and following up. I will proceed to close the issue 😄
