### ISSUE TITLE
termux install python not found cpython-3.12.7-linux-aarch64-none

### ISSUE THREAD

**Issue by WangZhongDian** [astral-sh/uv#9171]
I use `uv python list -- all-platforms` and do not have `cpython-3.12.7-linux-arch64-none`. I am using Android's termux for UV usage。Hope to add `cpython-3.12.7-linux-arch64-none` build

**Comment by charliermarsh** [comment]
I think this is a duplicate of #7373.

**Comment by charliermarsh** [comment]
My guess is that it's related to: https://github.com/astral-sh/uv/pull/9005.
