### ISSUE TITLE
path-dependencies with dynamic `version` incorrectly cached

### ISSUE THREAD

**Issue by acarapetis** [astral-sh/uv#9187]
I have a repo structured something like

```
.
├── app
│   ├── pyproject.toml
│   ├── uv.lock
│   └── ....
├── lib
│   ├── pyproject.toml
│   └── ...
```

with the app depending on the lib via a path-dependency:

```toml
[tool.uv.sources]
lib = { path = "../lib" }
```

The lib is using a dynamic version in its pyproject.toml. I'm not currently using uv workspaces.

**The issue:** If I change the version of `lib` (by modifying the `__version__` defined in lib's python source), then running `uv lock` in app/ does not detect this unless I purge the uv cache.

Here's a self-contained repro:

```sh
uv init app
uv init --lib --build-backend flit lib
sed -i 's/version = "0.1.0"/dynamic = ["version"]/' lib/pyproject.toml
echo '__version__ = "0.1.0"' >| lib/src/lib/__init__.py
uv --directory app add ../lib # + lib==0.1.0
echo '__version__ = "0.2.0"' >| lib/src/lib/__init__.py
uv --directory app lock # no change!
UV_CACHE_DIR=/tmp/fresh uv --directory app lock # Updated lib v0.1.0 -> v0.2.0
```

Seems related to #3796 but perhaps not quite the same? [This comment](https://github.com/astral-sh/uv/issues/3796#issuecomment-2128255312) suggests dynamic attributes should trigger a rebuild.

**Comment by charliermarsh** [comment]
This is working as intended -- it's discussed in several issues.. You can read [here](https://docs.astral.sh/uv/concepts/cache/#dynamic-metadata) in the docs for a summary of how we treat dynamic metadata. You likely want to add `lib/src/lib/__init__.py` as a cache key. (I personally recommend against using dynamic metadata like this -- it's more trouble than it's worth, in my opinion.)

**Comment by acarapetis** [comment]
Thanks, clearly I didn't find the right words to google!

**Comment by charliermarsh** [comment]
No prob, happy to help.
