### ISSUE TITLE
Can't use a private index in script dependency

### ISSUE THREAD

**Issue by oxenit** [astral-sh/uv#9201]
Hello, I can successfully use my private index with credentials saved in .netrc when installing a private package as dependency in the `pyproject.toml` of my lib.
However when copying the same logic in a script header it does not resolve my index.

Running `uv run myscript.py` gives :

```
error: Package `myprivatepackage` references an undeclared index: `myindex`
```

Code snippet :
```python
# /// script
# dependencies = [
#   "myprivatepackage>=1.2.3",
# ]
# [tool.uv]
# [[tool.uv.index]]
# name = "myindex"
# url = "https://pypi.myindex.com/simple"
# explicit = true
# [tool.uv.sources]
# myprivatepackage = { index = "myindex" }
# ///
mycode
```

Is config more limited in the script header ? 
Thanks

**Comment by charliermarsh** [comment]
This might just be a bug. I'll take a look today.
