### ISSUE TITLE
Using `--frozen` causes `--package` selection to be ignored

### ISSUE THREAD

**Issue by mattfysh** [astral-sh/uv#9214]
Reproduction repo here: https://github.com/mattfysh/uvsyncmono

Pass criteria: `uv sync --frozen --package foo` should not install baz or baz's dependencies (dpath)

* **uv version**: uv 0.5.2 (Homebrew 2024-11-14)
* **os**: Darwin 24.0.0 arm64 arm

**Comment by charliermarsh** [comment]
Thanks! (We confirmed that this only applies to workspaces without a `[project]` table.)
