### ISSUE TITLE
Virtual Environment Folder Configuration

### ISSUE THREAD

**Issue by SDAravind** [astral-sh/uv#9254]
Is it possible to have dedicated virtual environment folder outside project and link it to the project similar to poetry venv folder setup. The reason I ask is, when we switch between windows, linux(wsl) system to work on same project this requires deletion of .venv for each OS and again create virtual environment.

One can use `poetry config` (see below) command to customise virtual environment folder if user needs venv to be in project or default location outside the project that can be customised.

![Screenshot_20241120_033844](https://github.com/user-attachments/assets/807e6674-56b0-47e6-b815-eb8cf4a6cc29)

**Comment by zanieb** [comment]
Please see #1495 (and the issues linked there)

**Comment by SDAravind** [comment]
Thanks @zanieb.

@charliermarsh - Thanks for creating uv and ruff. They are fantastic tools for the python community. It would be nice to have this specific feature as adoption of uv increases across various platforms and containers.

I hope it would get addressed at some point sooner.

**Comment by zanieb** [comment]
Glad you like the tools! We're not sure how best to implement this and we have to balance _many_ requests and fixes. Your use-case is helpful context for prioritization though.
