### ISSUE TITLE
Is there a command that allows me to list all installed packages from my existing project into the dependencies section of pyproject.toml?

### ISSUE THREAD

**Issue by nonesubham** [astral-sh/uv#9265]

**Comment by FishAlchemist** [comment]
Do you have an expected output example? There's an API in the project series called "uv tree", and I guess it displays the dependencies described in the lock file. However, the lock file is also generated from pyproject.toml, so maybe it will meet your needs.

**Comment by MrMegaMango** [comment]
Is it preferred to move all packages from requirements.txt to pyproject.toml?

**Comment by charliermarsh** [comment]
Yeah.
