### ISSUE TITLE
installing current project as editable

### ISSUE THREAD

**Issue by zkurtz** [astral-sh/uv#9271]
Is there a single uv command that achieves both `uv sync; uv pip install -e .`? 

In my project's young and hackish workflow, the convention is to activate the virtual env and then cd into other directories to run stuff (still using the same venv). In that case, I need my project to be installed (as editable) in its own venv. The instructions [here](https://docs.astral.sh/uv/pip/packages/#editable-packages) say to do `uv pip install -e .`. But this makes no changes to the `uv.lock`, and correspondingly `uv sync` undoes the initial action. Which means that users need to remember to run `uv pip install -e .` after every time they do `uv sync`.

I noticed there is also the option of doing `uv add myproject --dev`, which looks like it _could_ be the right idea, but it doesn't seem to actually install anything, as `import myproject` does not work from other directories (with the same venv activated).

**Comment by konstin** [comment]
Does your project declare a build backend? `uv sync` only editably installs projects that declare one explicitly.

**Comment by zkurtz** [comment]
Thank you! Indeed adding this to my pyproject.toml resolved the issue, now `uv sync` behaves as desired:
```
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
```
However, I noticed that `uv build` assumes a default backend in case on is not provided. I wonder if `uv sync` could make a similar assumption?

**Comment by konstin** [comment]
This is a tradeoff we're making: We want to support people who don't write a package but only have scripts that shouldn't be installed (https://docs.astral.sh/uv/concepts/projects/#build-systems), while in `uv build`, we have to assume a setuptools default for backwards compatibility (PEP 517).

**Comment by KantiCodes** [comment]
> Does your project declare a build backend? `uv sync` only editably installs projects that declare one explicitly.

Thank you so much!
