### ISSUE TITLE
`uv export --package` from workspace root doesn't export root's dependencies

### ISSUE THREAD

**Issue by ultrapoci** [astral-sh/uv#9278]
I have a workspace setup with two subdirectories. The `pyproject.toml` file in the workspace root contains a dependency, which is then available for all projects in the workspace. In fact, if I run `uv run --package package1 pacakge1/hello.py`, it runs correctly when importing said dependency. 
The problem is that, if I run `uv export --package package1`, I get an empty result, because the `pyproject.toml` file in package1 is actually empty, but in reality package1 can use the dependencies declared in `pyproject.toml` in the workspace root.
Shouldn't `uv export` include all dependencies from the project root plus the dependencies for the project inside the workspace, if the `--package` flag is used?

uv version: 0.5.3 (using on macOS)
command invoked: `uv export --no-hashes --package package1`

**Comment by charliermarsh** [comment]
No, that's a reasonable approach!
