### ISSUE TITLE
uv pip compile emits index to output file

### ISSUE THREAD

**Issue by a-shkarupin** [astral-sh/uv#9287]
I'm trying to install dependencies from a private repository.

Using uv 0.5.3.

Running `uv pip compile --extra=dev --index https://user:password@my.repository/repository/repo-pypi/simple  --output-file=requirements.txt pyproject.toml`

The full index url including user and password is visible in requirements.txt.
```
# This file was autogenerated by uv via the following command:
#    uv pip compile --extra=dev --index https://user:password@my.repository/repository/repo-pypi/simple --output-file=requirements.txt pyproject.toml
```

Looking at the [docs](https://docs.astral.sh/uv/reference/cli/#uv-pip-compile)  I could only find the `--emit-index-url` option, so it seems that this shouldn't happen unless that option is specified.

Could you please advise if this is a bug or am I using the tool wrong?

**Comment by charliermarsh** [comment]
Ah sorry. This looks like a bug.
