### ISSUE TITLE
Changing the directory structure for uv init --package

### ISSUE THREAD

**Issue by benedikt-mue** [astral-sh/uv#9316]
Hi,
I am currently implementing uv as our package manager to replace poetry. In poetry, we defined the package entrypoints with `packages = [{ include = "backend", from = "src" }]` . 
Is there something similar possible with uv?

**Comment by charliermarsh** [comment]
I think `uv init --lib` will use a `src` layout by default.

**Comment by zanieb** [comment]
So does `uv init --package`:

```
❯ uv init --package example
Initialized project `example` at `/Users/zb/workspace/uv/example`
❯ tree example
example
├── README.md
├── pyproject.toml
└── src
    └── example
        └── __init__.py
```

**Comment by benedikt-mue** [comment]
Thanks for your quick response. I was rather curious if it is possible to change this behavior as in poetry with `[{ include = "whatever", from = "whereever" }]`

**Comment by charliermarsh** [comment]
I'm not sure exactly what you mean, but I think you're describing something that's specific to Poetry's _build backend_.

**Comment by benedikt-mue** [comment]
like changing the default layout? Say, I only want to have a flat structure:
```
example
├── README.md
├── pyproject.toml
└── project
           └── __init__.py
```

**Comment by charliermarsh** [comment]
You can't change the default layout that we create, but you can certainly change your project to use that layout!
