### ISSUE TITLE
Resolver hints should be line-wrapping

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#9325]
Kind of a note-to-self, I can't remember if these should be wrapping:

![Screenshot 2024-11-21 at 10 15 43 AM](https://github.com/user-attachments/assets/8bad2b97-b66d-4e38-92a4-994ea523e0c9)

**Comment by zanieb** [comment]
We probably wrap to the width of your terminal so if you had it wide when you ran the command it might be intentionally this way?

**Comment by charliermarsh** [comment]
Oh I think you're right

**Comment by charliermarsh** [comment]
(Is that the right behavior?)
