### ISSUE TITLE
`~` Tildes in environment variables not expanded before use

### ISSUE THREAD

**Issue by fynnsu** [astral-sh/uv#9326]
```bash
export UV_CACHE_DIR="~/uv_cache"
# Use uv
uv venv
uv pip install numpy
```
Will produce a subfolder `'~'` with `'uv_cache'` in it instead of expanding to `/home/user/uv_cache` when used. 

Note: Since shells will often expand the tildes themselves this may not often be a problem. In the above example, using `export UV_CACHE_DIR=~/uv_cache` (without the ""), works as my shell expands the `~` before setting the env variable. 

I ran into this issue because I was trying to use `astral-sh/setup-uv` with `cache-local-path: ~/.uv_cache` which then is used to set `UV_CACHE_DIR`. Unfortunately here, whether I include the "" or not, the env variable gets set with the `~` giving me the wrong cache dir.

I think it would be useful to support `~` at the start of paths for `UV_CACHE_DIR` and other similar path environment variables (untested but I'm guessing they have the same limitation).

**Comment by fynnsu** [comment]
This is potentially related to #9327. 
Doing something similar with env variables
```bash
export UV_CACHE_DIR=/home/user/path/../path/cache
uv venv
```
results in
```
error: failed to create directory `/home/user/path/../path/cache`
  Caused by: Operation not supported (os error 45)
```
Ideally there would be path resolution on all paths provided by the user (env variables, configuration files, cli args)

**Comment by zanieb** [comment]
I don't think I agree that we should expand this `~` in inputs, I don't think that's standard for most tools? As a simple example,`gh` clones into a `~` directory in the current folder:

```
$ gh repo clone zanieb/uv "~/test"
$ tree . -L 2
.
└── ~
    └── test
```

**Comment by zanieb** [comment]
I do think `astral-sh/setup-uv` should expand the `~` though.

**Comment by charliermarsh** [comment]
Yeah I don't think Cargo does that either. Maybe the GitHub Action should be expanding it though.

**Comment by fynnsu** [comment]
Okay I will open an issue in `astral-sh` for this. Thank you
