### ISSUE TITLE
Feature request - "pip download"-like behavior, but platform independent.

### ISSUE THREAD

**Issue by f3flight** [astral-sh/uv#9345]
Hi UV devs! I was looking for a way to use UV to download a full set of dependency files for a given package, similarly to how "pip download" works. Looks like there's no clean way to do this currently, only extracting from cache - is that correct? More importantly, I am looking for a way to download all possible artifacts for each dependency in the tree, i.e. both sdist and all wheels. This would be equivalent to creating a lock file and downloading all urls listed there. The end goal of this is to be able to do sparse updates of internal mirror of various external indexes, grabbing only necessary files.

**Comment by topher96** [comment]
Related #6323
