### ISSUE TITLE
loop over python versions in github actions

### ISSUE THREAD

**Issue by zkurtz** [astral-sh/uv#9376]
[Here](https://github.com/zkurtz/dummio/blob/619e049bb005f0e30c0e17fe3822eb7de02dc625/.github/workflows/ci.yml#L13-L23) is what I did and it seems to work. But is that really the recommended way? It feels a bit hacky to overwrite `.python-version`. FWIW I'd appreciate any other feedback on that workflow config. I'm trying to set up uv with a few repos and would like to get my setup right.

**Comment by samypr100** [comment]
👋 I believe you can use [UV_PYTHON](https://docs.astral.sh/uv/configuration/environment/#uv_python) instead

**Comment by zkurtz** [comment]
Thank you! I'm currently at
```
    - name: Set the python version for UV
      run: echo "UV_PYTHON=${{ matrix.python-version }}" >> $GITHUB_ENV
    [etc]
```

**Comment by zanieb** [comment]
I'd be happy to review a pull request adding documentation if needed. There's a bit at http://docs.astral.sh/uv/guides/integration/github/#setting-up-python but this sounds different.

**Comment by zkurtz** [comment]
Although https://github.com/astral-sh/uv/issues/9376#issuecomment-2495478626 seems to be working, I'm still not clear if that's considered a recommendable/canonical approach. From the docs you linked ^^, there is also this option
```
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
```
but it's not obvious to me whether the python version here specifically overrides the python version that would be used by subsequent `uv run` commands, which should obey the `.python-version` file regardless of which other versions of python happen to be available on the system
