### ISSUE TITLE
add a build system?

### ISSUE THREAD

**Issue by DinhHuy2010** [astral-sh/uv#9382]
I wondering what if uv include its own PEP 518-compatible build system? (e.g. no need for external build systems like setuptools), similar to poetry?

**Comment by Lingepumpe** [comment]
Duplicate of issue #3957

**Comment by DinhHuy2010** [comment]
@charliermarsh  wait what?

**Comment by charliermarsh** [comment]
We're already working on our own build backend. It's tracked in https://github.com/astral-sh/uv/issues/3957.
