### ISSUE TITLE
choose python installation dir

### ISSUE THREAD

**Issue by davidszotten** [astral-sh/uv#9384]
Hi. Apologies if this is documented somewhere and i just failed to find it:

is it possible to choose the directory into which pythons are installed? (currently for me on os x: `~/Library/Application Support/uv/python/`

the issue is that some tools (today mason-nvim) choke on the space in the path (with very cryptic errors). i know that's a bug elsewhere but maybe an easy workaround for me would be to pick a different installation dir

**Comment by charliermarsh** [comment]
Yeah: https://docs.astral.sh/uv/configuration/environment/#uv_python_install_dir

**Comment by charliermarsh** [comment]
Also, if you remove that directory entirely (like `rm ~/Library/Application Support/uv`), we should stop using it. It's only used for backwards compatibility.

**Comment by davidszotten** [comment]
Thanks!
