### ISSUE TITLE
Unable to download Python 3.11.2 on Windows

### ISSUE THREAD

**Issue by sk-ys** [astral-sh/uv#9394]
* The command you invoked:
  ```
  > uv python install 3.11.2 --verbose
  DEBUG uv 0.5.4 (c62c83c37 2024-11-20)
  error: No download found for request: cpython-3.11.2-windows-x86_64-none
  ```
* The current uv platform: Windows 11 24H2 26100.2454
* The current uv version: 0.5.4 (c62c83c37 2024-11-20)

**Comment by charliermarsh** [comment]
I think 3.11.2 was skipped in python-build-standalone: https://github.com/indygreg/python-build-standalone/releases/20230507. Is there a reason you need that specific patch...?

**Comment by sk-ys** [comment]
@charliermarsh 
Thank you for replying.
My Raspberry Pi 5 uses Python 3.11.2, so I'm trying to develop the related components on my laptop.

**Comment by charliermarsh** [comment]
I think we're unlikely to re-add these, since patch releases are generally meant to be upgradeable without issue. So you should be able to use, e.g., 3.11.3 interchangeably.
