### ISSUE TITLE
`--locked` does not always report an error even when the lockfile needs to be regenerated

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/uv#9396]
# environment
- uv: tested on 0.5.2 and 0.5.4
- python tested on 3.11, 3.12, 3.13
- windows
# to reproduce
sorry this isn't a minimal repro, i can't get it to happen reliably so this is the best i can do.

note that the project uses pyprojectx so it installs uv automatically

1. `git clone https://github.com/detachhead/basedpyright` (commit `6d94c2aca2683aaa1f36e5d1687c6240e239b315`)
2. `cd basedpyright`
3. run `./pw uv lock --locked` (no error)
4. delete `uv.lock`
5. run `./pw uv lock`
6. run `git diff uv.lock`

```diff
diff --git a/uv.lock b/uv.lock
index aca6ec6ee..f165035b0 100644
--- a/uv.lock
+++ b/uv.lock
@@ -1,8 +1,7 @@
 version = 1
 requires-python = ">=3.8"
 resolution-markers = [
-    "python_full_version < '3.9'",
-    "python_full_version >= '3.9' and python_full_version < '3.11'",
+    "python_full_version < '3.11'",
     "python_full_version == '3.11.*'",
     "python_full_version >= '3.12'",
 ]
@@ -250,8 +249,7 @@ name = "docify"
 version = "1.0.0"
 source = { registry = "https://pypi.org/simple" }
 dependencies = [
-    { name = "libcst", version = "1.1.0", source = { registry = "https://pypi.org/simple" }, marker = "python_full_version < '3.9'" },
-    { name = "libcst", version = "1.5.0", source = { registry = "https://pypi.org/simple" }, marker = "python_full_version >= '3.9'" },
+    { name = "libcst" },
     { name = "tqdm" },
 ]
 sdist = { url = "https://files.pythonhosted.org/packages/b2/cc/d403e8dbe89826340a18909e0aa26ed917981d41579ba91145e2e1b954c8/docify-1.0.0.tar.gz", hash = "sha256:8d779f8348dd8d46796709c0db7d710cbc6354935d90a727c9ff3ab77b4cd3bf", size = 7186 }
@@ -356,13 +354,10 @@ wheels = [
 name = "libcst"
 version = "1.1.0"
 source = { registry = "https://pypi.org/simple" }
-resolution-markers = [
-    "python_full_version < '3.9'",
-]
 dependencies = [
-    { name = "pyyaml", marker = "python_full_version < '3.9'" },
-    { name = "typing-extensions", marker = "python_full_version < '3.9'" },
-    { name = "typing-inspect", marker = "python_full_version < '3.9'" },
+    { name = "pyyaml" },
+    { name = "typing-extensions" },
+    { name = "typing-inspect" },
 ]
```
(the diff is larger than this but i only included the first few changes)

**Comment by FishAlchemist** [comment]
@DetachHead Actually, ``uv sync`` will automatically check if the lock file is up-to-date, unless you've used the ``--frozen`` flag.
So theoretically, as long as you've used ``uv sync`` before committing, your lock file should be up-to-date.

``uv sync``
``--frozen``
```
Sync without updating the uv.lock file.

Instead of checking if the lockfile is up-to-date, uses the versions in the lockfile as the source of truth. If the lockfile is missing, uv will exit with an error. If the pyproject.toml includes changes to dependencies that have not been included in the lockfile yet, they will not be present in the environment.

May also be set with the UV_FROZEN environment variable.
```

**Comment by DetachHead** [comment]
i think it only happens when deleting the lockfile before running `uv sync` or `uv lock` again. if the lockfile isn't deleted first, it doesn't seem to regenerate it which would explain why `--locked` doesn't think there are any changes

**Comment by charliermarsh** [comment]
This is generally intentional... `--locked` confirms that the `uv.lock` is up-to-date with the given requirements, _not_ that a fresh `uv lock` would produce the same lockfile. These are subtly different. For example, we might change how we represent some metadata in `uv.lock`, or we might change prioritization within the resolver. Both of those changes could be backwards-compatible, so existing `uv.lock` files work fine and still represent a valid resolution for the given inputs. But if you remove the `uv.lock`, we might then make different choices in resolving.

If you actually want to enforce _this_ guarantee, I'd probably do it manually by moving `mv uv.lock before.lock` then `uv lock` and diffing the two files.

**Comment by DetachHead** [comment]
@charliermarsh if i'm understanding correctly, you're saying that it's ok for the newly generated lockfile to be different as long as it's functionally the same as the previous one.

that doesn't seem to be the case here though, because as far as i can tell there definitely is a functional difference between these two versions of the lockfile, which was caused by removing these dependencies from `pyproject.toml`
```toml
[dependency-groups]
docstubs = [
    # ...
    "libcst>=1.5.0 ; python_version>='3.9'",
    "libcst==1.1.0 ; python_version<'3.9'",
]
```
(from https://github.com/astral-sh/uv/issues/9396#issuecomment-2497207219)

i'm still extremely confused as to what happened here because as far as i can tell this doesn't appear to be intentional. `uv lock --check` seems to only *sometimes* complain about this specific discrepancy. but unfortunately i couldn't reliably reproduce the issue :(

**Comment by charliermarsh** [comment]
Sorry yes, if the input dependencies change, then locked should error. I would need a reproduction to help though :(
