### ISSUE TITLE
Allow UV_NO_SYNC=1 UV_FROZEN=1 on uv run

### ISSUE THREAD

**Issue by inoa-jboliveira** [astral-sh/uv#9397]
I have a docker application where I don't want each `uv run` syncing every time (due to how I build the image without dev group on uv sync) and I don't want `uv sync` trying to resolve anything.
Therefore I tried to add both env variables to my docker image

```
UV_NO_SYNC=1
UV_FROZEN=1
```

For syncing, the UV_NO_SYNC  variable is simply ignored, which makes sense and is desirable.

When doing `uv run` I get:

```
$ uv run foo
error: the argument '--no-sync' cannot be used with '--frozen'

Usage: uv run --no-sync
```

Also notice the error messages refer as if I passed conflicting arguments when in fact I used env variables which should be more lenient as in a best effort basis.

In any case, I do not think --no-sync and --frozen are exclusive parameters. They should play along well

**Comment by charliermarsh** [comment]
Yeah this seems like a bug.

**Comment by charliermarsh** [comment]
Although, wait, I think `--no-sync` implies frozen in `uv run`?

**Comment by inoa-jboliveira** [comment]
> Although, wait, I think `--no-sync` implies frozen in `uv run`?

`--no-sync` will prevent syncing which makes `--frozen` just a no-op.

But for `uv sync` the `--frozen` option is important because `--no-sync` is a no-op. 

IMHO I would just remove the conflicts_with here:
https://github.com/astral-sh/uv/blob/e485dfd7f1984537374676e422691c2327c4e24e/crates/uv-cli/src/lib.rs#L2734-L2735

**Comment by charliermarsh** [comment]
I see, so we're agreed that `--frozen` is redundant for `uv run` here, but you're saying that because you set the env vars, it makes it inconvenient. That's reasonable. I'll lift the restriction.
