### ISSUE TITLE
Install from lockfile to system python (no venv) (Containerized env).

### ISSUE THREAD

**Issue by g-bar** [astral-sh/uv#9399]
I'm using uv to manage my dependencies in a Dockerfile.
Like so:

```
FROM python:3.12

ENV UV_SYSTEM_PYTHON=true
RUN pip install --no-cache-dir uv
COPY uv.lock pyproject.toml ./
RUN uv sync --frozen
```
I though the `UV_SYSTEM_PYTHON=true` sufficed but it's still creating a venv. Apparently the envvar and --system flag only apply to uv pip install, but that requires to specify the packages. I want to install from uv.lock.

I'm looking for something like poetry's `POETRY_VIRTUALENVS_CREATE` : https://python-poetry.org/docs/configuration#virtualenvscreate.

**Comment by FishAlchemist** [comment]
If you're going to install using uv sync into the system Python, you should consider setting the ``UV_PROJECT_ENVIRONMENT`` variable.
https://docs.astral.sh/uv/concepts/projects/config/#project-environment-path

**Comment by charliermarsh** [comment]
Yeah, you need to use `UV_PROJECT_ENVIRONMENT` here.

**Comment by g-bar** [comment]
Thank you!
