### ISSUE TITLE
Python symlink is wrong when building Dockerfile

### ISSUE THREAD

**Issue by timvink** [astral-sh/uv#9414]
Consider this Dockerfile:

```Dockerfile
# adapted from https://github.com/astral-sh/uv-docker-example/blob/main/Dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

WORKDIR /code

# Copy the lockfile and settings
COPY uv.lock .
COPY pyproject.toml .
COPY .python-version .

# Setup python environment
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    --mount=type=bind,source=.python-version,target=.python-version \
    --mount=type=secret,id=uv.toml,dst=/root/.config/uv/uv.toml \
    uv sync --frozen --no-install-project --link-mode=copy --python-preference=only-managed

# Place executables in the environment at the front of the path
ENV PATH="/code/.venv/bin:$PATH"
```

If I build this and open a shell inside the image, and run `ls -lah .venv/bin/`;

<img width="779" alt="image" src="https://github.com/user-attachments/assets/dc1d567f-757e-49ab-8058-727586e2b40f">

and compare it with `uv python list` you can see the wrong symlink (notice the root, `/home/azureuser/` instead of `/root/`:

<img width="698" alt="image" src="https://github.com/user-attachments/assets/76d47107-9685-4392-b795-bfd485f57d96">

The consequence is that `which python` points to the wrong python version, because the python version in the .venv does not exist.

I suspect something is going wrong with `~` expansion.. indeed on my host machine that points to `/home/azureuser/`. 
Using [0.5.4](https://github.com/astral-sh/uv/releases/tag/0.5.4)

**Comment by timvink** [comment]
Yes, I even have an additional `USER root:root` in my docker. The location of managed python is correct:

![image](https://github.com/user-attachments/assets/4e11eccf-0d52-43b5-8277-b2ee2e429751)

The location of python in the `.venv` folder inside the docker container isnt:

![image](https://github.com/user-attachments/assets/afcd0c82-7a9c-4875-8a97-a04b56d55289)

**Comment by FishAlchemist** [comment]
If we don't explicitly set the value of $HOME in Docker, what is the  value of $HOME?

**Comment by timvink** [comment]
I'm not convinced anymore this is `uv` related. I think it's related to the base image I am using. Closing issue.
