### ISSUE TITLE
Global config file ignored on Windows

### ISSUE THREAD

**Issue by markuspi** [astral-sh/uv#9416]
UV does not read the configuration file in `%SYSTEMDRIVE%\ProgramData\uv\uv.toml` unless the working directory happens to be `%SYSTEMDRIVE%\`.

### Root Cause

- The `SYSTEMDRIVE` environment variable consists only of a drive letter followed by a colon. There is no trailing backslash. E.g. `C:` `D:`
- The final path is assembled by UV as follows: 
  ```rust
  let candidate = PathBuf::from(system_drive).join("ProgramData\\uv\\uv.toml");
  ```
- `candidate` now contains a path like this: `C:ProgramData\uv\uv.toml`
- Since there is no backslash between `C:` and `ProgramData`, this path is [specified](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) to be 
  > A *relative* path from the current directory of the C: drive.

  rather than an absolute path. UV thus only recognizes the config file if the CWD is the root of the system drive.
- Inserting the missing backslash resolves the problem

### Steps to reproduce:

1. Create file `%SYSTEMDRIVE%\ProgramData\uv\uv.toml`. For demonstration purposes, insert an invalid option 

```toml
doesnotexist = true
```

2. Run UV from the drive root to observe parse error (as expected)

```cmd
cd %SYSTEMDRIVE%\
uv cache prune
```
`error: Failed to parse: C:ProgramData\uv\uv.toml`

3. Run UV from any other directory on the same drive. Observe that no parse error was thrown since the global config file was not loaded at all (bug)

```cmd
cd %SYSTEMDRIVE%\Users
uv cache prune
```
`Pruning cache at ...`

### Note

Be aware that windows keeps track of working directories _per system drive_. Changing to another drive such as `D:/foo` might not reproduce the bug

### Version Information

* UV version 0.5.4

**Comment by zanieb** [comment]
Are you sure "candidate now contains a path like this: C:ProgramData\uv\uv.toml" is true? `.join` should use the system separator to join the paths?

**Comment by zanieb** [comment]
It looks like this is intentionally omitted, interesting

https://doc.rust-lang.org/src/std/path.rs.html#1288-1289

**Comment by markuspi** [comment]
Yeah Windows Paths are quite a mess 😅
At least Rust's behavior of `.join` is in line with Python and Java implementations

**Comment by markuspi** [comment]
Thanks!
