### ISSUE TITLE
Add `--offline` flag to disallow network requests

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/uv#942]
This is like `--no-index`, but it should disallow _all_ network requests (including for distributions and `--find-links`).

**Comment by andrei-korshikov** [comment]
**`--offline` is not offline for "git+https" sources.**

I'm on uv 0.6.6 (c1a0bb85e 2025-03-12). Some of my dependencies are `git+https`, e.g. I have

```python
# /// script
# dependencies = [
#   "pycurl @ git+https://github.com/pycurl/pycurl.git",
#   ]
# ///
```

On every run of `uv run --offline my_script.py` I see `Resolving dependencies...` message and get these messages on `stderr` (and see corresponding traffic in Wireshark):

```
Updating https://github.com/pycurl/pycurl.git (HEAD)
Updated https://github.com/pycurl/pycurl.git (d92395d9fe1e18365c4e4812f4351bd6985872e1)
```

If this behaviour is intended, I think it should be documented. Documentation for `--offline` reads: "Disable network access. When disabled, uv will only use locally cached data and locally available files.", and as we see for "git+https" it is definitely not so.

---

Off-topic: and huge thank you for `uv`!:)
