### ISSUE TITLE
Packages are NOT found at the link specified as "index". But if specify the link as "find-links" then the installation is correct.

### ISSUE THREAD

**Issue by VladislavSoren** [astral-sh/uv#9441]
Info:
OS: MacOS
Python: 3.9.18
uv: 0.5.4

if specify the link as "find-links" then the installation is correct
![photo_2024-11-26_16-56-52](https://github.com/user-attachments/assets/db9b84d2-8109-4a5b-a915-da605d945998)

If the same link specified as "index" then package are NOT found
![photo_2024-11-26_16-39-23](https://github.com/user-attachments/assets/ec330505-3a1b-47b4-adfa-6ddd2bbe705f)

**Why can't I define a link as an index so that the packages install correctly?**

**Comment by charliermarsh** [comment]
The `--find-links` and `index` formats aren't the same -- the layouts are not equivalent.

**Comment by VladislavSoren** [comment]
How can I correctly specify my source so that it can be used as an index?

**Comment by konstin** [comment]
The page needs to follow [PEP 503](https://peps.python.org/pep-0503/) to be usable as an index, otherwise it's only usable as find-links.

**Comment by charliermarsh** [comment]
Yeah it needs to have `index.html` files and such -- it essentially needs to look like an index that you could host with `python -m http.server`.

**Comment by VladislavSoren** [comment]
Thank you guys for answers very much !
