### ISSUE TITLE
Improve documentation on how to do `uv lock --upgrade-package <package>` for optional dependency package

### ISSUE THREAD

**Issue by DeflateAwning** [astral-sh/uv#9449]
It is not clear from the documentation and `uv lock -h` docs how to upgrade an optional dependency with the `lock` subcommand.

For example, I have pyright unpinned in my `pyproject.toml` file, in the optional-dependencies / dev section. I want to upgrade it. Is there a feasible way to do that with the `uv lock` command?

**Comment by DeflateAwning** [comment]
I'm not sure what I was doing wrong earlier (could have sworn I tried that exact command), but it seems that it does now! Wish I mentioned what version of `uv` I was on back then. 

In the docs, I still think it'd be good to explicitly explain that optional dependencies are locked/upgraded the same as non-optional ones. Thanks for the clarification here!

**Comment by charliermarsh** [comment]
No worries! I re-read the docs, and personally I think the line on upgrades is okay as-is. If we get another issue like this, I'll definitely reconsider.
