### ISSUE TITLE
`uv` does not use ~/.netrc credentials for `--index`

### ISSUE THREAD

**Issue by stefanvanburen** [astral-sh/uv#9450]
```console
$ uv --version
uv 0.5.4 (Homebrew 2024-11-20)
```

```console
$ # add credentials to ~/.netrc
$ uv add <package> --index <my-index>
# fails with 401 due to not including credentials
$ env NETRC=~/.netrc uv add <package> --index <my-index>
# passes
```

Based on [the docs](https://docs.astral.sh/uv/configuration/authentication/#http-authentication), I'd expect these invocations to be the same — `uv add` should use the credentials for an index defined in my ~/.netrc file by default, without me needing to specify the file specifically. (Maybe there's a reason for `--index` not to do this, if the intention is to [provide credentials to a particular index in another way](https://docs.astral.sh/uv/configuration/indexes/#providing-credentials), but ISTM that ~/.netrc credentials should be used if they exist, regardless?)

**Comment by charliermarsh** [comment]
I don't think we do anything here, other than ask the crate to discover the netrc file:

```rust
    pub fn get_file() -> Option<PathBuf> {
        let env_var = std::env::var("NETRC")
            .map(PathBuf::from)
            .map(|f| shellexpand::path::tilde(&f).into_owned());

        #[cfg(windows)]
        let default = std::env::var("USERPROFILE")
            .into_iter()
            .flat_map(|home| repeat(home).zip([".netrc", "_netrc"]))
            .map(|(home, file)| PathBuf::from(home).join(file));

        #[cfg(not(windows))]
        let default = std::env::var("HOME").map(|home| PathBuf::from(home).join(".netrc"));

        env_var.into_iter().chain(default).find(|f| f.exists())
    }
```

**Comment by stefanvanburen** [comment]
Possibly a mistake on my end — thanks for looking; I'll close this out and reopen if I have a repro for you.
