### ISSUE TITLE
`uv` is not installing the latest version of dependency packages

### ISSUE THREAD

**Issue by Laughing-q** [astral-sh/uv#9462]
Hi team! Really awesome work on this package! 
The installation speed is incredibly fast and we really want to use `uv` package as the python package manager in our github CI tests. However I do noticed it behaves slightly different from the original `pip` manager and it causes our CI tests failing.

We have a dependency `tensorflowjs>=3.9.0` in our repo [ultralytics](https://github.com/ultralytics/ultralytics), https://github.com/ultralytics/ultralytics/blob/7c97ed19372655a8b3d9050fc0f2ffb2e6a31276/pyproject.toml#L104.
- With original `pip` as python package manager it'll install `tensorflow==4.15.0` which works fine with our tests.
- With `uv pip` somehow it'll install `tensorflowjs==3.9.0` and actually this version is not compatible with our tests. (I tried to pin this package to a higher version but `uv` raised another issue to me. see https://github.com/astral-sh/uv/issues/9462#issuecomment-2503274238)

I have all the install log here: 
[3_Benchmarks (ubuntu-latest, 3.11, yolo11n).txt](https://github.com/user-attachments/files/17931564/3_Benchmarks.ubuntu-latest.3.11.yolo11n.txt) 
and from the log it seems `uv` tried a higher version but eventually selected the lowest one, which I don't understand. Can you check the log and tell me why it's selecting the lowest version of the package? Thanks
Because from the docs it should be installing the latest version.
![Image](https://github.com/user-attachments/assets/2445281e-d676-4f8c-b705-6ec347fbd545)

**Comment by konstin** [comment]
Could it be that the conflict with the tighter bound is caused by packaging and https://docs.astral.sh/uv/pip/compatibility/#packages-that-exist-on-multiple-indexes ?

**Comment by Laughing-q** [comment]
@konstin @charliermarsh Thank you guys! using `unsafe-first-match` works to our case!
