### ISSUE TITLE
Is it possible to run workspace only dependencies command?

### ISSUE THREAD

**Issue by bepuca** [astral-sh/uv#9470]
I am working with workspaces and they work great.

One thing I'd like to do is to make sure that my code in one workspace is not leaking dependencies from another workspace. For now, I can ensure this by running the following commands:

```shell
uv sync --package "<my_package>" --no-dev
uv run --package "$component" --no-dev python "packages/<my_package>/something.py"
uv sync
```

The problem with that is that it uninstalls and reinstalls stuff and is a bit slow, specially on the second sync. Is there an easy way to run it in ephemeral venv or something? Maybe it is but I could not find it. What would be the recommended way to do this?

Thank you very much!

**Comment by zanieb** [comment]
I think if you use `uv run --isolated ...` we will use a separate environment.

How slow is the second sync?

**Comment by bepuca** [comment]
I knew I was missing something, thank you for the prompt reply. This works brilliantly.

The second sync is not super slow, maybe 10s, but one gets used to fast with `uv` ⚡ ⚡ ⚡ 

This project is amazing! (closing as issue is solved)

**Comment by zanieb** [comment]
Wonderful.

If you want to share some more details about that second sync, we can look into that too. 10s is slower than I'd expect.

**Comment by bepuca** [comment]
Well, it basically reinstalls almost everything from scratch. What takes time is not the resolving but is the actual download + installs (and considering, this is quite fast). I am working inside a docker container and I have uv link mode copy (not sure if that is important info). Maybe the cache is messed up due to the setup.

**Comment by zanieb** [comment]
Having a copy link mode would definitely slow things down. I'm not sure if we can do much better in an image, that makes more sense to me.

**Comment by bepuca** [comment]
It is fine, still like this is miles away from anything I used before. I can live with this speed. I see also that after one `--isolate` run, the subsequent ones reuse, which makes things fast too.
