### ISSUE TITLE
unable to uv add httpx or uv pip install httpx on windows

### ISSUE THREAD

**Issue by zkurtz** [astral-sh/uv#9476]
I always get an error like `.venv\...\Scripts\httpx.exe: Access is denied. (os error 5)`. The obvious solution is to run as admin, but in my corporate environment this would require involving IT.

It's unclear how much this is a uv issue vs an httpx issue ([cross posted](https://github.com/encode/httpx/discussions/3417)) vs something else. But I'm suspecting uv somehow because plain `pip install httpx` in a standard `python -m venv .venv` environment still works.

**Comment by zanieb** [comment]
Can you install other packages?

I don't really know what's going on here, it seems specific to your system. We use `httpx` in a lot of our tests.

**Comment by zanieb** [comment]
Perhaps your antivirus is flagging the executable for some reason? There's not anything we can do to help with that.

**Comment by zkurtz** [comment]
Right, maybe. Another peculiarity here is that if I simply rerun the command (either in the context of `uv add` or `uv sync`), it succeeds.

**Comment by DarrenPadraigDV** [comment]
@zanieb  I get something similar, I suspect it is crowdstrike related.
