### ISSUE TITLE
`uv tool run` fails when using `prefect` because it can't find modules, despite working when run in activated venv.

### ISSUE THREAD

**Issue by NicholasPini** [astral-sh/uv#9477]
I have a uv package that has `prefect` and a bunch of other dependencies installed.
`prefect` provides the command `prefect worker start --pool 'process-pool-test'`: this commands starts a worker process. If I go into my project, activate the venv, and run `prefect worker start --pool 'process-pool-test'`, I can start another script which runs the process deployed to this worker, and everything works correctly.
If, however, I use `uv tool run prefect worker start --pool 'process-pool-test'`, the worker starts, but as soon as I try to run the process deployed, I get errors about dependencies not found. This issue can be solved by passing all dependencies of the project to the `--with` flag, but this is tedious and not easily maintainable. 
I don't understand what is the problem, given that the dependencies are all present in `pyproject.toml` and installed in the venv.

**Comment by zanieb** [comment]
`uv tool run` doesn't run in your project's environment. You'll want to use `uv run` instead.

**Comment by zanieb** [comment]
Documentation at https://docs.astral.sh/uv/concepts/tools/#relationship-to-uv-run

**Comment by NicholasPini** [comment]
I was under the impression that `uv run` is used only to run my own scripts. Well, that solved the issue, thank you very much!

**Comment by Happily-Coding** [comment]
In case anyone else stumbles upon this post and still has an issue, because the command prefect is not recognized, i had to run uv lock --upgrade and that allowed me to execute prefect with uv run.
