### ISSUE TITLE
Add support for downloading Python from https://www.python.org/ftp/python

### ISSUE THREAD

**Issue by kimminw00** [astral-sh/uv#9496]
I would like to request support for downloading Python from https://www.python.org/ftp/python/.
As someone who has been using <code>pyenv</code>, I think this feature would be extremely helpful for those who are migrating to <code>uv</code>. 

Reference
https://docs.astral.sh/uv/configuration/environment/#uv_python_install_mirror

**Comment by zanieb** [comment]
I believe those Python versions are just the source code, not built distributions?

**Comment by zanieb** [comment]
Some more context in https://github.com/astral-sh/uv/issues/4270

**Comment by charliermarsh** [comment]
Yeah we don't plan to support building Python from source like that right now.
