### ISSUE TITLE
Migrate from Poetry to UV

### ISSUE THREAD

**Issue by lluisCM** [astral-sh/uv#9501]
Hello, I'm not sure if this is the place to post a question, but I would like to get some feedback/experience on relation of replacing poetry to uv.

I'm looking to migrate from Poetry to UV. But my only concern is that UV seems to not provide a build backend, so what is the recommended way to structure the pyproject.toml file? Should I still install poetry, pdm or hatchling as a build systems? In that case, isn't a better option to just use poetry (for example) to manage the project and uv for venv etc... but not for the pyproject.toml file?

I'm specifically referring to this section:

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

Thank you.

**Comment by FishAlchemist** [comment]
UV currently doesn't have a backend built, so it should be difficult to handle functions that require a backend.
* https://github.com/astral-sh/uv/issues/8779

**Comment by lluisCM** [comment]
Be able to generate the .whl file, building and install the current project and probably prepare it to publish to PyPi requires a backend, right? 
So what is the recommended way to proceed? which backend is recommended/supported to use?
Thank you.

**Comment by konstin** [comment]
Until uv has its own backend, you can use hatchling or the pdm backend:

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

uv works with all of them, you can use the backend you like best. For new projects, `uv init` has a `--build-backend` option, the default is hatchling, which should cover most use cases (also coming from poetry).

**Comment by laudmt** [comment]
Having personally passed a few projects from poetry to uv, I encountered an issue with hatchling, which had trouble to find the correct compiler.

Adding this fixed it:
```bash
export CC=gcc 
export AR=ar
```

I believe it is related to this issue : https://github.com/astral-sh/uv/issues/8429

**Comment by qiuxiaomu** [comment]
Hope uv's build system is on the schedule!

**Comment by zanieb** [comment]
We're working on it!

- #8779 
- #3957 
- #12804
