### ISSUE TITLE
The command to changing the install path in the document does not work on Windows

### ISSUE THREAD

**Issue by A-kirami** [astral-sh/uv#9503]
I attempted to follow the instructions in the [document](https://docs.astral.sh/uv/configuration/installer/#changing-the-install-path) to changing the install path using the following command, but encountered an error on a Windows system.

```
$env:UV_INSTALL_DIR = "C:\Custom\Path" powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

in PowerShell 7:

```
ParserError:
Line |
   1 |  $env:UV_INSTALL_DIR = "C:\Custom\Path" powershell -ExecutionPolicy By …
     |                                         ~~~~~~~~~~
     | Unexpected token 'powershell' in expression or statement.
```

in Windows PowerShell:

```
所在位置 行:1 字符: 40
+ $env:UV_INSTALL_DIR = "C:\Custom\Path" powershell -ExecutionPolicy By ...
+                                        ~~~~~~~~~~
表达式或语句中包含意外的标记“powershell”。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by FishAlchemist** [comment]
Although I'm not sure if this method(https://github.com/astral-sh/uv/pull/9507) will be accepted, at least it can solve your current problem.
```powershell
 $env:UV_INSTALL_DIR = "C:\Custom\Path"; powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
```

**Comment by A-kirami** [comment]
> Although I'm not sure if this method([#9507](https://github.com/astral-sh/uv/pull/9507)) will be accepted, at least it can solve your current problem.
> 
>  $env:UV_INSTALL_DIR = "C:\Custom\Path"; powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

Thank you, that resolved my issue.
