### ISSUE TITLE
Use uv inside container without venv?

### ISSUE THREAD

**Issue by Time0o** [astral-sh/uv#9505]
My apologies if this has been asked before but I could not find a solution.

I'd like to use uv to speed up some Docker image builds, while I'm at it also installing a different version of Python.

A "naive" approach would be something like:

```
RUN UV_NO_MODIFY_PATH=1 curl -LsSf https://astral.sh/uv/install.sh | sh && \
    mv $HOME/.local/bin/uv /usr/local/bin/ && \ 
    uv python install 3.12 && \
    uv venv /.venv && \
    . /.venv/bin/activate && \
    uv pip install --upgrade pip
```

After that I have Python 3.11 and `pip` available if I source `/.venv/bin/activate`. But I would prefer not to have to source this file in every subsequent layer. There is the possibility of running `uv pip install --system` but that only seems to work with the system Python version. There is the possibility of installing Python in a specific location with `UV_PYTHON_INSTALL_DIR` but uv will complain with "This Python installation is managed by uv and should not be modified." if I add the contained `bin` dir to my path and call `uv pip install --system`. There is also the possibility of pinning the Python version but that is equivalent to the former.

Is there no way to achieve what I want? Do I have to install the version of Python I want via my package manager and then use something like `update-alternatives`? That seems a bit messy when uv could do the same for me (obviously not a great idea on a production system but for containers...)

**Comment by FishAlchemist** [comment]
You want to install Python using uv, but you don't want a virtual environment. Do you want to modify  environment in the managed Python directly?
``--break-system-packages``
```
Allow uv to modify an EXTERNALLY-MANAGED Python installation.

WARNING: --break-system-packages is intended for use in continuous integration (CI) environments, when installing into Python installations that are managed by an external package manager, like apt. It should be used with caution, as such Python installations explicitly recommend against modifications by other package managers (like uv or pip).

May also be set with the UV_BREAK_SYSTEM_PACKAGES environment variable.
```
By additionally specifying the path to the managed Python, we should be able to make modifications
https://docs.astral.sh/uv/pip/environments/#using-arbitrary-python-environments

**Comment by Time0o** [comment]
> You want to install Python using uv, but you don't want a virtual environment. Do you want to modify environment of the managed Python directly? `--break-system-packages`
> 
> ```
> Allow uv to modify an EXTERNALLY-MANAGED Python installation.
> 
> WARNING: --break-system-packages is intended for use in continuous integration (CI) environments, when installing into Python installations that are managed by an external package manager, like apt. It should be used with caution, as such Python installations explicitly recommend against modifications by other package managers (like uv or pip).
> 
> May also be set with the UV_BREAK_SYSTEM_PACKAGES environment variable.
> ```
> 
> By additionally specifying the path to the managed Python, you should be able to make modifications https://docs.astral.sh/uv/pip/environments/#using-arbitrary-python-environments

Thanks! By combining `UV_PYTHON_INSTALL_DIR`, `--system` and `--break-system-packages` I can do what I want. For future users, could there maybe be a guide on using `uv` in CI environments? I could help contribute that if desired.

**Comment by astrojuanlu** [comment]
Not sure if you've seen this, but FYI https://hynek.me/articles/docker-uv/

**Comment by charliermarsh** [comment]
Hmm... I think we'd generally recommend using virtual environments here, so I don't know that I'd want a guide suggesting otherwise. Glad your issue was resolved here though.

**Comment by longqu** [comment]
inside the container, we should only have one set of python, so the virtual environment is not needed at all.
The python executable is preferred to be in the PATH directly.
