### ISSUE TITLE
Enable package overrides for 'tool install'

### ISSUE THREAD

**Issue by restlessronin** [astral-sh/uv#9517]
I have a CLI app that is currently being built by poetry (https://pypi.org/project/llm-context/). 'pipx' is used to install it. There are no dependency issues at either build or resolution times. And the package runs fine.

I want to be able to do a 'uv tool install' for this package.

There are no problems when I build using 'uv'. When I try to install, I get

```
 uv tool install "llm-context @ ."
  × No solution found when resolving dependencies:
  ╰─▶ Because tree-sitter-languages==1.10.2 has no wheels with a matching Python ABI tag
      and llm-context==0.1.1 depends on tree-sitter-languages==1.10.2, we can conclude that
      llm-context==0.1.1 cannot be used.
      And because only llm-context==0.1.1 is available and you require llm-context, we can
      conclude that your requirements are unsatisfiable.
```
Since I know it is currently running without apparent problems with the pipx install, I would like to force the override. Ideally I would do this at build time, rather than at install time.

I found this https://github.com/astral-sh/uv/pull/631 which seems to do what I want (although it's at install time), but this is for pip-install. Apparently the equivalent is not set up for tool install?

I'm wondering if there are plans to enable this for tools as well. As I said it's ideally something that goes into the metadata at build time, so that uv knows to override the dependency at install time.

Great project! Thanks for all the work.

**Comment by charliermarsh** [comment]
Hmm yeah, we probably need to accept `--with-overrides` or `--with-constraints` or something like that here. \cc @zanieb

**Comment by restlessronin** [comment]
Great.

'uv pip install" appears to work with project metadata, i.e. if I build with

```
[tool.uv]
override-dependencies = [
  "tree-sitter-languages==1.10.2"
]
```

in the 'pyproject.toml' file, I don't seem to need to specify overrides at install time. That would be the ideal solution.

**Comment by restlessronin** [comment]
ah. i thought the project metadata (including the override-dependencies) might be getting baked into the package at build time, and available to 'uv' at install time. i guess that's not what's happening here?

**Comment by charliermarsh** [comment]
Ah yeah, that metadata isn't available at `uv tool install` time if the package is coming from PyPI. It's not included in the distribution, since that piece is all standardized.

**Comment by charliermarsh** [comment]
I'm confused though, how / why does your package work if it has this problem? Why does `pipx` let you install it...?

**Comment by restlessronin** [comment]
I'm afraid I don't know enough about python installation to answer that question. I don't get any warnings from pipx install, and the package functionality works fine.

**Comment by charliermarsh** [comment]
My guess is that you're using different Python versions -- `tree-sitter-languages` doesn't have wheels for Python 3.13, but I'm guessing that's what you're using by default, whereas pipx is using some other, older Python version. What does ` uv tool install --python 3.12 "llm-context @ ."` give you?
