### ISSUE TITLE
`uv sync` removes editable install if `[build-system]` is not specified

### ISSUE THREAD

**Issue by randolf-scholz** [astral-sh/uv#9518]
```bash
uv pip install -e .  # ✅
uv lock --upgrade  # ✅
uv sync --upgrade  # ↯ removes main package
```

It seems this is because if `[build-system]` is missing, then `uv.lock` says `source = { virtual = "." }`, and with it `source = { editable = "." }`. (see comment by @atomiechen in https://github.com/astral-sh/uv/issues/1626#issuecomment-2394365983):

The lack of `[build-system]` should not prevent treating the package as editable. This is consistent with [PEP 518](https://peps.python.org/pep-0518/) and [PyPA specification](https://packaging.python.org/en/latest/specifications/pyproject-toml/)

> Build tools are expected to use the example configuration file above as their default semantics when a pyproject.toml file is not present.
> 
> Tools should not require the existence of the [build-system] table. A pyproject.toml file may be used to store configuration details other than build-related data and thus lack a [build-system] table legitimately. If the file exists but is lacking the [build-system] table then the default values as specified above should be used. If the table is specified but is missing required fields then the tool should consider it an error.

Alternatively, if this is not possible, it would make more sense if `uv` issued a warning/error when attempting to `uv pip install -e .` a package without `[build-system]`.

**Comment by charliermarsh** [comment]
This is intentional. Outside of the `uv pip` interface, we treat projects without a `[build-system]` as non-packages: https://docs.astral.sh/uv/concepts/projects/config/#build-systems.

**Comment by randolf-scholz** [comment]
> uv uses the presence of a build system to determine if a project contains a package that should be installed in the project virtual environment. _**If a build system is not defined, uv will not attempt to build or install the project itself, just its dependencies.**_ If a build system is defined, uv will build and install the project into the project environment.

But if that is the case, why does the following work?

```bash
mkdir myproject && cd myproject
uv init
mkdir -p src/foo
touch src/foo/__init__.py
uv venv --seed
source .venv/bin/activate
uv pip install -e .
python -c "import foo"
```

**Comment by charliermarsh** [comment]
That's a difference between the project APIs (where we use this behavior) and the `uv pip` CLI (where it would be "breaking" to do so, since it would be a significant divergence from pip).

**Comment by zanieb** [comment]
Notably, `uv pip install -e .` doesn't really mean anything if you don't want to install the project itself. Use `uv pip install -r ./pyproject.toml` instead.
