### ISSUE TITLE
Installing multiple projects in a single command issue

### ISSUE THREAD

**Issue by wkarwacki** [astral-sh/uv#9519]
```
$ uv --version
uv 0.5.4
```
Hey uv team! It's my first issue here, so firstly I would like to say that I love the work you're doing. 

In my current project we start migrating our build system to `uv`. We've encountered rather unexpected issue related to installing multiple projects dependencies at once like so:
```
uv pip install project_a project_b
```
or
```
uv pip install -r project_a/pyproject.toml -r project_b/pyproject.toml
```
Apparently, when doing so, `uv` picks up project's configuration from cwd. It may be the case however, that in order to install one of the projects' (`project_a` or `project_b`) dependencies, it has to refer to some specific `[uv.tool]` configurations, like defined source or index, lack of which (when installing like above) would lead to an error during installation. 

Currently we work around this issue by installing the dependencies twice, but I would imagine, that by default all configuration options should be picked up from relevant projects without need to provide any of:
```
--directory <DIRECTORY>                      Change to the given directory prior to running the command
--project <PROJECT>                          Run the command within the given project directory
--config-file <CONFIG_FILE>                  The path to a `uv.toml` file to use for configuration [env: UV_CONFIG_FILE=]
```
on the command-line explicitly.

**Comment by charliermarsh** [comment]
In the `uv pip` CLI, we don't read configuration from the target "projects" -- it's as if you passed `-r project_a/requirements.txt -r project_b/requirements.txt`. The configuration is instead from the current working directory. Have you tried using `--no-config`?

**Comment by wkarwacki** [comment]
@charliermarsh Thank you for quick answer.

> The configuration is instead from the current working directory. 

Could you explain the reason it's done this way? I find it inconvenient, as for instance, when installing dependencies in Dockerfile I need to set WORKDIR to project's dir, or `cd` to the python project in order to `uv pip install`. Also, there is a problem of installing multiple projects at once, as I've described above.

**Comment by charliermarsh** [comment]
What would be the alternative?

**Comment by charliermarsh** [comment]
Those commands aren't actually "the same", though. The former will resolve all the dependencies together; the latter will resolve and install the dependencies for `project_a`, then separately resolve and install all the dependencies for `project_b`. If we discover the configuration from both projects, we need some semantics for merging them. For example, what if they specify conflicting values for certain fields?

**Comment by zanieb** [comment]
We're unlikely to introduce `pyproject.toml` configuration awareness into the `uv pip` interface as the upstream (pip itself) is very opposed to doing so. It's possible we'll break from that in the future, but it would require a strong motivation.

Thanks for sharing your use-case <3
