### ISSUE TITLE
Difference in `uv run` behavior between GNU/Linux and Windows

### ISSUE THREAD

**Issue by sbellon** [astral-sh/uv#9574]
On GNU/Linux you can do

```
uv run --python 3.13 $SHELL
```

and inside the newly opened shell, the selected python is callable as its `bin` is added to `PATH`:

```
/home/user/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/bin
```

When doing the same on Windows, i.e.

```
uv run --python 3.13 cmd.exe
```

this does not work, even though `PATH` variable is also adjusted, but on Windows the `Scripts` folder is used instead:

```
C:\Users\user\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Scripts
```

and this folder only has the `.empty` file inside whereas the `python.exe` would be located one folder level higher.

My use case would be to call (platform-independently)

```
uv run --python 3.13 some_app
```

where `some_app` in turn expects a specific python version "to be available". `uv run` seems to be perfect for this use case, if only on Windows the `Scripts` part would be omitted.

Is this by intention or a bug?  Or am I misunderstanding things?

**Comment by charliermarsh** [comment]
I think this is an oversight.

**Comment by sbellon** [comment]
Thanks for confirming. An occasional fix for this will then be highly appreciated. :-)

**Comment by sbellon** [comment]
Not sure whether I know what I am doing, but this change seems to fix it for me:
```diff
--- a/crates/uv/src/commands/project/run.rs
+++ b/crates/uv/src/commands/project/run.rs
@@ -1016,7 +1016,11 @@ pub(crate) async fn run(
             .as_ref()
             .map(PythonEnvironment::scripts)
             .into_iter()
-            .chain(std::iter::once(base_interpreter.scripts()))
+            .chain(std::iter::once(if cfg!(windows) {
+                base_interpreter.data()
+            } else {
+                base_interpreter.scripts()
+            }))
             .map(PathBuf::from)
             .chain(
                 std::env::var_os(EnvVars::PATH)

```

**Comment by charliermarsh** [comment]
I think that works by "coincidence", my guess is that the data dir is the top-level dir.

**Comment by zanieb** [comment]
One guiding question: where does the `python.exe` live in unmanaged Python installations? Is it in `Scripts/`? Is it in the top-level directory?

**Comment by charliermarsh** [comment]
I believe it's the top-level directory. I checked on my Windows machine.

**Comment by sbellon** [comment]
But, in that case, is it then "by coincidence" or is it rather "by design"? ;-)

**Comment by zanieb** [comment]
Per https://docs.python.org/3.12/library/sysconfig.html#nt-user it seems okay to add the `data()` directory to the `PATH`. An alternative is that we generate a trampoline `python.exe` but that seems expensive without further justification. We probably want to include the `scripts()` directory too still though, in case it's populated with something.

**Comment by charliermarsh** [comment]
I think it's not the data dir -- it's the install dir. It seems like virtualenvs on Windows do use `./Scripts/python.exe`, but outside of virtual environments, the executables are placed in the install directory (i.e., the top-level), and both are added to PATH by the installer.

**Comment by zanieb** [comment]
I don't understand the distinction you're making. There is no "install directory" in the sysconfig paths and, from what I can tell, the data directory _is_ the install directory by definition?

**Comment by charliermarsh** [comment]
The "install directory" is the directory containing the Python installation. The "data directory" is some path that `sysconfig` tells you to look for data files in. I'm fairly certain they do not have to be the same by definition. Distributions can customize sysconfig paths however they want. By "install directory", I am quoting from the MSI README: https://github.com/python/cpython/blob/c4303763dac4494300e299e54c079a4a11931a55/Tools/msi/README.txt#L466

**Comment by zanieb** [comment]
> I'm fairly certain they do not have to be the same by definition

Yeah I'm not really sure. The `sysconfig` reference I linked to suggests that they're equivalent for all schemes. I imagine there's some way you could set it to a different directory but it seems unlikely in practice.

Regardless, the "install directory" seems correct to me. How are you going to retrieve it?

**Comment by charliermarsh** [comment]
I was considering: if the executable isn't in Scripts, add the executable's parent directory?

**Comment by sbellon** [comment]
I can confirm that this fixes my issue. Thanks for this lightnight fast fix. :-)
