### ISSUE TITLE
Function request: Dependency installation in virtual environment using soft connection

### ISSUE THREAD

**Issue by silent-rain** [astral-sh/uv#9592]
## Current Status

Although only one copy of the downloaded dependency library is retained globally, a separate dependency is installed in each virtual environment of the project, which takes up a lot of space.

## The problems we are facing

For example, in the "comfyui" drawing, the dependency library volume is expanding day by day, and it still consumes 13GB of memory. In the case of setting up multiple environments, the total volume will be even larger.
So, since there is already a copy of the dependency library globally, can soft links be used in a virtual environment? This can greatly reduce the occupation of space.
For example, in the frontend, "pnpm" also uses a soft connection, so not only does it execute extremely quickly in the "pnpm install" command, but also the "node_modules" volume is extremely small.
So, can we consider it?

**Comment by charliermarsh** [comment]
I believe we already have the behavior you're looking for. By default, we use copy-on-write links on macOS and hardlinks on Windows.

**Comment by silent-rain** [comment]
Yes, I just found what I was looking for

Very good



> [tool.uv]
link-mode = "symlink"

**Comment by charliermarsh** [comment]
I recommend against using `symlink` specifically. I think the hardlink mode should be better in just about every way.

**Comment by silent-rain** [comment]
I have set up multiple "comfyui" environments, each of which takes up a lot of space, so I have to find ways to alleviate this situation

**Comment by charliermarsh** [comment]
Hardlinks have the same effect though. The underlying files are the same, without copying.

**Comment by silent-rain** [comment]
Thank you very much for your guidance. 
I think I have discovered where the problem lies.
