### ISSUE TITLE
Monorepo packages

### ISSUE THREAD

**Issue by Dayof** [astral-sh/uv#9593]
I have this following structure on poetry:

```
[tool.poetry]
packages = [
  { include = "lib-io", from = "src/io" },
  { include = "transforms", from = "src/transforms" }
]
```

When I install my library, the io module is available when I try to import, example:

```
python -c "import lib_io"
```

Is it possible to do the same on uv?

I tried to do the following:

```
[tool.uv.sources]
lib-io = { path = "src/io" }
```

But it says that there is no module `lib-io`:

```
uv run python -c "import lib_io"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lib_io'
```

Note:
- I cannot add them as workspaces since they have dependencies conflicts.

**Comment by samypr100** [comment]
I think if you're using hatch as your build backend you can accomplish this via `tool.hatch.build.targets.wheel`

e.g.

```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/io", "src/transforms"]
````

**Comment by Dayof** [comment]
It worked! Thanks for the fast assistance :)
