### ISSUE TITLE
uv activate as a shortcode for `source .venv/bin/activate`

### ISSUE THREAD

**Issue by dmi3kno** [astral-sh/uv#9603]
I would appreciate a short command which could abstract the environment activation

```{bash}
uv activate [environment]
```
which would by default (without the environment specified) resolve to

```{bash}
source .venv/bin/activate
```

This would simplify the workflow and make `uv` easier to adopt in teaching.

**Comment by my1e5** [comment]
Duplicate of many
* https://github.com/astral-sh/uv/issues/8106
* https://github.com/astral-sh/uv/issues/8118
* https://github.com/astral-sh/uv/issues/9166

**Comment by zanieb** [comment]
Please read #9452 next time.

**Comment by dmi3kno** [comment]
I apologized. And I am sorry again. Please forgive me. I closed the issue within 15 min I think. I did do a search but failed to find it. **I am sorry**

**Comment by zanieb** [comment]
It's not a big deal, duplicates happen all the time. I'm referring you to #9452 as a resource — it includes a link to this specific request _because_ GitHub search frequently fails.
