### ISSUE TITLE
add a option that does NOT add uv.lock

### ISSUE THREAD

**Issue by DinhHuy2010** [astral-sh/uv#9632]
Hi, could uv add a option not creating a uv.lock file via cli arguments or config file?

**Comment by blueraft** [comment]
I think you can use the `--frozen` argument for this.

`uv add --frozen flask` doesn't create a lock file.

**Comment by charliermarsh** [comment]
What would the motivation be for doing this?

**Comment by DinhHuy2010** [comment]
Basically I am contributing to tqdm, and I use uv for handle dependencies.
I think that the tqdm developers are (maybe) not ready for using uv.
However, uv are creating uv.lock constantly
Previously, I just delete uv.lock file. That is annoying.
So add a option that not add uv.lock file (or if it exists, do not update the lock file) will be useful for me.

**Comment by zanieb** [comment]
I would recommend just adding the `uv.lock` file to a personal `.gitignore`

**Comment by zanieb** [comment]
i.e., in `<repo>/.git/info/exclude`

**Comment by DinhHuy2010** [comment]
> i.e., in `<repo>/.git/info/exclude`

yes this is what I using here
