### ISSUE TITLE
uv python list report error

### ISSUE THREAD

**Issue by cjdxhjj** [astral-sh/uv#9667]
when i run the uv python list
![Image](https://github.com/user-attachments/assets/71b49a78-02ae-4f88-85bd-2f98a4c01cbb)
i have install the python with windows store, the location at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2288.0_x64__qbz5n2kfra8p0

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/c5534248-8321-483f-abae-335040211884)

**Comment by cjdxhjj** [comment]
The path shown in the error message is the path where I installed the software last time.

**Comment by cjdxhjj** [comment]
the windows store install the python at appdata before, but now it at program files, i install the python first then install the uv
but the uv python list not working, is the uv read some configuration that broken ?

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/df9d8de0-8e45-4fb5-a4dc-23e39a732517)

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/875fb966-0cec-4f73-a0f5-52a842f952b2)

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/2d083112-0230-4cf0-9bb7-1dc3a5c368bd)
![Image](https://github.com/user-attachments/assets/66ee152a-b3af-4bff-9ab4-b9b117b2e117)

**Comment by cjdxhjj** [comment]
i have searched my register and found nothing about the error path

**Comment by charliermarsh** [comment]
Thanks. I _think_ we should be "skipping" that path but I need to double check.

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/89e963b0-9d6c-4f7f-9d8b-d6ee0005fdea)
when i upgrade to 0.5.7, it report that error

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/a05fd741-f912-4885-a0c1-10b160fcd6f9)
@charliermarsh

**Comment by cjdxhjj** [comment]
the issure not resolved
