### ISSUE TITLE
UV lists python interpreters but can't use them!

### ISSUE THREAD

**Issue by meitham** [astral-sh/uv#9668]
I'm on version uv 0.5.6 (b70c4f30e 2024-12-03) on windows
uv sees my python interpreters from the windows registry  

```
C:\Temp>uv python list
cpython-3.13.0+freethreaded-windows-x86_64-none    <download available>
cpython-3.12.7-windows-x86_64-none                 <download available>
cpython-3.12.2-windows-x86_64-none                 D:\apps\Python\Python312\python.exe
cpython-3.11.10-windows-x86_64-none                <download available>
cpython-3.10.15-windows-x86_64-none                <download available>
cpython-3.9.20-windows-x86_64-none                 <download available>
cpython-3.9.13-windows-x86_64-none                 D:\apps\python\Python39\python.exe
cpython-3.9.12-windows-x86_64-none                 C:\ProgramData\Miniconda3\python.exe
cpython-3.8.20-windows-x86_64-none                 <download available>
cpython-3.7.9-windows-x86_64-none                  <download available>
cpython-3.7.6-windows-x86_64-none                  C:\apps\python37\python.exe
pypy-3.10.14-windows-x86_64-none                   <download available>
pypy-3.9.19-windows-x86_64-none                    <download available>
pypy-3.8.16-windows-x86_64-none                    <download available>
pypy-3.7.13-windows-x86_64-none                    <download available>
```

But when I try and use one of them uv complains it does not exists

```
C:\Temp>uv venv --python 3.9.13 orion --seed --no-python-downloads
  x No interpreter found for Python 3.9.13 in managed installations, search path, or registry
```

I think the ``uv venv`` command does not use the same discover mechanism as the ``uv list``

**Comment by zanieb** [comment]
That's surprising. Can you share the `--verbose` logs for `uv venv`? It may be helpful to include trace logs which include additional information about interpreter selection `RUST_LOG=uv=trace`

**Comment by meitham** [comment]
sure, here's the verbose ``uv venv`` output

```
C:\Temp>uv venv --python 3.9.13 orion --seed --no-python-downloads -vvv
    0.000032s ←[1;34mDEBUG←[0m ←[2muv←[0m uv 0.5.6 (b70c4f30e 2024-12-03)
    0.001042s ←[1;34mDEBUG←[0m ←[2muv::commands::project←[0m Using Python request `3.9.13` from explicit request
    0.002170s ←[1;34mDEBUG←[0m ←[2muv_python::discovery←[0m Searching for Python 3.9.13 in managed installations, search path, or registry
    0.004699s ←[1;34mDEBUG←[0m ←[2muv_python::discovery←[0m Searching for managed installations at `C:\Users\mjamaa\AppData\Roaming\uv\python`
    0.008461s ←[1;34mDEBUG←[0m ←[2muv_python::discovery←[0m Found `cpython-3.12.2-windows-x86_64-none` at `D:\apps\Python\Python312\python.exe` (search path)
    0.008620s ←[1;34mDEBUG←[0m ←[2muv_python::discovery←[0m Skipping interpreter at `D:\apps\Python\Python312\python.exe` from search path: does not satisfy request `3.9.13`
    0.012016s ←[1;34mDEBUG←[0m ←[2muv_python::py_launcher←[0m Python interpreter in the registry is not executable: `Software\Python\PythonCore\3.9
  x No interpreter found for Python 3.9.13 in managed installations, search path, or registry
```

**Comment by aDotInTheVoid** [comment]
I'm running into a similar issue on macOS:

```
% uv --version
uv 0.5.6 (Homebrew 2024-12-03)
% cat ~/.config/uv/uv.toml
python-preference = "only-system"

% uv python list
cpython-3.13.0-macos-aarch64-none    /opt/homebrew/opt/python@3.13/bin/python3.13 -> ../Frameworks/Python.framework/Versions/3.13/bin/python3.13
cpython-3.12.8-macos-aarch64-none    /opt/homebrew/opt/python@3.12/bin/python3.12 -> ../Frameworks/Python.framework/Versions/3.12/bin/python3.12
cpython-3.9.6-macos-aarch64-none     /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -> ../../Library/Frameworks/Python3.framework/Versions/3.9/bin/python3
% uv python find '==3.13.0'
/opt/homebrew/opt/python@3.13/bin/python3.13
% uv python find '==3.12.8'
error: No interpreter found for Python ==3.12.8 in virtual environments or search path
```

Or with more logging:

```
% RUST_LOG=uv=trace uv python list
DEBUG uv 0.5.6 (Homebrew 2024-12-03)
DEBUG Searching for any Python interpreter in search path
TRACE Searching PATH for executables: python, python3, cpython, cpython3, pypy, pypy3, graalpy, graalpy3
TRACE Checking `PATH` directory for interpreters: /opt/homebrew/bin
TRACE Found possible Python executable: /opt/homebrew/bin/python3
TRACE Cached interpreter info for Python 3.13.0, skipping probing: /opt/homebrew/bin/python3
DEBUG Found `cpython-3.13.0-macos-aarch64-none` at `/opt/homebrew/bin/python3` (search path)
TRACE Found possible Python executable: /opt/homebrew/bin/python3.12
TRACE Cached interpreter info for Python 3.12.8, skipping probing: /opt/homebrew/bin/python3.12
DEBUG Found `cpython-3.12.8-macos-aarch64-none` at `/opt/homebrew/bin/python3.12` (search path)
TRACE Found possible Python executable: /opt/homebrew/bin/python3.13
TRACE Cached interpreter info for Python 3.13.0, skipping probing: /opt/homebrew/bin/python3.13
DEBUG Found `cpython-3.13.0-macos-aarch64-none` at `/opt/homebrew/bin/python3.13` (search path)
TRACE Checking `PATH` directory for interpreters: /opt/homebrew/sbin
TRACE Checking `PATH` directory for interpreters: /usr/local/bin
TRACE Checking `PATH` directory for interpreters: /System/Cryptexes/App/usr/bin
TRACE Checking `PATH` directory for interpreters: /usr/bin
TRACE Found possible Python executable: /usr/bin/python3
TRACE Querying interpreter executable at /usr/bin/python3
DEBUG Found `cpython-3.9.6-macos-aarch64-none` at `/usr/bin/python3` (search path)
TRACE Checking `PATH` directory for interpreters: /bin
TRACE Checking `PATH` directory for interpreters: /usr/sbin
TRACE Checking `PATH` directory for interpreters: /sbin
TRACE Checking `PATH` directory for interpreters: /Library/Apple/usr/bin
TRACE Checking `PATH` directory for interpreters: /Users/aloenr01/.cargo/bin
TRACE Checking `PATH` directory for interpreters: /Applications/iTerm.app/Contents/Resources/utilities
cpython-3.13.0-macos-aarch64-none    /opt/homebrew/opt/python@3.13/bin/python3.13 -> ../Frameworks/Python.framework/Versions/3.13/bin/python3.13
cpython-3.12.8-macos-aarch64-none    /opt/homebrew/opt/python@3.12/bin/python3.12 -> ../Frameworks/Python.framework/Versions/3.12/bin/python3.12
cpython-3.9.6-macos-aarch64-none     /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -> ../../Library/Frameworks/Python3.framework/Versions/3.9/bin/python3
% RUST_LOG=uv=trace uv python find '==3.12.8'
DEBUG uv 0.5.6 (Homebrew 2024-12-03)
DEBUG Using Python request `==3.12.8` from explicit request
DEBUG Searching for Python ==3.12.8 in virtual environments or search path
TRACE Searching PATH for executables: python3, python
TRACE Checking `PATH` directory for interpreters: /opt/homebrew/bin
TRACE Found possible Python executable: /opt/homebrew/bin/python3
TRACE Cached interpreter info for Python 3.13.0, skipping probing: /opt/homebrew/bin/python3
DEBUG Found `cpython-3.13.0-macos-aarch64-none` at `/opt/homebrew/bin/python3` (search path)
DEBUG Skipping interpreter at `/opt/homebrew/opt/python@3.13/bin/python3.13` from search path: does not satisfy request `==3.12.8`
TRACE Checking `PATH` directory for interpreters: /opt/homebrew/sbin
TRACE Checking `PATH` directory for interpreters: /usr/local/bin
TRACE Checking `PATH` directory for interpreters: /System/Cryptexes/App/usr/bin
TRACE Checking `PATH` directory for interpreters: /usr/bin
TRACE Found possible Python executable: /usr/bin/python3
TRACE Querying interpreter executable at /usr/bin/python3
DEBUG Found `cpython-3.9.6-macos-aarch64-none` at `/usr/bin/python3` (search path)
DEBUG Skipping interpreter at `/Applications/Xcode.app/Contents/Developer/usr/bin/python3` from search path: does not satisfy request `==3.12.8`
TRACE Checking `PATH` directory for interpreters: /bin
TRACE Checking `PATH` directory for interpreters: /usr/sbin
TRACE Checking `PATH` directory for interpreters: /sbin
TRACE Checking `PATH` directory for interpreters: /Library/Apple/usr/bin
TRACE Checking `PATH` directory for interpreters: /Users/aloenr01/.cargo/bin
TRACE Checking `PATH` directory for interpreters: /Applications/iTerm.app/Contents/Resources/utilities
error: No interpreter found for Python ==3.12.8 in virtual environments or search path
```

It looks like the `uv python list` code does this:

https://github.com/astral-sh/uv/blob/3aaa9594be4727fb4a6260b1cc5782eb66e47284/crates/uv-python/src/discovery.rs#L499-L501

where the `find_all_minor` means it can pick up on `/opt/homebrew/bin/python3.12`.

But when asking for `==3.12.8` specifically, it doesn't consider that `3.12` could be it:

https://github.com/astral-sh/uv/blob/3aaa9594be4727fb4a6260b1cc5782eb66e47284/crates/uv-python/src/discovery.rs#L579-L581

**Comment by zanieb** [comment]
@aDotInTheVoid that's unrelated — the above issue is related to the Windows registry — could you open a new issue instead?

@meitham There's an error

> Python interpreter in the registry is not executable: `Software\Python\PythonCore\3.9

This comes from the check at https://github.com/astral-sh/uv/blob/d0afd10ca4a7c6ebaacbe0a6188eec09d8f47022/crates/uv-python/src/py_launcher.rs#L66-L76

I'm not sure what would cause that, @konstin may know.

Does it work for other Python versions like 3.12?

**Comment by konstin** [comment]
Can you share the output of `Get-ChildItem -Path "HKCU:\Software\Python" -Recurse -Depth 2`?

Currently puzzled by how the 3.9.13 is shown in the list but then can't be used, we use the same code path for listing and deciding on which interpreter to execute.

**Comment by meitham** [comment]
Please see below my registry.  I think I see what the issue is, I have python 3.9.12 (miniconda) and python 3.9.13 (psf) but in the windows registry their patch version is omitted so they both appear as 3.9.  Though one was installed by admin so it went into current machine, and the other is in current user.


`

    Hive: HKEY_CURRENT_USER\Software\Python


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
PyLauncher                     InstallDir     : C:\Users\mjamaa\AppData\Local\Programs\Python\Launcher\                                                                                                                       
                               AssociateFiles : 1                                                                                                                                                                             
                               (default)      : C:\Users\mjamaa\AppData\Local\Programs\Python\Launcher\py.exe                                                                                                                 
PythonCore                     DisplayName : Python Software Foundation                                                                                                                                                       
                               SupportUrl  : https://www.python.org/                                                                                                                                                          


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
3.12                           DisplayName     : Python 3.12 (64-bit)                                                                                                                                                         
                               SupportUrl      : https://www.python.org/                                                                                                                                                      
                               Version         : 3.12.2                                                                                                                                                                       
                               SysVersion      : 3.12                                                                                                                                                                         
                               SysArchitecture : 64bit                                                                                                                                                                        


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore\3.12


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Help                                                                                                                                                                                                                          
Idle                           (default) : D:\apps\Python\Python312\Lib\idlelib\idle.pyw                                                                                                                                      
IdleShortcuts                  (default) : 1                                                                                                                                                                                  
InstalledFeatures              Shortcuts    : 3.12.2150.0                                                                                                                                                                     
                               exe          : 3.12.2150.0                                                                                                                                                                     
                               dev          : 3.12.2150.0                                                                                                                                                                     
                               lib          : 3.12.2150.0                                                                                                                                                                     
                               test         : 3.12.2150.0                                                                                                                                                                     
                               doc_shortcut : 3.12.2150.0                                                                                                                                                                     
                               doc          : 3.12.2150.0                                                                                                                                                                     
                               tcltk        : 3.12.2150.0                                                                                                                                                                     
                               pip          : 3.12.2150.0                                                                                                                                                                     
                               path         : 3.12.2150.0                                                                                                                                                                     
InstallPath                    (default)              : D:\apps\Python\Python312\                                                                                                                                             
                               ExecutablePath         : D:\apps\Python\Python312\python.exe                                                                                                                                   
                               WindowedExecutablePath : D:\apps\Python\Python312\pythonw.exe                                                                                                                                  
PythonPath                     (default) : D:\apps\Python\Python312\Lib\;D:\apps\Python\Python312\DLLs\                                                                                                                       


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
3.7                            DisplayName     : Python 3.7 (64-bit)                                                                                                                                                          
                               SupportUrl      : http://www.python.org/                                                                                                                                                       
                               Version         : 3.7.6                                                                                                                                                                        
                               SysVersion      : 3.7                                                                                                                                                                          
                               SysArchitecture : 64bit                                                                                                                                                                        


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore\3.7


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Help                                                                                                                                                                                                                          
Idle                           (default) : C:\apps\python37\Lib\idlelib\idle.pyw                                                                                                                                              
IdleShortcuts                  (default) : 1                                                                                                                                                                                  
InstalledFeatures              dev          : 3.7.6150.0                                                                                                                                                                      
                               Shortcuts    : 3.7.6150.0                                                                                                                                                                      
                               exe          : 3.7.6150.0                                                                                                                                                                      
                               lib          : 3.7.6150.0                                                                                                                                                                      
                               test         : 3.7.6150.0                                                                                                                                                                      
                               doc_shortcut : 3.7.6150.0                                                                                                                                                                      
                               doc          : 3.7.6150.0                                                                                                                                                                      
                               tools        : 3.7.6150.0                                                                                                                                                                      
                               tcltk        : 3.7.6150.0                                                                                                                                                                      
                               pip          : 3.7.6150.0                                                                                                                                                                      
InstallPath                    (default)              : C:\apps\python37\                                                                                                                                                     
                               ExecutablePath         : C:\apps\python37\python.exe                                                                                                                                           
                               WindowedExecutablePath : C:\apps\python37\pythonw.exe                                                                                                                                          
PythonPath                     (default) : C:\apps\python37\Lib\;C:\apps\python37\DLLs\                                                                                                                                       


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
3.9                            DisplayName     : Python 3.9 (64-bit)                                                                                                                                                          
                               SupportUrl      : https://www.python.org/                                                                                                                                                      
                               Version         : 3.9.13                                                                                                                                                                       
                               SysVersion      : 3.9                                                                                                                                                                          
                               SysArchitecture : 64bit                                                                                                                                                                        


    Hive: HKEY_CURRENT_USER\Software\Python\PythonCore\3.9


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Help                                                                                                                                                                                                                          
Idle                           (default) : D:\apps\python\Python39\Lib\idlelib\idle.pyw                                                                                                                                       
IdleShortcuts                  (default) : 1                                                                                                                                                                                  
InstalledFeatures              dev          : 3.9.13150.0                                                                                                                                                                     
                               Shortcuts    : 3.9.13150.0                                                                                                                                                                     
                               exe          : 3.9.13150.0                                                                                                                                                                     
                               lib          : 3.9.13150.0                                                                                                                                                                     
                               test         : 3.9.13150.0                                                                                                                                                                     
                               doc_shortcut : 3.9.1150.0                                                                                                                                                                      
                               doc          : 3.9.1150.0                                                                                                                                                                      
                               tools        : 3.9.13150.0                                                                                                                                                                     
                               tcltk        : 3.9.13150.0                                                                                                                                                                     
                               pip          : 3.9.13150.0                                                                                                                                                                     
InstallPath                    (default)              : D:\apps\python\Python39\                                                                                                                                              
                               ExecutablePath         : D:\apps\python\Python39\python.exe                                                                                                                                    
                               WindowedExecutablePath : D:\apps\python\Python39\pythonw.exe                                                                                                                                   
Modules                        (default) :                                                                                                                                                                                    
PythonPath                     (default) : D:\apps\python\Python39\Lib\;D:\apps\python\Python39\DLLs\                                                                                                                         


`

and 

`

    Hive: HKEY_LOCAL_MACHINE\Software\Python


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
ContinuumAnalytics             DisplayName : Continuum Analytics, Inc.                                                                                                                                                        
                               SupportUrl  : https://github.com/continuumio/anaconda-issues                                                                                                                                   


    Hive: HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Anaconda39-64                  DisplayName     : Anaconda py39_4.12.0                                                                                                                                                         
                               SupportUrl      : https://github.com/continuumio/anaconda-issues                                                                                                                               
                               Version         : py39_4.12.0                                                                                                                                                                  
                               SysVersion      : 3.9                                                                                                                                                                          
                               SysArchitecture : 64bit                                                                                                                                                                        


    Hive: HKEY_LOCAL_MACHINE\Software\Python\ContinuumAnalytics\Anaconda39-64


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Help                                                                                                                                                                                                                          
InstallPath                    (default)              : C:\ProgramData\Miniconda3                                                                                                                                             
                               ExecutablePath         : C:\ProgramData\Miniconda3\python.exe                                                                                                                                  
                               WindowedExecutablePath : C:\ProgramData\Miniconda3\pythonw.exe                                                                                                                                 
Modules                        (default) :                                                                                                                                                                                    
PythonPath                     (default) : C:\ProgramData\Miniconda3\Lib;C:\ProgramData\Miniconda3\DLLs                                                                                                                       


    Hive: HKEY_LOCAL_MACHINE\Software\Python


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
PythonCore                                                                                                                                                                                                                    


    Hive: HKEY_LOCAL_MACHINE\Software\Python\PythonCore


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
3.9                                                                                                                                                                                                                           


    Hive: HKEY_LOCAL_MACHINE\Software\Python\PythonCore\3.9


Name                           Property                                                                                                                                                                                       
----                           --------                                                                                                                                                                                       
Help                                                                                                                                                                                                                          
InstallPath                    (default) : C:\ProgramData\Miniconda3                                                                                                                                                          
Modules                        (default) :                                                                                                                                                                                    
PythonPath                     (default) : C:\ProgramData\Miniconda3\Lib;C:\ProgramData\Miniconda3\DLLs                                                                                                                       


`

**Comment by meitham** [comment]
Thank you for fixing this, and special thanks for fixing the colors issue ;-)
