### ISSUE TITLE
allow `uv lock` to fail when lock file is "corrupted"

### ISSUE THREAD

**Issue by Seluj78** [astral-sh/uv#9671]
I recently switched to using `0.5.6` and when I do a rebase and run `uv lock` to update it, it now fails with the error

```
error: Failed to parse `uv.lock`
  Caused by: TOML parse error at line 1356, column 1
     |
1356 | <<<<<<< Updated upstream
     | ^
invalid key
```

Which didn't happen before (I don't have the version in mind, sorry)

Could we get that back ?

**Comment by charliermarsh** [comment]
I see where you're coming from, but I think this is reasonable behavior (and is also what Cargo does, just as one data point). You should have the opportunity to resolve the conflicts yourself, or you can just `rm uv.lock`.

**Comment by Seluj78** [comment]
Yes I agree it's not reasonable, and it's also what `poetry` does, it throws an error if it cannot parse the `lock` file. I prefer it having it overwrite but alright :) I'll go back to `rm uv.lock` :)

**Comment by charliermarsh** [comment]
Thanks for understanding :)

**Comment by Seluj78** [comment]
Of course ! `uv` (and `ruff`) are the best tools I've used for a long time, and this minor thing isn't something you guys should spend time working on instead of great features ! Keep it up !

**Comment by charliermarsh** [comment]
Thank you so much 🙏
