### ISSUE TITLE
[Question]Is there any conditional package dependency setting when dev vs build

### ISSUE THREAD

**Issue by hawksung1** [astral-sh/uv#9675]
I have two packages in my project. However, they need to be deployed separately during actual deployment.
I am using them as shown below for debugging during development.
Is there a way to integrate them together at once?

when run build (for debugging)
```
[tool.uv.sources]
asdf = { workspace = true }
```

when build
```
[tool.uv.sources]
asdf = {path = "/tmp/asdf-0.1-py3-none-any.whl" }
```

**Comment by charliermarsh** [comment]
I think this is roughly the same as https://github.com/astral-sh/uv/issues/7945. Unfortunately there isn't a great way to do it today. I'm going to expand that issue.
