### ISSUE TITLE
Issue with uv backend to "sync"

### ISSUE THREAD

**Issue by franzhaas** [astral-sh/uv#9686]
Dear all,

![Image](https://github.com/user-attachments/assets/d67fc4de-cd24-4126-916a-7ea13ad75806)

There appears to be an issue with the uv backend when running "uv sync" in the directory of a library.

This surprised me as according to this https://github.com/astral-sh/uv/issues/8779 editable should already work...

Thanks,
Franz

**Comment by konstin** [comment]
You need to set `UV_PREVIEW=1` as environment variable to use the uv build backend preview by itself, and use `--preview` with all uv commands that use package with the uv build backend.

**Comment by zanieb** [comment]
@konstin can we have a better error here that suggests that? Or is it not worth the effort?

**Comment by konstin** [comment]
This is for early preview only and to avoid people from accidentally using the uv build backend before it's in a stable state, so it's not worth optimizing at this point.

**Comment by zanieb** [comment]
Won't it be in preview for a while? I have a pretty strong preference for having a clearer error message. It wasn't clear to me that this wasn't a bug. Would you mind if I implemented something?
