### ISSUE TITLE
[BUG]`--no-build-isolation` is invalid, UV_NO_BUILD_ISOLATION must be used

### ISSUE THREAD

**Issue by sdbds** [astral-sh/uv#9690]
UV version 0.5.6
`--no-build-isolation` is invalid, UV_NO_BUILD_ISOLATION must be used

**Comment by FishAlchemist** [comment]
To reproduce the problem, please provide an MRE.

**Comment by sdbds** [comment]
Sorry, the local reproduction failed, it seems to be okay now. It might be that I used the wrong command.
