### ISSUE TITLE
Limited Implementation of `tool.uv.conflicts`

### ISSUE THREAD

**Issue by NellyWhads** [astral-sh/uv#9699]
Currently, `tool.uv.conflicts` only supports `project.optional-dependencies.{extra}` and `dependency-groups.{group}`. Can we have support for `project.optional-dependencies.{group}` as well?

Docs link: https://docs.astral.sh/uv/concepts/projects/config/#conflicting-dependencies

**Comment by charliermarsh** [comment]
What is `project.optional-dependencies.{group}`?

**Comment by NellyWhads** [comment]
Am I blind ... are they just extras ...? 

https://hatch.pypa.io/1.9/config/dependency/#self-referential

**Comment by charliermarsh** [comment]
Haha. In that context, `awesome-project[crypto]` is referring to the `crypto` extra defined just above.

**Comment by NellyWhads** [comment]
I think they are. You right. I'm blind.

In this case, where can I learn about the difference between groups and extras, and when each should be used?

**Comment by NellyWhads** [comment]
Scratch that, figured it out: https://docs.astral.sh/uv/concepts/projects/dependencies/#dependency-tables

I've been staring at the screen too long. It's time for a nap. Thanks @charliermarsh

**Comment by charliermarsh** [comment]
No worries, glad it was easy to resolve :)
