### ISSUE TITLE
uvx not working on windows

### ISSUE THREAD

**Issue by pythonweb2** [astral-sh/uv#9742]
In the past two versions (0.5.6 and 0.5.7), I have been getting this error message when trying to use uvx:

```
PS> uvx --help
error: The system cannot find the file specified. (os error 2)
```

So I would assume this is some sort of bug, since it was working in the past for me.

Thanks!

**Comment by charliermarsh** [comment]
Hmm. My guess is that the install is in a weird state. We assume that `uv.exe` is next to `uvx.exe`, and that's the message I'd expect if `uv.exe` is no longer there. What does `where uvx` show? Is there a `uv.exe` next to it?

**Comment by pythonweb2** [comment]
Yeah I'm not quite sure how that happened, but this is what was happening:

```
PS> Get-Command uvx

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     uvx.exe                                            0.0.0.0    ~\.cargo\uvx.exe

PS> Get-Command uv

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     uv.exe                                             0.0.0.0    ~\.cargo\bin\uv.exe
```

I deleted `~\.cargo\uvx.exe` and now it works. Thanks!
