### ISSUE TITLE
uv add deletes 'root' comments from within the dependency-group section of pyproject.toml

### ISSUE THREAD

**Issue by dean-tate** [astral-sh/uv#9758]
uv version: 0.5.7

```
[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
[dependency-groups]
# These are our dev dependencies
dev = [
        "black",
]
# These are our test dependencies
test = [
        "pytest",
        "pytest-cov",
]
```
 
[tool.uv]
default-groups = ["dev", "test"]

Running `uv add --group dev isort` adds the isort dependency to the correct group, but all of the comment lines within the [dependency-groups] section are removed.

```
[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
[dependency-groups]
dev = [
        "black",
        "isort>=5.13.2",
]
test = [
        "pytest",
        "pytest-cov",
]
 
[tool.uv]
default-groups = ["dev", "test"]
```

Interestingly this doesn't occur for uv remove. 

There's another ticket about an issue with comments as well - could be worth grouping these. 

https://github.com/astral-sh/uv/issues/8982.

**Comment by charliermarsh** [comment]
Thanks, that's surprising!

**Comment by charliermarsh** [comment]
It looks like this is coming from `toml-edit`: https://github.com/toml-rs/toml/issues/818.
