### ISSUE TITLE
`uv pip compile` header does not include `--upgrade`

### ISSUE THREAD

**Issue by karthiknadig** [astral-sh/uv#9771]
![Image](https://github.com/user-attachments/assets/e9779236-22be-4676-8adf-c049209f0b21)

**Comment by FishAlchemist** [comment]
I don't see the point of adding ``--upgrade`` to the header, since it doesn't make any difference to the final result.
Unless you have specific cases where including ``--upgrade`` results in different outcomes, adding it will only cause unnecessary file changes.

By the way, I'm not part of the uv team. I'm just expressing my personal opinion, so whether or not this feature request should be implemented is not up to me.

**Comment by charliermarsh** [comment]
Yeah, I believe this is intentional.

**Comment by notatallshaw-gts** [comment]
> Unless you have specific cases where including `--upgrade` results in different outcomes

I don't have an opinion on including it / not including it, but there is a difference when an output file is specified and pre-populated. I found this a little confusing when first using `uv pip compile`, that it takes the contents of the output file as a starting solution and you need to explicitly call `--upgrade` to get a new solution.

E.g.

```
$ echo "pandas" | uv pip compile --exclude-newer 2023-01-01 --python 3.11 -o requirements.txt --annotation-style line -
Resolved 5 packages in 17ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --exclude-newer 2023-01-01 --python 3.11 -o requirements.txt --annotation-style line -
numpy==1.24.1             # via pandas
pandas==1.5.2
python-dateutil==2.8.2    # via pandas
pytz==2022.7              # via pandas
six==1.16.0               # via python-dateutil

$ echo "pandas" | uv pip compile --python 3.11 -o requirements.txt --annotation-style line -
Resolved 5 packages in 11ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --python 3.11 -o requirements.txt --annotation-style line -
numpy==1.24.1             # via pandas
pandas==1.5.2
python-dateutil==2.8.2    # via pandas
pytz==2022.7              # via pandas

$ echo "pandas" | uv pip compile --python 3.11 -o requirements.txt --annotation-style line --upgrade -
Resolved 6 packages in 141ms
# This file was autogenerated by uv via the following command:
#    uv pip compile --python 3.11 -o requirements.txt --annotation-style line -
numpy==2.2.0              # via pandas
pandas==2.2.3
python-dateutil==2.9.0.post0  # via pandas
pytz==2024.2              # via pandas
six==1.17.0               # via python-dateutil
tzdata==2024.2            # via pandas
```

**Comment by charliermarsh** [comment]
I would probably err on the side of removing `-o requirements.txt` from the header, actually.

**Comment by zanieb** [comment]
> I would probably err on the side of removing `-o requirements.txt` from the header, actually.

Wouldn't that make it hard to reproduce the file?

**Comment by charliermarsh** [comment]
Hmm, well what's the value in including it?

**Comment by zanieb** [comment]
So I can copy and paste the command :)

> If the aim is to reproduce, then you need to know if --upgrade was called or not...

I don't think so — you'll reproduce it without `--upgrade`. `--upgrade` is for mutating the file.

**Comment by notatallshaw-gts** [comment]
> So I can copy and paste the command :)
> 
> > If the aim is to reproduce, then you need to know if --upgrade was called or not...
> 
> I don't think so — you'll reproduce it without `--upgrade`. `--upgrade` is for mutating the file. Right?

I'm not sure what you mean, [as above](https://github.com/astral-sh/uv/issues/9771#issuecomment-2531991498) you get different results based on the contents of the output file and whether you call `--upgrade` or not.

If you want to be able to reproduce the same output with the same input, and the output file is an input (which is what I first found confusing about this command), then you need to know if `--upgrade` was called or not.

I guess the question is, what is the purpose of including the command? Copy and paste helper? Reproducibility? Copy pip-compile API? Or something else? 

I do actually have to do a bit of work in my script that calls `uv pip compile` so the the `-o {OUTPUT_PATH}` always looks the same, so I would be happy to delete the few lines that do that logic, but I don't care that much.
