### ISSUE TITLE
`uv pip compile` should have the option to use `uv.lock` as constraints file

### ISSUE THREAD

**Issue by fnep** [astral-sh/uv#9774]
We use the `pyproject.toml` to maintain dependencies of our project (which is not a library, but a product using libraries). 

To install the project we use `uv sync` or `uv pip install -r pyproject.toml`, but the final product is rolled out on servers where `uv` is not available, and so we need to compile a set of `requirements.txt` files for different features / extras when we "bundle" all the files.

For this, we use `uv pip compile` with `pyproject.toml` as source file, but for this the `uv.lock` file is ignored, what makes it hard to maintain  "stable" `requirements.txt` files.

The current workaround is to use the output of `uv export` as input for `--constraints`, but this feels like a hack.

```bash
uv export --all-extras | uv pip compile ---constraints - --output-file requirements.txt pyproject.toml
``` 

Instead, please allow giving `uv.lock` as constraints file to `uv pip compile` to make this easier to use it as a single source of truth.

```bash
uv pip compile --constraints uv.lock --output-file requirements.txt pyproject.toml
```

**Comment by fnep** [comment]
Its not the `uv export` itself, but more that we have to pipe it into another uv command as input.

**Comment by zanieb** [comment]
Thanks 👍 

We need to decide if we want to support this. It has other implications, like probably `--requirements` support too for consistency. I'm a little hesitant since `export` exists for this purpose.

**Comment by fnep** [comment]
Thank you for considering it.

I know feeding the information generated using a tool into the same tool again is not uncommon in Unix tools. But it is not very intuitive to use and understand.

I'm not entirely sure how much sense it makes to give a `uv.lock` file to `--requirements`. What the practical use case would be. The file is in its meaning very close to the constraints option, but not to the requirements option. For pip they share the same format, so maybe there is one.

**Comment by fnep** [comment]
Thinking about your comment, i assume i missed one very important detail. 

We do not need to run `uv pip compile` at all. The `uv export` with some options, will provide almost the same. There is no need for compile.

I think we can close this issue. Sorry for wasting your time.

**Comment by patrick-kidger** [comment]
I'd like to reopen this issue: I have a use for `uv pip compile foo bar --constraints uv.lock`, namely https://github.com/astral-sh/uv/issues/13245#issuecomment-2846861803 . This is useful as a way to ad-hoc include extra dependencies (e.g. a custom debugger for tackling a particular problem) without affecting the rest of the packages already available in an environment.
