### ISSUE TITLE
consider adding UV_OFFLINE environment variable

### ISSUE THREAD

**Issue by cataggar** [astral-sh/uv#9794]
I started using `uv` a few days ago. Amazing tool! I want to run a few commands in CI where the network is off. I can add `--offline` to the various commands, but a single `UV_OFFLINE` environment variable would make it easier. Just though I would add an issue for consideration. Tons of commands support `--offline`.

**Comment by zanieb** [comment]
Seems reasonable to me, see https://github.com/astral-sh/uv/pull/9795

**Comment by max-wittig** [comment]
What is the different to `UV_NO_SYNC=1`?

What other online actions exist?

**Comment by zanieb** [comment]
`uv add`, `uv pip install`, etc. are all "online" actions
