### ISSUE TITLE
feat: add a support for inheritance in dependency groups

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [astral-sh/uv#9806]
Normally I would make a base requirements file called "requirements-base.in" and then compile it and use it as a base file for all or most environments. For example in `django` projects, `django` will should be included in almost all dependency groups. dev, testing, prod but of course the user will choose in which dependency group django should be included. and I have looked at the docs [here](https://docs.astral.sh/uv/concepts/projects/dependencies/) and it doesn't seem to be supported out of the box.

What I think should be done is basically an `inherit` field in the `project` section and in the `dependency-groups` section and the value should be a list of dependency groups this should be inherited from. And  the dependencies defined in the dependency group should have higher priority over those defined in the base dependency groups. If you need any clarifications or suggestions I am here to help.

**Comment by notatallshaw-gts** [comment]
Does `uv` support `include-group`s? https://peps.python.org/pep-0735/#dependency-group-include

You get something very close to inheritance that way.

**Comment by ZeyadMoustafaKamal** [comment]
But this is not supported in the `[project]` section. for example here

```toml
[project]
name = "my project"
version = "0.1.0"
description = "my project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    {include = "base"}
]
```

I am getting this error
```
$ uv add django-guardian --group=base
error: Failed to parse: `pyproject.toml`
  Caused by: TOML parse error at line 8, column 5
  |
8 |     {include = "base"}
  |     ^^^^^^^^^^^^^^^^^^
invalid type: map, expected a string

```
can you get support for this as well ?

**Comment by ZeyadMoustafaKamal** [comment]
source https://peps.python.org/pep-0735/#use-cases-for-dependency-group-includes-from-project

**Comment by notatallshaw-gts** [comment]
> But this is not supported in the `[project]` section. for example here
> source https://peps.python.org/pep-0735/#use-cases-for-dependency-group-includes-from-project

You'll notice that is under the section "Deferred Ideas": https://peps.python.org/pep-0735/#deferred-ideas, meaning it is not part of the PEP 735 spec.

Adding new features to the `[project]` section would require a new specification and PEP and discussion would have to start at: https://discuss.python.org/c/packaging/14

See how lengthy and involved such discussions can get by looking at the PEP 735 discussion: https://discuss.python.org/t/pep-735-dependency-groups-in-pyproject-toml/39233

**Comment by ZeyadMoustafaKamal** [comment]
Thanks
