### ISSUE TITLE
[QUESTION] How to build whl file with uv that exist same name in pypi??

### ISSUE THREAD

**Issue by hawksung1** [astral-sh/uv#9816]
I am planning to create a project that uses a local .whl file with uv. 
However, there is a .whl file with the same name available on PyPI. 
For example, our pyproject.toml looks like this:

```
[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langflow-base",
]

[tool.uv.sources]
langflow-base = { path = "../../../tmp/langflow_base-0.1.1-py3-none-any.whl" }

```

After building the project with uv, when I try to install the generated .whl file from another location, it downloads the file from PyPI instead.
How can I configure the build process to prioritize the local .whl file?

Thanks for solving my problem

**Comment by zanieb** [comment]
A built package can't contain references to other wheels via a relative file path, that's sort of "by definition". 

At install time, you'd need to add an index containing a wheel for the package, e.g., with `--find-links <directory>`

**Comment by zanieb** [comment]
I'd recommend picking a unique name to avoid confusion though.

**Comment by hawksung1** [comment]
Thank you so much. I solved my problem using --find-links
