### ISSUE TITLE
error text provides bad command for additional information

### ISSUE THREAD

**Issue by hwine** [astral-sh/uv#9819]
While attempting to install the `aarch64` version of python, I received the following suggestions -- the first suggestion (`uv python help`) is both:
- a syntax error (as the second invocation shows)
- a reference error (there is no such documentation on the target syntax there)

Shell session:
```bash
❯ uv python install 3.13.1-windows-aarch64-none
error: `3.13.1-windows-aarch64-none` is not a valid Python download request; see `uv python help` for supported formats and `uv python list --only-downloads` for available versions

~
2 ❯ uv python help
error: unrecognized subcommand 'help'

Usage: uv.exe python [OPTIONS] <COMMAND>

For more information, try '--help'.

~
2 ❯ uv --version
uv 0.5.8 (80d41671b 2024-12-11)
```

This is on a Windows 11 arm64 machine (MS Surface X).

**Comment by zanieb** [comment]
Eek, sorry `uv help python`!

**Comment by hwine** [comment]
Thanks for the quick (instant?) response with the correct command!

I did come back to say I discovered from the _other_ suggestion (`uv python list --only-downloads`) that I'd misread the `uv python list` output, and _thought_ y'all were offering a windows arm64 version. Not yet -- `uv` found the arm64 version I'd manually installed from [python.org](https://python.org).

**Comment by zanieb** [comment]
You're welcome :)

Interesting, that's surprising. Can you open a new issue for that?
