### ISSUE TITLE
`Unexpected HTTP response: 503` running in Github CI workflow

### ISSUE THREAD

**Issue by DanielYang59** [astral-sh/uv#9831]
We have a [minimal setup of `uv` in Github workflow as](https://github.com/materialsproject/pymatgen/blob/653714e4fe6914a5b9bea6eef0f44da507db1a2f/.github/workflows/test.yml#L77-L78):
```
      - name: Install uv
        uses: astral-sh/setup-uv@v4
```

And noticed [the following error from CI workflow](https://github.com/materialsproject/pymatgen/actions/runs/12278923035/job/34261741997) (seemingly intermittent, but thought might be good to keep it tracked):

```
Run astral-sh/setup-uv@v4
  with:
    version: latest
    github-token: ***
    enable-cache: false
    cache-dependency-glob: **/uv.lock
    prune-cache: true
    ignore-nothing-to-cache: false
  env:
    PMG_MAPI_KEY: 
    MPLBACKEND: Agg
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
Downloading uv from "https://github.com/astral-sh/uv/releases/download/0.5.7/uv-x86_64-unknown-linux-gnu.tar.gz" ...
Unexpected HTTP response: 503
Waiting 20 seconds before trying again
Unexpected HTTP response: 503
Waiting 10 seconds before trying again
Error: Unexpected HTTP response: 503
```

**Comment by my1e5** [comment]
There might have been a short Github outage that occurred at 3.26 PM GMT. Your build failed at this time

<img width="438" alt="Image" src="https://github.com/user-attachments/assets/b4dbd226-b638-49e4-9875-7f5c36b0436e" />

and downdetector shows a spike in reports at this time too

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/49e67384-2317-4af8-9012-b4f6b9a9a6d1" />

**Comment by DanielYang59** [comment]
Cool thanks for letting me know, never knew about downdetector before but know it now :)
