### ISSUE TITLE
`uv python install` is unable to install python older than 3.7

### ISSUE THREAD

**Issue by jumper047** [astral-sh/uv#9833]
I used `pyenv` before `uv` to manage python interpreters, and `pyenv` was able to install any existing version. Minimal version `uv` can install is 3.7. Is there any technical reason for that (like, don't know, it is not possible to have prebuilt 3.5 in repos), or this was made intentionally to, for example, encourage usage of the actual python versions?

**Comment by zanieb** [comment]
Yeah we don't support older Python versions, they no longer get security fixes and it's not worth the effort to maintain the builds for them upstream. The Python build system changes between minor versions so the minor version range we support is relatively important from a technical maintenance perspective.

**Comment by zanieb** [comment]
There isn't a formal policy yet. They will probably be there for a long time, they're not much maintenance overhead. We drop versions upstream though, i.e., we don't do new builds of Python 3.8 anymore. As we improve the upstream builds, the maintenance overhead of supporting multiple distribution formats here will grow.

**Comment by zanieb** [comment]
The versions are hard-coded into uv though, so they'll be stable for a given uv version.
