### ISSUE TITLE
phantom UV_PROJECT_ENVIRONMENT value

### ISSUE THREAD

**Issue by superlopuh** [astral-sh/uv#9834]
I'm trying to run `uv sync` in a temporarily-created virtualenv, and am getting a weird warning:

```
$ echo $UV_PROJECT_ENVIRONMENT
> 
$ uv sync
> warning: `VIRTUAL_ENV=venvbla` does not match the project environment path `.venv` and will be ignored
> Resolved 138 packages in 7ms
> Audited 4 packages in 0.41ms
```

How do I get rid of this behaviour? I can't find where the project environment is set.

**Comment by zanieb** [comment]
Either `deactivate` or `unset VIRTUAL_ENV`

See https://docs.astral.sh/uv/concepts/projects/config/#project-environment-path

**Comment by zanieb** [comment]
Yeah, you'd set `UV_PROJECT_ENVIRONMENT`. We don't support using the "active" virtual environment, for various reasons. See https://github.com/astral-sh/uv/pull/6834

**Comment by Srivathsan-Srinivas** [comment]
@zanieb Can you please let me know how to set UV_PROJECT_ENVIRONMENT? I am on a mac. What is weird is this: my global python version is 3.11.5 and also my rag_3_env is 3.11.5. Why should uv complain?

```
(rag_3_env) Sri@MacBookPro rag_3 % uv sync
warning: `VIRTUAL_ENV=rag_3_env` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
Using CPython 3.11.5 interpreter at: /Users/Sri/.pyenv/versions/3.11.5/bin/python3.11
Creating virtual environment at: .venv
Resolved 1 package in 16ms
Audited in 0.15ms
(rag_3_env) Sri@MacBookPro rag_3 %
```

After reading through several posts in this and related issue: I tried these:

Checking pyproject.toml
```
(rag_3_env) Sri@MacBookPro rag_3 % cat pyproject.toml
[project]
name = "rag-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
```

```
(rag_3_env) Sri@MacBookPro rag_3 % uv add argparse
warning: `VIRTUAL_ENV=rag_3_env` does not match the project environment path `.venv` and will be ignored; use `--active` to target the active environment instead
Resolved 2 packages in 28ms
Prepared 1 package in 129ms
Installed 1 package in 4ms
 + argparse==1.4.0
```

```
(rag_3_env) Sri@MacBookPro rag_3 % uv add argparse --active
Resolved 2 packages in 7ms
Installed 1 package in 4ms
 + argparse==1.4.0
(rag_3_env) Sri@MacBookPro rag_3 %
```


Checking toml file again afer running with active.
```
(rag_3_env) Sri@MacBookPro rag_3 % more pyproject.toml
[project]
name = "rag-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
]
```

For more context: some of env are here:

```
(rag_3_env) Sri@MacBookPro .venv % more pyvenv.cfg
home = /Users/Sri/.pyenv/versions/3.11.5/bin
implementation = CPython
uv = 0.6.14
version_info = 3.11.5
include-system-site-packages = false
prompt = rag-3
```


But, then, somewhere, you had mentioned that you do not support `--active`. 

So, for a simple user like me, what must I do to avoid this warning and possible issues down the road? How to set UV_PROJECT_ENVIRONMENT? Where should I set it? In .zshrc ? And, set it to what?

Thanks for your help!
