### ISSUE TITLE
uv pip install report layout error

### ISSUE THREAD

**Issue by cjdxhjj** [astral-sh/uv#9859]
i have use uv init, uv add -r ./requement.txt to transform my project from requirment to uv use pyproject.toml to manager deps
![Image](https://github.com/user-attachments/assets/91c000cf-310c-4990-948e-41031d7e9bfa)
my project has that layout
when i install the deps. use uv venv and uv pip install . it report the error
![Image](https://github.com/user-attachments/assets/22aaad55-b6a2-488f-8d70-b742d0cbbd0a)
the project is web project and not to plan publish as a package

**Comment by charliermarsh** [comment]
You should use `uv sync` here, rather than `uv pip install .`. If you want to use `uv pip install`, it should be `uv pip instal -r pyproject.toml` since you don't want the project itself to be installed. But if you use `uv pip install`, you won't get the benefits of `uv.lock`.

**Comment by cjdxhjj** [comment]
i must delete the pyproject.toml, use this step to install deps
uv venv
uv add -r ./requirment.txt

**Comment by cjdxhjj** [comment]
i will have a try

**Comment by cjdxhjj** [comment]
it works, thanks @charliermarsh
