### ISSUE TITLE
UX: spurious output for `uv tool upgrade -p 3... --all`

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/uv#9869]
I just tried upgrading all my tools with the following command (which worked great !), and was curious to see what happened if I ran it twice in a row. I was pleasantly surprised that it correctly figured out nothing needed to be done instead of re-doing it, but also (very) mildly disappointed by the second message in the output:
```
❯ uv tool upgrade -p 3.13 --all
... # output not relevant here
❯ uv tool upgrade -p 3.13 --all
Nothing to upgrade
Upgraded tool environment for  to Python 3.13
```

This is an extremely minor annoyance which I hope is not blocking to anyone (and certainly isn't to me !), though when the user experience is consistently excellent, this level of detail still gets noticed. I also thought it might also be relatively easy to fix.

**Comment by charliermarsh** [comment]
Thank you, definitely!

**Comment by notatallshaw** [comment]
25 seconds:

```bash
$ curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/astral-sh/uv/issues/9869" |  jq -r '"ID\tUsername\tCreated_At", "\(.id)\t\(.user.login)\t\(.created_at)"'
ID      Username        Created_At
2738499379      neutrinoceros   2024-12-13T14:15:00Z

$ curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/astral-sh/uv/issues/9869/comments" |  jq -r '.[] | "\(.id)\t\(.user.login)\t\(.created_at)"'
2541555890      charliermarsh   2024-12-13T14:15:25Z
2541564001      neutrinoceros   2024-12-13T14:19:39Z
```

**Comment by neutrinoceros** [comment]
hahaha, well it *felt* even quicker
