### ISSUE TITLE
selected python version is not preserved on uv sync

### ISSUE THREAD

**Issue by mhechthz** [astral-sh/uv#9895]
I just started to check for uv as an alternative.

I face the problem, that, even if python 3.12. is stored in toml and lock file `uv sync` generates an environment with the current active python, e.g. 3.11.

I tried to predefine a fresh venv with python 3.12 but this is deleted on calling `uv sync`.

Since I'm new to uv it might be my fault. I'ts all very basic and I'm sure, there are solutions.

Maybe related, maybe a different problem: If i generate named venvs e.g. venv311 and venv312 `uv sync` also fails because there is no .venv directory.

**Comment by mhechthz** [comment]
Ok. The hint for  `uv python pin 3.12` did it. Since I found a related problem here I did not dig deeper in the web to find this. Sorry and thank you.

**Comment by charliermarsh** [comment]
Thanks for following up!
