### ISSUE TITLE
Feature Request: Command to Install All Dependencies Listed in pyproject.toml

### ISSUE THREAD

**Issue by dimanu-py** [astral-sh/uv#9900]
I've been using uv and really enjoy it, but I've noticed a missing feature that other package managers like pdm provide: a command to install all the dependencies listed in the pyproject.toml file.

When I clone a project, the first step is usually installing all dependencies. With pdm, for example, I can simply run `pdm install`, and it automatically creates a virtual environment and installs all the required dependencies. Additionally, this can be filtered to install only specific types of dependencies (e.g., production, dev).

I was expecting a similar feature in uv, but I couldn't find a way to install all dependencies directly from the pyproject.toml file. Having such a command would make project setup much easier and faster.

I think adding this command would improve the user experience for managing dependencies in projects.

Thank you for considering this!

**Comment by charliermarsh** [comment]
Are you looking for `uv sync`, maybe?

**Comment by j178** [comment]
`dependency-groups` are not included by default, you should try `uv lock --all-groups`

**Comment by zanieb** [comment]
Or, change your `default-groups` declaration.

**Comment by dimanu-py** [comment]
@j178 thanks for the help, that tag fixed the problem.

Turns out that with the version I was using that command didn't exist and had to upgrade uv 👍
