### ISSUE TITLE
resolver: requiring `PyQt5` produces non-portable locks

### ISSUE THREAD

**Issue by neutrinoceros** [astral-sh/uv#9907]
Ok this is a weird one. Let's start with what uv 0.5.9 does (or older versions too, as far as I could check):

```
mkdir test
cd test
uv init
uv add PyQt5
```

and let's look at the relevant portion of the resulting lock file. For context, `PyQt5-Qt5` is a dependency to `PyQt5`:
```
[[package]]
name = "pyqt5-qt5"
version = "5.15.15"
source = { registry = "https://pypi.org/simple" }
wheels = [
    { url = "https://files.pythonhosted.org/packages/4a/6e/a5789bac6310208756fc6a36fd7e01caa86ea6ae7abbb5922dcea003a215/PyQt5_Qt5-5.15.15-py3-none-macosx_10_13_x86_64.whl", hash = "sha256:eb74072935958a830887115b1de1ff26341fc2d5881b28129de39612b10a260e", size = 39147807 },
    { url = "https://files.pythonhosted.org/packages/92/4c/c9026ca280f2cd4bef562cfb0a5050eb23f1e7fe1b85aa8455eb6ea437bf/PyQt5_Qt5-5.15.15-py3-none-macosx_11_0_arm64.whl", hash = "sha256:f8b174725fbe29c1a22f8acce5798933a65c8a083f1d9833ff212479ec2b3c14", size = 36953104 },
    { url = "https://files.pythonhosted.org/packages/95/70/1ba9b828387f42e0812b496ed637a950bf57a5d59b844d034841e8f9fb4f/PyQt5_Qt5-5.15.15-py3-none-manylinux2014_x86_64.whl", hash = "sha256:611505d04ffb06a5e5bcf98f5ff0e4e15ba7785565ccbe7bd3b2e40642ea3bdd", size = 59827278 },
]
```
It is evident that the version that uv selected (the current latest) doesn't have wheels for windows. Unfortunately there a no source distribution either, so this lock file just doesn't port to windows.
Looking at https://pypi.org/simple/pyqt5-qt5/
> [PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl](https://files.pythonhosted.org/packages/62/09/99a222b0360616250fb2e6003a54e43a2a06b0774f0f8d5daafb86a2c375/PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl#sha256=76980cd3d7ae87e3c7a33bfebfaee84448fd650bad6840471d6cae199b56e154)
[PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/83/d4/241a6a518d0bcf0a9fcdcbad5edfed18d43e884317eab8d5230a2b27e206/PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl#sha256=1988f364ec8caf87a6ee5d5a3a5210d57539988bf8e84714c7d60972692e2f4a)
[PyQt5_Qt5-5.15.2-py3-none-win32.whl](https://files.pythonhosted.org/packages/1c/7e/ce7c66a541a105fa98b41d6405fe84940564695e29fc7dccf6d9e8c5f898/PyQt5_Qt5-5.15.2-py3-none-win32.whl#sha256=9cc7a768b1921f4b982ebc00a318ccb38578e44e45316c7a4a850e953e1dd327)
[PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl](https://files.pythonhosted.org/packages/37/97/5d3b222b924fa2ed4c2488925155cd0b03fd5d09ee1cfcf7c553c11c9f66/PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl#sha256=750b78e4dba6bdf1607febedc08738e318ea09e9b10aea9ff0d73073f11f6962)
[PyQt5_Qt5-5.15.11-1-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/e1/66/3f374e3f9e74c1bc5659c23f6312d12684d8f78782d3b51c874c3657fa69/PyQt5_Qt5-5.15.11-1-py3-none-macosx_11_0_arm64.whl#sha256=9bb0d816de8c003ce41881e39fe5d64c2cdf5e8ca96b6c016c34f8e0bdc30768)
[PyQt5_Qt5-5.15.11-py3-none-macosx_10_13_x86_64.whl](https://files.pythonhosted.org/packages/66/f5/0a684b2b33b1f1dceaf894d4e8a105f523bb08003f81c89a91e509c5f854/PyQt5_Qt5-5.15.11-py3-none-macosx_10_13_x86_64.whl#sha256=109c418d221538751e4d7755a81c978ee31abbd65facb3f1f361dca74a1b758a)
[PyQt5_Qt5-5.15.11-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/e0/ff/7ca1897bfb045562090491e3c368b3d2034dcdc04a92efae1e765564309a/PyQt5_Qt5-5.15.11-py3-none-macosx_11_0_arm64.whl#sha256=3cccb21942eb49d21fb0193f28e3e8ae3d35395f158e8a9d4d58e23efa3a2ea7)
[PyQt5_Qt5-5.15.12-py3-none-macosx_10_13_x86_64.whl](https://files.pythonhosted.org/packages/be/3c/0f2ab2ef3bdf93ddb6834540613add6fca9ba76de08deb4a2465bb108088/PyQt5_Qt5-5.15.12-py3-none-macosx_10_13_x86_64.whl#sha256=7adff02a33f2f82b409ca115d57fc7e39b22e673d29e35c9d2594164039f0f71)
[PyQt5_Qt5-5.15.12-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/46/c0/8d23f1e671fa63345d82852cf6734ade99f7dc69452ceed757afdcc6a868/PyQt5_Qt5-5.15.12-py3-none-macosx_11_0_arm64.whl#sha256=b4c56566683ae905d5f04dd6ab925f02a384d6ce5ff4986eea0720d453666c22)
[PyQt5_Qt5-5.15.13-py3-none-macosx_10_13_x86_64.whl](https://files.pythonhosted.org/packages/40/dc/96d9d0ba0d13256343b53efffe8729f278e62409ab4c937bb22e70ab98ac/PyQt5_Qt5-5.15.13-py3-none-macosx_10_13_x86_64.whl#sha256=92575a9e96a27c4ed67c56c7048ded7461a1655d5d21f0e05064664e6e9fcbdf)
[PyQt5_Qt5-5.15.13-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/c9/8b/4441c208c8ca29b50fab6467ebfa32b6401d16c5c915a031a48dc85dfa7a/PyQt5_Qt5-5.15.13-py3-none-macosx_11_0_arm64.whl#sha256=141859f2ffe04cc6c5db970e2b6ad9f98897805d886a14c52614e3799daab6d6)
[PyQt5_Qt5-5.15.14-py3-none-macosx_10_13_x86_64.whl](https://files.pythonhosted.org/packages/41/6c/fb7bfdf7345ef3ce8b1ed8ae67374cae177b0ea89928490de063932ae284/PyQt5_Qt5-5.15.14-py3-none-macosx_10_13_x86_64.whl#sha256=c89b35b2aaf24d2805cc76fe31880c77b7f7557db8aafb26f1015f1bba7031d6)
[PyQt5_Qt5-5.15.14-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/bf/b4/99c33cfe20b58426302783096a882a3defef0bc594c7891ff58c6122132c/PyQt5_Qt5-5.15.14-py3-none-macosx_11_0_arm64.whl#sha256=730da7e6a97f6bad1b6df21082fe625647730418bc83e20cbc2ff6401ed0a8be)
[PyQt5_Qt5-5.15.14-py3-none-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/2d/4c/5c9824e9844d03e2a32e7e89b28f7fd55765515dfabd4e4f2bb1f16a6d75/PyQt5_Qt5-5.15.14-py3-none-manylinux2014_x86_64.whl#sha256=aa3911276b1a1aa9b5b9cba687ef905faddd706980d34e234312591c3d3cbef8)
[PyQt5_Qt5-5.15.15-py3-none-macosx_10_13_x86_64.whl](https://files.pythonhosted.org/packages/4a/6e/a5789bac6310208756fc6a36fd7e01caa86ea6ae7abbb5922dcea003a215/PyQt5_Qt5-5.15.15-py3-none-macosx_10_13_x86_64.whl#sha256=eb74072935958a830887115b1de1ff26341fc2d5881b28129de39612b10a260e)
[PyQt5_Qt5-5.15.15-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/92/4c/c9026ca280f2cd4bef562cfb0a5050eb23f1e7fe1b85aa8455eb6ea437bf/PyQt5_Qt5-5.15.15-py3-none-macosx_11_0_arm64.whl#sha256=f8b174725fbe29c1a22f8acce5798933a65c8a083f1d9833ff212479ec2b3c14)
[PyQt5_Qt5-5.15.15-py3-none-manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/95/70/1ba9b828387f42e0812b496ed637a950bf57a5d59b844d034841e8f9fb4f/PyQt5_Qt5-5.15.15-py3-none-manylinux2014_x86_64.whl#sha256=611505d04ffb06a5e5bcf98f5ff0e4e15ba7785565ccbe7bd3b2e40642ea3bdd)

we can see that there are wheels for older versions on Windows (`PyQt5-Qt5==5.15.2`). Unfortunately *no* single version has wheels for all major platforms: `PyQt5-Qt5==5.15.2` misses a wheel for `macosx` + `arm64`.

My expectation would be that `uv`'s resolver could detect this problem and fork the requirements automatically, but it doesn't.
Admittedly this is an exceptional setup, and I would understand that it falls out of scope somehow, especially considering that it could be resolved downstream if `PyQt5-Qt5` just shipped more wheels. I just thought it was similar (at least in spirit) to the problem solved by https://github.com/astral-sh/uv/pull/9827, so I figured it was worth a shot.

Meanwhile, a usable workaround for me is to manually write the fork in my requirements as
```
"PyQt5-Qt5==5.15.2 ; platform_system == 'Windows'",
"PyQt5-Qt5>=5.15.14 ; platform_system != 'Windows'",
```
which I can hide away from users into a dependency group (where a user-visible requirement would be much more inconvenient).

**Comment by charliermarsh** [comment]
Thanks! This is another case of #9711: for packages that lack source distributions, we can end up with "incomplete" resolutions.

**Comment by neutrinoceros** [comment]
Oh, sorry I missed it ! Of course, feel free to close this one as a dup'
Thanks !

**Comment by charliermarsh** [comment]
I'll merge into that issue. I'm thinking about that problem now.
