### ISSUE TITLE
`uv run` with environment?

### ISSUE THREAD

**Issue by ameya98** [astral-sh/uv#9939]
I created two environments `.venv` and `.venv-analysis` in the same folder.
I activated `.venv-analysis` but when I try running this:
```bash
$ uv run -m pip install wheel pyemma
warning: `VIRTUAL_ENV=.venv-analysis` does not match the project environment path `.venv` and will be ignored
...
```
it seems like `uv` still runs the environment under `.venv`? I would like `uv run` to use the currently activated environment.

**Comment by zanieb** [comment]
I think you want `uv run --no-project ...`

**Comment by ameya98** [comment]
Thank you! This was a bit confusing for me, because I didn't understand the single project <-> single virtualenv philosophy that `uv` has.
