### ISSUE TITLE
uv sync dosn't install anything

### ISSUE THREAD

**Issue by cjdxhjj** [astral-sh/uv#9964]
![Image](https://github.com/user-attachments/assets/780fb5f3-6aff-4395-b175-703b086acd75)

**Comment by cjdxhjj** [comment]
i use uv sync first and run the app, it report no module found, then i check the sitepackages, and found nothing
then i use uv pip install, 
![Image](https://github.com/user-attachments/assets/af2cc3af-ed5d-4ed6-abdc-4d59d057a87c)

![Image](https://github.com/user-attachments/assets/e4050ec1-8aaa-4cbb-a570-39084f282432)

**Comment by konstin** [comment]
Can you share `uv sync -v`? Please use a text copy (e.g. https://gist.github.com/) instead of screenshots.

**Comment by zanieb** [comment]
(See #9452 for general guidelines on how to report issues)

**Comment by cjdxhjj** [comment]
uv 0.5.8
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/8fdd7c73-19e4-4a5d-9df8-1b45f13e64f1)

**Comment by cjdxhjj** [comment]
[log.txt](https://github.com/user-attachments/files/18173091/log.txt)

**Comment by cjdxhjj** [comment]
@konstin @zanieb

**Comment by zanieb** [comment]
Have you configured a build system? https://docs.astral.sh/uv/concepts/projects/config/#build-systems

**Comment by zanieb** [comment]
Please take more time with your responses, you need to explain _way_ more or we cannot help you.

**Comment by cjdxhjj** [comment]
the pyproject.toml is here
[pyproject.txt](https://github.com/user-attachments/files/18173327/pyproject.txt)

**Comment by cjdxhjj** [comment]
yes, it was config as 
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

**Comment by zanieb** [comment]
It looks like you're in a workspace member and we're syncing the root?

```
DEBUG Found project root: `/data0/langflow/src/backend/base`
DEBUG Found workspace root: `/data0/langflow`
```

Are the packages in `/data0/langflow/.venv`?

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/fa101974-c086-422d-8c33-af9c13556374)
/data0/langflow/.venv exisit, but the package is empty, and that was the wrong path

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/c398634b-d578-4800-8ed5-59048236d2bc)
the project root path is not the python project root

**Comment by cjdxhjj** [comment]
![Image](https://github.com/user-attachments/assets/87d6d630-be70-4c65-b08f-f0ef660d11a8)
![Image](https://github.com/user-attachments/assets/7eca790f-a583-48b0-8308-4a80b87fa8b7)
![Image](https://github.com/user-attachments/assets/fb6a462c-d5ab-4300-8347-79d5816f0935)

**Comment by cjdxhjj** [comment]
Sorry, I made a mistake。 the /data0/langflow package installed. the machine is another one
![Image](https://github.com/user-attachments/assets/03d1fc5f-0669-47d5-9fd5-c726a947682f)

**Comment by cjdxhjj** [comment]
but the package install on the wrong path.

**Comment by zanieb** [comment]
What's the `pyproject.toml` content at `/data0/langflow`?

**Comment by cjdxhjj** [comment]
there is no pyproject.toml on the path /data0/langflow

**Comment by cjdxhjj** [comment]
[tool.uv.sources]
langflow-base = { workspace = true }
langflow = { workspace = true }

[tool.uv.workspace]
members = ["src/backend/base", "."]

[tool.hatch.build.targets.wheel]
packages = ["src/backend/langflow"]

[project]
name = "langflow"
version = "1.1.1"
description = "A Python package with a built-in web application"
requires-python = ">=3.10,<3.14"
license = "MIT"
keywords = ["nlp", "langchain", "openai", "gpt", "gui"]
readme = "README.md"
maintainers = [
    { name = "Carlos Coelho", email = "carlos@langflow.org" },
    { name = "Cristhian Zanforlin", email = "cristhian.lousa@gmail.com" },
    { name = "Gabriel Almeida", email = "gabriel@langflow.org" },
    { name = "Igor Carvalho", email = "igorr.ackerman@gmail.com" },
    { name = "Lucas Eduoli", email = "lucaseduoli@gmail.com" },
    { name = "Otávio Anovazzi", email = "otavio2204@gmail.com" },
    { name = "Rodrigo Nader", email = "rodrigo@langflow.org" },
    { name = "Italo dos Anjos", email = "italojohnnydosanjos@gmail.com" },
]

# Define your main dependencies here
dependencies = [
    "langflow-base==0.1.1",
    "beautifulsoup4==4.12.3",
    "google-search-results>=2.4.1,<3.0.0",
    "google-api-python-client==2.154.0",
    "huggingface-hub[inference]>=0.23.2,<1.0.0",
    "networkx==3.4.2",
    "fake-useragent==1.5.1",
    "pyarrow==17.0.0",
    "wikipedia==1.4.0",
    "qdrant-client==1.9.2",
    "weaviate-client==4.9.6",
    "faiss-cpu==1.9.0.post1",
    "types-cachetools==5.5.0.20240820",
    "pymongo==4.10.1",
    "supabase==2.6.0",
    "certifi>=2023.11.17,<2025.0.0",
    "certifi==2024.8.30",
    "fastavro==1.9.7",
    "redis==5.2.1",
    "metaphor-python==0.1.23",
    'pywin32>=306,<307; sys_platform == "win32"',
    "langfuse==2.53.9",
    "metal_sdk==2.5.1",
    "MarkupSafe==3.0.2",
    "boto3==1.34.162",
    "numexpr==2.10.2",
    "qianfan==0.3.5",
    "pgvector==0.3.6",
    "langchain==0.3.10",
    "elasticsearch==8.16.0",
    "pytube==15.0.0",
    "dspy-ai==2.5.41",
    "assemblyai==0.35.1",
    "litellm==1.54.1",
    "chromadb==0.5.23",
    "zep-python==2.0.2",
    "youtube-transcript-api==0.6.3",
    "Markdown==3.7",
    "upstash-vector==0.6.0",
    "GitPython==3.1.43",
    "kubernetes==31.0.0",
    "json_repair==0.30.3",
    "langwatch==0.1.16",
    "langsmith==0.1.147",
    "yfinance==0.2.50",
    "wolframalpha==5.1.3",
    "astra-assistants[tools]~=2.2.6",
    "composio-langchain==0.5.42",
    "spider-client==0.1.24",
    "nltk==3.9.1",
    "lark==1.2.2",
    "jq==1.8.0",
    "pydantic-settings==2.4.0",
    "ragstack-ai-knowledge-store==0.2.1",
    "duckduckgo_search==6.3.7",
    "opensearch-py==2.8.0",
    "langchain-google-genai==2.0.6",
    "langchain-cohere==0.3.3",
    "langchain-anthropic==0.3.0",
    "langchain-astradb==0.5.2",
    "langchain-openai==0.2.12",
    "langchain-google-vertexai==2.0.7",
    "langchain-groq==0.2.1",
    "langchain-pinecone==0.2.0",
    "langchain-mistralai==0.2.3",
    "langchain-chroma==0.1.4",
    "langchain-aws==0.2.7",
    "langchain-unstructured==0.1.5",
    "langchain-milvus==0.1.7",
    "langchain-mongodb==0.2.0",
    "langchain-nvidia-ai-endpoints==0.3.5",
    "langchain-google-calendar-tools==0.0.1",
    "langchain-google-community==2.0.3",
    "langchain-elasticsearch==0.3.0",
    "langchain-ollama==0.2.1",
    "langchain-community~=0.3.10",
    "sqlalchemy[aiosqlite,postgresql_psycopg2binary,postgresql_psycopgbinary]>=2.0.36,<3.0.0",
    "atlassian-python-api==3.41.16",
    "mem0ai==0.1.34",
    "needle-python>=0.4.0",
    "aiofile>=3.9.0,<4.0.0",
    "sseclient-py==1.8.0",
    "arize-phoenix-otel>=0.6.1",
    "openinference-instrumentation-langchain==0.1.29",
    "crewai~=0.86.0",
    "ag2>=0.3.2",
]

[project.urls]
Repository = "https://github.com/langflow-ai/langflow"
Documentation = "https://docs.langflow.org"

[project.optional-dependencies]
deploy = [
    "celery[redis]>=5.3.6",
    "flower>=2.0.0"
]
couchbase = [
    "couchbase>=4.2.1"
]
cassio = [
    "cassio>=0.1.7"
]
local = [
    "llama-cpp-python~=0.2.0",
    "sentence-transformers>=2.3.1",
    "ctransformers>=0.2.10"
]
clickhouse-connect = [
    "clickhouse-connect==0.7.19"
]

[project.scripts]
langflow = "langflow.__main__:main"

[tool.uv]
dev-dependencies = [
    "pytest-instafail>=0.5.0",
    "types-redis>=4.6.0.5",
    "ipykernel>=6.29.0",
    "mypy>=1.11.0",
    "ruff>=0.8.2,<0.9.0",
    "httpx>=0.27.0",
    "pytest>=8.2.0",
    "types-requests>=2.32.0",
    "requests>=2.32.0",
    "pytest-cov>=5.0.0",
    "pandas-stubs>=2.1.4.231227",
    "types-pillow>=10.2.0.20240213",
    "types-pyyaml>=6.0.12.8",
    "types-python-jose>=3.3.4.8",
    "types-passlib>=1.7.7.13",
    "pytest-mock>=3.14.0",
    "pytest-xdist>=3.6.0",
    "types-pywin32>=306.0.0.4",
    "types-google-cloud-ndb>=2.2.0.0",
    "pytest-sugar>=1.0.0",
    "respx>=0.21.1",
    "pytest-asyncio>=0.23.0",
    "pytest-profiling>=1.7.0",
    "pre-commit>=3.7.0",
    "vulture>=2.11",
    "dictdiffer>=0.9.0",
    "pytest-split>=0.9.0",
    "pytest-flakefinder>=1.1.0",
    "types-markdown>=3.7.0.20240822",
    "packaging>=24.1,<25.0",
    "asgi-lifespan>=2.1.0",
    "pytest-github-actions-annotate-failures>=0.2.0",
    "pytest-codspeed>=3.0.0",
    "blockbuster>=1.3.2,<1.4",
    "types-aiofiles>=24.1.0.20240626",
]


[tool.codespell]
skip = '.git,*.pdf,*.svg,*.pdf,*.yaml,*.ipynb,poetry.lock,*.min.js,*.css,package-lock.json,*.trig.,**/node_modules/**,./stuff/*,*.csv'
# Ignore latin etc
ignore-regex = '.*(Stati Uniti|Tense=Pres).*'


[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "integration"]
console_output_style = "progress"
filterwarnings = ["ignore::DeprecationWarning", "ignore::ResourceWarning"]
log_cli = true
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
markers = ["async_test", "api_key_required"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
command_line = """
    -m pytest --ignore=tests/integration
    --cov --cov-report=term --cov-report=html
    --instafail -ra -n auto -m "not api_key_required"
"""
source = ["src/backend/base/langflow/"]
omit = ["*/alembic/*", "tests/*", "*/__init__.py"]


[tool.coverage.report]
sort = "Stmts"
skip_empty = true
show_missing = false
ignore_errors = true


[tool.coverage.html]
directory = "coverage"


[tool.ruff]
exclude = ["src/backend/base/langflow/alembic/*"]
line-length = 120

[tool.ruff.lint]
pydocstyle.convention = "google"
select = ["ALL"]
ignore = [
    "C90", # McCabe complexity
    "CPY", # Missing copyright
    "COM812", # Messes with the formatter
    "ERA", # Eradicate commented-out code
    "FIX002", # Line contains TODO
    "ISC001", # Messes with the formatter
    "PERF203", # Rarely useful
    "PLR09", # Too many something (arg, statements, etc)
    "RUF012", # Pydantic models are currently not well detected. See https://github.com/astral-sh/ruff/issues/13630
    "TD002", # Missing author in TODO
    "TD003", # Missing issue link in TODO
    "TRY301", # A bit too harsh (Abstract `raise` to an inner function)

    # Rules that are TODOs
    "ANN",
]

# Preview rules that are not yet activated
external = ["RUF027"]

[tool.ruff.lint.per-file-ignores]
"scripts/*" = [
    "D1",
    "INP",
    "T201",
]
"src/backend/tests/*" = [
    "D1",
    "PLR2004",
    "S101",
    "SLF001",
]

[tool.mypy]
plugins = ["pydantic.mypy"]
follow_imports = "skip"
disable_error_code = ["type-var"]
namespace_packages = true
mypy_path = "langflow"
ignore_missing_imports = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

**Comment by cjdxhjj** [comment]
[pyproject.toml.txt](https://github.com/user-attachments/files/18174289/pyproject.toml.txt)

**Comment by cjdxhjj** [comment]
the repo is here https://github.com/langflow-ai/langflow

**Comment by zanieb** [comment]
This is working as intended. The project is configured as a workspace member https://github.com/langflow-ai/langflow/blob/5a8d73c5b29d8f496bc02d8ef2d3a6dfe3c2e0c0/pyproject.toml#L5-L6 — it's intentional that the workspace root us used.

**Comment by cjdxhjj** [comment]
thanks @zanieb , @konstin
