### ISSUE TITLE
How to use uv with alembic?

### ISSUE THREAD

**Issue by raibann** [astral-sh/uv#9966]
<img width="407" alt="Image" src="https://github.com/user-attachments/assets/0a9abe3f-c6fe-4e65-890e-d043fdcb71d1" />
it not work how ever put it in package or project it still not work
- dep:
 alembic
sqlachemy
- project type:( monorepo )

**Comment by flyaroundme** [comment]
How do you launch it?

**Comment by samypr100** [comment]
In a project setup like this, you can use `uv run alembic <args>` assuming it's part of your lock dependencies.
