### ISSUE TITLE
uv publish does not read environment variables

### ISSUE THREAD

**Issue by fleetingbytes** [astral-sh/uv#9997]
I have the environment variables `UV_PUBLISH_URL` and `UV_PUBLISH_TOKEN` set to my corporate PyPI package registry and my authentication token. When I run `uv publish dist/*`, uv tries to upload it to pypi.org:

```
$ uv publish dist/*
warning: `uv publish` is experimental and may change without warning
Publishing 2 files https://upload.pypi.org/legacy/
Enter username ('__token__' if using a token):
```

When I run `uv publish --publish-url=$UV_PUBLISH_URL --token=$UV_PUBLISH_TOKEN dist/*` then everything is fine and the package gets published in my corporate package registry (output redacted).

```
$ uv publish --publish-url=$UV_PUBLISH_URL --token=$UV_PUBLISH_TOKEN dist/*
warning: `uv publish` is experimental and may change without warning
Publishing 2 files https://<corporate-gitlab-host>/api/v4/projects/<project-id>/packages/pypi
Uploading <file-name>
```

I can't imagine that there would be such bug, but maybe I missed something when reading the uv documentation. 

I use uv 0.5.10 (294da5261 2024-12-17) on Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

**Comment by fleetingbytes** [comment]
Thank you, that was exactly the issue, they were only set for the shell. After export it works as expected. 🙏🏻

**Comment by nathanscain** [comment]
Awesome - happy to help 🤙

**Comment by zanieb** [comment]
Thanks @nathanscain !
