### ISSUE TITLE
fork-strategy requires-python produces unexpected results with repeated dependencies

### ISSUE THREAD

**Issue by alex** [astral-sh/uv#9998]
Hello!

I'm playing with using `fork-strategy` to replace our current `tool.uv.environments`, however it doesn't seem to be working due to some dependencies being repeated.

To reproduce:

```
$ echo -e "nox >=2024.04.15\nnox[uv] >=2024.03.02; python_version >= '3.8'" | uv pip compile --universal -p 3.7 -
```

If you look at the result, you'll see that there is a single version of `argcomplete==3.1.2`. However, what I'd expect to see is:

```
argcomplete==3.1.2 ; python_full_version < '3.8'
    # via nox
argcomplete==3.5.2 ; python_full_version >= '3.8'
    # via nox
```

When I do a more minimal test (`echo 'nox' | uv pip compile --universal -p 3.7 -`), I see the expected behavior.

**Comment by charliermarsh** [comment]
Thanks yeah, I see the issue here. It should be an easy fix, I'm just evaluating the fixture changes to make sure it's correct.

**Comment by alex** [comment]
Great, thanks!

**Comment by notatallshaw-gts** [comment]
FWIW, I was also going to report this, I was surprised to see no resolution difference between the two fork strategies when I threw very complex resolutions at them, but my resolutions were too complex to produce a useful MRE 😰
